### ISSUE TITLE
Alternative installation method

### ISSUE THREAD

**Issue by auroua** [openvinotoolkit/cvat#1065]
I have built this tool from this morning and still can not finish. The network connection is quite unstable. I have retried again and again.

**Comment by nmanovic** [comment]
@auroua , definitely. We are working to implement several alternative approaches to install or use the tool.

**Comment by bsekachev** [comment]
@azhavoro Do you think publishing CVAT on dockerhub closes the issue?

**Comment by azhavoro** [comment]
> @azhavoro Do you think publishing CVAT on dockerhub closes the issue?

I think that the described problem should be fixed, let's close the issue.
