### ISSUE TITLE
CVAT deployment in Kubernetes

### ISSUE THREAD

**Issue by Rub21** [openvinotoolkit/cvat#1087]
Has anybody deployed  CVA in Kubernetes? is there any repo? It would be good to cooperate with it

**Comment by nmanovic** [comment]
Please search in gitter. The topic was discussed a couple of times. I will keep the issue open till we have a document which describe how to do that.

**Comment by bhack** [comment]
Can we use [Kompose](https://github.com/kubernetes/kompose/blob/master/docs/user-guide.md) to publish an official helm chart?

**Comment by Keramblock** [comment]
I dont think that publish just pure kubernetes files is usable for us or other users, could you please consider creating a helm chart? That will be way more user friendly =) I can try to create draft chart

**Comment by azhavoro** [comment]
> I dont think that publish just pure kubernetes files is usable for us or almost any other users, could you please consider creating a helm chart? That will be way more user friendly =) I can try to create draft chart if you want me to

Hi, it would be awesome.

**Comment by Keramblock** [comment]
will try on next week then

**Comment by Keramblock** [comment]
[Draft MR](https://github.com/openvinotoolkit/cvat/pull/3102)

**Comment by Keramblock** [comment]
Could please anybody take a look?

**Comment by jeffliao888** [comment]
I had installed CVAT 1.7 in K8s successful , please check the follow URL:
https://github.com/openvinotoolkit/cvat/pull/1962/files#diff-8a70bef46ce370fa3873af3e98daef813efc8fadaf6271ef71f3aa2aad8162ec
