### ISSUE TITLE
Keep frame order the same as remote files array from API.

### ISSUE THREAD

**Issue by svenvanbuurennl** [openvinotoolkit/cvat#1092]
When adding remote files to a task via the REST API, it would be beneficial to keep the resulting frame order the same as the order of the provided remote files array.

**Comment by azhavoro** [comment]
CVAT sorts file names inside, you can sort it before task creating too. Sorting in this case is needed to be consistent with other types of data from which you can create a task (archive or share for example).

**Comment by azhavoro** [comment]
I will close the issue. Don't hesitate to reopen the issue if you still have questions.

**Comment by svenvanbuurennl** [comment]
@azhavoro I would like this issue to be labeled as an enhancement. I was advised by Boris Sekachev @bsekachev that I should open an issue even though it is not possible to keep the frame order the same with the current implementation, "We might consider it, because it seems to be a frequent problem for users.".

**Comment by nmanovic** [comment]
Let's think how to support that in best way one more time. We don't promise a solution but if so many users are affected it makes sense to think twice.

**Comment by ErikOrjehag** [comment]
I'm also affected by this issue, would be great if you have time to think about a solution

**Comment by ErikOrjehag** [comment]
@azhavoro @nmanovic It seems from this issue https://github.com/openvinotoolkit/cvat/issues/1026 that he found some kind of solution to this problem. Do you think you could help me figure out what he did? When the ordering of the images are changed it becomes a hazzle for the annotator because he can not use tracks properly.

**Comment by svenvanbuurennl** [comment]
@ErikOrjehag I managed to create a temporary solution to the problem by following the changes in this [Pull Request](https://github.com/openvinotoolkit/cvat/pull/867/files/9359b647cfac02be8f029561c4739b3e744cb2ea).

**Comment by ErikOrjehag** [comment]
@svenvanbuurennl Thank you very much, do you know if this temporary solution has any side effects? For example breaking the GUI way of adding images to the task?

**Comment by ErikOrjehag** [comment]
@nmanovic @azhavoro We are still affected by this issue quite a bit. It's difficult to annotate sequences and using tracks when we can not order the images by timestamp and sequence identifier. Do you know if this is in the pipeline for development?

**Comment by nmanovic** [comment]
https://github.com/openvinotoolkit/cvat/pull/3937
