### ISSUE TITLE
Option to increase the attributes text size

### ISSUE THREAD

**Issue by Rub21** [openvinotoolkit/cvat#1107]
Sometimes I find difficult to check the text attributes of the box, It would be good to give an option to customize the font size, for now, I have added  some CSS in the HTML 👇 
```
.shapeText {
    font-size: 0.3em;
    fill: white;
    stroke:black;
    stroke-width: 0.2;
    cursor: default;
}
```
![image](https://user-images.githubusercontent.com/1152236/73382150-059da800-4295-11ea-995d-eef14c3a809f.png)

**Comment by nmanovic** [comment]
@bsekachev , it looks like it is something which you are implementing at the moment.
