### ISSUE TITLE
Versioning annotations

### ISSUE THREAD

**Issue by 4sfaloth** [openvinotoolkit/cvat#1118]
Hi,

is there any recommended way to version annotations? I see the .xml files have a 'version' field, but I believe that refers to the file format.

The use case is like

1. We have a dataset
2. We annotate the dataset
3. We use the dataset for something (eg: evaluating a model)
4. Someone notices a few mislabeled images and fixes it
5. x months later nobody knows if 3. was performed before or after the gt changes. In practice this could potentially lead to repeting evaluations, etc...

**Comment by azhavoro** [comment]
Hi,

Where do you store a annotation files? Internally we use git integration for this.
https://github.com/opencv/cvat/tree/develop/cvat/apps/git#git-integration-for-annotation-storage

**Comment by nmanovic** [comment]
@4sfaloth ,

It is exactly why we are trying to develop datumaro framework: https://github.com/opencv/cvat/blob/develop/datumaro/README.md. It doesn't support versioning at the moment but will be in the future. Also it is possible to compare several datasets (use diff command from the framework)

**Comment by 4sfaloth** [comment]
> Hi,
> 
> Where do you store a annotation files? Internally we use git integration for versioning.
> https://github.com/opencv/cvat/tree/develop/cvat/apps/git#git-integration-for-annotation-storage
Currently we just store them on .git and update a separate changelog file everytime they are changed, which is a bit clumsy


> @4sfaloth ,
> 
> It is exactly why we are trying to develop datumaro framework: https://github.com/opencv/cvat/blob/develop/datumaro/README.md. It doesn't support versioning at the moment but will be in the future. Also it is possible to compare several datasets (use diff command from the framework)

great news, looking forward for its release!

**Comment by zhiltsov-max** [comment]
@4sfaloth, also, take a look at https://github.com/iterative/dvc

**Comment by nmanovic** [comment]
@4sfaloth , we have added versioning into Datumaro using DVC library. I will close the issue for now.
