### ISSUE TITLE
How to sync package versions: codacy-eslint <-> cvat

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#1125]
codacy-eslint engine setups its own versions of different packages in package.json. These versions are changed quite often.

It's a reason why sometimes locally there aren't any errors in both vscode and eslint command line interface, but at the same time, they are in codacy reports. 

What should we do to avoid it?

**Comment by nmanovic** [comment]
After discussing the topic with Codacy team I don't see a good workaround for the issue. Let's sync our versions of dev packages with codacy-eslint plugin manually for now.

@azhavoro , please consider to take the task in the nearest feature.

**Comment by bsekachev** [comment]
We do not see the issue for a long time. Maybe it was fixed itself.
