### ISSUE TITLE
Rotated bounding boxes

### ISSUE THREAD

**Issue by MadsDyrmann** [openvinotoolkit/cvat#1128]
Thank you for the great effort, you are putting into this project :) There is, however, a feature I miss; rotated bounding boxes. Especially when objects are thin and diagonal, an ordinary bounding box fits poorly. Examples of such cases are shown here: [rotated bounding boxes](https://pythonawesome.com/rotated-mask-r-cnn-from-bounding-boxes-to-rotated-bounding-boxes/)

A way annotation could be carried out is by using the recently implemented "extreme clicking" combined with the [minimum bounding-box algorithem](https://github.com/cansik/LongLiveTheSquare)

**Comment by cbasavaraj** [comment]
I second this demand :) For info, opencv has its well-known minAreaRect function, which could be as well:

https://docs.opencv.org/3.4/dd/d49/tutorial_py_contour_features.html
https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga3d476a3417130ae5154aea421ca7ead9

So it's a simple extension from the polygon mode we already have. 
And it would definitely be useful to have Interpolation mode available for these Rotated Boxes.

Thanks!

**Comment by dketterer** [comment]
I saw [a rotated bounding box format](https://github.com/NVIDIA/retinanet-examples/blob/master/TRAINING.md#dataset) in a customized COCO json the other day. Just wanted to leave that here.

Like this:

```
"bbox" : [x, y, w, h, theta]    # all floats, where theta is measured in radians anti-clockwise from the x-axis.
"segmentation" : [[x1, y1], [x2, y2], [x3, y3], [x4, y4]]    # Required for validation scores.
```

I also think an addtional method to directly annotate rotated bounding boxes would be useful instead of using the segmentation to crete them from the segmentaion.

**Comment by nmanovic** [comment]
@MadsDyrmann , why don't use a polygon with 4 points? Do you need them only in annotation files?

**Comment by MaxPRon** [comment]
Hi guys,

thanks for the great effort!

I was trying to the [ rotated bounding box pull request](https://github.com/openvinotoolkit/cvat/pull/3832) but I can't seem to find the feature.

Could anybody give me a hint how to use it ? I'm new to the tool so maybe I'm just overlooking it.


Best regards and thanks a lot,

Max

**Comment by farid67** [comment]
> Hi guys,
> 
> thanks for the great effort!
> 
> I was trying to the [ rotated bounding box pull request](https://github.com/openvinotoolkit/cvat/pull/3832) but I can't seem to find the feature.
> 
> Could anybody give me a hint how to use it ? I'm new to the tool so maybe I'm just overlooking it.
> 
> Best regards and thanks a lot,
> 
> Max

Same here

**Comment by cbasavaraj** [comment]
Hello, this issue has been closed by the maintainers.
I tried using rotated bounding boxes for training a model on detectron2 last year.
But the results were not great, as the predicted angle changed from frame to frame.
So in my opinion, it's not worth the trouble.

A better approach is to use a segmentation model like mask-rcnn. So you have the exact mask, and the bounding box and its angle are less important. Of course from the mask you cannot tell which side is up or the orientation in general. But I think that's not so important usually.

**Comment by nmanovic** [comment]
@cbasavaraj , @farid67 , @MaxPRon , you can find it in develop branch at the moment: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/annotation-with-rectangles/#rotation-rectangle

**Comment by MaxPRon** [comment]
Thank you @nmanovic

**Comment by quents** [comment]
I also cannot use rotation point at the latest develop branch.

**Comment by kimlia545** [comment]
@nmanovic 
There is a problem with labeling the rotating box.
When I download the label(COCO 1.0) with "Export task dataset" and do "Upload annotations" again, all rotation disappear.

```
{
            "id": 1,
            "image_id": 1,
            "category_id": 1,
            "segmentation": [],
            "area": 334.9267999999998,
            "bbox": [
                261.75,
                190.06,
                44.42,
                7.54
            ],
            "iscrowd": 0,
            "attributes": {
                "occluded": false,
                "rotation": 324.4
            }
        }

#Upload Coco's dataset, the rotation disappears
{
            "id": 1,
            "image_id": 1,
            "category_id": 1,
            "segmentation": [],
            "area": 334.9267999999998,
            "bbox": [
                261.75,
                190.06,
                44.42,
                7.54
            ],
            "iscrowd": 0,
            "attributes": {
                "occluded": false,
                "rotation": 0.0
            }
        }
```

**Comment by kimlia545** [comment]
@nmanovic Thank you for answer. rotation remains in the CVAT 1.1. I hope it will be supported by coco as well.

**Comment by zhiltsov-max** [comment]
@kimlia545, hi. Our COCO implementation refers to the [original](https://cocodataset.org/#format-data) format, which doesn't have rotation info, but we've added a `rotation` attribute as an extension, and it can be seen in the example above. Thank you for reporting the import problem, need to double check this.
