### ISSUE TITLE
Could not check authorization on the server

### ISSUE THREAD

**Issue by xialuxi** [openvinotoolkit/cvat#1160]
open ip:8080
Could not check authorization on the server
Error: Network Error.

**Comment by azhavoro** [comment]
@xialuxi Hi, could you please provide docker-compose config?

**Comment by xialuxi** [comment]
same as #1093

**Comment by azhavoro** [comment]
@xialuxi Could you please attach the error message from browser console? f12->console tab?

**Comment by Gauthamraju31** [comment]
@azhavoro I have the same issue, here is the browser log and docker-compose.override.yml 

![Screenshot from 2020-02-21 18-25-29](https://user-images.githubusercontent.com/16057373/75036610-49707f80-54d8-11ea-87fa-2696cc467e07.png)


version: "2.3"

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: cvat
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        TF_ANNOTATION: "no"
        AUTO_SEGMENTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        TZ: "Etc/UTC"
        OPENVINO_TOOLKIT: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      UI_SCHEME: http
      UI_HOST: yantraaipc.local
      UI_PORT: 7080
      ALLOWED_HOSTS: '*'


    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models

  cvat_ui:
    container_name: cvat_ui
    image: nginx
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        REACT_APP_API_PROTOCOL: http
        REACT_APP_API_HOST: yantraaipc.local
        REACT_APP_API_PORT: 8080
      dockerfile: Dockerfile.ui

    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat
    ports:
      - "7080:80"

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:

**Comment by azhavoro** [comment]
@Gauthamraju31 could you please attach `docker logs cvat` output?

**Comment by Gauthamraju31** [comment]
@azhavoro I have attached the log file cvat_logs.txt
[cvat_logs.txt](https://github.com/opencv/cvat/files/4236615/cvat_logs.txt)

**Comment by azhavoro** [comment]
> @azhavoro I have attached the log file cvat_logs.txt
> [cvat_logs.txt](https://github.com/opencv/cvat/files/4236615/cvat_logs.txt)

Have you changed ALLOWED_HOSTS env var as described here https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#advanced-settings?
Also it seems you have a changed models. From your log:
`Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.` Please try to reproduce the issue on unchanged source code.

**Comment by Gauthamraju31** [comment]
> > @azhavoro I have attached the log file cvat_logs.txt
> > [cvat_logs.txt](https://github.com/opencv/cvat/files/4236615/cvat_logs.txt)
> 
> Have you changed ALLOWED_HOSTS env var as described here https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#advanced-settings?
> Also it seems you have a changed models. From your log:
> `Your models have changes that are not yet reflected in a migration, and so won't be applied. Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.`
> Please try to reproduce the issue on unchanged source code.

Docker compose file

[docker-compose.override.yml.txt](https://github.com/opencv/cvat/files/4236880/docker-compose.override.yml.txt)

No changes to source code
![Screenshot from 2020-02-21 21-20-40](https://user-images.githubusercontent.com/16057373/75050179-839a4b00-54f1-11ea-90c4-b767f80978f3.png)

Log for rerun 
[cvat_logs.txt](https://github.com/opencv/cvat/files/4236886/cvat_logs.txt)

**Comment by xialuxi** [comment]
i change the code in setting/base.py:
# Cross-Origin Resource Sharing settings for CVAT UI
UI_SCHEME = os.environ.get('UI_SCHEME', 'http')
UI_HOST = os.environ.get('UI_HOST', '192.168.1.9')
UI_PORT = os.environ.get('UI_PORT', '9080')
and it work!
I think“ os.environ” didn't work

**Comment by BenoCharlo** [comment]
> cvat-0.5.2.tar.gz
> i change the code in setting/base.py:
> 
> *****# Cross-Origin Resource Sharing settings for CVAT UI
> UI_SCHEME = os.environ.get('UI_SCHEME', 'http')
> UI_HOST = os.environ.get('UI_HOST', '192.168.1.9')
> UI_PORT = os.environ.get('UI_PORT', '7080')
> 
> and it work!
> I think“ os.environ” didn't work

Hello, I've tried your solution but was not lucky. Which python were you using? I'm on Python 3.7 but I don't rally think it should be the problem

**Comment by azhavoro** [comment]
@BenoCharlo Hi, could you please clarify what is the issue with development mode?

**Comment by BenoCharlo** [comment]
> @BenoCharlo Hi, could you please clarify what is the issue with development mode?

@azhavoro, I cannot simply get into the development mode when running the docker-compose. I have to rebuild all my project everytime I made a change to the code

**Comment by ggior** [comment]
Hello, I also have the "Could not check authorization on the server" error.
I have attached the error message from the browser console and the "attach docker logs cvat" output. Thank you in advance for your help.
![browser_console_error](https://user-images.githubusercontent.com/64864984/82634298-6269f900-9bcb-11ea-94cb-9e105019ab13.png)

[cvat_logs.txt](https://github.com/opencv/cvat/files/4666209/cvat_logs.txt)

**Comment by azhavoro** [comment]
This issue should be not relevant after adding cvat_proxy.
