### ISSUE TITLE
All annotations have disappeared

### ISSUE THREAD

**Issue by lcit** [openvinotoolkit/cvat#1252]
I was annotating a video and I was also constantly saving the work using the button "Save Work". Everything was fine until I reached the end of the video; I saved my work again all my annotation disappeared. Is there an explanation or something I can do to recover? I have not dumped the annotations to file

**Comment by lcit** [comment]
I found out what happened. I needed to delete the bounding box of the last frame because the object disappeared. If you click on the bounding box (with interpolation) and then delete it, all the bounding boxes associated to this object for all frames are deleted as well.  A popup message to warn could be useful here.  Thanks, this can be closed.

**Comment by bsekachev** [comment]
There are shapes - objects that exist only within one frame.
And there are tracks - objects that exist within the range of frame.
When you delete a track, you delete all related data.
If a track disappears from a frame, you should use "outside" property (set it to true), what means the track is out of this frame. Later, when object can appear again in the video, you can do the track not outside.

I believe, the idea of doing a warning message might be useful for new users. But for experienced users it is probably extra.

**Comment by ipesanz** [comment]
Another user (newbie) that has lost part of a daily work for some similar cause

**Comment by nmanovic** [comment]
@ipesanz , please vote for the feature request: https://github.com/openvinotoolkit/cvat/issues/2999.

**Comment by ipesanz** [comment]
Done. A thumbs up +1 in the first message of  #2999
<https://github.com/openvinotoolkit/cvat/issues/2999> - Warning can be a
good workaround (unfortunately, I was not the user losing the job... so no
direct experience)

Missatge de Nikita Manovich ***@***.***> del dia dj., 10 de
juny 2021 a les 5:15:
