### ISSUE TITLE
Growing Dataset

### ISSUE THREAD

**Issue by vtimofeev01** [openvinotoolkit/cvat#1278]
Hello!

I have my own dataset for attributes annotation that is growing from week to week. 
Please tell me how to do:
1) annotating new images with same labels to have one whole dataset
2) add new labels/properties to all dataset
3) what is the easyest way to export multi-label property annotation to PyTorch

Thank you
Vasili

**Comment by azhavoro** [comment]
The Projects feature, which is currently under development, will solve 1 and 2 issues.
What do you mean by `multi-label property annotation`?

**Comment by vtimofeev01** [comment]
I mean that I make multiple labels for each ROI and what the favourite way to export it for multi label training

**Comment by nmanovic** [comment]
@vtimofeev01 , we have implemented the project feature. I will close the issue as outdated. If you need multi-labels, please share with us ideas how to implement the feature for your scenario in a separate issue.
