### ISSUE TITLE
Mark ignore regions and keyframes for an object

### ISSUE THREAD

**Issue by oostap1** [openvinotoolkit/cvat#13]
Thanks for great annotation server.
It would be great to have "uncertain" flag for annotation (like you have occlusion). Which means that as human I see the object and can annotate but for detection it would be nice to detect but it is OK if detector does not detect it (do no penalize algorithm for that).

**Comment by nmanovic** [comment]
Hi @oostap1,

There are two ways to solve the problem (internally we use both for different cases):
- Create `ignore` label and mark using it different regions with a lot of small objects or any uncertainty
- Also if you definitely need "uncertain" flag you can add it to a label as an attribute: `person ~checkbox=uncertain:false`.

The story of "occlusion" flag is long and the root of the story is "Vatic" annotation tool. Let's see if a lot of users want to see "uncertain" flag by default and if it is the case we will add it.

Please let me know what you think.

**Comment by oostap1** [comment]
Tried and it works. Thanks. Just not really convenient. It is difficult to validate annotation. If I play video both my eyes are watching video and none tool box :(. It would truly help if such attribute changes annotation rectangle somehow (make it zigzag line  or so). 
BTW: it is true for key frame as well. Would be great to see it on annotated rectangle. Like having it bold or double line. Then it will be much easier to annotate/validate.

**Comment by nmanovic** [comment]
I will close the issue. We have a very useful workaround. Need just have an "ignore" label and use it to mark ignored regions.
