### ISSUE TITLE
Exporting annotator information for each annotation

### ISSUE THREAD

**Issue by radoye** [openvinotoolkit/cvat#1362]
I tried exporting into CVAT XML and into COCO JSON format. Neither seems to have any information about annotators, i.e., which annotator provided which annotation. I can't find any mention of this in the manual, either. Is this possible and how?

**Comment by nmanovic** [comment]
@radoye , 

Could you please give us an example how you want to see the information in an annotation file?

**Comment by radoye** [comment]
@nmanovic We work mostly with COCO JSON, so let's start the discussion around that one. It should be backward-compatible to simply add another top-level key, e.g., "attributions", and list {"annotation_id": ..., "labeler_id": ..., ...}. In other words, the same indirect structure like the one between "images" and "annotations" in COCO JSON.

For context, we typically overlap jobs in large tasks by a few %. Jobs are randomly assigned and we use majority vote to spot and log outliers.

**Comment by nmanovic** [comment]
@radoye , if we generate extra meta information as a separate file it will work? It can be difficult to extend each format (e.g. MOT) with such information. I understand that you are working with COCO but in the tool our team wants to keep more or less general solutions.

> For context, we typically overlap jobs in large tasks by a few %. Jobs are randomly assigned and we use majority vote to spot and log outliers.

If you and your team can share your experience with community and contribute some stories or even some features for CVAT it will be awesome.

**Comment by radoye** [comment]
@nmanovic A separate file would work great. As long as the data can be exported, in any way, merging is trivial. Sure, we can describe our process at some point, as we finish the PRs we already started.

**Comment by nmanovic** [comment]
@radoye , at the moment in DB we don't have an annotator for every shape. We have an owner and assignee for a task. As far as I remember the assignee field is dumped into CVAT XML. I think we are not going to add an annotator field for every shape in the future as well. I will close the issue.
