### ISSUE TITLE
Z-axis-slider in a task with z-order disabled (in new UI)

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#1390]
If the z-order is disabled in the created task, the z-axis-slider is still active or can be made active by clicking on the add new layer button, the order will also switch to the "+" and "-" buttons and the buttons in the action "to background" and "to foreground" is also active. 
But the order of objects does not affect the annotation file. This is confusing. 
Maybe if z-order is disabled when creating a task, make all the elements related to z-order inactive?
![image](https://user-images.githubusercontent.com/54434686/78980100-d96c9600-7b25-11ea-951b-1d393f7d20cc.png)

**Comment by bsekachev** [comment]
I suppose we should deprecate ``z order`` flag during task creating in the future releases

**Comment by nmanovic** [comment]
I believe the issue was resolved. Now you cannot specify z-order when create an annotation task.
