### ISSUE TITLE
CVAT new UI: progress bar of the automatic annotation is not displayed on the task page

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#1441]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The progress bar of the automatic annotation is displayed on the task page and in the task list

### Current Behaviour

The progress bar for automatic annotation does appear only in the task list

![progressbar](https://user-images.githubusercontent.com/54434686/79853659-fed48c00-83d0-11ea-9739-7f0dab189fb7.jpg)

### Possible Solution

I think that need to somehow display information about the process of automatic annotation, not only in the list of tasks but also on the task page

**Comment by nmanovic** [comment]
I will close the bug as outdated. I can see the progress bar on the task page.
