### ISSUE TITLE
Optimize documentation by size

### ISSUE THREAD

**Issue by nmanovic** [openvinotoolkit/cvat#1447]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Documentation should be about 10Mb-20Mb

### Current Behaviour

Current documentation takes 56Mb

### Possible Solution

*.gif files take 47Mb. It is too much. Need to remove gif where it is possible. Also it will be good to reduce its size. Probably we always can replace a gif by a sequence of 2-4 frames in a row.

### Steps to Reproduce (for bugs)

N/A

### Context

Rendering of documentation takes much time.

### Your Environment

N/A

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@TOsmanov , could you please look at the issue?

**Comment by TOsmanov** [comment]
@nmanovic I will replace some GIFs with images, and in other GIFs I will reduce the frame rate.

**Comment by nmanovic** [comment]
https://openvinotoolkit.github.io/cvat/docs/
