### ISSUE TITLE
Add Cli option to upload annotations on task creation

### ISSUE THREAD

**Issue by egrinstein** [openvinotoolkit/cvat#1453]
Hello,

My usage of Cvat requires uploading annotations when creating jobs (for visualisation, for instance).
I have added this option into the CLI:

```bash
python cli.py create --help
usage: cli.py create [-h] [--labels LABELS] [--bug BUG]
                     [--annotation_path ANNOTATION_PATH]
                     [--annotation_format ANNOTATION_FORMAT]
                     [--cooldown_period_in_secs COOLDOWN_PERIOD_IN_SECS]
                     name {local,share,remote} resources [resources ...]

Create a new CVAT task.

positional arguments:
  name                  name of the task
  {local,share,remote}  type of files specified
  resources             list of paths or URLs

optional arguments:
  -h, --help            show this help message and exit
  --labels LABELS       string or file containing JSON labels specification
  --bug BUG             bug tracker URL
  --annotation_path ANNOTATION_PATH
                        path to annotation file
  --annotation_format ANNOTATION_FORMAT
                        format of the annotation file being uploaded, e.g.
                        CVAT XML 1.1
  --cooldown_period_in_secs COOLDOWN_PERIOD_IN_SECS
                        number of seconds to wait for the job to be created
                        until uploading the annotations
```

I have modified files `utils/cli/definitions.py` and utils/cli/core.py`. You can see the changes [here].(https://github.com/egrinstein/cvat/tree/feature/create_task_with_annotations)
If this is interesting for you, @nmanovic , how could I provide a test for this?

PS1: I have included the "cooldown_period_in_secs" arg because cvat only accepts annotations after the job is created, which seems to happen after file compression and its impossible to know using the CLI. 
PS2: I have worked on this from the master branch because there seems to be a problem with the CLI in the develop branch, which I described at #1452 .

**Comment by nmanovic** [comment]
@egrinstein , any contribution is vital for our product. We are happy to accept contributions from our community. Several comments below:

> If this is interesting for you, @nmanovic , how could I provide a test for this?

Yes

> PS1: I have included the "cooldown_period_in_secs" arg because cvat only accepts annotations after the job is created, which seems to happen after file compression and its impossible to know using the CLI.

You need to use REST API to check if a task is created. When you post your data, you can periodically check status of the request.

 > PS2: I have worked on this from the master branch because there seems to be a problem with the CLI in the develop branch, which I described at #1452 .

Need to fix develop branch. Could you please help? The master branch only for releases. The develop branch is used for integration of new changes.
