### ISSUE TITLE
CVAT new UI: List of shortcuts

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#1461]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Convenient list of shortcuts containing all the necessary hotkeys

### Current Behaviour

There are errors in the shortcuts sheet:
Show shortcuts opens by pressing F2 instead of F1
Open settings opens by pressing F3 instead of F2
I did not find some shortcuts

### Possible Solution

I think that it’s worth adding the following shortcuts:
| Name | Shortcut | Action | Description|
|-- |-- |-- |-- |
|Delete a point | `` Ctrl + Double-Click`` | on point | Deleting a point (used when hovering over a point of polygon, polyline, points) |
| Editing a shape | `` Shift + Double-Click`` | on point | Editing a shape (used when hovering over a point of polygon, polyline, points) |
| Object element | `` Right-Click`` | on shape | Display of an object element from objects sidebar|
| Move image | `` Mouse Wheel`` | hold | To move an image frame (for example, while drawing) |
| Fix shape | ``Ctrl`` | hold | When the shape is active and fix it.|
| Multiple pasting| `` Ctrl`` | hold while pasting  | When pasting shape from the buffer for multiple pasting. |

I liked that in the new user interface, only the keys related to the selected scheme are displayed, but in any case there are a lot of them. Perhaps it would be more convenient if the table was divided into sections. For example:
- Main functions
- Player
- Modes
- Image operations
- Operations with objects
- Operations are available only for track
- Attribute annotation mode (display only in AAM)

### Steps to Reproduce (for bugs)

N/A

### Context

N/A

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@TOsmanov, @bsekachev Is this issue still relevant?

**Comment by bsekachev** [comment]
@azhavoro , I suppose it is relevant because we still do not have some hints (described in possible solution) in UI list

**Comment by TOsmanov** [comment]
@azhavoro in my opinion, only the partitioning of the shortcuts list into sections is relevant

**Comment by nmanovic** [comment]
I will close the issue as outdated.
