### ISSUE TITLE
Lidar/Radar 3D data labeling

### ISSUE THREAD

**Issue by nmanovic** [openvinotoolkit/cvat#1475]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible Solution

1. Integrate threejs as a replacement for svg.js = 2-3 months (very rough estimation) - https://github.com/mrdoob/three.js – DELAYED (unnecessary for the first version)
1. https://supervise.ly/lidar-3d-cloud/ - a good design solution (https://medium.com/deep-systems/releasing-first-online-3d-point-cloud-labeling-tool-in-supervisely-4faca42b5d6e)
1. A prototype of lidar annotation tool: https://github.com/bernwang/latte/tree/master/, https://arxiv.org/abs/1904.09085
1. Rendering KITI data: https://github.com/JustinGOSSES/lidar_threejs_playground, https://justingosses.github.io/lidar_threejs_playground/
1. 3d-bat: https://github.com/walzimmer/3d-bat,
1. https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor

### Context

CVAT cannot load and annotate 3D data at the moment. The feature is critical for automotive companies and some internal projects.

**Comment by nmanovic** [comment]
One of possible datasets to check the feature: https://techcrunch.com/2020/05/22/scale-ai-releases-free-lidar-dataset-to-power-self-driving-car-development/

**Comment by waelKH** [comment]
Hallo,
is there an estimation of when this story will be released?

**Comment by rodrigoGA** [comment]
I am also very interested in this feature.

**Comment by charlescho64** [comment]
@nmanovic 

Thank for your team. This feature is very good. 
How to export/dump the output of annotation on 3D with cuboid? 
In cvat.org site, I annotated object in 3D  and tried to dump/export the result of 3D annotation like 2D, but any don't response.

**Comment by nmanovic** [comment]
@charlescho64 , upload/download of annotations will be available as soon as https://github.com/openvinotoolkit/cvat/pull/3234 is merged. It should be done very soon. Don't hesitate to submit bugs, feature requests. We are happy to get code contribution as well.

**Comment by charlescho64** [comment]
@nmanovic 

After including dump / export function for 3D annotation data, latest CVAT removed the function that user move view point 3D  main window with mouse.

I can move  view point in previous version(without dump /export 3D data).

if this function is not included, user have inconvenience in 3D annotation.

**Comment by nmanovic** [comment]
Hi @charlescho64 , #3438. You still can use mouse but you have use "move" tool for that. Use left side panel to choose "move" tool. I agree that it isn't convent and should be fixed.

**Comment by nmanovic** [comment]
The feature was implemented. It has to be improved by I will close the issue.

**Comment by amitmohanty** [comment]
@nmanovic Nikita, is there a doc/manual on how to get started on this feature on CVAT (e.g., LiDAR data labeling)?
