### ISSUE TITLE
Import/Export a task functionality

### ISSUE THREAD

**Issue by nmanovic** [openvinotoolkit/cvat#152]
For different purpose it is very convenient to be able to import/export an annotation task to/from CVAT. For example, it can be used for debugging. Also it will help to get "all images" inside one archive.

**Comment by nmanovic** [comment]
It was implemented: https://github.com/openvinotoolkit/cvat/pull/3056. I will close the request.

**Comment by lsmliborio** [comment]
Sorry to post a comment here, but seems there is a limitation on this functionality. I have different tasks backups that I'd like to import to a project. They share the same annotation space, but I couldn't do it.
