### ISSUE TITLE
Unable to connect Elastic Search 

### ISSUE THREAD

**Issue by gururajdori** [openvinotoolkit/cvat#1523]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour
Seamless Elastic Search connection 

### Current Behaviour
Following is docker logs 
```
cvat_kibana           | {"type":"log","@timestamp":"2020-05-12T09:40:36Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
cvat_kibana           | {"type":"log","@timestamp":"2020-05-12T09:40:36Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
cvat_kibana           | {"type":"log","@timestamp":"2020-05-12T09:40:40Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
cvat_kibana           | {"type":"log","@timestamp":"2020-05-12T09:40:40Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
cvat_kibana           | {"type":"log","@timestamp":"2020-05-12T09:40:47Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
cvat_kibana           | {"type":"log","@timestamp":"2020-05-12T09:40:48Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
```

### Possible Solution

Not sure about the solution but I think ``elasticsearch.url: http://elasticsearch:9200`` in kibana.yml maybe we need to change this to hosting machine IP
**i.e** for local machine IP will start with 192.168.X.X and for AWS Instance External IP should do the job

### Steps to Reproduce (for bugs)

1. Clone CVAT and change branch to develop 
2. Get into chat Folder
3. ```docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml -f components/analytics/docker-compose.analytics.yml -f components/tf_annotation/docker-compose.tf_annotation.yml -f components/openvino/docker-compose.openvino.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml up```

### Your Environment

- Git hash commit (`git log -1`): 1b93d6edfb7526b3c1f599435bbc2f961ff4ccef
- Docker version `docker version` (e.g. Docker 17.0.05): v19.03.8
- Are you using Docker Swarm or Kubernetes? Kubernetes
- Operating System and version (e.g. Linux, Windows, MacOS):MacOS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>cvat_kibana           | {"type":"log","@timestamp":"2020-05-12T09:40:00Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}</summary> </details>
     <details>
    <summary>cvat_kibana           | {"type":"log","@timestamp":"2020-05-12T09:40:00Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}</summary>
    </details>

**Comment by gururajdori** [comment]
@nmanovic

**Comment by azhavoro** [comment]
@gururajdori Hi, could you attach logs from the elastic `docker logs cvat_elasticsearch`?

**Comment by gururajdori** [comment]
@azhavoro Hello, below log for cvat_elasticsearch container 
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2020-05-12T20:44:38,512][INFO ][o.e.n.Node               ] [] initializing ...
[2020-05-12T20:44:40,200][INFO ][o.e.e.NodeEnvironment    ] [AKM3ogp] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/vda1)]], net usable_space [18.5gb], net total_space [58.4gb], types [ext4]
[2020-05-12T20:44:40,217][INFO ][o.e.e.NodeEnvironment    ] [AKM3ogp] heap size [1007.3mb], compressed ordinary object pointers [true]
[2020-05-12T20:44:40,274][INFO ][o.e.n.Node               ] [AKM3ogp] node name derived from node ID [AKM3ogpOSpO75KuXauhTXg]; set [node.name] to override
[2020-05-12T20:44:40,275][INFO ][o.e.n.Node               ] [AKM3ogp] version[6.4.0], pid[1], build[oss/tar/595516e/2018-08-17T23:18:47.308994Z], OS[Linux/4.19.76-linuxkit/amd64], JVM["Oracle Corporation"/OpenJDK 64-Bit Server VM/10.0.2/10.0.2+13]
[2020-05-12T20:44:40,277][INFO ][o.e.n.Node               ] [AKM3ogp] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.Ho72kffJ, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=tar]
```

**Comment by azhavoro** [comment]
I cannot reproduce this issue with docker-compose and suppose it's related with Kubernetes deployment

**Comment by gururajjeerge** [comment]
@azhavoro Hello, Can you put git head to 1b93d6edfb7526b3c1f599435bbc2f961ff4ccef commit id and try?
I stopped the Kubernetes cluster and tried but still facing the same issue

**Comment by ilouzl** [comment]
This also happens in my ec2 deployment (not Kubernetes).
I'm using latest release (https://github.com/openvinotoolkit/cvat/commit/8eb7c13619e39d9546ba3807027d30eab9c5ce2b) and Docker 19.03.12.
Attached are elastic and kibana logs. 
[elastic.log](https://github.com/openvinotoolkit/cvat/files/5361247/elastic.log)
[kibana.log](https://github.com/openvinotoolkit/cvat/files/5361248/kibana.log)

**Comment by azhavoro** [comment]
@ilouzl 
In the logs I see that elastic and kibana were stared sucessfully
```
[2020-10-11T13:58:31,477][INFO ][o.e.c.r.a.AllocationService] [uGhlyAT] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[.kibana][0]] ...]).
{"type":"log","@timestamp":"2020-10-11T13:58:30Z","tags":["status","plugin:elasticsearch@6.4.0","info"],"pid":1,"state":"green","message":"Status changed from red to green - Ready","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200/."}
```
So, could you please provide more information about your issue: logs from the cvat server (docker logs cvat> cvat.log)? What do you see in the browser when you open the analytics tab, are there any errors?

**Comment by ilouzl** [comment]
@azhavoro 
It was started successfully but in kibana logs there are several connection errors with es:

```
{"type":"log","@timestamp":"2020-10-11T13:58:10Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.28.0.3:9200"}
{"type":"log","@timestamp":"2020-10-11T13:58:10Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-10-11T13:58:10Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
{"type":"log","@timestamp":"2020-10-11T13:58:10Z","tags":["status","plugin:elasticsearch@6.4.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch at http://elasticsearch:9200/.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
```

What happens is that the Analytics tab is stuck with the 'Loading Kibana' animation and Kibana UI won't load. 
Attached are new error logs (just logging in and selecting Analytics tab).
[kibana.log](https://github.com/openvinotoolkit/cvat/files/5371418/kibana.log)
[cvat.log](https://github.com/openvinotoolkit/cvat/files/5371419/cvat.log)
[es.log](https://github.com/openvinotoolkit/cvat/files/5371420/es.log)

Also in Chrome console I get this error:
```
vendors.bundle.js:1 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".

    at Function (<anonymous>)
    at vendors.bundle.js:1
    at vendors.bundle.js:1
    at vendors.bundle.js:1
    at Function.template (vendors.bundle.js:1)
    at commons.bundle.js:1
    at Object.show (commons.bundle.js:1)
    at fatalError (commons.bundle.js:1)
    at window.onerror (commons.bundle.js:1)
```

**Comment by azhavoro** [comment]
> @azhavoro
> It was started successfully but in kibana logs there are several connection errors with es:
> 
> ```
> {"type":"log","@timestamp":"2020-10-11T13:58:10Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.28.0.3:9200"}
> {"type":"log","@timestamp":"2020-10-11T13:58:10Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
> {"type":"log","@timestamp":"2020-10-11T13:58:10Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
> {"type":"log","@timestamp":"2020-10-11T13:58:10Z","tags":["status","plugin:elasticsearch@6.4.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch at http://elasticsearch:9200/.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
> ```

I think it's a normal behavior Elastic needs some times to start and be ready to accept connections.

Regarding Kibana error: do you use any reverse proxy?

**Comment by ilouzl** [comment]
I'm using Cloudflare dns if that's what you're asking

**Comment by azhavoro** [comment]
I think this might be the cause of this issue https://github.com/elastic/kibana/issues/76630 and we cannot fix it on CVAT side.

**Comment by ilouzl** [comment]
@azhavoro 
In order to verify your diagnosis, I tried accessing CVAT using the explicit IP address of my ec2 (without passing through Cloudflare DNS) and the error was still there.

As a sanity check, I've deployed a simlar CVAT instance (on a new machine), this time without HTTPS serving, and then Kibana loads perfect.
Maybe it's indeed something with HTTP serving?

**Comment by azhavoro** [comment]
@ilouzl According the mentioned issue the specific values of the CSP headers cause this error. This header doesn't related with https. On the cvat side we don't set or override this header, also Kibana works fine for cvat.org or our internal instance over https.
How do you setup https for you instance? Could you check the response headers with curl `curl -u "user:pass" -I -L https://CVAT_URL/analytics/app/kibana`?

**Comment by ilouzl** [comment]
Thanks, This is the response:
```
HTTP/2 301 
date: Thu, 15 Oct 2020 09:10:43 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d4e0022ba6170fa783241d51da8e89ef11602753043; expires=Sat, 14-Nov-20 09:10:43 GMT; path=/; domain=.tapwithus.com; HttpOnly; SameSite=Lax
location: /login
x-frame-options: SAMEORIGIN
vary: Origin,Cookie
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'self' http: https: data: blob: 'unsafe-inline'
strict-transport-security: max-age=31536000; includeSubDomains; preload
cf-cache-status: DYNAMIC
cf-request-id: 05cd1fb453000009879d224000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=16&lkg-time=1602753044"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 5e28689a1f5b0987-IAD

HTTP/2 200 
date: Thu, 15 Oct 2020 09:10:43 GMT
content-type: text/html
set-cookie: __cfduid=d4e0022ba6170fa783241d51da8e89ef11602753043; expires=Sat, 14-Nov-20 09:10:43 GMT; path=/; domain=.tapwithus.com; HttpOnly; SameSite=Lax
last-modified: Mon, 21 Sep 2020 08:29:49 GMT
accept-ranges: bytes
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'self' http: https: data: blob: 'unsafe-inline'
strict-transport-security: max-age=31536000; includeSubDomains; preload
cf-cache-status: DYNAMIC
cf-request-id: 05cd1fb480000009876305e000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=16&lkg-time=1602753044"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 5e28689a6f9b0987-IAD
```

**Comment by azhavoro** [comment]
@ilouzl Hi, did you resolve this issue?

**Comment by ilouzl** [comment]
Unfortunately not

**Comment by azhavoro** [comment]
could you try curl command (I mean `curl -u "user:pass" -I -L https://IP/analytics/app/kibana`) with public IP of you instance ? What is the output?

**Comment by ilouzl** [comment]
> On the cvat side we don't set or override this header, also Kibana works fine for cvat.org or our internal instance over https.

Isn't analytics disabled on the demo server?

**Comment by bsekachev** [comment]
@azhavoro @ilouzl 

I am not sure the issue is still relevant, so, I will close it. If somebody still has questions or ideas, please reopen and share
