### ISSUE TITLE
Could not check authorization on the server - On MacOS

### ISSUE THREAD

**Issue by madhu-kv** [openvinotoolkit/cvat#1533]
Hello

I installed the application on my Mac as per the guidelines. Everything worked correctly for the first time. Once I close the browser, reopen again & try to login using the URL - http://localhost:8080/auth/login , I get an error immediately - "Could not check authorization on the server". Attached is the screenshot.
Can someone please suggest help?
![Could not check auth](https://user-images.githubusercontent.com/39720735/81840018-00274d80-9566-11ea-9596-f91c37c6a996.jpg)

Thank you
Madhu

**Comment by ehtasham** [comment]
I am getting the same error, please let me know if you find any solution.

**Comment by azhavoro** [comment]
@madhu-kv Hi, please dont ignore the issue template and provide additional information that may help to solve your issue: CVAT version (git log -1), os, docker version, etc. Also please attach the container logs `docker logs cvat` and `docker logs cvat_proxy`

**Comment by nmanovic** [comment]
@ehtasham , @madhu-kv , please provide logs to investigate the issue. Nothing to do with the provided information. I can run CVAT on Mac OS without any issues.
