### ISSUE TITLE
Dump annotations/data features work with the new UI when I'm connected to CVAT via ssh tunneling

### ISSUE THREAD

**Issue by masonearles** [openvinotoolkit/cvat#1535]
### Expected Behaviour
For release v1.0.0-beta.2, none of the dump annotations/data features work with the new UI when I'm connected to CVAT via ssh tunneling. However, these features do work when I have a local Docker instance running and from within the old UI.

### Current Behaviour
The new UI drop down for dumping annotations does not expand to provide options for different formats like COCO JSON, etc. I am not receiving an error, just a lack of functionality.

### Context
Our team is trying to use CVAT when logged in via VPN to our local university network. We ssh tunnel into a machine where we can access the CVAT server on our local machine as `localhost:9000`. 

### Your Environment
- Git hash commit : 011c4aa
- Docker version: Docker 19.03.2
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version: Linux Ubuntu 18

**Comment by azhavoro** [comment]
@masonearles Hi, are there any error messages on the browser console?

**Comment by yohayonyon** [comment]
Using the same code (tag: v1.0.0-beta.2). Dump does not work using the CLI tool from other machine, but works from GUI and with the same CLI tool running on the same  machine running the server.
Not working - STATUS 200 forever.

**Comment by yohayonyon** [comment]
It is somewhat different, but maybe related.

**Comment by azhavoro** [comment]
The old UI has been removed, so I don't think this issue is actual, I'll close it.

**Comment by yohayonyon** [comment]
This issue happens with a clean v1.2.0 build.
![Screenshot from 2021-02-15 11-54-12](https://user-images.githubusercontent.com/61744528/107931916-9a993f00-6f85-11eb-9320-1cfb3a6c6898.png)
