### ISSUE TITLE
Too many polygon points in semi-automatic annotation

### ISSUE THREAD

**Issue by Deer-1170** [openvinotoolkit/cvat#1544]
### My actions before raising this issue
- [x] Read/searched [the docs]
- [x] Searched [past issues](/issues)

### What need help
* The number of polygon points surrounded by semi-automatic annotation using deep extreme cut is very large. How can I reduce this?

**Comment by nmanovic** [comment]
@Deer-1170 , first of all need to use approxpoly on the server side. Also the function can be useful on the client side as well. I believe we can implement a serverless function for that.

**Comment by Deer-1170** [comment]
Thank you for your feedback.
Can I change something temporarily to reduce points?

**Comment by davodogster** [comment]
> Thank you for your feedback.
> Can I change something temporarily to reduce points?

@nmanovic Yes I get the same problem - it produces too many points and the Polygon correction takes too long.. I guess it's just the nature of the algorithm.. or can backend params be fine-tuned?

**Comment by s3298230** [comment]
I have the same concern...Will update the threshold  or IoU work ?

**Comment by nmanovic** [comment]
The issue is outdated. Now we have ways to reduce the number of points: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/ai-tools/

![image](https://user-images.githubusercontent.com/40690625/143549048-7bb6558c-aa45-413d-b51b-ef1e34dc456d.png)
