### ISSUE TITLE
"ZIP cannot handle files older than 1.1.1980" error during task upload

### ISSUE THREAD

**Issue by yohayonyon** [openvinotoolkit/cvat#1565]
### My actions before raising this issue
- [V] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [V] Searched [past issues](/issues)

During task upload of a tar file containing files with 0 timestamp the above exception was raised. On GUI it was written to the screen and no task was created. On CLI there was no error reported and a task with no data was created.

### Expected Behaviour
Main issue - files with timestamp should be uploaded.
Secondary issue  -  If there is a problem CLI should report the error and not create a task with no data. 

### Current Behaviour
Specified above.

### Possible Solution
A simple workaround was to change the timestamp of the files before calling the zip library.
The root cause might be that the zip library was changed. There should be a way to control the library and versions used.

The change:
![Screenshot from 2020-05-20 15-35-30](https://user-images.githubusercontent.com/61744528/82446798-fe064700-9aaf-11ea-8715-4dc8131bf3ce.png)

### Steps to Reproduce (for bugs)
1. Take any image file.
2. Change its timestamp to be earlier than 1.1.1980
3. Put it a tar archive.
4. Try to create a task with it.
5. The above exception should occur.

### Context
Images captured with a zero  timestamp cannot be uploaded.

### Your Environment
- Git hash commit (`git log -1`): cf511ae7cd2d319429445ac4a63cb32c35ea3bec (It happened with yesterday's latest develop as well)
- Docker version 19.03.9 
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem: NA
- Other diagnostic information / logs: unfortunately it was erased.

**Comment by yohayonyon** [comment]
FYI: this was not fixed on release 1.1.0

**Comment by nmanovic** [comment]
@yohayonyon , 1.1.0-beta will be released at the end of this month.

**Comment by yohayonyon** [comment]
Did not happen on v1.2.0.
