### ISSUE TITLE
Support upload data to tasks in multiple batches

### ISSUE THREAD

**Issue by LukeAI** [openvinotoolkit/cvat#1616]
I'm trying to upload a few thousand images to a CVAT task using the APU, split into jobs of 100.

If I try to upload more than a certain threshold, I get HTTP 413 error.

If CVAT accepted multiple POSTs to _cvat_url/tasks/{task_id}/data_ then I would be able to do this.

Perhaps by default, each new POST could be created as a new job.

**Comment by azhavoro** [comment]
Hi, try to change this settings https://github.com/opencv/cvat/blob/develop/cvat/settings/base.py#L405-L406

**Comment by LukeAI** [comment]
thanks a lot! Can I ask: what is the purpose of baking in hard limits?

**Comment by kaustubhharapanahalli** [comment]
@azhavoro can you make this a configurable parameter though a file that is in .gitignore so that we can keep CVAT to the latest version?

**Comment by LukeAI** [comment]
personally, being able to set it in my docker-compose.override.yml would be really handy - so all of my custom cfg is in one place.

**Comment by nmanovic** [comment]
@LukeAI , it will be supported by the PR: https://github.com/openvinotoolkit/cvat/pull/3692
