### ISSUE TITLE
Implement social/google signin in CVAT UI

### ISSUE THREAD

**Issue by arvindcyclist** [openvinotoolkit/cvat#1624]
### My actions before raising this issue
-Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
-Searched [past issues](/issues)

I am trying to implement google sign but it just redirects to the /auth/login page, seems like some conditions in the code are preventing that and the authorisation of the user is not happening.
Can someone help in how we can proceed with the google sign process.
### Expected Behaviour
google sign in should work

### Current Behaviour
google sign in does not work

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@arvindcyclist 

Hi, the redirect depends on a state of the single page application. 
When ``state.auth.user === null`` and ``state.auth.initialized === true``, the application goes to ``/auth/login``.

This check is called in ```cvat-ui/src/components/cvat-app.tsx```. The function ``verifyAuthorized();``  causes changing state depends on result of the ``/api/v1/users/self`` request

**Comment by arvindcyclist** [comment]
Hi Thanks for your quick response, It gave me an idea of how the flow goes.

In order to achieve social login , I have implemented the same from django server side, and in cvat-ui/src/components/cvat-app.tsx, I redirected to django server localhost:7000/auth/login so that I get the google sign in page.

This is the only way I can think of achieving the google sign in,  please let me know if there is any other approach to achieve it from react side.

Thanks.

**Comment by bsekachev** [comment]
@arvindcyclist 

I am not sure I understand right what you have done.

**Comment by azhavoro** [comment]
There is no response for a long time, I'll close the issue.

**Comment by athira-selvam** [comment]
Hi @arvindcyclist I am facing the same problem. Did you manage to solve it?
