### ISSUE TITLE
Feature Request: Enable creation of Chuck sizes after a task is created

### ISSUE THREAD

**Issue by kaustubhharapanahalli** [openvinotoolkit/cvat#1625]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour
1. Enable users to split a task to multiple chunks after a task is created. This will enable users to be more flexible with the process of creating a task. If a task already is divided into multiple chunks, enable a way wherein, if creation of new chunks are requested, reorder the number of images for each job based on the requested chunk size. 
2. Redirect to tasks page after creating task

### Current Behaviour
1. After a task is created, there is no option to edit the some of the task parameters like chunk size or z-order.
2. After a task gets created, the page still stays in the create task page

### Possible Solution
Add an option of editting a task.

### Steps to Reproduce (for bugs)
NA

### Context
I had created a task with lots of images on one go and I was not able to annotate them all by myself. So I asked another person to help me out and I could't modify the task. So I had to create another task with multiple splits so that if more people joined the task, I wouldn't have to create the task.

### Your Environment
- Git hash commit: 
commit 42fb305d673c33b183170ab9edf16a764444b6ac (HEAD, origin/develop, origin/HEAD)
Author: TOsmanov <54434686+TOsmanov@users.noreply.github.com>
Date:   Tue May 19 10:04:25 2020 +0300
Update item Side panel in User guide (#1513)
    * Update item Side panel in User guide
    * Removed trailing spaces in an Object sidebar item
    * Update cvat/apps/documentation/user_guide.md
    * fix typo
    * missing image correction
Co-authored-by: Nikita Manovich <40690625+nmanovic@users.noreply.github.com>

- Docker version:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by nmanovic** [comment]
@kaustubhharapanahalli , do you mean be able to add jobs on an existing task?

**Comment by nmanovic** [comment]
https://github.com/opencv/cvat/issues/125

**Comment by kaustubhharapanahalli** [comment]
@nmanovic yes, sorry for the duplicate issue. Didn't use the proper search words I guess.

**Comment by nmanovic** [comment]
@kaustubhharapanahalli , I don't think that we will allow to change existing jobs after the task is created in the nearest future. I will close the feature request.
