### ISSUE TITLE
UX: User guide for hosted cvat.org needs better navigation

### ISSUE THREAD

**Issue by SDxKeeper** [openvinotoolkit/cvat#1630]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Current [user guide](https://cvat.org/documentation/user_guide.html) which new users of the service will try to check is hard to navigate.

### Expected Behaviour

Navigation pane stays on the left and only small article from selected sections are rendered to the right pane. For example: [openvino docs](https://docs.openvinotoolkit.org/latest/index.html)

### Current Behaviour

Plain wall of text meets new users.

### Possible Solution

Use different template or tool for docs generation.

### Context

As a new user for the tool I would be disappointed by such documentation

### Your Environment

- Firefox
- Chrome

**Comment by nmanovic** [comment]
@aschernov , could you please help us to improve documentation? Let's organize a meeting to discuss specific steps.

https://pages.github.com/
