### ISSUE TITLE
Could not upload COCO annotation.  Error: Request failed with status code 500. "TypeError: unhashable type:'list'\n".

### ISSUE THREAD

**Issue by justjess-lgtm** [openvinotoolkit/cvat#1649]
I encounter this error when trying to upload COCO annotation. 
  Error: Request failed with status code 500.  "TypeError: unhashable type: 'list'\n".

I have shared here the sample images and corresponding annotation which is in COCO format. 
https://github.com/JessKamau/annotated_masks.git

### Your Environment

-cvat.org / cvat on localhost (similar response)
- Docker version `v19.03.8` 
- Windows 10
- Code example or link to GitHub repo or gist to reproduce problem: https://github.com/JessKamau/annotated_masks.git
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
The annotations file can not be parsed with official COCO API, it has wrong wrong format - `category_id` is a list.

**Comment by nmanovic** [comment]
@zhiltsov-max , could we return 400 error code with more friendly error message in such cases?

**Comment by nmanovic** [comment]
I will close the issue as invalid. We will work to improve error messages for such problems.
