### ISSUE TITLE
Wrong and non-crresponding to annotation activatedStateID

### ISSUE THREAD

**Issue by ActiveChooN** [openvinotoolkit/cvat#1653]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

`activatedStateID` should contain id that represented in annotation array

### Current Behaviour

`activatedStateID` is not null when annotation list is empty for example. Originally issue appeared in #1611 . It was partly fixed in #1647 , but need further investigation.

### Steps to Reproduce (for bugs)

1. Open job
1. Wait ~5 seconds
1. Switch to a another frame (by clicking on the player slider)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
I will close the issue as outdated.
