### ISSUE TITLE
Error when uploading Pascal Voc annotations :"Could not upload annotations for the job 4 Error: Request failed with status code 500. "Exception: Could not match item id: 'frame_421' with any task frame\n"."

### ISSUE THREAD

**Issue by MrunaliniN** [openvinotoolkit/cvat#1658]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context
Trying to upload Pascal Voc annotations (zipped) fails with the above error.

### Your Environment
- Git hash commit (`git log -1`):  commit ac922e33a51d8a0ccd4d952742ed6ea0176df824 (HEAD -> develop, origin/develop, origin/HEAD)

- Docker version `docker version` (e.g. Docker 17.0.05):  Docker version 19.03.8, build afacb8b
- Operating System and version (e.g. Linux, Windows, MacOS):  Windows
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Have you tried to name annotations like it is shown in the format description here?https://github.com/opencv/cvat/tree/develop/cvat/apps/dataset_manager/formats#voc 

If you are using `frame_<number>` form, number should be a 6-digit string with leading zeros.

**Comment by MrunaliniN** [comment]
Thanks very much for your response @zhiltsov-max . I renamed the files as frames_xxxxx and finally got a success message that annotations have been loaded. 
However, the annotations are not being shown on the image (video). Any pointers to what might be wrong? This is my xml file:
<?xml version="1.0" ?>
<annotation>
  <folder>frame</folder>
  <filename>frame_000000</filename>
  <path>path-to-jpg-folder</path>
  <source>
    <database>MINE</database>
  </source>
  <size>
    <width>1920</width>
    <height>1080</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>Vessel/ship</name>
    <occluded/>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>1546.7008733624455</xmin>
      <ymin>379.8013100436682</ymin>
      <xmax>1918.4039301310045</xmax>
      <ymax>462.2467248908298</ymax>
    </bndbox>
  </object>
</annotation>

**Comment by zhiltsov-max** [comment]
This should work. I can suggest you to try to draw some annotations and export them to see differences. 

You can paste xml without being processed using triple apostrophe ` ``` ` (code button in UI)

**Comment by MrunaliniN** [comment]
Thanks. I tried that as well. Here is my xml file :
```
<?xml version="1.0" ?>
<annotation>
  <folder>frame</folder>
  <filename>frame_000000</filename>
  <path>path-to-jpeg-images</path>
  <source>
    <database>MINE</database>
  </source>
  <size>
    <width>1920</width>
    <height>1080</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>Vessel/ship</name>
    <occluded/>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>1546.7008733624455</xmin>
      <ymin>379.8013100436682</ymin>
      <xmax>1918.4039301310045</xmax>
      <ymax>462.2467248908298</ymax>
    </bndbox>
  </object>
</annotation>

```

Apart from the header string with xml version number & the "path" tag, I really did not see any difference between what cvat saved versus my files. 
Maybe I will try removing those from my files as well... anything else catching your eye?
I had also added all labels to the cvat task before importing .... did I need to add those attributes (occluded/pose/truncated/difficult)  to each label as well?

**Comment by zhiltsov-max** [comment]
Not really. Have you used the `framestep` option when created the task?

**Comment by nmanovic** [comment]
@MrunaliniN ,  I will close the issue as outdated. Don't hesitate to reopen it if you still can reproduce the issue.
