### ISSUE TITLE
Support image filtration by objects

### ISSUE THREAD

**Issue by 4sfaloth** [openvinotoolkit/cvat#169]
I think it would be useful to allow intersection operation outside square brackets in filters, similar to what we can do with the union operator |

Example of what I mean:
objectA & objectB & objectC[attr/status="valid"]

This filter would ignore all images in which objectC is not present or does not have the "valid" status. However, for such images it would display objectC as well as objectA and objectB

**Comment by nmanovic** [comment]
It can be implemented by several requests: find frames with objectA, find frames with objectB, find frames  with objectC[attr/status="valid"]. Intersect results.

**Comment by nmanovic** [comment]
I will close the issue as outdated. Filters were significantly redesigned.

**Comment by nmanovic** [comment]
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/filter/
