### ISSUE TITLE
Can't export dataset when task has 18k images

### ISSUE THREAD

**Issue by ghost** [openvinotoolkit/cvat#1765]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)
I tried multiple machines to ensure we have enough ram.

We have a task with 18k frames in it. But when I click on Export as a dataset and select TF OD API, it throws 503 (no upstream header error). For 4k frames, we needed 32gb ram. Do you have any suggestions why is it not working for 18k? or any suggestions on how we can improve it?
Thanks

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Hi, can you give your CVAT version number as described in the issue template?

**Comment by zhiltsov-max** [comment]
This might have been fixed with recent updates, please check if this problem persists.
