### ISSUE TITLE
Import labels when creating task

### ISSUE THREAD

**Issue by edurenye** [openvinotoolkit/cvat#1768]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour
When creating a new task I expect to be able to upload a bunch of images with their labels in labelMe xml files like you can do using app.roboflow.ai.

### Current Behaviour
It just imports the images.

### Steps to Reproduce (for bugs)

1. Have images with their labelMe xml files, one for each image.
2. Create a task.
3. Add the labels (would be nice to also get them from the xml files)
4. Upload all files from dataset folder containing images and xml files.
5. Submit task.

### Context
I have a dataset partially labeled using labelMe I want to easily import it without having to rename id's and stuff to be able to import, and of course I don't want to import file by file, I want to import all at once.

### Your Environment

- Git hash commit (`git log -1`): 07de7141edbc980031da857579128088f7a4630a
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.11
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by fedex-coder** [comment]
I join to this enhancement request.
I have a .json COCO file with a bunch of labels and annotations in it.
I upload images, but when i try to upload annotations file, the upload fails untill i add labels manually. 
It would be great if they could be added automatically once uploaded annotation file.

**Comment by getcontrol** [comment]
+1 this is a huge limitation of CVAT

**Comment by ysohma** [comment]
+1

**Comment by ActiveChooN** [comment]
Could be partly resolved by #3790 by importing the dataset as a project.
