### ISSUE TITLE
Is it possible to labeling images with keypoint and panoptic type?

### ISSUE THREAD

**Issue by charlescho64** [openvinotoolkit/cvat#1784]
### My actions before raising this issue
- [ V] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ V] Searched [past issues](/issues)

I try to label some object with keypoints and panoptic types, but I can't find any solution on CVAT.
currently I have to integrate some automatic labeling tool into CVAT and I integrated bounding box and semantic segmentation method, but I not yet find a way to import keypoint and panoptic result came from automatic labeling tool to CVAT for editing by human  and exporting final data.

**Comment by zhiltsov-max** [comment]
Keypoints and panoptic COCO formats are not fully supported yet. 

Keypoints are not supported, but they can be imported as just points with `COCO` format import and then they can be exported with [Datumaro](https://github.com/opencv/cvat/tree/develop/datumaro) to COCO format, but they won't contain categories and visibility properties. 

RLE instance segmentation from COCO instances/stuff and VOC png segmentation masks are supported, but not COCO panoptic.

**Comment by nmanovic** [comment]
I believe COCO keypoints and panoptic are supported now: https://openvinotoolkit.github.io/datumaro/docs/formats/coco/

I will close the issue.
