### ISSUE TITLE
Problems with tfrecords when Frame skip is used

### ISSUE THREAD

**Issue by savan77** [openvinotoolkit/cvat#1814]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

There seems to be a problem with tfrecords when you set Frame skip equals to something while creating a task. The dumped records seem to be corrupted and you can't train a model using it as Tensorflow throws Unable to decode bytes error. I confirmed this by creating multiple tasks, one with Frame skip set and one without it. The one without Frame skip worked.
Apart from that, there also seems to be an issue with tfrecords when you have so many empty frames. For example, we annotated every 7th frame in a video and it seems the tfrecord is corrupted. I can confirm this by looking into the tfrecords. We annotated 488 frames in total, but tfrecords had more than 3400 examples.

### Expected Behaviour

Tfrecords should not be corrupted and should work while training the model.

### Current Behaviour

Here is the error I get when trying to train,

`INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
[[{{node case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert}}]]
[[{{node IteratorGetNext}}]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]`

### Possible Solution

There might be something wrong with the way CVAT dumps tfrecords when there is Frame Skip set. 

### Steps to Reproduce (for bugs)

1. Create a task with video and set Frame skip to something (i.e 7 in our case)
2. Dump annotation in tfrecord format
3. Train a model using Tensorflow Object Detection API
4. You will get an error.

### Context

I was trying to train a model on it.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Could you please check if using TF 1.14 in the CVAT container solves the problem? We've updated recently to the newer 2.20 version and some regressions are possible.

**Comment by zhiltsov-max** [comment]
Could you specify how did you export your annotations? Did you use "export as a dataset"? Can you specify your CVAT version?

**Comment by savan77** [comment]
Hi @zhiltsov-max thanks. I checked TF version, it's 1.15.2. And yes, I used "export as a dataset". But note that I export this using Python. Here is a code snippet that I use.

```
with tempfile.TemporaryDirectory() as test_dir:
	project.export("cvat_tfrecord", test_dir, save_images=True)
```

**Comment by zhiltsov-max** [comment]
It looks like you're using an outdated version of CVAT. Could you check with some recent version?

**Comment by savan77** [comment]
Thanks, I will try that. Just FYI, I downloaded CVAT 2 months ago.

**Comment by zhiltsov-max** [comment]
Closing as no response for a long time.

**Comment by janmejaya-nanda** [comment]
@zhiltsov-max  apology for the delay. I completely missed this one.
We cloned the CVAT repo and hosted it on [e2-standard-4](https://cloud.google.com/compute/docs/general-purpose-machines#e2_machine_types) machine. for hosting we used [cvat/docker-compose](https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.yml). 
Regarding task:
 I am using [opensource fashionpedia](https://github.com/cvdfoundation/fashionpedia#images) data and split it into different chunks to create tasks. (we did this process of creating different Tasks using CVAT v1 (../api/v1/...) API.)

**Comment by zhiltsov-max** [comment]
@janmejaya-nanda, which CVAT version are you using? Which error do you see exactly? The original issue reported several problems.

**Comment by janmejaya-nanda** [comment]
we are using "release 1.6.0" and during training, some of our tfrecord fails with the below error. So it suggests some of the tfrecord have this issue. I have cross-checked all my images( as these are standard [fashionpedia](https://github.com/cvdfoundation/fashionpedia#images) images) for other than JPG or corrupt images, but all looks good over there. 
`INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP] [[{{node case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert}}]] [[{{node IteratorGetNext}}]] INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]`
