### ISSUE TITLE
CVAT new UI: hotkeys don't work when CapsLock is turned on

### ISSUE THREAD

**Issue by aschernov** [openvinotoolkit/cvat#1839]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

All hotkeys should work instead of Capslock is turned on or not
### Current Behaviour

Hotkeys don't work when Capslock is turned on. For example, moving to the next\previous frame (f,d); saving (ctrl+s), drawing new objects (n), and so on.
### Steps to Reproduce (for bugs)

1. Open a CVAT job
1. Turn on the CapsLock button and try to use the hotkeys
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Related #1341

It is a problem of library we use: ``react-hotkeys``, not CVAT.
I've created issue: https://github.com/greena13/react-hotkeys/issues/283
Let's wait for the answer and then will decide what to do.
