### ISSUE TITLE
Some annotations are not saving randomly

### ISSUE THREAD

**Issue by rnekk2** [openvinotoolkit/cvat#1857]
### My actions before raising this issue
- [ Done] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [Done ] Searched [past issues](/issues)

### Expected Behaviour

When we save the annotations for a specific task it should save all annotations

### Current Behaviour

When we save annotations randomly it is failing to save annotations for some images. . We are having to redo those images 

### Steps to Reproduce (for bugs)
 It is happening very randomly. 
1.
1.
1.
1.

### Context
 When we try to look back at the work we are doing, we are seeing some annotations are not being saved.

### Your Environment

- Git hash commit (`git log -1`):
cheling@cheling-ubuntu1604:~/cvat$ git log -1
commit 80ed45b4527c7560748660be02544b9c7fd69711
Author: zhiltsov-max <zhiltsov.max35@gmail.com>
Date:   Tue Jun 30 06:07:20 2020 +0300

    Allow attributes in COCO format (#1782)
    * allow attributes in coco
    * update changelog
    * update cli
    * update coco cli
- Docker version `docker version` (e.g. Docker 17.0.05):  5:19.03.1~3-0~ubuntu-xenial  
- Are you using Docker Swarm or Kubernetes?
No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 16.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Hello, can you describe which format do you use and which annotations are missing? Is it whole images or just some annotations?

**Comment by rnekk2** [comment]
@zhiltsov-max we use bounding box annotations. The process we use is pre annotate our dataset with our custom object detection model and build the annotations XML file and upload to CVAT. After that we use CVAT to fix any false positives. What we are seeing is randomly even though we are making changes to the false positive bounding boxes and save. It is saving successfully without any issues. When we look at our previous images, we are seeing randomly for some images the changes we made previously are not showing up. It is still showing the same false positives as before.

**Comment by zhiltsov-max** [comment]
If I understand correctly, you are fixing annotations, then saving them, and then UI shows old annotations? What about exporting annotations at this point? Can you compare the files and check if the annotations changed?

**Comment by rnekk2** [comment]
That is correct. Let me compare the annotation files and get back to you.

**Comment by rnekk2** [comment]
@zhiltsov-max I have verified. The issue is the annotations are not saving after making the changes. Does not seem like a UI issue. I downloaded the annotation file and uploaded to another task with the same images. The changes are not reflecting.

**Comment by zhiltsov-max** [comment]
Ok, could you specify which format are you using?

**Comment by rnekk2** [comment]
We are using CVAT XML bounding box annotations.

**Comment by rnekk2** [comment]
@zhiltsov-max any update on this ? We are also seeing sometimes once we save the annotations it shows as saved but when I open a new tab and see those changes are not being reflected.

**Comment by nmanovic** [comment]
@rnekk2 , could you please help us to reproduce it?

**Comment by rnekk2** [comment]
@nmanovic It is happening very randomly. I have a screen recording to show the issue we are seeing. It is 32 MB. Is there a way to send you the screen recording as the max size of file to attach is only 10 MB.

Here is the CVAT version information:



Server version: 1.1b0

Core version: 3.1.1

Canvas version: 2.0.1

UI version: 1.6.2

**Comment by zhiltsov-max** [comment]
I think you can convert it to a gif animation and greatly reduce the size. It feels like some server or UI problem, can you check the server and  the browser console for errors?

@bsekachev, @azhavoro, please, take a look.

**Comment by bsekachev** [comment]
Let's start with a GIF. It would be great also to see bodies of requests that sent to the server when you save annotations and the issue is reproduced.

**Comment by bsekachev** [comment]
@rnekk2 
Any updates here?

**Comment by zhiltsov-max** [comment]
Closing as no response for a long time.
