### ISSUE TITLE
Data is not getting cleared, even after deleting the Task from Django Admin App

### ISSUE THREAD

**Issue by dev225reddys** [openvinotoolkit/cvat#1925]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Data Related to the Specific Task should be cleared if Task is Deleted

### Current Behaviour

Data from Docker Container "CVAT" /data/data and /data/tasks not getting Cleared even after deleting a task from Django Admin App. 

### Possible Solution

Delete the Task Specific Data from Container if Task itself is deleted

### Steps to Reproduce (for bugs)

1. Delete a Task from Django Admin App
1. Data is still present in CVAT Container

### Context

Deleting a Task is to Clear the Data, to save some space. In this Scenario, The Data is not being Cleared as i clear the Task. 

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 19.03.8, build afacb8b7f0
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04 LTS

**Comment by katab** [comment]
Hi, I experienced the same issue when deleting tasks from the Admin site. I understand that you will fix this in a coming release. However, how do I get rid of the data belonging to these tasks that have already been deleted via the Admin site? I have (successfully) deleted the data entries from engine_data and related tables, but the data is not deleted from the disk. Is this expected? 
BR Katarina

**Comment by sonuranjitjacob** [comment]
Hi, I'm facing the same issue. On navigating to the cvat_cvat_data folder on my system, I can still see the job ids of the tasks I had already deleted as shown below and this takes up most of the space on my system as well. 

```
root@user:/var/lib/docker/volumes/cvat_cvat_data/_data# sudo du -chd 1 | sort -h
4.0K	./models
48K  	./projects
324K	./cache
181M	./tasks
155G	.
155G	./data
155G	total


root@user:/var/lib/docker/volumes/cvat_cvat_data/_data/data# ls
100  102  104  106  108  115  117  119  121  123  44  46  48  50  52  72  74  76  78  80  82  84  86  88  90  92  94  96  98
101  103  105  107  113  116  118  120  122  43   45  47  49  51  71  73  75  77  79  81  83  85  87  89  91  93  95  97  99
```

**Comment by vroooomm** [comment]
try docker system prune
