### ISSUE TITLE
How to import MOT file with det filedir?

### ISSUE THREAD

**Issue by Momofilm** [openvinotoolkit/cvat#1948]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
I used the MOT format to import my annotation project, which I wanted should like MOT, but the MOT was lack of the dt files like standard MOT dataset to verify my training result. How could I get this kind of data from my annotation?
For example, chart below is I expected.
MOT16/
├── test
│   ├── MOT16-01
│   │   ├── det
│   │   │   └── det.txt
│   │   ├── img1
│   │   │   ├── 000001.jpg
│   │   │   ├── xxxxxx.jpg
│   │   │   └── 000450.jpg
│   │   └── seqinfo.ini
│   ├── MOT16-03
│   ├── MOT16-06
│   ├── MOT16-07
│   ├── MOT16-08
│   ├── MOT16-12
│   └── MOT16-14
│
└── train
    ├── MOT16-02
    │   ├── det
    │   │   └── det.txt
    │   ├── gt
    │   │   └── gt.txt
    │   ├── img1
    │   │   ├── 000001.jpg
    │   │   ├── xxxxxx.jpg
    │   │   └── 000600.jpg
    │   └── seqinfo.ini
    ├── MOT16-04
    ├── MOT16-05
    ├── MOT16-09
    ├── MOT16-10
    ├── MOT16-11
    └── MOT16-13

### Current Behaviour
There is the files format which I get from MOT1.1 annotation, it was lack of det files. Could this be solved in some ways? I hope someone could tell me. Thanks a lot.
MOT16/
├── test
│   ├── MOT16-01
│   │   ├── img1
│   │   │   ├── 000001.jpg
│   │   │   ├── xxxxxx.jpg
│   │   │   └── 000450.jpg
│   │   └── seqinfo.ini
│   ├── MOT16-03
│   ├── MOT16-06
│   ├── MOT16-07
│   ├── MOT16-08
│   ├── MOT16-12
│   └── MOT16-14
│
└── train
    ├── MOT16-02
    │   ├── gt
    │   │   └── gt.txt
    │   ├── img1
    │   │   ├── 000001.jpg
    │   │   ├── xxxxxx.jpg
    │   │   └── 000600.jpg
    │   └── seqinfo.ini
    ├── MOT16-04
    ├── MOT16-05
    ├── MOT16-09
    ├── MOT16-10
    ├── MOT16-11
    └── MOT16-13

**Comment by zhiltsov-max** [comment]
Hi, this is not supported, but you can try to add an additional directory manually here: https://github.com/opencv/cvat/blob/develop/datumaro/datumaro/plugins/mot_format.py#L250

**Comment by Momofilm** [comment]
> Hi, this is not supported, but you can try to add an additional directory manually here: https://github.com/opencv/cvat/blob/develop/datumaro/datumaro/plugins/mot_format.py#L250

Thanks for your answer. The confidence in cvat/mot_format.py is about 0-1, however, which in MOT dt file is floating number. This could influence the results? Or I could change it by somways.

**Comment by zhiltsov-max** [comment]
`confidence` is parsed as a floating point number, you can see it here: https://github.com/opencv/cvat/blob/develop/datumaro/datumaro/plugins/mot_format.py#L184

If you want to see and modify this field in a CVAT task, add a label attribute with the same name.

**Comment by Momofilm** [comment]
> `confidence` is parsed as a floating point number, you can see it here: https://github.com/opencv/cvat/blob/develop/datumaro/datumaro/plugins/mot_format.py#L184
> 
> If you want to see and modify this field in a CVAT task, add a label attribute with the same name.

It means I must revise the original cvat code, then rebuild the cvat docker? Isn't it?

**Comment by zhiltsov-max** [comment]
Yes, you're right.

**Comment by Momofilm** [comment]
Thanks for your advice.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhiltsov-max"<notifications@github.com&gt;; 
发送时间: 2020年7月29日(星期三) 晚上8:39
收件人: "opencv/cvat"<cvat@noreply.github.com&gt;; 
抄送: "FILM JACK"<977925110@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [opencv/cvat] How to import MOT file with det filedir? (#1948)





 
Yes, you're right.

**Comment by Momofilm** [comment]
I tried to revise the code you have raised, but it didn't work.&nbsp;
I add the 'def find_subsets(path):' in line 245 and in line 267 of 'mot_format.py'. Like below,
1. def find_subsets(path):         subsets = []         if path.endswith('.txt') and osp.isfile(path):             subsets = [path]         elif osp.isdir(path):             p = osp.join(path, 'gt', MotPath.GT_FILENAME)             if osp.isfile(p):                 subsets.append(p)             p1 = osp.join(path, 'dt', MotPath.DET_FILENAME)             if osp.isfile(p):                 subsets.append(p1)         return subsets


2. det_dir = osp.join(save_dir, 'dt')         os.makedirs(det_dir, exist_ok=True)         det_file = osp.join(det_file, Mot_Path.DT_FILENAME)
&nbsp;with open(det_file, 'w', encoding="utf-8") as csv_file:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; writer = csv.DictWriter(csv_file, fieldnames=MotPath.FIELDS)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; track_id_mapping = {-1:-1}
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for idx, item in enumerate(extractor):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; log.debug("Converting item '%s'", item.id)


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; frame_id = cast(item.id, int, 1 + idx)


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for anno in item.annotations:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if anno.type != AnnotationType.bbox:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; continue
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; track_id = -1
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; writer.writerrow({
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'frame_id': frame_id,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'track_id': track_id,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'x': anno.x,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'y': anno.y,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'w': anno.w,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'h': anno.h,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'confidence': float(anno.attributes.get('score'))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'class_id': -1,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'visibility':-1
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; )









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhiltsov-max"<notifications@github.com&gt;; 
发送时间: 2020年7月29日(星期三) 晚上8:39
收件人: "opencv/cvat"<cvat@noreply.github.com&gt;; 
抄送: "FILM JACK"<977925110@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [opencv/cvat] How to import MOT file with det filedir? (#1948)





 
Yes, you're right.

**Comment by bsekachev** [comment]
Hi @zhiltsov-max, what is status of the issue?

**Comment by zhiltsov-max** [comment]
```diff
datumaro/plugins/mot_format.py

             p = osp.join(path, 'gt', MotPath.GT_FILENAME)
             if osp.isfile(p):
                 subsets.append(p)
+            p = osp.join(path, 'det', 'det.txt')
+            if osp.isfile(p):
+                subsets.append(p)
         return subsets
```

Allows successfully upload detection files from the official MOT17 demo (remember to set a class in the annotations, field 8):

Example file: [test_anno.zip](https://github.com/openvinotoolkit/cvat/files/5267361/test_anno.zip)
