### ISSUE TITLE
Support to Resolve ID Switches For Tracking Applications

### ISSUE THREAD

**Issue by mmaaz60** [openvinotoolkit/cvat#1976]
Dear Team,

ID Switch is a common problem in tracking applications. And while preparing ground truths for tracking applications, the human annotators may create this error and later during revision it will be too difficult to resolve id switch as it will involve re-annotating the tracks from scratch or manually switching the tracks for each keyframe. I guess this process can be automated, while the code can switch labels between two tracks after the mentioned frame number.

I think this feature is vital for tracking applications and will reduce huge efforts the annotators waste in fixing the id switches.

Best Regards,
M. Maaz

**Comment by mmaaz60** [comment]
The solution can be found at https://github.com/mmaaz60/cvat_id_switch_solution

**Comment by nmanovic** [comment]
@mmaaz60 , I'm not sure I understand your request. We have ability to split and merge tracks. If you have 2 tracks, you always can merge them into one without reannotation. I will close the issue as outdated.
