### ISSUE TITLE
Downloaded xml's have unexpected tokens at top. 

### ISSUE THREAD

**Issue by Boazrciasn** [openvinotoolkit/cvat#1982]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Annotations have unexpected tokens at top when downloaded via api in `CVAT XML 1.1 for videos` format. Downloading from UI has no issues.

### Expected Behaviour

Downloaded annotations should not contain unexpected tokens. 

### Current Behaviour

Downloaded annotations have unexpected tokens at the top of the xml file. 

### Steps to Reproduce (for bugs)

1. Download a tasks annotations via rest api.

### Context

Downloading a batch of annotations is practical via api, and useful in automating the process. 

### Your Environment

- CVAT alpha build 1.1.0
- OS : Centos 8

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@Boazrciasn , could you please provide a command which you used to download annotations using REST API? If you can attach bad files, it will help as well.

**Comment by Boazrciasn** [comment]
I have downloaded with the following function in the cli,

```python
def tasks_dump(self, task_id, fileformat, filename, **kwargs):
        """ Download annotations for a task in the specified format
        (e.g. 'YOLO ZIP 1.0')."""
        url = self.api.tasks_id(task_id)
        response = self.session.get(url)
        response.raise_for_status()
        response_json = response.json()
        url = self.api.tasks_id_annotations_filename(task_id,
                                                     response_json['name'],
                                                     fileformat)

```


Where, ` fileformat='CVAT for video 1.1' `, I cannot attach xml file I guess(I am kind of new to this sorry.), so I have zipped a single annotation xml file.

[annotion_bug.xml.zip](https://github.com/opencv/cvat/files/5023316/annotion_bug.xml.zip)

**Comment by nmanovic** [comment]
@Boazrciasn , what is wrong in the attached file?

**Comment by Boazrciasn** [comment]
There is undefined tokens at top and bottom of the xml. Therefore, the xml file is corrupted, you cannot read it. If you download and open it you would see that there is annotations, but it has undefined tokens at the start and at the end thus nothing shows up. Undefined tokens appear in first and the last line in the following structure `UNDEFINED_TOKENS<?xml version="1.0" encoding="utf-8"?>` line at top and `UNDEFINED_TOKENS</annotations>` at the end. The undefined tokens are as follows but it does not show up in markdown format. Best way to see is to open it in an text editor, however, if you try to open it with xml extension most of the editors that recognize xml's will show garbage I would suggest changing the extention to txt and opening it in a simple text editor.

```
PK

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please look?

**Comment by zhiltsov-max** [comment]
Does any other format have the same problem? COCO, for example.

**Comment by Boazrciasn** [comment]
Yes, COCO format also has undefined tokens. I will switch to beta or a previous version as I do not heave much time though. Can update if the problem persists.

**Comment by Boazrciasn** [comment]
Response text contains them too by the way. Response is broken there is no issue while saving the xml.

**Comment by zhiltsov-max** [comment]
Is it possible that the platform you use has `windows-1254 "Turkish"` character encoding by default (or anything else than `utf-8`)? It looks like this can be the source of the issue.

**Comment by Boazrciasn** [comment]
By platform you mean that the mahcine VM is installed?

**Comment by zhiltsov-max** [comment]
I think, there are few ways to fix this:
- [Specify `PYTHONIOENCODING=utf8` or `PYTHONUTF8=1` or `-X utf8`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8) for python interpreter
- Explicitly set `encoding='utf-8'` when writing files in the source code
- Check out `LC_ALL` env. var or set system locale with `localectl set-locale LANG=en_US.utf8`

**Comment by Boazrciasn** [comment]
All right thanks for the information, I will post a stable solution here. I think the perma solution is to set header encoding from requests.Session().

**Comment by Boazrciasn** [comment]
response header content type appears as 'application/zip' , shouldn't it be something different?
I cannot encode the byte array to utf-8

**Comment by bsekachev** [comment]
Hi @zhiltsov-max, what is status of the issue?

**Comment by katab** [comment]
I experience the same issue when exporting annotations with the CLI. I tried some of @zhiltsov-max recommended solutions (specifying PYTHONIOENCODING=utf8 and PYTHONUTF8=1 as well as setting LANG=C.UTF-8) but neither has solved the issue for me. 

Are you working on a solution to this issue?

Kind regards, Katarina

**Comment by Boazrciasn** [comment]
Hello Katarina,
I have found out that downloaded files are zip files. You can save it then
unzip the file and save again. It ia not the best solution though. Let me
send you a code snippet in an hour.

Best
Barış

**Comment by Boazrciasn** [comment]
Hello Katarina,
I have found out that downloaded files are zip files. You can save it then
unzip the file and save again. It is not the best solution though but you can use the following code if you like to directly dump to xml. You need the `zipfile` package. You should change the same named function of CLI class.

```python3

    def tasks_dump(self, task_id, fileformat, filename, **kwargs):
        """ Download annotations for a task in the specified format
        (e.g. 'YOLO ZIP 1.0')."""
        url = self.api.tasks_id(task_id)
        response = self.session.get(url)
        response.raise_for_status()
        response_json = response.json()

        url = self.api.tasks_id_annotations_filename(task_id,
                                                     response_json['name'],
                                                     fileformat)
        while True:
            response = self.session.get(url)
            response.raise_for_status()
            if response.status_code == 201:
                break

        response = self.session.get(url + '&action=download')
        response.raise_for_status()
        fbytes = BytesIO(response.content)
        zipf = ZipFile(fbytes)
        with codecs.open(filename, 'wb') as fp:
            fp.write(zipf.read('annotations.xml'))
```

Best
Barış

**Comment by katab** [comment]
Thank you @Boazrciasn for your help, very appreciated! I tried your solution and it works fine.

Is the current behaviour expected (the fact that the downloaded files are zip files) or will this be addressed going forward?

BR Katarina

**Comment by zhiltsov-max** [comment]
The files are the same as in UI - zip archives. It is not planned to change in foreseeable future.

**Comment by katab** [comment]
Ok thanks for your answer @zhiltsov-max, appreciate it.

**Comment by azhavoro** [comment]
I suppose the issue is resolved and can be closed.
