### ISSUE TITLE
Serverless component nuclio doesn't support nvidia-docker / GPU acceleration.

### ISSUE THREAD

**Issue by mhe-wyze** [openvinotoolkit/cvat#1997]
I've just created this issue ticket under their repo.
https://github.com/nuclio/nuclio/issues/1781

Meanwhile, is there anyone knows besides asking nuclio's cooperation, do we have another quick solution for this?
Thanks for your help ahead.

**Comment by nmanovic** [comment]
@mhe-wyze , thanks!

**Comment by mhe-wyze** [comment]
Hi, @nmanovic thanks for your help on this issue, the problem has been solved by changing the docker config file.
/etc/docker/daemon.json
from
```
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```
to
```
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

**Comment by veer5551** [comment]
Hello,

Any update on using/configuring the GPU for the deployed models on the CVAT using nuclio?
Currently, it is taking a considerable large amount of time. So assuming its running on CPU!

Thanks a lot!

**Comment by charlescho64** [comment]
Hello @mhe-wyze  @nmanovic 

I can't find /etc/docker/daemon.json after installing cvat in ubuntu. 
Please let know how to use GPU in models.

**Comment by mhe-wyze** [comment]
daemon.json is docker file @charlescho64 , did you forget to install the docker or nvidia-docker?

**Comment by charlescho64** [comment]
Hi @mhe-wyze 

I installed following instruction guide " Ubuntu 18.04 (x86_64/amd64) 
 - https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md "

If I use GPU in severless model on my desktop which have 2 GPUs, how to set up?

**Comment by nmanovic** [comment]
@charlescho64 , @mhe-wyze , it was implemented. Please see documentation: https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/#gpu-support
