### ISSUE TITLE
HTTPS in Swagger

### ISSUE THREAD

**Issue by StellaASchlotter** [openvinotoolkit/cvat#2006]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I set up my CVAT instance to use https. This works well. However on api/swagger i can't select the https scheme. This prevents me to try out the api endpoints there. I can however run the curl requests from my terminal with https. 

### Expected Behaviour
I expected that swagger uses the same protocol the site uses it self.

### Current Behaviour
All generated curl requests use http. Also I can't select https in the scheme dropdown on the top of the swagger page.

### Possible Solution
A possible workaround is to modify urls.py in `cvat/apps/engine` to include the site url:

```
schema_view = get_schema_view(
   openapi.Info(
      title="CVAT REST API",
      default_version='v1',
      description="REST API for Computer Vision Annotation Tool (CVAT)",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="nikita.manovich@intel.com"),
      license=openapi.License(name="MIT License"),
   ),
   url='https://<my site>/api/v1/',
   public=True,
   permission_classes=(permissions.IsAuthenticated,),
)
```
This will set the protocol to https. But then you can't select http.

### Steps to Reproduce (for bugs)
1.  set up cvat with https as described in the installation guide
1. go to the /api/swagger endpoint 
1. authorize and try any of the api endpoints

### Your Environment
- Git hash commit (`git log -1`): 000e9c4d
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.12
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by anderflash** [comment]
Same here. The server is exposed as HTTPS, but I can't select it on Swagger. So I get NetworkError for all requests.

**Comment by StellaASchlotter** [comment]
@anderflash could my workaround help you?

**Comment by nmanovic** [comment]
@Marishka17 , could you please look at the issue and fix?

**Comment by Marishka17** [comment]
@nmanovic, yes, sure
