### ISSUE TITLE
image compressing

### ISSUE THREAD

**Issue by NAcvat** [openvinotoolkit/cvat#2023]
Hi! 
Is there a way to display on cvat the original img? (cvat is 'smoothing' the pixels and I want to see the pixels when I zoom in)
Can you add a switch between compressed and original image?

**Comment by AmitN1212** [comment]
> Hi! Is there a way to display on cvat the original img? (cvat is 'smoothing' the pixels and I want to see the pixels when I zoom in) Can you add a switch between compressed and original image?

Did you succeed doing it eventually?

**Comment by nmanovic** [comment]
@NAcvat , it was implemented.

https://github.com/openvinotoolkit/cvat/pull/3933
