### ISSUE TITLE
The auto-annotation back-end seems single threaded.

### ISSUE THREAD

**Issue by mhe-wyze** [openvinotoolkit/cvat#2027]
I tried to change maxWorkers from 2 to 10, the task running speed seems not changed.
I tried to execute multiple auto-annotation parallelly, there's only one thread was working, others were just waiting there.
I tried to login using another account, then my task was also blocked as long as there's another single task was running.

Is this a fine-tune/TODO feature in the future?

@nmanovic thanks for your help again.

**Comment by nmanovic** [comment]
@mhe-wyze , I will suggest discussing these questions on our gitter channel and if replies are not sufficient, submit a PR.
