### ISSUE TITLE
Error: Request failed with status code 500. "<h1>Server Error (500)</h1>".

### ISSUE THREAD

**Issue by Sunhil** [openvinotoolkit/cvat#2042]
I cannot create any new task, today. Howerver, I can create new tasks successfully in previous. As I fill a new task and I press "submit" a always get this message. 
And I have tried [this](https://github.com/opencv/cvat/issues/919#issuecomment-575523527) solution which have  no effect. 
![image](https://user-images.githubusercontent.com/31230937/90377577-c016c000-e0aa-11ea-81af-fd3cd3141e86.png)
Please help me.
Thank You

**Comment by nmanovic** [comment]
@Sunhil , please describe your problem in non-emotional way.  By the description "something doesn't work", nobody will be able to help. If you follow the issue template, provide server logs, it will help a lot. Together we will find a solution.

**Comment by bsekachev** [comment]
I will close the issue since there aren't any response from you. 
Please, do not hesitate reopen if you are still experiencing it.
