### ISSUE TITLE
Predict annotations locally and upload vs upload images and predict in CVAT

### ISSUE THREAD

**Issue by davodogster** [openvinotoolkit/cvat#2060]
Hi CVAT Team, I'm a big fan of the model assisted annotation and have been converting my TFOD1 models to OpenVINO to use them for assisted annotation in a previous version of CVAT.

However, you have the upload annotations feature which means that if we can get our data into the correct format, e.g Pascal VOC or YOLO, and put it in a zip file then we can upload model assisted annotations from absolutely any object detection model that we can run locally.

Uploading annotations works with both Pascal and YOLO - I've tried it by dumping annotations from CVAT and then re-uploading them. I've noticed that the YOLO ZIP folder must be called "data" whereas the Pascal VOC folder can be called anything. Have also discovered that if you select upload pascal and chose YOLO format annotations, it doesn't throw any error (also doesn't work of course). I'm not using the latest version though - I installed CVAT earlier in the year.

Do you have a preference over one of these approaches and have you thought about conversion scripts (e.g raw preds to pascal voc format) for when people predict bboxes and categories outside CVAT?

Cheers,
Sam

**Comment by davodogster** [comment]
> Hi. I'm not sure I understood the question correctly, but there is no preference - you can use any method, which fits your case best:
> 
> * You can upload annotations obtained by any method using one of the [supported formats](https://github.com/opencv/cvat/tree/develop/cvat/apps/dataset_manager/formats)
> * You can upload images, a model, and run auto annotation inside CVAT
> 
> If you are interested in dataset conversion tools, take a look at our [Datumaro project](https://github.com/opencv/cvat/tree/develop/datumaro#examples), which can convert between many formats and do other useful things.

Thanks, Yes I've done both of those bullet points before. 
When I talk about conversion scripts I'm talking about converting raw model output with the bounding boxes, scores, and class labels from TFOD into Pascal and/or YOLO annotations which can be uploaded to CVAT which gives model assisted annotation without the trouble (we used to have to convert our model to OpenVINO format for CVAT) of uploading a model to CVAT.

**Comment by zhiltsov-max** [comment]
I think, there is no specific integration with TFOD yet, however, there is an opportunity to implement it after other [TF models like this] (https://github.com/opencv/cvat/tree/develop/serverless/tensorflow/faster_rcnn_inception_v2_coco/nuclio), please check if it could help.

**Comment by davodogster** [comment]
> I think, there is no specific integration with TFOD yet, however, there is an opportunity to implement it after other [TF models like this](https://github.com/opencv/cvat/tree/develop/serverless/tensorflow/faster_rcnn_inception_v2_coco/nuclio), please check if it could help.

Looks good but I don't know anything about serverless functions. I think some documentation or a tutorial for classical TFOD models like faster RCNN, mask RCNN would help CVAT users.

**Comment by zhiltsov-max** [comment]
@nmanovic, please, answer here.

Basically, you need to put TFOD into a Docker container and provide a simple wrapping script to invoke inference with TFOD for a single image.

**Comment by nmanovic** [comment]
@davodogster , I agree that we need a tutorial how to implement a serverless function. For now you can just look at the code as an example: https://github.com/opencv/cvat/tree/develop/serverless/tensorflow/faster_rcnn_inception_v2_coco/nuclio

Don't hesitate ask a specific question. I will be glad to answer.

**Comment by bsekachev** [comment]
Tutorial is in a progress #3124
