### ISSUE TITLE
Make importing of .xml easier / simplify label deletion / editing

### ISSUE THREAD

**Issue by cstamatopoulos** [openvinotoolkit/cvat#2066]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Currently the only way to edit a label is through the admin panel which is OK for a single project.
Many times various projects share labels (especially on videos where only 1 per project is allowed) and a typo is possible. This makes the editing of labels hard since it has to be done on a per project basis.

Additionally, while trying to find workarounds I stumbled upon difficulties in deleting labels.

### Expected Behaviour

There are couple of ways to make it easier

1. Ability to edit a label across all projects (might be to hard using the UI and not really a widely used feature).
2. Provide the ability to rename labels using the cmd line utility so that one can iterate through projects and provide a list of old_label, new_label pairs.
3. Another option is to export the CVAT xml, fix the labels and import the corrected .xml. However the labels from the imported xml are ignored and instead the project ones are the ones used. So labels have to first be deleted. Deleting labels is also a pain and has to be done one by one on a per project basis. A "Select all" checkbox would be nice in the admin panel rather than having to select one by one. This is really equivalent to deleting the project and starting from scratch, the only benefit is that you save re-uploading the data, the disadvantage is that you still have to repeat it per project. Once labels are deleted it is possible to import the corrected xml so long as the labels are first added to the project. One can easily write a script to generate a json file from the xml label file. But is not that a duplication ? The labels are already there, why not import them first and then continue with importing annotations ? 

Option 3. should also be helpful for case of adding existing data, e.g. one has the images / video and .xml and wants to recreate the project in CVAT.

### Current Behaviour

Fixing labels at the moment is possible on a per project basis by
1. Export current .xml from project, Remove annotations from Task and delete all labels one by one in the admin panel. Correct the .xml, create a json file of new labels from corrected .xml or add manually, then upload the .xml. Lot of duplication here, since labels are already in the .xml and deleting the labels from admin one by one is a pain.
2. Same as above but instead delete the project, re-upload the data and continue with adding the labels either manually or using a json then import the .xml

### Context
Fixing labels issues across various video projects that share labels.

### Next steps
I've already discussed this in gitter and was asked to add a suggestion.

**Comment by nmanovic** [comment]
@cstamatopoulos , the only motivation for the current restrictions is to avoid cases when you modify labels and after that have problems with re-uploading previous annotations. Another idea is to avoid modifying specification of labels and attributes because it should lead to annotation/verification of the whole task again. Probably instead we can warn users about the problem and force them to think twice before the change.

P.S. Too many complains from users. Need to allow editing of labels and implement a warning to be sure that users understand what they are doing.

**Comment by cstamatopoulos** [comment]
I mostly agree with you, I was asked to suggest the features in Gitter so I did.
I do think though that depending on the type of labels it is possible to have mistakes. We were dealing with scientific names of pests and typos (that could have been avoided) were made so all videos ended up having the same mistakes. I was asked to help in fixing them after the annotation stage (note that I did give plenty of cautionary warnings but it still happened). Dealing with it was pretty painful. 
I feel that the easier solution is to provide a rename label via cmd line for a project. The GUI has it so why should not the cmd line? That way it should be easy to automate for any number of project and all you are doing on your side is exposing an existing functionality that is present in the admin panel.
Alternatively, the issue here is the constraint of one video per project which does not allow "sharing" labels. If we could have multiple videos on the same "Task" even if they are different jobs, they would all have the same labels and thus we would have only one "task" to fix things.

**Comment by nmanovic** [comment]
>> I feel that the easier solution is to provide a rename label via cmd line for a project. The GUI has it so why should not the cmd line?

If it is possible in UI, it means that REST API allows such modifications. Thus it will be possible to implement in CMD tools.

>> Alternatively, the issue here is the constraint of one video per project which does not allow "sharing" labels. If we could have multiple videos on the same "Task" even if they are different jobs, they would all have the same labels and thus we would have only one "task" to fix things.

We are going to implement "projects" till EOY. A project is a set of annotation tasks.

**Comment by nmanovic** [comment]
@cstamatopoulos , please look at projects feature. Let us know if it helps.

**Comment by nmanovic** [comment]
@ActiveChooN , please don't forget to update the issue when "rename" of labels and attributes will be implemented as well.

**Comment by nmanovic** [comment]
@cstamatopoulos , now it is possible to rename labels. Could you please confirm that the way works for you. I will close the feature request as outdated.
