### ISSUE TITLE
Find a better place to job status switcher

### ISSUE THREAD

**Issue by bigred94** [openvinotoolkit/cvat#2082]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I don't have an option to change status of job.
<img width="352" alt="Screen Shot 2020-08-25 at 8 52 48 AM" src="https://user-images.githubusercontent.com/69821298/91183131-b562b900-e6b0-11ea-8347-cdc634a5c993.png">
Additionally the enumeration type for the status of the job in enums.js is called TaskStatus. I think the name of this should be changed since it is referring to a task not a job.

### Expected Behaviour

The menu on the annotation page gives option to change status.
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`): 1fdf10032a072da9f3ac19bfd623accc793c88cb
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@bigred94 

Hi, please look at #1704
Job and task statuses are the same.
A task status is changing automatically depends of job statuses of the task

**Comment by bigred94** [comment]
@bsekachev 

Thanks for pointing me to #1704 that helped me find how to change the status! I would recommend changing the following in the documentation to use the Info button not the menu inside the job. I do realize it references the info button later on in the documentation, but making the change here would help too.

 "A status of the job. The status is specified by the user in the menu inside the job. There are three types of status: annotation, validation or completed. The status of the job is changes the progress bar of the task." 


I understand that a task which has the states "pending", "in progress", and "completed" changes automatically as the jobs statuses change. However, in enums.js the enumeration TaskStatus has the states, 'annotation', 'validation', and 'completed'. As mentioned these are not the states of a Task, they are the states of a Job so the name TaskStatus should be changed to reflect that.

**Comment by bsekachev** [comment]
Hmm.. you are right. In UI task status is defined as following:

```ts
        if (numOfCompleted === numOfJobs) {
            progressColor = 'cvat-task-completed-progress';
            progressText = <Text strong className={progressColor}>Completed</Text>;
        } else if (numOfCompleted) {
            progressColor = 'cvat-task-progress-progress';
            progressText = <Text strong className={progressColor}>In Progress</Text>;
        } else {
            progressColor = 'cvat-task-pending-progress';
            progressText = <Text strong className={progressColor}>Pending</Text>;
        }
```

But it is only UI implementation. In the database task status is one of 
```python
class StatusChoice(str, Enum):
    ANNOTATION = 'annotation'
    VALIDATION = 'validation'
    COMPLETED = 'completed'

```

as you can see here: ``cvat/apps/engine/models.py``

Maybe we should sort it out.

**Comment by bsekachev** [comment]
What's more, we wanted rename 'validation' to 'review'
