### ISSUE TITLE
Authorized to Access all tasks, even without adding this new user to any group in Admin page

### ISSUE THREAD

**Issue by maravind707** [openvinotoolkit/cvat#2093]
### My actions before raising this issue
- [ yes] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ yes] Searched [past issues](/issues)

### Expected Behaviour
Initially, After Creating a new account, it should not have access to any Task or any Operation, until Admin assigned them to any of the existing role/group in the admin page.
I expecting it will be an empty page without any existing tasks as mentioned in User's guide

https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#authorization 

Group(Annotator) should be able to see Tasks which are assigned to him/she

### Current Behaviour

While I create a new account from the main login page, it was successful and logging in and listing all existing Tasks 
Even I can open Task, annotate, modify it and save it, which should not happen with a new account which has no group assigned

I had a user in only the Annotator group/role still am able to see all Tasks in that user account, even the task which I assigned to others.

### Possible Solution
I facing these issues since I last updated this repo that's around Aug first week 2020, before that it was working as expected
I hope this will be fixed ASAP
Thanks in Advance

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05):
               Docker version 19.03.12, build 48a66213fe
- Are you using Docker Swarm or Kubernetes?
               No
- Operating System and version (e.g. Linux, Windows, MacOS):
               Ubuntu 18.04.4 LTS (EC2, t2.2xlarge)

**Comment by nmanovic** [comment]
@maravind707 , thanks for reporting the issue. We are going to fix it.  Till we implement a full solution please modify your CVAT settings: https://github.com/opencv/cvat/blob/82ea21960241274a8c813420ed43131e1307fd70/cvat/settings/base.py#L408

**Comment by brucechou1983** [comment]
@nmanovic could you share any example of how to achieve proper access control by modifying `base.py`?

**Comment by victor-ab** [comment]
@nmanovic I have that same block of code in my settings and I still got the same issue.
Any workaround in the meantime?

**Comment by azhavoro** [comment]
> @nmanovic I have that same block of code in my settings and I still got the same issue.
> Any workaround in the meantime?

Did you set this variable to True? https://github.com/openvinotoolkit/cvat/blob/82ea21960241274a8c813420ed43131e1307fd70/cvat/settings/base.py#L415

**Comment by victor-ab** [comment]
> > @nmanovic I have that same block of code in my settings and I still got the same issue.
> > Any workaround in the meantime?
> 
> Did you set this variable to True?
> 
> https://github.com/openvinotoolkit/cvat/blob/82ea21960241274a8c813420ed43131e1307fd70/cvat/settings/base.py#L415

That was it. Thanks!

The user can still see jobs that are not assigned to him. Any way to also hide that?

**Comment by azhavoro** [comment]
No way at the moment, if the user can see the task he can view all jobs for this task.

**Comment by valeriyvan** [comment]
Any progress on this fix? Currently CVAT is not possible to be used on publicly accessible server. Any malicious user could register self and see everything immediately.

**Comment by nmanovic** [comment]
@valeriyvan , above you can see a simple solution. Look at cvat.org. Can you see tasks of other users? It was created from the repo without any modifications (just setup the configuration correctly).
