### ISSUE TITLE
service “cvat_ui” fails to build.

### ISSUE THREAD

**Issue by noamholz** [openvinotoolkit/cvat#2105]
### My actions before raising this issue
- [v] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [v] Searched [past issues](/issues)

"docker-compose build" fails at 'cvat_ui' service, saying "sh: can't create generated/aesprim-browser.js: Permission denied".
Replacing the "RUN npm install" lines in Dockerfile.ui with "RUN npm install --unsafe-perm=true --allow-root" [(as proposed here)](https://github.com/artilleryio/artillery/issues/714#issuecomment-518631770) seem to solve it, but I'd like to be sure if that's a legitimate solution here, or do I have a deeper problem in the installation that should be solved?

### Current Behaviour

After applying all installation steps successfully, executing of "docker-compose build" results in a very long list of "npm info lifecycle" lines, and then the error described below.
This happens even if I (1) delete & reclone the repo, (2) delete all containers, (3) use docker-compose build --no-cache.

```
npm info lifecycle jsonpath@1.0.2~postinstall: jsonpath@1.0.2

> jsonpath@1.0.2 postinstall /tmp/cvat-core/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

sh: can't create generated/aesprim-browser.js: Permission denied
npm info lifecycle jsonpath@1.0.2~postinstall: Failed to exec postinstall script
npm timing action:postinstall Completed in 665ms
npm timing stage:rollbackFailedOptional Completed in 26ms
npm timing stage:runTopLevelLifecycles Completed in 39210ms
npm WARN cvat-core@3.5.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonpath@1.0.2 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsonpath@1.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 40189ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-31T12_44_02_031Z-debug.log
ERROR: Service 'cvat_ui' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1


```
### Steps to Reproduce (for bugs)

Follow installation guide (develop branch) up to "docker-compose build"

### Your Environment

- Git hash commit (`git log -1`): error occurs both in:
15acb953e3d4e4903b2320a1ec41ba690ecb3f0d (develop)
b6bea11c8b5a98a379ca440dac655c6044be8143 (release-1.1.0)
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by noamholz** [comment]
Attaching a log
[build_log.txt](https://github.com/openvinotoolkit/cvat/files/5188463/build_log.txt)

**Comment by noamholz** [comment]
As suggested by @zhiltsov-max  , I compared my build log with a CI build like [this one](https://travis-ci.org/github/openvinotoolkit/cvat/builds/725120649).
To make the comparison more to the point, I've omitted any lines that appear in both logs (ignoring their order), and the number of ms that's reported for every process... with hopes this can help detect the problem I'm having. Here's the comparison file 
[cvat_ui_build_compare.zip](https://github.com/openvinotoolkit/cvat/files/5253545/cvat_ui_build_compare.zip)

**Comment by nmanovic** [comment]
@noamholz , I believe the issue is outdated. I see now other complains that it isn't possible to build UI.
