### ISSUE TITLE
Chunks on the fly: list of problems

### ISSUE THREAD

**Issue by nmanovic** [openvinotoolkit/cvat#2112]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour

- [x] In some cases meta_info.txt can contain information only about one frame (e.g. "0 0"). We need to reject such cases. Number of key frames should be sufficient to decode a video file smoothly. I saw TODO in source code. Need to fix that.
- [x] Need a documentation about the feature. Please ask our internal team to describe it.
- [x] Need a documentation about meta_info.txt and how to prepare it manually
- [x] meta_info.txt should be sorted by frame number.
- [ ] (from gitter) when i create task with share file ,and use cache , the result failed , FileNotFoundError:[Error2] no such file or directory. When the images in the root directory work well ,but in other directory it's failed.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by chaoyifei** [comment]
when i create task with share file ,and use cache , the result failed , FileNotFoundError:[Error2] no such file or directory. When the images in the root directory work well ,but in other directory it's failed.


HI，this proleblem occured when the file is a zip

**Comment by Marishka17** [comment]
@chaoyifei, hi, problem with share data was solved in [PR](https://github.com/openvinotoolkit/cvat/pull/2154).

**Comment by chaoyifei** [comment]
@Marishka17  HI，this PR is still  a problem when you seletct a directory ,such as when you seletct "/test/test" and not choose any file in this directory.  usecache, Normally,all the file can be use in this directory, but creat  task failed ,"IsDirectoryError:[Error:21] Is a directory:'~data/data/2/raw/test/test'"
