### ISSUE TITLE
Migration documentation

### ISSUE THREAD

**Issue by sherabi** [openvinotoolkit/cvat#2114]
Are there any migration procedures if I would like to move from an existing old version to the latest release 1.1.0?
If someone can lay out some generic instructions that would be fine too. We have tried migrating the data on the filesystem as well as the DB (postgres) but the new version doesn't allow us to see the data that was loaded into our old version i.e. 1.0

**Comment by azhavoro** [comment]
@sherabi, 
Hi, sorry for the delay. https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/faq.md#how-to-update-cvat.
Generally, you do not need any additional steps, but it is better to backup your data before updating.

**Comment by bsekachev** [comment]
I will close the issue since there aren't any response for a long time. 
Do not hesitate reopen it if you still have questions or ask our community on gitter
