### ISSUE TITLE
Fix models-reducer to be non-destructive.

### ISSUE THREAD

**Issue by bigred94** [openvinotoolkit/cvat#2115]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

The models-reducer is destructive to the state. Thus when a component subscribes to the store the prevprops and this.props are the same.

### Expected Behaviour

The reducer to be non-destructive.

### Current Behaviour

The reducer is destructive. For example see line 61 of models.reducer.ts
```
    case ModelsActionTypes.GET_INFERENCE_STATUS_SUCCESS: {
            const { inferences } = state;
            if (action.payload.activeInference.status === 'finished') {
                delete inferences[action.payload.taskID];
            } else {
                inferences[action.payload.taskID] = action.payload.activeInference;
            }

            return {
                ...state,
                inferences: { ...inferences },
            }
```
### Possible Solution

```
        case ModelsActionTypes.GET_INFERENCE_STATUS_SUCCESS: {
            const { inferences } = state;
            if (action.payload.activeInference.status === 'finished') {
                return {
                    ...state,
                    inferences: omit(inferences, action.payload.taskID),
                };
            }
            return {
                ...state,
                inferences: {
                    ...inferences,
                    [action.payload.taskID]: action.payload.activeInference,
                },
            };
        }
```
### Steps to Reproduce (for bugs)

1. Create a component that has modelsstate.inferences as prop
2. Run annotation
3. Log this.props.inferences and prev.props.inferences to see the are always the same.

### Your Environment

- Git hash commit (`git log -1`): 8eb7c13619e39d9546ba3807027d30eab9c5ce2b
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@bigred94 

Hi, thx for your concern.
As I understand omit creates shallow copy of an object without a specific key. Right? 
But in ES6 syntax ``{ ...inferences }`` does the same.

**Comment by bigred94** [comment]
Right but you are still modifying the original state because you are deleting the key from the original state THEN making a copy. You need to copy then delete. Following the reproduction steps will show this.
