### ISSUE TITLE
Feature Request: Include FPS of the video in the meta of cvat for video annotation dataset

### ISSUE THREAD

**Issue by hollowgalaxy** [openvinotoolkit/cvat#2118]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

In CVAT for video  annotations, the frame number is used, however one piece of info that isn't passed in is fps of the video making it harder to correlate to annotations to the video (as original video uploaded may have a different fps, or a piece of code that doesn't have access to the video, but has to deal with time)

### Expected Behaviour

Ability to see the fps of the video at which the frames are extracted from the meta section of CVAT for video annotations.

### Current Behaviour

no fps label in the annotation for cvat for video annotations.

### Possible Solution

add fps label in the annotaation for cvat for video annotations.

### Your Environment
docker-compose up on the yml in master branch

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@hollowgalaxy , it is possible to add such parameter into meta information but it is useless. There are multiple problems here. One of them is video can be with non-constant FPS. Video can be with encoding errors. Need to export datasets from CVAT or use the same pipeline as CVAT uses to split video on frames.

**Comment by hollowgalaxy** [comment]
Perhaps a solution is to include time of the video the frame is at. As an additional label, I mean.

**Comment by nmanovic** [comment]
@hollowgalaxy , it also doesn't work in some cases. It works fine when you watch a video, but it works time to time when you need precise frame navigation.

**Comment by nmanovic** [comment]
@hollowgalaxy , I will close the feature request. It looks like core team has too many requests and this one was not supported by our community (nobody implemented it, nobody voted for it).
