### ISSUE TITLE
How to label rotated bounding box?

### ISSUE THREAD

**Issue by bejoechen** [openvinotoolkit/cvat#2128]
Is there any convenient way to crop bounding box with a angle?
I tired polygon, but it is too complicated. 
Or, is there any document on how to write plugin or extend CVAT object type?
thanks

**Comment by a-andre** [comment]
There is no convenient way, yet. See https://github.com/openvinotoolkit/cvat/issues/1128

**Comment by nmanovic** [comment]
@bejoechen , it looks like we already have such issue. I will close this one.
