### ISSUE TITLE
Tracks end on last key frame in export even though they are shown in CVAT UI

### ISSUE THREAD

**Issue by hixz00** [openvinotoolkit/cvat#2129]
I've experienced a problem with the exported xml, CVAT-for-videos. For some objects it will end the track at the latest keyframe. It happens at every export from this task but it's not consistent that all tracks ends on a keyframe. In CVAT UI the object is still there all the way to the end of the video but in the export it disappears at the last keyframe. I haven't been able to create a new task with the same behaviour but one way to fix the problem, and maybe understand what's causing it, is to export the annotation and then import it and finally exporting it again. When this is done all tracks continue to the end of the video regardless of keyframe or not. One lead could be that this video was annotated in old ui.

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Tracks that show up as objects in CVAT should show up in the exported CVAT for videos XML. 

### Current Behaviour

All annotated objects shown in the UI should be exported, regardless of keyframe or not.

### Possible Solution

A work around is to export, import and export it again.

### Steps to Reproduce (for bugs)

Not a proper reproduce but it shows that the import will extend the track and the next export will have tracks that continues to the end of the video.
1. Verify that track 138 in first_export.xml ends on frame 3454
2. Create a new task with a video in proper length
3. Import the XML to the new task
4. Export the new task
5. Verify that the track that previously ended at frame 3454 now continue to the last frame, 3499. Attached is such an export, the new id of the track is 103.

### Context

It's not sure that the objects seen in the annotation will show up in the exported XML file.
[exported_xml.zip](https://github.com/opencv/cvat/files/5174653/exported_xml.zip)

### Your Environment

- Git hash commit (`git log -1`):  07de7141edbc980031da857579128088f7a4630a (tag: v1.0.0, upstream/master) Release 1.0.0 (#1335)
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.8
- Are you using Docker Swarm or Kubernetes?No
- Operating System and version (e.g. Linux, Windows, MacOS):​ linux Ubuntu 18.04.4 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please look at the issue?
