### ISSUE TITLE
No message when email confirmed

### ISSUE THREAD

**Issue by ActiveChooN** [openvinotoolkit/cvat#2135]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

UI should show some message that email was confirmed or declined successfully after registration. It's convenient way and applied in many services.

### Current Behaviour

There is only redirection to login page when email confirmed

### Possible Solution

Add pages with message email confirmed or declined.

### Steps to Reproduce (for bugs)

1. Register new user on [cvat.org](https://cvat.org)
1. Go to your mailbox and follow confirmation link

### Your Environment

- Git hash commit (`git log -1`): cb4d8e6ee571594f74ff96bc6cbc7c597c732e4a
- Docker version `docker version` (e.g. Docker 17.0.05): no
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@ActiveChooN , I agree. It can be a nice feature.

**Comment by ria-19** [comment]
If this issue is open, I would like to work on this.

**Comment by ActiveChooN** [comment]
As far I know, no one in our team is working on this feature right now. So you are welcome.

**Comment by gudipudiramanakumar** [comment]
Can I know if I can work on this, this would be my first contribution.

**Comment by ria-19** [comment]
Thank you, I will keep you updated with my progress.

**Comment by Spectre-ak** [comment]
Hello everyone, I opened a pull request at [Added email confirmation page #3573](https://github.com/openvinotoolkit/cvat/pull/3573) for this issue. 
Do you think that can close this issue?
