### ISSUE TITLE
pdf support was broken

### ISSUE THREAD

**Issue by mosqmara** [openvinotoolkit/cvat#2139]
I label documents in cvat.org. When I upload the pdf file that I will label, this error (could not create the task, open the browser console to get details) always show up. It started a few days ago until now. Please help resolve it so I can label the documents I am working on. Someone advised that after one of the latest updates, pdf support was broken.

**Comment by mosqmara** [comment]
Hello. May I know how long does it usually takes to fix this issue? Thank you.

**Comment by mosqmara** [comment]
Can please get an update for this? It is closed but the issue is not resolved.

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please provide the current status?

**Comment by zhiltsov-max** [comment]
Probably, cvat.org needs an update. The code should work.

**Comment by mosqmara** [comment]
Hi. Is there anything else that we can do here, please?

**Comment by azhavoro** [comment]
@mosqmara I suppose the issue should be resolved, I can create a task from pdf. I'll close the issue, feel free to reopen if the issue still isn't resolved for you.
