### ISSUE TITLE
Could not create the task Error: Network Error.

### ISSUE THREAD

**Issue by wenkaip-1836890** [openvinotoolkit/cvat#2147]
When I try to submit a new annotation task, I get this error: Could not create the task
Error: Network Error.

Below is the output of docker logs cvat, docker ps -a and my docker-compose config.

Output of docker logs cvat:

2020-09-07 18:03:45,218 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2020-09-07 18:03:45,218 DEBG 'rqworker_default_1' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2020-09-07 18:03:45,218 DEBG 'rqworker_low' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
INFO:rq.worker:Cleaning registries for queue: low

2020-09-07 18:03:45,219 DEBG 'rqworker_default_0' stderr output:
INFO:rq.worker:Cleaning registries for queue: default

Output of docker ps -a:
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                            NAMES
bdb68036b922        alpine:3.11                            "/bin/sh -c '/bin/sl…"   4 hours ago         Up 4 hours                                           nuclio-local-storage-reader
3f3b1ccd71fe        nginx:stable-alpine                    "/docker-entrypoint.…"   2 days ago          Up 2 days           0.0.0.0:8080->80/tcp             cvat_proxy
e4f319fb8df2        cvat/ui                                "/docker-entrypoint.…"   2 days ago          Up 2 days           80/tcp                           cvat_ui
fb09f7ce338f        cvat/server                            "/usr/bin/supervisord"   2 days ago          Up 2 days           8080/tcp, 8443/tcp               cvat
662781be0ed6        quay.io/nuclio/dashboard:1.4.8-amd64   "sh -c ./runner.sh"      2 days ago          Up 2 days           80/tcp, 0.0.0.0:8070->8070/tcp   nuclio
33490021acf1        redis:4.0-alpine                       "docker-entrypoint.s…"   2 days ago          Up 2 days           6379/tcp                         cvat_redis
42be7ceb7b43        postgres:10-alpine                     "docker-entrypoint.s…"   2 days ago          Up 2 days           5432/tcp                         cvat_db

Output of docker-compose config:
version: "2.3"

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: cvat/server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy: nuclio,${no_proxy}
        socks_proxy:
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        TZ: "Etc/UTC"
        CLAM_AV: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: "cvat_redis"
      CVAT_POSTGRES_HOST: "cvat_db"
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models

  cvat_ui:
    container_name: cvat_ui
    image: cvat/ui
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
      dockerfile: Dockerfile.ui

    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat

  cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - cvat
      - cvat_ui
    environment:
      CVAT_HOST: localhost
    ports:
      - "8080:80"
    volumes:
      - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  serverless:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:1.4.8-amd64
    restart: always
    networks:
      default:
        aliases:
          - nuclio
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      http_proxy:
      https_proxy:
      no_proxy: 172.28.0.1,${no_proxy}
      NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: "true"
    ports:
      - "8070:8070"

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:

Please help me, thanks!

**Comment by bsekachev** [comment]
@wenkaip-1836890 
Please, follow the issue template to we were able to help you.

**Comment by wenkaip-1836890** [comment]
I don't think I change anything in compose files. I have installed CVAT according to the quick installation guide. My operating system is Ubuntu 18.04.

**Comment by zhiltsov-max** [comment]
Is there anything in the browser console (F12 key)?

**Comment by wenkaip-1836890** [comment]
@zhiltsov-max 
Here are the error messages shown in the console:
:8080/api/v1/tasks/10/data:1 Failed to load resource: net::ERR_ACCESS_DENIED
cvat-app.tsx:215 Error: Network Error.
e @ cvat-app.tsx:215

**Comment by thomph** [comment]
@wenkaip-1836890 how to fix it ?, thanks

**Comment by azhavoro** [comment]
@thomph make sure that user have permissions to create a task
