### ISSUE TITLE
Paused or Hanged at npm timing action: extract Completed in 99128ms?

### ISSUE THREAD

**Issue by pranavpeddi** [openvinotoolkit/cvat#2149]
For around 45 minutes, there is no change on the console of command prompt, can anybody help me with this

npm http fetch GET 200 https://registry.npmjs.org/ast-types-flow/-/ast-types-flow-0.0.7.tgz 2944ms
npm http fetch GET 200 https://registry.npmjs.org/asap/-/asap-2.0.6.tgz 924ms
npm http fetch GET 200 https://registry.npmjs.org/array-tree-filter/-/array-tree-filter-2.1.0.tgz 616ms
npm http fetch GET 200 https://registry.npmjs.org/@ant-design/icons/-/icons-2.1.1.tgz 79987ms
npm http fetch GET 200 https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001006.tgz 15990ms
npm http fetch GET 200 https://registry.npmjs.org/core-js-pure/-/core-js-pure-3.4.7.tgz 16879ms
npm http fetch GET 200 https://registry.npmjs.org/typescript/-/typescript-3.7.3.tgz 86040ms
npm http fetch GET 200 https://registry.npmjs.org/rxjs/-/rxjs-6.5.4.tgz 76515ms
npm http fetch GET 200 https://registry.npmjs.org/core-js/-/core-js-2.6.10.tgz 21697ms
npm http fetch GET 200 https://registry.npmjs.org/@icons/material/-/material-0.2.4.tgz 91554ms
npm http fetch GET 200 https://registry.npmjs.org/antd/-/antd-3.26.17.tgz 94959ms
npm timing action:extract Completed in 99128ms

**Comment by anderflash** [comment]
In my case, `npm timing npm Completed in 1440663ms` just for one step (out of 31 steps). Something is wrong here with the NodeJS stuff when building cvat docker image.

**Comment by pranavpeddi** [comment]
> In my case, `npm timing npm Completed in 1440663ms` just for one step (out of 31 steps). Something is wrong here with the NodeJS stuff when building cvat docker image.

Mine working fine now, in fact, there is no problem, check if ur docker container is running or not

**Comment by anderflash** [comment]
Mine is also working now, but this issue might be mentioned as an enhancement for the building process.

**Comment by pranavpeddi** [comment]
> Mine is also working now, but this issue might be mentioned as an enhancement for the building process.

Of course.
