### ISSUE TITLE
File tree does not update automatically when there are changes in files

### ISSUE THREAD

**Issue by savan77** [openvinotoolkit/cvat#2166]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

While using Connected file storage, the file tree does not update automatically whenever there are changes in the files (i.e adding a new file). We have to refresh the page to see the updated list. For better user UX, it would be great to have this list update automatically.

### Possible Solution

Use a filewatcher like Watchdog to watch for file changes.
Create an endpoint to serve a Websocket that will notify the client of file changes.
Update UI to make an additional request to connect to the websocket and update the UI.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@savan77 , it is a nice feature request. Let me know if you can help with the issue.

**Comment by savan77** [comment]
Sure @nmanovic , we are working on the proposed approach.

**Comment by nmanovic** [comment]
@savan77 , I will close the feature request. Nobody else complained about the behaviors. Probably the easiest approach is to have a button 'refresh'. But let's wait more complains from community about that.
