### ISSUE TITLE
When I some changes in the code,  when I re-run again, there was no change, old one shows up again?

### ISSUE THREAD

**Issue by pranavpeddi** [openvinotoolkit/cvat#2169]
What I mean to say is, I made some changes in the UI, this does not show up when I re-run it again, can somebody help?

**Comment by savan77** [comment]
Ideally, you should see that changes reflected immediately without doing anything. At least that's what the case is with me using VS Code. Sometimes, I have to run `npm install` and `npm start`.

**Comment by nmanovic** [comment]
@pranavpeddi , by the description it is not possible to help. Also the question is better for https://gitter.im/opencv-cvat/dev. I see that you already asked it here. I will close the issue.

**Comment by NarenZen** [comment]
@pranavpeddi How did you solve it. Can you help me. Facing the same issue

**Comment by stavyadatta** [comment]
Same, please help if someone found a solution
