### ISSUE TITLE
Combine Annotation or Import annotations

### ISSUE THREAD

**Issue by WeiChihChern** [openvinotoolkit/cvat#2175]
Hello,

As me and my team we're not familiar with setting up online cvat for all the members.  We would like to divide the images and annotate them on our ends, then combine them afterward.  We did try a few times, but doesn't work flawlessly.

I wonder is there any suggestion on how can we combine annotations or import other's annotations on a same task.

**Comment by zhiltsov-max** [comment]
Hi, when creating a task, you can set `segment_size` and `overlap` (in the advanced options). `segment_size` will split the task into few equal parts, and `overlap` can make annotations from adjacent jobs visible in a job.

**Comment by azhavoro** [comment]
@WeiChihChern I'll close the issue, feel free to reopen it if you have questions.
