### ISSUE TITLE
Verikovanı kayıt Sorunu

### ISSUE THREAD

**Issue by bilteknik** [openvinotoolkit/cvat#2184]
https://verikovani.ssb.gov.tr/auth/register sitesinde 7. aşamada şifreyi girerken aşağıdaki hatayı almaktayım. o yüzden kayıt oluşturamadım.  yardımcı olursanız sevinirim.
![hata](https://user-images.githubusercontent.com/45789580/93271074-13b81e80-f7bb-11ea-8872-1054a5bdf08c.JPG)

**Comment by nmanovic** [comment]
Lütfen sorununuzu İngilizce olarak açıklayın. Şimdilik konuyu kapatacağım.

**Comment by bilteknik** [comment]
Password part fails while registering.

16 Eyl 2020 Çar 07:41 tarihinde Nikita Manovich <notifications@github.com>
şunu yazdı:

**Comment by bilteknik** [comment]
I will be glad if you help

**Comment by nmanovic** [comment]
@bilteknik , we don't support external CVAT instances except cvat.org. If it is your server, provide logs using the command `docker logs cvat`.
