### ISSUE TITLE
How to upload DL which built by myself?

### ISSUE THREAD

**Issue by SaihholdChiu** [openvinotoolkit/cvat#2185]
As per the DL models already in the CVAT platform are not good enough, I used more tranning data to built a new model based on YOLOV3, and trained a DL model used for cuboid semi annotation, but I didn't find a way to upload the model, may you share a guideline how to do it?

**Comment by bsekachev** [comment]
We do not have such a guideline right now. You can look at other models implementation. 
First you need to write several scripts and .yml file (``cvat/serverless/openvino/omz/public/yolo-v3-tf/nuclio/*``)
Than you need deploy this function (look at ``/cvat/serverless/deploy.sh`` to see how to do it)

**Comment by mtourne** [comment]
I'm also interested in this, I'd like to deploy a model based on yolov4 and trained with my own dataset.

**Comment by KALALRANJITHKUMAR** [comment]
Hello sir, Any tutorial document to setup our model in cvat framework?

Thank you
