### ISSUE TITLE
docker-compose build - ERROR (certificate signed by unknown authority)

### ISSUE THREAD

**Issue by mohammadsahal** [openvinotoolkit/cvat#2188]
### My actions before raising this issue
- [ yes] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ yes] Searched [past issues](/issues)

### Current Action
I'm trying to set up CVAT for image annotation on a Ubuntu 18.04 VM.
I've been able to follow the steps in the Installation Guide to the dot, and am currently stuck at the "docker-compose build" command

### Current Behaviour

This is the output which I get:
cvat_db uses and image, skipping
cvat_redis uses and image, skipping
cvat_proxy uses and image, skipping
serverless uses and image, skipping
Building cvat
Step 1/34 : FROM ubuntu:20.04
ERROR: Service 'cvat' failed to build : Get https;//registry-1.docker.io/v2/ : x509: certificate signed by unknown authority

The url has the following information:
errors:
    0:
        code:    "UNAUTHORIZED"
        message:    "authentication required"
        detail:    null

### Your Environment

- Git hash commit: 59b338994d6d3b67e5477679341ab3aad347c9fb
- Docker version `docker version`: 19.03.12, build 48a66213fe
- Are you using Docker Swarm or Kubernetes?: Whatever it mentions in the CVAT installation guide
- Operating System and version: Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Hi, This is more probably docker issues.

Some of google answers:
1. https://stackoverflow.com/questions/50768317/docker-pull-certificate-signed-by-unknown-authority
2. https://www.digitalsanctuary.com/general/solution-for-docker-registry-error-certificate-signed-by-unknown-authority.html
3. https://forums.docker.com/t/docker-private-registry-x509-certificate-signed-by-unknown-authority/21262

**Comment by bsekachev** [comment]
I will close the issue. Do not hesitate reopen it is still a problem for you, or you can ask the community on gitter
