### ISSUE TITLE
How to get the grouping shapes annotations when dumping annotations

### ISSUE THREAD

**Issue by karthik-kalyanasundaram** [openvinotoolkit/cvat#2190]
Currently trying to extract the grouped shapes when I dump [annotations.]
<img width="940" alt="Screen Shot 2020-09-16 at 12 24 12 PM" src="https://user-images.githubusercontent.com/68397870/93382893-b0a8a500-f817-11ea-898e-53b6c1f3fb55.png"> When I extract the current annotations, it only provides me with the label and the mid x mid y w and height of instances.

**

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Not all formats support this attribute, it is only available in `CVAT *`, `COCO` (for boxes and polygons), `Datumaro`, `LabelMe`.

**Comment by bsekachev** [comment]
In ``CVAT`` format look at ``group_id`` property of annotated objects.
