### ISSUE TITLE
How to show Track id on top of Every Bounding Box(Ex: Reactangle,Polygon...every shape)

### ISSUE THREAD

**Issue by satyavardhan626** [openvinotoolkit/cvat#2191]
I would like to show Track id on top of Every Bounding Box .....wihthout hovering on box.

Any help Please

**Comment by bsekachev** [comment]
Hi, please, follow the issue template in the future.
You can find corresponding checkbox in settings

![Screenshot from 2020-09-18 10-23-56](https://user-images.githubusercontent.com/40690378/93568607-140e1080-f999-11ea-8415-9bc70ac6ed36.png)
