### ISSUE TITLE
Can instance identities across frames (in video) be labelled?

### ISSUE THREAD

**Issue by jong372** [openvinotoolkit/cvat#2193]
Does CVAT support a smart way of labeling instance identities across frames (for video instance segmentation task)? Hence using instance identities of a previous frame and add them to next frame?

**Comment by zhiltsov-max** [comment]
You can use track annotations for this.

**Comment by bsekachev** [comment]
Please, follow the issue template in the future. For common questions it is better to use gitter chat.
Each object in CVAT (box, cuboid, polyline, polygon, points set) can be prolongated during the whole video with different positions and attributes on different frames. It is called "track" as Maxim said. I hope we answered your question
