### ISSUE TITLE
Server error when uploading dumped "segmentation mask 1.1" annotations

### ISSUE THREAD

**Issue by noamholz** [openvinotoolkit/cvat#2201]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Dumped "segmentation mask 1.1" annotations, and right after that tried to upload the exported file and got a server error.

### Expected Behaviour

Expected to be able to upload the exact annotation files I was downloading.

### Current Behaviour

Upon uploading I get a server error, with the log (full file attached) showing:
```
File "/home/django/cvat/apps/engine/views.py", line 788, in _import_annotations
 os.close(rq_job.meta['tmp_file_descriptor'])
[remote 172.28.0.7:42888] OSError: [Errno 9] Bad file descriptor
```

### Steps to Reproduce (for bugs)

1. Dump "segmentation mask 1.1" annotations
1. Upload the dumped file into the same task

### Your Environment

- Git hash commit (`git log -1`): develop branch, commit 71efaac6eb4044bf05f168f2b7108e5c7cada2ec
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.05
- Code example or link to GitHub repo or gist to reproduce problem:
- Logs from `cvat` container 
[upload_fail.txt](https://github.com/openvinotoolkit/cvat/files/5252507/upload_fail.txt)

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Try to clear rq queue with `docker run -it --rm cvat bash -c 'python manage.py shell'`

```python
import django_rq
q = django_rq.get_queue("default")
ids = q.failed_job_registry.get()
for id in ids:
    if 'upload' not in id:
        continue
    job = q.fetch_job(id)
    job.cancel()
    job.delete()
```

**Comment by noamholz** [comment]
Thanks @zhiltsov-max ,
The problem seems to be related the maybe more fundamental [issue](https://github.com/openvinotoolkit/cvat/issues/2105) I'm having. It seems that I was working with a failed cvat_ui build, that I had to fix again by adding 
``` --allow-root --unsafe-perm=true ``` to all the ``` RUN npm install ``` lines in Dockerfile.ui.
