### ISSUE TITLE
Could not check authorization on the server when I change a tiny thing on cvat image

### ISSUE THREAD

**Issue by archwolf118** [openvinotoolkit/cvat#2207]
I don't think rebuild the images is good choice, because spending long time.

When I change some documents in cvat container, and commit the container to be the new cvat image, like cvat:0921
Than I change the docker-compose.yml,  like:
```
cvat:
    container_name: cvat
    image: cvat:0921
```
then I use:
docker-compose down, and clean the volumes
Last, I rerun the new server, and I got the "Could not check authorization on the server" error in the webpage.
What is the problem? Maybe I forgot somethins. 
Thank you with your help !!!!

**Comment by bsekachev** [comment]
Changing something in built docker image and commiting it looks like rather exotic way of working with CVAT (why do you need it?). We didn't practice it. 
Speaking about the error: there aren't enough information to help you, some logs might help (from the browser console, details of requests from the browser, logs from cvat container, logs from cvat proxy, etc).

And please, follow the issue template in the future.

**Comment by azhavoro** [comment]
No response a log time, I'll close the issue.
@archwolf118 don't hesitate to reopen if the issue is still actual for you.
