### ISSUE TITLE
Which version of CVAT will add point cloud tool?

### ISSUE THREAD

**Issue by SaihholdChiu** [openvinotoolkit/cvat#2209]
I saw this requirement is in the Backlog page, but don't know which version of CVAT will add it, in addition when will 1.1-realease will be finished?

Thanks,

**Comment by bsekachev** [comment]
Hi, thx for the questions. 

* 1.1 has been released: https://github.com/openvinotoolkit/cvat/releases/tag/v1.1.0
* We do not have a strict roadmap, what's more backlog means that our team is not planning to do the feature in foreseeable future. Maybe somebody from the community will help with the feature,
