### ISSUE TITLE
Docs for ReID are obsolete

### ISSUE THREAD

**Issue by PMazarovich** [openvinotoolkit/cvat#2213]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Discussed this in gitter with developer

### Current Behaviour
There is an outdated link in docs when searching for information about ReID
https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/cvat/apps/reid/README.md
Also screenshots and description are not relevant.

### Expected Behaviour
Updated docs connected with ReID merge here:
https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/user_guide.md#top-panel

**Comment by nmanovic** [comment]
@TOsmanov , @aschernov , could you please help us to fix documentation?

**Comment by TOsmanov** [comment]
@nmanovic we are planning to make changes to the user guide with this plan #2216

**Comment by azhavoro** [comment]
@TOsmanov Can this issue be closed?

**Comment by TOsmanov** [comment]
@azhavoro yes
