### ISSUE TITLE
Plan for updating the User Guide and add "AI tool" section

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#2216]
#2224 
*AI tools section*
- [x] Add "AI tools" section
- [x] Add item "Interactors"
   - edit and rename item "Make AI Polygon" and  move to this section
- [x] Add item "Detectors"
   - add text
   - add images and gifs    

---
#2236 
- [x] Update item "Automatic annotation"
   - replace ReID to  Using the Person reidentification model
   - update text and images
- [x] Update item "Menu button"
   - remove item "Run ReID merge"

*Creating an annotation task  section*
- [x] Add text about color changes for label
- [x] Update images

---
#2242 

*Models section*
- [x] Fix text
- [x] Add links to installation.md#semi-automatic-and-automatic-annotation
- [x] Remove item and images "Upload a new model"

*Controls sidebar section*
- [x] Add icon AI tools and link to relevant section

*Appearance section*
- [x] Update item Black stroke rename to Outlines borders

- [x] Check and fix hotkeys
- [x] Update images containing menus
- [x] Update images containing controls sidebar

---

**Comment by vineethdas** [comment]
Has The AI tool been removed from the online portal?
