### ISSUE TITLE
Integrate Inside-Outside-Guidance semi-automatic segmentation

### ISSUE THREAD

**Issue by nmanovic** [openvinotoolkit/cvat#2227]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible solution

Integrate the semi-automatic segmentation as a serverless function and write an article about the process.
https://github.com/shiyinzhang/Inside-Outside-Guidance

**Comment by davodogster** [comment]
Keep up the awesome work @nmanovic - very pleased to hear that you are interested in incorporating this model to CVAT.

**Comment by mh-mazen** [comment]
@nmanovic hi sir , i am interested in IOG as well and took a look at your work
very good work so far you have solved all of the issues i had when i tried to implement the model
one question i have is were you able to find the implementation of the refinement as shown here?
[refinement](https://github.com/shiyinzhang/Inside-Outside-Guidance/blob/master/ims/refinement.gif) 
would love to hear back from you and keep up the good work

**Comment by davodogster** [comment]
I think I suggested IOG Integration many months ago but there seems to be no record of that anymore.
