### ISSUE TITLE
Could not get models from the server

### ISSUE THREAD

**Issue by yanmu2017** [openvinotoolkit/cvat#2245]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues): I have checked all related issues

### Expected Behaviour

I should see DL models in CVAT

### Current Behaviour

After following the [instructions,](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#semi-automatic-and-automatic-annotation) CVAT still cannot find any DL models. 
Whenever I open CVAT, it shows an error message 
![Screenshot from 2020-09-30 12-13-44](https://user-images.githubusercontent.com/33514089/94673071-76123280-0316-11eb-9b3e-50a6ca6e8d07.png)

### Possible Solution

Not sure. Maybe I have missed something in installation?

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

I want to use auto-segmentation for my segmentation tasks.

### Your Environment

- Git hash commit (`git log -1`): commit a5b2229039367e05cef7ea0f120bee2e33dd73ee (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Some logs are in txt
[error_dl_models.txt](https://github.com/openvinotoolkit/cvat/files/5304710/error_dl_models.txt)</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@yanmu2017 Hi, I cannot see running nuclio container (the name is `serverless`) on 8070 port in the `docker ps` output. Did you include `docker-compose.serverless.yml` config file to the docker-compose command as described here: https://github.com/openvinotoolkit/cvat/tree/develop/components/serverless?

**Comment by yanmu2017** [comment]
@azhavoro Thanks for the reply. Including the docker-compose command you mentioned solves the problem and I can see the models now.

One suggestion: Do you think it makes sense to include the docker-compose command `docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d`" into the instruction of [Semi-automatic and automatic annotation](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#semi-automatic-and-automatic-annotation)? Or at least a link to that [webpage](https://github.com/openvinotoolkit/cvat/tree/develop/components/serverless)? For myself, I checked the [instructions](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#semi-automatic-and-automatic-annotation) again and again but had never thought I should include another docker-compose command from a different [webpage](https://github.com/openvinotoolkit/cvat/tree/develop/components/serverless).

**Comment by azhavoro** [comment]
> @azhavoro Thanks for the reply. Including the docker-compose command you mentioned solves the problem and I can see the models now.
> 
> One suggestion: Do you think it makes sense to include the docker-compose command `docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d`" into the instruction of [Semi-automatic and automatic annotation](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#semi-automatic-and-automatic-annotation)? Or at least a link to that [webpage](https://github.com/openvinotoolkit/cvat/tree/develop/components/serverless)? For myself, I checked the [instructions](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#semi-automatic-and-automatic-annotation) again and again but had never thought I should include another docker-compose command from a different [webpage](https://github.com/openvinotoolkit/cvat/tree/develop/components/serverless).

👍 I believe that need to update the installation guide and think it's better to add the both things: compose command and link to the serverless component. Could you please prepare the PR?

**Comment by night-kun** [comment]
@yanmu2017 I run the command `docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d`，but  cvat still cannot find any DL models.

**Comment by nmanovic** [comment]
I believe the issue was resolved. If somebody has another issue, need to create a separate bug request.

**Comment by Auth0rM0rgan** [comment]
@nmanovic No No the problem didnt solve and still exists!!
