### ISSUE TITLE
How annotate vertical video

### ISSUE THREAD

**Issue by lolpa1n** [openvinotoolkit/cvat#2246]
Hello, how annotate vertical video? after upload video stretches to full screen.  Or maybe after annotation all coordinates will be correct.

**Comment by bsekachev** [comment]
Sorry, I am not sure I understand you.
Does the video change orientation after upload to CVAT? Or... ?

**Comment by lolpa1n** [comment]
@bsekachev I have a vertical video, in videoplayers it looks like it should, but in a CVAT it expands (probably due to the fact that the height and width are mixed up) 

like this
![pic](https://user-images.githubusercontent.com/47947340/94799255-85af7b00-03eb-11eb-90ee-3898ef97d691.png)

**Comment by bsekachev** [comment]
It looks strange
@azhavoro Could you please take a look?

**Comment by azhavoro** [comment]
@lolpa1n could you share a video sample ?

**Comment by lolpa1n** [comment]
can't, not for public access, but I solved the problem by changing the width and height

**Comment by bsekachev** [comment]
@azhavoro 

Just for experiment I took a vertical video on my smartphone and uploaded it into CVAT. In CVAT the video is rotated and became horizontal. Is it expected?

**Comment by azhavoro** [comment]
@bsekachev Yes, your video stored horizontally with `rotate=90` field in the metadata (you can check this with ffprobe tool). Currently it isn't supported, but this PR https://github.com/openvinotoolkit/cvat/pull/2218 should fix this issue.

**Comment by udamaster** [comment]
> can't, not for public access, but I solved the problem by changing the width and height

Having the same issue, can you please tell me how you changed the width/height? Not seeing options in CVAT for that. thx!
