### ISSUE TITLE
Integration with crowd sourcing platforms/frameworks

### ISSUE THREAD

**Issue by disssid** [openvinotoolkit/cvat#2247]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context
Is there a plan to provide integrations with crowd sourcing frameworks like PyBOSSA. I looked at the issues and found a request for MTurk, but there wasn't much progress. 

Thank You

**Comment by bsekachev** [comment]
Related issue #20
There are some thoughts about, but they aren't on stage active development.

**Comment by disssid** [comment]
Thank you for the response. If I want to contribute and start working on this, can you please tell me what would be the starting point and a rough checklist of how to go about it?

**Comment by nmanovic** [comment]
I will close as a duplicate. Probably it isn't an issue. It is a project.
