### ISSUE TITLE
[cvat.org] Could not get models from the server, Could not get users from the server, Could not fetch tasks - I keep getting this messages when I try to label and upload documents. It says that there is an issue with the network although I have a stable internet connection. Please help!

### ISSUE THREAD

**Issue by mosqmara** [openvinotoolkit/cvat#2252]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@mosqmara Hi, please don't ignore the issue template and fill the missed fields. I cannot help you without details of your issue.

**Comment by azhavoro** [comment]
Upd: I just read your post on Gitter, the issue has been fixed.
