### ISSUE TITLE
AI Tools missing from the CVAT.org online tool

### ISSUE THREAD

**Issue by vineethdas** [openvinotoolkit/cvat#2256]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
AI tool used for  automatic image annotation has been removed

### Current Behaviour
Will this change be reverted or is completely removed?

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@vineethdas Hi, thanks for the report, fixed.

**Comment by vineethdas** [comment]
thanks a lot for the update!
