### ISSUE TITLE
Migrate datasets from CVAT 2.3 to 3.3

### ISSUE THREAD

**Issue by davodogster** [openvinotoolkit/cvat#2258]
Hi, Is there a fast way to migrate datasets from CVAT 2.3 to 3.3? I currently have 2.3 running with 20+ annotated datasets and I want to move them to 3.3. I also want to be able to launch CVAT v3 (with serverless capability on my linux machine) in parallel with v2.3 before I stop running CVAT v2.3 to make sure v3 is working well with serverless enabled. I tried to launch cvat v3 in paralell already but docker names 'cvat_db' and cvat_redis are already in use from CVATv2.

**Comment by azhavoro** [comment]
Hi, this is not version of CVAT, this is just version of config file for docker-compose,
You only need to make one change: if you used an override file, change the version from 2.3 to 3.3, nothing else.
