### ISSUE TITLE
Cannot dump data as segmentation mask

### ISSUE THREAD

**Issue by PNeigel** [openvinotoolkit/cvat#2264]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I click on Actions -> Dump Annotations -> Segmentation Mask and it lets me download the segmentation masks.

### Current Behaviour

I do the above, nothing happens, and windows 10 notifies me that the WSL 2 backend has stopped unexpectedly.
It seems to work with other types of dumps (e.g. CVAT for images), but not "Segmentation Mask"

### Steps to Reproduce (for bugs)

1. Make dataset task, where every image is its own job (203 jobs)
2. Annotate the images
3. Actions -> Dump Annotations -> Segmentation Mask

### Your Environment

- Git hash commit (`git log -1`):
- Docker version '2.3.0.5':
- Are you using Docker Swarm or Kubernetes?
    Docker Desktop
- Operating System and version (e.g. Linux, Windows, MacOS):
    Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    2020-10-06 12:47:56,565 DEBG 'runserver' stdout output:
    Successfully ran command.

    2020-10-06 12:47:56,570 DEBG 'runserver' stdout output:
    Server URL         : http://localhost:8080/
    Server Root        : /tmp/cvat-server
    Server Conf        : /tmp/cvat-server/httpd.conf
    Error Log File     : /dev/stderr (INFO)
    Request Capacity   : 5 (1 process * 5 threads)
    Request Timeout    : 60 (seconds)
    Startup Timeout    : 15 (seconds)
    Queue Backlog      : 100 (connections)
    Queue Timeout      : 45 (seconds)
    Server Capacity    : 20 (event/worker), 20 (prefork)
    Server Backlog     : 500 (connections)
    Locale Setting     : C.UTF-8
    
    2020-10-06 12:47:56,646 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:47:56.646294 2020] [mpm_event:notice] [pid 14:tid 140218696096832] AH00489: Apache/2.4.41 (Ubuntu) mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations
    [Tue Oct 06 12:47:56.646274 2020] [wsgi:info] [pid 277:tid 140218696096832] mod_wsgi (pid=277): Starting process 'localhost:8080' with threads=5.
    [Tue Oct 06 12:47:56.646362 2020] [mpm_event:info] [pid 14:tid 140218696096832] AH00490: Server built: 2020-08-12T19:46:17
    [Tue Oct 06 12:47:56.646369 2020] [core:notice] [pid 14:tid 140218696096832] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/cvat-server/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'

    2020-10-06 12:47:56,647 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:47:56.647779 2020] [wsgi:info] [pid 277:tid 140218696096832] mod_wsgi (pid=277): Python home /usr.

    2020-10-06 12:47:56,648 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:47:56.648854 2020] [wsgi:info] [pid 277:tid 140218696096832] mod_wsgi (pid=277): Initializing Python.

    2020-10-06 12:47:56,690 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:47:56.690624 2020] [wsgi:info] [pid 277:tid 140218696096832] mod_wsgi (pid=277): Attach interpreter ''.

    2020-10-06 12:47:56,694 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:47:56.694485 2020] [wsgi:info] [pid 277:tid 140218696096832] mod_wsgi (pid=277): Imported 'mod_wsgi'.

    2020-10-06 12:47:56,694 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:47:56.694544 2020] [wsgi:info] [pid 277:tid 140218696096832] mod_wsgi (pid=277, process='localhost:8080', application=''): Loading Python script file '/tmp/cvat-server/handler.wsgi'.

    2020-10-06 12:47:56,868 DEBG 'ssh-agent' stderr output:
    debug2: fd 4 setting O_NONBLOCK

    2020-10-06 12:47:56,869 DEBG 'ssh-agent' stderr output:
    debug1: process_message: socket 1 (fd=4) type 17

    2020-10-06 12:47:56,871 DEBG 'ssh-agent' stderr output:
    debug1: process_add_identity: add ssh-rsa SHA256:6q1QvszNhPzO+ixk76DefVGNTVnUVysj5hDAcZooefU "django@22d199ea6926" (life: 0) (confirm: 0) (provider: none)

    2020-10-06 12:47:56,874 DEBG 'ssh-agent' stderr output:
    debug2: fd 4 setting O_NONBLOCK
    debug1: process_message: socket 1 (fd=4) type 11

    2020-10-06 12:48:16,299 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:48:16.299081 2020] [wsgi:error] [pid 277:tid 140218571785984] [remote 172.28.0.7:35616] [2020-10-06 12:48:16,298] WARNING django.request: Not Found: /analytics/app/kibana

    2020-10-06 12:48:16,304 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:48:16.304388 2020] [wsgi:error] [pid 277:tid 140218571785984] [remote 172.28.0.7:35616] WARNING:django.request:Not Found: /analytics/app/kibana

    2020-10-06 12:48:20,496 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:48:20.495832 2020] [wsgi:error] [pid 277:tid 140218555000576] [remote 172.28.0.7:35644] [2020-10-06 12:48:20,495] INFO cvat.server.task_2: get repository request

    2020-10-06 12:48:20,496 DEBG 'runserver' stderr output:
    [Tue Oct 06 12:48:20.495978 2020] [wsgi:error] [pid 277:tid 140218555000576] [remote 172.28.0.7:35644] INFO:cvat.server.task_2:get repository request

    2020-10-06 12:48:40,378 DEBG 'rqworker_default_0' stderr output:
    INFO:rq.worker:default: cvat.apps.dataset_manager.views.export_task_annotations(2, 'Segmentation mask 1.1', 'http://192.168.21.104:8080') (/api/v1/tasks/2/annotations/Segmentation mask 1.1)

    2020-10-06 12:48:40,378 DEBG 'rqworker_default_0' stderr output:
    DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

    2020-10-06 12:48:40,383 DEBG 'rqworker_default_0' stderr output:
    DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.

    2020-10-06 12:49:10,383 DEBG 'rqworker_default_0' stderr output:
    DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Hi, can you check if it was Out of memory error? For example, using `dmesg -HTw`

**Comment by PNeigel** [comment]
Yes, probably was a memory error. I freed up some gigs of RAM and now it works 👍
