### ISSUE TITLE
how to include our own model in the model list

### ISSUE THREAD

**Issue by Ironman1508** [openvinotoolkit/cvat#2270]
Hello, Can someone share the process/steps to include our own like yolov3, yolov5, or faster rcnn model into the **Model** list for automatic/ semi automatic annotation. I wanna add my own model which i have trained on my own dataset.

**Comment by nmanovic** [comment]
@Ironman1508 , we are working on the tutorial. For now you have to look at examples inside the repository:  https://github.com/openvinotoolkit/cvat/tree/develop/serverless

**Comment by s3298230** [comment]
> @Ironman1508 , we are working on the tutorial. For now you have to look at examples inside the repository: https://github.com/openvinotoolkit/cvat/tree/develop/serverless

Hi @nmanovic, I did replace the files needed for "yolo-v3 tf" with my custom model (IR files) and have no change to the code except for the number of classes is now only 1 for my custom class.

My custom yolov3 tf model  built from darknet and convert to Openvino (IR) but the CVAT default yolo-v3 tf seems to built from Keras. Could this be the reason ?

**Comment by valavanisleonidas** [comment]
Is it added in the tutorial ? I haven't found it anywhere
