### ISSUE TITLE
How to use "person re-identification" model  installed in CVAT?

### ISSUE THREAD

**Issue by charlescho64** [openvinotoolkit/cvat#2277]
### My actions before raising this issue
- [V] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ V] Searched [past issues](/issues)

### Expected Behaviour

In other Git for "REID model", I try to get result for searching objects similar to input object. But I don't know how to use REID model in automatic annotation functionality. 
  
### Current Behaviour

I uploaded street(including person) mp4 to cvat, and try to use reid model for automatic annotation. But I don't get any. I don't know how to use this model. I had something for other model in cvat.

### Possible Solution

Let me get to use REID mode in cvat.

### Steps to Reproduce (for bugs)

1. upload mp4 file(including person) to cvat
1. run automatic annotation with reid model
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by charlescho64** [comment]
Hello, 

If anybody know how to use ReID in CVAT, plz let me know.

**Comment by bsekachev** [comment]
Hi, 
To install ReID model, with installed nuclio from ``serverless`` subdirectory perform:

```bash
nuctl deploy --project-name cvat \
    --path "`pwd`/openvino/omz/intel/person-reidentification-retail-300/nuclio" \
    --volume "`pwd`/openvino/common:/opt/nuclio/common" \
    --platform local
```
 Or just run the script ``serverless/deploy.sh``, but it will install all available models.

ReID doesn't perform person detection, it performs joining of separated shapes into tracks. 
For example on two frames you have the same person that is annotated by different rectangles, ReID automatically merges these shapes into the track (track is an object that exist on a range of frames, shape is an object that exist on a single frame). To person detection you can use another model (Faster RCNN for example).

**Comment by omarreda14** [comment]
@bsekachev  is there any tutorials or user manual to get in Re-Id  ?
