### ISSUE TITLE
CVAT Mounted bucket task issue 

### ISSUE THREAD

**Issue by theYGE** [openvinotoolkit/cvat#2283]
Hi,
I currently have CVAT installed on a gcloud Compute Engine VM.
On the same VM there is a mounted bucket from Google Cloud.
When I log in into CVAT and add files manually from my computer, the task works fine.
However, there is a problem when I try to create a job with the files from a mounted location. 
CVAT UI sees the location and allows me to choose the files, but when I click "Submit" button, I get the following error.

_Couldn't create task.
Error: Could not create the task on the server. OSError: [Errno 5] input/output error:
'home/django/share/test/testfile.jpg'_

Is there a standard procedure to fix this issue? Thanks!

**Comment by bsekachev** [comment]
Hi, @theYGE 

``home/django/share/test/testfile.jpg`` doesn't look like a correct linux path. 
Could you please send us request/response info for  POST request ``api/v1/tasks/13/data`` (you can find it in chrome dev tools, open it on network tab before submitting a task).
You can see there something like: ``server_files[0]: /data 1/data/1/preview.jpeg`` (but with your paths)

**Comment by theYGE** [comment]
Hi, @bsekachev , thank you for your response.
I've found this method in network tab.

Here is the preview:
```
{chunk_size: null, size: 0, image_quality: 70, start_frame: 0, stop_frame: 0, frame_filter: "",…}
chunk_size: null
client_files: []
compressed_chunk_type: "imageset"
frame_filter: ""
image_quality: 70
original_chunk_type: "imageset"
remote_files: []
server_files: ["/test/"]
size: 0
start_frame: 0
stop_frame: 0
use_zip_chunks: false

```

Here are the headers
```
Request URL: https://XXX/api/v1/tasks/109/data
Request Method: POST
Status Code: 202 
Remote Address: 
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
allow: GET, POST, HEAD, OPTIONS
content-length: 249
content-type: application/json
date: Fri, 16 Oct 2020 06:34:31 GMT
server: nginx/1.16.1
status: 202
vary: Accept,Origin
x-frame-options: SAMEORIGIN
:authority: 
:method: POST
:path: /api/v1/tasks/109/data
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,ru;q=0.8
authorization: Token
content-length: 359
content-type: multipart/form-data; boundary=----WebKitFormBoundary52TprlRwWJQLuL4I
cookie: sessionid=ogxgdkolzbcow9uyg9f51gdimbkb8cyl; csrftoken=w8DSo4IAlVEIF0P3jLbS8ROU0BB29JikgpbNeVvMPaxsgGfN9I9xS6hLCC1hecFz
origin: 
referer: https://XXX/tasks/create
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
x-csrftoken: 
server_files[0]: /test/
image_quality: 70
use_zip_chunks: true
```

And here is the response:
`
{"chunk_size":null,"size":0,"image_quality":70,"start_frame":0,"stop_frame":0,"frame_filter":"","compressed_chunk_type":"imageset","original_chunk_type":"imageset","client_files":[],"server_files":["/test/"],"remote_files":[],"use_zip_chunks":false}`


I've noticed that it says:
`"server_files":["/test/"]`
instead of: 
`[home/django/share/test/testfile.jpg]`

Can it be an issue with the mapping?
What might be the cause of the cause?

Thank you for your help

**Comment by bsekachev** [comment]
Hi, sorry for delay.

> Can it be an issue with the mapping?

No, It is not a problem. If you select a collapsed directory, it sends the whole directory and uses all the files inside the directory in a task. I even try the same scenario and task was successful. Maybe just updating CVAT will help you. I am not sure what version you use, but I don't see the error on the latest develop.

**Comment by theYGE** [comment]
Hi, @bsekachev .
Thank you for your reply. Can it ben an issue with the permissions then?

**Comment by bsekachev** [comment]
> Hi, @bsekachev .
> Thank you for your reply. Can it ben an issue with the permissions then?

Theoretically it could be permissions issue, but in this case I think you wouldn't be able to see the list of files. Did you try update CVAT?

**Comment by theYGE** [comment]
Hi, @bsekachev . Thanks a lot for your help!
Turns out it was a problem with a mounted drive and even though CVAT recognized the files, it couldn't read them.

**Comment by bamwani** [comment]
@theYGE How did you solve this?
