### ISSUE TITLE
Docker-compose build error

### ISSUE THREAD

**Issue by sivaishere** [openvinotoolkit/cvat#2291]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Trying to install cvat on my lightsail instance on aws. When running the docker-compose build the following error occurs:

`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-
functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2
 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURC
E=2 build/temp.linux-x86_64-3.8/src/av/buffer.o -lswscale -lavdevice -lavcodec -lswresampl
e -lavfilter -lavutil -lavformat -o build/lib.linux-x86_64-3.8/av/buffer.cpython-38-x86_64
-linux-gnu.so
    building 'av.error' extension
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O
2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fs
tack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fP
IC -I/usr/include/x86_64-linux-gnu -I/usr/include/python3.8 -Ibuild/temp.linux-x86_64-3.8/
include -Iinclude -I/usr/include/python3.8 -Ibuild/temp.linux-x86_64-3.8/include -c src/av
/error.c -o build/temp.linux-x86_64-3.8/src/av/error.o
    x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setupto
ols, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_8dyn85c/av/setup.py'"'"'; __file__='"'
"'/tmp/pip-install-_8dyn85c/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__f
ile__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __
file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3seul6t0/install-record.txt --s
ingle-version-externally-managed --compile --install-headers /usr/local/include/python3.8/
av Check the logs for full command output.
WARNING: You are using pip version 20.0.1; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' comm
and.
ERROR: Service 'cvat' failed to build : The command '/bin/sh -c python3 -m pip install --n
o-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt' returned a non-zero code: 1`

### Your Environment

- Git hash commit (`git log -1`): commit 10964b9b23b493544d631c664f46165c60d78eda
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.13
- Are you using Docker Swarm or Kubernetes? : no
- Operating System and version (e.g. Linux, Windows, MacOS): Linux ubutnu 18.04;aws lightsail-512mb ram,20gb ssd
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by azhavoro** [comment]
Hi, I cannot reproduce this issue.
```
fatal error: Killed signal terminated program cc1 compilation terminated
```
I guess the cause for this issue the RAM size, please try increasing. Anyway, I think 512MB is too small for CVAT to work.

**Comment by sivaishere** [comment]
Will 1gb of ram work?
