### ISSUE TITLE
How to deploy Nuclio remotely?

### ISSUE THREAD

**Issue by lll9p** [openvinotoolkit/cvat#2301]
Hi, I deployed CVAT on a web server (without GPU), and now I want to use the automatic annotation tool on CVAT.

Is it possible to deploy Nuclio on another server with GPU installed, and then use Nuclio remotely?

like this:

CVAT(on server without GPU) <---> NUCLIO(on server with GPU)

Is there any example about this?

Thanks!

**Comment by bsekachev** [comment]
I can only suggest that it is possible by changing corresponding settings of nuclio dashboard in ``cvat/settings/base.py``:

```python
NUCLIO = {
    'SCHEME': 'http',
    'HOST': 'localhost',
    'PORT': 8070,
    'DEFAULT_TIMEOUT': 120
}
```

**Comment by ganindu7** [comment]
once I modify these vaibles 

```
NUCLIO = {
    'SCHEME': os.getenv('CVAT_NUCLIO_SCHEME', 'http'),
    'HOST': os.getenv('CVAT_NUCLIO_HOST', 'aisrv.gnet.lan'),
    'PORT': int(os.getenv('CVAT_NUCLIO_PORT', 30936)),
    'DEFAULT_TIMEOUT': int(os.getenv('CVAT_NUCLIO_DEFAULT_TIMEOUT', 120)),
    'FUNCTION_NAMESPACE': os.getenv('CVAT_NUCLIO_FUNCTION_NAMESPACE', 'nuclio'),
    'INVOKE_METHOD': os.getenv('CVAT_NUCLIO_INVOKE_METHOD',
        default='dashboard' if 'KUBERNETES_SERVICE_HOST' in os.environ else 'direct'),
}

```

do I need to have these in a seperate yaml ? 

  cvat_server:
    environment:
      CVAT_SERVERLESS: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cvat_worker_annotation:
    extra_hosts:
      - "host.docker.internal:host-gateway"
~
