### ISSUE TITLE
Annotate disconnect objects as a single instance

### ISSUE THREAD

**Issue by mmaaz60** [openvinotoolkit/cvat#2310]
Hi,

Can I annotate disjoint objects (occluded objects) as a single segment using CVAT? If yes then how?

Example: https://camo.githubusercontent.com/33478dd2ac65c7bc332799826e324fa16a2f7cbf/68747470733a2f2f692e696d6775722e636f6d2f354f5a4f5a344b2e6a7067

Grateful,
M. Maaz

**Comment by bsekachev** [comment]
You can use [shape grouping](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/user_guide.md#shape-grouping) functionality. In annotations file grouped objects have the same group_id. Also you can setup color by group in the user interface.

**Comment by nmanovic** [comment]
@mmaaz60 , Another approach is to use z-order. You can annotate the car as one object. After that annotate the tree branch as a background object. Thus on the frame you will have the car as a foreground object, an explicit background object, all other annotated pixels you can consider as background by default.
