### ISSUE TITLE
Unable to create a new task on CVAT.org

### ISSUE THREAD

**Issue by cyrilzakka** [openvinotoolkit/cvat#2315]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I've previously created two tasks on CVAT and they're currently being annotated. For the past two days, I've been trying to create a third, but when I press the submit button, I get the following error:
`Could not create the task: Open the Browser Console to get details`. Opening up the console, I just get a general `Failed to load resource: the server responded with a status of 500 (Internal Server Error). 
Error: Request failed with status code 500.`. 

### Expected Behaviour
The video should be uploaded the task should be created.

### Current Behaviour
The UI errors out upon pressing the submit button.

### Possible Solution
I thought it might be a hard limit on the number of tasks I can create on CVAT, or the maximum size of video I can upload. But turns out you can create up to 10 tasks, with a limit of 500mb each so that's not it.

### Steps to Reproduce (for bugs)
1. Login
2. Create Labels
3. Select video to upload
4. Submit for task creation

### Context
I can't create a third segmentation task.

### Your Environment
I'm using the online UI at CVAT.org.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@cyrilzakka Hi, is it possible to share this video?

**Comment by cyrilzakka** [comment]
I think I've isolated the issue. It seems that raw labels from one task can't be copied over to another task. It fails silently and you get the Error 500 I mentioned above. Might be an ID issue as far as I can tell.

**Comment by azhavoro** [comment]
Yes, please use `Copy` button 
![image](https://user-images.githubusercontent.com/41117609/95954387-e5525100-0e03-11eb-8c7e-b26e1e9f0053.png)

**Comment by azhavoro** [comment]
@cyrilzakka the issue is resolved?

**Comment by cyrilzakka** [comment]
Yes thank you!

**Comment by shajahanpc** [comment]
For for mine also getting same issue, Can you guys help me out?

I cant upload task into CVAT.

**Comment by kaylC4** [comment]
Hi, I have the same issue, unable to submit the task, this is the console error:
`unexpected response while creating upload, originated from request (method: POST, url: https://cvat.org//api/v1/tasks/184550/data/, response code: 405, response text`

**Comment by johnfoxy** [comment]
> Hi, I have the same issue, unable to submit the task, this is the console error: `unexpected response while creating upload, originated from request (method: POST, url: https://cvat.org//api/v1/tasks/184550/data/, response code: 405, response text`

hey @kaylC4 did you resolve this?

**Comment by shajahanpc** [comment]
Hi @johnfoxy @kaylC4 I resolved this issue by checking my dataset format. Kindly use JPG data to upload. I mean you can set all your data JPG into a Zip folder and upload it. Then the task will be created.

Note: If your data is another format like PNG, TIFF then converts to JPG.

Kindly let me know your feedback if your are not succeed.

**Comment by johnfoxy** [comment]
> Hi @johnfoxy @kaylC4 I resolved this issue by checking my dataset format. Kindly use JPG data to upload. I mean you can set all your data JPG into a Zip folder and upload it. Then the task will be created.
> 
> Note: If your data is another format like PNG, TIFF then converts to JPG.
> 
> Kindly let me know your feedback if your are not succeed.

Thank you so so much @shajahanpc The problem was my extension, my files were *.TIFF so I converted to .PNG and now it worls. Thank you so much. 
I wish CVAT would expressly mention the image formats supported!
Thanks again.

**Comment by shajahanpc** [comment]
@johnfoxy You are welcome! I'm glad too that everything is fine with you.
