### ISSUE TITLE
Add shortcuts for changing the current label

### ISSUE THREAD

**Issue by cpudney** [openvinotoolkit/cvat#2317]
It would be useful if keyboard shortcuts existed for the labels used during an annotation task.

During the annotation process it is often necessary to change to a different label from the current one. This involves using the mouse to select the label in the annotation widgets on the left-hand side of the GUI. Providing this action via a shortcut would make annotation more facile and quicker.

The shortcuts could be keys: 0 ... 9 and would correspond to the (first 10) labels (e.g. alphabetically ordered).

**Comment by bsekachev** [comment]
Hi,

One question here. Where a label should be changed? In all drawing popups? Or on the latest used? Or only for N shortcut? How do you see the feature?

Additionally I can say that 0 ... 9 isn't the best choice, because these keys used in attribute annotation mode. We can use them only with an additional modifier (like ctrl or shift). In long term view these shortcuts could be setup by a user.

**Comment by cpudney** [comment]
Thanks, Boris for your quick response.

> Where a label should be changed?
> In all drawing popups? Or on the latest used? Or only for N shortcut? 

Ideally, apply to all drawing popups but if that's not feasible, the current drawing mode (N shortcut). So for example

1. you select the polygon drawing method and a specific label
2. label several objects in the image for the current label (using N shortcut in the process)
3. now you want to start labelling a new category of object so use the new shortcut (e.g. Ctrl+2) to switch to the new label
4. continue labelling objects in the usual fashion

>We can use them only with an additional modifier (like ctrl or shift)

Understood - I think Ctrl+<number key> (or Alt?) might be better as Shift+<number key> produces different characters on various keyboard layouts.

**Comment by xyc2690** [comment]
Any update? How could I help to do it?

**Comment by bsekachev** [comment]
Hi, @xyc2690 

The core team isn't working on the feature. If somebody from the community could propose a PR, it would be great

**Comment by xyc2690** [comment]
> 
> 
> Hi, @xyc2690
> 
> The core team isn't working on the feature. If somebody from the community could propose a PR, it would be great

Thanks for your kind notification.
I am willing to work on the feature, however, I am not familiar with TS. 
Does there any examples or similar functions which I can take them as references?

**Comment by bsekachev** [comment]
@xyc2690 

TS is just a superset of JS, nothing really difficult if you familiar with JS. You can look how other shortcuts are implemented I suppose. I would suggest to make a search using key ``GlobalHotKeys`` in the project. We use the library https://github.com/greena13/react-hotkeys to maintain shortcuts.

**Comment by xyc2690** [comment]
> 
> 
> @xyc2690
> 
> TS is just a superset of JS, nothing really difficult if you familiar with JS. You can look how other shortcuts are implemented I suppose. I would suggest to make a search using key `GlobalHotKeys` in the project. We use the library https://github.com/greena13/react-hotkeys to maintain shortcuts.

Thanks a lot, I will try to make it！

**Comment by lisc199** [comment]
@xyc2690 Hi~ I have the same requirement. Have you achieved this function?

**Comment by JimEverest** [comment]
Same requirement. It's a very useful shortcut for improving work efficiency.

**Comment by Serakov** [comment]
Same requirement. It's a very useful shortcut.
