### ISSUE TITLE
Polyon point becomes significantly bigger when selected and released unlike previous versions hindering accurate annotation

### ISSUE THREAD

**Issue by smajida** [openvinotoolkit/cvat#2329]
# My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
If a point is selected and mouse gets away from it, its size shall not change similar to the early versions.

### Current Behaviour
When a point is select and mouse gets away from it, it becomes significantly bigger which hinders to see the area near that point.
![Screenshot from 2020-10-17 14-01-11](https://user-images.githubusercontent.com/12903362/96336653-9c0f3500-1081-11eb-8062-83d0b9aeb500.jpg)
![Screenshot from 2020-10-17 14-01-18](https://user-images.githubusercontent.com/12903362/96336654-9ca7cb80-1081-11eb-8393-b887aacb8438.jpg)
![Screenshot from 2020-10-17 14-01-27](https://user-images.githubusercontent.com/12903362/96336655-9d406200-1081-11eb-8142-807418786282.jpg)
![Screenshot from 2020-10-17 14-01-34](https://user-images.githubusercontent.com/12903362/96336656-9dd8f880-1081-11eb-93ea-09ae63cbbcc3.jpg)
![Screenshot from 2020-10-17 14-02-02](https://user-images.githubusercontent.com/12903362/96336657-9e718f00-1081-11eb-8060-8d0edce52649.jpg)
![Screenshot from 2020-10-17 14-02-06](https://user-images.githubusercontent.com/12903362/96336658-9f0a2580-1081-11eb-8e17-25b3e7938a71.jpg)
### Possible Solution
Reverting back to the previous settings?!

### Steps to Reproduce (for bugs)
1. start with creating a polygon.
2. create a point a release the mouse click. you see the points are becoming significantly bigger.
3. when you select another point and keep the left mouse click still pressed, the points appear with normal size, but as soon a you release the left click, they come larger.

### Context
It does not allow fine annotation because it blocks to see area near that point.

### Your Environment
Origin/develop branch - 19th October 2020 
Linux

**Comment by bsekachev** [comment]
Please, provide exact version (not ``latest``) and git hash.

**Comment by bsekachev** [comment]
I would say we have fixed similar issue in #2307

**Comment by smajida** [comment]
Oops!
@bsekachev 
I used the "origin/develop" branch which has the commit dating until October 9th. 2020. I did not use any specific git tags as I wanted to clone the latest develop version.
I see the commit below as the latest commit by calling "git log"

commit 2b221d26fd65cd4f7c81d19247459f3f2416ed73
Author: tdowgiel <tomasz.dowgielewicz@intel.com>
Date:   Fri Oct 9 21:13:47 2020 +0200

Thanks. I see issue in #2307 dates back to 8 days ago. I will pull the merge and try again. I will update this issue afterwards.

**Comment by smajida** [comment]
@bsekachev 

I just pulled the repo by "git pull" and compiled it again
"docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml -f components/analytics/docker-compose.analytics.yml  up -d"
Still points appear to be bigger when selected and released.

**Comment by bsekachev** [comment]
``up -d`` doesn't rebuild image.
You need to use ``up --build -d``

**Comment by smajida** [comment]
@bsekachev  
Oh I missed it. Now it is being built, but it takes long to finish.
In this way, even by a tiny modification in the code, the whole repo has to be built again.
I am wondering whether there is any alternatives to compile the code faster and see the changes.

**Comment by bsekachev** [comment]
@smajida 

Internally we use docker deployment only for production. For development & debugging we install the whole system on a host operating system. The process is described in CONTRIBUTING.md

**Comment by smajida** [comment]
@bsekachev 
Thanks for the explanation. 
I can confirm that the issue has been solved. I will then close the issue.
