### ISSUE TITLE
Labels are not imported from yolo datasets

### ISSUE THREAD

**Issue by stiv-yakovenko** [openvinotoolkit/cvat#2331]
I have a dataset:

![image](https://user-images.githubusercontent.com/4163254/96375151-7d07c480-11a1-11eb-99ac-89a14d02f38a.png)
![image](https://user-images.githubusercontent.com/4163254/96375167-8db83a80-11a1-11eb-9230-9bf065b71570.png)
![image](https://user-images.githubusercontent.com/4163254/96375209-c6581400-11a1-11eb-972d-98e71088f58c.png)
![image](https://user-images.githubusercontent.com/4163254/96375232-e2f44c00-11a1-11eb-8cd0-d0aefab937ed.png)

all of this is compressed into zip file and uploaded to cvat:
![image](https://user-images.githubusercontent.com/4163254/96375259-07e8bf00-11a2-11eb-8ad5-294f10fbc355.png)

I can see pictures but there are no labels, labels are not imported:
![image](https://user-images.githubusercontent.com/4163254/96375296-601fc100-11a2-11eb-8336-41cd1096d8a0.png)

How can I fix that? I had to create label z in order for it to allow me import the dataset. This is strange, should not it take labels from the dataset?

**Comment by zhiltsov-max** [comment]
Labels must be set in the task, they are not imported from annotations.

**Comment by stiv-yakovenko** [comment]
How can i import entire dataset from zip file?

**Comment by zhiltsov-max** [comment]
You should create a task and import annotations. There is no option to create a task from a file.

**Comment by nmanovic** [comment]
@stiv-yakovenko , it should be implemented in the PR: https://github.com/openvinotoolkit/cvat/pull/3790
