### ISSUE TITLE
Uploading huge yolo dataset causes error 500

### ISSUE THREAD

**Issue by stiv-yakovenko** [openvinotoolkit/cvat#2332]
I have 11G zip yolo dataset. When I try to upload it through web interface, i get these errors:

```
Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
    at create-task-content.tsx:156
:8080/api/v1/jobs/5/annotations?format=YOLO%201.1:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
cvat-app.tsx:217 Error: Request failed with status code 500. "Exception: Can't find image info for '/tmp/tmpnq5lma66/obj_train_data/frame_000000.png'\n".
e @ cvat-app.tsx:217
:8080/api/v1/tasks/6/data:1 Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
cvat-app.tsx:217 Error: Request failed with status code 413. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>413 Request Entity Too Large</title>\n</head><body>\n<h1>Request Entity Too Large</h1>\nThe requested resource does not allow request data with POST requests, or the amount of data provided in\nthe request exceeds the capacity limit.\n</body></html>\n".
```
how can we fix or workaround this?

**Comment by zhiltsov-max** [comment]
Can you describe the task? It looks like it is a video, and frame 0 is missing in the task.

**Comment by bsekachev** [comment]
To solve status code 413 (request entity too large), I would recommend you upload data via shared storage (not from local computer). You can attach the storage as it described [here](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path)

**Comment by azhavoro** [comment]
@stiv-yakovenko Did you solve this issue?

**Comment by stiv-yakovenko** [comment]
No, i gave up.

**Comment by ddebby** [comment]
See error, waiting for solution

```
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
cvat-app.tsx:208 Error: Request failed with status code 413. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>413 Request Entity Too Large</title>\n</head><body>\n<h1>Request Entity Too Large</h1>\nThe requested resource does not allow request data with POST requests, or the amount of data provided in\nthe request exceeds the capacity limit.\n</body></html>\n".

```

**Comment by haviduck** [comment]
> See error, waiting for solution
> 
> ```
> Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
> cvat-app.tsx:208 Error: Request failed with status code 413. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>413 Request Entity Too Large</title>\n</head><body>\n<h1>Request Entity Too Large</h1>\nThe requested resource does not allow request data with POST requests, or the amount of data provided in\nthe request exceeds the capacity limit.\n</body></html>\n".
> ```

nginx is set  client_max_body_size to 0 as should. is it django overriding or that sendfile lib? that one seems to utilize apache2, so im struggling ^^ Vinoguys! help? =)

**Comment by nmanovic** [comment]
https://github.com/openvinotoolkit/cvat/pull/3692
