### ISSUE TITLE
[Bug] this.el.node.getScreenCTM() is null

### ISSUE THREAD

**Issue by azhavoro** [openvinotoolkit/cvat#2335]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

```js
this.el.node.getScreenCTM() is null
e.prototype.update@https://cvat.org/cvat-ui.215f5569aef9e961668b.min.js:307:125619
e.prototype.start/<@https://cvat.org/cvat-ui.215f5569aef9e961668b.min.js:307:125112
```

### Expected Behaviour
No exceptions

### Current Behaviour
This is Firefox specific exception

### Steps to Reproduce (for bugs)
N/A

### Your Environment

- Git hash commit (`git log -1`):70e89d6f83d49b4109ebd316403ab4e54a3e13f9, but it happened before
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
Let's close the issue as outdated.
