### ISSUE TITLE
[Bug] Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by azhavoro** [openvinotoolkit/cvat#2337]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Chrome on different platforms (Win10, MacOS)

```js
TypeError: Cannot read property 'nodeType' of null
    at e.exports (https://cvat.org/cvat-ui.215f5569aef9e961668b.min.js:353:37896)
    at https://cvat.org/cvat-ui.215f5569aef9e961668b.min.js:353:1112765
```

### Steps to Reproduce (for bugs)

N/A

### Your Environment

- Git hash commit (`git log -1`): 70e89d6f83d49b4109ebd316403ab4e54a3e13f9
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Latest appeared on November 3rd in our dependencies. Probably was fixed.
