### ISSUE TITLE
Outside property not used for rectangle tracks at CVAT for Images 1.1

### ISSUE THREAD

**Issue by georkap** [openvinotoolkit/cvat#2339]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

We use interpolation of rectangles to annotate objects in annotation mode. Occasionally a rectangle is not visible so we mark it as "outside". The dumped annotation xml using "CVAT for Images 1.1" still includes entries for the "outside" rectangles at the frames where they were marked as "outside" without any indication that they are actually outside. Using CVAT version v.1.1.0

Related: https://github.com/openvinotoolkit/cvat/issues/1620 and https://github.com/openvinotoolkit/cvat/pull/1729

### Expected Behaviour

The expected behaviour is to exclude entries for the rectangles that are marked as "outside" (as was the case with "hidden" at v.0.6.1).

### Current Behaviour

As a test, we dumped the annotations using the "YOLO 1.1" format directly and the "outside" rectangles were excluded. Dumping with "CVAT for Videos 1.1" provides an "outside" attribute to the resulting xml however the output format of the xml is incompatible with the post-processing steps we developed using the previous CVAT version.

### Steps to Reproduce (for bugs)

1. Create a new task
1. Draw new Rectangle as Track (doesn't matter if 2-points or 4-points)  
1. Mark the rectangle at a random frame as "outside" 
1. Save
1. Dump annotations as "CVAT for Images 1.1"

### Context

I can't be sure if it a bug or desired behaviour introduced in the new version, however the usability of "hidden" from version 0.6.1 to hide object instances when annotating with interpolation mode cannot be reproduced neither with "hidden" nor with "outside".

### Your Environment

not relevant

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@georkap , thanks for the report. @zhiltsov-max , could you please look at the issue?
