### ISSUE TITLE
Exported dataset of image format

### ISSUE THREAD

**Issue by arthurtibame** [openvinotoolkit/cvat#2342]
With the title of issue, is it possible to export datasets of images with .jpg rather than the .png (default is .png)

BTW, I am using the latest version of cvat by docker

Many thanks.

**Comment by zhiltsov-max** [comment]
Images should have the same format, as they had initially. Videos are exported as `png` by default. If you want to convert them to another format, you can dump as `Datumaro`, and then export the dataset with `datum project export -- --image-ext=jpg`.

**Comment by azhavoro** [comment]
@arthurtibame does it answer your question?

**Comment by arthurtibame** [comment]
Sorry I just started to use cvat these days, could you please tell me where to input the command that you mentioned?

I am currently using it by docker container by the way. 
Many thanks

**Comment by zhiltsov-max** [comment]
[Datumaro](https://github.com/openvinotoolkit/datumaro) is a command line tool. Is it what you needed?

**Comment by azhavoro** [comment]
No response for a long time, I'll close the issue.
@arthurtibame Feel free to reopen if you still have questions.

**Comment by bobrolmil** [comment]
Hello, i am trying to export video as jpg dataset with datum export  -f yolo -- --save-images --image-ext='.jpg' and i getting ERROR: 'ProjectDataset' object has no attribute 'export', any ideas whats wrong? Thanks

**Comment by zhiltsov-max** [comment]
@bobrolmil, hi, fixed [here](https://github.com/openvinotoolkit/datumaro/pull/119)

**Comment by bobrolmil** [comment]
@zhiltsov-max Thank you very much!
