### ISSUE TITLE
Error: Request failed with status code 500. "OSError: [Errno 28] No space left on device: '/tmp/tmp3b4hjt77/obj_train_data/frame_04268

### ISSUE THREAD

**Issue by stoneMo** [openvinotoolkit/cvat#2348]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When I wanted to download my own dataset in YOLO format, it always shows that **no space left on the device** '/tmp/tmp3b4hjt77/obj_train_data/frame_04268'. But there is still space on my Mac. So I am very confused. Hope somebody can help me out. Thank you. Here is my docker-compose.override.yml file. 

![image](https://user-images.githubusercontent.com/59949790/96980113-e3019c80-1551-11eb-8fc6-883e3826606a.png)

`
version: "3.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /Users/stonemo/Downloads/agots/share_data host directory"
    volumes:
      - cvat_share:/home/django/share:ro
      - cvat_data:/home/django/data
    ports:
      - "80:8080"

volumes:
  cvat_data:
    driver_opts:
      type: none
      device: /Users/stonemo/Downloads/agots/data
      o: bind
  cvat_share:
    driver_opts:
      type: none
      device: /Users/stonemo/Downloads/agots/share_data
      o: bind
`

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05): 

Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

- Are you using Docker Swarm or Kubernetes? Docker Swarm 
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi, 
It says you are run out of drive memory. Probably CVAT could not prepare data for dataset exporting because of the issue. 
I would recommend to release some memory deleting extra files (maybe old tasks for example) or release memory on the host where docker volume is located.

**Comment by stoneMo** [comment]
> I would recommend to release some memory deleting extra files (maybe old tasks for example) or release memory on the host where docker volume is located.

Boris, thanks for your quick response. But how could I check where the docker volume is located? From my docker-compose.override.yml, I guess my docker volume is located at my device, like "/Users/stonemo/Downloads/agots/data", right?

**Comment by azhavoro** [comment]
@stoneMo Hi, please run `docker inspect cvat | grep "MergedDir" 'and free space on the device where the returned path is located.
`/tmp/tmp3b4hjt77/o` is not located on your volumes.

**Comment by stoneMo** [comment]
> docker inspect cvat | grep "MergedDir"

Hello, do you mean that the returned path is located on the docker, not on my volumes? Here is my returned path. But how to free space on that path. Where could I log in to the docker server? I am a freshman to the docker.  

![image](https://user-images.githubusercontent.com/59949790/96986856-cdda3d00-1554-11eb-9c30-730799c91c20.png)

**Comment by azhavoro** [comment]
The filesystem of the cvat container is just some folder on you host filesystem, so this folder is located on some partition that depends on your system configuration. You need to free space on this partition.

**Comment by stoneMo** [comment]
@azhavoro Hello, is there any way for me to find my system configuration to locate this partition?

**Comment by alalek** [comment]
Please refer to docker documentation:
https://docs.docker.com/docker-for-mac/space/

**Comment by azhavoro** [comment]
@stoneMo have you solved this issue?
