### ISSUE TITLE
Expand CVAT flexibility by adding more environment variables to cvat/settings/base.py

### ISSUE THREAD

**Issue by aleksandrmelnikov** [openvinotoolkit/cvat#2362]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Current Behaviour

Current paths are hard-coded.
```
SHARE_ROOT = os.path.join(BASE_DIR, 'share')
```

### Possible Solution

```
SHARE_ROOT = os.path.join(BASE_DIR,os.getenv("CVAT_SHARE_ROOT",'share'))
```

### Context

We're using CVAT inside a k8s environment.
Overall, it works great.

One issue we're running into is supporting CVAT on a wider range of machine types on Azure.

The main issue is we allow the user to create a volume for "keys", "logs", "data", "models", and so forth.
-We allow volumes to persist the data between pod restarts.
These volumes use up disks, and each machine type on Azure supports only so many disk.

One thing we can do is reduce volumes, and we can do that by putting logs, keys, etc, under one path.
- And this path would be under one volume

To make this work with CVAT, we can have python pull the path via environment variable, or default to the original setting in CVAT.
Example:
```
SHARE_ROOT = os.path.join(BASE_DIR,os.getenv("CVAT_SHARE_ROOT",'share'))
```

Relevant issues:
https://github.com/openvinotoolkit/cvat/issues/445
https://github.com/openvinotoolkit/cvat/pull/1641

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by aleksandrmelnikov** [comment]
We're working on this change and will create a PR for further review.

**Comment by nmanovic** [comment]
@aleksandrmelnikov , community added some environment variables. Let me know if it isn't enough. Don't hesitate to contribute. I will close the issue as outdated.
