### ISSUE TITLE
Project architecture issues

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [openvinotoolkit/cvat#2372]
Could you please provide the architectural diagram of the project? I want to learn about it

**Comment by bsekachev** [comment]
Right now I can provide not very detailed structure. But I believe we should make and support such the diagram in the future. 

![Screenshot from 2020-10-29 11-22-23](https://user-images.githubusercontent.com/40690378/97543290-14a6b780-19d9-11eb-9be2-aaa6c7b70656.png)
