### ISSUE TITLE
How to deploy CVAT behind nginx (ingress) without location path "/"

### ISSUE THREAD

**Issue by xuchenCN** [openvinotoolkit/cvat#2374]
I want to deploy cvat services for each user in my kubernetes cluster with the nginx-ingress.

like this:

userA access the cvat with the location `http://{host}/cvat-1`
userB access the cvat with the location `http://{host}/cvat-2`

I try to modify the login redirect url but it not working.

**Comment by nmanovic** [comment]
@xuchenCN , could you please explain why do you need it? I will suggest discussing the feature on gitter and transform to a feature request. I will close the issue for now.

**Comment by xuchenCN** [comment]
Hi @nmanovic , in my project I need provide CVAT service instance per user. 

I know CVAT is design for multi user with one instance, it can scale the `cvat-server` replicas behind `cvat-ui(Nginx)` and involved `nuclio` to solve the performace issue.

But it still hard to intigrate with my project cause redirect to absolute path "/".

I can only deploy CVAT in the wildcard domain like `cvat.xxxx.com`, this need config the A record (*.xxxx.com) in my IPS

**Comment by nmanovic** [comment]
Please send me a private message on gitter. I want to understand your use case better. I really believe that the proposed solution isn't the best for your case. Based on my experience it will lead to many issues after that. I hope together we will find an appropriate solution. Better to configure proxy to emulate something like that or add a specific feature into CVAT to support your use case.
