### ISSUE TITLE
Annotate disconnect objects as a single instance

### ISSUE THREAD

**Issue by smajida** [openvinotoolkit/cvat#2381]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
### Expected Behavior
sometimes objects disconnected due to occlusions caused by other objects. It would be could to link separate polygons or boxes together as single object.
### Current Behavior
Currently, it is not possible to link separate polygons or boxes with each other.
### Possible Solution
We could activate selecting more than one objects by keeping a button pressed and then press another hotkey to link them with each other as single object.

**Comment by bsekachev** [comment]
Looks like grouping feature.
Also you can use zorder to annotate occlusion as a background (or another class) in the case of semantic segmentation
Please refer to a user guide.

**Comment by smajida** [comment]
@bsekachev 

as mentioned here #2385 ,
There is a problem in grouping feature to be used for this purpose. The group-id does not appear in the annotation environment so it is not possible to tell which annotations are grouped with each other unless the annotations are dumped. Neither the color of polygons in instance mode nor their ID during the annotation do not become similar.

**Comment by bsekachev** [comment]
You can set color option "By Group" and then grouped objects will have the same color on canvas and in right side bar.

**Comment by borgarpa** [comment]
> You can set color option "By Group" and then grouped objects will have the same color on canvas and in right side bar.

Does grouped objects appear as a single instance when dumped into COCO labels?

**Comment by arasharchor** [comment]
@bsekachev 
@borgarpa 
when the objects have overlap with each other, merging them by grouping them should merge them into object which is the union of two objects. This is my understanding of merging.
