### ISSUE TITLE
Single image: There is no possibilities to merge polygons with each other or split a polygon into two polygons or more

### ISSUE THREAD

**Issue by arasharchor** [openvinotoolkit/cvat#2385]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
To be able merge several polygons - either with same classes or different ones - (more than two) with each other as the same class or assigning them a new label.
To be able to split a polygon into two or more polygons. Even splitting into two polygons will be great.

When annotating an object is not possible to be done with one polygon either because it is two big or it contains holes, one has to annotate the object into separate polygons which have to be merged with each other.

### Current Behaviour
At the moment, splitting and merging features apply only to videos and not single images and one does not have any options to merge polygons with each other or split them.
 
### Possible Solution
Merging:
One can think of keeping a button pressed and then select polygons and then press another button to merge them or another button to merge them and also ask for a new class naming.
Splitting:
One can think of splitting a polygon into two pieces in the editing mode, but instead of removing one of the polygons after the editing, keeping both polygons with a shared border.

**Comment by bsekachev** [comment]
Looks similar to #774 and #690
BTW, have you tried grouping feature?

**Comment by smajida** [comment]
@bsekachev 
Yes, I have tried grouping feature. I can select more than one polygons, but it is not clear which button shall be pressed after polygons are selected. I activate the grouping feature with G and select polygons. The next step to merge them is either not defined or I can not find it. 
Oops! I had not seen those previous issues.

**Comment by bsekachev** [comment]
You need activate grouping (with G, or with dedicated icon at left panel), select shapes, then deactivate grouping (in the same way). Selected shapes will be united to the same group and will have the same group_id in annotations file. 
To reset group of an object you need to select it in grouping mode and press shift+g

**Comment by smajida** [comment]
@bsekachev 
Grouping feature does not merge polygons with each other rather link them. In merging polygons, the overlapped area shalle be merge to make two or more polygons as one polygon. Also it should work if and only if the selected polygons have overlap with each other all.

However, in grouping feature, the polygons do not have to be overlapping each other and the feature keeps all of the polygon points which is unwanted. 

Regarding the grouping feature itself, it is useful for another issue which I made to connect disconnected objects with each other which can be done with this feature. However, there is a problem here, the group-id does not appear in the annotation environment so it is not possible to tell which annotations are grouped with each other unless the annotations are dumped. Neither the color of polygons in instance mode or their ID during the annotation do not become one.

**Comment by bsekachev** [comment]
> Also it should work if and only if the selected polygons have overlap 

Why do you believe this restriction makes sense? Or I do not understand your use case.
In my opinion we should allow an annotator to decide what polygons should be merged. 

> However, there is a problem here, the group-id does not appear in the annotation environment so it is not possible to tell which annotations are grouped with each other unless the annotations are dumped. 

I answered you in the separated issue.

**Comment by smajida** [comment]
From my point of view, there is a difference between merging and connecting/linking if the polygons have overlap each other.

Connecting/linking: polygons are separated and we want to assign them one unique object id while keeping all of the points.
Merging: making polygons (>=2) one polygon. It will be a 𝐴∪𝐵 and similar to the connecting operation if the polygons are separated, but if the polygons are overlapping each other, 𝐴∪𝐵 will be 𝐴∪𝐵 - 𝐴∩𝐵 i.e. the points in the intersection area will be removed. 
https://intl.siyavula.com/read/maths/grade-10/probability/14-probability-03

Please let me know if I am missing a point here.


I mentioned the issues concerning merging features usability in the corresponding issue #2381

**Comment by arasharchor** [comment]
@bsekachev 
any updates on this?

**Comment by bsekachev** [comment]
@arasharchor 

The issue has been moved to backlog. It means, that the core team doesn't have any current plan on implementation of this. 
CVAT is an open source tool and we hope the community help us with development it because internal resources are restricted

**Comment by ZA0068** [comment]
Well thats a shame. 

Seems a fork would be 100x better than the original...
