### ISSUE TITLE
Interface request problem

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [openvinotoolkit/cvat#2387]
In the 1.1.0 version of CVAT, I deployed Cavr-Server locally and got rid of Docker. When I checked the details of job, When I requested the interface of/Server /log, I kept turning in a circle, instead of automatically requesting the next interface. I wonder why
<img width="950" alt="logs" src="https://user-images.githubusercontent.com/15922437/97856132-db52ac80-1d36-11eb-861a-92cebbb5766c.png">

**Comment by bsekachev** [comment]
Please send logs from console. I see errors there.

**Comment by ITBOX-ITBOY** [comment]
> Please send logs from console. I see errors there.

![image](https://user-images.githubusercontent.com/15922437/97937200-f108b600-1db8-11eb-9b39-42af34a4ec28.png)

**Comment by bsekachev** [comment]
I mean console of the Browser immediately after you meet the issue. Logs you sent are clear.

**Comment by ITBOX-ITBOY** [comment]
> I mean console of the Browser immediately after you meet the issue. Logs you sent are clear.

<img width="943" alt="ttt" src="https://user-images.githubusercontent.com/15922437/97973518-276a2380-1e01-11eb-8afd-71faa0f57549.png">

**Comment by bsekachev** [comment]
We need all the console output. It's not clear what errors occurred on the screenshot you provided.

**Comment by ITBOX-ITBOY** [comment]
> I mean console of the Browser immediately after you meet the issue. Logs you sent are clear.

<img width="713" alt="1" src="https://user-images.githubusercontent.com/15922437/97974637-d65b2f00-1e02-11eb-9eee-a22f8171d7af.png">
<img width="941" alt="2" src="https://user-images.githubusercontent.com/15922437/97974644-db1fe300-1e02-11eb-996e-4a620153959b.png">
<img width="928" alt="3" src="https://user-images.githubusercontent.com/15922437/97974654-df4c0080-1e02-11eb-9602-a14b5a8c0907.png">

After requesting the /server/logs interface, there is a circular image on the front page
I don't know why I can't check the function now

**Comment by bsekachev** [comment]
It is a fragment of your screenshot. It says you have 6 errors in console output and to help we need to see the whole browser console output. 

![Screenshot from 2020-11-03 13-36-02](https://user-images.githubusercontent.com/40690378/97975064-90d63c00-1dd9-11eb-8c58-b2fcc0a2a935.png)

/server/logs request was successful, so I suppose it doesn't cause the issue.

**Comment by ITBOX-ITBOY** [comment]
> It is a fragment of your screenshot. It says you have 6 errors in console output and to help we need to see the whole browser console output.

For this one useful error, the others were due to my proxy network
<img width="941" alt="44" src="https://user-images.githubusercontent.com/15922437/97975561-4a4a0700-1e04-11eb-8be2-183d2731a983.png">

**Comment by bsekachev** [comment]
You've opened one more issue about this request #2389. Right? 
It could be a reason why you cannot open the job. CVAT cannot get frames from the server because of not authorized error.

**Comment by ITBOX-ITBOY** [comment]
> 您已经打开了有关此请求[＃2389的](https://github.com/openvinotoolkit/cvat/issues/2389)另一个问题。对？
> 这可能是您无法打开工作的原因。由于未授权错误，CVAT无法从服务器获取帧。

So how do I solve it

> You've opened one more issue about this request #2389. Right?
> It could be a reason why you cannot open the job. CVAT cannot get frames from the server because of not authorized error.

So how do I solve it

**Comment by ITBOX-ITBOY** [comment]
> > 您已经打开了有关此请求[＃2389的](https://github.com/openvinotoolkit/cvat/issues/2389)另一个问题。对？
> > 这可能是您无法打开工作的原因。由于未授权错误，CVAT无法从服务器获取帧。
> 
> So how do I solve it
> 
> > You've opened one more issue about this request #2389. Right?
> > It could be a reason why you cannot open the job. CVAT cannot get frames from the server because of not authorized error.
> 
> So how do I solve it

I put the CVAT project locally, away from the Docker environment

**Comment by ITBOX-ITBOY** [comment]
> You've opened one more issue about this request #2389. Right?
> It could be a reason why you cannot open the job. CVAT cannot get frames from the server because of not authorized error.

So how do I solve it

**Comment by bsekachev** [comment]
![image](https://user-images.githubusercontent.com/40690378/97976229-67b6ab00-1ddb-11eb-8f0f-5cef2c41a154.png)

On the screenshot you provided I see response header ``Access-Control-Allow-Origin: localhost:3000``. What is CVAT URL for you? localhost:3000?

**Comment by ITBOX-ITBOY** [comment]
> On the screenshot you provided I see response header `Access-Control-Allow-Origin: localhost:3000`. What is CVAT URL for you? localhost:3000?

My front-end CVat-UI is deployed locally, cVAT is deployed locally, and the Python environment USES the Conda virtual environment in the Centos7 virtual machine

**Comment by bsekachev** [comment]
I got it. But the question what was is current host for CVAT-UI?

**Comment by ITBOX-ITBOY** [comment]
> I got it. But the question what was is current host for CVAT-UI?

localhost:3000

**Comment by ITBOX-ITBOY** [comment]
> 我知道了。但是问题是CVAT-UI的当前主机是什么？


Front end service address is localhost:3000
The service port of the back-end cvat is 192.168.2.100:8000

**Comment by bsekachev** [comment]
In this case I would recommend trying to debug backend. For example set a breakpoint somewhere here: engine > views.py TaskViewSet > data on the first line. BTW, do you account with admin rights?

**Comment by ITBOX-ITBOY** [comment]
> In this case I would recommend trying to debug backend. For example set a breakpoint somewhere here: engine > views.py TaskViewSet > data on the first line. BTW, do you account with admin rights?

I have admin privileges, but what do I need to pay attention to? Now I have created the task successfully. I can't see the details of job, just look at the details of Job is club 401, or there is a circle on the page

**Comment by ITBOX-ITBOY** [comment]
> In this case I would recommend trying to debug backend. For example set a breakpoint somewhere here: engine > views.py TaskViewSet > data on the first line. BTW, do you account with admin rights?

Still asking about 401

[2020-11-03 10:16:51,069] WARNING django.request: Unauthorized: /api/v1/tasks/36/data
WARNING:django.request:Unauthorized: /api/v1/tasks/36/data
[2020-11-03 10:16:51,070] WARNING django.server: "GET /api/v1/tasks/36/data?type=chunk&number=0&quality=compressed HTTP/1.1" 401 58
WARNING:django.server:"GET /api/v1/tasks/36/data?type=chunk&number=0&quality=compressed HTTP/1.1" 401 58

**Comment by ITBOX-ITBOY** [comment]
> > In this case I would recommend trying to debug backend. For example set a breakpoint somewhere here: engine > views.py TaskViewSet > data on the first line. BTW, do you account with admin rights?
> 
> Still asking about 401
> 
> [2020-11-03 10:16:51,069] WARNING django.request: Unauthorized: /api/v1/tasks/36/data
> WARNING:django.request:Unauthorized: /api/v1/tasks/36/data
> [2020-11-03 10:16:51,070] WARNING django.server: "GET /api/v1/tasks/36/data?type=chunk&number=0&quality=compressed HTTP/1.1" 401 58
> WARNING:django.server:"GET /api/v1/tasks/36/data?type=chunk&number=0&quality=compressed HTTP/1.1" 401 58

The front end also reported an error：
DataCloneError: The object could not be cloned.

**Comment by ITBOX-ITBOY** [comment]
> > > In this case I would recommend trying to debug backend. For example set a breakpoint somewhere here: engine > views.py TaskViewSet > data on the first line. BTW, do you account with admin rights?
> > 
> > 
> > Still asking about 401
> > [2020-11-03 10:16:51,069] WARNING django.request: Unauthorized: /api/v1/tasks/36/data
> > WARNING:django.request:Unauthorized: /api/v1/tasks/36/data
> > [2020-11-03 10:16:51,070] WARNING django.server: "GET /api/v1/tasks/36/data?type=chunk&number=0&quality=compressed HTTP/1.1" 401 58
> > WARNING:django.server:"GET /api/v1/tasks/36/data?type=chunk&number=0&quality=compressed HTTP/1.1" 401 58
> 
> The front end also reported an error：
> DataCloneError: The object could not be cloned.

The problem has been solved.

Solutions:

Make the IP address of CVat-UI be the same as that of CVat-Server, otherwise it will jump to the canvas page improperly
