### ISSUE TITLE
401 Unauthorized 问题

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [openvinotoolkit/cvat#2389]
<img width="944" alt="test1" src="https://user-images.githubusercontent.com/15922437/97969493-1a4a3600-1dfb-11eb-99a1-c41e555cebc8.png">

<img width="960" alt="test" src="https://user-images.githubusercontent.com/15922437/97969398-f4bd2c80-1dfa-11eb-80ba-1a322dbf191d.png">

How to solve the above problem

**Comment by bsekachev** [comment]
Have you customized CVAT on your own or you get CVAT somewhere else (with Chinese characters)? 
We need to see logs from ``docker logs cvat`` after this error occur. It seems that now you are not authorized, but other requests are ok, so, I am not sure what is problem.

**Comment by liucong255** [comment]
![image](https://user-images.githubusercontent.com/38726093/148350205-9dd13764-defa-4307-8955-c3d719cee183.png)
I also have this problem, login in the project page error 401

**Comment by nmanovic** [comment]
@liucong255 , please create a separate issue and describe steps to reproduce. We will look. For now even CVAT version is unknown.
