### ISSUE TITLE
Segmentation mask image is 3 color channel whereas expected is 1 channel

### ISSUE THREAD

**Issue by min2bro** [openvinotoolkit/cvat#2390]
### My actions before raising this issue
- [x] Searched past issues

### Expected Behaviour
The "Segmentation mask 1.1" mask image should be single channel image

### Current Behaviour
The "Segmentation mask 1.1" mask image is 3 channel

### Steps to Reproduce (for bugs)

1. Go to Menu and press Dump Annotations > Segmentation mask 1.1
2. Unzip the compressed annotation folder
3. Navigate to "SegmentationClass" and check the shape of png images
4. All the png images are 3 color channels

### Context
I've two labels in the image so doing np.unique(img) returns array([0. , 0.00392157, 0.00784314], dtype=float32).
where 0 is background, 0.0039 is class 1 and 0.00784 is class 2 which is correct but the image is 3 color channel instead of 1.

**Comment by zhiltsov-max** [comment]
Hi. `Segmentation Mask` output is not supposed to be single-channel. You can find single-channel masks in `MOTS` format. Another way is to export in [`Datumaro` format](https://github.com/openvinotoolkit/datumaro), and then execute `datum project export -f voc -- --apply-colormap=0 [--save-images]`.

**Comment by MarioProjects** [comment]
I'm having issues with that. If I have 5 labels and I dump as `Segmentation Mask` 3 channels images are not right (for example each time puts the each class in not the same channel). And `MOTS` and `MOT` format returns empty zip files (some empty folders)... Datumaro returns errors too 'KeyError: 'cvat_rest_api_task_images''

**Comment by zhiltsov-max** [comment]
@MarioProjects, 

> 'KeyError: 'cvat_rest_api_task_images''

Please, follow instructions in README.md in the downloaded archive. This way, you will need to run 

```
pip install 'git+https://github.com/openvinotoolkit/datumaro'
datum project transform -t polygons_to_masks -o proj_masks # assuming annotations are polygons
datum project export -p proj_masks -f voc -- --apply-colormap=0 [--save-images]
```

Note that recent CVAT versions support color selection for labels, which affect colors in masks.
