### ISSUE TITLE
User Guide is broken

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#2391]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Can see a user guide inside the tool

### Current Behaviour
![Screenshot from 2020-11-03 16-28-18](https://user-images.githubusercontent.com/40690378/97990864-9ccdf800-1df1-11eb-9b4e-63fb7f394bde.png)

### Possible Solution
Probably related with code fixing by prettifier

### Steps to Reproduce (for bugs)

1. Open User Guide
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`): ef952888
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@azhavoro , the issue is quite critical. Could you please look at it with high priority?

**Comment by nmanovic** [comment]
@dvkruchinin , need to cover the case by tests.

**Comment by dvkruchinin** [comment]
> @dvkruchinin , need to cover the case by tests.

Sure. Will do.
