### ISSUE TITLE
A bug with deleting attributes

### ISSUE THREAD

**Issue by aschernov** [openvinotoolkit/cvat#2411]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The "delete the attribute" button must delete the corresponding attribute instead of the first one
### Current Behaviour

Noticed that if we try to delete an attribute while creating a task using the button "delete the attribute":
![image](https://user-images.githubusercontent.com/45849884/98796993-1337af00-241d-11eb-8166-50ae08338504.png)
it deletes the first attribute from the list instead of the selected one:
![image](https://user-images.githubusercontent.com/45849884/98797115-319daa80-241d-11eb-84a9-502bc3a9294f.png)

### Steps to Reproduce (for bugs)

1. Try to add some attributes while creating a new CVAT task
1. Then try to delete any attribute except the first one
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@dvkruchinin 

Hi,
We need test for this issue after it will be fixed.

**Comment by dvkruchinin** [comment]
> We need test for this issue after it will be fixed.

Hi. Sure. Will do.
