### ISSUE TITLE
Freezing with a large number of objects with the "text" attribute

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#2417]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Without freezing during operation if all objects are expanded.

### Current Behaviour

If the frame has there are a lot of expanded objects containing the "text" attribute, then when panning there are freezes.

### Possible Solution

It might be worth limiting the number of objects that can be expanded at the same time if the label has the "text" attribute (for example 50 objects can be expanded and the rest are collapsed automatically). 

### Steps to Reproduce (for bugs)

1. Create a task with a label containing the attribute "text"
1. Create an object and enter text in the input field (the more characters, the more freezing)
1. Create over 300 copies of this object
1. Expand all objects
1. Move the image

### Context

Here is the task in which I managed to reproduce it:
https://cvat.org/tasks/4796/jobs/6653

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@TOsmanov , could you please check that it is still an issue? If it isn't, please close the isuse.
