### ISSUE TITLE
Dataset download API call with FilePath

### ISSUE THREAD

**Issue by pushkal-ag** [openvinotoolkit/cvat#2420]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I'm using the following API call 
```
    def tasks_id_dataset(self, task_id, name, fileformat):
        return self.tasks_id(task_id) + '/dataset?format={}&filename={}' \
            .format(fileformat, name)
```

and saving the response like this
```
    def tasks_download_dataset(self, task_id, fileformat, filename, **kwargs):
        """ Download a dataset for a task in specified format"""
        url = self.api.tasks_id(task_id)
        response = self.session.get(url)
        response.raise_for_status()
        response_json = response.json()

        url = self.api.tasks_id_dataset(task_id,
                                        response_json['name'],
                                        fileformat)
        while True:
            response = self.session.get(url)
            response.raise_for_status()
            log.info('STATUS {}'.format(response.status_code))
            if response.status_code == 201:
                break

        response = self.session.get(url + '&action=download')
        response.raise_for_status()

        with open(filename, 'wb') as fp:
            fp.write(response.content)
```

But the dataset file is not downloaded.

### Expected Behaviour
Ideally dataset with filename should be downloaded.

### Current Behaviour
File is not being downloaded.

### Steps to Reproduce (for bugs)

1. Setup a RestAPI client as https://github.com/openvinotoolkit/cvat/blob/develop/utils/cli/tests/test_cli.py
2. Add the above API call to download dataset

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@pushkal-ag , the API was changed. I will close the issue as outdated. Don't hesitate to re-create if you still need the functionality.
