### ISSUE TITLE
Readonly label editor

### ISSUE THREAD

**Issue by ActiveChooN** [openvinotoolkit/cvat#2422]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

In project sometimes readonly small label editor is needed. For example project page. It also can be helpful when we migrate for separate task/project editing page.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

_Originally posted by @bsekachev in https://github.com/openvinotoolkit/cvat/pull/2255#issuecomment-724585094_

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@ActiveChooN , not enough details. I will close the issue.
