### ISSUE TITLE
How to by pass 2 cvat_host in cvat_proxy in docker-compose.override.yml

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [openvinotoolkit/cvat#2428]
@nmanovic Thank you for your great work. I have a question.

I want to pass 2 cvat_host like below:

1. For my LAN network -> so I set  CVAT_HOST: 192.168.1.125
2. My 2nd host to the world -> I set 1 more CVAT_HOST: my-2ndhost-server.xxx.zzz

But problems when I set like this then only the last CVAT_HOST is working.
How do I make 2 CVAT_HOST work at the same time?

This is my docker-compose.override.yml
version: "2.3"
services:
  cvat_proxy:
    environment:
      ALLOWED_HOSTS: "*"
      CVAT_HOST: 192.168.1.125
      CVAT_HOST: my-2ndhost-server.xxx.zzz

Thank you so much.

**Comment by azhavoro** [comment]
Hi, try to use:
```
CVAT_HOST: my-2ndhost-server.xxx.zzz 192.168.1.125
```
http://nginx.org/en/docs/http/server_names.html

**Comment by nguyenanhtuan1008** [comment]
> Hi, try to use:
> 
> ```
> CVAT_HOST: my-2ndhost-server.xxx.zzz 192.168.1.125
> ```
> 
> http://nginx.org/en/docs/http/server_names.html

Thank you so much! It works perfectly!

**Comment by malfonsoNeoris** [comment]
> 192.168.1.12

hi.. in which file did you place this env variable? in the docker-compose.yml

i have tried there.. in the server and ui (just in case) and it didnt work.

when i try to acces via localhost.. i have some errors poping up

_Could not check authorization on the server
Error: Request failed with status code 404. "404 page not found\n"._

any toughts? 
thanks

**Comment by azhavoro** [comment]
https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-specify-multiple-hostnames

**Comment by malfonsoNeoris** [comment]
thanks! i foundit 5 minutes ago!
