### ISSUE TITLE
How to install nuclt to deploy serverless on windows 10?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [openvinotoolkit/cvat#2429]
I installed CVAT on Windows 10.
I downloaded the nuctl-1.5.4-windows-amd64 but I don’t know how to install and use this file, I’m a windows10 system.
Can anyone tell me how to do?

Update: I rename nuctl-1.5.4-windows-amd64 to nuctl and then put it into cvat/serverless then run:
nuctl create project cvat  --> 'nuctl' is not recognized as an internal or external command.

**Comment by s3298230** [comment]
You ca refer to my steps mentioned in this nuclio thread [](https://github.com/nuclio/nuclio/issues/1821)

**Comment by nguyenanhtuan1008** [comment]
> You can refer to my steps mentioned in this nuclio thread for nuctl deployment.
> [nuclio/nuclio#1821](https://github.com/nuclio/nuclio/issues/1821)

Thanks. I will read and try it!

**Comment by azhavoro** [comment]
@nguyenanhtuan1008 Hi, did you solve the issue?

**Comment by nguyenanhtuan1008** [comment]
> @nguyenanhtuan1008 Hi, did you solve the issue?

not yet!

**Comment by bsekachev** [comment]
No updates here, so, I will close the issue. Do not hesitate to reopen it if is still relevant.

**Comment by bswapnil119** [comment]
Please refer my video. It will help.

https://youtu.be/uKMKM5o5vUw
