### ISSUE TITLE
Could Not Create Task

### ISSUE THREAD

**Issue by zaimpower** [openvinotoolkit/cvat#2430]
Hi, I'm new here I'm trying to upload almost 2GB of Images. But while im uploading some error occur. I hope that someone could resolve this issue for me :(

![WhatsApp Image 2020-11-15 at 5 03 54 PM](https://user-images.githubusercontent.com/74284879/99183970-bf112f80-277a-11eb-902c-d44fb0622908.jpeg)

**Comment by prashantcdac** [comment]
pls you log in again then see

**Comment by azhavoro** [comment]
@zaimpower, Answered you in Gitter

The size of uploaded data with the web UI is limited by 500MB, please use share to create a task in this case. https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path

or try to increase these values https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path and https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L65
