### ISSUE TITLE
I typed docker-compose down and all of the data is lost!

### ISSUE THREAD

**Issue by arasharchor** [openvinotoolkit/cvat#2451]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I downed the server temporarily to free up some ram for a job and then typed docker-compose up -d,to continue the annotations.

### Current Behaviour
after docker-compose up -d, all of the annotations and data is gone! all of the three months of work is gone in a second :(

**Comment by bsekachev** [comment]
Your data and annotations are stored in docker volumes, they cannot just disappear if you don't delete them.
Try to enter: ``docker volume list``, output should include ``cvat_cvat_data``, ``cvat_cvat_db``, and others.

**Comment by smajida** [comment]
@bsekachev 

Thanks a lot! You saved my not only day, but days.

Is there any documentation to restore all jobs with their data and annotations as well as users?

**Comment by bsekachev** [comment]
First need to understand if these volumes actually contain all the data (the problem is that ``up`` creates volumes if they do not exist) and since you do not see any data these volumes could be empty or in some reasons CVAT don't see the data

Try maybe use ``docker inspect cvat`` to see where in your host OS the data are stored, go there and see what data there are

**Comment by bsekachev** [comment]
Found some similar issues on the internet:
https://forums.docker.com/t/docker-volume-missing-after-docker-compose-down-without-v-flag/62203

https://forums.docker.com/t/why-docker-compose-down-deletes-my-volume-how-to-define-volume-as-external/67433

From our practice I can say, that after more then 3 years regularly done ``docker compose down``, we never met the issue

**Comment by arasharchor** [comment]
@bsekachev 

Thanks for the link. Unfortunately, volumes of data and db are empty for another clone of cvat in my machine which I had cloned from a newer version. However, the volumes of a clone of older version was still there and I could retrieve at least some of the annotations.

That is really scary that by stopping the docker all of the volumes get empty. :(
