### ISSUE TITLE
Support longer label naming

### ISSUE THREAD

**Issue by victor-ab** [openvinotoolkit/cvat#2461]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I have 60+ labels (very detailed) and I want to see the whole label name. 

### Current Behaviour
The current box is small, won't show entirely most of the label name.
![image](https://user-images.githubusercontent.com/26576394/99606532-b2920e80-29e8-11eb-8dde-7a2206b546d1.png)

### Possible Solution
Not sure, but I think we could Increase this [width](https://github.com/openvinotoolkit/cvat/blob/d20cbf610c947c2380baf4641ebf8f2daa06717f/cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-basics-edtior.tsx#L19) to 100% (don't think that's a huge design change) or make it customizable. 

### Steps to Reproduce (for bugs)

1. Any label with a long string name.

### Context
I can't quickly choose the right label.

**Comment by bsekachev** [comment]
I would suggest to add tooltip with the full label name. Even 100% percent width doesn't guarantee that there will be enough space to show the label.

**Comment by victor-ab** [comment]
100% was enough for me in my local testing. But yeah, the tooltip would help.

**Comment by victor-ab** [comment]
I tried to change the this [width ](https://github.com/openvinotoolkit/cvat/blob/d20cbf610c947c2380baf4641ebf8f2daa06717f/cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-basics-edtior.tsx#L19)to 100% but it doesn't have any effect when I rebuild the docker. Any ideas why?

**Comment by bsekachev** [comment]
You need not only rebuild the image, but also restart the container:
Something like ``docker-compose up --build``
