### ISSUE TITLE
How to create 2 languages for website interface.

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [openvinotoolkit/cvat#2470]
So sorry, I'm a beginner in web development. I just want to change the interface for this website. I have a few questions like bellow:

1. I would like to use 2 languages for the interface of this website. Example: English and German. However, I don't know-how.
I have accessed cvat/cvat-ui folder, I can't find any language javascript file.
Can anyone tell me how to do it?

2. If I use plugin translate like Qtranslate in Word Press, then how can I use this?

Thank you so much!

**Comment by bsekachev** [comment]
Hi, @nguyenanhtuan1008 

1. We do not support multi-language interface at all. There is a corresponding issue #374, but it is out of our current scope of tasks. 
2. I am not sure it is right place to ask about WordPress, probably need to find a better place.
