### ISSUE TITLE
Export as dataset COCO1.0 not save tag

### ISSUE THREAD

**Issue by dingChangmao** [openvinotoolkit/cvat#2472]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.I found that after exporting the annotation results, the coco format does not store the tag tags。
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
COCO does not support tags, https://cocodataset.org/#format-data 
In [Datumaro](https://github.com/openvinotoolkit/datumaro) we have an own extension for labels in COCO, if you want to use it do:
```bash
# export the task in Datumaro format, unpack and launch from the resulting directory:
datum project export -f coco (or coco_labels) [-- --save-images]
```

**Comment by dingChangmao** [comment]
Dear Maxim Zhiltsov：
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;I am very glad to receive your reply. I will do the relevant operations on the coco format as you said. Thank you again for your notification.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openvinotoolkit/cvat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 晚上10:57
收件人:&nbsp;"openvinotoolkit/cvat"<cvat@noreply.github.com&gt;;
抄送:&nbsp;"丁昌茂"<1255535360@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [openvinotoolkit/cvat] Export as dataset COCO1.0 not save tag (#2472)





 
COCO does not support tags, https://cocodataset.org/#format-data
 In Datumaro we have an own extension for labels in COCO, if you want to use it do:
 # export the task in Datumaro format, unpack and launch from the resulting directory: datum project export -f coco (or coco_labels) [-- --save-images]
