### ISSUE TITLE
CVAT WINDOWS7

### ISSUE THREAD

**Issue by kai102910202** [openvinotoolkit/cvat#2476]
Does CVAT support Windows7? Do I need WLS2 installed?

**Comment by ActiveChooN** [comment]
Hello, Windows 7 does not support WSL. You need Windows 10 version 1903 or higher.

**Comment by kai102910202** [comment]
> Hello, Windows 7 does not support WSL. You need Windows 10 version 1903 or higher.

thank you for reply!
I mean that my operating system is Windows7, so can't I use CVAT?

**Comment by bsekachev** [comment]
@kai102910202 
Docker doesn't support Windows 7. 
You can try installation under virtual machine with Linux OS.
