### ISSUE TITLE
http://localhost:8080/documentation/user_guide.html Not showing after "docker-compose down" and "docker-compose up" again.

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [openvinotoolkit/cvat#2480]
I am having some problems that http://localhost:8080/documentation/user_guide.html is not showing up.

I install CVAT on 2 PC, and both PC give the same error as above. On the first PC that installed CVAT, I thought I did something wrong, but today I install it again on the 2nd PC, I still get an error that does not display the content http://localhost:8080/documentation/user_guide.html.

I'm following https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#windows-10 to install CVAT:

- It only works after the first time "docker-compose up -d". 
![image](https://user-images.githubusercontent.com/36155295/100053096-abdd1e80-2e62-11eb-9092-a4326b0201f5.png)

But if I use "docker-compose down" then use "docker-compose up -d" the next time then got the error that does not display user_guide.html as bellow. From now user_guide will be not showing any contents if I "down" and "up" docker-compose again and again....
![image](https://user-images.githubusercontent.com/36155295/100052790-fdd17480-2e61-11eb-83ca-25117250d47c.png)

- If I delete all docker containers and all volumes then restart containers again by following commands then it showing up the user_guide with contents.
    docker-compose down
    docker rm -f $(docker ps -a -q)
    docker volume rm $(docker volume ls -q)
    docker-compose up -d

But if I do like this then all of my datasets with my annotation will be deleted. And that means user_guide.html working only first build up the docker-compose.
And if I do "docker-compose down" and "docker-compose up -d" again then getting the same error user_guide didn't show any contents.

Anyone can tell me the reason and how I can fix this issue to access http://localhost:8080/documentation/user_guide.html?

Thank you so much

**Comment by DouglasLivingstone** [comment]
I'm also seeing this issue, in the Chrome console there is a 404 error for:

```
https://cvat.example.com/static/CACHE/js/thirdparty.3960605f84fa.js
```

It looks like that should be generated in [base_page.html](https://github.com/openvinotoolkit/cvat/blob/e786f198c5e7724851839b3babe6a610deebcea1/cvat/apps/documentation/templates/documentation/base_page.html) by this block:

```
<!DOCTYPE html>
{% load static compress %}

<head>
    <title>{% block title %} {% endblock %}</title>
    {% compress js file thirdparty %}
    <script type="text/javascript" src="{% static 'documentation/js/3rdparty/showdown.js' %}"></script>
    <script type="text/javascript" src="{% static 'documentation/js/3rdparty/showdown-toc.js' %}"></script>
    {% endcompress %}
</head>
```

Is this an issue with caching the template after first build, but not the compressed JS output?

When that script fails to load, the Markdown isn't rendered so the user guide page stays blank.

**Comment by nmanovic** [comment]
@DouglasLivingstone , @nguyenanhtuan1008 , we have moved documentation here: https://openvinotoolkit.github.io/cvat/

I will close the issue.
