### ISSUE TITLE
404 error on google cloud vm

### ISSUE THREAD

**Issue by juanmanuelrq** [openvinotoolkit/cvat#2499]
I have created a google cloud vm
https://console.cloud.google.com/compute/instances

![image](https://user-images.githubusercontent.com/29231800/100481638-b3026780-30c2-11eb-9693-bf3e83ca74d1.png)

When I run http://ip:8080

I have:

404 Not Found
nginx/1.18.0
![image](https://user-images.githubusercontent.com/29231800/100481717-02e12e80-30c3-11eb-9e01-366c3ad7983a.png)

docker version
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

docker ps
```
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                  NAMES
3598d7a0f6ae        nginx:stable-alpine   "/docker-entrypoint.…"   2 hours ago         Up 2 hours          0.0.0.0:8080->80/tcp   cvat_proxy
13c5f45dbefb        cvat/ui               "/docker-entrypoint.…"   2 hours ago         Up 2 hours          80/tcp                 cvat_ui
9771037b0c5d        cvat/server           "/usr/bin/supervisord"   2 hours ago         Up 2 hours          8080/tcp, 8443/tcp     cvat
10578f86432d        postgres:10-alpine    "docker-entrypoint.s…"   2 hours ago         Up 2 hours          5432/tcp               cvat_db
3dd91b0b6906        redis:4.0-alpine      "docker-entrypoint.s…"   2 hours ago         Up 2 hours          6379/tcp               cvat_redis

```

docker logs cvat

```

2020-11-27 18:09:21,892 INFO RPC interface 'supervisor' initialized
2020-11-27 18:09:21,892 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-11-27 18:09:21,893 INFO supervisord started with pid 1
2020-11-27 18:09:22,895 INFO spawned: 'ssh-agent' with pid 7
2020-11-27 18:09:22,898 INFO spawned: 'clamav_update' with pid 8
2020-11-27 18:09:22,901 INFO spawned: 'git_status_updater' with pid 9
2020-11-27 18:09:22,905 INFO spawned: 'rqscheduler' with pid 10
2020-11-27 18:09:22,908 INFO spawned: 'rqworker_default_0' with pid 12
2020-11-27 18:09:22,911 INFO spawned: 'rqworker_default_1' with pid 13
2020-11-27 18:09:22,921 INFO spawned: 'rqworker_low' with pid 15
2020-11-27 18:09:22,925 INFO spawned: 'runserver' with pid 17
2020-11-27 18:09:22,926 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140368191584288 for <Subprocess at 140
368191583616 with name clamav_update in state STARTING> (stdout)>
2020-11-27 18:09:22,926 DEBG fd 14 closed, stopped monitoring <POutputDispatcher at 140368191320320 for <Subprocess at 140
368191583616 with name clamav_update in state STARTING> (stderr)>
2020-11-27 18:09:22,926 INFO exited: clamav_update (exit status 0; not expected)
2020-11-27 18:09:22,927 DEBG received SIGCHLD indicating a child quit
2020-11-27 18:09:22,928 DEBG 'ssh-agent' stdout output:
SSH_AUTH_SOCK=/tmp/ssh-agent.sock; export SSH_AUTH_SOCK;
echo Agent pid 7;
2020-11-27 18:09:22,928 DEBG 'ssh-agent' stderr output:
debug2: fd 3 setting O_NONBLOCK
2020-11-27 18:09:22,940 DEBG 'rqworker_default_0' stderr output:
wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
2020-11-27 18:09:22,946 DEBG 'rqscheduler' stderr output:
wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
2020-11-27 18:09:22,946 DEBG 'rqworker_default_1' stderr output:
wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
2020-11-27 18:09:22,947 DEBG 'git_status_updater' stderr output:
wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
2020-11-27 18:09:22,955 DEBG 'rqworker_default_0' stderr output:
wait-for-it.sh: cvat_redis:6379 is available after 0 seconds
2020-11-27 18:09:22,955 DEBG 'rqworker_low' stderr output:
wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
2020-11-27 18:09:22,956 DEBG 'rqworker_default_0' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2020-11-27 18:09:22,959 DEBG 'rqworker_default_1' stderr output:
wait-for-it.sh: cvat_redis:6379 is available after 0 seconds
2020-11-27 18:09:22,960 DEBG 'runserver' stderr output:
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
2020-11-27 18:09:22,961 DEBG 'rqworker_default_1' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

```

docker-compose up -d
```
WARNING: The no_proxy variable is not set. Defaulting to a blank string.
cvat_db is up-to-date
cvat_redis is up-to-date
cvat is up-to-date
cvat_ui is up-to-date
cvat_proxy is up-to-date
```

docker info
```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 66
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1029-gcp
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.64GiB
 Name: docker-ubuntu-1-vm
 ID: NRA6:FRJ5:4MZ6:KZYN:4HU2:3DCG:KWMY:RVEY:YRTD:X4LW:A2ZB:NEPL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

sudo docker-compose up
`cvat          | Server Backlog     : 500 (connections)
cvat          | Locale Setting     : C.UTF-8
cvat          | 
cvat          | 2020-11-27 21:37:29,277 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 27 21:37:29.276790 2020] [mpm_event:notice] [pid 18:tid 140594528226368] AH00489: Apache/2.4.41 (Ubuntu) mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations
cvat          | [Fri Nov 27 21:37:29.276912 2020] [mpm_event:info] [pid 18:tid 140594528226368] AH00490: Server built: 2020-08-12T19:46:17
cvat          | [Fri Nov 27 21:37:29.276924 2020] [core:notice] [pid 18:tid 140594528226368] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/cvat-server/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'
cvat          | [Fri Nov 27 21:37:29.276739 2020] [wsgi:info] [pid 201:tid 140594528226368] mod_wsgi (pid=201): Starting process 'localhost:8080' with threads=5.
cvat          | 
cvat          | 2020-11-27 21:37:29,277 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 27 21:37:29.277605 2020] [wsgi:info] [pid 201:tid 140594528226368] mod_wsgi (pid=201): Python home /usr.
cvat          | 
cvat          | 2020-11-27 21:37:29,278 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 27 21:37:29.277744 2020] [wsgi:info] [pid 201:tid 140594528226368] mod_wsgi (pid=201): Initializing Python.
cvat          | 
cvat          | 2020-11-27 21:37:29,302 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 27 21:37:29.302238 2020] [wsgi:info] [pid 201:tid 140594528226368] mod_wsgi (pid=201): Attach interpreter ''.
cvat          | 
cvat          | 2020-11-27 21:37:29,308 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 27 21:37:29.307935 2020] [wsgi:info] [pid 201:tid 140594528226368] mod_wsgi (pid=201): Imported 'mod_wsgi'.
cvat          | [Fri Nov 27 21:37:29.308038 2020] [wsgi:info] [pid 201:tid 140594528226368] mod_wsgi (pid=201, process='localhost:8080', application=''): Loading Python script file '/tmp/cvat-server/handler.wsgi'.
cvat          | 
cvat          | 2020-11-27 21:37:29,587 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          | 
cvat          | 2020-11-27 21:37:29,589 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          | 
cvat          | 2020-11-27 21:37:29,591 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:ysQh0PnzvkMww3Rk6vN+oPr0/WXHyUYx0UnmcVlvcYc "django@9771037b0c5d" (life: 0) (confirm: 0) (provider: none)
cvat          | 
cvat          | 2020-11-27 21:37:29,598 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          | 
cvat          | 2020-11-27 21:44:06,398 DEBG 'rqworker_default_1' stderr output:
cvat          | DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          | 
cvat          | 2020-11-27 21:44:06,699 DEBG 'rqworker_low' stderr output:
cvat          | DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          | 
cvat          | 2020-11-27 21:44:06,700 DEBG 'rqworker_default_0' stderr output:
cvat          | DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          | 
cvat_proxy    | 190.248.180.100 - - [27/Nov/2020:21:50:01 +0000] "GET / HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
cvat          | 2020-11-27 21:50:51,463 DEBG 'rqworker_default_1' stderr output:
cvat          | DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          | 
cvat          | 2020-11-27 21:50:51,763 DEBG 'rqworker_low' stderr output:
cvat          | DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          | 
cvat          | 2020-11-27 21:50:51,763 DEBG 'rqworker_default_0' stderr output:
cvat          | DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.`

**Comment by azhavoro** [comment]
@juanmanuelrq 
Please specify CVAT_HOST environment variable as described in the installation guide https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#advanced-settings

**Comment by azhavoro** [comment]
@juanmanuelrq did you solve the issue?

**Comment by azhavoro** [comment]
No response for a long time.

**Comment by Yasin-Ali-Cpuflat** [comment]
how you fix it
