### ISSUE TITLE
YOLO Annotation

### ISSUE THREAD

**Issue by peyman-sabouri** [openvinotoolkit/cvat#2511]
If I dump annotation in yolo format and upload them again, the bounding boxes won't be matched again. 
There was not this issue before updating my local repo!

**Comment by nmanovic** [comment]
@yasakova-anastasia , could you please reproduce the issue and fix?

**Comment by nmanovic** [comment]
@peyman-sabouri , which version of CVAT do you use? Please don't ignore our template. We created it because sometimes it is difficult to reproduce an issue and fix without the information.

**Comment by peyman-sabouri** [comment]
Server version: 1.2b0

Core version: 3.9.1

Canvas version: 2.1.3

UI version: 1.10.9

**Comment by yasakova-anastasia** [comment]
Hi, @peyman-sabouri
I have not been able to reproduce the issue on the develop branch. I received only small deviations in the fourth digit after the decimal point, which is rather the norm. Could you share the commit hash, annotation file and image please?

**Comment by azhavoro** [comment]
@yasakova-anastasia There may be the similar issue: #2569

**Comment by azhavoro** [comment]
No response a long time, I'll close the issue.
@peyman-sabouri feel free to reopen if the issue is still actual for you.
