### ISSUE TITLE
Could not dump annotations for the task 28414: Error: Request failed with status code 500. "AssertionError: Image info differs for item 'salmon2'\n".

### ISSUE THREAD

**Issue by ZurMaD** [openvinotoolkit/cvat#2520]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Dump to PASCAL VOC 1.1
Delete some irrelevant images from dataset uploaded.
Edit some labels don't used.

### Current Behaviour

I have the following task where I need to label fish on 500 images. In the process I find some images that are irrelevant: don't have any label in some images. https://cvat.org/tasks/28414

![image](https://user-images.githubusercontent.com/28235457/100908078-114f9180-3499-11eb-932d-3299fd699894.png)

### Possible Solution

I don't have idea, I'm newbie using CVAT.

### Steps to Reproduce (for bugs)

1. Downloand the dataset ziped in https://drive.google.com/file/d/1ygzmCmQRIApEcI4tX3w3HeSaMSOOi1Gz/view?usp=sharing
2. Extract only the "salmon" folder and upload to CVAT.
3. Label salmons in some images and try to export. It will fails.

### Context

Label some fish on images

### Your Environment

Directly in https://cvat.org/

**Comment by zhiltsov-max** [comment]
It seems like the dataset contains different images with the same filename (except of extension). Such a task can only be dumped in `CVAT for *` formats.

**Comment by ZurMaD** [comment]
@zhiltsov-max yes, looks like PASCAL doesn't work with that. I will check the requirements before starting labeling to a format. Thanks for answering, I will close the comment.
