### ISSUE TITLE
Kubernetes uses Nuctl to deploy function issues

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [openvinotoolkit/cvat#2522]
Executed command：
nuctl deploy --project-name cvat \
    --path serverless/openvino/dextr/nuclio \
	--namespace nuclio \
	--volume /opt/nuclio:/opt/nuclio \
	--volume `pwd`/serverless/openvino/common:/opt/nuclio/common \
	--kubeconfig /etc/kubernetes/admin.conf \
	--platform kube

Generated problems：

20.12.03 03:07:49.118 cessor.healthcheck.server (I) Listening {"listenAddress": ":8082"}
20.12.03 03:07:49.118            processor.http (D) Creating worker pool {"num": 2}
20.12.03 03:07:49.118 sor.http.w1.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-bv45d194b7irpkaapatg.sock"}
20.12.03 03:07:49.118 sor.http.w1.python.logger (D) Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
20.12.03 03:07:49.118 sor.http.w1.python.logger (D) Using Python handler {"handler": "main:handler"}
20.12.03 03:07:49.118 sor.http.w1.python.logger (E) Can't find Python exe {"error": "exec: "/opt/nuclio/common": stat /opt/nuclio/common: no such file or directory"}
20.12.03 03:07:49.118 sor.http.w0.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-bv45d194b7irpkaapau0.sock"}
20.12.03 03:07:49.119 sor.http.w0.python.logger (D) Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
20.12.03 03:07:49.119 sor.http.w0.python.logger (D) Using Python handler {"handler": "main:handler"}
20.12.03 03:07:49.119 sor.http.w0.python.logger (E) Can't find Python exe {"error": "exec: "/opt/nuclio/common": stat /opt/nuclio/common: no such file or directory"}

Error - exec: "/opt/nuclio/common": stat /opt/nuclio/common: no such file or directory
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:228

Call stack:
Can't run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:228
Failed to run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:104
Failed to start runtime
    /nuclio/pkg/processor/worker/factory.go:101
Failed to create worker
    /nuclio/pkg/processor/worker/factory.go:122
Failed to create workers
    /nuclio/pkg/processor/worker/factory.go:132

    /nuclio/pkg/platform/kube/deployer.go:177
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:175
You have new mail in /var/spool/mail/root

nuctl version 1.5.7
nuctl version 1.5.6
nuctl version 1.4.19

How can I solve it

**Comment by nmanovic** [comment]
We don't support kubernetes deployment for nuclio functions yet.

**Comment by turowicz** [comment]
@nmanovic any workarounds? I'm having a weird issue here: https://github.com/nuclio/nuclio/issues/2031

**Comment by turowicz** [comment]
not using volumes for the f-rcnn
