### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'id' of undefined.

### ISSUE THREAD

**Issue by dvkruchinin** [openvinotoolkit/cvat#2523]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
The user who created the task assigns it to the second user. The second user reassigns the task to the third user. Error does not occur.
When you enter username in the "Assigned to" field and press Tab, the task is reassigned.

### Current Behaviour
The second user assigns the task to the third user by entering their "username" in the "Assigned to" field and pressing Enter. An error occurs. The same error occurs when reassigning via the drop-down menu.
```
tasks-reducer.ts:325 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at tasks-reducer.ts:325
    at Array.map (<anonymous>)
    at KE (tasks-reducer.ts:323)
    at redux.js:459
    at b (redux.js:213)
    at redux-logger.js:1
    at index.js:11
    at dispatch (redux.js:638)
    at tasks-actions.ts:480
```
And infinite preloader.

When enter username in the "Assigned to" field and press Tab the field is cleared and the task becomes unassigned to anyone.

### Possible Solution
Fix the bug.

### Steps to Reproduce (for bugs)

1. Register an additional 2 users
2. Create a task and assign it to the second user.
3. Log in as the second. Enter the username of the third user in the "Assigned to" field and press "Enter" or via the drop-down menu. The error appears.
Or log in as the second user. Enter the username of the third user in the "Assigned to" field and press Tab. The field is cleared and the task becomes unassigned to anyone.

### Your Environment

- Git hash commit (`git log -1`): 5735efe72f4c5a50cd6a417cdc01ef88928e9a93
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.13
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10.
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@dvkruchinin Thanks a lot! 
@ActiveChooN Could you please look at the issue?
