### ISSUE TITLE
Some parts of the Redux state (issues) isn't reset after chaning a job 

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#2524]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Issues are reset after changing a job

### Current Behaviour
Issues are not reset after changing a job

### Possible Solution
Reset Redux storage

### Steps to Reproduce (for bugs)

1. Open a review job
1. Left an issue
1. Close the job, open another job
1. The issue is visible in another job

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@dvkruchinin Hi, could you please write a test for the issue?

**Comment by dvkruchinin** [comment]
> Hi, could you please write a test for the issue?

Hi, sure.
