### ISSUE TITLE
Dump annotation with Assignees info

### ISSUE THREAD

**Issue by thuyngch** [openvinotoolkit/cvat#2532]
When dumping annotation with node `CVAT for images 1.1`, an XML file is downloaded.
The content includes:
```xml
        <segment>
          <id>2046</id>
          <start>2600</start>
          <stop>2617</stop>
          <url>http://zealotnt.freeddns.org:8082/?id=2046</url>
        </segment>
```

However, the assignee of the segment is not specified.
For example:
```xml
        <segment>
          <id>2046</id>
          <start>2600</start>
          <stop>2617</stop>
          <url>http://zealotnt.freeddns.org:8082/?id=2046</url>
          <assignee>username</assignee>
        </segment>
```

Could you support this feature?
Many thanks!

**Comment by nmanovic** [comment]
@thuyngch , I think it is possible. Let me know if you can contribute the future. It should not very difficult.

**Comment by nmanovic** [comment]
@thuyngch , the feature was implemented. At least I can see on CVAT.org it works properly.

**Comment by thuyngch** [comment]
thank you very much
