### ISSUE TITLE
How to handle annotation change over time?

### ISSUE THREAD

**Issue by ZahraAnam** [openvinotoolkit/cvat#2533]
I am trying to use CVAT for annotating the videos of children playing in the playroom and video is around the room. Therefore sometime a person or object disappears for some frames and appears again, I was wondering how can I tackle this problem. Coz hidind and deleting are not the solutions.
Besides merge icon is also not working, I was wondering if you guys can guide me about it.

**Comment by azhavoro** [comment]
Please use the `Outside` property for the tracks https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/user_guide.md#track-mode-basics
