### ISSUE TITLE
toomanyrequests: You have reached your pull rate limit

### ISSUE THREAD

**Issue by MagicCodess** [openvinotoolkit/cvat#2542]
ERROR: Service 'cvat' failed to build : toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by azhavoro** [comment]
There are new Docker policies, unfortunately we cannot change them.

**Comment by azhavoro** [comment]
Let's keep the question open, it might be better to look for another docker registry.

**Comment by nmanovic** [comment]
@azhavoro , the problem is really critical even for us. Could you please propose a short-term and long-term solutions?

**Comment by nmanovic** [comment]
@azhavoro , is it fixed with github actions?

**Comment by nmanovic** [comment]
It looks like the issue was resolved. I will close the issue.
