### ISSUE TITLE
Wrong parametrization of the rqscheduler instance

### ISSUE THREAD

**Issue by jcchr** [openvinotoolkit/cvat#2543]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

In the 46th line of the https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf file there is a command that starts the rqscheduler - and as the --host parameter in this line there is a "redis" value hardcoded. The ENV_CVAT_REDIS_HOST env variable, where a user can change this name, is ignored. It makes installing redis instance with a different hostname impossible.

### Expected Behaviour
Name of the redis container should be always taken from the ENV_CVAT_REDIS_HOST env variable.

### Current Behaviour
As described in the description of this issue.

### Possible Solution
Replace hardcoded "redis" value with the ENV_CVAT_REDIS_HOST env variable.

### Context
When the pod with CVAT is started on kubernetes it takes some time to the k8s to start seeing the "redis" container - which extends the time needed to start the whole pod.

**Comment by azhavoro** [comment]
@jcchr Hi, thanks for the issue, may I ask you to help us fix this? Thanks.

**Comment by jcchr** [comment]
The correction is in the following fork: https://github.com/jcchr/cvat
