### ISSUE TITLE
Status code 500 Internal Server Error when uploading cvat 1.1 for images annotations (500MB of size)

### ISSUE THREAD

**Issue by kairikibear** [openvinotoolkit/cvat#2557]
### My actions before raising this issue
- [done] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [done] Searched [past issues](/issues)

Basically, i have a huge object detection dataset (nearly 200 GBs of size) which has been annotated beforehand using YOLOMARK, and i want to further annotate them with attributes. The idea is i want to reuse the annotated boxes and make every class have their own attributes for the annotaters to annotate.

My approach to do so is as follows :
1. Create a new task, with the classnames from my dataset.
2. Dump the empty annotations as CVAT for images format (why not yolo format is due to another separate issue #2473 )
3. Use a custom python script to parse all the <image> tag in the exported xml file, grab the relevant annotation file (from yolomark) and fill in the detections.
4. Write the xml file and upload.

Forgot to mention : uploading was done through cli.py

Before, this has happened and i succeed in uploading the annotations.

Then some things happened and i have to redeploy cvat in another environment.
Same exact version, similar system (i dont think it would cause any different but just for the sake of completeness), same tweaking (had to change the package lock and bump up rq timeout to 12 hours for my big dataset), basically same everything.

The only difference being : 
1. In the successful attempt, i added the label names manually from each entry in the .names file of yolomark.
1,5. Sometimes after the succesful attempt, my friend added the suitable attributes for each class.
2. In the unsuccessful attempt, i did not add the label names manually from the .names file, but rather took the json after 1,5 happened and use it for labels.

My investigation : 
- there are no much difference inspecting both versions of XML files (of 1 and 2) besides the presence of list of attributes aside of list of labels. 
- The logs does not say much about things, only that an internal error has happened. will attach if requested but that's pretty much everything it said. no lines causing error, no nothing!
- I experimented with another xml where i only write the first 500 labels because i had suspicions that it was caused by the sheer size of the annots file. And it worked! Weird thing is, why did it work with the previous one then? as i said, same version, same everything. 
- I started inspecting views.py and the subsequent relevant files and may or may not have the singular [line](https://github.com/openvinotoolkit/cvat/blob/v1.1.0/cvat/apps/engine/views.py#L775-L780) causing it. But still no luck on why it failed.
### Expected Behaviour

That it uploads normally or at the very least, tells me what's wrong so i can have another chance.
### Current Behaviour

I think everything is already mentioned above. Will add more info if requested

### Possible Solution

No idea since i dont know what is causing it

### Steps to Reproduce (for bugs)
As above. I doubt it would be beneficial if i give you the 200GB dataset plus the 500MB annotations since it will take extremely long and i cant really give you the dataset. Any huge annots file would suffice probably

### Context
I will go out on a limb and say this has already been expressed clearly above. feel free to inquire further

### Your Environment
- Git hash commit (`git log -1`): Release 1.1.0 
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.14
- Are you using Docker Swarm or Kubernetes? Docker compose
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18 04 lts
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Hi, please check if there are any messages like `child process exited with code -9` and Out-Of-Memory errors in the system log (`dmesg -HTw` on Linux).

**Comment by kairikibear** [comment]
> Hi, please check if there are any messages like `child process exited with code -9` and Out-Of-Memory errors in the system log (`dmesg -HTw` on Linux).

thanks for the response, i will look into it later and report back

**Comment by kairikibear** [comment]
Ah, there's actually one.. Is this a limitation forced by docker that i can circumvent by setting configurations, or do i have no choice but to add more ram to my system?

**Comment by zhiltsov-max** [comment]
Basically, there are few options here: 
- check container limits
- add (more) swap memory (can hurt application performance, but anyway)
- add physical ram

**Comment by kairikibear** [comment]
Thanks! adding swap is a bit slow but it does the trick without adding rams.
