### ISSUE TITLE
Couldn't Install nuclio on Ubuntu 18.04

### ISSUE THREAD

**Issue by BhargaviChintanippu** [openvinotoolkit/cvat#2567]
Hi,

OS : Ubuntu 18.04

I have recently started working on CVAT  to auto annotate my datasets for the custom model. 
Below are the steps I have followed for CVAT:
   1.I have followed all the steps for installing CVAT from [here](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#semi-automatic-and-automatic-annotation)

   2.Able to open CVAT Tool(localhost:8080) and  after creating a task while click "automatic annotation" under Action tab I am unable to deploy my custom model. So,  i am following the "Semi-automatic and automatic annotation" steps to deploy new serverless functions and deploy my custom model. But facing the issue while setting up the nuclio.

   3 . I have followed the following steps for nuclio Installation.

      a. Downloaded the nuctl-1.5.8-linux-amd64 package using the [link](https://github.com/nuclio/nuclio/releases)

      b. Navigated to the downloaded directory and executed the below command:
             chmod +x nuctl-1.5.8-linux-amd64

      c. Able to run the executable using the following command:
           ./nuctl-1.5.8-linux-amd64

      d. For Nuclio usage, executed the below command:
          nuctl --help
         But Facing "command: nuctl not found, did you mean" issue. Please find the attached issue screenshot.
<img width="203" alt="nuclioissue" src="https://user-images.githubusercontent.com/45841187/102047749-cf610c80-3e03-11eb-8055-b2a67abdbda1.PNG">

Could Anyone please help me in resolving the issue.

TIA,
Bhargavi

**Comment by veer5551** [comment]
Hi,
You need to execute the command as follows: `./ nuctl-1.5.8-linux-amd64 xxxxxx`
Or you can Rename your file to `nuctl` to use just the `./nuctl xxxxxx`

**Comment by azhavoro** [comment]
@veer5551 thanks for the answer, I think the issue can be closed.

**Comment by BhargaviChintanippu** [comment]
> Hi,
> You need to execute the command as follows: `./ nuctl-1.5.8-linux-amd64 xxxxxx`
> Or you can Rename your file to `nuctl` to use just the `./nuctl xxxxxx`

Thank you for the reply...It worked for me.

**Comment by BhargaviChintanippu** [comment]
> Hi,
> You need to execute the command as follows: `./ nuctl-1.5.8-linux-amd64 xxxxxx`
> Or you can Rename your file to `nuctl` to use just the `./nuctl xxxxI 

It worked..Thank you...
