### ISSUE TITLE
some bounding boxes coordinate in xml file (pascal voc format) are not correct

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/cvat#2569]
I noticed some bounding boxes are shifted after I saved the annotation.

Then, I use other annotation tool [https://github.com/tzutalin/labelImg](url) to load the annotation files export by cvat and it also shows some bounding boxes are shifted.

**Comment by zhiltsov-max** [comment]
Can you give more information about the annotations and differences, maybe some screenshots?

**Comment by tankienleong** [comment]
![a1](https://user-images.githubusercontent.com/25731934/102160965-6770fb80-3ec1-11eb-844d-4129aa7a8f0e.JPG)
![a2](https://user-images.githubusercontent.com/25731934/102160966-68a22880-3ec1-11eb-8e37-1c8c16570fcc.JPG)
![a3](https://user-images.githubusercontent.com/25731934/102160967-693abf00-3ec1-11eb-9ebf-11327c2f021a.JPG)
![a4](https://user-images.githubusercontent.com/25731934/102160968-69d35580-3ec1-11eb-91c8-c3449e96c17d.JPG)
![a5](https://user-images.githubusercontent.com/25731934/102160969-69d35580-3ec1-11eb-9958-16ffbef4d9d4.JPG)
![a6](https://user-images.githubusercontent.com/25731934/102160970-6a6bec00-3ec1-11eb-9287-7093069abbca.JPG)

The bounding box of white car and motorbike are shifted.

**Comment by zhiltsov-max** [comment]
Could you check if any other formats have this problem? `CVAT for images`, `COCO`.
Is it a video task? Are these annotations produced by interpolation, or they were drawn manually? Do annotations fall to the right frames on loading?

**Comment by azhavoro** [comment]
@tankienleong any updates? Is the issue still actual for you?

**Comment by azhavoro** [comment]
No response for a long time, let's close the issue, @tankienleong don't hesitate to reopen if this issue is still actual to you.
