### ISSUE TITLE
The cursor jumps to the end of the line when renaming a task.

### ISSUE THREAD

**Issue by dvkruchinin** [openvinotoolkit/cvat#2572]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
When renaming a task, the cursor does not jump to the end of the line.

### Current Behaviour
When renaming a task, if put the cursor anywhere other than the end of the line and start typing characters, the cursor jumps to the end of the line.

### Steps to Reproduce (for bugs)

1. Create an annotation task.
2. Click to "Edit" to edit the task name.
3. Put the cursor anywhere in the line except at the end and enter any character

### Your Environment

- Git hash commit (`git log -1`): 4edabdb3ed34b0902140493f78634770936047a9
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.13
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by ActiveChooN** [comment]
@dvkruchinin, it's AntD bug. Reported to their repo https://github.com/ant-design/ant-design/issues/28487.

**Comment by bsekachev** [comment]
Has been fixed two days ago. Probably need to update antd in CVAT.
