### ISSUE TITLE
How can I do something with a group of objects?

### ISSUE THREAD

**Issue by KoryakovDmitry** [openvinotoolkit/cvat#2575]
Hi,

How can I do something with a group of objects? For example, changing the labels of each object in a group at the same time, or copying and pasting a group of objects?

thanks.

**Comment by aschernov** [comment]
Hi Dmitry,
The "group" option in CVAT UI supports only visual grouping of objects. You can get the information that some objects were grouped and use it in your goals after downloading the annotation you made. See the details here: https://cvat-icv.inn.intel.com/documentation/user_guide.html#shape-grouping

**Comment by saad-abdullah62** [comment]
@aschernov  I am deploying custom trained model to CVAT, i tried to assign group id to rectangles predicted by models using key 'group_id' and 'group', but groups are not assigned. Can you kindly tell what should be correct key for grouping shapes?
