### ISSUE TITLE
The coordinates of some frames within a tracklet remain unchanged in the ''CVAT for video' format.'

### ISSUE THREAD

**Issue by qiguming** [openvinotoolkit/cvat#2586]
![2020-12-17 09-29-01屏幕截图](https://user-images.githubusercontent.com/31810368/102429754-99af6400-404d-11eb-897a-771afc6b8f9a.png)

The coordinates from frame 6915 to frame 6924 keeps changed actually but keep unchanged in the exported annotation file.

**Comment by azhavoro** [comment]
@qiguming Please don't ignore the issue template and specify which version of CVAT you are using. Could you provide steps to reproduce this issue?

**Comment by azhavoro** [comment]
The same issue report #2604
