### ISSUE TITLE
Deployment model problem

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [openvinotoolkit/cvat#2587]
Model deployment statement：

nuctl deploy --project-name cvat \
    --path $SCRIPT_DIR/tensorflow/faster_rcnn_inception_v2_coco/nuclio \
    --platform local

The configuration file is as follows：
functions.yaml

metadata:
  name: tf-faster-rcnn-inception-v2-coco
  namespace: cvat
  annotations:
    name: Faster RCNN via Tensorflow
    type: detector
    framework: tensorflow
    spec: |
      [
        { "id": 1, "name": "person" },
        { "id": 2, "name": "bicycle" },
        { "id": 3, "name": "car" },
        { "id": 4, "name": "motorcycle" },
        { "id": 5, "name": "airplane" },
        { "id": 6, "name": "bus" },
        { "id": 7, "name": "train" },
        { "id": 8, "name": "truck" },
        { "id": 9, "name": "boat" },
        { "id":10, "name": "traffic_light" },
        { "id":11, "name": "fire_hydrant" },
        { "id":13, "name": "stop_sign" },
        { "id":14, "name": "parking_meter" },
        { "id":15, "name": "bench" },
        { "id":16, "name": "bird" },
        { "id":17, "name": "cat" },
        { "id":18, "name": "dog" },
        { "id":19, "name": "horse" },
        { "id":20, "name": "sheep" },
        { "id":21, "name": "cow" },
        { "id":22, "name": "elephant" },
        { "id":23, "name": "bear" },
        { "id":24, "name": "zebra" },
        { "id":25, "name": "giraffe" },
        { "id":27, "name": "backpack" },
        { "id":28, "name": "umbrella" },
        { "id":31, "name": "handbag" },
        { "id":32, "name": "tie" },
        { "id":33, "name": "suitcase" },
        { "id":34, "name": "frisbee" },
        { "id":35, "name": "skis" },
        { "id":36, "name": "snowboard" },
        { "id":37, "name": "sports_ball" },
        { "id":38, "name": "kite" },
        { "id":39, "name": "baseball_bat" },
        { "id":40, "name": "baseball_glove" },
        { "id":41, "name": "skateboard" },
        { "id":42, "name": "surfboard" },
        { "id":43, "name": "tennis_racket" },
        { "id":44, "name": "bottle" },
        { "id":46, "name": "wine_glass" },
        { "id":47, "name": "cup" },
        { "id":48, "name": "fork" },
        { "id":49, "name": "knife" },
        { "id":50, "name": "spoon" },
        { "id":51, "name": "bowl" },
        { "id":52, "name": "banana" },
        { "id":53, "name": "apple" },
        { "id":54, "name": "sandwich" },
        { "id":55, "name": "orange" },
        { "id":56, "name": "broccoli" },
        { "id":57, "name": "carrot" },
        { "id":58, "name": "hot_dog" },
        { "id":59, "name": "pizza" },
        { "id":60, "name": "donut" },
        { "id":61, "name": "cake" },
        { "id":62, "name": "chair" },
        { "id":63, "name": "couch" },
        { "id":64, "name": "potted_plant" },
        { "id":65, "name": "bed" },
        { "id":67, "name": "dining_table" },
        { "id":70, "name": "toilet" },
        { "id":72, "name": "tv" },
        { "id":73, "name": "laptop" },
        { "id":74, "name": "mouse" },
        { "id":75, "name": "remote" },
        { "id":76, "name": "keyboard" },
        { "id":77, "name": "cell_phone" },
        { "id":78, "name": "microwave" },
        { "id":79, "name": "oven" },
        { "id":80, "name": "toaster" },
        { "id":81, "name": "sink" },
        { "id":83, "name": "refrigerator" },
        { "id":84, "name": "book" },
        { "id":85, "name": "clock" },
        { "id":86, "name": "vase" },
        { "id":87, "name": "scissors" },
        { "id":88, "name": "teddy_bear" },
        { "id":89, "name": "hair_drier" },
        { "id":90, "name": "toothbrush" }
      ]

spec:
  description: Faster RCNN from Tensorflow Object Detection API
  runtime: "python:3.6"
  handler: main:handler
  eventTimeout: 30s
  image: 47.104.169.133:8888/cvat/tf.faster_rcnn_inception_v2_coco:latest
  imagePullPolicy: Never
  serviceType: NodePort
  minReplicas: 1
  maxReplicas: 3
  triggers:
    myHttpTrigger:
      maxWorkers: 2
      kind: "http"
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3

Partial logs after execution：

[root@master serverless]# nuctl deploy --project-name cvat --path $SCRIPT_DIR/tensorflow/faster_rcnn_inception_v2_coco/nuclio --namespace nuclio --kubeconfig /etc/kubernetes/admin.conf --platform kube
20.12.18 10:17:38.202                     nuctl (I) Deploying function {"name": ""}
20.12.18 10:17:38.203                     nuctl (I) Building {"versionInfo": "Label: 1.5.8, Git commit: c12022750a6003a309d4f20c72a98addacd3e95d, OS: linux, Arch: amd64, Go version: go1.14.3", "name": ""}
20.12.18 10:17:38.284                     nuctl (I) Staging files and preparing base images
20.12.18 10:17:38.284                     nuctl (I) Building processor image {"imageName": "nuclio/processor-tf-faster-rcnn-inception-v2-coco:latest"}
20.12.18 10:17:38.284     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.5.8-amd64"}

Spec. image I have specified my own custom image, why not use a custom image instead of nuclio/ processor-TF-faster - rCNN-inception -v2-coco:latest

After I execute the following command, image uses custom：

nuctl deploy --project-name cvat \
    --path $SCRIPT_DIR/tensorflow/faster_rcnn_inception_v2_coco/nuclio \
    --image 47.104.169.133:8888/cvat/tf.faster_rcnn_inception_v2_coco:latest
    --platform local

Partial logs after execution：
[root@master serverless]# nuctl deploy --project-name cvat --path $SCRIPT_DIR/tensorflow/faster_rcnn_inception_v2_coco/nuclio --namespace nuclio --kubeconfig /etc/kubernetes/admin.conf --platform kube
20.12.18 10:17:38.202                     nuctl (I) Deploying function {"name": ""}
20.12.18 10:17:38.203                     nuctl (I) Building {"versionInfo": "Label: 1.5.8, Git commit: c12022750a6003a309d4f20c72a98addacd3e95d, OS: linux, Arch: amd64, Go version: go1.14.3", "name": ""}
20.12.18 10:17:38.284                     nuctl (I) Staging files and preparing base images
20.12.18 10:17:38.284                     nuctl (I) Building processor image {"imageName": "47.104.169.133:8888/cvat/tf.faster_rcnn_inception_v2_coco:latest"}
20.12.18 10:17:38.284     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.5.8-amd64"}

Is there any difference between using image in functions.YAMl definition and using image in nuctl execution command

**Comment by azhavoro** [comment]
@ITBOX-ITBOY Please ask this question nuclio developers
