### ISSUE TITLE
Account creation on cvat.org not possible.

### ISSUE THREAD

**Issue by nise** [openvinotoolkit/cvat#2590]
Maybe offtopic, but with newly created credentials I am not able to login after I have clicked the link in the confirmation mail. 
Since I did not find any other 'about'-page I had to write an issue. Sorry for that.

`Could not login on the server
Error: Request failed with status code 400. {"non_field_errors":["Unable to log in with provided credentials."]}.`

**Comment by azhavoro** [comment]
@nise Hi, what username did you use?

**Comment by azhavoro** [comment]
I see that your email has been verified, so you are most likely using the wrong password, try resetting it: https://cvat.org/auth/password/reset

**Comment by nise** [comment]
That's unlikely when using a password manager. 

I reseted the password, but the problem remains the same. Are 15 chars to many for a password? Shall I use Chromium instead of firefox?

**Comment by azhavoro** [comment]
Make sure that you use username (not email). In my case Firefox stored email instead username.

**Comment by nise** [comment]
Thanks, it was the email instead of the username. Me and the browser were not used to it...
