### ISSUE TITLE
Add migration guide

### ISSUE THREAD

**Issue by cstamatopoulos** [openvinotoolkit/cvat#2591]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behavior
There is no migration guide and no information how to migrate CVAT data in installation/FAQ guide.

### Possible Solution
Update FAQ.

### Steps to Reproduce (for bugs)
N/A

### Context
N/A

### Your Environment
N/A

### Next steps
N/A
Already asked in gitter but have not received an answer.

**Comment by cstamatopoulos** [comment]
I think this is the way to do it but I am not sure if that is all the files required to migrate CVAT to another host
```
mkdir ~/backup
docker run --rm --name temp_backup --volumes-from cvat_db -v ~/backup:/backup ubuntu tar -cjvf /backup/cvat_db.tar.bz2 /var/lib/postgresql/data
docker run --rm --name temp_backup --volumes-from cvat -v ~/backup:/backup ubuntu tar -cjvf /backup/cvat_data.tar.bz2 /home/django/data
```

**Comment by smallbee3** [comment]
@cstamatopoulos 

Thanks for the solution!

But it seems there is a typo in your `to restore` command

`/backup/cvat_db.tar.bz2` -> `/backup/cvat_data.tar.bz2`

<br>
<br>

and to restore
```
docker run --rm --name temp_backup --volumes-from cvat_db -v ~/backup:/backup ubuntu bash -c "cd /var/lib/postgresql/data && tar -xvf /backup/cvat_db.tar.bz2 --strip 4"
docker run --rm --name temp_backup --volumes-from cvat -v ~/backup:/backup ubuntu bash -c "cd /home/django/data && tar -xvf /backup/cvat_data.tar.bz2 --strip 3"
```

**Comment by pedrofrodenas** [comment]
You cannot restore postgress db copying data from volume, when docker-compose is run the database keeps restarting again and again.

In order to backup the cvat postgress database, you nned to execute the following command with the cvat_db container running.
This command saves the db data to file dump.sql in current working directory.

`docker exec -i cvat_db /bin/bash -c "pg_dump --username root --clean cvat" > dump.sql`

To restore in another machine, start docker-compose and run

`docker exec -i cvat_db /bin/bash -c "psql --username root cvat" < dump.sql`

**Comment by malfonsoNeoris** [comment]
hi! HELP! needed here..
i executed this
docker exec -i cvat_db /bin/bash -c "psql --username root cvat" < dump.sql
and now everythin is broken!

**Comment by nmanovic** [comment]
@malfonsoNeoris , try to run `docker exec python3 manage.py migrate`. I hope it will help.

**Comment by ikjoooon** [comment]
@nmanovic Can I move and use the data that is backed up to another computer after I back it up from my current computer?

**Comment by nmanovic** [comment]
@didnmj , you can but you need to be sure that you are using the same CVAT version. Only after that upgrade CVAT instance.
