### ISSUE TITLE
Model file deployment issues

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [openvinotoolkit/cvat#2598]
Now that I have packaged the CVAT /openvino.dextr image, can I use just one functions.YAMl file when Deploying the CVAT/Openvino.dextr image

For example：
nuctl deploy --project-name cvat \
--path $SCRIPT_DIR/openvino/dextr/nuclio \
--volume $SCRIPT_DIR/openvino/common:/opt/nuclio/common \
--platform local

There are three files in the path specified by --path one functions.YAMl and two.py files. Can I leave three files in the path specified by path only one functions.yaml

**Comment by bsekachev** [comment]
CVAT provides working configurations out of the box. Any custom changes could lead to unexpected behavior.
We aren't experts in nuclio, it is another framework developed by another team and I am not sure it is right place for such kind of questions.  

Trying to answer your question: Can I leave three ... ? 
You can try, but we do not know what you get in this case.
