### ISSUE TITLE
Integration with Data Version Control (DVC)

### ISSUE THREAD

**Issue by WaldoPepper** [openvinotoolkit/cvat#2602]
When I write code, I change it, improve it, break it, throw it away, try something different...
Git is a tool that helps me with that and I can not think about doing something without it.

I recently started using CNN's for CV, and in addition to changing, improving [...] code, I now deal with training data, annotations, test sets, etc...
DVC became a tool and it seems to have the potential to become indispensable.

Have you thought about supporting something like DVC (or comparable tools which I am not aware of) in the (near) future?

**Comment by zhiltsov-max** [comment]
Hi. We definitely have had a look at DVC and have come to integration with it in Datumaro. Currently, it is in development [here](https://github.com/openvinotoolkit/datumaro/pull/26). We are open to discussion on this topic, you are welcome to share your thoughts on how we can integrate it best.

**Comment by AbdelsalamHaa** [comment]
So how is this function, is it added to CVAT already or to Datumaro

**Comment by zhiltsov-max** [comment]
@AbdelsalamHaa, hi, The DVC integration has only been added in Datumaro. It's not possible to use DVC from CVAT now, but we're open for ideas how it could be implemented. If you just want to save backup copies for dataset versioning, there is an option to attach a Git repository to a task in CVAT.

**Comment by Oceane4973** [comment]
@zhiltsov-max , Hello, I currently need to save backup copies for dataset version control, what is your option to attach a Git repository to a task in CVAT?

What did you mean by "attaching a Git repository to a task in CVAT"? Does it save annotations for an entire task? Does CVAT retrieve annotations from the Git repository to work with?

**Comment by zhiltsov-max** [comment]
@Oceane4973, support for Git repo integration was removed in https://github.com/cvat-ai/cvat/pull/6904 (v2.7.3+). If you want to automate CVAT in your workflow, please consider using webhooks. For backups, please consider using cloud storages, which can be used for import and export.
