### ISSUE TITLE
Unable enable Semi-automatic and automatic annotation

### ISSUE THREAD

**Issue by technoproindia** [openvinotoolkit/cvat#2605]
nuctl deploy --project-name cvat \
        --path serverless/openvino/omz/public/faster_rcnn_inception_v2_coco/nuclio \
        --volume /home/cvat/cvat/serverless/openvino/common:/opt/nuclio/common \
        --platform local
20.12.21 15:04:20.724                     nuctl (I) Deploying function {"name": ""}
20.12.21 15:04:20.724                     nuctl (I) Building {"versionInfo": "Label: 1.5.8, Git commit: c12022750a6003a309d4f20c72a98addacd3e95d, OS: linux, Arch: amd64, Go version: go1.14.3", "name": ""}
20.12.21 15:04:21.149                     nuctl (I) Cleaning up before deployment {"functionName": "openvino-omz-public-faster_rcnn_inception_v2_coco"}
20.12.21 15:04:21.203                     nuctl (I) Staging files and preparing base images
20.12.21 15:04:21.203                     nuctl (I) Building processor image {"imageName": "cvat/openvino.omz.public.faster_rcnn_inception_v2_coco:latest"}
20.12.21 15:04:21.204     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.5.8-amd64"}
20.12.21 15:04:26.746     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/uhttpc:0.0.1-amd64"}
20.12.21 15:04:33.112            nuctl.platform (I) Building docker image {"image": "cvat/openvino.omz.public.faster_rcnn_inception_v2_coco:latest"}
20.12.21 15:04:36.500     nuctl.platform.docker (W) Docker command outputted to stderr - this may result in errors {"workingDir": "/tmp/nuclio-build-102504167/staging", "cmd": "docker build --network host --force-rm -t cvat/openvino.omz.public.faster_rcnn_inception_v2_coco:latest -f /tmp/nuclio-build-102504167/staging/Dockerfile.processor  --build-arg NUCLIO_BUILD_LOCAL_HANDLER_DIR=handler --build-arg NUCLIO_LABEL=1.5.8 --build-arg NUCLIO_ARCH=amd64  .", "stderr": "The command '/bin/bash -xo pipefail -c /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo' returned a non-zero code: 1\n"}
20.12.21 15:04:36.504                     nuctl (W) Create function failed, setting function status {"err": "Failed to build processor image", "errVerbose": "\nError - exit status 1\n    /nuclio/pkg/cmdrunner/shellrunner.go:95\n\nCall stack:\nstdout:\nSending build context to Docker daemon  38.14MB\r\r\nStep 1/16 : FROM openvino/ubuntu18_dev:2020.2\n ---> bf7a4dff2d97\nStep 2/16 : ARG NUCLIO_LABEL\n ---> Using cache\n ---> 68fef893721f\nStep 3/16 : ARG NUCLIO_ARCH\n ---> Using cache\n ---> 207e4c1c2239\nStep 4/16 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR\n ---> Using cache\n ---> ce41e4482db4\nStep 5/16 : USER root\n ---> Using cache\n ---> 0cc19f55b437\nStep 6/16 : WORKDIR /opt/nuclio\n ---> Using cache\n ---> 8ce7166f9de6\nStep 7/16 : RUN ln -s /usr/bin/pip3 /usr/bin/pip\n ---> Using cache\n ---> 51f03e800c7f\nStep 8/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py --name faster_rcnn_inception_v2_coco -o /opt/nuclio/open_model_zoo\n ---> Using cache\n ---> 879dcd971f3d\nStep 9/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n ---> Running in 5db82d0b0087\n\u001b[91m+ /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n\u001b[0m========= Converting faster_rcnn_inception_v2_coco to IR (FP32)\nConversion command: /usr/bin/python3 -- /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework=tf --data_type=FP32 --output_dir=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/FP32 --model_name=faster_rcnn_inception_v2_coco --reverse_input_channels '--input_shape=[1,600,1024,3]' --input=image_tensor --output=detection_scores,detection_boxes,num_detections --transformations_config=/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config --input_model=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb\n\nFAILED:\nfaster_rcnn_inception_v2_coco\nRemoving intermediate container 5db82d0b0087\n\nstderr:\nThe command '/bin/bash -xo pipefail -c /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo' returned a non-zero code: 1\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:95\nFailed to build\n    /nuclio/pkg/dockerclient/shell.go:96\nFailed to build docker image\n    .../pkg/containerimagebuilderpusher/docker.go:53\nFailed to build processor image\n    /nuclio/pkg/processor/build/builder.go:250\nFailed to build processor image", "errCauses": [{"error": "Failed to build docker image", "errorVerbose": "\nError - exit status 1\n    /nuclio/pkg/cmdrunner/shellrunner.go:95\n\nCall stack:\nstdout:\nSending build context to Docker daemon  38.14MB\r\r\nStep 1/16 : FROM openvino/ubuntu18_dev:2020.2\n ---> bf7a4dff2d97\nStep 2/16 : ARG NUCLIO_LABEL\n ---> Using cache\n ---> 68fef893721f\nStep 3/16 : ARG NUCLIO_ARCH\n ---> Using cache\n ---> 207e4c1c2239\nStep 4/16 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR\n ---> Using cache\n ---> ce41e4482db4\nStep 5/16 : USER root\n ---> Using cache\n ---> 0cc19f55b437\nStep 6/16 : WORKDIR /opt/nuclio\n ---> Using cache\n ---> 8ce7166f9de6\nStep 7/16 : RUN ln -s /usr/bin/pip3 /usr/bin/pip\n ---> Using cache\n ---> 51f03e800c7f\nStep 8/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py --name faster_rcnn_inception_v2_coco -o /opt/nuclio/open_model_zoo\n ---> Using cache\n ---> 879dcd971f3d\nStep 9/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n ---> Running in 5db82d0b0087\n\u001b[91m+ /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n\u001b[0m========= Converting faster_rcnn_inception_v2_coco to IR (FP32)\nConversion command: /usr/bin/python3 -- /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework=tf --data_type=FP32 --output_dir=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/FP32 --model_name=faster_rcnn_inception_v2_coco --reverse_input_channels '--input_shape=[1,600,1024,3]' --input=image_tensor --output=detection_scores,detection_boxes,num_detections --transformations_config=/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config --input_model=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb\n\nFAILED:\nfaster_rcnn_inception_v2_coco\nRemoving intermediate container 5db82d0b0087\n\nstderr:\nThe command '/bin/bash -xo pipefail -c /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo' returned a non-zero code: 1\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:95\nFailed to build\n    /nuclio/pkg/dockerclient/shell.go:96\nFailed to build docker image\n    .../pkg/containerimagebuilderpusher/docker.go:53\nFailed to build docker image", "errorCauses": [{"error": "Failed to build", "errorVerbose": "\nError - exit status 1\n    /nuclio/pkg/cmdrunner/shellrunner.go:95\n\nCall stack:\nstdout:\nSending build context to Docker daemon  38.14MB\r\r\nStep 1/16 : FROM openvino/ubuntu18_dev:2020.2\n ---> bf7a4dff2d97\nStep 2/16 : ARG NUCLIO_LABEL\n ---> Using cache\n ---> 68fef893721f\nStep 3/16 : ARG NUCLIO_ARCH\n ---> Using cache\n ---> 207e4c1c2239\nStep 4/16 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR\n ---> Using cache\n ---> ce41e4482db4\nStep 5/16 : USER root\n ---> Using cache\n ---> 0cc19f55b437\nStep 6/16 : WORKDIR /opt/nuclio\n ---> Using cache\n ---> 8ce7166f9de6\nStep 7/16 : RUN ln -s /usr/bin/pip3 /usr/bin/pip\n ---> Using cache\n ---> 51f03e800c7f\nStep 8/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py --name faster_rcnn_inception_v2_coco -o /opt/nuclio/open_model_zoo\n ---> Using cache\n ---> 879dcd971f3d\nStep 9/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n ---> Running in 5db82d0b0087\n\u001b[91m+ /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n\u001b[0m========= Converting faster_rcnn_inception_v2_coco to IR (FP32)\nConversion command: /usr/bin/python3 -- /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework=tf --data_type=FP32 --output_dir=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/FP32 --model_name=faster_rcnn_inception_v2_coco --reverse_input_channels '--input_shape=[1,600,1024,3]' --input=image_tensor --output=detection_scores,detection_boxes,num_detections --transformations_config=/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config --input_model=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb\n\nFAILED:\nfaster_rcnn_inception_v2_coco\nRemoving intermediate container 5db82d0b0087\n\nstderr:\nThe command '/bin/bash -xo pipefail -c /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo' returned a non-zero code: 1\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:95\nFailed to build\n    /nuclio/pkg/dockerclient/shell.go:96\nFailed to build", "errorCauses": [{"error": "stdout:\nSending build context to Docker daemon  38.14MB\r\r\nStep 1/16 : FROM openvino/ubuntu18_dev:2020.2\n ---> bf7a4dff2d97\nStep 2/16 : ARG NUCLIO_LABEL\n ---> Using cache\n ---> 68fef893721f\nStep 3/16 : ARG NUCLIO_ARCH\n ---> Using cache\n ---> 207e4c1c2239\nStep 4/16 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR\n ---> Using cache\n ---> ce41e4482db4\nStep 5/16 : USER root\n ---> Using cache\n ---> 0cc19f55b437\nStep 6/16 : WORKDIR /opt/nuclio\n ---> Using cache\n ---> 8ce7166f9de6\nStep 7/16 : RUN ln -s /usr/bin/pip3 /usr/bin/pip\n ---> Using cache\n ---> 51f03e800c7f\nStep 8/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py --name faster_rcnn_inception_v2_coco -o /opt/nuclio/open_model_zoo\n ---> Using cache\n ---> 879dcd971f3d\nStep 9/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n ---> Running in 5db82d0b0087\n\u001b[91m+ /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n\u001b[0m========= Converting faster_rcnn_inception_v2_coco to IR (FP32)\nConversion command: /usr/bin/python3 -- /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework=tf --data_type=FP32 --output_dir=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/FP32 --model_name=faster_rcnn_inception_v2_coco --reverse_input_channels '--input_shape=[1,600,1024,3]' --input=image_tensor --output=detection_scores,detection_boxes,num_detections --transformations_config=/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config --input_model=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb\n\nFAILED:\nfaster_rcnn_inception_v2_coco\nRemoving intermediate container 5db82d0b0087\n\nstderr:\nThe command '/bin/bash -xo pipefail -c /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo' returned a non-zero code: 1\n", "errorVerbose": "\nError - exit status 1\n    /nuclio/pkg/cmdrunner/shellrunner.go:95\n\nCall stack:\nstdout:\nSending build context to Docker daemon  38.14MB\r\r\nStep 1/16 : FROM openvino/ubuntu18_dev:2020.2\n ---> bf7a4dff2d97\nStep 2/16 : ARG NUCLIO_LABEL\n ---> Using cache\n ---> 68fef893721f\nStep 3/16 : ARG NUCLIO_ARCH\n ---> Using cache\n ---> 207e4c1c2239\nStep 4/16 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR\n ---> Using cache\n ---> ce41e4482db4\nStep 5/16 : USER root\n ---> Using cache\n ---> 0cc19f55b437\nStep 6/16 : WORKDIR /opt/nuclio\n ---> Using cache\n ---> 8ce7166f9de6\nStep 7/16 : RUN ln -s /usr/bin/pip3 /usr/bin/pip\n ---> Using cache\n ---> 51f03e800c7f\nStep 8/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py --name faster_rcnn_inception_v2_coco -o /opt/nuclio/open_model_zoo\n ---> Using cache\n ---> 879dcd971f3d\nStep 9/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n ---> Running in 5db82d0b0087\n\u001b[91m+ /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n\u001b[0m========= Converting faster_rcnn_inception_v2_coco to IR (FP32)\nConversion command: /usr/bin/python3 -- /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework=tf --data_type=FP32 --output_dir=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/FP32 --model_name=faster_rcnn_inception_v2_coco --reverse_input_channels '--input_shape=[1,600,1024,3]' --input=image_tensor --output=detection_scores,detection_boxes,num_detections --transformations_config=/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config --input_model=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb\n\nFAILED:\nfaster_rcnn_inception_v2_coco\nRemoving intermediate container 5db82d0b0087\n\nstderr:\nThe command '/bin/bash -xo pipefail -c /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo' returned a non-zero code: 1\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:95\nstdout:\nSending build context to Docker daemon  38.14MB\r\r\nStep 1/16 : FROM openvino/ubuntu18_dev:2020.2\n ---> bf7a4dff2d97\nStep 2/16 : ARG NUCLIO_LABEL\n ---> Using cache\n ---> 68fef893721f\nStep 3/16 : ARG NUCLIO_ARCH\n ---> Using cache\n ---> 207e4c1c2239\nStep 4/16 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR\n ---> Using cache\n ---> ce41e4482db4\nStep 5/16 : USER root\n ---> Using cache\n ---> 0cc19f55b437\nStep 6/16 : WORKDIR /opt/nuclio\n ---> Using cache\n ---> 8ce7166f9de6\nStep 7/16 : RUN ln -s /usr/bin/pip3 /usr/bin/pip\n ---> Using cache\n ---> 51f03e800c7f\nStep 8/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py --name faster_rcnn_inception_v2_coco -o /opt/nuclio/open_model_zoo\n ---> Using cache\n ---> 879dcd971f3d\nStep 9/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n ---> Running in 5db82d0b0087\n\u001b[91m+ /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo\n\u001b[0m========= Converting faster_rcnn_inception_v2_coco to IR (FP32)\nConversion command: /usr/bin/python3 -- /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework=tf --data_type=FP32 --output_dir=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/FP32 --model_name=faster_rcnn_inception_v2_coco --reverse_input_channels '--input_shape=[1,600,1024,3]' --input=image_tensor --output=detection_scores,detection_boxes,num_detections --transformations_config=/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config --input_model=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb\n\nFAILED:\nfaster_rcnn_inception_v2_coco\nRemoving intermediate container 5db82d0b0087\n\nstderr:\nThe command '/bin/bash -xo pipefail -c /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo' returned a non-zero code: 1\n", "errorCauses": [{"error": "exit status 1"}]}]}]}]}

Error - exit status 1
    /nuclio/pkg/cmdrunner/shellrunner.go:95

Call stack:
stdout:
Sending build context to Docker daemon  38.14MB
Step 1/16 : FROM openvino/ubuntu18_dev:2020.2
 ---> bf7a4dff2d97
Step 2/16 : ARG NUCLIO_LABEL
 ---> Using cache
 ---> 68fef893721f
Step 3/16 : ARG NUCLIO_ARCH
 ---> Using cache
 ---> 207e4c1c2239
Step 4/16 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR
 ---> Using cache
 ---> ce41e4482db4
Step 5/16 : USER root
 ---> Using cache
 ---> 0cc19f55b437
Step 6/16 : WORKDIR /opt/nuclio
 ---> Using cache
 ---> 8ce7166f9de6
Step 7/16 : RUN ln -s /usr/bin/pip3 /usr/bin/pip
 ---> Using cache
 ---> 51f03e800c7f
Step 8/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py --name faster_rcnn_inception_v2_coco -o /opt/nuclio/open_model_zoo
 ---> Using cache
 ---> 879dcd971f3d
Step 9/16 : RUN /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo
 ---> Running in 5db82d0b0087
+ /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo
========= Converting faster_rcnn_inception_v2_coco to IR (FP32)
Conversion command: /usr/bin/python3 -- /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework=tf --data_type=FP32 --output_dir=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/FP32 --model_name=faster_rcnn_inception_v2_coco --reverse_input_channels '--input_shape=[1,600,1024,3]' --input=image_tensor --output=detection_scores,detection_boxes,num_detections --transformations_config=/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config --input_model=/opt/nuclio/open_model_zoo/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb

FAILED:
faster_rcnn_inception_v2_coco
Removing intermediate container 5db82d0b0087

stderr:
The command '/bin/bash -xo pipefail -c /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/converter.py --name faster_rcnn_inception_v2_coco --precisions FP32 -d /opt/nuclio/open_model_zoo -o /opt/nuclio/open_model_zoo' returned a non-zero code: 1

    /nuclio/pkg/cmdrunner/shellrunner.go:95
Failed to build
    /nuclio/pkg/dockerclient/shell.go:96
Failed to build docker image
    .../pkg/containerimagebuilderpusher/docker.go:53
Failed to build processor image
    /nuclio/pkg/processor/build/builder.go:250
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:175

**Comment by bsekachev** [comment]
Hi, @technoproindia 

I was not able to reproduce the issue on my side. The process was succeed.
Please, try one more time. If it will be failed again, probably better to ask OpenVINO developers in the corresponding repository https://github.com/openvinotoolkit/openvino
