### ISSUE TITLE
Development mode: network error

### ISSUE THREAD

**Issue by xyc2690** [openvinotoolkit/cvat#2611]
I followed the instructions in 
https://github.com/openvinotoolkit/cvat/blob/develop/CONTRIBUTING.md

In the last step, when I tried to login, I got the following error：
Could not check authorization on the server
Error: Network Error.
Could not get user agreements from the server
Error: Network Error.

OS：ubuntu 18.04

What could be the problem？

**Comment by azhavoro** [comment]
Most likely the cvat backend doesn't run, make sure that you run this step: `Select server: debug configuration and start it (F5) to run REST server and its workers` and the server is successfully started.
P.S. please use [Github Discussions](https://github.com/openvinotoolkit/cvat/discussions) or Gitter for such questions.
