### ISSUE TITLE
Can CVAT do text input where the user types in description (2-3 lines)

### ISSUE THREAD

**Issue by nikky4D** [openvinotoolkit/cvat#2613]
This is a question on CVAT's capabilities: 

Can CVAT do text input where the annotator types a 2-3 line description of image/video into a text box?

**Comment by bsekachev** [comment]
Hi, @nikky4D

CVAT cannot do it currently. Text attributes are single-lined. 
You could use artificial line separators I suppose (maybe ``;`` for example) and process them after dumping annotations.
