### ISSUE TITLE
When reselecting an annotation box the top menu disappears

### ISSUE THREAD

**Issue by Inquisitive-ME** [openvinotoolkit/cvat#2621]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Whenever I either create an annotation or automatically annotate an image. If I select that box again it shifts the viewer down so that I can no longer access the top menu. I believe this maybe a screen size issue as I am using a 14" laptop.

### Expected Behaviour
Should be able to always access top menu

### Current Behaviour
top menu goes away so I can no longer hit save, next or export annotations.

### Before
![image](https://user-images.githubusercontent.com/13723516/103181010-a60f9a00-4861-11eb-9f14-e5546e84431e.png)

### After
![image](https://user-images.githubusercontent.com/13723516/103181020-bfb0e180-4861-11eb-9502-e124497581c9.png)

### Your Environment
Server version: 1.2rc0
Core version: 3.10.0
Canvas version: 2.2.1
UI version: 1.13.1

Running from docker containers off master

If I use full screen mode it works as expected so I would say this is probably low priority

**Comment by ashokbalaraman** [comment]
@Inquisitive-ME: Yeah.  I ran into the same issue.  Zooming out (ctrl-) and zooming in (ctrl+) brought back the Top Panel.

**Comment by nmanovic** [comment]
Thanks for the report. We will look at the issue.

**Comment by bsekachev** [comment]
Hi @Inquisitive-ME, what is your screen resolution? Do you use windows system scale?

**Comment by bsekachev** [comment]
@Inquisitive-ME never mind, was able to reproduce it in chrome dev tools with 1360x768 resolution. I hope the patch above will help you with it. Let me know if it will not.
