### ISSUE TITLE
Kibana_Create index pattern

### ISSUE THREAD

**Issue by Huynh-Chinh** [openvinotoolkit/cvat#2640]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

![image](https://user-images.githubusercontent.com/61222689/103507939-d626f080-4e92-11eb-914b-f9335e6cf321.png)

### Current Behaviour

![image](https://user-images.githubusercontent.com/61222689/103507812-92cc8200-4e92-11eb-95f5-fe3a27447b21.png)

### Context

I tried to build a kibana runtime but it still doesn't have a default index.
I tried to do it manually, but the default index cannot be saved.
Please someone who can help me.

### Your Environment

- Git hash commit (`git log -1`): git log -1
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 19.03.8
- Are you using Docker Swarm or Kubernetes?: Docker Swarm
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem: 
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by MarioProjects** [comment]
How did you solve that?
