### ISSUE TITLE
Unable to move (drag with the mouse) track when it's a polygon

### ISSUE THREAD

**Issue by Smirkey** [openvinotoolkit/cvat#2650]
### My actions before raising this issue
- Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- Searched [past issues](/issues)

Hello, when I draw a boundingBox (2 points) in track mode it's totally possible to drag it on the image. But sadly when I try the same thing with a polygon the whole image moves instead of moving the polygon on the image.

I couldn't find anything in the docs or in previous issues related to this problem.

Thanks in advance for your response :)

Best

**Comment by azhavoro** [comment]
@bsekachev could you please take a look?

**Comment by bsekachev** [comment]
@Smirkey 

Hi, thanks for you concern.
Polygons are default "pinned" and cannot be moved (in the most of task you do not need to move an entire polygon).
To do them "unpinned" press the icon button (shown on the screenshot below)
![Screenshot from 2021-01-14 09-20-00](https://user-images.githubusercontent.com/40690378/104552395-ce610c00-5649-11eb-9f2e-6571bcddd013.png)

**Comment by Smirkey** [comment]
Thank you :) !

**Comment by mohammadreza-sheykhmousa** [comment]
Hi @bsekachev there actually are many instances that suffer from mismatching thus it is crucial to move ans also sometimes to rotate multiple polygons at once. I know about the unpinning, however I was wondering is there any other convenient way of moving (single or multiple at once) polygons? How about rotating? if not is there any plan to add such capabilities which seems crucial to many geospatial data labeling? I appreciate the help and thank you :)

**Comment by bsekachev** [comment]
Hi @mohammadreza-sheykhmousa 

We do not have these features in our current road map. Since our team has limited resources we can't satisfy all the community requests. But CVAT is an open source tool which everyone can contribute into, and we would like to review community PRs, provide feedbacks, and give advice if necessary
