### ISSUE TITLE
Unable to get the models from the server to CVAT tool

### ISSUE THREAD

**Issue by IshanBorkar10038** [openvinotoolkit/cvat#2651]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have installed and enabled nuclio as well as cvat tool and completed all the serverless functions from the nuclio deploy. However when I am opening http://localhost:8080. it opens CVAT tool and shows that "**Could not get the models from the server**" like fasterrcnn, maskrcnn etc.
Kindly provide me the solution for this issue.
I have attached the screenshot below for the reference. 
![image](https://user-images.githubusercontent.com/77141119/104012259-84090680-51d5-11eb-8645-8d5ada3403aa.png)

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.2
- Are you using Docker Swarm or Kubernetes? Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu 18.04

**Comment by azhavoro** [comment]
please attach logs from cvat container

**Comment by azhavoro** [comment]
No response a long time, I'll close the issue. Feel free to re-open if this issue is still actual.
