### ISSUE TITLE
Can depth images be displayed?

### ISSUE THREAD

**Issue by happyCodingSusan** [openvinotoolkit/cvat#2652]
@CVAT, thanks for sharing your great work! Are you able to display both RGB and depth images? If annotation can only be done on rgb images, is it possible to display its depth pair since the depth image can help the annotator to identify the correct object boundaries in RGB images, especially in occluded cases. It is even better if annotating depth images is supported.

**Comment by jahaniam** [comment]
Agreed. Looking forward to this.

**Comment by nmanovic** [comment]
@bsekachev , should we close the issue after adding context images feature?

**Comment by bsekachev** [comment]
Please look at #3122 and user guide to be acquainted with context images. I'll close the issue for now, do not hesitate to reopen it if the suggested feature does not sutisfy your request.
