### ISSUE TITLE
How to download annotations from all tasks at once ?

### ISSUE THREAD

**Issue by Smirkey** [openvinotoolkit/cvat#2678]
### My actions before raising this issue

- Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)

- Searched [past issues](/issues)

Hi !

I would like to know if there's a straightforward way to download annotations (and images ?) from all tasks from the interface or using the CLI.

I have a lot of tasks so downloading manually from the interface would take too much time. 

Thanks :)

**Comment by yohayonyon** [comment]
I've been using the list command and then the dump command for every task. This is very slow.
If there is a better way, I would be glad to know.
Refer to the [CLI README](https://github.com/openvinotoolkit/cvat/tree/develop/utils/cli).

**Comment by Smirkey** [comment]
Ok will use the CLI then, being able to extract all annotations from all task as a new dataset would be awesome indeed !

**Comment by azhavoro** [comment]
In the future, we will add such functionality for projects that it will be possible to download annotations for all tasks in the project.

**Comment by nikky4D** [comment]
is there functionality for this yet?

**Comment by ActiveChooN** [comment]
@nikky4D. Project dump is planned for future releases.

**Comment by tongchangD** [comment]
Has it been realized?
