### ISSUE TITLE
Update REST API documentation (assignee_id, owner_id,  etc.)

### ISSUE THREAD

**Issue by jordancharest** [openvinotoolkit/cvat#2679]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

POST request to the /tasks REST API to create a new task, a new task is not created and the server responds that the username for the assignee and owner already exists, which is to be expected because you cannot assign a task to a non-existent user.

### Expected Behaviour

A task should be created, owned by the provided owner and assigned to the provided assignee.

### Current Behaviour

Server responds:
```
{"owner":{"username":["A user with that username already exists."]},"assignee":{"username":["A user with that username already exists."]}}
```
### Steps to Reproduce (for bugs)

Create a user (or two). Make the following request:
```
curl -X POST "https://<domain>/api/v1/tasks" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Token <auth-token>" -d "{ \"name\": \"API Task\", \"owner\": { \"username\": \"<existing user>\"}, \"assignee\": { \"username\": \"<existing user>\"}, \"labels\": [ { \"name\": \"box\" } ]}"
```

### Context

I am building a service that automates the creation of new tasks when a user finishes their existing task.

### Your Environment

- Git hash commit (`git log -1`): a440ef24f88749a99cc6eaaf434821b9b3a3ca60
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.14
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
`docker logs cvat`:
```
2021-01-18 18:20:56,356 DEBG 'runserver' stderr output:
[Mon Jan 18 18:20:56.355854 2021] [wsgi:error] [pid 154:tid 140259286574848] [remote 172.28.0.3:56084] [2021-01-18 18:20:56,355] WARNING django.request: Bad Request: /api/v1/tasks
[Mon Jan 18 18:20:56.356096 2021] [wsgi:error] [pid 154:tid 140259286574848] [remote 172.28.0.3:56084] WARNING:django.request:Bad Request: /api/v1/tasks
```

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi @jordancharest 

``owner``, ``assignee`` and other user related fields aren't expected to be in server request anymore (they can only come from server response). Instead use ``owner_id``, ``assignee_id``, etc. Let me know if it helps.

**Comment by jordancharest** [comment]
Yes, you are right, thank you. Maybe the documentation is out of date or I am reading it wrong? These are the parameters I see. I am new to using REST APIs so I could definitely be reading it wrong.
![image](https://user-images.githubusercontent.com/31459889/105042149-e366e200-5a31-11eb-92c7-a6742203431c.png)

**Comment by bsekachev** [comment]
@jordancharest 

You are right, CVAT lacks of documentation for this case.

**Comment by nmanovic** [comment]
It will be reimplemented. We are going to work on the REST API documentation in the nearest future.  I will close the issue.
