### ISSUE TITLE
Flipping polygon shapes

### ISSUE THREAD

**Issue by ktobah** [openvinotoolkit/cvat#2688]
### My actions before raising this issue
- [ Y] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ Y] Searched [past issues](/issues)

### Expected Behaviour
I would like to ask if it is possible to implement a new feature where polygons (or shapes in general) can be flipped (as you would flip an image). For example, I draw the shape of a car door which is on the right side view. Then in the next picture, I have the same exact car but on the left side. It would be a time saver if I can just copy the polygon (which is possible now) and flip it, then just adjust it in its correct position.  

### Current Behaviour
Flipping a polygon is not supported.

### Context
Because I am not able to flip the polygon, I have to redraw it all over again which wastes a lot of time.

**Comment by bsekachev** [comment]
Hi @ktobah 

Generally the feature is possible, but the core CVAT team currently has other priorities. The CVAT community is always welcome to implement new features and improve existing. I'll put the issue into backlog. 

I suppose it can be done in two actions:
1. Select a spape
2. Draw an axis to flipping

**Comment by nmanovic** [comment]
@ktobah , it looks like you try to annotate augmented images. It is better to annotate unique images and transform annotations together with images after that. I don't think that the "flip" case can be applied in general to annotate shapes. I will close the feature request.
