### ISSUE TITLE
Cannot open filter help dialog windows

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#2690]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Can open filter help dialog window

### Current Behaviour
Can't open filter help dialog window

### Possible Solution
Fix the bug

### Steps to Reproduce (for bugs)

1. Open a job
1. Go to filters input field
1. Press filters icon
1.

### Your Environment

- Git hash commit (`git log -1`): f84c128
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi, @dvkruchinin 
Do we have such a test? If do, I suppose it probably work using ``force`` argument when clicking. Actually user cannot press the button, but I was able to do it via selectors in the Browser Console.

**Comment by dvkruchinin** [comment]
Hi, @bsekachev 
At the moment, there is no test for this functionality. I'll prepare it.
