### ISSUE TITLE
Problem "split" function doesn't work with polygons/boundingboxes

### ISSUE THREAD

**Issue by Smirkey** [openvinotoolkit/cvat#2692]
### My actions before raising this issue
- Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- Searched [past issues](/issues)

Hi :)

When I try to use the split function on a polygon/boundingbox nothing appens. My cursors changes and when I drag the mouse over a bbx/poly the object becomes blue, but when I click nothing appens. Am i missing something here?

My goal is to be able to cut a polygon in two by drawing a cutting line.

Thanks !

**Comment by bsekachev** [comment]
Hi @Smirkey 

The function of split doesn't cut a polygon into several polygons by cutting line (CVAT doesn't have such a function like you described).
Please, refer to user guide.
