### ISSUE TITLE
tfRecord grayed out

### ISSUE THREAD

**Issue by ericchen321** [openvinotoolkit/cvat#2711]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When exporting a job in TFRecord format (including the `.tfRecord` file and the `.pbtxt` file) by clicking Export as a Dataset -> TFRecord 1.0, I expected the TFRecord option to be not grayed out, **as on [cvat.org](https://cvat.org/tasks)**:

![image](https://user-images.githubusercontent.com/22675300/105617893-0b8a7400-5d97-11eb-88fa-f40f53821068.png)

### Current Behaviour

but I saw the TFRecord option being grayed out when I tried, **while running CVAT locally on my desktop**:

![image](https://user-images.githubusercontent.com/22675300/105617617-6f5f6d80-5d94-11eb-96b4-367154caba82.png)

### Steps to Reproduce (for bugs)

1. Install CVAT following [the installation doc](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md), and launch CVAT
2. Create a project and a task under the project created
3. Import Pascal-VOC annotations (a list of `.xml` files) for the task
4. Export as a Dataset -> TFRecord 1.0

### Context

I was trying to use CVAT to convert YOLO annotations to TFRecord for a dataset I created.

### Your Environment

- Git hash commit: `3ced77c`
- Docker version : `20.10.2`
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem: No code
- Other diagnostic information / logs: None

**Comment by azhavoro** [comment]
@ericchen321 Hi, make sure that your CPU supports AVX instruction set. https://github.com/openvinotoolkit/cvat/issues/1393

**Comment by ericchen321** [comment]
Hey @azhavoro , thanks for the help! Yes, my CPU (Xeon E5-1650) supports the AVX instruction set, based on docs I found [here](https://ark.intel.com/content/www/us/en/ark/products/64601/intel-xeon-processor-e5-1650-12m-cache-3-20-ghz-0-0-gt-s-intel-qpi.html). Also if I ssh into the docker container, and run `pip list`, I cannot see `tensorflow` listed.

**Comment by azhavoro** [comment]
@ericchen321 probably there is an issue with tensorflow==2.4.0 https://github.com/openvinotoolkit/cvat/blob/develop/cvat/requirements/base.txt#L42 which requires avx2 support, and looks like this was removed in 2.4.1 (https://github.com/tensorflow/tensorflow/issues/45866). could you please change corresponding line in the base.txt and send PR if it that helps?

**Comment by azhavoro** [comment]
@ericchen321 Have you solved the issue?

**Comment by ericchen321** [comment]
> @ericchen321 Have you solved the issue?

Hi @azhavoro , sorry for not replying earlier. Due to our time constraints, we did not keep on debugging, and moved onto Roboflow to generate ``.tfrecord`` files. But thank you for the help anyway!

**Comment by mgroenemeijer** [comment]
Same issue. It is grayed out for me aswell, tensorflow is listed within the docker container. Any advice?
