### ISSUE TITLE
Manual configuration file for Tasks

### ISSUE THREAD

**Issue by rushabh31** [openvinotoolkit/cvat#2722]
I am trying to deploy CVAT tool and don't want to use UI to create tasks and to upload images.  Is it possible to write a task configuration file manually and defaulting the app to read that config?
This config file would contain the path from where the images can be loaded and it would also contain labels for annotation.

**Comment by azhavoro** [comment]
At the moment you can use cli.py to create a task with REST API https://github.com/openvinotoolkit/cvat/tree/develop/utils/cli. 
I think it's good idea to support a task config file by CLI.

**Comment by nmanovic** [comment]
It looks like a question which was answered. I will close the issue.
