### ISSUE TITLE
Incorrect position of the arrow on the object sidebar and Appearance.

### ISSUE THREAD

**Issue by dvkruchinin** [openvinotoolkit/cvat#2732]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
The position of the arrow opposite the Details and Appearance lines

### Current Behaviour
The position of the arrow is slightly below the specified lines.
![changing_the_css_style_for_the_arrow](https://user-images.githubusercontent.com/33020454/106111012-8c14f000-615c-11eb-81f7-d4ddd093f176.JPG)

### Steps to Reproduce (for bugs)

1. Start creating a task. Add label with at least one attribute. 
2. Open the task, open a job.
3. Draw an object.

### Your Environment

- Git hash commit (`git log -1`): 2e9b17afadc8e05286214001d7880a62c0579fdb
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.2
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Maybe specific for windows OS.
