### ISSUE TITLE
subtractive grouped shapes required

### ISSUE THREAD

**Issue by jahaniam** [openvinotoolkit/cvat#2745]
I have annotations similar to the following. As far as I understood CVAT does not support annotations like this, even importing annotation using the segmentation mask method fails. It would be nice in the grouped polygons, each could have attributes `additive` or `subtractive` then converting this binary mask to polygon would be the outer addictive polygon grouped by the subtractive inner polygon. 
This way we can have any annotation shapes.

![image4](https://user-images.githubusercontent.com/13435607/106328497-2ba9af80-623d-11eb-838b-13a74fdea492.png)

**Comment by nmanovic** [comment]
@jahaniam , it is supported. If black is background, then you can use z-order to correctly generate the mask. Look for z-order in documentation.

**Comment by jahaniam** [comment]
Thanks
