### ISSUE TITLE
automatic annotation with custom models

### ISSUE THREAD

**Issue by MrSouwbauck** [openvinotoolkit/cvat#2754]
Hi,
Is there a way to make auto annotation working with custom models ? I have my own custom dataset so i can't use the generic models. I already have custom models (.h5 tensorflow models).
thanks in advance.

**Comment by nmanovic** [comment]
@azhavoro , could you please add the question to FAQ and close the issue?

**Comment by MaloM-CVision** [comment]
@azhavoro, i'm also interested by this functionnality.

**Comment by MaloM-CVision** [comment]
@azhavoro can you explain how to do it ? thanks

**Comment by valavanisleonidas** [comment]
Did you add it to the FAQ? Is there a link to the answer?

**Comment by MaloM-CVision** [comment]
> Did you add it to the FAQ? Is there a link to the answer?

No, i'm still waiting for the answer too..

**Comment by azhavoro** [comment]
@marcociccone Hi, please take a look at this PR https://github.com/openvinotoolkit/cvat/pull/3124
