### ISSUE TITLE
[Feature request] Smart attribute keeper

### ISSUE THREAD

**Issue by victor-ab** [openvinotoolkit/cvat#2755]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

![image](https://user-images.githubusercontent.com/26576394/106546172-6fc0dc80-64e9-11eb-908c-911fbf0620c8.png)

### Expected Behaviour
If you change the current label to another label with the same attribute name, keep the attribute value.

### Current Behaviour
If you change the current label to another label, it cleans the attribute value even if both have the same attribute name.

### Possible Solution
I am not a CVAT specialist, sorry.

### Steps to Reproduce (for bugs)
1. change the current label to another label with the same attribute name

### Context
A very simple tweak could improve a lot the annotation experience for certain types of annotations, specially on documents.

**Comment by timurlenk07** [comment]
I would also like this feature, it is an essential one for OCR annotations. Something simple would do the trick, like if the attribute name and type matches, keep the last value.

**Comment by zhouyuangan** [comment]
keep watching for this feature...

**Comment by nmanovic** [comment]
@timurlenk07 , thanks for your contribution. It looks like the issue was resolved long time ago. I will close the feature request.

https://github.com/openvinotoolkit/cvat/pull/3309
