### ISSUE TITLE
Upload annotations transform track in shape

### ISSUE THREAD

**Issue by MrSouwbauck** [openvinotoolkit/cvat#2757]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
When uploading tracking annotations in format that support it (eg pascal voc, coco), annotations should be tracks.
### Current Behaviour
When uploading tracking annotations, annotations always became shape and don't keep id.

### Steps to Reproduce (for bugs)

1.Make a track annotation
1.Dump annotation
1.Try to upload annotations

Thanks in advance

**Comment by zhiltsov-max** [comment]
Formats that support tracks are those, that designed for tracks, i.e.
- CVAT for video
- MOT
- MOTS

Other formats are not supposed to support importing of tracks.

**Comment by MrSouwbauck** [comment]
okay, I tried CVAT for images but forget to try CVAT for video. thanks
