### ISSUE TITLE
[Bug] UnboundLocalError at auto-annotations with empty data.

### ISSUE THREAD

**Issue by DmitriyOparin** [openvinotoolkit/cvat#2769]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
UnboundLocalError does not occurs. Response returned with status code = 400 Bad Requests.

### Current Behaviour
UnboundLocalError occurs. 

### Possible Solution
Fix the bug.

### Steps to Reproduce (for bugs)
1. Create task
2. Install function
3. Create POST query to '/api/v1/lambda/requests' with data = {} 

### Your Environment

- Git hash commit (`git log -1`): 3d4fad4c1b9ab4c79ae0636c82fe463a00c54e4d
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>

 </details>

>   File "/home/diman/.local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, args, *kwargs)
  File "/home/diman/git/cvat/cvat/apps/lambda_manager/views.py", line 499, in func_wrapper
    data = func(*args, **kwargs)
  File "/home/diman/git/cvat/cvat/apps/lambda_manager/views.py", line 594, in create
    '`{}` lambda function was run '.format(function) +
UnboundLocalError: local variable 'function' referenced before assignment

   

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@DmitriyOparin , could you please prepare a PR for the bug?

**Comment by DmitriyOparin** [comment]
@nmanovic, yes, I will fix this error
