### ISSUE TITLE
Garbage on the beginning and on the end of annotation dumps generated using the CLI

### ISSUE THREAD

**Issue by yohayonyon** [openvinotoolkit/cvat#2779]
### My actions before raising this issue
- [v] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [v] Searched [past issues](/issues)

### Expected Behaviour

The files usualy started with
`<?xml version="1.0" encoding="utf-8"?>`
and finished with
`</annotations>`

### Current Behaviour

A few garbage characters are added before the beginning and after the end of the file.

![Screenshot from 2021-02-07 15-54-44](https://user-images.githubusercontent.com/61744528/107148798-d9177400-695d-11eb-88f7-359d2ed6ce8d.png)

![Screenshot from 2021-02-07 15-55-02](https://user-images.githubusercontent.com/61744528/107148803-df0d5500-695d-11eb-9e80-50edbaca863d.png)

### Steps to Reproduce (for bugs)

1. Upload a task
2. Use the CLI interface to dump its annotations.

### Context

A tool that was written in Python to generate dumps of many tasks has generated the files as described above.
BTW, using the GUI, it does not happen.

### Your Environment

- Git hash commit (`git log -1`): tag v1.1.0
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.9
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18

**Comment by zhiltsov-max** [comment]
Both gui and cli return zip archives.

**Comment by yohayonyon** [comment]
I am using v1.1.0 anf I get an XML when using CLI. Was this changed on a newer version?

**Comment by zhiltsov-max** [comment]
It was changed prior to 1.0.0.

**Comment by azhavoro** [comment]
@yohayonyon May I close the issue?

**Comment by yohayonyon** [comment]
No, it has just happened with a clean v1.2.0 build.
![Uploading Screenshot from 2021-02-15 11-54-12.png…]()

**Comment by codeistpl** [comment]
If this is a zip, why content is not comressed ?

**Comment by yohayonyon** [comment]
Well, I do not know. But executing "unzip out2" created a normal annotation file names "annotations.xml".
This issue may be closed.
