### ISSUE TITLE
Nightly build is failed (.cvat-draw-polygon-popover-visible never found)

### ISSUE THREAD

**Issue by nmanovic** [openvinotoolkit/cvat#2792]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

CI tests have to be robust.

### Current Behaviour

```
  2) Actions on polygon
       Testing case "10"
         Draw a polygon shape, track with second label:
     AssertionError: Timed out retrying: Expected to find element: `.cvat-draw-polygon-popover-visible`, but never found it.
      ./cypress/support/commands.js/<@http://localhost:8080/__cypress/tests?p=cypress/support/index.js:1035:6
      runCommand/<@http://localhost:8080/__cypress/runner/cypress_runner.js:169097:15
      tryCatcher@http://localhost:8080/__cypress/runner/cypress_runner.js:10325:23
```

### Steps to Reproduce (for bugs)

https://github.com/openvinotoolkit/cvat/actions/runs/556084657

### Context

Nightly testing on our CI

**Comment by dvkruchinin** [comment]
This is similar to the situation after the antd update. And is reproduce frequently in Firefox browser in headless mode. The error became reproducible after the commit merge #2780 . I will try to solve it by means of Cypress.
