### ISSUE TITLE
Numpy version 1.20 conflict 

### ISSUE THREAD

**Issue by ChrisPHP** [openvinotoolkit/cvat#2799]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)

### Expected Behaviour

Should successfully install the cvat/requirements/development.txt as shown in the CONTRIBUTION.md.

### Current Behaviour

When attempting to install development.txt it will use NumPy version 1.20 causing conflicts.

```
The conflict is caused by:
    The user requested numpy==1.20.0
    datumaro 0.1.5.1 depends on numpy>=1.17.3
    h5py 2.10.0 depends on numpy>=1.7
    open3d 0.11.2 depends on numpy
    opencv-python-headless 4.4.0.42 depends on numpy>=1.17.3
    tensorflow 2.4.1 depends on numpy~=1.19.2
```

### Possible Solution

Editing the cvat/development/base.txt  file and changing NumPy version to 1.19.5 appears to fix the problem.

### Steps to Reproduce (for bugs)

1. git clone https://github.com/opencv/cvat
1. cd cvat && mkdir logs keys
1. python3 -m venv .env
1. . .env/bin/activate
2. pip install -U pip wheel setuptools
3. pip install -r cvat/requirements/development.txt

### Context

I'm trying to run the developmental environment for my own fork of CVAT.

### Your Environment

- Development branch
- Docker: 20.10.3
- Operating System: **Arch Linux**

**Comment by bsekachev** [comment]
@azhavoro Could you please look at the issue? I think it should not be difficult to fix, but it affects community when they try to setup dev environment
