### ISSUE TITLE
Macbook pro with Linux 18.04 and docker cvat -> when trying to open in browser giving error

### ISSUE THREAD

**Issue by vibhubithar** [openvinotoolkit/cvat#2804]
Steps:
installed linux 18.04 on Macbook pro
installed docker
ran openvino docker image -> tested / working
docker pull openvino/cvat_ui
docker run -p 80:80 --name some-cvat-ui -d openvino/cvat_ui

ran locahost:80 (tried both firefix and chrome)

TypeError
n.map is not a function

pl<@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:365:390070
qo@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:57930
Ii@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:66791
Pi@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:66610
ji@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:66293
gs@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:107698
cl@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:96719
sl@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:96642
Qs@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:93672
Kr/<@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:45314
t.unstable_runWithPriority@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:349:3844
Br@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:45023
Kr@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:45261
Gr@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:45194
N@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:114343
$t@http://localhost/cvat-ui.b7bb8e626f20982c98d1.min.js:341:22725

 CVAT version

    Server:
    Core: 3.10.0
    Canvas: 2.2.1
    UI: 1.13.3

**Comment by nmanovic** [comment]
@vibhubithar , please read documentation how to run CVAT: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#mac-os-mojave. You cannot run cvat_ui only. It will not work.

I will close the issue. Don't hesitate to reopen if you think that my answer isn't enough.
