### ISSUE TITLE
Enforce a minimun BB size

### ISSUE THREAD

**Issue by yohayonyon** [openvinotoolkit/cvat#2825]
### My actions before raising this issue
- [v] was told by @azhavoro that it does not exist
- [v] Searched [past issues](/issues)

### Expected Behaviour

Upon labels definition the user may define a minimum size for each label. After doing so, the annotators will not be able to save smaller BBs.

### Current Behaviour

There is no way to enforce a minimum size.

### Possible Solution

A field may be added to the labels file. If a shape is smaller that the given values, the user will get an error when annotating it.

### Context

Too small objects are useless for our project and consumes annotators time.

### Your Environment

- Git hash commit (`git log -1`): v1.2.0
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.2
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem: NA
- Other diagnostic information / logs: NA
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by nmanovic** [comment]
@yohayonyon , for now you can use GRID feature which will help you to estimate the object size. Also you can see the size of the bounding boxes. I'm not sure that we are going to complete the UI and have an option to specify the limit size of bounding boxes. In the training script you can always mark small bounding boxes as ignored. It is better than just remove them. If by a reason you net can detect them, it will not be penalised.

![image](https://raw.githubusercontent.com/openvinotoolkit/cvat/develop/cvat/apps/documentation/static/documentation/images/image068_mapillary_vistas.jpg)

I will close the feature request. If we see that community wants to have the feature (more requests from other users), I will reopen it. If you have a good idea how to implement the feature and are ready to contribute, you are welcome to send us a PR.
