### ISSUE TITLE
Error: "Could not get formats from the server"

### ISSUE THREAD

**Issue by ericmjl** [openvinotoolkit/cvat#2834]
### My actions before raising this issue

- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

cc: @RaphaelThierry

### Expected Behaviour

Clicking on "Dump annotations" and "Export as a dataset" do nothing. We are referring to the following menu:

![image](https://user-images.githubusercontent.com/2631566/108529364-6766f080-72a2-11eb-8bcd-6403cc7f9b74.png)

### Current Behaviour

When my colleague @RaphaelThierry and I try running CVAT on a Kubernetes cluster, we found that the CVAT UI would raise the following error:

![image](https://user-images.githubusercontent.com/2631566/108528847-dabc3280-72a1-11eb-9299-8ba4d369935b.png)

While we get the "models" error (there are no models loaded), however, we are not quite sure why the "formats" error is showing up. 

We went digging around online, and saw a related [StackOverflow question](https://stackoverflow.com/questions/60316150/cvat-computer-vision-annotation-tool-export-impossible), in which we noticed that there are calls to the API:

```
<ip_addr>:<port>/api/v1/server/dataset/formats
```

However, when we look into the Django REST APIs available at `<ip_addr>:<port>/api/v1/`, the `server/` endpoint is not available:

![image](https://user-images.githubusercontent.com/2631566/108529131-2a9af980-72a2-11eb-8151-8246f3bd530d.png)

### Possible Solution

We aren't quite sure what a solution might be, but maybe some guidance on which container serves up the `/server` endpoint might help us narrow the problem further.

### Steps to Reproduce (for bugs)

It may be hard for us to provide exact steps, as we have deployed this on a private K8s cluster, but if there's a specific point you'd like to know, we can dig around. Have to admit, neither of us we're not pros with k8s.

### Context

Our test-drive of CVAT on local machines has been pretty awesome, and so we wanted to scale it to multiple users across multiple continents, particularly for the annotation UI.

### Your Environment

The containers we are using are:

- `postgres:10-alpine`
- `nginx:stable-alpine`
- `redis:4.0-alpine`
- `onepanel/cvat-ui:0.17.0_cvat.1.0.0
- `skxogh252/cvat:latest`

The reason we were pulling in others' containers is because we otherwise would have to build it on our own, and we thought of leveraging others' pre-built containers first.

The logs were quite verbose, kudos! Is there a specific keyword we should look for? We can go digging in for those.

**Comment by nmanovic** [comment]
@ericmjl , you need to look at swagger documentation for your instance. For example, https://cvat.org/api/swagger/. You will see that actually /api/v1/server/dataset/formats exists. If you cannot provide steps to reproduce, we will not be able to help here. 

Please provide instructions to reproduce, otherwise we will close the issue after some time.

**Comment by nmanovic** [comment]
@ericmjl , I will close the issue. Need more information from you. Don't hesitate to reopen it if you can provide more information to reproduce the issue on our side.
