### ISSUE TITLE
[Bug] Message "Error validating field attributes.0.values" displayed when is reopening created label.

### ISSUE THREAD

**Issue by DmitriyOparin** [openvinotoolkit/cvat#2841]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Error message does not displayed.
Creating label can be save.

### Current Behaviour

Error message displayed.
Creating label can not be save.

### Possible Solution

Fix this bug.

### Steps to Reproduce (for bugs)

1. Click 'Create new task'
1. Click 'Add label'
1. Write label name 
1. Click 'Add an attribute'
2. Write attribute name 
3. Select type attribute - 'Number'
4. Write value attribute  - 1;10;2
5. Click 'Done'
6. Click on 'Update Attributes' on created label
7. Click 'Done'

### Your Environment

- Git hash commit (`git log -1`): 16d7f3ce016a45636ea419f24c8b34284765fb28
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

![image](https://user-images.githubusercontent.com/35344996/108601713-01b45a80-73af-11eb-80bf-10e836c84027.png)

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by ZahraAnam** [comment]
Apparently, it's something with commas apparently, I copied the raw file put it to the other project made changes, and pasted it back. It's not trivial but works.

**Comment by bsekachev** [comment]
That was fixed. I am not sure about the patch where it was done, but in the current develop it is not reproducable.
