### ISSUE TITLE
installation_automatic_annotation.md guide needs to update to reflect the path change in develop branch

### ISSUE THREAD

**Issue by waterfall414** [openvinotoolkit/cvat#2843]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

installation_automatic_annotation guide needs to update to reflect the path change

### Expected Behaviour

Follow the guide and load dextr model into cvat
### Current Behaviour

nuctl complaints it can't find Python exe if I strictly follow the steps in guideline
### Possible Solution

Instead of running
```
nuctl deploy --project-name cvat \
  --path serverless/openvino/dextr/nuclio \
  --volume `pwd`/serverless/openvino/common:/opt/nuclio/common \
  --platform local
```
run
```
nuctl deploy --project-name cvat \
  --path serverless/openvino/dextr/nuclio \
  --volume `pwd`/serverless/common:/opt/nuclio/common \
  --platform local
```

**Comment by nmanovic** [comment]
@waterfall414 , thanks for the report. Do you think you can send us a PR with the fix inside documentation?

**Comment by waterfall414** [comment]
@nmanovic, no problem. Just created one in https://github.com/openvinotoolkit/cvat/pull/2847
