### ISSUE TITLE
Expose interpolation as an API

### ISSUE THREAD

**Issue by kunaltyagi** [openvinotoolkit/cvat#2848]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Allow custom interpolations to be performed via API

### Expected Behaviour

There are several models that can track objects over multiple seconds. It makes sense to take advantage of them to reduce effort for annotation. An annotation API (similar to current automatic detection API) would be quite nice.

### Current Behaviour

Simple linear interpolations are performed between KeyFrames. No way to extend the functionality.

### Possible Solution

Interpolation API could be
* Request: for annotation of frame X or X1 to X2
* Result: annotations for frame(s)

The API will be free to use the CVAT API to get the following information:
* tracks (if they exist) from frames {X-Y to X+Y}
  * differentiate between auto-annotated and manually annotated tracks

Optionally, CVAT should assist in merging multiple annotations (for frames with existing manual annotation). This would need a visual indication of frames which require attention as well as the ability to:
* allow user to manually choose between them OR
* allow user to perform auto-merge (choose between new or pre-existing annotation)
### Context

Automatic annotation if done frame-by-frame could give sub-par results. Models with multi-frame dependence are getting better (and easier to train), and there should be a way to integrate them in the workflow, explicitly, specially since the current auto-annotation API doesn't promise any dependence between requests.

**Comment by tralfamadude** [comment]
I would like to add that there are many simpler things that would be useful as an API. 

In my case, I really would like an API that could inspect project, tasks, jobs, and fetch annotations. It could start out being just API analogues of those operations in the web UI. Examples: Get list of tasks that are completed, or  Fetch annotations for a particular task.

**Comment by nmanovic** [comment]
@kunaltyagi , you can try to use tracker AI serverless function for the purpose. An example, can be found here: https://github.com/openvinotoolkit/cvat/tree/develop/serverless/pytorch/foolwood/siammask/nuclio

We are not going to expose interpolation as an API for now.
