### ISSUE TITLE
'reduce_task_visibility' option not applied

### ISSUE THREAD

**Issue by zmfkzj** [openvinotoolkit/cvat#2849]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

1. I set settings.RESTRICTIONS['reduce_task_visibility']=True and  signed in with an unauthorized account. I can see and change everything, that is, the settings do not apply.
2. Job assignee list changes every refresh.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@zmfkzj Most likely you did not rebuild the cvat images

**Comment by nmanovic** [comment]
@zmfkzj , I will close the issue. Don't hesitate to reopen, if you think that the answer from @azhavoro doesn't work for you.

**Comment by omersefaztrk** [comment]
@zmfkzj @nmanovic @azhavoro I did not solve this problem. I changed `reduce_task_visibilty` as True in **base.py**. Then I builded cvat with `docker compose up -d` but it was not work. As ı understand it, i did not rebuild. How can I handle it?

**Comment by azhavoro** [comment]
@zmfkzj `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`
