### ISSUE TITLE
Add possibility to not copy files when using share files and cli

### ISSUE THREAD

**Issue by iraadit** [openvinotoolkit/cvat#2862]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched #2377 #204

### Expected Behaviour
PR #2377 will allow to not copy files inside CVAT when creating a task using share files.
It should be possible to do it through cli too.

### Current Behaviour
Impossible to use the cli to not copy files inside CVAT when creating a task using share files.

### Possible Solution
Implement the use of cli to not copy files inside CVAT when creating a task using share files.

### Context
I use the CLI to automatically add a large number of video tasks to CVAT.
Currently, all this data is copied in CVAT, even if it is freely available in the CVAT share folder (that is a Minio bucket on the same server); hence using double space "for nothing".
Not copying the data would allow to avoid wasting space and speed the upload of tasks on CVAT.
I mentioned my situation [here](https://github.com/openvinotoolkit/cvat/pull/2377#issuecomment-783381218) and @Marishka17 asked me to create an issue concerning it.

**Comment by yohayonyon** [comment]
When using the "Connected file share" on the create task screen (or by CLI) and using a tar file, the data is copied to server. Checking or unchecking "Copy data into CVAT" just changes the location of the data - in raw directly or in folders under it.
![Screenshot-from-2021-09-22-19-28-59](https://user-images.githubusercontent.com/61744528/135240764-a91b4d5a-68ca-4441-bf9d-175903a85e03.png)
![Screenshot-from-2021-09-22-19-30-21](https://user-images.githubusercontent.com/61744528/135240769-92f24575-6490-4895-9cc8-70db138eb34d.png)
![Screenshot-from-2021-09-22-19-31-46](https://user-images.githubusercontent.com/61744528/135240772-c5f311f1-23b8-4e64-a0ef-e92a422e59b2.png)

**Comment by yohayonyon** [comment]
https://github.com/openvinotoolkit/cvat/issues/3763 was opened.

**Comment by nmanovic** [comment]
It looks like the issue was resolved. I will close it.
