### ISSUE TITLE
The doubling of the cuboids to redraw.

### ISSUE THREAD

**Issue by dvkruchinin** [openvinotoolkit/cvat#2873]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
When redrawing the cuboid, the number of shape does not increase.

### Current Behaviour
When redrawing the cuboid, the shape is doubled.

### Possible Solution
Fix the bug.

### Steps to Reproduce (for bugs)

1. Draw a cuboid.
2. Press Shift+N above it to start redrawing.
3. Redraw the cuboid.

### Your Environment

- Git hash commit (`git log -1`): 45a0530facf024e14a596c373babb38768069c28
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.2
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@vnishukov 

Please, look at the issue. Need to fix it till March, 31st.

**Comment by Rose-we** [comment]
why become double polygons in cvat annotation when I draw just one polygon and go to next frame... Step back to frame it become double ? Any solution

**Comment by bsekachev** [comment]
@Rose-we 

If you believe it is a bug, please create another issue and provide more information:
- Git hash commit
- Exact steps to reproduce
- Does it happen stable or sometimes?
- Gif with reproducing
Etc. We will try to investigate.
