### ISSUE TITLE
cvat_proxy ... error

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/cvat#2892]
Status: Downloaded newer image for nginx:stable-alpine
Creating cvat_redis ... done
Creating cvat_db    ... done
Creating cvat       ... done
Creating cvat_ui    ... done
Creating cvat_proxy ... error

ERROR: for cvat_proxy  Cannot start service cvat_proxy: failed to create endpoint cvat_proxy on network cvat_default: failed to add the host (vethf730fa1) <=> sandbox (veth95d5f7e) pair interfaces: operation not permitted

ERROR: for cvat_proxy  Cannot start service cvat_proxy: failed to create endpoint cvat_proxy on network cvat_default: failed to add the host (vethf730fa1) <=> sandbox (veth95d5f7e) pair interfaces: operation not permitted
ERROR: Encountered errors while bringing up the project.

**Comment by azhavoro** [comment]
@monkeycc Please specify your environment

**Comment by monkeycc** [comment]
Linux version 5.10.5-amd64-desktop+ (deepin@deepin-PC) (gcc (Uos 8.3.0.3-3+rebuild) 8.3.0, GNU ld (GNU Binutils for Uos) 2.31.1) #1 SMP Mon Jan 11 14:55:28 CST 2021

cat /etc/debian_version
10.7

cat /etc/os-release
PRETTY_NAME="Deepin 20.1"
NAME="Deepin"
VERSION_ID="20.1"
VERSION="20.1"
ID=Deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="https://bbs.deepin.org/"

uname -a
Linux mmmm-PC 5.10.5-amd64-desktop+ #1 SMP Mon Jan 11 14:55:28 CST 2021 x86_64 GNU/Linux


NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1 


          .';;;;;.       .,;,.            OS: Deepin 20.1
       .,;;;;;;;.       ';;;;;;;.         Kernel: x86_64 Linux 5.10.5-amd64-desktop+
     .;::::::::'     .,::;;,''''',.       Uptime: 9h 52m
    ,'.::::::::    .;;'.          ';      Packages: 2371
   ;'  'cccccc,   ,' :: '..        .:     Shell: bash
  ,,    :ccccc.  ;: .c, '' :.       ,;    Resolution: 4480x1440
 .l.     cllll' ., .lc  :; .l'       l.   DE: Deepin 20.1
 .c       :lllc  ;cl:  .l' .ll.      :'   WM: KWin
 .l        'looc. .   ,o:  'oo'      c,   GTK Theme: deepin-dark [GTK2/3]
 .o.         .:ool::coc'  .ooo'      o.   Icon Theme: bloom
  ::            .....   .;dddo      ;c    CPU: Intel Core i7-9750H @ 12x 4.5GHz
   l:...            .';lddddo.     ,o     GPU: GeForce RTX 2060
    lxxxxxdoolllodxxxxxxxxxc      :l      RAM: 4699MiB / 15878MiB
     ,dxxxxxxxxxxxxxxxxxxl.     'o,      
       ,dkkkkkkkkkkkkko;.    .;o;        
         .;okkkkkdl;.    .,cl:.          
             .,:cccccccc:,.

**Comment by azhavoro** [comment]
CVAT supports only Ubuntu only Linux distro and I'm sure that is not CVAT issue, so please make sure that Docker is correctly installed on your system and works well, try to run `docker run hello-world`. The `cvat_proxy` container is just Nginx image with specific config, so try to run Nginx container https://hub.docker.com/_/nginx with ` docker run --name some-nginx -d -p 8080:80 some-content-nginx` command, then you can hit http://localhost:8080 or http://host-ip:8080 in your browser.
