### ISSUE TITLE
Update cvat-core/tests/internal/filter.js with new annotation filters functionality

### ISSUE THREAD

**Issue by vnishukov** [openvinotoolkit/cvat#2894]
This test was deleted in https://github.com/openvinotoolkit/cvat/pull/2871 because of completely new filters realization

**Comment by nmanovic** [comment]
@dvkruchinin , do we have tests for filters? If we don't, please add a couple of them. I will close the issue for now.

**Comment by dvkruchinin** [comment]
> do we have tests for filters?

@nmanovic 
We have tests for filters.
