### ISSUE TITLE
context "ompose" does not exist

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/cvat#2896]
**docker-compose down**
Stopping cvat_ui    ... done
Stopping cvat       ... done
Stopping cvat_proxy ... done
Stopping cvat_db    ... done
Stopping cvat_redis ... done
Removing cvat_ui    ... done
Removing cvat       ... done
Removing cvat_proxy ... done
Removing cvat_db    ... done
Removing cvat_redis ... done
Removing network cvat_default

**docker -compose -f docker-compose.yml -f components / serverless / docker-compose.serverless.yml up -d**

**unable to resolve docker endpoint: context "ompose" does not exist**

**Comment by azhavoro** [comment]
Please fill the issue template with exact steps to reproduce your issue on Ubuntu Linux

**Comment by lgg** [comment]
You miss typed and have redundant space here
![image](https://user-images.githubusercontent.com/12018713/109698510-87e75280-7ba0-11eb-8c9f-21bb5a4e9530.png)


`docker -compose -f docker-compose.yml -f components / serverless / docker-compose.serverless.yml up -d`

You typed: `docker -compose` instead of `docker-compose`

**Comment by lgg** [comment]
@monkeycc please, close this issue

**Comment by bsekachev** [comment]
Thank you @lgg 

@monkeycc I will close the issue.

**Comment by monkeycc** [comment]
https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation_automatic_annotation.md

To bring up cvat with auto annotation tool, from cvat root directory, you need to run:

docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
If you did any changes to the docker-compose files, make sure to add --build at the end.
