### ISSUE TITLE
Update documentation about review mode

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#2899]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context
If two issue tags created at the same place it was impossible to access on of them (#2607).
To fix the behavior we've added the feature of scrolling these tags by mouse wheel (#2868) as shown on the gif below. 
Need to hover cursor under an issue and use wheel your mouse. We should add a piece of information about it to our user guide

![Peek 2021-03-03 13-48](https://user-images.githubusercontent.com/40690378/109794939-71d0a500-7c27-11eb-96e5-3cd13e76c7ca.gif)

**Comment by nmanovic** [comment]
@TOsmanov , could you please check that it is covered by our documentation? If it is not, please add corresponding information. I will close the issue.
