### ISSUE TITLE
Support exporting of projects as datasets

### ISSUE THREAD

**Issue by zhiltsov-max** [openvinotoolkit/cvat#2911]
As well as tasks, projects in CVAT should be available for exporting as datasets in various formats.

Requirements:
- Ability to export a project as a dataset
- Several export options and parameters can be provided (inclusion of images, format-specific things)
- Tasks inside of a project should be joined (TBD: propose a naming convention for images and videos)
- Tasks inside of a project can be classified into subsets

**Comment by chaoyifei** [comment]
await

**Comment by zhiltsov-max** [comment]
@chaoyifei, do you agree with the requirements above? If you have own considerations, you are welcome to share them.

**Comment by chaoyifei** [comment]
> @chaoyifei, do you agree with the requirements above? If you have own considerations, you are welcome to share them.

Ability to dump  a project as annotations

**Comment by shaojun** [comment]
this is a important feature that can save lots of time, for now, I have to manually merge tasks' export.
but I can think one potential issue that different tasks may contain the images files with the same name, then the tasks combine(merge) will have problems.

so just wonder, does the software support file auto renaming when importing assets(image of video files) files? at least I can see for every new tasks, the video files uploaded are all split with frames `PNG` files with name like `frame_00000n`, that cause image file name collision across different tasks, then I can't merge them together for form the final full dataset.

**Comment by zhiltsov-max** [comment]
@shaojun, thank you for joining this discussion! 

Right, it is good that you noticed this problem with same names of images. I have few comments on this topic.

1. About manual merging. Have you tried using Datumaro for this? https://github.com/openvinotoolkit/datumaro/issues/112#issuecomment-783645671

2. About naming. I, personally, see few ways to resolve:
  - on export, add a prefix for task images. On import, do the opposite. Looks like the most simple and natural way for me.
  - on export, rename all the images using a pattern like `frame_xxx`. Impossible to import.
  - on creation, allow to rename images in a specific way
  - allow to (batch) rename images by request

**Comment by Okoyl** [comment]
Please implement this feature.

**Comment by Saharkakavand** [comment]
Dear @nmanovic , 
Would you let me know if I can save the data , so that the labels are in int16 using the cvat tool?
I have a cell dataset, that I want to use them for instance segmentation for Stardist and EmbedSeg networks.
Thanks
