### ISSUE TITLE
"Projects" module does not appear on top of the page after installing

### ISSUE THREAD

**Issue by schliffen** [openvinotoolkit/cvat#2912]
I noticed that there are four modules; "Projects", "Models", "Tasks", "Analytics" appearing on top of the cvat page in cvat.org, however in my case, I can't see the module "Projects". 
I used the docker version and the installation was according to the guidelines. I installed cvat about 4 months ago.
environment:
os: ubuntu 18.04
docker version: 19.04.13
Projects is a very useful feature for me as I am using CVAT to manage several projects at the same time.

**Comment by azhavoro** [comment]
@schliffen Please fill the issue template.

**Comment by nmanovic** [comment]
Probably your version of code doesn't have the feature. I will close the issue. If you can provide more details and you are sure that it is a problem with CVAT, don't hesitate to reopen.
