### ISSUE TITLE
AI Tool Error: "state label" is expected to be Label, but "undefined" has been go

### ISSUE THREAD

**Issue by toddlerya** [openvinotoolkit/cvat#2913]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

all container and service is ok.

- cvat version
![image](https://user-images.githubusercontent.com/5418150/110135675-c0d63000-7e09-11eb-8798-64ca82758a56.png)

- docker container is ok
![image](https://user-images.githubusercontent.com/5418150/110135737-d4819680-7e09-11eb-8a08-373cf994c5bb.png)

- nuclio and functions is ok
![image](https://user-images.githubusercontent.com/5418150/110135839-f24efb80-7e09-11eb-8afd-6aa8aef59df0.png) 
![image](https://user-images.githubusercontent.com/5418150/110135915-085cbc00-7e0a-11eb-8d60-4643e93a8b2b.png) 
![image](https://user-images.githubusercontent.com/5418150/110136114-45c14980-7e0a-11eb-963b-2bd0fc00a769.png)
![image](https://user-images.githubusercontent.com/5418150/110136376-946ee380-7e0a-11eb-8fa4-90428418ea44.png)

- auto annotation is ok.
![image](https://user-images.githubusercontent.com/5418150/110136500-b8cac000-7e0a-11eb-8c1d-fbb50fb46013.png)

but after finish auto annotation, no label data, no draw rectangle in the video! so I'm open the task use the left slide bar "AI Tools" , an error occured!
![image](https://user-images.githubusercontent.com/5418150/110136842-224ace80-7e0b-11eb-94db-a558232aae98.png)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
```
commit 37d82f90052ab26c584dfb2c87a4623cb22e0ff4 (HEAD, tag: v1.2.0)
Merge: 8eb7c136 da4efddd
Author: Nikita Manovich <nikita.manovich@intel.com>
Date:   Fri Jan 8 19:06:27 2021 +0300

    Merge branch 'release-1.2.0'
```

- Docker version `docker version` (e.g. Docker 17.0.05): 

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Are you using Docker Swarm or Kubernetes? --> No
- Operating System and version (e.g. Linux, Windows, MacOS): --> MacOS 11.1
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    no error, but has some warning:
```
2021-03-05 15:10:04,297 DEBG 'runserver' stderr output:
WARNING:root:Failed to import module 'coco_format.converter.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

2021-03-05 15:10:04,538 DEBG 'runserver' stderr output:
WARNING:root:Failed to import module 'coco_format.extractor.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

2021-03-05 15:10:04,543 DEBG 'runserver' stderr output:
WARNING:root:Failed to import module 'datumaro_format.converter.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

2021-03-05 15:10:04,546 DEBG 'runserver' stderr output:
WARNING:root:Failed to import module 'transforms.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi @toddlerya 

Please, be acquainted with my [previous reply](https://github.com/openvinotoolkit/cvat/issues/2747#issuecomment-775379931) and corresponding thread.  Looks like issue might be the same and already fixed (need to update CVAT only). Let us know additionally if it does not help.

**Comment by toddlerya** [comment]
> Hi @toddlerya
> 
> Please, be acquainted with my [previous reply](https://github.com/openvinotoolkit/cvat/issues/2747#issuecomment-775379931) and corresponding thread. Looks like issue might be the same and already fixed (need to update CVAT only). Let us know additionally if it does not help.

yes, This way is effective :  https://github.com/openvinotoolkit/cvat/issues/2747#issuecomment-786389222

**Comment by bsekachev** [comment]
@toddlerya 

If you don't use projects, yes. If you do, the only way is to update CVAT. Can we close the issue?

**Comment by toddlerya** [comment]
> @toddlerya
> 
> If you don't use projects, yes. If you do, the only way is to update CVAT. Can we close the issue?

OK，Please close the issue.
