### ISSUE TITLE
请增加图像上任意形状的文本分割+文本内容识别标注功能，谢谢

### ISSUE THREAD

**Issue by gengyanlei** [openvinotoolkit/cvat#2917]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@gengyanlei , please submit your feature request in English.

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/110404387-b93cb280-80b9-11eb-96c3-3452ace28418.png)
