### ISSUE TITLE
Dumping annotations or exporting dataset via web UI hangs forever

### ISSUE THREAD

**Issue by ericchen321** [openvinotoolkit/cvat#2919]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Dataset or annotations should pop up as a zip file to be downloaded from Chrome.

### Current Behaviour
Nothing pops up. The menu entry for the format selected stays gray forever:

![image](https://user-images.githubusercontent.com/22675300/110391064-cc994080-801b-11eb-8941-baf14343eb07.png)

### Possible Solution
[A previous issue](https://github.com/openvinotoolkit/cvat/issues/2330#issue-723986131) suggested using `wget` to download the file. But I am not sure exactly how I should provide authentication info to `wget`. 

### Steps to Reproduce (for bugs)

1. Creat a project, then a task
2. Upload images
3. Create annotations
4. Export dataset or dump annotations as any format (YOLO/Pascal-VOC/...)

### Your Environment

- CVAT Web UI
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04 + Chromium browser
- Other diagnostic information / logs: Task ID is 53979. Tried dumping annotations from other tasks for which I could export a couple days ago and did not work either. So I am sure this is not a task-specific issue.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by ericchen321** [comment]
Never mind, just had files showing up and I was able to download them successfully. Guess it was just a temporary service disruption.

**Comment by joao-dourado** [comment]
Hi, I having the exact issue you described, for days now, when the downloads starts the file I get is missing several annotations, I have annotated around 30k instances, but the file only has like 10k. And sometimes it only continues loading forever.
