### ISSUE TITLE
Serverless function for text segmentation and recognition

### ISSUE THREAD

**Issue by gengyanlei** [openvinotoolkit/cvat#2920]
![image](https://user-images.githubusercontent.com/22360785/110404494-e8ebba80-80b9-11eb-8bc3-0092e4a64aae.png)

**Comment by zhiltsov-max** [comment]
It looks like it can be done by adding a custom auto-annotation model.

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/110464922-b8823b80-810e-11eb-89c8-17b3504dc92d.png)

**Comment by nmanovic** [comment]
@gengyanlei , we have a serverless function to detect text: https://github.com/openvinotoolkit/cvat/tree/develop/serverless/openvino/omz/intel/text-detection-0004/nuclio.

Do you need something else? Could you please specify a DL model which you need?

**Comment by gengyanlei** [comment]
tks，
we need draw a ploygon(eg: bbox, segmentation-any shape), then manually identify and label the text in the area。

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/110562286-2c126000-8184-11eb-9713-13649b0d7c28.png)

bbox or sgementation-coordinate and text-label

**Comment by gengyanlei** [comment]
like https://github.com/vandyyu/dataset_labeling , but it is not convenient to operate. 
tks.

**Comment by nmanovic** [comment]
@gengyanlei ,

You can create a task with your images. Create a label inside the task with an attribute with type text:

![image](https://user-images.githubusercontent.com/40690625/110577534-e057ba80-8173-11eb-9354-55a255b05102.png)


After that you can use Text Detection v4 model to detect text automatically and manually add text value for each shape as a text attribute.

![image](https://user-images.githubusercontent.com/40690625/110577372-91118a00-8173-11eb-88d4-d7166757dff3.png)


What don't work for you in the scenario?

**Comment by gengyanlei** [comment]
ok，tks，but it is not friendly to Chinese.

**Comment by gengyanlei** [comment]
ok，tks，but it is not friendly to Chinese.

**Comment by nmanovic** [comment]
@gengyanlei , is it working for you now? I will close the issue. If you still have problems with Chinese text, please create another issue for the problem. The issue was resolved I believe.
