### ISSUE TITLE
Custom model for automatic annotation

### ISSUE THREAD

**Issue by valavanisleonidas** [openvinotoolkit/cvat#2926]
Hello, I have seen many issues asking this but I am not sure about the answer. 

I have some data and I want to train my own model to annotate. Is it possible to do that? If so, are there instructions somewhere on how to do that? 

Also is there a specific framework required for training i.e. pytorch, tensorflow?

Thanks

**Comment by nmanovic** [comment]
@valavanisleonidas , please read the tutorial: https://github.com/openvinotoolkit/cvat/pull/3124. The PR should be merged soon. In any case the tutorial has necessary information already now.

https://github.com/openvinotoolkit/cvat/blob/49e4875dad6d2b61d306078f25d05e69dab97f50/site/content/en/docs/manual/advanced/serverless-tutorial.md
