### ISSUE TITLE
Can you configure multiple file sharing

### ISSUE THREAD

**Issue by newliufeng** [openvinotoolkit/cvat#2930]
Can you configure multiple file sharing
volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/qj/cvat/cvat/biaozhu
      o: bind

**Comment by nmanovic** [comment]
@newliufeng , at the moment you cannot  attach multiple shares to your server. But you can workaround the issue. Create a directory and mount all your shares into it (or create soft links). Attach the directory to CVAT server. It should work.

I will close the issue for now.
