### ISSUE TITLE
LabelMe 3.0 format not correct

### ISSUE THREAD

**Issue by Once88** [openvinotoolkit/cvat#2938]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am using the develop branch of cvat. When I dumped a dataset in the format of LabelMe 3.0, I found the format was not correct.

### Expected Behaviour

The label file of "a.jpg" should be "a.xml"
The label file of "b.jpg" should be "b.xml"
......

### Current Behaviour

The label file of "a.jpg" is "item_000000000.xml"
The label file of "b.jpg" is "item_000000001.xml"
......

### Steps to Reproduce (for bugs)

1. create a task
2. label images
3. select Menu->Export as dataset -> LabelMe 3.0

**Comment by zhiltsov-max** [comment]
This behaviour is intended, check https://github.com/openvinotoolkit/datumaro/issues/17. TL;DR: the reason is support of relative image paths in a dataset.

**Comment by zhiltsov-max** [comment]
@Once88, if you have experience with this format, could you advice on the following question:

If a task has image paths like:
```bash
./c.jpeg
./a/b/c.jpg
./a/b/c.png
./a/b/d.jpg
```

How the resulting dataset should look like? What would you expect as a result?

**Comment by Once88** [comment]
@zhiltsov-max, I don't have a perfect solution to the question you mentioned. 

But some open source projects or existing projects read annotation files by the name of relative image filename with a different suffix, without reading the `<filename>` field inside the XML. So we need to do a lot of work to convert the annotation filenames.

Make importing more convenient or exporting more convenient? I think there is a trade-off here.

**Comment by zhiltsov-max** [comment]
Thanks for sharing your point. How do you think, if we exported a dataset above like this:

```bash
./c.jpeg
./c.xml
./a/b/c.jpg
./a/b/c.xml
./a/b/c.png
./a/b/c.png.xml
./a/b/d.jpg
./a/b/d.xml
```

Would such solution be satisfying?
