### ISSUE TITLE
500 Server Error Dumping Big Dataset

### ISSUE THREAD

**Issue by fede-citti** [openvinotoolkit/cvat#2939]
We are working on a segmentation task with a big dataset. To avoid problems with the GUI, we are using CLI to upload/dump the annotations. 
We successfully loaded the images and the annotations, but the dump operation fails due to a Server Error.

### Expected Behaviour
When executing the following code on the terminal, we expect a zip file containing the masks to be created in the local folder.
`python3 cli.py  dump --format "Segmentation mask 1.1" 17 output.zip`
This successfully happens for tasks containing few small images.

### Current Behaviour
When we dump the annotations, process starts correctly and many messages "Status 202" are shown on the terminal, then it stops with the following error: "500 Server Error: Internal Server Error"
![image](https://user-images.githubusercontent.com/47630971/110759927-719b5f80-824e-11eb-99ec-d8684486347b.png)

### Possible  @Issues/Considerations
1. Images are quite big: on average 7'000x3'000 pixels, biggest image is 12'000x6'000 pixels.
2. Annotations are very complex: there may be many of them (up to 255 polygons per image) and the polygons may have many vertices. This one is an example:
![image](https://user-images.githubusercontent.com/47630971/110762131-c4761680-8250-11eb-8ed4-d907aef3f93f.png)
3. During execution sometimes memory fills up. We have 30GB RAM + 100GB through a swap to disk. Disk is used up to 60GB but it never fills.

### Context
We are processing medical images that must be in high definition for the annotator to detect the areas of interest. Such areas can be very complex and detailed, this is why we have such big images and such complex annotations.

### Your Environment
We are using Ubuntu 20.4 and CVAT 1.2

**Comment by azhavoro** [comment]
@fede-citti Hi, please attach CVAT container logs: `docker logs cvat > cvat.log`

**Comment by zhiltsov-max** [comment]
Try to update to the current develop branch, where mask dumps were significantly optimized. Another option is to update only Datumaro library to 0.1.6 (`cvat/requirements/base.txt`) and rebuild the server.

https://github.com/openvinotoolkit/cvat/pull/2794
https://github.com/openvinotoolkit/datumaro/releases/tag/v0.1.6

**Comment by fede-citti** [comment]
@azhavoro This is CVAT container log
[cvat.log](https://github.com/openvinotoolkit/cvat/files/6122206/cvat.log)

**Comment by nmanovic** [comment]
@fede-citti , could you please confirm, that it was fixed in the latest develop branch?

**Comment by fede-citti** [comment]
Yes, thanks.
