### ISSUE TITLE
Missing import format: CVAT for images

### ISSUE THREAD

**Issue by Ursanon** [openvinotoolkit/cvat#2940]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Feature request

Importing option for dataset in `CVAT for images` format.

### Context

I want to be able to export images with groups, reorganize dataset and upload back to CVAT, everything in `CVAT for images` format.

**Comment by turowicz** [comment]
@jahaniam this would be of great help

**Comment by nmanovic** [comment]
@Ursanon , please let me check my understanding. You want to be able to backup a task and after that be able to restore it. Right?

**Comment by Ursanon** [comment]
@nmanovic Sometimes I want to edit exported task without losing any part of annotation (for instance grouped items).
By edit I mean add new label, delete few images or verify dataset again.

**Comment by zhiltsov-max** [comment]
There is the `CVAT` format in the list of import formats, it covers both `for video` and `for images`.
