### ISSUE TITLE
Significantly more data being transferred than image size.

### ISSUE THREAD

**Issue by dreaquil** [openvinotoolkit/cvat#2941]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour
I would expect the task open time to be proportional to the image size.

### Current Behaviour
A single image task of size (image of size 297KB) is taking approximately 26s to download. The file size being downloaded is approximately 22.8MB. I don't understand why the file size is so much larger when there aren't even any annotations

![image](https://user-images.githubusercontent.com/32460579/110775957-70226500-8257-11eb-9804-a5774ac14332.png)

When I change task compression % down, this reduces the time to download but the file being downloaded is still significantly larger than the actually file (many times larger).

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

This greatly impact annotation speed because most of the annotation time is waiting for an annotation to load.

### Your Environment
I am running this on Azure over HTTPS. 
VM Size: Standard B2ms (2 vcpus, 8 GiB memory)
### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hi, could you attach the image?

**Comment by dreaquil** [comment]
Unfortunately, I can't as it is proprietary clinical data. This is all I can provide:
![image](https://user-images.githubusercontent.com/32460579/110778073-cabcc080-8259-11eb-948c-05f4437bd51c.png)

**Comment by azhavoro** [comment]
What is format of the original images?

**Comment by dreaquil** [comment]
It's a jpg.

**Comment by dreaquil** [comment]
Any thoughts on what I can look into?

**Comment by f3rm4rf3r** [comment]
@dreaquil Maybe completely unrelated but I found that for downloading the data faster (I know it is not your issue) creating a task [without cache and zip chunks](https://i.imgur.com/8WFGsjO.png) helped a lot. Maybe worth trying with a subset of your dataset in case you see any improvement.

**Comment by dreaquil** [comment]
@f3rm4rf3r Thanks for the suggestion. It seems like the Use Cache button in Task creation is inverted! This does not explain the large data transfer for a small image though.

Deleted browser cache with use cache setting enabled:
![image](https://user-images.githubusercontent.com/32460579/110826579-20f72700-828d-11eb-922e-60694b2be4dd.png)
Deleted cache with use cache setting disable:
![image](https://user-images.githubusercontent.com/32460579/110826628-2fddd980-828d-11eb-94ce-1a6b3dc1fb83.png)

With browser cache and use cache setting enabled:
![image](https://user-images.githubusercontent.com/32460579/110826907-73d0de80-828d-11eb-9946-16f8cafe7773.png)

With browser cache and use cache setting disabled:
![image](https://user-images.githubusercontent.com/32460579/110827278-d033fe00-828d-11eb-88e9-0b2256bcca50.png)

**Comment by dreaquil** [comment]
Any suggestions of what this issue may be and where to begin debugging it?

**Comment by azhavoro** [comment]
@dreaquil Hi,
Unfortunately, I cannot reproduce this problem. It is possible to get a block size larger than the uploaded image, especially if the quality parameter is high, because the uploaded images are recompressed inside the CVAT. In my experiments, the maximum difference was 3 times: save the image in jpeg format with quality 0 and create a task with it with quality = 100. Regarding your data, it looks very strange because the chunk size is larger than the uncompressed image size for 1600x1200 24 bit. Could you specify the options in which the task was created? Also could you make sure that downloaded chunk contains only 1 image (this is just zip archive)

**Comment by nmanovic** [comment]
@dreaquil , fill free to reopen the issue if you have any ideas how to reproduce the problem on our side.
