### ISSUE TITLE
Cannot enable OpenCV Tools

### ISSUE THREAD

**Issue by kotetsu-n** [openvinotoolkit/cvat#2942]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

On the online [demo](https://cvat.org/), there is an [OpenCV Tools](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/user_guide.md#opencv-tools) under AI Tools.  Can I enable it on my own environment? I've read the [documents](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation_automatic_annotation.md) but I cannot find any explanations about the function. 

### Your Environment
- Docker version 20.10.2, build 2291f61
- MacOS Big Sur v.11.2.2

**Comment by bsekachev** [comment]
hi @kotetsu-n,

You do not need additional actions to activate the tools. 
Just check your CVAT version, probably it is outdated. The feature is available since cvat-ui 1.14
