### ISSUE TITLE
Allow Siammask active tracker to run for more frames 

### ISSUE THREAD

**Issue by Hiddenfire21** [openvinotoolkit/cvat#2949]
### My actions before raising this issue
- [✓] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [✓] Searched [past issues](/issues)

### Expected Behaviour

Would like to suggest a new feature to include to allow user to set the number of frames the Siammask active tracker runs for. 
User should be able to:
1) choose number of frames to run the active tracker
2) run up to the next keyframe
3) run to the end of current track

### Current Behaviour

Currently the active tracker is fixed to running for 10 frames, to continue active tracking user has to run tracker again 

### Context

I am annotating a long video(900 frames) to create a tracking dataset.
The active works alright but has to be rerun every 10 frames.
Would like to be able to set the active tracker to run to the end of the video 

### Your Environment

cvat/develop 86eef84
Docker version 20.10.5, build 55c4c88

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by plato-ron** [comment]
I think this exists when you use the cvat siammask tracker (tracking frames option). You should also be able to set siammask to run until the end of the video by just setting the tracking frames to a large number (larger than the number of frames in the video) and it'll run until the end of the video.

**Comment by LucaBallan96** [comment]
Is it possible to specify the #frames on which the tracker has to run automatically?
Do I have to specify this in the function.yaml of SiamMask or TransT ?

Please help!

**Comment by lucidBrot** [comment]
> I think this exists when you use the cvat siammask tracker (tracking frames option). You should also be able to set siammask to run until the end of the video by just setting the tracking frames to a large number (larger than the number of frames in the video) and it'll run until the end of the video.

Where is this setting?

I've looked in the siammask repo's yaml files and in the CVAT gui, and haven't found it there.
