### ISSUE TITLE
Cvat_proxy (Nginx) does not track DNS changes (for example, the container with the upstream service has been restarted).

### ISSUE THREAD

**Issue by afonseca18** [openvinotoolkit/cvat#2951]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)

Restarting (expected or unexpected) of the one of CVAT upstream services may leads to 502 error on the client.

### Your Environment
I'm using Linux and the web version of CVAT on Google Chrome.

**Comment by DegardinBruno** [comment]
Same issue here!!
I'm resorting to the online version of cvat "cvat.org".
Is there anything we can do on the client-side?

**Comment by azhavoro** [comment]
Thanks for the report. Should be fixed now.
I will change the issue so that it stays open until the root cause is fixed.

**Comment by DegardinBruno** [comment]
Thank you very much!
And thanks for a great job with CVAT!

**Comment by afonseca18** [comment]
> Thanks for the report. Should be fixed now.
> I will change the issue so that it stays open until the root cause is fixed.

Thanks for your quick response. Great job!

**Comment by azhavoro** [comment]
fixed by #3409
