### ISSUE TITLE
Attribute order of labels deviates from that specified in original raw label definition

### ISSUE THREAD

**Issue by manybodycpa** [openvinotoolkit/cvat#2952]
When using the API to create tasks, I specify the label definition in a file. Specifically, I have

```
[
    {
        "name": "object",
        "color": "#24b353",
        "attributes": [
            {
                "name": "partial",
                "input_type": "radio",
                "mutable": true,
                "default_value": "undefined",
                "values": [
                    "undefined",
                    "no",
                    "left",
                    "right",
                    "other"
                ]
            },
            {
                "name": "readability",
                "input_type": "radio",
                "mutable": true,
                "default_value": "undefined",
                "values": [
                    "undefined",
                    "low",
                    "medium",
                    "high"
                ]
            }
        ]
    }
]
```
When opening the label definitions of a task in the CVAT GUI (Raw tab), I can see that each item has been supplemented with an id and that items are sorted by their id. (Am I correct to assume that the id determines the position of the attribute in a?)

Although I use exactly the same procedure and label file to create tasks, "partial" has a smaller id than "readability" for some of the tasks, whereas in other cases it is the other way around. This causes the attributes to be shown in different orders during annotation, creating a potential source for annotation mistakes, as shown in the screen shots.  (Am I correct to assume that the id determines the position of the attribute in annotation mode?)

![Screenshot from 2021-03-15 13-55-38](https://user-images.githubusercontent.com/51188795/111156772-6a4dbc00-8596-11eb-8768-5fd66a451c2d.png)
![Screenshot from 2021-03-15 13-55-24](https://user-images.githubusercontent.com/51188795/111156773-6ae65280-8596-11eb-9f8d-3b52003009cf.png)

I would like to understand if this problem can be avoided. I would also be interested in a workaround. Can I simply switch the IDs of two attributes in a task after the task has been created and (partially) annotated?

**System info:**

Server version: 1.2
Core version: 3.8.0
Canvas version: 2.1.2
UI version: 1.9.10

**Comment by nmanovic** [comment]
@azhavoro , it looks like a similar request. Don't forget to mention the issue in your PR.
