### ISSUE TITLE
All image-uploads on CVAT.org look cluttered

### ISSUE THREAD

**Issue by JFMeyer2k** [openvinotoolkit/cvat#2956]
Hello,

since yesterday evening all the images I uploaded to CVAT.org are cluttered .
I tried to upload again but same issue.
Any advise?

Cheers,
JFM

**Comment by azhavoro** [comment]
Hi, what is task id?

**Comment by JFMeyer2k** [comment]
Dear azhavoro,

it is #58745 and #58738

Thanks

**Comment by DegardinBruno** [comment]
Any updates? Same over here since yesterday.
It seems that all recent tasks are affected in terms of image quality (cluttered).

Thank you for your attention.

**Comment by JFMeyer2k** [comment]
Hey,

so far no - I am still waiting.

Thanks for posting.

**Comment by afonseca18** [comment]
Hi! 
Same issue here. I tried to upload a single image (just for testing), and it did not affect the image quality. However, when I tried to start my annotation project, it results in clutter again. 

Thanks.
