### ISSUE TITLE
Add switcher to polygon cut behaviour (auto cut - user choice)

### ISSUE THREAD

**Issue by nstolyarov** [openvinotoolkit/cvat#2961]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am trying to edit a polygon by holding down the shift key and drawing a line inside the polygon. This is how I try to cut off a part of the polygon. When I click on the last point of the new line, I want to select which part to keep. There is such a function and it is described in the User Guide, but in reality it works once in five. In other cases, a smaller part is removed. In doing so, I do the same thing.

![pic](https://user-images.githubusercontent.com/80746178/111302094-072a5b00-8664-11eb-8f59-0bfd83394f6c.jpg)

### Expected Behaviour
At the end of the polygon editing, it becomes possible to choose which part to leave.

### Current Behaviour
When you finish editing a polygon, the smaller part is removed almost always. In some cases it works correctly, but we haven't found such right conditions.

### Possible Solution
Fix this problem.

### Context

It is very important feature for our project.
### Your Environment
- Git hash commit (`git log -1`): commit 7a2dcfff61626dbfdaa694127fc1cff8ee10e000 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Anastasia Yasakova <anastasia.yasakova@intel.com>
Date:   Tue Mar 9 10:41:33 2021 +0300
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): GNU/Linux Ubuntu
4.15.0-136-generic
x86_64

**Comment by bsekachev** [comment]
Hi @nstolyarov

It is not a bug actually.
In the most of cases CVAT decides itself what part of polygon should be cut. Before we always left a choice for a user, but there were issues where users don't like the behavior #1579 #1515. 

Now it works in the following way:

> This PR introduces updated approach. Two criteria are computed to decide which part of a polygon should be cut during editing automatically. The first criteria is a number of cut points. The second criteria is a length of a cut curve. If both criteria recommend to cut the same part, algorithm works automatically, if not, a user asked to make a choice.

**Comment by nstolyarov** [comment]
Is it possible to add some toggle switch for choosing between smart and old version of editing?

**Comment by bsekachev** [comment]
@nstolyarov 

Yes, it is possible.

**Comment by jahaniam** [comment]
Thanks for having this . Choosing automatically was also annoying to me sometimes. Toggle helps.
