### ISSUE TITLE
CVAT Error saving my annotation

### ISSUE THREAD

**Issue by sarrahjoyyasay** [openvinotoolkit/cvat#2962]
Hi

I am having this error. What should I do?
<img width="243" alt="error" src="https://user-images.githubusercontent.com/80766994/111325122-5beec580-86a6-11eb-905a-72831037625e.PNG">

**Comment by bsekachev** [comment]
Hi @sarrahjoyyasay 

Are you working on CVAT.org or on your personal server?

**Comment by sarrahjoyyasay** [comment]
Personal Server

**Comment by bsekachev** [comment]
@sarrahjoyyasay 

Then please, fill out the issue template and provide approximate steps to reproduce (what actions have you done before?).

**Comment by azhavoro** [comment]
@sarrahjoyyasay any updates?

**Comment by nmanovic** [comment]
@sarrahjoyyasay , I will close the issue. Don't hesitate to reopen it if you can provide more details.
