### ISSUE TITLE
Add dataset URI to Task from CLI

### ISSUE THREAD

**Issue by dreaquil** [openvinotoolkit/cvat#2976]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Expected Behaviour

It would be useful to programmatically attach a  git repository for annotation synchronization. 

### Current Behaviour

Either cannot be done or the CLI is missing documentation on how to do it.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by dreaquil** [comment]
@azhavoro Is there any way to do this in some alternate way for an already create task? Perhaps through the swagger API?

**Comment by azhavoro** [comment]
Yes, it should be possible via `PATCH` request, but need to check.

**Comment by dreaquil** [comment]
Had a look in the patch request and couldn't see any variable that indicates the git repository.

![image](https://user-images.githubusercontent.com/32460579/111658847-a25a3680-8804-11eb-9439-6eed0712c794.png)

**Comment by azhavoro** [comment]
Correct, it is not implemented.

**Comment by azhavoro** [comment]
Looks like it should be possible with these endpoints that is not documented: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/dataset_repo/urls.py#L10-L15

**Comment by dreaquil** [comment]
Thanks! I'll have a look

**Comment by dreaquil** [comment]
@azhavoro What would be the full URL then?

**Comment by dreaquil** [comment]
Got it: `/git/repository/create/{task_id}`
