### ISSUE TITLE
Error when uploading annotations to task

### ISSUE THREAD

**Issue by GillesKap** [openvinotoolkit/cvat#2978]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When uploading coco annotations (in the form of a single .json file) I get the error 
```
Error: Request failed with status code 500. "TypeError: list indices must be integers or slices, not NoneType\n".
``` 
I have made sure that the format is correct by comparing it to the annotations that are created by CVAT when dumping them. 

### Expected Behavir

The annotations should be loaded in.

### Steps to Reproduce (for bugs)

Upload the annotations (see gist: https://gist.github.com/GillesKap/559824c4f4b2a93cfb002b674954516bhttps://gist.github.com/GillesKap/559824c4f4b2a93cfb002b674954516b)

Unfortunately I cannot share the dateset itself.

### Context

I want to upload automatically generated annotations and manually modify them where needed to ensure they are 100% correct.

### Your Environment

- Git hash commit (`git log -1`): d8ddf6a00eef41a33611d8be44dd939ecc4dc5c2
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.3, build 48d30b5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Hi, please check if this issue helps: https://github.com/openvinotoolkit/cvat/issues/2085

BTW, annotations are not available for downloading

**Comment by azhavoro** [comment]
@GillesKap Hi, have you solved the issue?

**Comment by GillesKap** [comment]
Yeah I have solved the issue since then. It wasn't an issue with CVAT but with my own code. 

 My category ID's started counting from 1 but the category ID's in the annotations didn't 
i.e. 
```
"categories": [
        {
            "id": 0,
            "name": "category",
            "supercategory": ""
        },\
 "annotations": [
        {
            "area": 822358.1058493332,
            "bbox": [
                46.157044956818694,
                488.76621303186,
                1965.5220212318432,
                418.3917030519659
            ],
            "category_id": 0,
            "id": 1,
            "image_id": 1,
            "iscrowd": 0,
            "segmentation": []
        },
```

So when CVAT looks for the correct category it can't find it which causes an index somehwere to be a NoneType.
