### ISSUE TITLE
Welcome to nginx?

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/cvat#2989]
docker-compose up -d
Creating network "cvat_default" with the default driver
Creating cvat_db    ... done
Creating cvat_redis ... done
Creating cvat       ... done
Creating cvat_ui    ... done
Creating cvat_proxy ... done

----------

docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
..
Superuser created successfully.

-----------

http://localhost:8080/

Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.
....

-----

What should we do now ？？

**Comment by azhavoro** [comment]
Hi, occasionally this error is happens, but the reason is unknown.
Looks like you built cvat images locally, try to rebuild with `--no-cache` option and make sure that build logs of `cvat_ui` don't contain errors.

**Comment by azhavoro** [comment]
@monkeycc Hi, any updates?
