### ISSUE TITLE
Fix polygon crop behaviour

### ISSUE THREAD

**Issue by nstolyarov** [openvinotoolkit/cvat#2990]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When drawing polygons, if you put a point outside the border of the image, after completing the shape, that point is projected onto the edge of the image. Because of this, the line attached to this point also moves out.
Video of the problem: https://drive.google.com/file/d/1U37pZPXsa4aJmCGS16DrlO6L92wAGYNg/view?usp=sharing
### Expected Behaviour
After the polygon with a point outside the image boundary is completed, the point is not projected, but the resulting shape is clipped along the image boundaries.

### Current Behaviour
After the polygon is finished, the points lying outside the image boundaries are projected onto the image boundaries.
### Possible Solution

Crop anything outside of the image.

### Context

Point projection changes the drawn shape, which is inconvenient.
### Your Environment
- Git hash commit (`git log -1`): commit 7a2dcfff61626dbfdaa694127fc1cff8ee10e000 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Anastasia Yasakova <anastasia.yasakova@intel.com>
Date:   Tue Mar 9 10:41:33 2021 +0300
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): GNU/Linux Ubuntu
4.15.0-136-generic
x86_64

**Comment by bsekachev** [comment]
Looks like issue title does not correspond to the issue description.

The problem from the description has been solved by #3048
The problem from the title is gonna be solved by #3070

I'll rename the issue and close it because it was already solved. 
We will merge the PR with shortcuts for labels ASAP

@nstolyarov FYI
