### ISSUE TITLE
Duplicating polygon at the same place

### ISSUE THREAD

**Issue by nstolyarov** [openvinotoolkit/cvat#2991]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

You can copy and paste polygons in CVAT. This helps us in cases when we mark one place with different classes. We need to be able to paste the copied polygon in exactly the same place. But when you insert a polygon, it snaps to the mouse cursor and moves away from its original position.

### Expected Behaviour
After pressing ctrl-v, the polygon is inserted exactly in the same place as the original.

### Current Behaviour
After pressing ctrl-v, the polygon snaps to the mouse cursor and moves.
### Possible Solution

Insert a polygon in exactly the same place by default, if necessary, drag it with the mouse from its original position.

### Context

When working with complex regions of segmentation, it can be useful to duplicate the polygon at the same place.

### Your Environment
- Git hash commit (`git log -1`): commit 7a2dcfff61626dbfdaa694127fc1cff8ee10e000 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Anastasia Yasakova <anastasia.yasakova@intel.com>
Date:   Tue Mar 9 10:41:33 2021 +0300
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): GNU/Linux Ubuntu
4.15.0-136-generic
x86_64

**Comment by bsekachev** [comment]
Hi, @nstolyarov 

What is usecase when you need the same polygon in exactly the same place?

**Comment by nstolyarov** [comment]
Hi, @bsekachev 

Here is the example below
https://drive.google.com/file/d/12fSvIVwvw5eBdaZKFDZHcdV8Rgyst86M/view?usp=sharing

**Comment by nmanovic** [comment]
@nstolyarov , As far as I know the automatic border solved the issue. Could you please confirm and close the issue in the case?

**Comment by nstolyarov** [comment]
Hi, @nmanovic!

You are right, the automatic bordering solved this issue. Thank you.

**Comment by wiekern** [comment]
Hi, I see that we can propagate a polygon to prev/next frames, however, I get accustomed to use copy/paste(Ctrl-c, Ctrl-v) to duplicate a polygon at same position. my question is that how could I implement this feature in an easy way? thanks
