### ISSUE TITLE
Update a documentation about annotation filters

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#2994]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Recently we have merged new implementation of annotation filters #2871. 
Now it uses UI components instead of raw string. Need to actualize the user guide.

**Comment by nmanovic** [comment]
@aschernov, could your team please prepare a PR with documentation about the feature?

**Comment by bsekachev** [comment]
It was resolved by the PR above.
