### ISSUE TITLE
Clowder integration feature

### ISSUE THREAD

**Issue by andech** [openvinotoolkit/cvat#3009]
# Clowder integration feature

## Short description

For our client we implemented new feature, that allows to upload files from a cloud storage, that is managed by Clowder Framework. Client asked, if this feature could be added into main CVAT stream. We asked about this possibility in https://gitter.im/opencv-cvat/dev?source=orgpage and got the answer with advise to create issue about this feature.

## What is Clowder Framework

Official site with full description https://clowderframework.org/.

This framework allows you to manage files from your cloud storage.
You can put files and folders in **datasets**, and, then request content of the specific **dataset**.

### Screens from Clowder interface

<img src="https://user-images.githubusercontent.com/26138412/112284965-dcab5400-8c9a-11eb-8ad6-beca85a43aa0.png" height="150px"/> <img src="https://user-images.githubusercontent.com/26138412/112284975-df0dae00-8c9a-11eb-9c4a-1f30ad7b5334.png" height="150px"/> <img src="https://user-images.githubusercontent.com/26138412/112284979-dfa64480-8c9a-11eb-9b00-3fe1f89c0dbe.png" height="150px"/>

### Create task page

User goes to task creation page and opens new **Clowder Sync** tab, then inputs **dataset ID** and **Clowder API key**:

<img src="https://user-images.githubusercontent.com/26138412/112296542-159cf600-8ca6-11eb-8bfc-dac6de74f8d4.png" height="150px"/>

User clicks on **Synchronize** button and receives content of the dataset. In the top table user can open subfolders to get their content, as in file manager. Also, user has breadcrumbs above the table:

<img src="https://user-images.githubusercontent.com/26138412/112297021-6f052500-8ca6-11eb-9353-a1ba60bafb07.png" height="150px"/>

User can select folders and files, and add them to the bottom table. If bottom table will have unacceptable combination of files and folders or file formats, user will get warnings about it under the second table:

<img src="https://user-images.githubusercontent.com/26138412/112298140-c1931100-8ca7-11eb-9812-cedc4ed37d46.png" height="150px"/>

After click on **Submit** button, all folders and files, from bottom table, will be send to the server side, as it works for another tabs.

### Task details page

Here user can see additional button **Clowder Sync**, that exports annotations for the task in COCO format to the same Clowder dataset into **annotaions** folder:

<img src="https://user-images.githubusercontent.com/26138412/112301245-c86f5300-8caa-11eb-9bb5-3084aeff0156.png" height="150px"/> <img src="https://user-images.githubusercontent.com/26138412/112300733-3b2bfe80-8caa-11eb-9741-7c3d06d38c45.png" height="150px"/>

### Job details page

Here the same **Clowder Sync** exists and do the same export as on task details page:

<img src="https://user-images.githubusercontent.com/26138412/112301158-b1306580-8caa-11eb-8298-0ba950873fd1.png" height="150px"/>

## How our integration works from developers side

I think, it will be bet better to open pull request just to CVAT team can look at all changes, if functionality described above is acceptable for the project.

In nutshell, during development we tried to encapsulate our changes in additional classes and components to avoid big changes in already existed project files.

### BE part

* Added api class for working with Clowder api
* Added new model for Clowder file
* Added new 4 migrations with changes in Clowder file model
* Added new serializer for Clowder file
* Added new endpoints for new Clowder Sync tab and button
* New method in task.py to copy data from Clowder
* Added new views into views.py 

### FE part

* Added new component for Clowder Sync tab. It encapsulates almost all new FE logic
* Added new global store branch for Clowder sync functionality
* Added new actions and reducer
* Added new actions for annotation and their handling in annotation reducer
* Added new api methods to communicate with new BE endpoints

# P.S.

We are really looking forward to a response from the CVAT team in order to understand what to do next with our feature to integrate it with https://github.com/openvinotoolkit/cvat/issues/863.
And, of course, we are ready to answer your questions.

Thank you!

**Comment by nmanovic** [comment]
@andech , thanks for the issue. It looks awesome. 

>> I think, it will be bet better to open pull request just to CVAT team can look at all changes, if functionality described above is acceptable for the project.

I agree. Could you please send us the PR?

--
  Nikita.

**Comment by cpudney** [comment]
> I agree. Could you please send us the PR?

See https://github.com/openvinotoolkit/cvat/pull/3012

**Comment by nmanovic** [comment]
@cpudney , I will close the issue. We have an open PR now for the functionality.
