### ISSUE TITLE
Documentation about polygon crop behaviour switcher

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#3028]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Need to document recently merged feature #3021.

**Comment by bsekachev** [comment]
Hi, @aschernov 

Could your team prepare a patch with documentation?

**Comment by bsekachev** [comment]
Hi, @TOsmanov 

Since Andrey is on vacation can I ask you to look into the issue?

**Comment by TOsmanov** [comment]
> Hi, @TOsmanov
> 
> Since Andrey is on vacation can I ask you to look into the issue?

Hi, @bsekachev 

Yes, sure
