### ISSUE TITLE
Add documentation about filters and sortings of jobs

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#3038]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Need to document recently merged feature #3030 

@aschernov @TOsmanov , could you please prepare a documentation patch?

**Comment by TOsmanov** [comment]
@bsekachev 

We cannot prepare documentation because this functional is not available on cvat.org
