### ISSUE TITLE
Context images as a hint for an image/frame

### ISSUE THREAD

**Issue by nmanovic** [openvinotoolkit/cvat#3049]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible Solution

For 3D annotation for automotive we have context 2D image as a hint. The feature can be useful for 2D case as well. For example, it is possible to attach depth image. It is a request from a customer which annotates reflective surfaces.

**Comment by waterfall414** [comment]
We have similar demands in medical images too. 

One image can contain multiple layers of information, and the annotation requires user to toggle between layers before confirmation. The current work-around is to have image displayed side by side, which is not optimal for conformation.

Before taking a look at the code, it seems it would change at least two things: one is how the image is managed, and the second is UI/keyboard-shortcut to toggle through.

If we upload a collection of image like this:
image directory:
- imageColor0001.png
- imageDepth0001.png
- imageColor0002.png
- imageDepth0002.png

Which modules should we touch to add this feature? @nmanovic

**Comment by GeorgePearse** [comment]
@mingxin-zheng how do you display two images side by side? Could be very helpful for me.  

Trying to workout a workflow where you accept the better predictions from different models.
