### ISSUE TITLE
Rename labels without changing anything else

### ISSUE THREAD

**Issue by kunaltyagi** [openvinotoolkit/cvat#3051]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Edit a label (as project owner) to correct spelling errors

### Current Behaviour
Label names can't be updated. If the raw field is used to rename a label, a new label is created instead

### Possible Solution
Allow project_owner to edit the label name field

### Steps to Reproduce (for bugs)

1. Open a project
1. Click on "pencil" or update attribute button of a label
1. Confirm that the label name can't be changed
1. Use the raw json to change the name
2. Confirm that there is a new label with the new name, the old label is unaffected

### Context
Spelling errors, ontology management is very difficult with fixed labels

**Comment by kunaltyagi** [comment]
I'm using 
```
Server version: 1.2

Core version: 3.10.0

Canvas version: 2.2.1

UI version: 1.13.3
```

Which version is that?

**Comment by bsekachev** [comment]
@kunaltyagi 

I would suggest to download 1.3 release. 
It's UI version is 1.18.

**Comment by josephj11** [comment]
I recently tested this as a user (using the GitHub website/GUI).

When I renamed a label it was allowed, but it removed the old label from exiting issues and did not add the new label in its place. This seems like a bug to me. I did this in a test repo, so no damage was done.
