### ISSUE TITLE
Unable to connect to dataset repository

### ISSUE THREAD

**Issue by Arpitrf** [openvinotoolkit/cvat#3060]
I am unable to link my CVAT Task to my GitHub repository. When I go to my Task and click on "Synchronize", I get the following error:
![image](https://user-images.githubusercontent.com/14124093/113475537-f6ffe180-9493-11eb-95e5-7b6fc62807b7.png)

Any help would be appreciated. Thank you!

**Comment by azhavoro** [comment]
Hi, have you added the public key from the error message to your Github repository?

**Comment by nmanovic** [comment]
@Arpitrf , don't hesitate to reopen the issue if you can provide more information. For now I will close the issue.
