### ISSUE TITLE
saving Issues

### ISSUE THREAD

**Issue by evilhulk** [openvinotoolkit/cvat#3062]
![Screenshot (139)](https://user-images.githubusercontent.com/59325601/113535829-26c4fb80-95f2-11eb-9caa-5a5b19afaf4a.png)
![Screenshot (139)](https://user-images.githubusercontent.com/59325601/113535854-36dcdb00-95f2-11eb-8e0f-2fa95a2315ed.png)

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by evilhulk** [comment]
I can't able to save my data now it's almost completed

**Comment by azhavoro** [comment]
Hi, try to open a new browser tab and login to cvat, after that it should be possible to save annotations in the current tab.

**Comment by azhavoro** [comment]
@evilhulk Have you solved this issue?

**Comment by nmanovic** [comment]
Please let us know if you still cannot solve the problem. 401 is authentication issue. You need to relogin.
