### ISSUE TITLE
Add documentation about labels hotkeys

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#3076]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

We have merged recently #3070. 
It adds hotkeys to labels ``Ctrl + Num`` where Num is [0...9]. Using the hotkey you can update a label of existing object (if activated) or change default label (for next object created using ``N`` hotkey). Also user can specify custom bindings Num <-> Label.

**Comment by nmanovic** [comment]
@aschernov , @TOsmanov , could you please add information into documentation?

**Comment by aschernov** [comment]
@bsekachev , taken it in work.

**Comment by bsekachev** [comment]
Closed by #3085
