### ISSUE TITLE
UI fails to load previously cached frames when working with large images

### ISSUE THREAD

**Issue by maximusunc** [openvinotoolkit/cvat#3080]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

A user can navigate through all frames in a job regardless of image size.

### Current Behaviour

The UI gets stuck in a loading state when trying to go backwards through already loaded frames.

### Possible Solution

This seems to be some issue with retrieving frames that have been cached, because the UI always stops at one of the image chunk points.

### Steps to Reproduce (for bugs)

Here is a live example uploaded on cvat.org: https://cvat.org/tasks/66868/jobs/97576
1. Create a task with 100 images (all 2048x2448)
1. Open the job and step through all frames
1. Once at the end, step backwards through all frames
1. At some point, the UI shows the loading icon and fails to load any previous images. You can however step back forward, but everything backwards fails to load.

**Comment by azhavoro** [comment]
Hi, this is an expected issue due to image cache size limitation in the current implementation, especially for high resolution images.

**Comment by maximusunc** [comment]
Hey @azhavoro thanks for the response. Do you know if or when this issue might have a fix? Just downscaling the images isn't really an option because we really need pixel accuracy on higher resolution images. I've also looked into just disabling the cache, but trying to disable it through the UI as well as the API doesn't seem to work. Any advice would be greatly appreciated!

**Comment by azhavoro** [comment]
@maximusunc Sorry, my previous comment was wrong, I thought you were talking about reloading each frame in the backward, which is related with the limited cache size. Thanks for the fix, I'll test it today.
