### ISSUE TITLE
CentOS version of CVAT

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [openvinotoolkit/cvat#3092]
Is there a CentOS version of CVAT

**Comment by bsekachev** [comment]
Hi @ITBOX-ITBOY 

What do you mean? Development under CentOS, deploying on CentOS or CVAT docker image based on CentOS?

**Comment by ITBOX-ITBOY** [comment]
> What do you mean? Development under CentOS, deploying on CentOS or CVAT docker image based on CentOS?

I want a CVAT build based on CentOS

**Comment by bsekachev** [comment]
Current docker image based on Ubuntu and the core team does not support other base operating systems.
