### ISSUE TITLE
The image that i have uploaded was reversed automatically 

### ISSUE THREAD

**Issue by kgloveyou** [openvinotoolkit/cvat#3120]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.create a task and upload the following image
![U1cxaFoyVmZNakF5TURBeE1UTXhNREE0TURBM09Eaw](https://user-images.githubusercontent.com/5866147/115711148-c41b8000-a3a5-11eb-976d-72cc84709c7d.jpg)

2. open the created task,  found the image was reversed automatically.
<img width="1920" alt="snap_20210422200046" src="https://user-images.githubusercontent.com/5866147/115711328-f5944b80-a3a5-11eb-96f0-9c053dcfab66.png">

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Related issue #1059 

For this image:
```
 Orientation: BottomRight
``` 
which causes the image should be rotated to display correctly

**Comment by kgloveyou** [comment]
@azhavoro ，thanks. It should be the reason.

**Comment by nmanovic** [comment]
@kgloveyou , thanks for the report. I will close the issue as a duplicate.
