### ISSUE TITLE
 Could not create the task on the server when using shared storage

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#3123]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
No any errors when creating a task using image lists and directories

### Current Behaviour
When I upload some images together with directories, I get error:
```
Error: Could not create the task on the server.
Exception: Combined data types are not supported.
```

### Possible Solution
Probably need to convert directory to list of images properly, or to allow different media types in case of images and directories

### Steps to Reproduce (for bugs)

I have the following structure on shared storage:
```
root/
    data1/
        people.jpg
        street_1.jpeg
        street_2.jpg
        street_3.jpg
        street.png
        subdir/
                image_4.jpg
                image_5.jpg
                image_6.jpg
```

1. Start creating a task, go to connected file share and select files
1. Expand root
1. Expand data1
1. Click data1 to select all the files and directories inside (IMPORTANT: Do not expand the subdirectory)
If expand the subdirectory, task can be created. 
1. Click "Submit"

Request body in this case:
```json
{"chunk_size":null,"size":0,"image_quality":70,"start_frame":0,"stop_frame":0,"frame_filter":"","compressed_chunk_type":"imageset","original_chunk_type":"imageset","client_files":[],"server_files":["/data1/","/data1/people.jpg","/data1/street_1.jpeg","/data1/street_2.jpg","/data1/street_3.jpg","/data1/street.png","/data1/subdir/"],"remote_files":[],"use_zip_chunks":false,"use_cache":false,"copy_data":false}
```

### Context
![Screenshot from 2021-04-22 22-07-20](https://user-images.githubusercontent.com/40690378/115771882-23ce5700-a3b7-11eb-8934-d66bcc819b11.png)

### Your Environment

- Git hash commit (`git log -1`):
```
commit 38b774046d41d604ed85a521587e4bacce61b69c (HEAD -> develop, origin/develop, origin/HEAD)
Author: Dmitry Kruchinin <33020454+dvkruchinin@users.noreply.github.com>
Date:   Thu Apr 22 17:04:05 2021 +0300

    Remark linter. Check lenght of messages only. (#3117)
```

- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? N/A
- Operating System and version (e.g. Linux, Windows, MacOS): N/A
- Code example or link to GitHub repo or gist to reproduce problem: N/A

**Comment by varchanaiyer** [comment]
Hi there! Are there any updates on this, I am also getting a server error while creating a new task!

**Comment by bsekachev** [comment]
Hi @varchanaiyer 

Maria now is working on another feature, but fixing the issue is also within the nearest plans.
