### ISSUE TITLE
Could not fetch frame data from server

### ISSUE THREAD

**Issue by himalayanZephyr** [openvinotoolkit/cvat#3126]
Hi
When dragging the video bar left and right following error is popping up:

"Could not fetch frame data from server"

[Error screenshot ](https://ibb.co/phzPkr2)

Tried both cvat release 1.2 and 1.3
Both show this error. What might be causing this issue?
I'll try reverting back to 1.1 and see if this gets fixed.

Thanks

**Comment by azhavoro** [comment]
Confirmed, I can reproduce this issue, but it looks like these are only notifications that should not be displayed and do not affect anything else.

**Comment by himalayanZephyr** [comment]
@azhavoro  Thanks for checking this. Yes, I agree that it doesn't affect anything else but it becomes difficult to view/use the panel with all those pop-ups covering the screen. 
I'm going to try an older version and report back on it whether that fixes and wait for this to be fixed in the newer versions. If you have any other suggestions please let me know!
Appreciate your help :)

**Comment by ipesanz** [comment]
Hi @nmanovic ,
As discussed in [Glitter](https://gitter.im/opencv-cvat/public)

Adding a .gif reproducing the error. 

![CVAT_v4](https://user-images.githubusercontent.com/6901569/121485564-94b1e880-c9d0-11eb-91ba-a58ed1a7b0dc.gif)

**Comment by manybodycpa** [comment]
@bsekachev I have the same error but in my case, some users cannot see the affected frames whereas for others it works (version 1.4). Should I open an independent issue?

**Comment by bsekachev** [comment]
@manybodycpa 
I would suggest using a newer version. 
1.1 is too old.

**Comment by manybodycpa** [comment]
@bsekachev We did move on to 1.4 recently. Same problem.

**Comment by bsekachev** [comment]
@manybodycpa 

Did you try fix #3373?

**Comment by manybodycpa** [comment]
@bsekachev I have not tried the fix. However, since my issue is not just about notifications but about actually inaccessible frames (stuck at loading), I will open a separate issue with full details. Please feel free to close or link if applicable.
