### ISSUE TITLE
Empty dataset download

### ISSUE THREAD

**Issue by spatra007** [openvinotoolkit/cvat#3127]
![CVAT_Issue_Image1](https://user-images.githubusercontent.com/66479020/115956043-43c95c00-a518-11eb-94e2-e7391b165e54.PNG)
![CVAT_Issue_Image2](https://user-images.githubusercontent.com/66479020/115956044-44fa8900-a518-11eb-89a8-efdb6a633eca.PNG)

### My actions before raising this issue
I have deployed CVAT on a Azure VM with 32 GB RAM and 8 vCPUs. I have created a task with 45000 images (from videos) and after annotating the task, I am selecting on export dataset with Yolo 1.1 format.

### Expected Behaviour
Ideally it should download the dataset in a zip file.

### Current Behaviour
The download starts as a zip file (with proper name, like, task_annotation xxxx) showing that the file size is 132 GB. As soon as it reaches the mark of 1 GB, the download completes and in my Downloads folder I just see and file with name "dataset" and size=0 KB.

### Possible Solution
Not sure how to solve it. Please help, its urgent :(

### Steps to Reproduce (for bugs)
I dont have access to VM management, so cant open up the firewall for a live link, as I am not the admin. 

### Context
I am stuck as all my annotations and datasets saved on CVAT server, are not downloading.

### Your Environment
CVAT on Azure VM running on - 

**1. Ubuntu 18.04**
**[2. Docker -]([url](url))**
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by spatra007** [comment]
@nmanovic @azhavoro , is there any temporary work around to this? I would really love to get the dataset off the server. Meanwhile kindly let me know when this bug is going to be fixed in future releases and if there is anyway I can contribute :) :)

**Comment by spatra007** [comment]
@azhavoro I read this in another issue to update the "limit-request-body" parameter in supervisord.conf , could you please help understand how do I do that? 

I see here you have advised to this - [https://github.com/openvinotoolkit/cvat/issues/2330#issuecomment-768084006](url)

How do I update it to have no limits and then apply the changes to my running cvat docker instance on the VM?

**Comment by azhavoro** [comment]
@spatra007 Hi, just change the value of `--limit-request-body` option here https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L65, rebuild image and restart your containers with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`. Try setting the value to `0` to disable this limitation, but I'm not sure if this will work. If that doesn't work, increase the value up to 1000 times, the current value is 1 GB.

**Comment by spatra007** [comment]
Yes!! It worked right away! Thanks a lot @azhavoro !

**Comment by ConstantSun** [comment]
Sorry, but now, even I tried --limit-request-body with 0 or 10GB, it still did not work, it stopped downloading when it reached 1 GB.

**Comment by azhavoro** [comment]
@ConstantSun need to rebuild containers `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`
