### ISSUE TITLE
Annotator role should not have permission to reassign jobs to other users

### ISSUE THREAD

**Issue by adamhrv** [openvinotoolkit/cvat#3151]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Annotator role should be limited to annotations, but in task view (eg site.com/tasks/1) an annotator is able to reassign a job (eg site.com/tasks/1/jobs/2) to other users. Also, the annotator is able to see a full list of users (mentioned here https://github.com/openvinotoolkit/cvat/projects/24). Even when the Task is assigned to the Admin. The Annotator is only the "Assignee" for the Job.

### Current Behaviour

User is assigned role as "Annotator", logs in, visits task and can change the assignee ("assignee_id") to any user, thereby removing the Job from their assignments.

### Possible Solution

Possibly disable editable HTML and limit JSON data response for Annotator role.

### Context

This causes issues because users are able to unassign or reassign jobs which should only be the role of Admin users.

### Your Environment
- using `develop` `HEAD e00c389991fc6a0d9d43f977cba10015b80c71dd`

**Comment by arcibiyo** [comment]
@adamhrv Could you solve this problem ?
