### ISSUE TITLE
Deploying Yolov4 on darknet to nuclio serverless

### ISSUE THREAD

**Issue by spatra007** [openvinotoolkit/cvat#3152]
Hey Guys

Can someone guide me to how I can deploy a yolov4 model on darknet framework to nuclio serverless in cvat? I have the model trained on custom data and my environment is ubuntu18.04LTS? If there isn't a way for darknet, then please guide me how to deploy using any other framework.

Thanks

**Comment by spatra007** [comment]
Any updates on this please? I have been having a hard time figuring out how to do that :(

**Comment by AdimasBarelang** [comment]
any news on this ? i really dont understand the tutorial
