### ISSUE TITLE
Make annotation tasks visible/editable only for specific group(s) of users

### ISSUE THREAD

**Issue by daniel-de** [openvinotoolkit/cvat#317]
Sometimes it ist useful to restrict access and visibility of annotation tasks to certain groups of users instead of running one instance of cvat for each of these groups...

**Comment by nmanovic** [comment]
issue #851 looks similar. Need different groups for different actions.

**Comment by nmanovic** [comment]
https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=916402

**Comment by nmanovic** [comment]
Let's use https://casbin.org/ to implement Role-Based Access Control (RBAC).

**Comment by nmanovic** [comment]
Another approach is to use [Open Policy Agent](https://github.com/open-policy-agent/opa). It looks very promising. The whole idea is to have something like [AWS IAM](https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html)

Alternative solutions which were found by me:
- https://github.com/ory/ladon
- https://github.com/rsinger86/drf-access-policy
- https://github.com/kolotaev/vakt/

**Comment by leeyh20** [comment]
Will this feature be added anytime soon? This is a great feature to have
