### ISSUE TITLE
Zoom is reseted when changing frame

### ISSUE THREAD

**Issue by siahuat0727** [openvinotoolkit/cvat#3185]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Keep the zoom regioned when changing between frames.

### Possible Solution

I think it's already there and I don't know how to do it.

### Steps to Reproduce (for bugs)

Zoom a frame and then press `F` or `D`

### Context

How the keep the zoomed region when changing frame?
I found an issue #2062 about this but it was then deleted by the author.

**Comment by bsekachev** [comment]
@siahuat0727 

Just go to settings, uncheck "Reset zoom" and press save. 
For more information please refer to the user guide. 
I will close the issue, if you still have questions, please ask our community on gitter.

**Comment by siahuat0727** [comment]
Thanks a lot!
