### ISSUE TITLE
For Instance segmentation and automatic annotation

### ISSUE THREAD

**Issue by kankanzheli** [openvinotoolkit/cvat#3195]
The question is simple. First of all, there is a case that two parts belong to the same object. How is this labeled? At the same time, how to distinguish different objects in the process of annotation?

Besides, I want to try the auto tagging function. But the optional model doesn't have the object I want to label. Can I train the model for cvat through my tagged data?

**Comment by azhavoro** [comment]
@kankanzheli Hi,
1. Take a look at object grouping https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/user_guide.md#shape-grouping
2. Tutorial how to use a custom model for auto annotation is not ready, but I hope the draft PR will be helpful anyway https://github.com/openvinotoolkit/cvat/pull/3124

**Comment by bsekachev** [comment]
I hope you have found the answer and I will close the issue, because there is not a response from your side. Do not hesitate to reopen it if you still have questions.
