### ISSUE TITLE
[Bug] Server raises errors while trying to dump one type and upload another type.

### ISSUE THREAD

**Issue by MashaSS** [openvinotoolkit/cvat#3201]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
CVAT has to handle errors correctly and return status code 500 or 404.

### Current Behaviour
If CVAT can't upload another type it raises errors.

### Steps to Reproduce (for bugs)

1) create annotations in frames/jobs
2) dump annotations one type
4) upload annotations with another type
PUT query /api/v1/tasks/1/annotations&name_type)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
What is the problem here specifically? Server raises an error, if input data has unexpected format. UI displays the error.

**Comment by bsekachev** [comment]
As Maxim mentioned, probably it is not a bug.
