### ISSUE TITLE
[Bug] CamVid 1.0 format doesn't load annotation after rewriting annotations in task.

### ISSUE THREAD

**Issue by MashaSS** [openvinotoolkit/cvat#3203]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
1) response_code == 202
2) necessary annotations are present (from step 1)

### Current Behaviour
1) response_code == 202
2) necessary annotations are not present

### Steps to Reproduce (for bugs)

1) create annotations in frames/jobs
2) dump annotations
3) create several new annotations and remove several old annotations 
4) upload annotations with different types (CamVid 1.0)
PUT query /api/v1/tasks/1/annotations&name_type)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Please be more specific about the case, I couldn't reproduce it. Uploading (at least, in UI) always removes annotations first.
