### ISSUE TITLE
[Bug] Unexpected behaviour in dump/upload annotations with objects are different types (images)

### ISSUE THREAD

**Issue by MashaSS** [openvinotoolkit/cvat#3204]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

1) response_code == 202
2) necessary annotations are present
3) Two shapes are present in task

### Current Behaviour

Only one shape is present in uploaded annotation. Rectangle shape is converted to track in case of video format.

### Steps to Reproduce (for bugs)

1) create task with images
2) create rectangle (shape and track) annotations in frames
3) dump CVAT for images 1.1 annotations
4) upload CVAT 1.1 annotations
(PUT query /api/v1/tasks/1/annotations&format=CVAT 1.1)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Please be more specific about the case, I couldn't reproduce it.
We always expect 2 shapes in these cases, but in CVAT for video we expect 2 tracks, and in CVAT for images we expect 2 regular shapes.
