### ISSUE TITLE
Context images 2D add documentation to the user guide

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#3214]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Recently we have merged new patch, which adds ability to upload additional context images to images for annotations.
Now need to update documentation to show users how these images could be attached.
Reference PR #3122

Please, contact me additionally if you have any questions

**Comment by bsekachev** [comment]
@TOsmanov @aschernov 

Could you please prepare a patch with documentation to cover the feature?

**Comment by aschernov** [comment]
@bsekachev , sure. Taken in work.

**Comment by bsekachev** [comment]
@aschernov 

Thx. It is better to start working on it after #3039 is merged.

**Comment by bsekachev** [comment]
Closed by #3227
