### ISSUE TITLE
"TypeError: Cannot read property 'clientX' of undefined" error with redraw/repeat draw a cuboid.

### ISSUE THREAD

**Issue by dvkruchinin** [openvinotoolkit/cvat#3219]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
A cuboid redraw/repeat draw successfully

### Current Behaviour
Getting an error:
```
svg.draw.js:270 Uncaught TypeError: Cannot read property 'clientX' of undefined
    at e.calc (svg.draw.js:270)
    at e.done (svg.draw.js:153)
    at t.draw (svg.draw.js:220)
    at t.a_.Element.draw (svg.patch.ts:29)
    at q_.release (drawHandler.ts:318)
    at q_.draw (drawHandler.ts:931)
    at dE.notify (canvasView.ts:1265)
    at t_.notify (master.ts:41)
    at t_.draw (canvasModel.ts:543)
    at hE.draw (canvas.ts:128)
```
![canvas2d_2-issue](https://user-images.githubusercontent.com/33020454/118979795-864c5000-b981-11eb-80c5-83d4212b764a.gif)

### Steps to Reproduce (for bugs)

1. Demonstrated above
At the time of redrawing/repeat drawing, press N or Shift+N.

### Your Environment

- Git hash commit (`git log -1`): ccb24c2a2cac92523893983738605a9f70ae9d42
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@ActiveChooN That was fixed
