### ISSUE TITLE
Unable to Save Player and Workspace settings

### ISSUE THREAD

**Issue by digitalpixi** [openvinotoolkit/cvat#3221]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)

Required to set the settings each time for the Workspace and Play when I work on a task or job in CVAT. It doesn't save across sessions.

### Expected Behaviour
Saves settings for the Workspace to be the same each time user logins.

### Current Behaviour
Have to modify and save the settings for each job and task.

### Possible Solution
Set and forget it settings.

### Steps to Reproduce (for bugs)
Go to Settings, make changes work on a job. Open a new job, reset the settings.

### Context
It wastes time setting the settings every time.

### Your Environment
Server version: 1.3
Core version: 3.10.0
Canvas version: 2.2.1
UI version: 1.13.5

Happens when I log in on Ubuntu and Windows Chrome. I have Admin privileges but I do not run our server. Any suggestions to fix would be passed along.

Thank you!

**Comment by ActiveChooN** [comment]
@digitalpixi, hi, maybe I cannot understand completely. What is expected behaviour?
What I've done:
- login
- change settings 
- save settings
- logout
- reload page
- login
- settings still the same

Do you been this behaviour should be different?

**Comment by digitalpixi** [comment]
The Workspace settings are now saving correctly.
