### ISSUE TITLE
Doc [installation_automatic_annotation] is 404

### ISSUE THREAD

**Issue by tycallen** [openvinotoolkit/cvat#3222]
Please provide the installation guide for auto and semi auto annotation part, thanks!

**Comment by nmanovic** [comment]
We are updating our documentation. Please find it here now: https://openvinotoolkit.github.io/cvat/docs/for-users/installation_automatic_annotation/

Don't hesitate to reopen the issue if my answer isn't complete.

**Comment by ohm1998** [comment]
> We are updating our documentation. Please find it here now: https://openvinotoolkit.github.io/cvat/docs/for-users/installation_automatic_annotation/
> 
> Don't hesitate to reopen the issue if my answer isn't complete.

This again throws 404
can you help me with the installation of automatic annotation?

**Comment by nmanovic** [comment]
@ohm1998 , the actual link is https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/

**Comment by ohm1998** [comment]
> @ohm1998 , the actual link is https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/

works thank you!
