### ISSUE TITLE
Unable to show context image for 2D tasks

### ISSUE THREAD

**Issue by waterfall414** [openvinotoolkit/cvat#3239]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I uploaded a sample image dataset following the file structure detailed in enhancement #3122, and hoped to see the context image.

### Current Behaviour

CVAT recognized the context image as an additional image to annotate, and trailed this image to the end of the frame sequence

### Steps to Reproduce (for bugs)

Here is the one-image (1 image to annotate, 1 context image) zip archive I uploaded to CVAT:
[cat.zip](https://github.com/openvinotoolkit/cvat/files/6550700/cat.zip)
And the context image was trailed to the end
![image](https://user-images.githubusercontent.com/18563433/119757805-7f3aab80-be73-11eb-8ba8-9ae5fcfd8f46.png)

### Your Environment

- Git hash commit (`git log -1`): commit 11d967d2087d2eecf331cf445ea49bdcff77234f (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.6
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04 and 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi @waterfall414

I tried archive you provided and it works as expected.
Have you rebuilt cvat images and restart cvat containers after fetching the changes?
Could you please provide versions from About modal window?
![Screenshot from 2021-05-27 08-38-29](https://user-images.githubusercontent.com/40690378/119771808-ee8dbb00-bec6-11eb-8f6b-3e616d92f8c2.png)

**Comment by waterfall414** [comment]
Thanks for looking into this @bsekachev 

This is from the version window: 

Server version: 1.3

Core version: 3.11.0

Canvas version: 2.3.2

UI version: 1.15.3

I will try to rebuild the images and go from there

**Comment by waterfall414** [comment]
The issue is solved after I built the images by

```bash
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
docker-compose up -d
```
As the changes are still unreleased.

Thanks and I will close this issue.
