### ISSUE TITLE
Task deleted spontaneously

### ISSUE THREAD

**Issue by AlperenEnesBayar** [openvinotoolkit/cvat#3241]
### Bug
The task we worked on deleted spontaneously. Can we do something to make it come back or is it all gone.

The error we got:
Sorry, but this job was not found
Please, be sure information you tried to get exist and you have access

![image](https://user-images.githubusercontent.com/45437411/119777107-6dd2bd00-bece-11eb-8c6f-53282d822e1f.png)

Our usernames:
asdas
enesalperen

**Comment by mehmethaliloglu** [comment]
Hi  @AlperenEnesBayar , I have the same problem. I think there is work on cvat.org. If you log in from a different computer or phone, you will see that you do not have access to the site. The reason you can open it now is because it is kept in the cache. Let's wait and see what happens.

**Comment by AlperenEnesBayar** [comment]
@mehmethaliloglu, thanks for the heads up, let's wait like you said.

**Comment by bsekachev** [comment]
@AlperenEnesBayar 

The access to cvat.org was restored. I would also recommend to clear the browser cache.

**Comment by AlperenEnesBayar** [comment]
@mehmethaliloglu If you haven't noticed, the site has come to life again. We can continue working.
