### ISSUE TITLE
Assignee user should'nt change your reviewer

### ISSUE THREAD

**Issue by arcibiyo** [openvinotoolkit/cvat#3247]
Assignee user can change your reviewer. How can I disable this option?

![image](https://user-images.githubusercontent.com/47760055/119852017-99c66080-bf17-11eb-97ed-75eca62126c4.png)

**Comment by bsekachev** [comment]
Hi @arcibiyo 

CVAT does not has such the option. 
Speaking in general, how an annotator can ask somebody to review the job if they don't have permissions to it?

**Comment by arcibiyo** [comment]
I wanna assign jobs to users and reviewers that I have determined as admin. I dont wanna reviewers to change because I cant manage these changes. A assignee can change own assignee and reviewer. So it's getting harder to manage for admin. Because of this ı wanna restrict this option like a assigne can not change other jobs.

**Comment by bsekachev** [comment]
I understand your request. Probably it cannot be well implemented within the current permission system. 
We have some plans to support an advanced permission system, but I can't provide any deadlines here.
