### ISSUE TITLE
Add own base models to CVAT

### ISSUE THREAD

**Issue by dluo222** [openvinotoolkit/cvat#3248]
Does CVAT allow developers to add own base models to CVAT and train a model to pre-annotate images? If yes, is there any document?

**Comment by azhavoro** [comment]
Hi, yes it's possible, please tale a look at this PR https://github.com/openvinotoolkit/cvat/pull/3124

**Comment by dluo222** [comment]
Do you mean in order to add my custom DL I have to push my code on git?
