### ISSUE TITLE
use multiple user from cvat  in network

### ISSUE THREAD

**Issue by masoudgh85** [openvinotoolkit/cvat#3256]
hi,
How to use the cvat as a network and on another computer? How to connect multiple user from multiple computers under the network to cvat?
I am working with cvat on my computer in localhost 8080, how can another network user connect through another computer?

Copyright (C) 2020 Intel Corporation

SPDX-License-Identifier: MIT
-->

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi @masoudgh85 

In ``docker-compose.yml`` set CVAT_HOST variable to your internal IP (usually 192.168.0.*). 
Then rebuild the images and restart the containers. Be sure that PORT 8080 is not blocked by your firewall.
Connect to CVAT from another machine: 192.168.0.*:8080

**Comment by bsekachev** [comment]
I hope my reply helped you. I will close the issue, do not hesitate to reopen it if you still have questions.
