### ISSUE TITLE
Implement mechanism for automatic backup

### ISSUE THREAD

**Issue by gfolego** [openvinotoolkit/cvat#326]
Following a suggestion made by Nikita Manovich ( @nmanovic ) on Gitter, I'm opening this feature request.

It would be very interesting to have the possibility to automatically backup annotations.
As far as I understand, there's currently a dump mechanism via UI, where you can download and use/store/share annotations. However, it seems that it is not possible to perform such dump via a backend script, for instance.
The idea would be to automate annotation backup to a repository, such as Google Drive, Dropbox, etc.
Such feature would be very much welcome.

Thanks!

**Comment by Diaislam** [comment]
This would be a good feature (personally i need it)

**Comment by nmanovic** [comment]
@gfolego , the issue was particular solved. Annotations can be dumped using https://github.com/opencv/cvat/tree/develop/utils/cli. But I will keep the issue open till we have a script to backup CVAT instance (DB, files, logs, etc).

**Comment by jackneil** [comment]
Hi @nmanovic 
Any update on the backup process? I'm currently backing up by tarring the /home/django/data/ and /var/lib/postgresql/data folders to a .tar file mounted to /home/django/share/mytars.tar

Backing up those directories should cover me for backing up the annotations and database correct? And if something happened I should be able to untar them back to their original directories and overwrite the files at those locations to get back up and running?

Didn't see the exact how to backup tasks and annotations documented anywhere and considering we're spending a lot of time 'tagging' I want to make sure we don't accidentally overwrite our progress by running some accidental command or upgrade in docker. thanks all and thany you nmanovic for your diligent work on this excellent tool. A+

-jack

**Comment by RomanVeretenov** [comment]
Yes, I also would like to see a clear backup process. Now we are using [borg docker image](https://hub.docker.com/r/pschiffe/borg/) to backup cvat and cvat_db, but we have never tested it truly. Just tried once and succeeded.

But at the moment, we are trying to move our cvat instance to other machine and having problems with applying our backups there.

**Comment by nmanovic** [comment]
We wrote the tutorial: https://openvinotoolkit.github.io/cvat/docs/administration/advanced/backup_guide/. I will close the issue.

**Comment by antortjim** [comment]
Can someone share the link to the backup guide using the CLI (or any automatable tool e.g. Python)? The one above is broken :cry: Thanks!

**Comment by antortjim** [comment]
Nevermind, I think it's here
https://github.com/cvat-ai/cvat/blob/master/site/content/en/docs/administration/advanced/backup_guide.md
