### ISSUE TITLE
Output results

### ISSUE THREAD

**Issue by kankanzheli** [openvinotoolkit/cvat#3260]
I need to output annotation results under two tasks. How to integrate the annotation results of two tasks into one task?

In addition, I want to output coco datasets or VOC datasets. How to output VOC data set? How can coco dataset be divided into three parts: train, test and val for training? Is there a ready-made data processing method?

**Comment by bsekachev** [comment]
CVAT is not able to merge annotations from different tasks yet. 

@zhiltsov-max Can Datumaro provide anything from the request?

**Comment by zhiltsov-max** [comment]
> I need to output annotation results under two tasks. How to integrate the annotation results of two tasks into one task?
> In addition, I want to output coco datasets or VOC datasets. How to output VOC data set?

Probably, this was resolved in https://github.com/openvinotoolkit/cvat/issues/3268

> How can coco dataset be divided into three parts: train, test and val for training? Is there a ready-made data processing method?

Use Datumaro for this (https://github.com/openvinotoolkit/datumaro/blob/develop/docs/user_manual.md#transform-project):
```
datum import -i path/to/dataset -f coco -o proj
datum transform -t random_split -p proj -o splitted -- -s train:0.6 -s val:0.2 -s test:0.2
datum export -f coco -p splitted -- --save-images
```

**Comment by bsekachev** [comment]
I will close the issue, because there is not a response from your side. Do not hesitate to reopen it if you still have questions
