### ISSUE TITLE
Error 504 in tasks with large amount of frames

### ISSUE THREAD

**Issue by aschernov** [openvinotoolkit/cvat#3264]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Fix the error 504.
### Current Behaviour

Today have been noticed that we can't  open some jobs in tasks with large amount of frames.
We've faced the 504 error: Request failed with status code 504. "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.13.6</center>\r\n</body>\r\n</html>\r\n\r\n<!

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
These changes lead to performance degradation https://github.com/openvinotoolkit/cvat/commit/6f52ef30e411c3d9624beead4fe7405c2e283fe8#diff-ebeaa393d7c4bb7b662665b2af97e08a16b1c81bceb158b1b1a0cc47bb7e7c46L639-L650
