### ISSUE TITLE
Merging two coco datasets

### ISSUE THREAD

**Issue by kankanzheli** [openvinotoolkit/cvat#3268]
Is there a way to merge two coco datasets from cvat?

**Comment by zhiltsov-max** [comment]
https://github.com/openvinotoolkit/datumaro/issues/16#issuecomment-691976170

**Comment by kankanzheli** [comment]
Sorry. 
For openvinotoolkit/datumaro#16 (comment). I can do this steop "pip install 'git+https://github.com/openvinotoolkit/datumaro@zm/coco-reindexing' --force-reinstall". But I install Datumaro in the nearly time. Then, I try it:
datum project import -f coco -i /home/zhaowentao/1/coco2/annotations/instances_default.json -o src2_proj
datum project import -f coco -i /home/zhaowentao/1/coco1/annotations/instances_default.json -o src1_proj
Last I work "datum project export -p merged -f coco -- --reindex", it will say "coco: error: argument --reindex: expected one argument".
I tried "datum project export -p merged -f coco".
But the result is not good.
For example, the coco1 is the result for 100 images. coco2 is the result for another 100 images. The merged result showed nothing in the 100 images of coco1. The merged result showed the Label results(result of coco1 and coco2) in the 100 images of coco2. But the result of coco1 showed in the wrong images.

**Comment by zhiltsov-max** [comment]
Probably, you need to use `--reindex`, it expects `0` or `1` as its value. Try to run it like this:

```
datum export -p merged -f coco -- --reindex=1 
```

Also, you can add `--save-images` to include images in the resulting directory.

Run `datum export -p merged -f coco -- -h` to see help about supported parameters.

**Comment by kankanzheli** [comment]
Thank you very much. It is worked!
