### ISSUE TITLE
Uploaded frames in incorrect order

### ISSUE THREAD

**Issue by afonseca18** [openvinotoolkit/cvat#3270]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
When we upload 500 frames from a video we expect them to be placed in order.

### Current Behaviour
It worked fine in the past, but today it seems that the server isn't able to place a list of frames correctly. 
For example: 
![image](https://user-images.githubusercontent.com/38769721/120484693-3ae76800-c3ab-11eb-86f1-1eeaee08d4e9.png)
![image](https://user-images.githubusercontent.com/38769721/120484723-420e7600-c3ab-11eb-8ac1-c3bc8f3a4915.png)

These two consecutive frames appear in the first and last frame.

### Steps to Reproduce (for bugs)
Upload 500 frames in a task.

### Your Environment

Using cvat.org and Linux.

**Comment by azhavoro** [comment]
Hi, the frames sorted in lexicographical order, so please pad the numbers with leading zeros like `s4_00123456` to get the expected order
