### ISSUE TITLE
Issues on review mode are seen only on the same machine and disspear after deleting cookies

### ISSUE THREAD

**Issue by yohayonyon** [openvinotoolkit/cvat#3280]
### My actions before raising this issue
- [v] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [v] Searched [past issues](/issues)

Issues on review mode are seen only on the same machine and disspear after removing cookies

### Expected Behaviour
Issues should be seen for all users and on all machines. They should be saved on server and not on cookies.

### Current Behaviour
The steps that were done:
1. Issues were created.
2. The task was saved.
3. A review was requested from another user.
4. Cookies were removed and the browser was re-opened.
5. The issues were not seen neither by the reporter nor by the assignee.

### Possible Solution
Save the issues to the server.

### Steps to Reproduce (for bugs)
Refer to "Current Behaviour" above.

### Context
The reviewing mechnism is not useful this way. Am I missing something???

### Your Environment

- Git hash commit (`git log -1`): 315c9cc8d2b1c8fbd3b6b5e6ab6fca3a792bc895 - v1.4.0
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.6
- Are you using Docker Swarm or Kubernetes? None
- Operating System and version (e.g. Linux, Windows, MacOS): Lnix 18.04
- Code example or link to GitHub repo or gist to reproduce problem: NA
- Other diagnostic information / logs: NA

**Comment by bsekachev** [comment]
Hi @yohayonyon

They are saved on the server when you submit the review.

**Comment by yohayonyon** [comment]
I understand.
Thank you!
