### ISSUE TITLE
Maintaining upload order

### ISSUE THREAD

**Issue by dreaquil** [openvinotoolkit/cvat#3282]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I would like to be able to maintain the job list order in which I upload my images. If this is not possible, can you point me to the area of code that does the lexicographical ordering of the job list/segments please? The reason I want to do this is a comparative annotation experiment which requires random reordering.

### Current Behaviour
Currently, these are being sorted by the file name.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@dreaquil Hi, https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/media_extractors.py#L52. Image order management is not supported at this time.

**Comment by bsekachev** [comment]
Looks like your question was answered, so, I will close the issue. If you believe it is a feature request, please provide more details about different use-cases and possible solutions. Right now I don't see a lot of requests to support image randomization.
