### ISSUE TITLE
Task deleted but docker volume cache full 

### ISSUE THREAD

**Issue by sirinemrab** [openvinotoolkit/cvat#3285]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

The issues relate to space use from CVAT operations. I created a new task using a shared repository and "using cache to store data". The task contains a big amount of pictures. After adding the annotations and looking at all the images of the task, I deleted the task. But I noticed the docker volume cvat_cvat_data has not been emptied. So I looked at the content of this volume cvat_cvat_data and I noticed that it is the cache directory (/var/lib/docker/volumes/cvat_cvat_data/_data/cache) which is not emptied. 

### Expected Behaviour

The cache into the docker volume cvat_cvat_data  should be deleted when a task is deleted. 
The cache into the docker volume cvat_cvat_data  should be deleted when a task is not used for a long period of time. 

### Steps to Reproduce (for bugs)

1. Create Task using a "Connected file Share" (the repo contains 10000 images)  
"Copy data into CVAT" is unchecked 
"Use zip chuncks"  is unchecked 
"Use cache" is checked

2. Check space used on Docker (docker system df) --> Local Volumes = 100MB
3. Open task and scroll through the images 
4.   Check space used on Docker (docker system df) --> Local Volumes = 1GB
5. Delete task
6. Check space used on Docker (docker system df) --> Local Volumes = 1GB
7. sudo du -h /var/lib/docker/volumes/cvat_cvat_data/_data/cache --> 1GB

### Context
My computer have a limited space and I cannot store unused files.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` Docker 20.10.2
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04.5 LTS

### Next steps
How Can I properly delete a task? Thank you

**Comment by bsekachev** [comment]
Hi @sirinemrab 

Try:
```
docker exec -it cvat /bin/bash
cd data # and expore what exactly gets your space
```

**Comment by sirinemrab** [comment]
This is what I get before and after deleting the task (nothing deleted)  [](url)
![Screenshot from 2021-06-09 11-03-36](https://user-images.githubusercontent.com/85320686/121277006-10e5f680-c913-11eb-9e0c-87268d5d5328.png)

**Comment by bsekachev** [comment]
Cache probably will be rewritten later when new data requests will be used. You can try to configure cache size editing [settings](https://github.com/openvinotoolkit/cvat/blob/72fdef4335b5b88743829a58a8c707fe32a6f7b4/cvat/settings/base.py#L467)

**Comment by bsekachev** [comment]
I will close the issue, because there is not a response from your side. Do not hesitate to reopen it if you still have questions
