### ISSUE TITLE
Implement better algorithm for changing labels (keep attributes if possible)

### ISSUE THREAD

**Issue by timurlenk07** [openvinotoolkit/cvat#3294]
### My actions before raising this issue
- [*] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [*] Searched [past issues](/issues)

### Expected Behaviour
When changing the type of a label for another with identically set up attributes, the attributes remain the same.

### Current Behaviour
When changing the type of a label for another with identically set up attributes, the attributes are reset.

### Possible Solution
If label type is changed, check for attributes with identical names and types, and then set the value of the attribute of the new label to that of the old one.

### Steps to Reproduce (for bugs)

1. Create a task with at least two types of labels with identical attributes (ex. name "text" with type "Text")
2. Create a label on an image and set some value to the _text_ attribute
3. Change label class, and observe that the attribute is reset

### Context

This is a real hindrance for labelling data for OCR training, and there is already a feature request about it (#2755) but no progress on it for months. Also, it is not that "smart" of a feature, it's just a simple heuristic.

**Comment by bsekachev** [comment]
It could be a feature request to write a smarter algorithm for changing labels. We would be happy if somebody from the community could prepare a patch. I expect this is client-part only (JavaScript, TypeScript) expertise is necessary.

**Comment by nmanovic** [comment]
@timurlenk07 , thanks for your contribution. I will close the issue.
