### ISSUE TITLE
Where to fix pre-loading size

### ISSUE THREAD

**Issue by SaihholdChiu** [openvinotoolkit/cvat#3295]
I deployed CVAT on a server and issue is when multiple annotators loading files, the speed will be very slow, so I want to fix pre-loading size.

**Comment by bsekachev** [comment]
I am not sure it is CVAT issue, usually downloading speed depends on the bandwidth of the server and user's host. What do you expect from CVAT side?

**Comment by bsekachev** [comment]
I will close the issue, because there is not a response from your side. Do not hesitate to reopen it if you still have questions
