### ISSUE TITLE
Remove all annotations inside a range of frames

### ISSUE THREAD

**Issue by Alexander-Petrikov** [openvinotoolkit/cvat#33]
This is very useful option to remove all options from one frame to another.
I want to reannotate part of video. It is not good idea to search for keyframes and turn off them or
delete lines in xml file and upload annotation.

**Comment by nmanovic** [comment]
@Alexander-Petrikov ,

Do I understand correctly that you want to remove annotations from frame N till frame N+K? Are you trying to annotate an existing dataset? I just want to understand your annotation flow.

**Comment by Alexander-Petrikov** [comment]
Yes, I want to remove annotation on video from frame N till frame N+K, very K is big.
I have annotated video. In part of video bounding boxes have too big size and I want to reannotate this part (not all). I don't want to search for keyframes.

**Comment by gudipudiramanakumar** [comment]
Hey, I've submitted pull request #3617  to this issue. Can someone have a look at it

**Comment by nmanovic** [comment]
@gudipudiramanakumar , thanks for your contribution.
