### ISSUE TITLE
Working with 3D Data

### ISSUE THREAD

**Issue by HannesReichert96** [openvinotoolkit/cvat#3315]
I discovered the following 3D annotation mode:
![Selection_171](https://user-images.githubusercontent.com/85691358/121543361-24738900-ca09-11eb-9912-3a630c20246a.png)
However I'm not able to create a task with 3D data (e.g. LiDAR)
Is this already possible already or jet to come?

Apart from this I have a multiple view camera setup and wonder if it is in principle possible to simultaneous view and label synchronize frames from all cameras. in one task. 

If not I would be happy to contribute.

**Comment by bsekachev** [comment]
Hi @HannesReichert96

This mode is not ready to use yet. We are preparing documentation about how to use it and finishing development.
Basically, you need to create a task with .zip archive containing point cloud data (.pcd files) or velodyne format data (.bin files).
An example is the Kitty dataset: https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_drive_0001/2011_09_26_drive_0001_sync.zip 

Different sources (several cameras as I understand) with lidar data are not supported at the same task, probably we are not very acquainted about this use-case. It is great, if you ready to contribute. From our side, we could assist you if any help is needed.

**Comment by bsekachev** [comment]
I'll close the issue. If you still have questions, do not hesitate reopen it.

**Comment by rodrigoGA** [comment]
@bsekachev  Do you have an estimated date to launch this feature?

**Comment by bsekachev** [comment]
The feature is develop branch. It is not a perfect yet, but workable. We are planning to improve it continuously. Refer to documentation to create 3D task.
