### ISSUE TITLE
make my own MOT dateset

### ISSUE THREAD

**Issue by JAYCHOU2020** [openvinotoolkit/cvat#3317]
when i use this tool to make my own MOT dateset,Can this tool help me get visibility rate (between 0-1)?

**Comment by zhiltsov-max** [comment]
Add `visibility` (number) attribute to the labels. Accepted values are [0 ... 1].

https://openvinotoolkit.github.io/cvat/docs/for-users/formats/format-mot/

**Comment by JAYCHOU2020** [comment]
> Add `visibility` (number) attribute to the labels. Accepted values are [0 ... 1].
> 
> https://openvinotoolkit.github.io/cvat/docs/for-users/formats/format-mot/

sorry to ask u again ，how to add visibility？，Is the visibility value calculated manually？

**Comment by zhiltsov-max** [comment]
> how to add visibility？

Add an attribute to each label in the task configuration.

https://openvinotoolkit.github.io/cvat/docs/for-users/user-guide/creating_an_annotation_task/#basic-configuration

> Is the visibility value calculated manually？

No, CVAT does not have such functionality yet. It will be a value you can set manually for an object.

**Comment by JAYCHOU2020** [comment]
> > how to add visibility？
> 
> Add an attribute to each label in the task configuration.
> 
> https://openvinotoolkit.github.io/cvat/docs/for-users/user-guide/creating_an_annotation_task/#basic-configuration
> 
> > Is the visibility value calculated manually？
> 
> It will be a value you can set manually for an object. CVAT does not have functionality to compute visibility yet.

so when i make my own MOT dataset does the visibility (number) attribute is really needed?

**Comment by zhiltsov-max** [comment]
When you export annotations, the `visibility` attribute will be used. If there is no such attribute, occlusion value will be transformed into `visibility` as 0 or 1.

**Comment by nmanovic** [comment]
@JAYCHOU2020 , I believe the question was answered. I will close the issue.
