### ISSUE TITLE
Is there any easy way to disable the ability to download datasets or annotations for the assignee.

### ISSUE THREAD

**Issue by shawnlee103** [openvinotoolkit/cvat#3318]
Thank you for the great project.
According to
https://github.com/openvinotoolkit/cvat/issues/1030
the permission system is not ready.

Is there any easy way(workaround) to disable the ability to download datasets or annotations for the assignee.
change the few codes and rebuild it to get this purpose? Which code should i focus on?
in my opinion, the assignee should not get the datasets or annotations .

Thanks again.

**Comment by SaihholdChiu** [comment]
you can change permission in /admin

**Comment by shawnlee103** [comment]
> you can change permission in /admin

Hi SaihholdChiu,
Thanks for your reply.
the permission system is ready now?


i change permission to 'annotator' for the assignee in /admin.
The assignee still can download datasets or annotations.
It doesn't work.
Could you give me more detail?

Thanks again.

**Comment by SaihholdChiu** [comment]
> > you can change permission in /admin
> 
> Hi SaihholdChiu,
> Thanks for your reply.
> the permission system is ready now?
> 
> i change permission to 'annotator' for the assignee in /admin.
> The assignee still can download datasets or annotations.
> It doesn't work.
> Could you give me more detail?
> 
> Thanks again.

The permission system is existing, open it in /admin, for example, if you deployed CVAT in localhost:8080, then try localhost:8080/admin, there are 4 permissions: admin, user, annotator, observer, only admin accounts have permission to dump images and outputs.

**Comment by SaihholdChiu** [comment]
Hi, last time it was my fault, if you want to disable the permission of annotators you need to fix the code.



发自我的iPhone


------------------ Original ------------------
From: shawnlee103 ***@***.***&gt;
Date: Fri,Jun 18,2021 10:36 AM
To: openvinotoolkit/cvat ***@***.***&gt;
Cc: SaihholdChiu ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [openvinotoolkit/cvat] Is there any easy way to disable the ability to download datasets or annotations for the assignee. (#3318)





  
you can change permission in /admin
  
Hi SaihholdChiu,
 Thanks for your reply.
 the permission system is ready now?
 
i change permission to 'annotator' for the assignee in /admin.
 The assignee still can download datasets or annotations.
 It doesn't work.
 Could you give me more detail?
 
Thanks again.
