### ISSUE TITLE
Hello all,

### ISSUE THREAD

**Issue by KALALRANJITHKUMAR** [openvinotoolkit/cvat#3319]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by KALALRANJITHKUMAR** [comment]
http://localhost:3000/auth/login it is keeps on loading... not opening the login page.. any solution.

**Comment by azhavoro** [comment]
@KALALRANJITHKUMAR Hi,
please provide any logs, error messages or steps to reproduce your issue

**Comment by KALALRANJITHKUMAR** [comment]
(node:13028) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/ubuntu/cvat/cvat-ui/dist
ℹ ｢wds｣: 404s will fallback to /index.html
⚠ ｢wdm｣: Hash: 50ab14c72472524ec82a
Version: webpack 4.44.2
Time: 27799ms
Built at: 06/11/2021 7:43:32 AM
                                              Asset      Size   Chunks                         Chunk Names
    3rdparty/Decoder.worker.bbb3370a33ffb127440a.js  40.3 KiB           [emitted] [immutable]  
3rdparty/Decoder.worker.bbb3370a33ffb127440a.js.map    48 KiB           [emitted] [dev]        
                                  3rdparty/avc.wasm   124 KiB           [emitted]              
                cvat-ui.24d64bfcbb09df27da03.min.js  18.6 MiB  cvat-ui  [emitted] [immutable]  cvat-ui
            cvat-ui.24d64bfcbb09df27da03.min.js.map  17.9 MiB  cvat-ui  [emitted] [dev]        cvat-ui
            download.worker.02a7b3290c18388160cd.js  64.7 KiB           [emitted] [immutable]  
        download.worker.02a7b3290c18388160cd.js.map  65.4 KiB           [emitted] [dev]        
                                         index.html  1.02 KiB           [emitted]              
          unzip_imgs.worker.3e58c31d8129cf963182.js   174 KiB           [emitted] [immutable]  
      unzip_imgs.worker.3e58c31d8129cf963182.js.map   202 KiB           [emitted] [dev]        
Entrypoint cvat-ui = cvat-ui.24d64bfcbb09df27da03.min.js cvat-ui.24d64bfcbb09df27da03.min.js.map
[0] multi (webpack)-dev-server/client?http://localhost:3000 ./src/index.tsx 40 bytes {cvat-ui} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {cvat-ui} [built]
[./node_modules/react-redux/es/index.js] 776 bytes {cvat-ui} [built]
[./node_modules/react-router-dom/esm/react-router-dom.js] 9.76 KiB {cvat-ui} [built]
[./node_modules/react/index.js] 190 bytes {cvat-ui} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {cvat-ui} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:3000] (webpack)-dev-server/client?http://localhost:3000 4.29 KiB {cvat-ui} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {cvat-ui} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {cvat-ui} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {cvat-ui} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {cvat-ui} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {cvat-ui} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {cvat-ui} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {cvat-ui} [built]
[./src/index.tsx] 4.04 KiB {cvat-ui} [built]
    + 4768 hidden modules

WARNING in ../cvat-canvas3d/src/typescript/canvas3d.ts 83:0-105
"export 'ViewsDOM' was not found in './canvas3dView'
 @ ./src/cvat-canvas3d-wrapper.ts
 @ ./src/reducers/annotation-reducer.ts
 @ ./src/reducers/root-reducer.ts
 @ ./src/index.tsx
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 1.15 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 531 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
Child worker:
                                            Asset     Size  Chunks                         Chunk Names
        unzip_imgs.worker.3e58c31d8129cf963182.js  174 KiB    main  [emitted] [immutable]  main
    unzip_imgs.worker.3e58c31d8129cf963182.js.map  202 KiB    main  [emitted] [dev]        main
    Entrypoint main = unzip_imgs.worker.3e58c31d8129cf963182.js unzip_imgs.worker.3e58c31d8129cf963182.js.map
    [../cvat-data/node_modules/jszip/dist/jszip.min.js] 96.8 KiB {main} [built]
    [../cvat-data/src/js/unzip_imgs.worker.js] 1.55 KiB {main} [built]
    [./node_modules/base64-js/index.js] 3.85 KiB {main} [built]
    [./node_modules/buffer/index.js] 47.5 KiB {main} [built]
    [./node_modules/buffer/node_modules/isarray/index.js] 132 bytes {main} [built]
    [./node_modules/ieee754/index.js] 2.02 KiB {main} [built]
    [./node_modules/process/browser.js] 5.29 KiB {main} [built]
    [./node_modules/setimmediate/setImmediate.js] 6.32 KiB {main} [built]
    [./node_modules/timers-browserify/main.js] 1.97 KiB {main} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
Child worker:
                                                  Asset      Size  Chunks                         Chunk Names
        3rdparty/Decoder.worker.bbb3370a33ffb127440a.js  40.3 KiB    main  [emitted] [immutable]  main
    3rdparty/Decoder.worker.bbb3370a33ffb127440a.js.map    48 KiB    main  [emitted] [dev]        main
    Entrypoint main = 3rdparty/Decoder.worker.bbb3370a33ffb127440a.js 3rdparty/Decoder.worker.bbb3370a33ffb127440a.js.map
    [../cvat-data/src/js/3rdparty/Decoder.worker.js] 36.2 KiB {main} [built]
Child worker:
                                          Asset      Size  Chunks                         Chunk Names
        download.worker.02a7b3290c18388160cd.js  64.7 KiB    main  [emitted] [immutable]  main
    download.worker.02a7b3290c18388160cd.js.map  65.4 KiB    main  [emitted] [dev]        main
    Entrypoint main = download.worker.02a7b3290c18388160cd.js download.worker.02a7b3290c18388160cd.js.map
    [../cvat-core/node_modules/axios/index.js] 40 bytes {main} [built]
    [../cvat-core/node_modules/axios/lib/adapters/xhr.js] 5.73 KiB {main} [built]
    [../cvat-core/node_modules/axios/lib/axios.js] 1.47 KiB {main} [built]
    [../cvat-core/node_modules/axios/lib/cancel/Cancel.js] 385 bytes {main} [built]
    [../cvat-core/node_modules/axios/lib/cancel/CancelToken.js] 1.21 KiB {main} [built]
    [../cvat-core/node_modules/axios/lib/cancel/isCancel.js] 102 bytes {main} [built]
    [../cvat-core/node_modules/axios/lib/core/Axios.js] 2.59 KiB {main} [built]
    [../cvat-core/node_modules/axios/lib/core/InterceptorManager.js] 1.22 KiB {main} [built]
    [../cvat-core/node_modules/axios/lib/core/mergeConfig.js] 2.83 KiB {main} [built]
    [../cvat-core/node_modules/axios/lib/defaults.js] 2.5 KiB {main} [built]
    [../cvat-core/node_modules/axios/lib/helpers/bind.js] 256 bytes {main} [built]
    [../cvat-core/node_modules/axios/lib/helpers/isAxiosError.js] 343 bytes {main} [built]
    [../cvat-core/node_modules/axios/lib/helpers/spread.js] 564 bytes {main} [built]
    [../cvat-core/node_modules/axios/lib/utils.js] 8.74 KiB {main} [built]
    [../cvat-core/src/download.worker.js] 778 bytes {main} [built]
        + 14 hidden modules
ℹ ｢wdm｣: Compiled with warnings.
http://localhost:3000/auth/login

**Comment by azhavoro** [comment]
If you are trying to set up development environment follow this guide https://openvinotoolkit.github.io/cvat/docs/for-developers/contributing/#development-environment

**Comment by KALALRANJITHKUMAR** [comment]
Yes @azhavoro

**Comment by azhavoro** [comment]
Make sure that you did all steps properly, are there any error in the visual studio code output?

**Comment by KALALRANJITHKUMAR** [comment]
@azhavoro no errors in vscode output

**Comment by bsekachev** [comment]
@KALALRANJITHKUMAR 

Please check if there are pending requests in the Network tab of dev tools in Chrome. Also please check if there are any errors on the Console tab of dev tools in Chrome. You can open Dev Tools by pressing F12 (windows, linux) or via the menu.

**Comment by KALALRANJITHKUMAR** [comment]
Thank you for your detailed solution, I can see these are in pending status,
http://localhost:7000/api/v1/users/self

After removing this from the network , I got the login page along with errors on dev console and not able to login into cvat.

**Comment by azhavoro** [comment]
I cannot reproduce your issue, please provide exact steps to reproduce

**Comment by nmanovic** [comment]
@KALALRANJITHKUMAR , need clear steps to reproduce the issue. I will close the request. Don't hesitate to reopen it if you can provide step by step instructions for us.
