### ISSUE TITLE
[Feature Request] Retrieve images from MongoDB on 'Create new task' 

### ISSUE THREAD

**Issue by neerajarun2001** [openvinotoolkit/cvat#3321]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When I click 'create new task', I would like to automatically import an image from a URI specified in a MongoDB datastore. The images in the database should be sorted by priority (1-100, low priority is towards 100, high priority is towards 1) before the highest priority record is chosen. The basic configuration should be automatically filled out. 

Essentially, I would like to go directly from 'create a new task' to having an image loaded and ready to label in one step. I understand this may not be possible to incorporate in production releases of the tool itself, but would like guidance on implementing this feature for my own use. 

### Current Behaviour

The current behaviour: I click 'create new task'. Then I fill out the basic configuration fields (name, labels, and source: my computer). Then the tool loads up the selected image or video and I can begin labeling.

### Context

I am trying to use CVAT in a data labeling pipeline. My image data is stored in a MongoDB. I would like to use CVAT to import the images, label them, and export the labeled images back to my servers. I am not sure how to go about this myself. 

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@Marishka17 May this be implemented as cloud source? What do you think?

**Comment by Marishka17** [comment]
> @Marishka17 May this be implemented as a cloud source? What do you think?

@azhavoro , I think it's possible.

**Comment by nmanovic** [comment]
@neerajarun2001 , I have realized that the request is very specific. Probably the test way in your scenario is to use CLI or REST API and create tasks in a script. Thus you will able to load images from any source and after that upload them to CVAT.

I will close the issue. Don't hesitate to contribute us the functionality.
