### ISSUE TITLE
Is there any way to enter a non-english character in the text attribute of each annotated object?

### ISSUE THREAD

**Issue by huyhoang17** [openvinotoolkit/cvat#3323]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

---

Hi, how can I enter a non-English character in the `text` attribute of each annotated object, like Vietnamese character?

![image](https://user-images.githubusercontent.com/15128654/121833250-2170e500-ccf6-11eb-88fe-fa575dfec683.png)

Currently, I want to use CVAT tool for the OCR task (I know CVAT does not fully support the feature like this) by changing the corresponding `text` attribute. But I can't directly set the non-English word into it. I realized that other placeholders like search box, task name or label name can enter a non-English character but can not set it in the attribute. Is there any way so that I can perform this action? Thank you so much!

---

### Related issue
- https://github.com/openvinotoolkit/cvat/issues/248
- https://github.com/openvinotoolkit/cvat/issues/973

**Comment by bsekachev** [comment]
Hi, @huyhoang17 

I tried (on CVAT.org) both Russian and Vietnamese characters which are non-English and it works fine. I am not sure why it does not work on your side. Probably I need more information. What CVAT version, etc. Please, fill out the issue template. 

![Screenshot from 2021-06-15 08-25-44](https://user-images.githubusercontent.com/40690378/121997618-50995c00-cdb3-11eb-8b7d-3c1a1e95f276.png)


![Screenshot from 2021-06-15 08-24-23](https://user-images.githubusercontent.com/40690378/121997613-4e370200-cdb3-11eb-8887-e59efb05140a.png)

**Comment by huyhoang17** [comment]
@bsekachev in my case, I realized that when I used Ubuntu, I can not directly type non-English character in the text attribute (both cvat.org and my server). But when switched to Window, it's okay. Maybe due to the different typing engine of each operation.
