### ISSUE TITLE
Tasks filter does not work correctly after incorrect filter was applied

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#3328]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Applying correct filter after incorrect should work fine

### Current Behaviour
status: "completed" shows all the tasks when there are only two completed tasks actually

### Steps to Reproduce (for bugs)
![Peek 2021-06-15 18-17](https://user-images.githubusercontent.com/40690378/122079561-3472da80-ce06-11eb-87c2-ef47de3be29f.gif)

### Your Environment

- Git hash commit (`git log -1`):  3d496ef
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? N/A
- Operating System and version (e.g. Linux, Windows, MacOS): N/A

**Comment by nmanovic** [comment]
@bsekachev , I will recommend to reimplement the filter. I like the filter of Kanboard. Probably we can add something similar.

![image](https://user-images.githubusercontent.com/40690625/142978983-58b0b637-1cdc-4ed3-a2c2-de6c4eee98d3.png)

**Comment by bsekachev** [comment]
Not relevant after #4409
