### ISSUE TITLE
Can't open a task that is assigned to inactive user

### ISSUE THREAD

**Issue by Leeleman** [openvinotoolkit/cvat#3339]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
There is a bug. In the case you are trying to open a task that is assigned to inactive user (or includes a job that assigned to inactive user):
![image](https://user-images.githubusercontent.com/31480109/122366245-d1538600-cf74-11eb-8885-742efa6e1f52.png)

### Steps to Reproduce (for bugs)

1. Create a task, assign it to some active user
2. Change user active status to false
3. Try to open the task

### Your Environment

- cvat version - release v1.3.0
- browser - Google Chrome v.89.0.4389.128

**Comment by bsekachev** [comment]
Thank you, we will look into it in the nearest future.

**Comment by bsekachev** [comment]
@Leeleman 
The fix is ready. It will be merged after review.
