### ISSUE TITLE
404 error page when connecting to AWS ec2

### ISSUE THREAD

**Issue by Jakubelo** [openvinotoolkit/cvat#3341]
### Expected Behaviour

After configuration end start up the docker. The first page should be where you have to log

### Current Behaviour

Page 404 error

### Possible Solution

 I cut the section in cvat_proxy/conf.d/cvat.conf
to the form:
```
server {
    listen       80;
    server_name  ${CVAT_HOST};

    proxy_pass_header       X-CSRFToken;
    proxy_set_header        Host $http_host;
    proxy_pass_header       Set-Cookie;

    location ~* /api/.*|git/.*|opencv/.*|analytics/.*|static/.*|admin(?:/(.*))?.*|documentation/.*|django-rq(?:/(.*))? {
        proxy_pass              http://cvat:8080;
    }

    location / {
        proxy_pass              http://cvat_ui;
    }
}
```

### Steps to Reproduce (for bugs)

 all points from the installation guide with AWS extension(docker-compose.overrife.yml)

### Your Environment

AWS EC2 t2.medium instance

**Comment by azhavoro** [comment]
First of all make sure that you configured `CVAT_HOST` as described here https://openvinotoolkit.github.io/cvat/docs/for-users/installation/#advanced-settings
If it will not help please attach as files logs from containers: `docker logs cvat_proxy > proxy.log` and `docker logs cvat > cvat.log`

**Comment by Jakubelo** [comment]
@azhavoro I am sure that, the configuration was good. I wrote the AWS IP public address to the CVAT_HOST section configuration.

The first main page which was showing up was the 404 error.

After solution described above, I was able to get the right view after connection.

**Comment by garg-sparsh** [comment]
What did you write in CVAT_HOST instead of AWS IP public address, I have installed cvat version 1.4, and I'm still not able to connect to the port 8080, please help

**Comment by azhavoro** [comment]
> What did you write in CVAT_HOST instead of AWS IP public address, I have installed cvat version 1.4, and I'm still not able to connect to the port 8080, please help

Most likely port 8080 is closed for inbound connections, you should open it in the AWS console.

**Comment by azhavoro** [comment]
> @azhavoro I am sure that, the configuration was good. I wrote the AWS IP public address to the CVAT_HOST section configuration.
> 
> The first main page which was showing up was the 404 error.
> 
> After solution described above, I was able to get the right view after connection.

So, I close the issue
