### ISSUE TITLE
av library issue...

### ISSUE THREAD

**Issue by KALALRANJITHKUMAR** [openvinotoolkit/cvat#3342]
every time it is required to install the library manually using **pip install av** , please look into this. if we dont install it we are facing issues while running manage.py file.

**Comment by bsekachev** [comment]
@azhavoro Could you please look at the issue?

**Comment by azhavoro** [comment]
@KALALRANJITHKUMAR Hi,
Please don't ignore the issue template, please provide error messages and exact steps to reproduce. `av` is one of the many CVAT dependencies, and currently I can't figure out why you need to reinstall if this package is already installed.

**Comment by bsekachev** [comment]
I will close the issue, because there is not a response from your side. Please, do not hesitate to reopen it if you still have questions and ready to provide more details.
