### ISSUE TITLE
Nuclio Link appears to point to the wrong spot

### ISSUE THREAD

**Issue by benhoff** [openvinotoolkit/cvat#3346]
Currently pointing here:

https://github.com/openvinotoolkit/cvat/blob/df175a856179f1c31ac2b15c80d98986a3d35acf/cvat-ui/src/consts.ts#L18

Maybe it should be here instead?
https://openvinotoolkit.github.io/cvat/docs/for-users/installation_automatic_annotation/

Just bouncing around trying to get the project working.

**Comment by nmanovic** [comment]
@TOsmanov , could you please look?

**Comment by benhoff** [comment]
Current link 404's

**Comment by TOsmanov** [comment]
Thank you, I've fixed this and a few other incorrect links in #3320
