### ISSUE TITLE
How to download segmentation masks per object not 

### ISSUE THREAD

**Issue by tugot17** [openvinotoolkit/cvat#3350]
I have an image where a single pixel consist of two classes. My annotators annotate them in  the following way:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/27293258/122827786-1f55ea00-d2e5-11eb-983b-022606d562a5.png">

Masks overlap. How to download the mask per individual object not the whole segmentation mask? Exporting the dataset as Segmenttation 1:1 gives the following result: 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/27293258/122828009-66dc7600-d2e5-11eb-90c7-7fb31009db90.png">

Where the last object is the one "on top". Is there a way to get individual masks for each object so they don't overlap?

**Comment by zhiltsov-max** [comment]
Hi, currently it is only available in COCO format, which stores a separate mask per instance. However, it stores them as RLE-encoded arrays, instead of images. Will it be sufficient for you task?

**Comment by tugot17** [comment]
yeah, coco format solves this problem somehow, thanks
```py
from pycocotools.coco import COCO
```
