### ISSUE TITLE
I don't understand the instruction to add own custom model

### ISSUE THREAD

**Issue by dluo222** [openvinotoolkit/cvat#3354]
I have asked the question before about how to add own custom model in nuclio. But I don't understand the instruction (at this PR #3124) in the reply. Do you mean in order to add my custom DL I have to push my code on git?

**Comment by azhavoro** [comment]
@dluo222 please take a look at this file from the mentioned PR https://github.com/openvinotoolkit/cvat/blob/nm/serverless_tutorial/docs/serverless_tutorial.md

**Comment by KALALRANJITHKUMAR** [comment]
> @dluo222 please take a look at this file from the mentioned PR https://github.com/openvinotoolkit/cvat/blob/nm/serverless_tutorial/docs/serverless_tutorial.md

Could you please share the tutorial link?

**Comment by kosehy** [comment]
> > @dluo222 please take a look at this file from the mentioned PR https://github.com/openvinotoolkit/cvat/blob/nm/serverless_tutorial/docs/serverless_tutorial.md
> 
> Could you please share the tutorial link?

@KALALRANJITHKUMAR below is the serverless_tutorial link
[https://github.com/openvinotoolkit/cvat/blob/nm/serverless_tutorial/site/content/en/docs/manual/advanced/serverless-tutorial.md](https://github.com/openvinotoolkit/cvat/blob/nm/serverless_tutorial/site/content/en/docs/manual/advanced/serverless-tutorial.md)
