### ISSUE TITLE
CVAT opens every image to get dimensions when creating a task

### ISSUE THREAD

**Issue by geometrikal** [openvinotoolkit/cvat#3362]
Adding a lot of images (e.g. 30000) from a shared drive takes a very long time. For many large images stored over a slow connection (e.g. NAS / HDDs) this can take hours or more.

The reason is that CVAT opens each image to get its dimensions.

https://github.com/openvinotoolkit/cvat/blob/e76b0ea5fc31509b0462694ddfd6bbc982492168/utils/dataset_manifest/core.py#L157

Please remove the requirement to open every image when creating a task

**Comment by nmanovic** [comment]
@Marishka17 , could you please comment? I believe manifest file should help here.

**Comment by Marishka17** [comment]
@geometrikal , Hello, you can prepare a [manifest file](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/dataset_manifest/) for the dataset in advance and attach it when creating a task along with the data.

**Comment by Marishka17** [comment]
@geometrikal ,
For each task, an auxiliary manifest file is created containing the necessary information. Image resolution information is required, so it is saved when creating a task.
The pre-prepared manifest file contains the characteristics of the images and will allow you to avoid opening each image.
A link to detailed instructions for preparing such a file was given above.
I'll close this issue now, feel free to re-open in case of problems.
