### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by KALALRANJITHKUMAR** [openvinotoolkit/cvat#3363]
Hello Team,
could you please fix this,

https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation_automatic_annotation.md

**Comment by Marishka17** [comment]
@KALALRANJITHKUMAR , please, see [here](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)
