### ISSUE TITLE
get_prpgress function of VideoReader can compatible with more video format

### ISSUE THREAD

**Issue by Thatwho** [openvinotoolkit/cvat#3376]
### My actions before raising this issue
while extract from video with typical format, like mkv, it can't show precise progress. Like shown in the code:
```python
    def get_progress(self, pos):
        container = self._get_av_container()
        # Not for all containers return real value
        stream = container.streams.video[0]
        return pos / stream.duration if stream.duration else None
```
VideoStream object may not have a real duration value.

### Expected Behaviour

But we can find duration information from metadata of VideoStream object, then we can calculate precise progress instead of showing "Images are being compressed |/-\\"

**Comment by azhavoro** [comment]
@Thatwho Hi, thanks for the suggestion, would you like to prepare a PR for this?

**Comment by Thatwho** [comment]
> @Thatwho Hi, thanks for the suggestion, would you like to prepare a PR for this?

Of course! I had made a PR which is #3381. Please let me know the PR has any error.
