### ISSUE TITLE
DEXTR: extreme points not aligning with mask

### ISSUE THREAD

**Issue by RGring** [openvinotoolkit/cvat#3382]
Hi,
October 2020, I used DEXTR within Cvat on my data and it worked like a charm.

Now, I used it again and it is not performing as good. The generated masks are not even aligned with the defined extreme points (see attached image). Furthermore, it is much slower, although I have a significantly more powerful PC. 

What changed? Can I make settings to get the previous performance. 

I appreciate your work and help!

![image](https://user-images.githubusercontent.com/19685020/124083314-028c8580-da4e-11eb-9b6b-7e289afca605.png)

**Comment by bsekachev** [comment]
Hi @RGring 

Could you please share an original image?

**Comment by bsekachev** [comment]
Just tried this piece of the image and it works fine:

![Screenshot from 2021-07-01 10-50-42](https://user-images.githubusercontent.com/40690378/124086937-3372b780-da5a-11eb-8cb8-1fb052ea7090.png)

Server version: 1.5.dev20210630112742
Core version: 3.13.3
Canvas version: 2.4.5
UI version: 1.20.5

Please, be sure you use the version after the latest DEXTR fixes #3325

**Comment by RGring** [comment]
@bsekachev thanks for your answer.
My versions are slightly behind, although I built the latest develop-branch. Do you use a different branch?

Server version: 1.5
Core version: 3.13.0
Canvas version: 2.4.3
UI version: 1.20.1

**Comment by bsekachev** [comment]
@RGring 

Yes, the branch I tested on is not exactly develop, but changes in this branch don't affect DEXTR functionality. 
Does updating solve your issue?

**Comment by RGring** [comment]
@bsekachev 
Nice yes! I was missing the redeployment of the serverless function. Thanks a lot for your support!
