### ISSUE TITLE
Convert shape to track

### ISSUE THREAD

**Issue by esuhio** [openvinotoolkit/cvat#3388]
Hi, I have a video sequence loaded and labeled one frame using polygon 'shape'.

Now I want to convert this 'shape' to 'track' in order to interpolate between keyframes. How is this possible?

**Comment by bsekachev** [comment]
@esuhio 

Please, read about ["Merge"](https://openvinotoolkit.github.io/cvat/docs/manual/basics/track-mode-basics/).
It works for shapes, but you need at least two shapes on different frames with the same label (in the case with polygon start point and drawing direction also must be the same) to make a track. Another option is to create a polygon track from scratch. 

For more information read [here](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/annotation-with-polygons/track-mode-with-polygons/)

**Comment by bsekachev** [comment]
I will close the issue, because there is not a response from your side. Do not hesitate to reopen it if you still have questions
