### ISSUE TITLE
Can't access any of the tasks in a project

### ISSUE THREAD

**Issue by GuillaumeChampain** [openvinotoolkit/cvat#3389]
Hi, when annotating my frames, I got a sudden error "Error: Request failed with status code 403. {"detail":"You do not have permission to perform this action."}", when trying to save the annotations. I could annotate the first 71 frames but I suddenly got this error. I logged out and in again, and now none of the tasks work. I get a :

> Could not receive repository status
> Error: Request failed with status code 403. "\n<!doctype html>\n<html lang=\"en\">\n<head>\n <title>403 Forbidden</title>\n</head>\n<body>\n <h1>403 Forbidden</h1><p></p>\n</body>\n</html>\n".

Any idea of what could cause the problem ? Thank you !

**Comment by bsekachev** [comment]
Hi @GuillaumeChampain 

Please, provide more information. Is this your own server or cvat.org? If the first, please provide the version and fill out the issue template.

**Comment by bsekachev** [comment]
I will close the issue, because there is not a response from your side. Please, do not hesitate to reopen it if you still have questions and ready to provide more details.
