### ISSUE TITLE
 Division of engine_labeledshape  table  into several tables

### ISSUE THREAD

**Issue by chaoyifei** [openvinotoolkit/cvat#3395]
With the growth of time, there will be a lot of data in this table, which will affect the query efficiency. Do you want to consider division of engine_labeledshape  table  into several tables

**Comment by bsekachev** [comment]
We do not consider it because we do not see performance issues here (having several quite high-loaded CVAT servers). Do you have any research measures that make you worried?

**Comment by bsekachev** [comment]
I will close the issue, because there is not a response from your side. Do not hesitate to reopen it if you still have questions
