### ISSUE TITLE
Support for rosbag files, created by Intel Realsense Viewer

### ISSUE THREAD

**Issue by wl2776** [openvinotoolkit/cvat#3396]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I'd like to annotate RGBD data from the Intel Realsense D435/D455 cameras.
Intel Realsense SDK contains viewer application that can save data streams from these cameras in ROS1 Bag format.
However, CVAT doesn't support it.
I've tried uploading bag file, but have got the error "No media data found"

### Expected Behaviour
Process these data in a fashion, similar to video processing.

### Current Behaviour
Very long pause, then error "No media data found"

### Possible Solution
 Add Realsense support using SDK

### Your Environment
- Git hash commit (`git log -1`):
    ```
    commit 7f4b1853aba06584afb7698bd07358cb2f4ae7ca (HEAD -> develop, origin/develop, origin/HEAD)
    Author: Andrey Zhavoronkov <andrey.zhavoronkov@intel.com>
    Date:   Thu Jul 1 17:29:05 2021 +0300

    Fixed cvat_ui image build in case of OOM error (#3379)

    * fixed cvat_ui image build in case of OOM error

    * updated changelog

    ```
   Local changes:
   ```
    diff --git a/components/serverless/docker-compose.serverless.yml b/components/serverless/docker-compose.serverless.yml
    index 8938d5c5..98ec09ee 100644
    --- a/components/serverless/docker-compose.serverless.yml
    +++ b/components/serverless/docker-compose.serverless.yml
    @@ -2,7 +2,7 @@ version: '3.3'
     services:
       serverless:
         container_name: nuclio
    -    image: quay.io/nuclio/dashboard:1.5.16-amd64
    +    image: quay.io/nuclio/dashboard:1.6.11-amd64
         restart: always
         networks:
           default:
    diff --git a/cvat_proxy/conf.d/cvat.conf.template b/cvat_proxy/conf.d/cvat.conf.template
    index 0c7ab685..bb496e87 100644
    --- a/cvat_proxy/conf.d/cvat.conf.template
    +++ b/cvat_proxy/conf.d/cvat.conf.template
    @@ -1,9 +1,3 @@
    -server {
    -    listen       80;
    -    server_name  _ default;
    -    return       404;
    -}
    -
    ```

- Docker version 20.10.7
- Are you using Docker Swarm or Kubernetes?
    No
- Operating System and version (e.g. Linux, Windows, MacOS):
    Ubuntu 20.04, all recent updates

**Comment by nmanovic** [comment]
@wl2776 , sorry. I'm not sure we are going to support Intel RealSense rosbug in the nearest future. Try to use official scripts from RealSense SDK to extract images. If we see that a lot of community members need the feature, we will consider to add the option. Also you can try to contribute the feature by yourself.
