### ISSUE TITLE
Set labels to all the frames in the task automatically 

### ISSUE THREAD

**Issue by Chumik** [openvinotoolkit/cvat#3400]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am working with CVAT and for our annotators we preset labels, where annotators annotate frames with data within the label. 
### Expected Behaviour

If there is a way to preset labels or automatically set the labels to each frame in the task, I would appreciate any advice on how to do it

### Current Behaviour

After I create the task, I have to go to the task, open all the job, where I set a label (tag) to the frame and propagate to all the frames in the job. Doing so for many jobs and tasks takes a lot of time.

**Comment by bsekachev** [comment]
Maybe using REST API.. 
Something like that (for the task with id **370**:
The first label in the task is used. You can customize logic.

In the browser console (in opened CVAT tab, being logged in and having annotations write access for the task): 

```js
async function appendDefaultTags() {
    const jobs = await fetch('/api/v1/tasks?id=6').then((response) => response.json())
        .then((data) => data.results[0].segments.map((segment) => [data.results[0].labels[0].id, segment.start_frame, segment.stop_frame, segment.jobs[0]]));
    for (const [labelID, startFrame, stopFrame, job] of jobs) {
        const tags = [];
        const annotations = await fetch(`/api/v1/jobs/${job.id}/annotations`).then((response) => response.json());
        for (let frame = startFrame; frame <= stopFrame; frame++) {
            tags.push({
                attributes: [],
                frame,
                group: 0,
                label_id: 1, 
            })
        }
        const data = { version: annotations.version + 1, tracks: [], shapes: [], tags };
        await fetch(`/api/v1/jobs/${job.id}/annotations?action=create`, { 
            method: 'PATCH',
            body: JSON.stringify(data),
            headers: { 'Content-Type': 'application/json', Authorization: `Token ${localStorage.getItem('token').slice(1, -1)}` } 
        })
    }
}
appendDefaultTags()
```

**Comment by Chumik** [comment]
> Maybe using REST API..
> Something like that (for the task with id **6**:
> The first label in the task is used. You can customize logic.
> 
> In the browser console (in opened CVAT tab, being logged in and having annotations write access for the task):
> 
> ```js
> async function appendDefaultTags() {
>     const taskID = 6;
>     const jobs = await fetch(`/api/v1/tasks?id=${taskID}`).then((response) => response.json())
>         .then((data) => data.results[0].segments.map((segment) => [data.results[0].labels[0].id, segment.start_frame, segment.stop_frame, segment.jobs[0]]));
>     for (const [labelID, startFrame, stopFrame, job] of jobs) {
>         const tags = [];
>         const annotations = await fetch(`/api/v1/jobs/${job.id}/annotations`).then((response) => response.json());
>         for (let frame = startFrame; frame <= stopFrame; frame++) {
>             tags.push({
>                 attributes: [],
>                 frame,
>                 group: 0,
>                 label_id: 1, 
>             })
>         }
>         const data = { version: annotations.version + 1, tracks: [], shapes: [], tags };
>         await fetch(`/api/v1/jobs/${job.id}/annotations?action=create`, { 
>             method: 'PATCH',
>             body: JSON.stringify(data),
>             headers: { 'Content-Type': 'application/json', Authorization: `Token ${localStorage.getItem('token').slice(1, -1)}` } 
>         })
>     }
> }
> appendDefaultTags()
> ```

I was trying something similar, but a bit simpler

        url = self.api.tasks_id_annotations(task_id)
        data = {
                    "version": 3,
                    "tags": [
                        {
                            "frame": 0,
                            "label_id": 5,
                            "group": 0,
                            "attributes": []
                        }
                    ],
                    "shapes": [],
                    "tracks": []
                }
        response = self.session.put(url,data)
        print(response)
        response_json = response.json()
        print(response_json)
        response.raise_for_status()

However, I keep getting an error that would not allow me to put a tag

<Response [400]>
{'tags': ['This field is required.'], 'shapes': ['This field is required.'], 'tracks': ['This field is required.']}
400 Client Error: Bad Request for url: .../api/v1/tasks/77/annotations


Do you know what might be the issue?
