### ISSUE TITLE
Missing Ai tools on new installation

### ISSUE THREAD

**Issue by georgecloudservices** [openvinotoolkit/cvat#3404]
### My actions before raising this issue
-  Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
-  Searched [past issues](/issues)

I just installed cvat based on Installation Guide and there is no ai tools button just like the webpage. My server version is 1.5. Should I do any extra steps?

Thanks!

**Comment by JK-97** [comment]
what is the  ai tools button?

**Comment by georgecloudservices** [comment]
this button exist in online version but when I installed it on my computer I can not find it
https://imgur.com/a/V5XS4vZ

**Comment by nmanovic** [comment]
https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

I will close the issue. Don't hesitate to ask on our public gitter if you have more questions:  https://gitter.im/opencv-cvat/public

**Comment by davidggphy** [comment]
Thanks for the answer, @nmanovic .
Is it possible to run the Automatic annotation tools in the same machine where CVAT is running, this is, without the use of nuclio.
Thanks in advance!
