### ISSUE TITLE
CVAT can't add share path

### ISSUE THREAD

**Issue by SjoerdBraaksma** [openvinotoolkit/cvat#3406]
Sorry if this is a beginner question, but the answers posted to this question did not help me, so I have no other way of asking for additional help.

I am trying to set up CVAT on my local windows machine, and by any means I cannot add a share folder. I have tried many options:
1) using the folder I wanted
2) creating a folder in the home directory of my git bash, and just using that name in the override.yml file
3) using " ", \ instead of /, you name it
Anyone know what I am doing wrong?
the /mnt folder is very much there, and it's not read-only

As can be seen in the image below:

![image_cvat](https://user-images.githubusercontent.com/41111399/125164234-80106e00-e191-11eb-816a-cfce1e277d01.png)

thank you in advance for the help!

**Comment by davodogster** [comment]
I have also been unsuccessful mounting cvat docker to windows (Running the Docker for WSL 2 though). But I have had success on my linux machine. I see that by default your docker is trying to mount it to C: first, but in the second image you are specifying E so it's looking for a directory that doesn't exist. Maybe try different file path configurations and look into your docker settings to make sure docker has permission to access the mount location (E.g E drive) 
![image](https://user-images.githubusercontent.com/46079516/125368296-0c0ed980-e3ce-11eb-85eb-3af666c473d5.png)

**Comment by SjoerdBraaksma** [comment]
Hey Davodogster!

I think I have found the problem: When using WSL2 your docker runs inside the Linux shell. Therefore, the docker container's only scope is inside that shell, and not your drivers on your windows OS

**Comment by davodogster** [comment]
@SjoerdBraaksma Ok that makes sense! So are you able to mount WSL Docker to Windows or not?

**Comment by bsekachev** [comment]
Please, use Gitter, or StackOverflow to ask for help. GitHub issues are more for bugs/feature requests. 
I will close the issue.
