### ISSUE TITLE
Replace Nginx with Traefik

### ISSUE THREAD

**Issue by tadejsv** [openvinotoolkit/cvat#3407]
Would you be interested in replacing Nginx proxy with [Traefik](https://doc.traefik.io/traefik/)?

Short pitch: Traefik can be a perfect substitute for Nginx, and unlike Nginx it is Docker-native. You can easily put all configuration inside the docker-compose file, and adding HTTPS/TLS is as easy as adding a few lines of configuration, no multi-step manual process is needed.

I have a perfectly functioning version of CVAT where I replaced Nginx with Traefik, and it runs great, without any issues. If you would be interesting in implementing Traefik here I can open a PR for it (and also tackle changing tests and updating documentation).

**Comment by nmanovic** [comment]
@tadejsv , Thanks for the issue and willing to contribute into our project. Personally I don't want to change something if we don't have really strong reasons to do that. I understood the point about configuration and docker-native. Which other benefits do you see in the integration?

Also I would love to look at the code. You always can fork CVAT, make changes which you like and send us your PR.

**Comment by tadejsv** [comment]
@nmanovic Ofc, I understand that you want to keep CVAT stable.

But thank you giving some consideration to the idea. As for the benefits:
- very easy https setup (see example below) - Traefik gets certificates from letsencrypt itself (based on your configuration), and also takes care of their renewal.
- you also get a nice dashboard for free :) This can be very useful when you are setting up CVAT (or anything else), and need to debug what went wrong - so is it the problem with the service, or did you misconfigure the proxy.
- Something more speculative: easy kubernetes integration. Traefik has native kubernetes integration, which might mean it's much easier to integrate in it than Nginx. But that's just "speculation", as I do not have experience with Kubernetes.

I followed your suggestion and created [a fork](https://github.com/tadejsv/cvat). I added two files there:
- `docker-compose.traefik.yml`: this can be a drop-in replacement for `docker-compose.yml`. It requires not outside configuration files. Right now the host is hardcoded to `localhost`, but you can change this to env variable
- `docker-compose.traefik-https.yml`: this is a slight extension of the previous file, and is a fully functioning example that will have HTTPS enabled - no manual generation of certificates needed, and as you can see the change in configuration is minor as well. The host is hardcoded to `example.com`, but you can set that by env variable (I just wanted to make a quick example)

**Comment by nmanovic** [comment]
@tadejsv , thanks. Could you please create a PR with your changes? Need to remove nginx and see if it works after that.

@azhavoro , could you please look at the issue?

**Comment by tadejsv** [comment]
@nmanovic Thanks, I will create a PR during this week.
