### ISSUE TITLE
account create on cvat.org cannot sign in cvat local

### ISSUE THREAD

**Issue by hunterchenghx** [openvinotoolkit/cvat#3410]
excuse me!
I created an account on cvat.org and tried some simple tasks.
Today, I installed the cvat on my local PC following the installation guide. I run the docker-compose up -d, and successfully accessed to the login page on Chrome. However, I cannot login with my account created on cvat.org.

![image](https://user-images.githubusercontent.com/45347759/125434469-bfddd10a-2641-4f6d-910c-b10607c172da.png)

Does it mean that they don't share the same account?

**Comment by nmanovic** [comment]
@hunterchenghx , your CVAT instance has own local database with users. It isn't connected to cvat.org. You can think about your local CVAT instance as an application which runs on your computer. It doesn't try to communicate with any external servers. CVAT.org is our instance which we shared with our community for free.
