### ISSUE TITLE
API POST image to Task

### ISSUE THREAD

**Issue by CarolusM** [openvinotoolkit/cvat#3418]
Hi all,

I am trying to create a Task and upload some images to CVAT using Python and Requests. My current workaround is that I create a Task by:

`res = requests.post("http://localhost:8080/api/v1/tasks", auth=("user","pass"),json={"name":"task_1","labels":[{"name":"person"}]})`

When I go to the CVAT UI, the Task is correctly created and its ID is 7. Then I try to upload one image from my computer (using its path) by:

`res = requests.post("http://localhost:8080/api/v1/tasks/7/data", auth=("user","pass"), json={'image_quality':100, 'server_files[0]': img_local_path})`

The response to my request is: <Response [202]> Which is typically used for actions that take a long while to process but that have been accepted. 
However, I have tried several times in the last hours and I cannot see any image uploaded to the CVAT task yet. 
Am I missing something? Did I do a good POST request? Any info or hint would be greatyly appreciated, as I do not have much experiencie dealing with API RESTs

Thank you all in advance!

**Comment by azhavoro** [comment]
@CarolusM Hi,
Why you dont use https://openvinotoolkit.github.io/cvat/docs/manual/advanced/cli/ to create a task? You may also be interested in the implementation of this functionality https://github.com/openvinotoolkit/cvat/blob/develop/utils/cli/core/core.py#L73

**Comment by bsekachev** [comment]
I will close the issue since there is not a response from your side. 
If you believe CVAT has a bug, please create a corresponding issue, for support questions it is better to ask on gitter. I personally would suggest you to be sure that redis workers (default) are run and check their queues (at least via admin page). In default configuration it should work, if it does not, let's investigate.

**Comment by CarolusM** [comment]
Hi, I solved my issue by using 'cvat/utils/cli.py'.
In the end it was easier than expected

**Comment by azhavoro** [comment]
> Hi, I solved my issue by using 'cvat/utils/cli.py'.
> In the end it was easier than expected

👍
