### ISSUE TITLE
Could not create the task, Open the Browser Console to get details.

### ISSUE THREAD

**Issue by debashisbd** [openvinotoolkit/cvat#3419]
### When I am trying to create a task on my local host CVAT , I am getting an error that says "Could not create the task, Open the Browser Console to get details."

In the console it gives RESET_ERRORS
Check the screenshot below :
![CVAT](https://user-images.githubusercontent.com/58014025/125697060-525c647d-6964-4b9d-a453-e104ceab4d70.png)

**Comment by bsekachev** [comment]
> In the console it gives RESET_ERRORS 

It shows the error above in red.
I see some issues with connection to localhost:6379, and I suppose this is the port of Redis, please, be sure you have done all the steps correctly from CONTRIBUING guide and installed Redis

**Comment by bsekachev** [comment]
I will close the issue, do not hesitate to reopen it if you still have problems

**Comment by BeckyJiangT** [comment]
> ### When I am trying to create a task on my local host CVAT , I am getting an error that says "Could not create the task, Open the Browser Console to get details."
> In the console it gives RESET_ERRORS
> Check the screenshot below :
> ![CVAT](https://user-images.githubusercontent.com/58014025/125697060-525c647d-6964-4b9d-a453-e104ceab4d70.png)
