### ISSUE TITLE
Change segments size or create tasks with segments that do not have constant size

### ISSUE THREAD

**Issue by Chumik** [openvinotoolkit/cvat#3420]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
- [x] Experimenting with api - task and jobs
- [x] checking the Django administrator page (one can change segments size manually, I want to automatize the process)

I have to make multiple jobs within the task and those jobs must be different size (specific frames included in the job). 

### Expected Behaviour

I change the segment size in the api for the specific task - and I expect that segment size go to the once I set

    def split_segments(self, task_id, segments_new,**kwargs):
        print('working with task ID: ',task_id)
        url = self.api.tasks_id(task_id)
        print(url)
        response = self.session.get(url)
        response_json = response.json()
        segments_old = response_json['segments']
        data_id = response_json['data'] 
        name = response_json['name']
        print("size is", size, "frames. Segments are:",segments_old)
        
        data = { 
                'segments': [{'start_frame': 0, 'stop_frame': 15, 'jobs': [{'assignee': None, 'reviewer': None, 'status': 'annotation'}]}],
                'name': name,
               }
        
        response = self.session.put(url, json = data)
        print(response)
        print(response.raise_for_status())
        response_json = response.json()
        print(response_json)
        

### Current Behaviour

However, segment size does not change... 

### Possible Solution

In Django admin page there is an option to change segment size manually - so I assume it is 100% possible. However, I do not understand why my way does not work, and currently do not have ideas for other ways to do it with code. 

### Context

I have sets of frames that have to go together, so the annotator puts one single annotation for the whole set. The annotator puts the annotation on the last frame. 
Currently we make 1 task for 1 set (~20-50 frames). However, there are many sets, so we want to put them in one task in different jobs to make it more comfortable for the annotators.

**Comment by bsekachev** [comment]
@Chumik 

I would suggest considering creating different tasks for these purposes. 
CVAT architecture does not assume changing job size, it can lead to different bugs.

**Comment by Chumik** [comment]
> @Chumik
> 
> I would suggest considering creating different tasks for these purposes.
> CVAT architecture does not assume changing job size, it can lead to different bugs.

That what we currently do, having them in separate tasks. 

Why then there is an opportunity to change segments in the Django administrator page? 
![image](https://user-images.githubusercontent.com/58881110/125779619-69a88877-2ab0-4b83-bfc2-1781a4207de0.png)

**Comment by bsekachev** [comment]
@Chumik 

> Why then there is an opportunity to change segments in the Django administrator page?

This is not a feature, this is a bug :)

We pay little attention to this part of UI because it is rarely used and auto-generated by Django framework.

**Comment by Chumik** [comment]
> @Chumik
> 
> > Why then there is an opportunity to change segments in the Django administrator page?
> 
> This is not a feature, this is a bug :)
> 
> We pay little attention to this part of UI because it is rarely used and auto-generated by Django framework.

Thank you for the reply!

**Comment by Chumik** [comment]
> @Chumik
> 
> > Why then there is an opportunity to change segments in the Django administrator page?
> 
> This is not a feature, this is a bug :)
> 
> We pay little attention to this part of UI because it is rarely used and auto-generated by Django framework.

Actually, is there a way to make a bug to be a feature? 
How hard it is to make changes to an architecture? 

Maybe any advice on what I can try?

**Comment by bsekachev** [comment]
> > @Chumik
> > > Why then there is an opportunity to change segments in the Django administrator page?
> > 
> > 
> > This is not a feature, this is a bug :)
> > We pay little attention to this part of UI because it is rarely used and auto-generated by Django framework.
> 
> Actually, is there a way to make a bug to be a feature?
> How hard it is to make changes to an architecture?
> 
> Maybe any advice on what I can try?

Initially it was not intentioned in CVAT architecture, so, I think this is very huge change that brings a lot of problems with existing annotated objects.
