### ISSUE TITLE
How can I render ellipse as visualization for polygon annotation

### ISSUE THREAD

**Issue by lravindr** [openvinotoolkit/cvat#3431]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

My team is using the annotations for drawing an ellipse around a desired object. Currently, we generate the polygon based (8-point) annotations and use a separate backend for generating the ellipses. Our intent is to use JS's openCV module to render an ellipse instead of the polygon when 8 points are available. 

We have modified CVAT for our use case and we will be able to modify the source code for our use case. While I am exploring this, I wanted to get some pointers or help on the implementation direction. Could you please help in this regard?

**Comment by nmanovic** [comment]
@bsekachev , could you please advise?

**Comment by bsekachev** [comment]
@Iravindr, 

Hi, I do not think you need OpenCV.js here.
SVG library we use (svg.js) [supports ellipses](https://svgjs.dev/docs/3.0/shape-elements/#svg-ellipse). I believe the feature should be implemented exactly the same way as for boxes, polygons, etc.

**Comment by lravindr** [comment]
Thank you Boris and Nikita. I will close the issue now. This should work for me.
