### ISSUE TITLE
DJANGO_AUTH_DEFAULT_GROUPS not working

### ISSUE THREAD

**Issue by manybodycpa** [openvinotoolkit/cvat#3432]
I added a default group for users in cvat/settings/base.py as advised on gitter:

`DJANGO_AUTH_DEFAULT_GROUPS = ['USER']`

However, even after rebuilding, this has no effect. New users do not have a default group.

Server version: 1.4
Core version: 3.12.1
Canvas version: 2.4.3
UI version: 1.19.1

Steps to reprocuce:

* install CVAT 1.4 as per instructions
* change cvat/settings/base.py as above
* rebuild using `docker-compose -f docker-compose.yml -f docker-compose.dev.yml build`
* create new user via UI (self-registration)
* verify user group on admin page: no value selected

**Comment by azhavoro** [comment]
@manybodycpa Hi,
please provide exact steps to reproduce

**Comment by manybodycpa** [comment]
@azhavoro I have added the steps involved. Please let me know if more information is needed

**Comment by azhavoro** [comment]
Seems you missed recreating the containers based on the new images you created:
`rebuild using docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d`
or one line command `rebuild using docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

**Comment by manybodycpa** [comment]
But is this command not identical to the one I have above?

**Comment by azhavoro** [comment]
> But is this command not identical to the one I have above?

this command just builds images:
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml **build**`
after that you need to recreate containers with
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml **up -d**`

Does this solve the issue?

**Comment by manybodycpa** [comment]
OK, my bad. I was not aware of this. I had to modify docker-compose.dev.yml because I had renamed the container image. Now everything is working as expected. Thanks you so much.
