### ISSUE TITLE
Could not save annotations Error: Network Error.

### ISSUE THREAD

**Issue by garg-sparsh** [openvinotoolkit/cvat#3443]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Whenever I try to save the annotations, it throws Could not save annotations Error: Network Error.
### Expected Behaviour

I had deployed the tool on gcp remote server, its deployed successfully, I deployed the tool on my intranet server too where I was able to save the annotations easily, I think its some issues with the gcp

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Linux, Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by garg-sparsh** [comment]
While running :
sudo python3 -m pip install setuptools docker-compose

This issue is occuring:

    error: can't find Rust compiler

    If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

    To update pip, run:

        pip install --upgrade pip

    and then retry package installation.

    If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

    This package requires Rust >=1.41.0.

    ----------------------------------------
  Can't rollback cryptography, nothing uninstalled.
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k3ahrmw9/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_r7vn_0q-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-k3ahrmw9/cryptography/

**Comment by azhavoro** [comment]
Hi, regarding first problem please provide any logs or error messages.
Regarding the second: I'm not sure this is cvat related issue, please follow the docker-compose installation guide https://docs.docker.com/compose/install/

**Comment by bsekachev** [comment]
I hope you solved your problems. I will close the issues because there is not response from your side. Do not hesitate to reopen if you still have questions.
