### ISSUE TITLE
Unable to login with new password after password reset at cvat.org

### ISSUE THREAD

**Issue by jaiswati** [openvinotoolkit/cvat#3445]
Hi @nmanovic ,

We are Unable to login with new password after password reset at cvat.org with userid monikapandey234@gmail.com.. 
Need help with recovering this account.

Best Regards,
Swati

**Comment by nmanovic** [comment]
@azhavoro , could you please help?

**Comment by azhavoro** [comment]
@jaiswati Hi, I just checked that the reset password is working as expected. Have you tried resetting your password again?

**Comment by nmanovic** [comment]
@jaiswati , I will close the issue. Don't hesitate to re-open it if the answer doesn't solve your issue.

**Comment by jaiswati** [comment]
@nmanovic , this user has reported that they tried resetting the password multiple times, but that did not work for them. So is that possible to reset the password from admin side?

**Comment by nmanovic** [comment]
@jaiswati , send me a private message and I will reply with a new random password. Don't forget to change it after that.

**Comment by jaiswati** [comment]
> @jaiswati , send me a private message and I will reply with a new random password. Don't forget to change it after that.

Hi @nmanovic , just sent a response to this. waiting for response

**Comment by jaiswati** [comment]
Thank you, @nmanovic
