### ISSUE TITLE
CVAT keeps loading and images are not uploading when I submit a task in development server.

### ISSUE THREAD

**Issue by debashisbd** [openvinotoolkit/cvat#3453]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The task should create smoothly when click on the submit button.

### Current Behaviour

When I am submitting the task with images, the submit button keeps loading.
If I check the task list page, I see the task was created but images are not uploading.

### Context

I am trying to customize CVAT for our surgery tool anticipation and can not go forward for this problem.

### Your Environment

-Ubuntu 20.04
- Other diagnostic information / logs:
    <details>
    <summary>Showing an issue in the browser console, Logs from browser console:</summary>
    <summary>SharedArrayBuffer usage is restricted to cross-origin isolated sites
SharedArrayBuffers (SABs) can be used to construct high-resolution timers. High-resolution timers simplify Spectre attacks on cross-origin resources.
To mitigate security risks across browsers, SharedArrayBuffers are gated behind cross-origin isolated contexts starting with Chrome 92 (July 2021). To continue using SharedArrayBuffers, please ensure that this page opts-into cross-origin isolation by setting Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy appropriately.
Note that for each iframe, only the first issue is reported for performance reasons.</summary>
    </details>
![cvat](https://user-images.githubusercontent.com/58014025/126631125-7cdb95eb-d3a4-4690-8bb2-009aeb4c0e87.png)

**Comment by bsekachev** [comment]
@debashisbd 

Be sure you have launched RQ workers which are responsible for long-term processes (task creating, dumping, automatic annotation, etc.) 
RQ worker: default is responsible for task creating. 
![Screenshot from 2021-07-22 16-02-13](https://user-images.githubusercontent.com/40690378/126643416-6109c65a-8ff6-4763-b943-820fc8f4606a.png)

**Comment by debashisbd** [comment]
Thanks for the reply. Can you give me an example command to start rq worker and which mode to use?
Thank you.

**Comment by debashisbd** [comment]
I found it : 

python manage.py rqworker default

Now it works perfectly. 
Thanks
