### ISSUE TITLE
Can not dump annotations in "CVAT for video 1.1" format

### ISSUE THREAD

**Issue by PMazarovich** [openvinotoolkit/cvat#3456]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hello, here is a strange situation: 
I have some annotations  in cvat for video format, that I can upload successfully to the task, that contains only one job. After I need to dump this annotations back and after some tome I receive this error:
```
2021-07-22 15:04:59,098 DEBG 'rqworker_default_0' stderr output:
WARNING - 2021-07-22 15:04:59,097 - worker - Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 9)
```
Also, all RAM was consumed in host machine. 
Here is a screenshot:
![Screenshot from 2021-07-22 18-47-44](https://user-images.githubusercontent.com/57707673/126761871-941cb0aa-c5ad-4647-a741-4766ab3016e8.png)

### Expected Behaviour
I need to be able to dump back annotations as I successfully uploaded them. 

### Current Behaviour
Out of memory

### Steps to Reproduce (for bugs)
I has xml file, but guthub restricts to upload it here as it is 54Mb. Where I can send this file to you?

### Possibly connected issue
I can not upload this xml to multi-job task: the same out of memory error. Should I create another issue about that?

### Your Environment

cvat release 1.4.0 on docker

**Comment by zhiltsov-max** [comment]
Hi, please add more info about the task configuration - its size and job parameters.

If you can share the annotations, try to send a link in a private mail. If the uncompressed xml weights 54mb, try to compress it with zip.

**Comment by PMazarovich** [comment]
Hello, here is annotations file:
[large_annotations.zip](https://github.com/openvinotoolkit/cvat/files/6953574/large_annotations.zip)
To reproduce such behavior (first issue), just create a task with 13086 frames (one job), import annotations there and try to dump them back. Please, pay attention on RAM consumption during dump.
As for second question, divide task on multiple jobs, as example, with segment size 3000 and try to upload the same annotations there.
