### ISSUE TITLE
How to get video name for frame name instead of frame_000000

### ISSUE THREAD

**Issue by vinodkreddy** [openvinotoolkit/cvat#3458]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

when annotating multiple videos with different tasks the output XML file names should automatically include video name or task name in it then it is easy to distinguish. Ex: video1_frame_0001, video2_frame_0001
 
### Current Behaviour

when annotating multiple videos with different tasks the output XML file names (frame_000000, frame_000001) are same for 
all tasks. It is not possible to combine them while training a DL model on all video data.

### Possible Solution

append task name or video name to frames
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
I am using CVAT web version
### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi @vinodkreddy 

1. Dumped file name by default contains task name
2. Dumped xml contains source file name ``<source>VID_20201001_165046.mp4</source>``

**Comment by vinodkreddy** [comment]
> Hi @vinodkreddy
> 
> 1. Dumped file name by default contains task name
> 2. Dumped xml contains source file name `<source>VID_20201001_165046.mp4</source>`

Thank you bsekachev,

My sample xml output file:

<annotation>
  <folder>frame</folder>
  <filename>frame_000027.PNG</filename>
  <source>
    <database>Unknown</database>
    <annotation>Unknown</annotation>
    <image>Unknown</image>
  </source>
  <size>
    <width>1280</width>
    <height>720</height>
    <depth></depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>Airplane</name>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <bndbox>
      <xmin>5.01</xmin>
      <ymin>204.62</ymin>
      <xmax>480.9</xmax>
      <ymax>311.87</ymax>
    </bndbox>

I dont see source file name in it. 
Am I missing something ?

**Comment by bsekachev** [comment]
Sorry, I do not see any xml output in your message.

**Comment by vinodkreddy** [comment]
[frame_000027.txt](https://github.com/openvinotoolkit/cvat/files/6877478/frame_000027.txt)
Attached txt format as xml was not allowed

**Comment by bsekachev** [comment]
@vinodkreddy 

What format do you use to export annotations?

**Comment by vinodkreddy** [comment]
PASCAL VOC 1.1

**Comment by vinodkreddy** [comment]
Do I need to use cvat for video 1.1 format? It has file name

**Comment by bsekachev** [comment]
PASCAL VOC 1.1 was probably designed only for images and it does not support storing metadata (like video name). 
@zhiltsov-max correct me if I am wrong. 

You can use CVAT for video, if using COCO is not obligatory for you.

**Comment by bsekachev** [comment]
BTW dumped pascal VOC has name task_<task name>_datetime-pscal voc 1.1.zip
So, it could contain info about a video name if a task name contains info about the video name.

**Comment by vinodkreddy** [comment]
> BTW dumped pascal VOC has name `task_<task name>-datetime-pascal voc 1.1.zip`
> So, it could contain info about a video name if a task name contains info about the video name.

you are correct that the dumped pascal VOC has task name, however .xml files dont have the details of the task or video name.

**Comment by zhiltsov-max** [comment]
Look projects export introduced in #3365 - they allow exporting multiple tasks as a single dataset from CVAT.

Also, for existing datasets you can use [Datumaro](https://github.com/openvinotoolkit/datumaro#installation) for renaming dataset elements with the [`rename` transform](https://github.com/openvinotoolkit/datumaro/blob/develop/docs/user_manual.md#transform-project) [example](https://github.com/openvinotoolkit/datumaro/issues/16#issuecomment-885453770).

**Comment by bsekachev** [comment]
I hope we answered your question. I will close the issue, if you still have questions, please do not hesitate to reopen it.

**Comment by AbdelsalamHaa** [comment]
@bsekachev 
I'm facing the same issue currently. I exported my data in a Yolo format. but every time I have to rename using datumaro. I was wondering if there is a way to download the data with the right naming right away(name that includes the task name or video name).  my data keep on expanding so I create a new task and I want to combine to the existing one. But I will have to first rename that only I can integrate. sometimes Datumaro will create a new copy of the dataset with the new name so I have to go and delete the old ones

**Comment by zhiltsov-max** [comment]
@AbdelsalamHaa, hi, this could be a nice feature for CVAT, but there is no such option yet. As a workaround please look at our SDK, which can be used to download task frames separately with proper naming:

```python
from cvat_sdk import make_client

with make_client('localhost', credentials=('admin', 'password')) as client:
    client.tasks.retrieve(task_id).download_frames(
            frame_ids=frame_ids,
            outdir=outdir,
            quality=quality,
            filename_pattern=f"task_{task_id}" + "_frame_{frame_id:06d}{frame_ext}",
    )
```

We're open for new feature requests, please open an issue if you want such feature in CVAT.
