### ISSUE TITLE
How can I access splitting videos to frame script?

### ISSUE THREAD

**Issue by memirerdol** [openvinotoolkit/cvat#3459]
I cannot download my dataset because it is over 1GB. Now i want to access script in cvat which included splitting code video to frames. What is the path of this script?

**Comment by bsekachev** [comment]
Hi @memirerdol 

Do you mean that you cannot upload it to CVAT? Or you cannot export (download) dataset from CVAT/

**Comment by memirerdol** [comment]
> Hi @memirerdol
> 
> Do you mean that you cannot upload it to CVAT? Or you cannot export (download) dataset from CVAT/

I can download annotations without images but I can not export my dataset with images from CVAT because it is over 1GB. Now I want to split my videos to frame manually. Can I access the splitting script in CVAT?

**Comment by bsekachev** [comment]
I do not expect any issues with exporting dataset more than 1GB, do you have any errors?

**Comment by azhavoro** [comment]
> > Hi @memirerdol
> > Do you mean that you cannot upload it to CVAT? Or you cannot export (download) dataset from CVAT/
> 
> I can download annotations without images but I can not export my dataset with images from CVAT because it is over 1GB. Now I want to split my videos to frame manually. Can I access the splitting script in CVAT?

Try to set `--limit-request-body 0` here https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L65 and rebuild images with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

**Comment by memirerdol** [comment]
> > > Hi @memirerdol
> > > Do you mean that you cannot upload it to CVAT? Or you cannot export (download) dataset from CVAT/
> > 
> > 
> > I can download annotations without images but I can not export my dataset with images from CVAT because it is over 1GB. Now I want to split my videos to frame manually. Can I access the splitting script in CVAT?
> 
> Try to set `--limit-request-body 0` here https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L65 and rebuild images with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

I tried it before but it didn't work

**Comment by memirerdol** [comment]
I solved the problem by writing script. --limit-request-body 0 is not working for me.

**Comment by joaquin03** [comment]
I have the same problem, @memirerdol you cloud explain what do you mean with "writing script"

Thanks!

**Comment by memirerdol** [comment]
> I have the same problem, @memirerdol you cloud explain what do you mean with "writing script"
> 
> Thanks!

I can not solve limit problem and I can not download the images. I splitted the videos manually and use dump annotations.
