### ISSUE TITLE
Getting rate limited while using CLI

### ISSUE THREAD

**Issue by kraster010** [openvinotoolkit/cvat#3467]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I'm trying to write some scripts that use the CVAT cli to automatically download annotations (using authenticated mode), but I'm getting rate limited. I get this error: 
`requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: http://localhost:8080/api/v1/auth/login`

the bash script is this:
```
IFS=','
./cli.py --auth user:pass ls | while read x; do
  read -a strarr <<<"$x"
  filename=$(echo ${strarr[1]} | cut -f 1 -d '.')
  ./cli.py --auth user:pass dump --format "CVAT for images 1.1" ${strarr[0]} ${filename}.xml
done
```

the line which cause this behaviour is this:
`./cli.py --auth user:pass dump --format "CVAT for images 1.1" taskname taskname.xml`

### Expected Behaviour
we should not get rate limited while using CLI (with --auth)

### Your Environment
- Git hash commit (`git log -1`):
commit 315c9cc8d2b1c8fbd3b6b5e6ab6fca3a792bc895 (HEAD, tag: v1.4.0, origin/master)
Merge: c7033a79 3ca86bcf
Author: Nikita Manovich <nikita.manovich@intel.com>
Date:   Wed May 19 07:26:02 2021 +0300
- Docker version `docker version`: 20.10.6
- Are you using Docker Swarm or Kubernetes?
no
- Operating System and version (e.g. Linux, Windows, MacOS):
linux
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    2021-07-27 10:48:53,442 DEBG 'runserver' stderr output:
    [Tue Jul 27 10:48:53.442499 2021] [wsgi:error] [pid 342:tid 140394214803200] [remote 127.0.0.1:57650] 
    WARNING - 2021-07-27 10:48:53,442 - log - Too Many Requests: /api/v1/auth/login
    </details>

**Comment by kraster010** [comment]
sorry @azhavoro, how can we remove rate limitations for cli? 
can you give some hint on this pls? currently we are blocked by this issue, we have more than 5000 task and we would like to download the annotations for each one of this task.

**Comment by azhavoro** [comment]
> sorry @azhavoro, how can we remove rate limitations for cli?
> can you give some hint on this pls? currently we are blocked by this issue, we have more than 5000 task and we would like to download the annotations for each one of this task.

Hi, you can adjust or remove this setting https://github.com/openvinotoolkit/cvat/blob/develop/cvat/settings/base.py#L169 and rebuild cvat images with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

**Comment by kraster010** [comment]
hi @azhavoro, thanks for the response.
i've tried:
- removing the line you mentioned
- set a bigger value: 10000/minute
i've recompiled with:
`docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml -f docker-compose.override.yml up -d --build`

but still i hit that problem:
`requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: http://localhost:8080/api/v1/auth/login`

on the docker instance where i can find the base.py file you mentioned to see if i did everything correctly?

i've tried grepping:
`grep -ir "DEFAULT_THROTTLE_RATES"`
inside `/opt/venv/lib/python3.8/site-packages`
and it found:
`rest_framework/settings.py:    'DEFAULT_THROTTLE_RATES': {`
`rest_framework/throttling.py:    THROTTLE_RATES = api_settings.DEFAULT_THROTTLE_RATES`

thanks for your time

**Comment by kraster010** [comment]
maybe the problem is that i can't just stop the container with:
`docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml -f docker-compose.override.yml down`
and starting again with:
`docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml -f docker-compose.override.yml up -d --build`

do i need to manually remove the images & volume and start again?
i don't want to lose the data we have currently

**Comment by kraster010** [comment]
for the time being we changed our scripts in order to stay below the 100/minute limits.

**Comment by nmanovic** [comment]
@kraster010 , thanks for the update. I will close the issue for now.
