### ISSUE TITLE
Allow access to CVAT from multiple machines in a secure way

### ISSUE THREAD

**Issue by lamechah** [openvinotoolkit/cvat#3481]
Hi, I'm trying to access cvat from other machines in a secure way.

I understand that in order to do this I should modify ALLOWED_HOSTS parameter in the docker-compose.override.yml ?

This is what my file looks like:

version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: 'Mounted from host directory'
      ALLOWED_HOSTS: localhost <the ip addresses of other hosts go here>
    ports:
      - "80:8080"
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_proxy:
    environment:
      CVAT_HOST: localhost <the ip addresses of other hosts go here>

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/mercedes/
      o: bind

After rebuilding cvat I still can't log in from another machine through the web browser http<my ip>:8080 
The only way this works is if I allow all hosts (*) but not sure if that's a secure way of doing it. 

Thanks for the help!

**Comment by azhavoro** [comment]
Hi, you do not need to change the ALLOWED_HOSTS variable for the `cvat` service because the service is behind a proxy. If you are using the development version of CVAT follow https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port, otherwise just change the CVAT_HOST env variable for `cvat_proxy `

**Comment by lamechah** [comment]
Hi @azhavoro thanks for the help. 

I changed the CVAT_HOST env variable under cvat_proxy to include the public ip address of the other machines that I want to enable access to cvat and it's still not working. After rebuilding cvat I still can't log in from another machine through the web browser http:public-ip-address:8080

This is how my docker-compose.override.yml looks like

version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: 'Mounted from host directory'
    ports:
      - "80:8080"
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_proxy:
    environment:
            CVAT_HOST: public-ip-address

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/mercedes/
      o: bind

**Comment by JoshChristie** [comment]
The `CVAT_HOST` is the cvat machines public IP address, not the other machines IP. 

On AWS I ran `export CVAT_HOST=<YOUR_HOSTNAME>` before `docker-compose up -d`. Then I needed to open access to port 8080 by creating an inbound rule for the EC2 instance. Is your cvat running locally or in the cloud?

**Comment by lamechah** [comment]
Hi @JoshChristie, thank you very much for your help. This solved my issue
