### ISSUE TITLE
Request for Information - Permission groups of CVAT

### ISSUE THREAD

**Issue by sammed-ai** [openvinotoolkit/cvat#3482]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I noticed that there are four groups of users on the cvat platform: admin, annotator, observer and user. 
I wanted to understand what users in each group have permissions to do. The names are pretty clear on what permissions they have but an extensive list of things that the group can do would be very much helpful. If it already exists somewhere, could someone point me towards it. 
### Expected Behaviour

Not Applicable

### Current Behaviour

Not applicable

### Possible Solution

A new page in the documentation listing the permissions for each group

### Steps to Reproduce (for bugs)

Not Applicable

### Context

Not Applicable

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
Not Applicable

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by sammed-ai** [comment]
@nmanovic Could you briefly inform me about this?

**Comment by nmanovic** [comment]
@sammed-ai , we are developing a solution to improve IAM in CVAT. I have no news for you at the moment.

**Comment by davodogster** [comment]
@nmanovic @sammed-ai yes, what do these four groups actually mean? admin, annotator, observer and user. Is it in the documentation? I can't find it

**Comment by vaskokj** [comment]
> 

I've got the same question. Seems extremely cryptic on what which one allows a user to do.
