### ISSUE TITLE
CVAT CLI create task argument "project" should be "project_id"

### ISSUE THREAD

**Issue by muhammadsyahyas** [openvinotoolkit/cvat#3494]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

CVAT CLI create task argument "project" should be "project_id".
https://github.com/openvinotoolkit/cvat/blob/1ea3334b2febb41458add5e9a53d673d7b963f4b/utils/cli/core/definition.py#L116

### Current Behaviour

Argument "project" is parsed by the argument parser as `project`. The `CLI.task_create` keyword argument is expecting `project_id` instead. Since the project ID value is not parsed, the `project_id` data in the POST request https://github.com/openvinotoolkit/cvat/blob/1ea3334b2febb41458add5e9a53d673d7b963f4b/utils/cli/core/core.py#L45 is always `None`, and the server was giving status code 400 response.

### Possible Solution

Replace CVAT CLI create task argument "project" to "project_id" in the `definition.py`.
https://github.com/openvinotoolkit/cvat/blob/1ea3334b2febb41458add5e9a53d673d7b963f4b/utils/cli/core/definition.py#L116
I tested this and the create task succeed.

### Steps to Reproduce (for bugs)

1. Put `some_video.mov` into shared data.
1. Create a new project and define some label. E.g., the created project has project ID 4.
1.  `python3 cli.py --auth admin:password create --project_id 4 my_task share /data/some_video.mov`

### Context

Creating new task from share data source by only specifying project ID. The project is already created before with some label definition.

### Your Environment

- Git hash commit (`git log -1`): 315c9cc8d2b1c8fbd3b6b5e6ab6fca3a792bc895
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.13
- Are you using Docker Swarm or Kubernetes? N
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04.5 LTS

**Comment by bsekachev** [comment]
@ActiveChooN 

Could you please take a look at the issue?

**Comment by ActiveChooN** [comment]
@bsekachev 

> Could you please take a look at the issue?

Sure.
