### ISSUE TITLE
Problems with https

### ISSUE THREAD

**Issue by brunovollmer** [openvinotoolkit/cvat#3495]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Deploy CVAT with respect to [HTTPS Docs](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#deploy-secure-cvat-instance-with-https) and have a valid certificate.

Command:
`docker-compose -f docker-compose.yml -f docker-compose.https.yml up -d`

### Current Behaviour
Firefox does not accept certificat and states connection not secure.

### Your Environment

- Git hash commit (`git log -1`): 1ea3334b2febb41458add5e9a53d673d7b963f4b
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.7
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

**Comment by nmanovic** [comment]
@azhavoro , could you please comment?

**Comment by brunovollmer** [comment]
Hey @nmanovic and @azhavoro after switching to a proper subdomain the problem was solved. Sorry for the inconvenience.
Thanks for the great project!
