### ISSUE TITLE
Suggestion for improving task creation

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#3503]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Related #3420
### Expected Behaviour

- Creating a task or project from multiple videos. The main idea is to quickly create a task from several videos and quickly get an annotation file.
When creating a task, it should be possible to attach several videos simply by dragging them into the drag and drop area.
In this case, each job will contain one video. Different jobs may have different number of frames. The "Segment Size" parameter in this case will be applied only to those videos, that have a large number of frames compared to the segment size.
And the data copied using the "Copy" button on the task page should contain the file name for each job.

- Also, for convenience, you can add "Number of Parts" parameter into which the video will be divided. This parameter is needed to accurately predict the number of jobs. In cases where there is only one video or a group of images in the task, the number of parts will be equal to the number of jobs. Perhaps you need to make this parameter replaceable with the parameter "Segment Size" since these parameters will be mutually exclusive.

### Current Behaviour

- You cannot create a task with multiple video files.

- When creating a task, it is difficult to predict how many jobs in the task if you use the "Frame Step" "Segment Size" parameters and other parameters.

### Possible Solution

N/A
### Steps to Reproduce (for bugs)

N/A

### Context

N/A

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@TOsmanov , we are not going to allow uploading multiple video files for a task. But it is valid for a project. "Number of parts" is a good idea. Could you please create separate issues for each one because they are independent? I will close the issue.
