### ISSUE TITLE
Shortcut key to send object to background

### ISSUE THREAD

**Issue by davodogster** [openvinotoolkit/cvat#3515]
Hi is there a shortcut key to send the object to the background? This would be very useful for overlapping polygons for instance segmentation. Cheers, Sam

**Comment by bsekachev** [comment]
Hi, 

![Screenshot from 2021-08-05 10-57-11](https://user-images.githubusercontent.com/40690378/128313532-f6d42480-7296-45dc-abdb-c658989ce394.png)

**Comment by bsekachev** [comment]
I will close the issue. If you still experiencing issues, do not hesitate to reopen.

**Comment by davodogster** [comment]
@bsekachev Hi Boris. How come when I go here there is no to background or to foreground shortcut listed?
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/shortcuts/
S

**Comment by bsekachev** [comment]
@davodogster 

I am not sure I understand your question. I can see them there:
![image](https://user-images.githubusercontent.com/40690378/129897216-8726fdfc-576c-45ed-b16d-91f2c4dba84d.png)

**Comment by davodogster** [comment]
@bsekachev thanks! I was using Control + Find "background" and "foreground" and couldn't find any information.
