### ISSUE TITLE
Trying to get Semi-automatic and Automatic Annotation

### ISSUE THREAD

**Issue by millmi17** [openvinotoolkit/cvat#3520]
I am new to using the command prompt and am having some issues. I am on a windows 10 machine

I have downloaded nuctl-1.5.16-windows-amd64 and in the command prompt i have ran the below line. It looks like it recognizes the file. but when i try running uctl-1.5.16-windows-amd64 create project cvat I run into an issue as seen below. If any  knows how to help can you give me a step by step walkthrough of what to do? thank you

C:\Users\millermicd\cvat>nuctl-1.5.16-windows-amd64
Nuclio command-line interface

Usage:
  nuctl [command]

Available Commands:
  build       Build a function
  create      Create resources
  delete      Delete resources
  deploy      Build and deploy a function, or deploy from an existing image
  export      Export functions or projects
  get         Display resource information
  help        Help about any command
  import      Import functions or projects
  invoke      Invoke a function
  update      Update resources
  version     Display the version number of the nuctl CLI

Flags:
  -h, --help                help for nuctl
  -k, --kubeconfig string   Path to a Kubernetes configuration file (admin.conf)
  -n, --namespace string    Namespace
      --platform string     Platform identifier - "kube", "local", or "auto" (default "auto")
  -v, --verbose             Verbose output

Use "nuctl [command] --help" for more information about a command.

C:\Users\millermicd\cvat>nuctl-1.5.16-windows-amd64 create project cvat

Error - exec: "/bin/sh": file does not exist
    /nuclio/pkg/cmdrunner/shellrunner.go:96

Call stack:
stdout:

stderr:

    /nuclio/pkg/cmdrunner/shellrunner.go:96
Failed to get docker version
    /nuclio/pkg/dockerclient/shell.go:729
No docker client found
    /nuclio/pkg/dockerclient/shell.go:83
Failed to create docker client
    .../pkg/containerimagebuilderpusher/docker.go:31
Failed to create containerimagebuilderpusher
    /nuclio/pkg/platform/local/platform.go:88

**Comment by nmanovic** [comment]
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/#installation-serverless-functions-on-windows-10-with-using-the-ubuntu-subsystem

Please don't hesitate to ask questions on our gitter channel: https://gitter.im/opencv-cvat/public. I will close the issue.
