### ISSUE TITLE
Chrome debugger for vs-code is deprecated

### ISSUE THREAD

**Issue by ActiveChooN** [openvinotoolkit/cvat#3525]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Description

[Chrome debugger](https://github.com/Microsoft/vscode-chrome-debug) for vs-code is deprecated now, so we should move to the [JavaScript Debugger](https://github.com/microsoft/vscode-js-debug)

### Possible Solution

Change vs-code tasks for compatibility with JavaScript Debugger

**Comment by 0xmessi** [comment]
how ?

**Comment by ActiveChooN** [comment]
According to the [doc](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md), changing the type of launch target in [launch.json](https://github.com/openvinotoolkit/cvat/blob/develop/.vscode/launch.json) will be enough. Other configs should work fine as is.

**Comment by rohittrimalle** [comment]
Can I solve this issue?

**Comment by rajattiwariii** [comment]
Taking help from the below link of changing vs-code tasks for compatibility with Javascript Debugger.

[](https://code.visualstudio.com/docs/editor/debugging)

So changing the launch taget can solve the problem. 

If you go back to the File Explorer view (Ctrl+Shift+E), you'll see that VS Code has created a .vscode folder and added the launch.json file to your workspace.
**Variable substitution**
```
{
  "type": "node",
  "request": "launch",
  "name": "Launch Program",
  "program": "${workspaceFolder}/app.js",
  "cwd": "${workspaceFolder}",
  "args": ["${env:USERNAME}"]
}
```
VS Code makes commonly used paths and other values available as variables and supports variable substitution inside strings in launch.json. This means that you do not have to use absolute paths in debug configurations. For example, ${workspaceFolder} gives the root path of a workspace folder, ${file} the file open in the active editor, and ${env:Name} the environment variable 'Name'. You can see a full list of predefined variables in the Variables Reference or by invoking IntelliSense inside the launch.json string attributes.


**Platform Specific Property**

Launch.json supports defining values (for example, arguments to be passed to the program) that depend on the operating system where the debugger is running. To do so, put a platform-specific literal into the launch.json file and specify the corresponding properties inside that literal.

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/node_modules/gulp/bin/gulpfile.js",
      "args": ["myFolder/path/app.js"],
      "windows": {
        "args": ["myFolder\\path\\app.js"]
      }
    }
  ]
}
```

This may work. For further you can refer to the doc.
