### ISSUE TITLE
Using my own domain for CVAT, beyond localhost

### ISSUE THREAD

**Issue by spatra007** [openvinotoolkit/cvat#3526]
Hi

I see in the documentation that I have to add 

export CVAT_HOST=<YOUR_DOMAIN>

to allow access to CVAT beyond the localhost. However, could you please help me understand where I have to make this change exactly, as i don't see it in the installation manual?

**Comment by azhavoro** [comment]
Hi starting with the latest version, if you want to use any domain other than localhost (default) you need to export  `CVAT_HOST` environment variable, just run the command in your terminal `export CVAT_HOST = <YOUR_DOMAIN>` which sets the env variable for the current session shell. After that, you can run any `docker-compose` commands from the installation guide as usual. https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

**Comment by spatra007** [comment]
Hi @azhavoro , I am still not able to bring it up in the network. I issued the following command before the docker-compose - 

export CVAT_HOST=http://54.172.80.111

And in the cloud IAM network policy, I have allowed the incoming and outgoing from my IP address for port 8080.

Any idea what I could be doing wrong?

**Comment by azhavoro** [comment]
You should use domain name (FQDN) or IP address without any protocol specification like:
```shell
export CVAT_HOST=54.172.80.111
docker-compose up -d
```

after that cvat should be available at http://54.172.80.111:8080 url

**Comment by spatra007** [comment]
Hi @azhavoro 

Thanks for your reply. I followed the steps and it gives me a 404-Page not found error.

![image](https://user-images.githubusercontent.com/66479020/128718192-7b7e8633-9174-4c51-8e84-0e91a233e5d7.png)

**Comment by azhavoro** [comment]
@spatra007 I cannot reproduce this issue. 404 error indicates that you are trying to access the cvat instance using a different domain name than the one configured (default is localhost).
First of all, make sure that you are exporting the CVAT_HOST variable correctly with `env | grep CVAT_HOST` command, note that the export is only actual for the current shell session, so you need to export every time you open a new terminal window. Another way set env variable before the command: `CVAT_HOST=<FQDN> docker-compose ....`
After that, try restarting all containers:
```shell
docker-compose down
docker-compose up -d
```
If that doesn't work, please provide the exact steps to reproduce.

**Comment by KALALRANJITHKUMAR** [comment]
Hello @azhavoro , could you please take a look into this. I am not getting any issues while setting up cvat on AWS, however there are some issue in docker-compose on azure 

![image](https://user-images.githubusercontent.com/16818767/128833906-6ee405cd-0d99-440e-9a72-46ed416fcf07.png)
![Uploading Capture.PNG…]()

**Comment by spatra007** [comment]
> env | grep CVAT_HOST

Hi @azhavoro , thank you for your response. I tried the following command and it worked like a charm - 

sudo CVAT_HOST=54.172.80.111 docker-compose up -d

Not sure what was wrong in the earlier approach where I export the variable before the docker-compose, even grep confirmed that it was set. But anyway thanks a lot :)

**Comment by azhavoro** [comment]
@spatra007 The main reason in your case is the use of `sudo` (unfortunately you did not mention it), which by default does not export environment variables from the current session, but it's possible with use of the` -E` flag. I think it would be better if we add this information to the installation guide.
