### ISSUE TITLE
With Values.cvat.backend.defaultStorage.enabled the backend still creates volumes

### ISSUE THREAD

**Issue by MauroRibeiroHV** [openvinotoolkit/cvat#3552]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

In the deployment of the backend there is a container and an initContainer, and both need the same storage. There is a block of code that defines the volumes in the container, but in the initContainer the same block of code is inside an if that validates the flag defaultStorage.enabled. So, with the flag set to false, we will have the volumeMounts configuration in the container and not in the iniContainer. Since to define the storage we need to configure the additionalVolumeMounts value with our volumes, in the container we would have duplicated entries.

The configuration of volumes of the backend deployment container lacks the if {{- if .Values.cvat.backend.defaultStorage.enabled }} like in the configuration of the volumes of the initContainer.

### Expected Behaviour
When we use custom storage there shouldn't be volumes mounted in the backend.

### Current Behaviour
We use custom storage but there are still volumes hard coded mounted in the backend.

### Possible Solution
The configuration of volumes of the backend deployment container lacks the if {{- if .Values.cvat.backend.defaultStorage.enabled }} like in the configuration of the volumes of the initContainer.

### Steps to Reproduce (for bugs)
1. Set Values.cvat.backend.defaultStorage.enabled to false
2. Check that backend creates the volumes

### Context
I was trying to use a custom storage and was getting error that the volumes i wanted to create already existed. I was using the same names.
 
### Your Environment
Not important to the case

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@MauroRibeiroHV , don't hesitate to contribute a feature which is necessary for you. To be honest I'm not sure I understand from your description what you propose. I will close the issue. Don't hesitate to describe specific actions from our end to help you.
