### ISSUE TITLE
List input for ALLOWED_HOST variable

### ISSUE THREAD

**Issue by kjh0121** [openvinotoolkit/cvat#3560]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- I understand that before running docker-compose up -d, I must run export CVAT_HOST =<domain> (https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port). This must be redone every new terminal instance
- I looked through django documentation as well, and felt that the ALLOWED_HOST variable description verified that you could use a list for this as they describe: "When DEBUG is True and ALLOWED_HOSTS is empty, the host is validated against ['.localhost', '127.0.0.1', '[::1]']." (https://docs.djangoproject.com/en/3.2/ref/settings/)

- [ X] Searched [past issues](/issues)
- this was useful https://github.com/openvinotoolkit/cvat/issues/3526
- https://bleepcoder.com/cvat/371807827/how-can-i-deploy-the-web-server

I would like to deploy my CVAT instance to a URL, but I want only certain network connections to be allowed to reach cvat. Specifically, I'd like it to work only if you are connected on one of two networks.

### Expected Behaviour
After making this change from '*',
  cvat:
    environment:
      ALLOWED_HOSTS: ['network 1/subnet mask', 'network 2/subnet mask', 'my IP (if it's not on network)']

I followed documentation to expose CVAT to web from https://bleepcoder.com/cvat/371807827/how-can-i-deploy-the-web-server

I expect only computers specified can reach my url and login to my CVAT instance.

### Current Behaviour
when trying to run docker-compose with this docker-compose file, an error is thrown--

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.cvat.environment.ALLOWED_HOSTS contains ['network 1/subnet mask', 'network 2/subnet mask', 'my IP (if it's not on network)'], which is an invalid type, it should be a string, number, or a null

### Possible Solution
- not having a bracketed list seems to solve the error, however, I believe the yaml format requires brackets. So I suspect taking the brackets out enters this whole thing as a string that won't actually parse more than one network.
- when I say "solves the error," I just mean I'm able to access my url:8080 and see the CVAT login page but I can't login (I get 400 errors). I don't truly understand all the ports between the containers, so have been changing them all between 8080 and 80 to try and produce expected behavior. I just oscillate between 400 and 502 (bad gateway) errors.

### Steps to Reproduce (for bugs)
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Any help would be greatly appreciated!

**Comment by azhavoro** [comment]
Hi,
the backend server is behind the traefik proxy - is the reason that ALLOWED_HOSTS are set to `*`

> I expect only computers specified can reach my url and login to my CVAT instance.

It's impossible to do this with ALLOWED_HOSTS Django settings, this is not working as you expected. This is just a list of strings representing the host/domain names by which this Django site can be reachable. For example if ALLOWED_HOSTS=['localhost'] the backend will respond by `http://localhost` url, but will not response by 127.0.0.1 from the same computer.
I think you should set up network rules for inbound connections using iptables or nftables for your server.

**Comment by kjh0121** [comment]
Oh, ok, thank you for your help!
