### ISSUE TITLE
BUG: modifying attributes is applied even on the previous frames; in object tracking in videos, no keyframe for attributes

### ISSUE THREAD

**Issue by arasharchor** [openvinotoolkit/cvat#3564]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behavior
To be able to have an object with different attributes in specific frames during a video. We would like to have the attributes until they are not changed and if they are, their new status remains for the next frames and do affect the previous frames. 

### Current Behavior
By adding or removing an attribute to or from an object, it is applied globally to all frames. 
There is only keyframe for occlusion property and not attributes. Extending the effect of keyframe for attributes would solve this problem.

### Steps to Reproduce (for bugs)
For instance, let's say, an object is truncated in the first and second frame and then it is not truncated anymore, If we activate the truncated flag for the first frame and let it be there for the second frame and then make that attribute flag since the third frame, the truncated flag for the first and second frames are also removed. Please note that we have 5 custom attributes and there is a distinction from occluded and truncated. For the occlusion, we use the default attribute in the tool.

**Comment by bsekachev** [comment]
Hi @arasharchor 

Did you mark the attribute "truncated" as "Mutable" when creating it?

**Comment by arasharchor** [comment]
Hi, thanks a lot. 
I missed that part. 
Then it was a false alarm then!
