### ISSUE TITLE
Failed to Deploy function

### ISSUE THREAD

**Issue by pkcktkksh98** [openvinotoolkit/cvat#3574]
hi, i encounter this problem right here after i run `./serverless/deploy_cpu.sh ./serverless/openvino/omz/public/FaceDet2
`.  I have also include the config file in the attachment. 
Openvino: 2021.3.394
python: 3.8.10
[FaceDet2.zip](https://github.com/openvinotoolkit/cvat/files/7019093/FaceDet2.zip)

<pre>21.08.20 04:00:58.577 <font color="#D3D7CF">cessor.healthcheck.server</font> <font color="#3465A4">(I)</font> Listening {&quot;listenAddress&quot;: &quot;:8082&quot;}
21.08.20 04:00:58.577 <font color="#D3D7CF">           processor.http</font> <font color="#4E9A06">(D)</font> Creating worker pool {&quot;num&quot;: 2}
21.08.20 04:00:58.577 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#4E9A06">(D)</font> Creating listener socket {&quot;path&quot;: &quot;/tmp/nuclio-rpc-c4fihuj1bcdjtb88ci3g.sock&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#4E9A06">(D)</font> Using Python wrapper script path {&quot;path&quot;: &quot;/opt/nuclio/_nuclio_wrapper.py&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#4E9A06">(D)</font> Using Python handler {&quot;handler&quot;: &quot;main:handler&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#4E9A06">(D)</font> Using Python executable {&quot;path&quot;: &quot;/opt/nuclio/common/openvino/python3&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#4E9A06">(D)</font> Setting PYTHONPATH {&quot;value&quot;: &quot;PYTHONPATH=/opt/nuclio&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#4E9A06">(D)</font> Running wrapper {&quot;command&quot;: &quot;/opt/nuclio/common/openvino/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-c4fihuj1bcdjtb88ci3g.sock --platform-kind local --namespace nuclio --worker-id 1 --trigger-kind http --trigger-name myHttpTrigger&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w0.python.logger</font> <font color="#4E9A06">(D)</font> Creating listener socket {&quot;path&quot;: &quot;/tmp/nuclio-rpc-c4fihuj1bcdjtb88ci40.sock&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w0.python.logger</font> <font color="#4E9A06">(D)</font> Using Python wrapper script path {&quot;path&quot;: &quot;/opt/nuclio/_nuclio_wrapper.py&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w0.python.logger</font> <font color="#4E9A06">(D)</font> Using Python handler {&quot;handler&quot;: &quot;main:handler&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w0.python.logger</font> <font color="#4E9A06">(D)</font> Using Python executable {&quot;path&quot;: &quot;/opt/nuclio/common/openvino/python3&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w0.python.logger</font> <font color="#4E9A06">(D)</font> Setting PYTHONPATH {&quot;value&quot;: &quot;PYTHONPATH=/opt/nuclio&quot;}
21.08.20 04:00:58.578 <font color="#D3D7CF">sor.http.w0.python.logger</font> <font color="#4E9A06">(D)</font> Running wrapper {&quot;command&quot;: &quot;/opt/nuclio/common/openvino/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-c4fihuj1bcdjtb88ci40.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger&quot;}
[setupvars.sh] OpenVINO environment initialized
[setupvars.sh] OpenVINO environment initialized
21.08.20 04:00:58.939 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#3465A4">(I)</font> Wrapper connected {&quot;wid&quot;: 1, &quot;pid&quot;: 18}
21.08.20 04:00:58.939 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#4E9A06">(D)</font> Waiting for start
l{&quot;datetime&quot;: &quot;2021-08-20 04:00:58,939&quot;, &quot;level&quot;: &quot;info&quot;, &quot;message&quot;: &quot;Init context...  0%&quot;, &quot;with&quot;: {&quot;worker_id&quot;: &quot;1&quot;}}
l{&quot;datetime&quot;: &quot;2021-08-20 04:00:58,958&quot;, &quot;level&quot;: &quot;error&quot;, &quot;message&quot;: &quot;Exception raised while running init_context&quot;, &quot;with&quot;: {&quot;worker_id&quot;: &quot;1&quot;}}
l{&quot;datetime&quot;: &quot;2021-08-20 04:00:58,959&quot;, &quot;level&quot;: &quot;error&quot;, &quot;message&quot;: &quot;Caught unhandled exception while initializing&quot;, &quot;with&quot;: {&quot;err&quot;: &quot;Cannot create ShapeOf layer Shape_196 id:209&quot;, &quot;traceback&quot;: &quot;Traceback (most recent call last):\n  File \&quot;/opt/nuclio/_nuclio_wrapper.py\&quot;, line 350, in run_wrapper\n    args.trigger_name)\n  File \&quot;/opt/nuclio/_nuclio_wrapper.py\&quot;, line 80, in __init__\n    getattr(entrypoint_module, &apos;init_context&apos;)(self._context)\n  File \&quot;/opt/nuclio/main.py\&quot;, line 17, in init_context\n    model = ModelHandler(labels)\n  File \&quot;/opt/nuclio/model_handler.py\&quot;, line 14, in __init__\n    self.model = ModelLoader(model_xml, model_bin)\n  File \&quot;/opt/nuclio/common/openvino/model_loader.py\&quot;, line 13, in __init__\n    network = ie_core.read_network(model, weights)\n  File \&quot;ie_api.pyx\&quot;, line 136, in openvino.inference_engine.ie_api.IECore.read_network\n  File \&quot;ie_api.pyx\&quot;, line 157, in openvino.inference_engine.ie_api.IECore.read_network\nRuntimeError: Cannot create ShapeOf layer Shape_196 id:209\n&quot;, &quot;worker_id&quot;: &quot;1&quot;}}
21.08.20 04:00:58.959 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#C4A000">(W)</font> Failed to read from connection {&quot;err&quot;: &quot;EOF&quot;}
21.08.20 04:00:58.964 <font color="#D3D7CF">sor.http.w0.python.logger</font> <font color="#3465A4">(I)</font> Wrapper connected {&quot;wid&quot;: 0, &quot;pid&quot;: 19}
21.08.20 04:00:58.964 <font color="#D3D7CF">sor.http.w0.python.logger</font> <font color="#4E9A06">(D)</font> Waiting for start
l{&quot;datetime&quot;: &quot;2021-08-20 04:00:58,964&quot;, &quot;level&quot;: &quot;info&quot;, &quot;message&quot;: &quot;Init context...  0%&quot;, &quot;with&quot;: {&quot;worker_id&quot;: &quot;0&quot;}}
21.08.20 04:00:58.976 <font color="#D3D7CF">sor.http.w1.python.logger</font> <font color="#CC0000">(E)</font> Unexpected termination of child process {&quot;error&quot;: null, &quot;status&quot;: &quot;exit status 1&quot;}
panic: Wrapper process for worker 1 exited unexpectedly with: exit status 1

goroutine 24 [running]:
github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).watchWrapperProcess(0xc0002d4780)
	/nuclio/pkg/processor/runtime/rpc/abstract.go:464 +0x576
created by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper
	/nuclio/pkg/processor/runtime/rpc/abstract.go:236 +0x1b5

    /nuclio/pkg/platform/local/platform.go:1001
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:182
  NAMESPACE |                      NAME                      | PROJECT |  STATE   | NODE PORT | REPLICAS  
  nuclio    | openvino-omz-public-face-detection-0204        | cvat    | building |         0 | 1/1       
  nuclio    | openvino-omz-public-face-detection-adas-0001   | cvat    | ready    |     49195 | 1/1       
  nuclio    | pth.facebookresearch.detectron2.retinanet_r101 | cvat    | ready    |     49272 | 1/1   </pre>

**Comment by bsekachev** [comment]
It seems you have issues in source code. Try to write and run it without nuclio first.
I will close the issue because it is not really related with CVAT.
