### ISSUE TITLE
local server access problem

### ISSUE THREAD

**Issue by SungbinSon** [openvinotoolkit/cvat#3579]
i am installed my server (*.*.*.*:22)
localhost:8080 is done

but, i want to connect cvat on my computer
so i want to access using url like *.*.*.*:8080 on my own computer

how can i do it?

my cvat version is latest version 3.3 

i am trying to solve this problem for 3 days!!
but still not solved

how can i solve this problem

**Comment by azhavoro** [comment]
Please follow this guide https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

**Comment by SungbinSon** [comment]
> Please follow this guide https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

Thanks a lot !!. i am already solved.
