### ISSUE TITLE
Downloading Dataset from tasks

### ISSUE THREAD

**Issue by Jakubelo** [openvinotoolkit/cvat#3590]
Hi, maybe this is in most question, not an issue. I have uploaded X videos as tasks on the CVAT server. The significant part is annotated (sem seg). I just looked up any information on how to download these tasks as dataset. I know there is a CLI but, there is nothing in documentation how to do this in that case (multiple videos). Do I need datumaro or CLI is enough for that or maybe I have to do this through GET request  in /api/swagger/ ??? I need a fast response, very please .

**Comment by Jakubelo** [comment]
If it is possible, I want to download multiple tasks as one dataset.

**Comment by zhiltsov-max** [comment]
Hi. It should be available with Project export added in https://github.com/openvinotoolkit/cvat/pull/3365. Try to use the `develop` version.

**Comment by Jakubelo** [comment]
@zhiltsov-max  So the next issue is, I have uploaded already the data and somehow the CLI didn't want to assign the tasks to the project. The tasks aren't under any project.

**Comment by zhiltsov-max** [comment]
I'm not sure understood the problem correctly, but you need to create a new project and move tasks inside. Then, export the project in some format. Currently, it can be done with UI only.

**Comment by Jakubelo** [comment]
@zhiltsov-max Okay, how can I move all tasks to project. How to exactly change the version "current" to "develop" - restaring through docker-compose??? but then what about the data in volume, won't be lost?

**Comment by Jakubelo** [comment]
@ActiveChooN Can you provide some info, how to do this?

> @bsekachev Okay, I see. I don't have attributes on any label, so I won't lose anything. But how can I move the tasks to a specific project? I have 360 tasks.

**Comment by ActiveChooN** [comment]
@Jakubelo, hi. We have no such function in cvat-cli, so I guess now it can be done with UI only. PR with such a feature will be highly anticipated.

**Comment by nmanovic** [comment]
@Jakubelo , we will close the issue. As suggested you can use export datasets feature in a project.
