### ISSUE TITLE
Export project as dataset

### ISSUE THREAD

**Issue by Pepslee** [openvinotoolkit/cvat#3595]
### My actions before raising this issue
- [+] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [+] Searched [past issues](/issues)

I'm trying to export project as dataset after [#3365 ](https://github.com/openvinotoolkit/cvat/pull/3365) but if I'm using subset (train, validation, test) export doesn`t work. It just saves two files in archive: obj.data and obj.names.

If I delete subset info - download works fine. But I want to use subsets to easy and comfort exporting of big number of tasks and automaticly split to train/validation.

**Comment by bsekachev** [comment]
@ActiveChooN Please, take a look

**Comment by davodogster** [comment]
@ActiveChooN @bsekachev Hi, I still don't see the option for export project as dataset - the only option is "delete"

I have recently updated cvat:  docker compose down (2 days ago), git clone cvat, docker compose CVAT_Host=xxxxxxxx (does this give me the latest cat version or the development version? 
Do I have to specify train and valid subsets to use this "export project as dataset" feature? Thank you!
