### ISSUE TITLE
Search duplicated images in CVAT

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#3602]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

**Comment by zhiltsov-max** [comment]
Maybe use https://github.com/openvinotoolkit/datumaro/blob/develop/tests/test_ndr.py
Maybe use https://github.com/openvinotoolkit/datumaro/blob/f69ccde583ff79a955d18beac80ccb67dbf091d9/datumaro/components/operations.py#L1299-L1347
