### ISSUE TITLE
About data storage 

### ISSUE THREAD

**Issue by SaihholdChiu** [openvinotoolkit/cvat#3606]
I have 2 questions about data storage:
1. Is there any way to read data from remote site and don't store data on my device?
2. I realized that data will be stored tripe times: 1)original quality, 2)compressed quality, 3)chunk, only chunk is enough for me, because i always store raw data on my computer, so I don't need to store original and compressed data, is there any way to disable them? or where to fix the code?
thx

**Comment by Marishka17** [comment]
Hope I answered on questions. I'm going to close the issue. Feel free to reopen.

**Comment by MattWittbrodt** [comment]
@Marishka17 Is it possible to only store symlinks (or similar) of the data? I have a shared storage set up and working, but it still seems to be copying over the images for a second time to the device (use cache is always checked). Is it possible to configure CVAT to just use the file paths? Or....am I just mis-interpreting what `use cache` is using?

**Comment by Marishka17** [comment]
If you use shared storage you can uncheck `Copy data into CVAT` checkbox in UI. This will avoid copying `raw` data (links will be used), does not apply to archives.
`Use cache` allows avoiding preparing all chunks (`original`/`compressed`) at the moment of an annotation task creating.
Related #3542

**Comment by MattWittbrodt** [comment]
Thank you for the clarification, @Marishka17. Having done a little more investigate with the share folder and your suggestions, I do not see as big of an increase in size as previously thought. Thank you very much for your help.
