### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by vishwas123r** [openvinotoolkit/cvat#3615]
![Uploading image.png…]()

any help from you folks

**Comment by sarangtamrakar** [comment]
Create Super user

**Comment by bsekachev** [comment]
If you registered this user via interface, it does not have enough permissions without adding them explicitly. As @sarangtamrakar suggested, create a superuser first after you deployed CVAT: 

```docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'```

**Comment by azhavoro** [comment]
@vishwas123r Have you solved the problem?

**Comment by azhavoro** [comment]
Hope, the issue is resolved
