### ISSUE TITLE
Weak Registration Implementation

### ISSUE THREAD

**Issue by jayant766** [openvinotoolkit/cvat#3618]
Steps:

Register on the website 
An account verification link will be sent by email 
Go to email inbox 
Right-click on the box and copy the link    
Check the link by pasting it in new tab
Hit enter and check if the account is being opened

HTTP LINK: 

Impact - The user's account can be directly logged if the token is grabbed by the attacker by the tool named Wireshark.

**I want to fix this bug. Please let me know what I can do for fixing it.**

![Screenshot (209)](https://user-images.githubusercontent.com/73739820/131230375-b7929c56-2acc-47e6-bc1c-9c63193ba78a.png)

**Comment by g-kartik** [comment]
It is because, it is not using https protocol. If used everything will be encrypted.

**Comment by nmanovic** [comment]
@jayant766 , cvat.org uses https. Thus it should not be an issue. I will close the request. Don't hesitate to reopen it if you believe I'm wrong.
