### ISSUE TITLE
Bug in automatic annotation in job page.

### ISSUE THREAD

**Issue by AmitN1212** [openvinotoolkit/cvat#3620]
I deployed my own serverless function. I am able to run auto annotation from the task page successfully. However, when I try to run it from the job page (for each picture), it gives me the following error:
`Error: "point coordinate" is expected to be "number", but "string" has been got.`
It happens because I send the coordinates as string, because unless I do it, the json gives me an error. My question is:
If I don't get an error when I run it from the tasks page, why do I get it when I run it from the job page?

**Comment by bsekachev** [comment]
> If I don't get an error when I run it from the tasks page, why do I get it when I run it from the job page?

Probably because the database also stores points as a string, but client works with array of numbers. It is not a bug, please follow the specified interface. Look at code in  ``cvat/apps/lambda_manager/views.py``  to learn more
