### ISSUE TITLE
Does the cvat automatic annotation support polyline mode ?

### ISSUE THREAD

**Issue by pingchesu** [openvinotoolkit/cvat#3624]
Really appreciate for the great work of this project!!

Our team has already used CVAT to finish lots of object detection and segmentation annotation jobs!!

We also use the automatic annotation to accelerate our annotation speed.

However, there is no tutorial about how to pre-label polyline with automatic annotation mode.

Does the automatic annotation of CVAT support polyline type?

It will be really helpful if CVAT can support this automatic annotation type!!

**Comment by bsekachev** [comment]
Hi, currently CVAT does not support automatic polylines annotation.
It would be great if the community helped us with the implementation.

**Comment by pingchesu** [comment]
@bsekachev 

Really thanks for the reply!!

I found that CVAT has another great freature: `Upload annotations`

The workaround way for our team is :

(1) using the pretrained polyline model to create the label 

(2) save the label as cvat annotation format

(3) upload the cvat annotation to cvat server

**Comment by nmanovic** [comment]
@pingchesu , great to see that you have the workaround. I will close the issue. If you can provide more information about your use case (e.g. a DL model which is used to consume polylines, it will help).
