### ISSUE TITLE
UI updates not reflecting when running docker-compose up -d or other related commands

### ISSUE THREAD

**Issue by sammed-ai** [openvinotoolkit/cvat#3630]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I need a few changes to be made in the header component of the UI. When I make the change and I run docker-compose up -d the UI changes do not reflect on the chrome browser website. I tried other commands such as
1. docker-compose up --build
2. docker-compose build
3. docker-compose build --no-cache
4. docker-compose up -d --build --force-recreate
5. docker-compose up -d --build

Seeing that the changes are not reflected I restored to the original version and change very minuscule things like Placeholder value in the login form and ran the above commands again but still, the changes were not reflected. 

Could someone guide me on what to do so that the UI changes are reflected on the website?

### Expected Behaviour

By changing the components and rebuilding the images the website UI should change. 

### Current Behaviour

The UI is not reflecting the changes

### Possible Solution

A very specific command for docker to rebuild the images with the new changes in the UI.
### Steps to Reproduce (for bugs)

1. Change the UI components in the "cvat-ui" folder header component and rebuild the docker images. There is no error in the building process but the changes are not visible. 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Try:
``docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build``

``docker-compose.dev.yml`` is necessary when trying to build from the current code. In other way the latest image will be downloaded from dockerhub.

**Comment by bsekachev** [comment]
From the [documentation](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/): 

![image](https://user-images.githubusercontent.com/40690378/131476548-826a1905-de18-4fae-9f15-bcc332cb76f9.png)

**Comment by sammed-ai** [comment]
<img width="1784" alt="Screenshot 2021-08-31 at 4 37 22 PM" src="https://user-images.githubusercontent.com/72775806/131492124-a622199d-c42a-4147-a266-a3dc6fcc0ef3.png">

I get this error when I run the above said command. What is the issue?

**Comment by bsekachev** [comment]
Have you done any changes in ``cvat-ui/package-lock.json``? Try to send output for ``git diff cvat-ui/package-lock.json``

**Comment by sammed-ai** [comment]
No. I have only chagned the header.tsx file in the header component of then cvat-ui.

**Comment by bsekachev** [comment]
@sammed-ai 

Maybe you have done ``npm install`` instead of ``npm ci``?
Need to be sure that ``package-lock.json`` has not been changed.

**Comment by sammed-ai** [comment]
<img width="1777" alt="Screenshot 2021-08-31 at 4 51 46 PM" src="https://user-images.githubusercontent.com/72775806/131494080-5e23a76f-a624-444f-a8a8-cadb1c64ba6c.png">

I ran the command `npm cache clean -force` and then again ran your command and got the above new error. I am using a Mac. 

And I did `git diff package-lock.json` and it did not return anything.

**Comment by bsekachev** [comment]
It says you are run out of memory (RAM).
Stackoverflow suggests some solutions, please google ``npm build 134 code``.

**Comment by sammed-ai** [comment]
I have 16 GB RAM system. How is it possible to run of memory? Does CVAT takes that much space to run development build?

**Comment by sammed-ai** [comment]
For those who might be facing this issue. To build the CVAT local changes a lot of RAM memory is needed. I don't exactly know why. But I was able to build the local changes on an EC2 instance with 16 GB RAM (It does not even work with 8 GB of RAM). The above command to build works fine. 

I will be closing this issue. I hope something is done to reduce the memory taken to build the local changes.
