### ISSUE TITLE
How do I upload a pre-made label???

### ISSUE THREAD

**Issue by starspder** [openvinotoolkit/cvat#3636]
I am trying to upload an already created label in yolo format.

error is

Could not upload annotations for the job 10

Error: Request failed with status code 500.
FileNotFoundError: [Errno 2] No scuh file or directory:
'/tmp/tmpgi5vtyiz/obj_train_data/....

So I did an experiment. After dumping the tagged label, uncompressed the zip file and re-compressed it to try uploading. But the same error occurred. In short, If I recompress the dumped zip file that has already been unpacked, an error will appear when uploading. I don't know what this means.

What I want is to move the existing data tagging txt file (yolo format). And further tagging is in progress. What should I do??

**Comment by zhiltsov-max** [comment]
Probably, the archive has an extra directory in the root. Check if it is the case. The archive must have just the dataset in the root.
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/format-yolo/

**Comment by azhavoro** [comment]
@starspder Hi, have you solved your issue?

**Comment by bsekachev** [comment]
@starspder 
There is not response from your side, so, I will close the issue. Do not hesitate to reopen if you still have questions.
