### ISSUE TITLE
Mount directory and delete data inside a volume

### ISSUE THREAD

**Issue by DP1701** [openvinotoolkit/cvat#3638]
Hello all,

I am currently struggling with two issues. When I delete a task in CVAT, then unfortunately the data still remains in the cvat_cvat_data volume. How can I remove this data? Does it maybe remove Docker itself when the disk image size is reached?

The second problem is that I actually want to store the data outside of a container. According to the documentation, it is enough if I run the following command in the terminal: $ docker run --name cvat-server -v /my/cvat_data_dir:/home/django/data -d openvino/cvat_server

I swapped /my/cvat_data_dir for a custom path. Unfortunately this does not work, because the destination folder always remains empty. No files are stored there. Do I have to execute something before?

My system: MacOS 10.15.7
Docker version: 20.10.8, build 3967b7d

**Comment by azhavoro** [comment]
@DP1701 Hi,

1. How did you delete tasks?
2. I suggest to use [docker-compose](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#quick-installation-guide) (it's much easier) to run CVAT, so you need to configure docker volume [here](https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.yml#L94) like this:
   ```yml
   volumes:
      cvat_data:
        driver_opts:
          type: none
          device: /your_path
          o: bind
   ```

**Comment by DP1701** [comment]
@azhavoro Hi,

2. 
The bind mount now works. The data is finally stored in the directory. Thanks for the tip! 

1.
I always delete the data via the web interface (Task > Action > Delete). But the data is now also deleted after I set up the bind mount. But I also loaded the current version from the repository once. My two problems have been solved. 

Thanks for your help!
