### ISSUE TITLE
How to host CVAT on local network

### ISSUE THREAD

**Issue by mmaaz60** [openvinotoolkit/cvat#3639]
I will appreciate if anyone can share a detailed instruction to deploy CVAT on a local network. Thanks

**Comment by alalek** [comment]
Check "Installation guide" on the main page: https://github.com/openvinotoolkit/cvat

**Comment by mmaaz60** [comment]
Hi @alalek,

I did that but was still not able to figure out the steps. Are you referring to the `Deploying CVAT behind a proxy` section in the installation guide? If that so, I tried it and it doesn't work

**Comment by alalek** [comment]
The current link points to this location: https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/

**Comment by mmaaz60** [comment]
> The current link points to this location: https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/
> 
> Start from the beginning. Don't jump to the end.
> Provide your steps and test logs in case of troubles.

Thank You @alalek  for your response,

In my case what I want is to install CVAT on one machine and access it from another machine/machines on the same network. So, for example, if I install CVAT on a machine with IP address `10.127.10.109`. Then what I want is to use it from any other machine on the same network. It may be done by just typing, `10.127.10.109:8080` in the browser of let's say machine with IP `10.127.20.201`.

I have followed the instructions at https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation and was able to successfully run CVAT locally. But when I try to access it from another machine, it says 
```
This site can’t be reached
10.127.30.103 refused to connect.
```
Following the instructions under `Deploying CVAT behind a proxy 
` I updated my ~/.docker/config.json file and it looks like the following.
```
{
  "proxies": {
    "default": {
      "httpProxy": "10.127.30.103:8080",
      "httpsProxy": "10.127.30.103:8080",
      "noProxy": "*"
    }
  }
}
```
Also, following some comments found on web, I updated `cvat-ui/react_nginx.conf` file as,
```
server {
    root /usr/share/nginx/html;
    # Any route that doesn't have a file extension (e.g. /devices)
    location / {
        try_files $uri $uri/ /index.html;
        add_header Access-Control-Allow-Origin "*";
    }
}
```
I don't have any experience with web programming so I may be overlooking some things. I wanted you to point me out where I am doing a mistake or otherwise, the instructions to deploy CVAT on a machine and access it using other machines on the same network. Furthermore, I am attaching screeshot of `docker-compose logs -f` in case it may be helpful. Thanks
![cvat](https://user-images.githubusercontent.com/55104795/132119479-7fc60d88-b44c-4070-8567-b6bdbaf3f1bd.png)

**Comment by alalek** [comment]
> was able to successfully run CVAT locally
> I want is to use it from any other machine on the same network
> 10.127.30.103 refused to connect.

IMHO, this is off-topic. You HAVE to learn, how to configure your firewall and open ports properly on your own, we can't help you here.
It is better to ask your system administrator to configure that. We don't know your network configuration details or policies of your corporate network. So any suggestions would be inaccurate.

BTW, There are some guidelines in Internet:
- https://askubuntu.com/questions/911765/open-port-on-ubuntu-16-04
- https://www.bojankomazec.com/2019/12/how-to-open-ports-on-ubuntu.html 
- https://www.ibm.com/docs/en/spectrum-scale/4.2.2?topic=firewall-examples-how-open-ports

**Caution**: don't try to play with network through remote connection. You may broke network settings and lost your remote connection without any chance to recover.

---

> Deploying CVAT behind a proxy

You don't need that at all if you already run CVAT locally (you have direct/transparent access to Internet).
