### ISSUE TITLE
How to annotate attribute of multiple continuous frames in track mode?

### ISSUE THREAD

**Issue by xqfone070** [openvinotoolkit/cvat#3643]
I have a task to annotate the behavior of person in video. I annotate the behavior of person as a attribute. I must annotate the attribute every frame, It takes me lots of time. Is there a way to annotate attribute of multiple continuous frames at once in track mode, for example: 
frame 1-100, behavior of  person 1 is sitting
frame 100-200, behavior of person 1 is standing

**Comment by azhavoro** [comment]
Hi, you need to create a label with **mutable** attribute (I think select type will be ok for your case) and use tracks, i.e. :
go to 1 frame and set attribute to sitting
go to 100 frame and set the attribute to standing

https://openvinotoolkit.github.io/cvat/docs/manual/basics/vocabulary/

**Comment by xqfone070** [comment]
Thanks for your reply! But it not works, forward your steps, 1 frame is set to sitting, 100 frame is set to standing, but the frames between 1-100 are not changed , their attrbute is the default value.

**Comment by azhavoro** [comment]
@xqfone070 Please provide exact steps to reproduce your issue
