### ISSUE TITLE
3D annotation image preview

### ISSUE THREAD

**Issue by korshunovdv** [openvinotoolkit/cvat#3644]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Current Behaviour

When I read the [docs](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/3d-object-annotation-advanced/) lidar point cloud loaded with image in right top corner.
But when I upload raw kitti lidar data (.bin files), it's shown without preview image.

Could you tell me which format should I use to see image preview with raw lidar data?

**Comment by bsekachev** [comment]
Hi, @korshunovdv 

They are called context images.
Uploaded file must be .zip with one of following structures:
```
kitty
# velodyne_points/
#     data/
#         image_01.bin
# IMAGE_00
#     data/
#         image_01.png

pointcloud
# pointcloud/
#     00001.pcd
# related_images/
#     00001_pcd/
#         image_01.png # or other image

# Default formats
# Option 1
# data/
#     image.pcd
#     image.png

# Option 2
# data/
#    image_1/
#        image_1.pcd
#        context_1.png
#        context_2.jpg
```

UI now supports only one context image per annotation image, but server supports multiple.

**Comment by bsekachev** [comment]
Documentation here: https://openvinotoolkit.github.io/cvat/docs/manual/basics/creating_an_annotation_task/#data-formats-for-a-3d-task

**Comment by bsekachev** [comment]
I will close the issue, do not hesitate to reopen if you still have questions.

**Comment by northeastsquare** [comment]
Image preview mean display lidar cuboid in image, like the following image, can cvat preview it?
<img width="661" alt="image" src="https://github.com/opencv/cvat/assets/3086078/b636419e-0422-4496-9fec-f55aff96132a">

**Comment by bsekachev** [comment]
CVAT does not support cuboids projection from 3D scene to 2D related images.
