### ISSUE TITLE
Ui changes are not applied in CVAT

### ISSUE THREAD

**Issue by FarnazashtariUT** [openvinotoolkit/cvat#3646]
hi, I installed the CVAT on my PC using the local installation method. But after the change in the cvat-ui, the changes are not displayed. I pressed (Shift + f5) but my changes did not take effect.
For example, I changed the color of the toolbar, but it did not change. how can I fix it?

**Comment by nmanovic** [comment]
@FarnazashtariUT , it is very difficult to investigate issues with "local installation method" remotely. Thus we are not able to support you. Please ask in our dev channel on gitter (https://gitter.im/opencv-cvat/dev). I hope somebody will answer and help. Be sure that you are using localhost:3000. Look into console and check that cvat-ui is actually rebuilding.

I will close the issue.
