### ISSUE TITLE
Click on the bouding box without releasing the mouse, press delete key, the annotation page will be stuck

### ISSUE THREAD

**Issue by kgloveyou** [openvinotoolkit/cvat#3652]
### My actions before raising this issue
- [√ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ √] Searched [past issues](/issues)

### Expected Behaviour

the annotation page can interact correctly
### Current Behaviour

you can zoom, but you cannot select the bouding box and change to next picture
### Steps to Reproduce (for bugs)

1.Click on the bouding box without releasing the mouse
2.press delete key
3.the annotation page will be stuck(you can zoom, but you cannot select the bouding box and change to next picture)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi @kgloveyou

Thank you for the report.
