### ISSUE TITLE
Order of instances in xml 

### ISSUE THREAD

**Issue by mmhello** [openvinotoolkit/cvat#3653]
hello,
i exported the task dataset after annotating and i want to save the data about the order i labeled the instances (what i labeled first, second etc.)
i saw in the xml that the order is not saved.
can i keep this information somehow?
thanks

**Comment by nmanovic** [comment]
@mmhello , unfortunately it is impossible at the moment. Could you please describe your use case? Why do you need the feature?

**Comment by mmhello** [comment]
thanks for the fast response!
i have 2 classes and there are connections between the instances of different classes (instance 1 from class 1 belong to instance 1 from class 2, etc.)
and i want to be able to have the information about the connections.
i thought to label them one after another but the export to xml shuffles the order.

**Comment by zhiltsov-max** [comment]
How about joining them into groups then? They will have the same group id in the exported file.

**Comment by nmanovic** [comment]
@mmhello , please use groups as Max suggested. I will close the issue.
