### ISSUE TITLE
Kitti data format

### ISSUE THREAD

**Issue by BarcaBear** [openvinotoolkit/cvat#3659]
Is it possible to import and export the kitti data format?

**Comment by kirill-sizov** [comment]
Hi, @BarcaBear currently CVAT does not support Kitti format, but we plan to add it in the future.

**Comment by kirill-sizov** [comment]
Hi, @BarcaBear, we added Kitti segmentation and detection format into the develop branch, is it cover your issue?

**Comment by nmanovic** [comment]
@BarcaBear , I will close the issue. Could you please try and provide a feedback?

![image](https://user-images.githubusercontent.com/40690625/142726120-05ea56f7-0064-4ed0-8205-3679b28ecf2e.png)

**Comment by BarcaBear** [comment]
Sorry for he delay. I have installed the development branch and cant see any option for kitti format from https://github.com/openvinotoolkit/cvat.git

Am i doing something wrong?


![1](https://user-images.githubusercontent.com/38292127/144252710-e8e27d9e-02c1-409f-87da-4e409b56a215.png)

**Comment by BarcaBear** [comment]
We have tested and confirmed everything is working as expected. Also importing and exporting into other systems that support the kitti format works.

Thanks!
