### ISSUE TITLE
to get just point locations

### ISSUE THREAD

**Issue by Muhibullah1** [openvinotoolkit/cvat#3663]
I need to know how to get just the locations (values of x, y) of the points. Any help would be greatly appreciated

**Comment by azhavoro** [comment]
Hi, unfortunately, I don't quite understand your question, so could you please add more details?

**Comment by Muhibullah1** [comment]
Thanks for the quick response. I was working on dot annotations and could not extract the positions of the points for each image just. for instance, we get bounding box positions for an individual images in XML files but we don't get the same for dot annotations

**Comment by zhiltsov-max** [comment]
Hi, probably, if you want to convert boxes to their points, CVAT can't help. You can try to export in some format (CVAT for images, Datumaro, VOC, COCO etc.) and process the file, e.g. with [Datumaro](https://github.com/openvinotoolkit/datumaro):

```bash
pip install datumaro
```

```python
from datumaro.components.dataset import Dataset
from datumaro.components.extractor import Transform, AnnotationType, Points

class BoxesToPoints(Transform):
    def transform_item(item):
        new_anns = []
        for ann in item.annotations:
            if ann.type is AnnotationType.bbox:
                ann = Points(ann.as_polygon(), attributes=ann.attributes, id=ann.id, group=ann.group, label=ann.label)
            new_anns.append(ann)
        return item.wrap(annotations=new_anns)

dataset = Dataset.import_from('path/', 'format')
dataset.transform(BoxesToPoints)
dataset.export('new_path/', 'format')
```
