### ISSUE TITLE
Is CVAT down? I can't do anything, there's network error all the time. I can save it from time to time, but that's all, it's not even loading properly.

### ISSUE THREAD

**Issue by RoksanaRambus** [openvinotoolkit/cvat#3664]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
It works for me, please try to investigate your network issue with `traceroute` tool or smth like that.

**Comment by bsekachev** [comment]
There is not response from your side. I will close the issue, do not hesitate to reopen if something still is not clear.
