### ISSUE TITLE
About background labels

### ISSUE THREAD

**Issue by kankanzheli** [openvinotoolkit/cvat#3665]
Want to ask how to add a background label. How to add a label for the background after labeling multiple objects in one image.

**Comment by azhavoro** [comment]
Hi,
You can change the order of objects with the z-order slider: https://openvinotoolkit.github.io/cvat/docs/manual/basics/workspace/
Also, hope this will be helpful https://openvinotoolkit.github.io/cvat/docs/manual/advanced/annotation-with-polygons/creating-mask/

**Comment by bsekachev** [comment]
There is not response from your side. I will close the issue, do not hesitate to reopen if something still is not clear.
