### ISSUE TITLE
Frames fail to load for some videos with Chrome 92 but not with Chrome 91

### ISSUE THREAD

**Issue by manybodycpa** [openvinotoolkit/cvat#3668]
### My actions before raising this issue

* Verified that the issue occurs for several videos (more than 10 at the moment, out of about 1000).
* Cleared browser cache, logged out user, accessed CVAT from different machine, tested different browsers and CVAT versions.

Superficially related issues: #3126, #3373

### Expected Behaviour

All annotators can access and annotate all frames of a video if they have access to the task.

### Current Behaviour

Annotators using Chrome 92 on Windows encounter videos for which some or even all frames cannot be loaded. Depending on the video, the inaccessible frames may start at frame 0 or at a later frame. Direct access of the frames by entering the frame number is also not possible in general, although it sometimes allows loading some of the frames.

Here are some screen shots showing the error message and some debugging information from the browser for two different videos.

![image005](https://user-images.githubusercontent.com/51188795/133067455-56ae623c-b810-4d6b-a154-c02752dc9090.png)

![image003](https://user-images.githubusercontent.com/51188795/133067457-41316bf5-0c3a-4ee2-932d-b9ad47aff8da.png)

![image007](https://user-images.githubusercontent.com/51188795/133067451-204ce22a-0013-403c-aae7-fc3f168d705f.png)

Accessing the same server from a Ubuntu client, the problem occurs for the same videos when using Chrome 92 but is absent when using Chrome 91 (detailed versions below).

### Steps to Reproduce (for bugs)

* Upload a problematic video
* Use Chrome 92 to access the resulting CVAT task
* Go through the video frames until the problem appears

I would be willing to share a video directly with the developers if absolutely necessary. Alternatively, a WebEx call could be organized for demonstration and further debugging.

### Context

The affected videos cannot be annotated as required.

### Your Environment

The problem has been observed on two separate CVAT instances, both accessed via a VPN tunnel.

#### CVAT instance 1

* Server version: 1.2b0
* Core version: 3.10.0
* Canvas version: 2.2.1
* UI version: 1.11.1
* git hash: 65b29a6818cb29dbb1a6542ba8e5463c8d566de7

#### CVAT instance 2

* Server version: 1.4
* Core version: 3.12.1
* Canvas version: 2.4.3
* UI version: 1.19.1
* git hash: 315c9cc8d2b1c8fbd3b6b5e6ab6fca3a792bc895

#### Server

The instances are hosted on the same virtual machine, which has the following specs:

* Ubuntu 4.15.0-117-generic x86_64 x86_64 x86_64 GNU/Linux
* Docker version: 19.03.12
* No Docker Swarm or Kubernetes

#### Browser on clients

Different version of Chrome were tested on a Ubuntu client:

* 91.0.4472.114 (problem absent)
* 92.0.4515.159 (problem occurs)

Windows clients used version 92.0.4515.159

**Comment by azhavoro** [comment]
@manybodycpa Hi,
Is it possible to share such video (via email if you dont want to publish it here) or provide detailed information about the video with `ffprobe` tool?

**Comment by manybodycpa** [comment]
@azhavoro I would prefer not to share the videos but can of course provide meta information first. 

Here is the output of ffprobe, please let me know if you need additional information:

```
 ffprobe version 4.3.2-0york0~18.04 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mxf, from 'bayern-037_R-024-cl.MXF':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    uid             : adab4424-2f25-4dc7-92ff-29bd000c0000
    generation_uid  : adab4424-2f25-4dc7-92ff-29bd000c0001
    company_name    : FFmpeg
    product_name    : OP1a Muxer
    product_version : 58.45.100
    product_uid     : adab4424-2f25-4dc7-92ff-29bd000c0002
    material_package_umid: 0x060A2B340101010501010D00139A620952947134559A62090052947134559A00
    timecode        : 13:49:22:34
  Duration: 00:00:19.92, start: 0.000000, bitrate: 35334 kb/s
    Stream #0:0: Video: mpeg2video (Main), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 50 tbn, 100 tbc
    Metadata:
      file_package_umid: 0x060A2B340101010501010D00139A620952947134559A62090052947134559A01
    Side data:
      cpb: bitrate max/min/avg: 35000000/0/0 buffer size: 9781248 vbv_delay: N/A
```

**Comment by manybodycpa** [comment]
@azhavoro I now have CVAT version 1.6 installed on my local machine as well. I can confirm that I have at least one video that shows the problem on 1.6 and Chrome 93 but not on Chrome 91. If you can provide an e-mail address, I can share it.

**Comment by manybodycpa** [comment]
Options were all per default. Video on the way.

**Comment by azhavoro** [comment]
@manybodycpa Hi, I tried your video and I cannot reproduce the issue, all frames load without problems in Chrome 93.0.4577.82 and Chromium 91.0.4472.0 (I could not find Chrome 91.x.x.x release quickly) on Windows and Linux.
So, according to the attached logs, it doesn't look like a issue with this particular video, it looks like there is some issue with loading web assembly module that I cannot reproduce on my side.
Could you please attach Chrome HAR file (open dev tools, go to Network tab, reproduce the issue and export HAR file) or send it via email? It will be good if you recorded HARs for 91(without issue) and 93(with issue) Chrome.

Thanks.

**Comment by manybodycpa** [comment]
Following your advice, the issue appears to be solved (so far) after adjusting the value of chunk_size. Specifically, this value had not been set before in the API call. Setting chunk_size to 8 resolves the problem independent of the Chrome version. Thank you!
