### ISSUE TITLE
uploading CVAT 1.1 XML file

### ISSUE THREAD

**Issue by med-tz** [openvinotoolkit/cvat#3675]
Couldn't upload annoatarions on CVAT online platform it was working just fine yesterday

**Comment by med-tz** [comment]
Couldn't upload annoatarions on CVAT online platform it was working just fine yesterday

**Comment by lakshaymehra** [comment]
Facing the same issue. The task is getting created but whenever I try to import annotations in any format, nothing gets uploaded. Hopefully this gets fixed soon with high priority.

**Comment by Marishka17** [comment]
@dvkruchinin , Can you take a look at this issue?

**Comment by dvkruchinin** [comment]
> Can you take a look at this issue?

@Marishka17 
Perhaps the author of the change in the code should look at this. I was only engaged in adapting tests.
