### ISSUE TITLE
Create Task Fails With Large Files

### ISSUE THREAD

**Issue by omerergun1123** [openvinotoolkit/cvat#3691]
I can create497mb task on cvat.org but cannot create same task on cvat which is deployed on AWS machine. The logs that I get on cvat container:

[Thu Sep 16 12:09:16.214778 2021] [wsgi:info] [pid 336:tid 140316382443264] mod_wsgi (pid=336): Daemon process request time limit exceeded, stopping process 'localhost:8080'
[Thu Sep 16 12:21:57.519115 2021] [wsgi:error] [pid 274:tid 140316656023296] [client 192.168.1.144:57644] mod_wsgi (pid=274): Request data write error when proxying data to daemon process: Broken pipe., referer: http://192.168.1.83:7080/

**Comment by omerergun1123** [comment]
Is there any different method related to deployment of cvat.org differs from mine on machine. I mean something recovers when network lives momentarty disconnections during upload. I see that broken pipe log then cvat container restrarts itself

**Comment by bsekachev** [comment]
Hi @omerergun1123 

You can try creating a task using data from shared storage/remote sources/AWS or other cloud storages. 
Please, refer to [documentation](https://github.com/openvinotoolkit/cvat/pull/3372) to learn more. 
Also there are options to mount cloud storage to a local filesystem: https://openvinotoolkit.github.io/cvat/docs/administration/advanced/mounting_cloud_storages/

Documentation about cloud storages is not ready yet, but PR is: https://github.com/openvinotoolkit/cvat/pull/3372

**Comment by nmanovic** [comment]
@omerergun1123 , I will close the issue. Don't hesitate to ask our https://gitter.im/opencv-cvat/public community if you have more questions.

**Comment by japel** [comment]
https://github.com/openvinotoolkit/cvat/issues/1080
