### ISSUE TITLE
Question: How can I apply a tag/label to all images in a task?

### ISSUE THREAD

**Issue by ri-ceres** [openvinotoolkit/cvat#3695]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

How can I apply a tag/label to all items in a task?

For example, say I have an image dataset of cats and dogs, where cats are in one folder and dogs in another. Is there an easy way to add the images and apply a tag based on this folder structure?

**Comment by bsekachev** [comment]
Hi, I can only suggest generating annotations file and upload it after the task is created. Would it be an option?

**Comment by ri-ceres** [comment]
Seems like generating annotations first would be a lot of effort for something that could be a single click in the GUI, or automatically generated on import unless I'm missing something obvious. There are a lot of real-world data formatted in a directory structure where folder names serve as labels.

If there isn't currently a way to achieve this, maybe this is less a question and more a feature request?

**Comment by bsekachev** [comment]
Let's add a "feature request" label, but I personally don't have ideas how it could be implemented in UI in a unified way.
If you have ideas, or examples of annotation tools where it is implemented, please, share.

**Comment by nmanovic** [comment]
@ri-ceres , try to use https://github.com/openvinotoolkit/datumaro for the purpose to generate required annotation file.
