### ISSUE TITLE
Cannot Access CVAT from Outside Localhost (i.e., using my own domain)

### ISSUE THREAD

**Issue by digiwang** [openvinotoolkit/cvat#3698]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

Access CVAT from Chrome by navigating to **http://cvat.ai-lab.edu:8080**. I should also mention that I everything works fine when accessing CVAT from localhost. But, multiple people will be using this server and so it needs to work on our domain network.

### Current Behaviour

In Chrome I get, "This site can’t be reached. The connection was reset."

### Steps to Reproduce (for bugs)

1. Followed [CVAT Installation Instructions](https://github.com/openvinotoolkit/cvat/blob/v1.4.0/cvat/apps/documentation/installation.md) for **v1.4.0**.
1. Set the CVAT_HOST parameter to **cvat.ai-lab.edu** in the `docker-compose.override.yml` file.
```sh
version: '3.3'

services:
  cvat_proxy:
    environment:
      CVAT_HOST: cvat.ai-lab.edu

  cvat:
    environment:
      CVAT_SHARE_URL: 'Mounted from ai-lab /data NFS'
    volumes:
      - cvat_share:/home/django/share

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /data
      o: bind
```
* cvat/docker-compose.yml
```sh
#
# Copyright (C) 2018-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: openvino/cvat_server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      ADAPTIVE_AUTO_ANNOTATION: 'false'
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs

  cvat_ui:
    container_name: cvat_ui
    image: openvino/cvat_ui
    restart: always
    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat

  cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - cvat
      - cvat_ui
    environment:
      CVAT_HOST: localhost
    ports:
      - '8080:80'
    volumes:
      - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
```

* cvat/cvat_proxy/conf.d/cvat.conf.template
```sh
server {
    listen       80;
    server_name  _ default;
    return       404;
}

server {
    listen       80;
    server_name  ${CVAT_HOST};

    proxy_pass_header       X-CSRFToken;
    proxy_set_header        Host $http_host;
    proxy_pass_header       Set-Cookie;

    location ~* /api/.*|git/.*|opencv/.*|analytics/.*|static/.*|admin(?:/(.*))?.*|documentation/.*|django-rq(?:/(.*))? {
        proxy_pass              http://cvat:8080;
    }

    location / {
        proxy_pass              http://cvat_ui;
    }
}
```
1. Ran containers with `docker-compose up -d`
1. Navigated to **http://cvat.ai-lab.edu:8080** in Chrome and got a "This site can’t be reached. The connection was reset." page. 

> **INFO:** However, if I navigate to **http://cvat.ai-lab.edu** I get the default Nginx CentOS landing page.

### Your Environment

- Git hash commit (`git log -1`): 315c9cc8d2b1c8fbd3b6b5e6ab6fca3a792bc895 (**release-1.4.0**)
```sh
commit 315c9cc8d2b1c8fbd3b6b5e6ab6fca3a792bc895 (HEAD, tag: v1.4.0)
Merge: c7033a79 3ca86bcf
Author: Nikita Manovich <nikita.manovich@intel.com>
Date:   Wed May 19 07:26:02 2021 +0300

    Merge branch 'release-1.4.0'
```
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.8
```sh
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:43:57 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Are you using Docker Swarm or Kubernetes? **No**
- Operating System and version (e.g. Linux, Windows, MacOS): **CentOS v7**
- Code example or link to GitHub repo or gist to reproduce problem: I tried my best to follow the  [CVAT Installation Instructions](https://github.com/openvinotoolkit/cvat/blob/v1.4.0/cvat/apps/documentation/installation.md).

### Additional Logs
* Output from `docker exec -it cvat_proxy nginx -T`
[docker_exec_it_cvat_proxy_nginx_T.txt](https://github.com/openvinotoolkit/cvat/files/7205530/docker_exec_it_cvat_proxy_nginx_T.txt)

* Output from `docker exec -it cvat_ui nginx -T`
[docker_exec_it_cvat_ui_nginx_T.txt](https://github.com/openvinotoolkit/cvat/files/7205682/docker_exec_it_cvat_ui_nginx_T.txt)

* Output from `docker logs cvat_ui`
[docker_logs_cvat_ui.txt](https://github.com/openvinotoolkit/cvat/files/7205686/docker_logs_cvat_ui.txt)

* Output from `docker exec -it cvat_ui cat /usr/share/nginx/html/index.html`
```sh
<!--
 Copyright (C) 2020 Intel Corporation

 SPDX-License-Identifier: MIT
-->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
            name="description"
            content="Computer Vision Annotation Tool (CVAT) is a free, open source, web-based image and video annotation tool which is used for labeling data for computer vision algorithms. CVAT supports the primary tasks of supervised machine learning: object detection, image classification, and image segmentation. CVAT allows users to annotate data for each of these cases"
        />
        <meta name="”robots”" content="index, follow" />
        <title>Computer Vision Annotation Tool</title>
    </head>

    <body>
        <div id="root"></div>
        <div id="layout-grid"></div>
    <script type="text/javascript" src="/cvat-ui.6b2ae289a73efc92057f.min.js"></script></body>
</html>
```

* Output from `docker ps`
![image](https://user-images.githubusercontent.com/3182804/134234823-8e2eff77-97dc-402a-bd64-26214c79f0cc.png)

* Output from `docker logs cvat_proxy` returned nothing.

I am stumped... Please help if you can.

**Comment by alalek** [comment]
Compare output of these commands (from the machine with docker containers):

```
curl -v http://127.0.0.1
curl -v --connect-to cvat.ai-lab.edu:80:127.0.0.1:80 http://cvat.ai-lab.edu
curl -v http://cvat.ai-lab.edu
```

**Comment by bsekachev** [comment]
@azhavoro Could you please look here?

**Comment by digiwang** [comment]
> Compare output of these commands (from the machine with docker containers):
> 
> ```
> curl -v http://127.0.0.1
> curl -v --connect-to cvat.ai-lab.edu:80:127.0.0.1:80 http://cvat.ai-lab.edu
> curl -v http://cvat.ai-lab.edu
> ```

Here is output from `curl -v http://127.0.0.1`:
[curl_v_127.0.0.1.txt](https://github.com/openvinotoolkit/cvat/files/7246589/curl_v_127.0.0.1.txt)

Here is the output from `curl -v --connect-to cvat.ai-lab.edu:80:127.0.0.1:80 http://cvat.ai-lab.edu`
[curl_v_connect-to.txt](https://github.com/openvinotoolkit/cvat/files/7246558/curl_v_connect-to.txt)

Here is output from `curl -v http://cvat.ai-lab.edu`:
[curl_v_connect-to.txt](https://github.com/openvinotoolkit/cvat/files/7246613/curl_v_connect-to.txt)

In all cases I seem to get the default CentOS landing page.

**Comment by bsekachev** [comment]
Hi @digiwang 

I am not a network specialist, just have an idea. Do not you think it can be related with 2nd domain level **cvat** . **ai-lab** . **edu**?
I mean that it was not our use case before and not sure CVAT setups support it. 

As far as I know "ai-lab.edu" should have its DNS table to resolve subdomain "cvat". Have you setup it?
Did you try to setup CVAT on host "ai-lab.edu"? (maybe with a different port)

**Comment by bsekachev** [comment]
Hi @digiwang

I am not a network specialist, just have an idea. Do not you think it can be related with 2nd domain level cvat . ai-lab . edu?
I mean that it was not our use case before and not sure CVAT setups support it.
Did you try to setup CVAT on host "ai-lab.edu"? (maybe with a different port)

**Comment by bsekachev** [comment]
@digiwang 

What is hostname of the server where you have installed CVAT?
What is output for ``host -v user-Z170M-D3H.inn.intel.com``. Does it match IP address of the server in LAN?

**Comment by alalek** [comment]
@ 
Author
digiwang Thank you for update!

Try to fetch content from cvat-proxy directly:
- find IP address: `docker inspect --format '{{ .NetworkSettings.IPAddress }}' cvat_proxy`
- run `curl -v http://<IP>:80` (and other experiments with replaced 127.0.0.1 => IP)

---

> get the default CentOS landing page

This is strange, because:

```
  cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
```

"alpine" should not emit CentOS messages.

Please shutdown CVAT containers and check availability of port 80. You can reuse `curl -v http://127.0.0.1` from above.
Expected output is "Connection refused" or similar. If you still see "CentOS landing page" then you need to turnoff that process/service (not related to CVAT).
Use `ss -lnpt` to find process which occupies port 80 (root user is required to see process names).

**Comment by nmanovic** [comment]
@digiwang , I hope you solved the issue. Don't hesitate to ask help on our https://gitter.im/opencv-cvat/public
