### ISSUE TITLE
Task Creation fails - Serialization/Axios issue 0.21.3

### ISSUE THREAD

**Issue by Vafilor** [openvinotoolkit/cvat#3699]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Creating a task should work.

### Current Behaviour

An error occurs as API does not get the correct object type - it gets a string.
Error:

```
​ Error: Request failed with status code 400. {"non_field_errors":["Invalid data. Expected a dictionary, but got str."]}.
```

### Possible Solution

Change axios dependency in `cvat/cvat-core` to `^0.21.4`.

There's a JSON transform issue fix: https://github.com/axios/axios/releases/tag/v0.21.4

### Steps to Reproduce (for bugs)

1. Update to use axios v0.21.3 by running `npm install` in `cvat/cvat-core`.
2. Run cvat ui
3. Try to create a task

### Context

I can't create tasks, and other API endpoints fail because the input data is a string, and not a dict or list.

### Your Environment

- Git hash commit (`git log -1`): `8d03ed7959632d6f3ffd76020ad577fa409acfcd`
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes?: N/A - running locally
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS BigSur - 11.3 (20E232)
- Code example or link to GitHub repo or gist to reproduce problem: N/A
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

I can create a PR, but I seem to have significant `package-lock.json` changes in `cvat-core`, and I'm not sure if those changes would interfere with the setup you have.

**Comment by nmanovic** [comment]
@Vafilor , thanks for the report. Could you please help us to fix the issue and contribute?

**Comment by bsekachev** [comment]
@Vafilor 

> Update to use axios v0.21.3 by running npm install in cvat/cvat-core.

Also would suggest using ``npm ci`` (which installs exact versions from package-lock.json) instead of ``npm install``

**Comment by Vafilor** [comment]
> @Vafilor , thanks for the report. Could you please help us to fix the issue and contribute?

Sure thing - https://github.com/openvinotoolkit/cvat/pull/3706.

**Comment by nmanovic** [comment]
@Vafilor , thanks for the fix. I will close the issue.
