### ISSUE TITLE
How to integrate kibana with CVAT

### ISSUE THREAD

**Issue by ishtiyAhemad** [openvinotoolkit/cvat#3700]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi, please follow user guide: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/analytics/

**Comment by bsekachev** [comment]
I will close the issue because there is not a response from your side. If you still have questions, do not hesitate to reopen it.
