### ISSUE TITLE
Assign track ID over successive frames 

### ISSUE THREAD

**Issue by ayanasser** [openvinotoolkit/cvat#3705]
I saw many people using Cvat with assigning tracking unique Ids over successive frames
Is there a tutorial or document to illustrate how this could be done ?

**Comment by bsekachev** [comment]
Hi @ayanasser

I probably don't understand you request fully. Could you please clarify? (maybe with an example)

**Comment by ayanasser** [comment]
Hello @bsekachev, 

Thank you for the fast reply ^^
What I mean is, I want to work with tracking annotation task (The task contains successive frames of a video) 
Work with the first frame and do the following: 
- Draw a bbx around each object 
- Assign a unique ID for each object
- **"Find a way to copy what I have done with those objects through number of future frames "**

I need help with that last step, is this clear

**Comment by bsekachev** [comment]
I suspect Tracks are exactly what you need. Just draw it on the first frame, than go for example 10 frames forward, shift the boxes according to the current position of objects and go back to frames 1..9 to see how it was interpolated. Adjust if necessary.

https://openvinotoolkit.github.io/cvat/docs/manual/basics/track-mode-basics/
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/track-mode-advanced/

**Comment by ayanasser** [comment]
Thank you ^^
