### ISSUE TITLE
Task dir does not exist

### ISSUE THREAD

**Issue by dmitryzykovArtis** [openvinotoolkit/cvat#3709]
### My actions before raising this issue
I have annotated dataset. 7000 images with bounding boxes, and want to export it.
Click on Save or Export as dataset

### Expected Behaviour
All works

### Current Behaviour
Save Notification:
"Could not send logs to the server
Open the Browser Console to get details"

Export as Dataset Notification:
"Could not export dataset for the task 41
Error: Request failed with status code 500. "FileNotFoundError: [Errno 2] No such file or directory: '/home/django/data/tasks/41/logs/task.log'\n"."

"docker logs cvat" 
[logs.txt](https://github.com/openvinotoolkit/cvat/files/7214626/logs.txt)

main exception is "Task dir does not exist" if I understand it right.

### Your Environment
- Docker
- Windows

I don't know what to do, but don't want lose my annotated data. But cannot export it. Can anybody help?

**Comment by bsekachev** [comment]
Hi @dmitryzykovArtis 

I am not sure how it could happen, but you can go to cvat container and browse it:
```docker exec -it cvat /bin/bash```

Then navigate to ``/home/django/data/tasks/41/`` and look if there is ``logs`` directory, if not, try to create.

**Comment by bsekachev** [comment]
Hi, hope you coped with your issue.
I will close it because there is not a response from your side. If you still have questions, don't hesitate to reopen it.
