### ISSUE TITLE
Disable export dataset function

### ISSUE THREAD

**Issue by utkarshumarye** [openvinotoolkit/cvat#3715]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Modified this method https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/views.py#L631 to return Response(status=status.HTTP_403_FORBIDDEN).  However when I clicked export data or dump annotation, data is starting to download.

Even modified "views.py" but it is not getting reflected on the tool

**Comment by azhavoro** [comment]
Hi,
1. Please specify correct link on the method which you have modified.
2. Have you read this guide https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/?: 

> Alternative: if you want to build the images locally with unreleased changes run the following command. It will take some time to build CVAT images.
>  ```
>  docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
>  docker-compose up -d
> ```

**Comment by bsekachev** [comment]
Hi @utkarshumarye 

I will close the issue, because there is not response from your side. If you still have questions, do not hesitate to reopen it and ask

**Comment by jansony1** [comment]
Same issue here, I try to modified below two parts 

https://github.com/openvinotoolkit/cvat/blob/439c6d5fb9f48a4f25e89e809f1d3401a70674e6/cvat/apps/engine/views.py#L894
https://github.com/openvinotoolkit/cvat/blob/439c6d5fb9f48a4f25e89e809f1d3401a70674e6/cvat/apps/engine/views.py#L323

to 

```
def dataset_export(self, request, pk):
       Response(status=status.HTTP_403_FORBIDDEN) 
```
But nothing works, user could still download images.
