### ISSUE TITLE
Adjust "Copy labels" feature because it is not obvious now why a task cannot be created, after Ctrl+C, Ctrl+V existing labels from Raw editor

### ISSUE THREAD

**Issue by lokeshn011101** [openvinotoolkit/cvat#3717]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I am trying to annotate a video on cvat of size 157mb. It was working for the past 1 month and I was annotating videos of size <500mb. But suddenly a week ago I got this error.
![image](https://user-images.githubusercontent.com/63955341/134630089-c792d02a-501a-4ce2-9835-7b3445730b20.png)
I tried after 2 days and today also and I was always getting the same error.
I even tried running cvat locally using docker but its giving me the same error.
Please help.

### Expected Behaviour

The task is successfully created.

### Current Behaviour

Error while creating the task.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

I am currently doing a project for school which requires annotating videos.
There aren't any free tools other than cvat which could help me achieve this task. So I started working with cvat for creating bounding boxes for YOLOv5 algorithm.

### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): Windows
- I am using the cvat website for creating the task

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hi, I'm afraid it will be difficult to find these logs on cvat.org, so could you please collect and attach the server logs from your local instance after a failed task creation attempt? Command is: `docker logs cvat> cvat.log`

Thanks

**Comment by lokeshn011101** [comment]
@azhavoro I tried uploading a 157 mb video today locally and the task was created successfully. But then I tried to create a another task with a video of size 222 mb, the task creation failed this time. https://drive.google.com/file/d/1FvsY4HAnki3zVhMc0ttDTzTv3JUAYY-v/view?usp=sharing Please have a look at the logs in this link. Thank you so much! 🙏

**Comment by bsekachev** [comment]
@lokeshn011101 

You probably have copied labels from created task with Ctrl+C and pasted them with Ctrl+V to the new task, right?
So, it is a wrong way because Raw data contains database IDs and looks like you try to create labels with primary keys which already exist. 

Solution: To use button "Copy" in the top right corner of labels form (instead of Ctrl+C).

**Comment by lokeshn011101** [comment]
Damn. That was a silly thing that I missed. Thanks for taking your time and pointing it out! The issue is now resolved!

**Comment by bsekachev** [comment]
Let's consider it like appeal to actions. You are not the first person, who was confused with this issue.
I will reopen it and mark as a enhancement, to find a better solution.

**Comment by nmanovic** [comment]
Let's treat the issue as a UX bug. No need to have a separate button if the usual way to copy is CTRL+C.
