### ISSUE TITLE
could not create task, Error : user has maximum number of task.

### ISSUE THREAD

**Issue by tushar-wagh-bioenable** [openvinotoolkit/cvat#3722]
![cvat-error](https://user-images.githubusercontent.com/68533310/134659886-d46f69cb-d254-4406-b323-351d38431279.PNG)

After uploading images while creating task when press submit button, I get this error.
 "could not create task, Error : user has maximum number of task."

**Comment by bsekachev** [comment]
Hi @tushar-wagh-bioenable 

cvat.org has restricted number of tasks per user for now since for now it is only demo server to show CVAT annotations capabilities.

**Comment by bsekachev** [comment]
I'll close the issue. Let me know if you still have questions about it.
