### ISSUE TITLE
[Feature Request] Request to new interactive segmentation model

### ISSUE THREAD

**Issue by xiong-jie-y** [openvinotoolkit/cvat#3729]
Hi, thank you for developing and maintaining awesome annotation tool!

This is the feature request to add new interactive segmentation model.
Currently f-BRS seems require user many clicks to annotate and sometimes cannot annotate complex object.
This [click based interactive segmentation model](https://github.com/saic-vul/ritm_interactive_segmentation) seems perform better than the current one (f-BRS) from the evaluation in [their paper](https://arxiv.org/abs/2102.06583).

I used this interactive segmentation method both in CVAT and the tool in [the repository](https://github.com/saic-vul/ritm_interactive_segmentation), and feel that it really makes better segmentation than f-BRS. The branch is [here](https://github.com/xiong-jie-y/cvat/commit/cd10713fc22ed59c20f7feb2e4d7f4dfa7cab37b).

I will proceed to prepare for an PR if I you think that this new interactive segmentation model is worth adding to this repository.

Thank you!

**Comment by bsekachev** [comment]
Hi @xiong-jie-y 

The demo looks promising. If you believe it is better than f-BRS, do not think, just send a PR :) Especially if you already have written the code.

Thank you.
