### ISSUE TITLE
Rearrange CVAT labels 

### ISSUE THREAD

**Issue by omarreda14** [openvinotoolkit/cvat#3746]
i need to rearrange a pre-entered labels in CVAT without affecting the annotations made . is there any way to do that ?

**Comment by bsekachev** [comment]
Hi @omarreda14 

Could you please clarify what do you mean on "rearranging pre-entered labels"? It would be great if you provide an example.

**Comment by omarreda14** [comment]
> Hi @omarreda14
> 
> Could you please clarify what do you mean on "rearranging pre-entered labels"? It would be great if you provide an example.

i had entered the classes labels in an order , let's say :
0-person.
1-car.
2-cash.
3-bags.

and then exported the annotated files in YOLO format , but now i need to rearrange
 the classes names to a new order , let's say :
0-car.
1-bags.
2-cash.
3-person.

to fit the exporting file to my model .

**Comment by bsekachev** [comment]
There is no way to do it automatically in CVAT. You probably can open exported data and try to amend them manually.

**Comment by zhiltsov-max** [comment]
Hi, you can try to use [Datumaro](https://github.com/openvinotoolkit/datumaro) for this. Check this answer: https://github.com/openvinotoolkit/datumaro/issues/256#issuecomment-858052945

**Comment by nmanovic** [comment]
@omarreda14 , as Maxim said, you need to use Datumaro framework to transform your data. The framework is responsible for import/export of datasets inside the data annotation tool. CVAT isn't going to support such specific cases because in general there are too many possible transformations.
