### ISSUE TITLE
Update documentation for installing CVAT on Windows

### ISSUE THREAD

**Issue by BaoZhengG** [openvinotoolkit/cvat#3752]
Hi @nmanovic ,

Thanks for updating the documentation on how to use CVAT on WIndows Home. Currently, after updating the docker desktop application to the latest version, I am able to execute docker command via the command prompt provided on Windows, but when I run the command `winpty docker exec -it cvat -ic 'python3 ~/manage.py createsuperuser' it throws the following error saying `'winpty' is not recognized as an internal or external command, operable program or batch file.` 

So I tried running just `docker exec -it cvat -ic 'python3 ~/manage.py createsuperuser' 
This command worked initially but later threw this error. 
```
setupvars.sh] OpenVINO environment initialized
manage.py: unexpected EOF while looking for matching `''
manage.py: syntax error: unexpected end of file
```

Could you please take a look at this and update the documentation? 
Thanks :)

_Originally posted by @kaustubhharapanahalli in https://github.com/openvinotoolkit/cvat/issues/1536#issuecomment-658211951_

**Comment by BaoZhengG** [comment]
docker exec -it cvat -ic 'python3 ~/manage.py createsuperuser

**Comment by nmanovic** [comment]
@BaoZhengG , do you think you can help us and contribute? Just prepare a PR for documentation. It should be more or less easy to do.

![image](https://user-images.githubusercontent.com/40690625/135405276-0041d294-9c91-4623-8390-09971c2e7860.png)

**Comment by kaustubhharapanahalli** [comment]
Hi @BaoZhengG winpty works only on git bash, if you not using git bash, you use it without winpty

**Comment by nmanovic** [comment]
@kaustubhharapanahalli , thanks for your help! It looks like the question is answered. I will close the issue.
