### ISSUE TITLE
Recover password at localhost login page

### ISSUE THREAD

**Issue by clarecatcreates** [openvinotoolkit/cvat#3755]
I had finished two tasks in cvat and didn't export the labels yet. However, when I had to restart Docker I am logged out of CVAT and couldn't remember the correct password. What can I do to reset the password? It would be of great help since I'd like to recover the two tasks I already finished.

**Comment by nmanovic** [comment]
@clarecatcreates , you can create one more superuser. It is the easiest approach:
```
docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
```
