### ISSUE TITLE
Images are copied into the docker FS though using the "Connected file share" option

### ISSUE THREAD

**Issue by yohayonyon** [openvinotoolkit/cvat#3763]
### My actions before raising this issue
- [v] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [v] Searched [past issues](/issues)

### Expected Behaviour

When using the "Connected file share" option Images files will not be copied into the docker FS.

### Current Behaviour

Images are copied into the docker FS though using the "Connected file share" option. Checking or unchecking "Copy data into CVAT" just changed the location.

### Possible Solution

Use the given files...

### Steps to Reproduce (for bugs)

1. Follow the instructions here: https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#share-path to mount a shared folder.
2.  Use the "Connected file share" on the create task screen (or by CLI).
3.  Check or uncheck "Copy data into CVAT" from GUI just changes the location of the copied files.
4. The following images show where the files are located on the system here. Tasks 2 and 3 there were created with check and unchecked "Copy data into CVAT".

![Screenshot-from-2021-09-22-19-31-46](https://user-images.githubusercontent.com/61744528/135745654-6465f83f-d121-4cf7-8cb4-7f84eb0f0749.png)

![Screenshot-from-2021-09-22-19-28-59](https://user-images.githubusercontent.com/61744528/135745660-2525b933-94e1-4546-af83-244413322080.png)

![Screenshot-from-2021-09-22-19-30-21](https://user-images.githubusercontent.com/61744528/135745663-3b684e16-57e9-4540-a041-9e11fa4294c0.png)

### Context

A lot of old data is planned to be accessed and not copied by CVAT for annotation and viewing. Creating light tasks without images seemed like a simple solution.

### Your Environment

- Git hash commit (`git log -1`): v1.6.0
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.8
- Are you using Docker Swarm or Kubernetes? None
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Other diagnostic information / logs: Refer to the images.

**Comment by Marishka17** [comment]
@yohayonyon , Hi, as you mentioned, you used a tar file, right? Unfortunately, in the current implementation, it's impossible to use archive from a mounted share without coping because CVAT uses unzipped images and of course we cannot unzip files to mounted share. However, you can use a dataset with images or video from mounted share, and in this case, files aren't copied into CVAT. (if the `Copy data into CVAT` checkbox is unchecked)

**Comment by yohayonyon** [comment]
@Marishka17, thank you for your answer. Do you think that with the current design it will be not too complicated to implement untar on demand?

**Comment by Marishka17** [comment]
As I mentioned early, CVAT use extracted images and there is a certain reason for that. I can suppose that there isn't one tool/module for work with archives like ffmpeg for videos. I think it isn't very simple task, but we welcome any ideas and contributions.
@azhavoro , Could you please correct me If I'm wrong?

**Comment by nmanovic** [comment]
@yohayonyon , in theory it is possible to mount tar archives using [archivemount](https://csatlas.com/mount-tar-file-ubuntu/) but we are not going to invest resources into the direction. I will recommend just untar your archive.

Thanks for you time. If you like contribute, we are happy to accept your code. For now I will close the report.
