### ISSUE TITLE
Installation without Docker

### ISSUE THREAD

**Issue by anjugopinath** [openvinotoolkit/cvat#3765]
Is it possible to install cvat without docker?
I came across this thread https://github.com/openvinotoolkit/cvat/issues/2946
But, the solution posted https://github.com/openvinotoolkit/cvat/blob/develop/CONTRIBUTING.md
shows 404

**Comment by nmanovic** [comment]
https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/

**Comment by Legend94rz** [comment]
@nmanovic hi, the link your provided above is also 404. could you please leave the new link?

**Comment by nmanovic** [comment]
https://opencv.github.io/cvat/docs/contributing/development-environment/
