### ISSUE TITLE
How to move several annotation boxes together?

### ISSUE THREAD

**Issue by JimXu1989** [openvinotoolkit/cvat#3780]
Hi
Thanks for sharing the great tool !

When I annotate a video, I want move several bboxes together, is there any method make it possible?

**Comment by bsekachev** [comment]
@nmanovic 

Probably in a video several objects can move the same way at approximately the same speed

**Comment by nmanovic** [comment]
@bsekachev , probably we should not guess. I will close the issue. 

@JimXu1989 , if you can describe the scenario in more details, don't hesitate to reopen.

**Comment by JimXu1989** [comment]
> @nmanovic
> 
> Probably in a video several objects can move the same way at approximately the same speed

That's the point!
