### ISSUE TITLE
Feature Request - ability to rotate images and annotations independently .

### ISSUE THREAD

**Issue by kurtjcu** [openvinotoolkit/cvat#3782]
I have been working with using external automatic annotation(DL model) and external manual annotations(VGG) and uploading annotations into CVAT. Many times the annotations are 90 or 180 degrees out of alignment with the image.

Being able to rotate image/annotations independently of each other would be a great feature. :)

**Comment by nmanovic** [comment]
@kurtjcu , thanks for the idea. But it doesn't look like a common use cases. There to many requests and I'm not sure we have ability to implement the feature request. Don't hesitate to contribute. I will close the issue.

@kurtjcu , one more idea. It can be a good feature request for Datumaro: https://github.com/openvinotoolkit/datumaro
