### ISSUE TITLE
point delete bug

### ISSUE THREAD

**Issue by laol777** [openvinotoolkit/cvat#3821]
### My actions before raising this issue
- [ ] similar to https://github.com/openvinotoolkit/cvat/issues/1391

### Expected Behaviour
just remove one point

### Current Behaviour
random point is removed

### Steps to Reproduce (for bugs)

1.   https://u.pcloud.link/publink/show?code=XZkKiEXZqcJUymaSNN5fOUnR05q1LhmNYLvX

### Your Environment
Server version: 1.6
Core version: 3.16.0
Canvas version: 2.7.0
UI version: 1.23.1
linux

**Comment by laol777** [comment]
@ActiveChooN any updates about this task? could you reproduce this problem?

**Comment by ActiveChooN** [comment]
@laol777, have no opportunity to check this issue

**Comment by nmanovic** [comment]
We are going to address the issue in next releases
