### ISSUE TITLE
storage.Client without service account path can't be called (GoogleCloudStorage)

### ISSUE THREAD

**Issue by engineer-exercise** [openvinotoolkit/cvat#3831]
### Overview

CloudStorageSerializer class has a validate func to avoid without gcp service account path.
https://github.com/openvinotoolkit/cvat/blob/78158cbcf5a19ea11389a7dfe7d6d6ac6df8dd06/cvat/apps/engine/serializers.py#L837

It causes that `storage.Client()` without service account path can't be called.
https://github.com/openvinotoolkit/cvat/blob/78158cbcf5a19ea11389a7dfe7d6d6ac6df8dd06/cvat/apps/engine/cloud_provider.py#L364

But in some case, `storage.Client()` without service account path is available (e.g. GKE Workload Identity / VM) and then it can't set service account path.

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible Solution

- Remove `if not attrs.get('key_file_path', '')` from a validate func.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by Marishka17** [comment]
@engineer-exercise, Hi, Could you please prepare PR with these changes?

**Comment by engineer-exercise** [comment]
@Marishka17 I've prepared PR #3831
