### ISSUE TITLE
Something happened to the website and the processing speed

### ISSUE THREAD

**Issue by decadance-dance** [openvinotoolkit/cvat#3837]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
About 2 weeks ago, at the same time of day, I downloaded a dataset with 1k images. Auto-rotation didn't take very long, which was good. 

### Current Behaviour
But now I have uploaded a dataset of 200 images and the auto-annotation has not advanced by 1 percent. I also began to see hash requests in the network packet log, the answer to which is the statuses of not my tasks, that is, I see which tasks are currently being processed. I'm not sure if this was not the case before, but now it definitely is. 

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
![Screenshot from 2021-10-27 17-57-21](https://user-images.githubusercontent.com/86170544/139091783-f178caf8-ecf9-4a7a-b187-559ae609c240.png)

**Comment by nmanovic** [comment]
@decadance-dance , I will close the issue. It looks like Andrey answered the question.
