### ISSUE TITLE
ERROR RUN npm run build:cvat-ui

### ISSUE THREAD

**Issue by ChangSeobYun** [openvinotoolkit/cvat#3840]
i try to "docker-compose -f docker-compose.yml -f docker-compose.dev.yml build" but i have error 
what is the problem?

 > [openvino/cvat_ui cvat-ui 15/15] RUN npm run build:cvat-ui:
#54 0.541
#54 0.541 > cvat@1.0.0 build:cvat-ui
#54 0.541 > npm run build --workspace=cvat-ui
#54 0.541
#54 0.778
#54 0.778 > cvat-ui@1.25.0 build
#54 0.778 > webpack --config ./webpack.config.js
#54 0.778
#54 1.884 Error: error:0308010C:digital envelope routines::unsupported
#54 1.884     at new Hash (node:internal/crypto/hash:67:19)
#54 1.884     at Object.createHash (node:crypto:130:10)
#54 1.884     at module.exports (/tmp/node_modules/webpack/lib/util/createHash.js:135:53)
#54 1.884     at NormalModule._initBuildHash (/tmp/node_modules/webpack/lib/NormalModule.js:417:16)
#54 1.884     at handleParseError (/tmp/node_modules/webpack/lib/NormalModule.js:471:10)
#54 1.884     at /tmp/node_modules/webpack/lib/NormalModule.js:503:5
#54 1.884     at /tmp/node_modules/webpack/lib/NormalModule.js:358:12
#54 1.884     at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
#54 1.884     at iterateNormalLoaders (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
#54 1.884     at iterateNormalLoaders (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
#54 1.884     at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
#54 1.884     at runSyncOrAsync (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
#54 1.884     at iterateNormalLoaders (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
#54 1.884     at Array.<anonymous> (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
#54 1.884     at Storage.finished (/tmp/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
#54 1.884     at /tmp/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
#54 1.884     at /tmp/node_modules/graceful-fs/graceful-fs.js:123:16
#54 1.884     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
#54 2.357 node:internal/crypto/hash:67
#54 2.357   this[kHandle] = new _Hash(algorithm, xofLen);
#54 2.357                   ^
#54 2.357
#54 2.357 Error: error:0308010C:digital envelope routines::unsupported
#54 2.357     at new Hash (node:internal/crypto/hash:67:19)
#54 2.357     at Object.createHash (node:crypto:130:10)
#54 2.357     at module.exports (/tmp/node_modules/webpack/lib/util/createHash.js:135:53)
#54 2.357     at NormalModule._initBuildHash (/tmp/node_modules/webpack/lib/NormalModule.js:417:16)
#54 2.357     at handleParseError (/tmp/node_modules/webpack/lib/NormalModule.js:471:10)
#54 2.357     at /tmp/node_modules/webpack/lib/NormalModule.js:503:5
#54 2.357     at /tmp/node_modules/webpack/lib/NormalModule.js:358:12
#54 2.357     at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
#54 2.357     at iterateNormalLoaders (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
#54 2.357     at iterateNormalLoaders (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
#54 2.357     at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
#54 2.357     at context.callback (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
#54 2.357     at /tmp/node_modules/babel-loader/lib/index.js:59:71 {
#54 2.357   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#54 2.357   library: 'digital envelope routines',
#54 2.357   reason: 'unsupported',
#54 2.357   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#54 2.357 }
#54 2.357
#54 2.357 Node.js v17.0.1
#54 2.363 npm ERR! Lifecycle script `build` failed with error:
#54 2.364 npm ERR! Error: command failed
#54 2.364 npm ERR!   in workspace: cvat-ui@1.25.0
#54 2.364 npm ERR!   at location: /tmp/cvat-ui
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c npm run build:cvat-ui]: exit code: 1

**Comment by bsekachev** [comment]
The issue looks to be solved. CI works fine now for newly submitted PRs. I will close the issue, do not hesitate to reopen if you still have difficulties

**Comment by jeyyoon** [comment]
@bsekachev 
what is the main reason of this issue(npm ci error)?
I forked cvat repo 4 months ago and developed it for our own annotation job(based on release-1.5.0 branch.)

last week, when I ran build command, it failed with npm ci error.
I tried to build with openvinotookit/cvat 'develop' branch and it was built successfully.

I want to fix my cvat but there are too many commits and I can't find which commit can solve the problem.
Could you give me some hints?

Thank you.

**Comment by bsekachev** [comment]
@jeyyoon 

To be honest, I don't know.
Incompatibilities between new node version and webpack probably.
If you google it, you can find different explanations because it affected many people around. 

I just changed base image in Dockerfile.ui to LTS version.
