### ISSUE TITLE
Polylines are not visible on segmentation masks

### ISSUE THREAD

**Issue by ehsan2563** [openvinotoolkit/cvat#3846]
Hi ,I want to use the Polyline for images segmentation but when I use it ,nothing is shown on the bitmap or I cant get a dataset as in "segmentation mask" out of it. can anyone give me a solution pls

**Comment by bsekachev** [comment]
Hi @ehsan2563 

Could you please provide more details? Steps, screenshots, CVAT version, etc.

**Comment by nmanovic** [comment]
@ehsan2563 , please don't hesitate to post the question on our gitter chat: https://gitter.im/opencv-cvat/public
I will close the issue.

**Comment by ehsan2563** [comment]
> Hi @ehsan2563
> 
> Could you please provide more details? Steps, screenshots, CVAT version, etc.

hi thank you for answering
I use the cvat.org and as you can see the polygon is shown but the polyline is not, and when I want to get my dataset as in "segmentation mask ", there is no outcome from polyline
![22](https://user-images.githubusercontent.com/87540099/140297739-fd79d55f-5a29-46b7-adcd-bb212322d1fb.png)
![11](https://user-images.githubusercontent.com/87540099/140297745-d69a0478-4a8c-4094-8235-72cf380afadd.png)

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please comment?

**Comment by zhiltsov-max** [comment]
Hi, currently, there is no dataset formats in CVAT, supporting polyline annotations, except `CVAT for *` and `Datumaro`. Could you describe the result you are trying to achieve?

**Comment by bsekachev** [comment]
Polylines are infinitely thin and it's why they are absent on a bitmap (zooming them in CVAT you see that polylines can be thinner than 1px).

**Comment by nmanovic** [comment]
@zhiltsov-max , @bsekachev , in some cases it can be useful to annotate curves using polylines and generate masks. But probably we need to support the feature together with brush tool. Polylines should have zero area. I will mark the issue as duplicate for brush and close.

**Comment by nmanovic** [comment]
https://github.com/openvinotoolkit/cvat/issues/1849
