### ISSUE TITLE
Tutorial for automatic annotation using own custom model

### ISSUE THREAD

**Issue by Yoon5** [openvinotoolkit/cvat#3857]
Hello, I try to find a way for adding my own model to cvat for automatic annotation. Do you have a clear tutorial for this situation? I try to do it using https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models. But above tutorial not clear

**Comment by nmanovic** [comment]
@Yoon5 , could you please explain how we can improve the tutorial?

**Comment by Yoon5** [comment]
If I understood the steps. For auto labeling first I need to add my custom model for cvat models using  https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models this tutorial and then I need to follow by this step for auto annotation https://openvinotoolkit.github.io/cvat/docs/manual/advanced/automatic-annotation/. I am right? And did auto annotation work for segmentation cases or only for bbox ?

**Comment by nmanovic** [comment]
@Yoon5 , auto annotation works for segmentation cases. I still don't understand what is wrong with the tutorial. Did you try it? Where did you have problems with understanding? I'm open to improve the tutorial, but really need to understand which step was not clear.

**Comment by FarranYang** [comment]
hi, I am not familiar with docker and nuctl， after reading [https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-model)s where should I add  ‘pth.facebookresearch.detectron2.retinanet_r101’ and ‘./serverless/pytorch/facebookresearch/detectron2/retinanet/’. I am so confused.

**Comment by nmanovic** [comment]
Unfortunately without knowledge at least docker, it will be extremely difficult to run your own serverless function. I will recommend to follow the tutorial and tell me first line which isn't working for you.

**Comment by FarranYang** [comment]
> 不幸的是，至少在没有 docker 知识的情况下，运行自己的无服务器功能将非常困难。我会建议您遵循教程并告诉我第一行不适合您的行。

Thank you for your reply! I'm sorry that those few weeks I have less time to handle  this  problem, maybe later I will focus on this.

**Comment by MrHoang1999** [comment]
am trying to use auto annotation cvat for segmantic segmentation with my custom pytorch model . Can you help me ? Thanks.
