### ISSUE TITLE
Can t access to web service at MYIPCVATHOST:8080 but services are up

### ISSUE THREAD

**Issue by DavideCatto** [openvinotoolkit/cvat#3866]
### My actions before raising this issue
- I have read the documentation and followed all the installation steps
- I checked that the various containers are active and no errors are shown during installation
- I read all issues on this git, related to my problem
- CVAT_HOST environment is setted to MYIPCVATHOST before docker-compose command, also it s setted in docker-compose.yml 
- ALLOWED_HOSTS setted to "*"

### Expected Behaviour
- Log to MYIPCVATHOST:8080 and access to cvat service for annotate a dataset.

### Current Behaviour
When I launch the server and try to access (from a server in the same LAN) the "_MYIPCVATHOST:8080_" page, I get the "Bad gateway" error, but if I try to connect to the "_MYIPCVATHOST:8080/admin_" page, the server responds correctly and once logged in I can change the settings. Even if I access the "_api/v1_" I can view the api export. I cannot access the main page of the cvat service. If i access to "_MYIPCVATHOST:8090_" I can see the  traefik dashboard and all services up.

### Steps to Reproduce (for bugs)
just download last cvat release rep and launch _"docker-compose -f docker-compose.yml up -d --build"_

### Context
Some change are done in docker-compose.yaml following installation step

### Your Environment

- Cvat version 1.6.0
- Docker version 20.10.8 (WSL2)
- Traefik active for proxy web service
- Windows 10
- I m using Git Bash for build and launch docker

**Comment by azhavoro** [comment]
Hi, if MYIPCVATHOST != localhost you need to export `CVAT_HOST` environment variable before `docker-compose up` command: https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

**Comment by azhavoro** [comment]
BTW the installation guide has a note about this https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#use-your-own-domain

**Comment by DavideCatto** [comment]
> BTW the installation guide has a note about this https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#use-your-own-domain

@azhavoro ty for the fast reply, I have already done this but nothing has change. Always "Bad Gateway"

**Comment by StellaASchlotter** [comment]
What i experienced that i need to wait for minute after docker-compose up. Only then the routing works correctly.

**Comment by DavideCatto** [comment]
@StellaASchlotter yeah, it's 2/3 days that i try to connect to the service. If can help I post "docker ps"
`$ Docker `
`|CONTAINER ID |  IMAGE | COMMAND  |  CREATED  |  STATUS   |   PORTS     |   NAMES|`
`|800a53e01e87 |  openvino/cvat_ui    |   "/usr/bin/supervisord" |  19 hours ago | Up 19 hours |  8080/tcp     |                                            cvat_ui|`
`|39d2f89d47ca  | openvino/cvat_server |  "/usr/bin/supervisord" |  19 hours ago |  Up 19 hours  | 8080/tcp   |                                              cvat|`
`|56f584d7a076|   postgres:10-alpine |    "docker-entrypoint.s…"|   19 hours ago |  Up 19 hours  | 5432/tcp   |                                              cvat_db|`
`|98f9df6af2c4 |  redis:4.0-alpine      | "docker-entrypoint.s…"|   19 hours ago |  Up 19 hours  | 6379/tcp |                                                cvat_redis|`
`|b557c2ec40fb  | traefik:v2.4     |      "/entrypoint.sh --pr…"  | 19 hours ago |  Up 19 hours  | 0.0.0.0:8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp  | traefik|`
</code>

**Comment by azhavoro** [comment]
@DavideCatto What is output of `docker inspect -f '{{ index  .Config.Labels "traefik.http.routers.cvat.rule" }}' cvat`?

**Comment by DavideCatto** [comment]
@azhavoro Output is: 

> Host(`192.168.1.124`) && PathPrefix(`/api/`, `/git/`, `/opencv/`, `/analytics/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)

All routes don t work and "Bad gatway" is returned from the server except for "admin" route that works.

**Comment by azhavoro** [comment]
Are you using CVAT behind a reverse proxy?
Please add `--logLevel=DEBUG` for traefik service here https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.yml#L75 , restart containers and try to open CVAT urls. After that please attach log file `docker logs traefik > traefik.log`

**Comment by DavideCatto** [comment]
Theoretically not: I'm trying to access to the server located at ip 192.168.1.124 from a PC connected locally with ip 192.168.1.14 (ping ip works). 
I attach the file with the logs [traefik.log](https://github.com/openvinotoolkit/cvat/files/7503989/traefik.log).

**Comment by azhavoro** [comment]
```
traefik.http.routers.cvat-ui.rule:Host(`192.168.1.124`) traefik.http.services.cvat-ui.loadbalancer.server.port:8090]}
```
I believe smth wrong with your configuration, the default port which cvat_ui webserver is available is 80,

could you provide you compose configuration? just pass `config` option instead of `up -d` for your  `docker-compose` command that are you used.

**Comment by DavideCatto** [comment]
I change the port accordig to docker-compose.yml on the repository (using port 80) but same beahaviur: route admin works but others return "bad gateway". I attach the config file using the command (also docker-compose.yml) and traefik log.
config: [config.txt](https://github.com/openvinotoolkit/cvat/files/7504363/config.txt)
docker compose: [docker-compose.txt](https://github.com/openvinotoolkit/cvat/files/7504369/docker-compose.txt)
log traefik: [traefik.log](https://github.com/openvinotoolkit/cvat/files/7504373/traefik.log)

**Comment by azhavoro** [comment]
Your config contains a little unnecessary changes, but it works for me (just changed the IP), but I see something strange in your docker ps
`|800a53e01e87 | openvino/cvat_ui | "/usr/bin/supervisord" | 19 hours ago | Up 19 hours | 8080/tcp | cvat_ui|`
the entrypoint cannot be a valid for such image, as it's base on nginx, it should be smth like this:
```shell
▶ docker ps              
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS                                                                                          NAMES
b2ac9bc0cabe   openvino/cvat_ui       "/docker-entrypoint.…"   11 minutes ago   Up 11 minutes   80/tcp                                                                                         cvat_ui
```

So, please stop and delete all cvat containers, delete `cvat_ui` image, make sure that you have no `openvino/cvat_ui` local images and pull again by `docker-compose pull cvat_ui` or directly `docker pull openvino/cvat_ui`

**Comment by DavideCatto** [comment]
Great news! Now it's works!.. I think that there was an older version of "cvat_ui" because in past (1/2 years ago) I had used it.. For this reason it was using nginx. I have deleted all the containers and images and pulled like you said and now it's work! localhost no, but it s not a problem and i will check why in future if necessary. ty @azhavoro !!

I think that we can close this issue!

**Comment by nmanovic** [comment]
@DavideCatto , great to see that @azhavoro helped you to resolve issues. I will close the issue.
