### ISSUE TITLE
How do China users use docker

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/cvat#3868]
It's very troublesome for China users to build dockers

It is difficult to access foreign network environment

Building and buying VPN is an illegal and criminal act in China

Is there a better way ？

**Comment by StellaASchlotter** [comment]
Is this problem only with images from https://hub.docker.com/? There are other registries like https://quay.io/. There might be some registries that are allowed in china. Can you find out which registries that are?

What would be possible is to also publish the images to other registries.

**Comment by monkeycc** [comment]
CVAT Docke

Docker container：

Dockerfile   Cannot access
apt install   Cannot access
pip install     Cannot access
npm install  Cannot access
git clone  Cannot access

Unable to access or download very slow

It is recommended that the cvat container speed up the image configuration file for easy modification

CVAT  Docker installation is too painful

**Comment by nmanovic** [comment]
@monkeycc , could you please propose a way? I was one time in China. It was a big issue for me to work behind GFC. How do other software products solve the problem? If you have a couple of examples which work for you well, it will help. If somebody can help us to build a reliable solution for users in China, it will be awesome.

**Comment by monkeycc** [comment]
My suggestion

----------------------------------
#  Replace cvat dock acceleration source
```
# https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/
# apt update 
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-backports main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-security main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-security main restricted universe multiverse
```

```
# https://www.daocloud.io/mirror
# Docker mirror station

daemon.json
{
    "registry-mirrors": [
        "http://f1361db2.m.daocloud.io",
        "https://docker.mirrors.ustc.edu.cn",
        "https://hub-mirror.c.163.com",
        "https://https://mirror.ccs.tencentyun.com",
        "https://mirror.ccs.tencentyun.com",
    ]
}
```

```
# https://mirrors.tuna.tsinghua.edu.cn/help/pypi/
# pip
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

```
# https://npmmirror.com/
# npm 
npm config set registry https://registry.npm.taobao.org/
```

```
# https://gitee.com/
# git 
# https://gitee.com/monkeycc/cvat
```

```
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \

# docker.com Replace acceleration source
```

```
curl https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
# google.com Replace acceleration source

```

@nmanovic

**Comment by nmanovic** [comment]
@monkeycc , thanks for the information. First step is to have all these information as a section inside installation guide. Second step is to have customized Dockerfiles to simplify live of Chinese users.

@azhavoro , @TOsmanov , could you please work together to prepare corresponding documentation? Could we create Dockerfile.ch or something like that?
