### ISSUE TITLE
See the actual pixels when zooming

### ISSUE THREAD

**Issue by AmitN1212** [openvinotoolkit/cvat#3870]
Hi, I would like to see the actual pixels when I zoom in an image. I searched for it in the issues, and found exactly what I am asking for [here](https://github.com/openvinotoolkit/cvat/issues/2023), But I didn't understand what I should do. I tried to upload the task and set the quality to 100%, but I didn't get what I wanted. I tried to increase the maximum zoom in the code - 
it worked and I could have a bigger zoom, but I still didn't see the actual pixels.

What can I do?

Sorry if there is something that I missed.

Thank you.

**Comment by nmanovic** [comment]
@AmitN1212 , I will close the issue as duplicate. We just need to implement the future. We have original images on the server. It should not be a big deal to show them. But it isn't supported at the moment.

**Comment by AmitN1212** [comment]
Thanks for the answer. I think that the problem is not with the upload quality, but with another function that smooths the image when you zoom in, so maybe show the original images won't be enough. What do you think?

**Comment by nmanovic** [comment]
@AmitN1212 , I will eat the elephant step by step. The most obvious problem is CVAT cannot show original images at the moment. To zoom in/out we rely on functions implement in browsers (like style transform property).

**Comment by AmitN1212** [comment]
Thanks for the answers. I found a solution (for seeing the pixels when zooming in, not for seeing the original image).

In cvat-canvas/src/scss/canvas.scss, [line 261](#cvat_canvas_background {), add these lines inside the #cvat_canvas_background section:
```
    image-rendering:pixelated;
    -ms-interpolation-mode:nearest-neighbor;
```

It gave me exactly what I wanted. Thank you very much for the help!
