### ISSUE TITLE
additional components in dev env

### ISSUE THREAD

**Issue by AmitN1212** [openvinotoolkit/cvat#3874]
Hi, I wanted to know if there's any way to setup a sharepath and the analytics component in the dev environment? The ways provided [here](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#share-path) and [here](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/analytics/) should work with the regular installation only. 
Thanks.

**Comment by azhavoro** [comment]
Hi,
CVAT uses `cvat_root/share` folder as a fileshare, just mount to this point any resource you want
Regarding Analytics I would to suggest run analytics containers (ELK) as usually but you need to forward port for logstash service definition here https://github.com/openvinotoolkit/cvat/blob/develop/components/analytics/docker-compose.analytics.yml#L57

**Comment by AmitN1212** [comment]
Thanks for the answer. I didn't understand what I should do with the logstash service. Can you explain it again please?

**Comment by nmanovic** [comment]
@AmitN1212 , for analytics, nuclio you need docker containers. We don't develop these components. I will close the discussion. Don't hesitate to ask our community on gitter if you have more questions.
