### ISSUE TITLE
{"error":"Not found"}  at https://registry.npmjs.org/cvat-data

### ISSUE THREAD

**Issue by vikram1995** [openvinotoolkit/cvat#3876]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

getting error while building CVAT files as the response of   [https://registry.npmjs.org/cvat-data](https://registry.npmjs.org/cvat-data) is {"error":"Not found"}

version used : v1.6.0 master branch

Step 17/33 : RUN npm ci
 ---> Running in 4d991272e09c
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN old lockfile HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/cvat-data - Not found
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm WARN old lockfile     at runMicrotasks (<anonymous>)
npm WARN old lockfile     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9)
npm WARN old lockfile  Could not fetch metadata for cvat-data@1.0.2 HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/cvat-data - Not found
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm WARN old lockfile     at runMicrotasks (<anonymous>)
npm WARN old lockfile     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9) {
npm WARN old lockfile   headers: [Object: null prototype] {
npm WARN old lockfile     date: [ 'Mon, 08 Nov 2021 04:58:08 GMT' ],
npm WARN old lockfile     'content-type': [ 'application/json' ],
npm WARN old lockfile     'content-length': [ '21' ],
npm WARN old lockfile     connection: [ 'keep-alive' ],
npm WARN old lockfile     'cf-ray': [ '6aac39717dac1b64-DEL' ],
npm WARN old lockfile     vary: [ 'Accept-Encoding' ],
npm WARN old lockfile     'expect-ct': [
npm WARN old lockfile       'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"'
npm WARN old lockfile     ],
npm WARN old lockfile     server: [ 'cloudflare' ],
npm WARN old lockfile     'x-fetch-attempts': [ '1' ],
npm WARN old lockfile     'x-local-cache-status': [ 'skip' ]
npm WARN old lockfile   },
npm WARN old lockfile   statusCode: 404,
npm WARN old lockfile   code: 'E404',
npm WARN old lockfile   method: 'GET',
npm WARN old lockfile   uri: 'https://registry.npmjs.org/cvat-data',
npm WARN old lockfile   body: { error: 'Not found' },
npm WARN old lockfile   pkgid: 'cvat-data@1.0.2'

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@ActiveChooN , @azhavoro ,

Could you please comment?

**Comment by bsekachev** [comment]
Hi @vikram1995

Sorry for delay. Please, try 1.7 release.

**Comment by nmanovic** [comment]
@vikram1995 , I will close the issue. If the problem exists, don't hesitate to reopen.
