### ISSUE TITLE
Jobs frame is mismatch with upload order of image task

### ISSUE THREAD

**Issue by krismp** [openvinotoolkit/cvat#3877]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

How to use task annotation CVAT REST API correctly? I find it difficult to match the image frame with the annotation I try to send via REST API

<img width="1405" alt="Screen Shot 2021-11-08 at 11 31 47" src="https://user-images.githubusercontent.com/6040035/140684671-ac6784d3-62df-4a9f-a507-7e2786bdb9ab.png">

In the documentation, I should provide the `frame` attribute in order to match the annotation to the frame we uploaded before using the upload image to task API: 

<img width="638" alt="Screen Shot 2021-11-08 at 11 32 52" src="https://user-images.githubusercontent.com/6040035/140684739-f22c95f2-de61-4b45-8d82-7d6240232954.png">

but I have tried its value is not the same as the order of array index when we upload the image to task, for example when using `remote_files`, the order is:

```json
{
    "image_quality": 70,
    "remote_files": [
        "/path/to/image/pic_1.jpeg",
        "/path/to/image/pic_2.jpeg",
        "/path/to/image/pic_3.jpeg"
    ]
}
```

But after it became `jobs`, the image `frame` is not the same, which makes it difficult to use annotation API, because the result will always be mismatched.

### Expected Behaviour

I think it will be easier to make the order of the frame the same as the image array index when we upload the image to the task? But I'm to any suggestion

### Current Behaviour

The frame is not the same as the array index, result in the annotation is always mismatched

### Steps to Reproduce (for bugs)

1. Create a task (via API or UI is fine)
2. Upload an image to the task using the below API:

<img width="638" alt="Screen Shot 2021-11-08 at 11 32 52" src="https://user-images.githubusercontent.com/6040035/140684739-f22c95f2-de61-4b45-8d82-7d6240232954.png">

3. Annotate via task annotation rest API below:

<img width="1405" alt="Screen Shot 2021-11-08 at 11 31 47" src="https://user-images.githubusercontent.com/6040035/140684671-ac6784d3-62df-4a9f-a507-7e2786bdb9ab.png">

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Deployed on VM
- Operating System and version (e.g. Linux, Windows, MacOS): Linux, MacOS

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@krismp , frames are sorted in lexicographical order at the moment. Probably we can preserve order.
