### ISSUE TITLE
deploy auto annotations ERROR

### ISSUE THREAD

**Issue by yearlz** [openvinotoolkit/cvat#3878]
when i try to deploy the  auto annotate model as follow:
[https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/](url)

nuctl deploy --project-name cvat \
  --path serverless/openvino/dextr/nuclio \
  --volume `pwd`/serverless/common:/opt/nuclio/common \
  --platform local

it went wrong as:

#6 [ 3/11] RUN ln -s /usr/bin/pip3 /usr/bin/pip
#6 sha256:c91ba0fbe021ac7518b6f41da248ace229c281b39de3aadb7abb9393fcf313ac
#6 CACHED

#11 [ 7/11] COPY handler /opt/nuclio
#11 sha256:3951fc6ebab233abd5ed1c5ee3fc11878378490278ad13bb0145f87f6e9fb982
#11 CACHED

#12 [ 8/11] RUN curl -O https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip
#12 sha256:8f7587a40f242cc0a9d08918c47fc331ef1e1f6d7729582ee861f0a2633c3882
#12 0.093 + curl -O https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip
#12 0.098   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#12 0.098                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#12 0.838 curl: (60) SSL certificate problem: unable to get local issuer certificate
#12 0.838 More details here: https://curl.haxx.se/docs/sslcerts.html
#12 0.838
#12 0.838 curl failed to verify the legitimacy of the server and therefore could not
#12 0.838 establish a secure connection to it. To learn more about this situation and
#12 0.838 how to fix it, please visit the web page mentioned above.
#12 ERROR: executor failed running [/bin/bash -xo pipefail -c curl -O https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip]: exit code: 60
------
 > [ 8/11] RUN curl -O https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip:
------
executor failed running [/bin/bash -xo pipefail -c curl -O https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip]: exit code: 60

    /nuclio/pkg/cmdrunner/shellrunner.go:96
Failed to build
    /nuclio/pkg/dockerclient/shell.go:118
Failed to build docker image
    .../pkg/containerimagebuilderpusher/docker.go:53
Failed to build processor image
    /nuclio/pkg/processor/build/builder.go:250
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:182

it seems to be the net problem ,  it happened no matter i used the vpn or not,
any ideas to solve it ?

**Comment by nmanovic** [comment]
@yearlz , could you please one more time? I have no problems now to download https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip. I hope it was temporary problems with the download.01.org server.

**Comment by nmanovic** [comment]
@yearlz , I will close the issue. Don't hesitate to reopen, if you still have the problem.

**Comment by giordifungula** [comment]
@nmanovic  Hey, 2 questions
-  im trying to setup the auto annotate feature on a linux 18.04 ec2 instance.
Im having issues finding good documentation to install the Nvidea, do you have perhaps a reference or guide to set this up?
- I am having issues installing the 2nd model in the documentation, see the command below
 ``` nuctl deploy --project-name cvat \
  --path serverless/openvino/omz/public/yolo-v3-tf/nuclio \
  --volume `pwd`/serverless/common:/opt/nuclio/common \
  --platform local ```
- See the screenshot of the error below, do you maybe know what todo in this case, as the docs don't cover any thing going wrong at this point
![Screenshot 2021-12-03 at 18 07 10](https://user-images.githubusercontent.com/27930281/144634623-383309e9-0eba-45e8-9abb-bb4c66b6c8d9.png)
.

**Comment by A-Zenith** [comment]
@yearlz I am facing the same problem as you did. I am able to download https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip dirctly without docker. I guess it is due to docker? How did you solve the problem? Thanks in advance!
