### ISSUE TITLE
Boxes on non-key frames exported with incorrect coordinates

### ISSUE THREAD

**Issue by manybodycpa** [openvinotoolkit/cvat#3879]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When exporting annotations in CVAT video format, bounding boxes that are not marked as "key frame" are sometimes exported with incorrect coordinates (namely, the same coordinates as on the last key frame). The GUI shows these boxes correctly, with interpolated coordinates matching the object to be annotated.

Example:

```
<box frame="10" outside="0" occluded="0" keyframe="1" xtl="498.90" ytl="269.80" xbr="531.60" ybr="282.23" z_order="0">
<attribute name="check">false</attribute>
</box>
<box frame="11" outside="0" occluded="0" keyframe="0" xtl="498.90" ytl="269.80" xbr="531.60" ybr="282.23" z_order="0">
<attribute name="check">false</attribute>
</box>
<box frame="12" outside="1" occluded="0" keyframe="1" xtl="486.82" ytl="273.12" xbr="521.20" ybr="285.27" z_order="0">
<attribute name="partial">undefined</attribute>
```

The box on frame 11 is shown at an interpolated position in CVAT but exported with the coordinates of frame 10.

### Steps to Reproduce (for bugs)

* Annotate tracks with a mixture of key and non-key frames
* Export in CVAT Video XML format (either via dump menu or via API download)

### Context

The issue causes annotations to be incorrect when used outside CVAT. Even more problematic, the problem is not visible to annotators.

For the example given, the problem is absent in CVAT 1.6 (8d03ed7959632d6f3ffd76020ad577fa409acfcd). 

I have more than a thousand videos on two different instances (CVAT 1.2 and 1.4) that are potentially affected. Transferring these videos is not a very attractive option. Instead, a patch would be the much preferred solution.

### Your Environment

- Git hash commit (`git log -1`): 315c9cc8d2b1c8fbd3b6b5e6ab6fca3a792bc895
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.12
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu

**Comment by kirill-sizov** [comment]
Hi, @manybodycpa, it's seems that we already fixed this problem in [this PR](https://github.com/openvinotoolkit/cvat/pull/3348), could you please update your CVAT version to `1.5.0` or greater, after that try to export your annotation again.

 Also, please give feedback, if this solved your problem or not

**Comment by manybodycpa** [comment]
@kirill-sizov Thank you very much. 

Since I'm under the impression that upgrading can be problematic over several versions (1.2 to 1.5), can I just apply the changes from the PR by hand?

**Comment by kirill-sizov** [comment]
@manybodycpa, I think you can try to run this:
```bash
git fetch; git cherry-pick 47ea751 -X theirs
```

**Comment by kirill-sizov** [comment]
Hi, @manybodycpa, did [it](https://github.com/openvinotoolkit/cvat/issues/3879#issuecomment-966265127) solve your problem or not?

**Comment by manybodycpa** [comment]
@kirill-sizov Thanks for your help. Not entirely, that's why I had not commented yet.

The patch itself is the solution I'm looking for and works nicely on 1.4 (but see below). However, I have a production server that runs 1.2 for which applying the patch raises two new issues:

1. There is no docker-compose.dev.yml; how do I rebuild the containers? Copy the yml file from 1.4?

2. Even for 1.4, I ran into another issue, see https://github.com/openvinotoolkit/cvat/issues/3853. Applying all available updates using git pull, I was able to update. However, I'm hesitant to do the same for 1.2 since that would amount to a huge version jump. Any advice would be appreciated.

**Comment by manybodycpa** [comment]
Considering that these issues are not related to the problem of bounding boxes, I think the current issue can be closed.

**Comment by varungupta31** [comment]
Hey @kirill-sizov @manybodycpa 
I'm using 
```
Server version: 1.6
Core version: 3.16.0
Canvas version: 2.7.0
UI version: 1.23.1
```

But still facing the same issue. When I upload on CVAT for video format, non-key frames, even though having correct `xtl,ytl,xbr` and `ybr` params, are not rendering correctly.

Any help?

**Comment by nmanovic** [comment]
@varungupta31 , please create a separate issue. We need a way to reproduce the issue on our end. Could you please share the exact steps? Otherwise it is really difficult to debug and fix.
