### ISSUE TITLE
Could not listen on public domain name - web page always show: 404 page not found

### ISSUE THREAD

**Issue by shaojun** [openvinotoolkit/cvat#3906]
just hours ago, I followed the doc on [section](https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port) to add the `CVAT_HOST` to my public domain name(for security reason, i replaced the real domain to **MY.HOSTNAME.com**) with: `export CVAT_HOST=MY.HOSTNAME.com`, and then `~/cvat/sudo docker-compse up -d`, all works fine, I can access the web from public internet by typing `MY.HOSTNAME.com:8080` in browser.

but somehow later, after I played with the port number changing(no luck yet though followed the doc by changing a bit in `traefik` section in `src\docker-compose.yml` : `--entryPoints.web.address=:8080`) and some docker-compose up and down, then web cannot open anymore from public internet by `MY.HOSTNAME.com:8080`, so I delete all docker images and source, and re-clone repo and re-download docker images again from scratch, now the local host accessing is OK, but, still can not get the web page open again from public domain name, for debug, I used `sudo docker-compose up` to get more output, you can see the `CVAT_HOST` is already properly set:

> aaaa@iZuf6931owccge6i2dgt2bZ:/cvat$ **printenv CVAT_HOST
MY.HOSTNAME.com**
aaaa@iZuf6931owccge6i2dgt2bZ:/cvat$ sudo docker-compose up
Creating network "cvat_cvat" with the default driver
Creating cvat_db    ... done
Creating cvat_redis ... done
Creating traefik    ... done
Creating cvat       ... done
Creating cvat_ui    ... done
Attaching to traefik, cvat_redis, cvat_db, cvat, cvat_ui
cvat_db       |
cvat_db       | PostgreSQL Database directory appears to contain a database; Skipping initialization
cvat_db       |
cvat_db       | 2021-11-12 06:58:22.844 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
cvat_db       | 2021-11-12 06:58:22.844 UTC [1] LOG:  listening on IPv6 address "::", port 5432
cvat_db       | 2021-11-12 06:58:22.850 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
cvat          | 2021-11-12 06:58:23,273 INFO RPC interface 'supervisor' initialized
cvat          | 2021-11-12 06:58:23,273 CRIT Server 'unix_http_server' running without any HTTP authentication checking
cvat_db       | 2021-11-12 06:58:22.865 UTC [21] LOG:  database system was shut down at 2021-11-12 06:57:04 UTC
cvat_db       | 2021-11-12 06:58:22.868 UTC [1] LOG:  database system is ready to accept connections
cvat_redis    | 1:C 12 Nov 06:58:22.807 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cvat_redis    | 1:C 12 Nov 06:58:22.807 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
cvat_redis    | 1:C 12 Nov 06:58:22.807 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cvat_redis    | 1:M 12 Nov 06:58:22.810 * Running mode=standalone, port=6379.
cvat_redis    | 1:M 12 Nov 06:58:22.810 # Server initialized
cvat_redis    | 1:M 12 Nov 06:58:22.810 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cvat          | 2021-11-12 06:58:23,273 INFO supervisord started with pid 1
cvat_redis    | 1:M 12 Nov 06:58:22.810 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
cvat_redis    | 1:M 12 Nov 06:58:22.810 * Ready to accept connections
cvat_ui       | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
cvat_ui       | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
cvat_ui       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
cvat_ui       | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
traefik       | time="2021-11-12T06:58:22Z" level=info msg="Configuration loaded from flags."
cvat_ui       | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
cvat_ui       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
cvat_ui       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
cvat_ui       | /docker-entrypoint.sh: Configuration complete; ready for start up
cvat_ui       | 2021/11/12 06:58:23 [warn] 1#1: duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/mime.types:98
cvat_ui       | nginx: [warn] duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/mime.types:98
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: using the "epoll" event method
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: nginx/1.21.3
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424)
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: OS: Linux 5.4.0-75-generic
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: start worker processes
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: start worker process 33
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: start worker process 34
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: start worker process 35
cvat_ui       | 2021/11/12 06:58:23 [notice] 1#1: start worker process 36
cvat          | 2021-11-12 06:58:24,275 INFO spawned: 'ssh-agent' with pid 8
cvat          | 2021-11-12 06:58:24,277 INFO spawned: 'clamav_update' with pid 9
cvat          | 2021-11-12 06:58:24,278 INFO spawned: 'git_status_updater' with pid 10
cvat          | 2021-11-12 06:58:24,280 INFO spawned: 'rqscheduler' with pid 11
cvat          | 2021-11-12 06:58:24,281 INFO spawned: 'rqworker_default_0' with pid 13
cvat          | 2021-11-12 06:58:24,283 INFO spawned: 'rqworker_default_1' with pid 14
cvat          | 2021-11-12 06:58:24,285 INFO spawned: 'rqworker_low' with pid 15
cvat          | 2021-11-12 06:58:24,287 INFO spawned: 'runserver' with pid 18
cvat          | 2021-11-12 06:58:24,287 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140674653466144 for <Subprocess at 140674653465472 with name clamav_update in state STARTING> (stdout)>
cvat          | 2021-11-12 06:58:24,288 DEBG fd 14 closed, stopped monitoring <POutputDispatcher at 140674653231616 for <Subprocess at 140674653465472 with name clamav_update in state STARTING> (stderr)>
cvat          | 2021-11-12 06:58:24,288 INFO exited: clamav_update (exit status 0; not expected)
cvat          | 2021-11-12 06:58:24,289 DEBG received SIGCHLD indicating a child quit
cvat          | 2021-11-12 06:58:24,289 DEBG 'ssh-agent' stdout output:
cvat          | SSH_AUTH_SOCK=/tmp/ssh-agent.sock; export SSH_AUTH_SOCK;
cvat          | echo Agent pid 8;
cvat          |
cvat          | 2021-11-12 06:58:24,290 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 3 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,293 DEBG 'git_status_updater' stderr output:
cvat          | wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
cvat          |
cvat          | 2021-11-12 06:58:24,294 DEBG 'rqscheduler' stderr output:
cvat          | wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
cvat          |
cvat          | 2021-11-12 06:58:24,298 DEBG 'rqworker_default_1' stderr output:
cvat          | wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
cvat          |
cvat          | 2021-11-12 06:58:24,298 DEBG 'rqworker_low' stderr output:
cvat          | wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
cvat          |
cvat          | 2021-11-12 06:58:24,299 DEBG 'rqscheduler' stderr output:
cvat          | wait-for-it.sh: cvat_redis:6379 is available after 0 seconds
cvat          |
cvat          | 2021-11-12 06:58:24,300 DEBG 'git_status_updater' stderr output:
cvat          | wait-for-it.sh: cvat_redis:6379 is available after 0 seconds
cvat          |
cvat          | 2021-11-12 06:58:24,301 DEBG 'git_status_updater' stderr output:
cvat          | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
cvat          | bash: no job control in this shell
cvat          |
cvat          | 2021-11-12 06:58:24,301 DEBG 'rqscheduler' stderr output:
cvat          | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
cvat          | bash: no job control in this shell
cvat          |
cvat          | 2021-11-12 06:58:24,303 DEBG 'rqworker_default_0' stderr output:
cvat          | wait-for-it.sh: waiting for cvat_redis:6379 without a timeout
cvat          |
cvat          | 2021-11-12 06:58:24,305 DEBG 'runserver' stderr output:
cvat          | wait-for-it.sh: waiting for cvat_db:5432 without a timeout
cvat          |
cvat          | 2021-11-12 06:58:24,305 DEBG 'rqworker_low' stderr output:
cvat          | wait-for-it.sh: cvat_redis:6379 is available after 0 seconds
cvat          |
cvat          | 2021-11-12 06:58:24,306 DEBG 'rqworker_low' stderr output:
cvat          | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
cvat          | bash: no job control in this shell
cvat          |
cvat          | 2021-11-12 06:58:24,308 DEBG 'rqworker_default_1' stderr output:
cvat          | wait-for-it.sh: cvat_redis:6379 is available after 0 seconds
cvat          |
cvat_db       | 2021-11-12 06:58:24.309 UTC [28] LOG:  incomplete startup packet
cvat          | 2021-11-12 06:58:24,310 DEBG 'rqworker_default_1' stderr output:
cvat          | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
cvat          | bash: no job control in this shell
cvat          |
cvat          | 2021-11-12 06:58:24,311 DEBG 'rqworker_default_0' stderr output:
cvat          | wait-for-it.sh: cvat_redis:6379 is available after 0 seconds
cvat          |
cvat          | 2021-11-12 06:58:24,313 DEBG 'rqworker_default_0' stderr output:
cvat          | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
cvat          | bash: no job control in this shell
cvat          |
cvat          | 2021-11-12 06:58:24,315 DEBG 'runserver' stderr output:
cvat          | wait-for-it.sh: cvat_db:5432 is available after 0 seconds
cvat          |
cvat          | 2021-11-12 06:58:24,316 DEBG 'runserver' stderr output:
cvat          | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
cvat          | bash: no job control in this shell
cvat          |
cvat          | 2021-11-12 06:58:24,405 DEBG 'rqscheduler' stderr output:
cvat          | 06:58:24 Registering birth
cvat          |
cvat          | 2021-11-12 06:58:24,427 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,432 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,433 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          |
cvat          | 2021-11-12 06:58:24,437 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,440 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          |
cvat          | 2021-11-12 06:58:24,442 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:SOANhjL2M4rxL7qMcUZ2qw9OJm2Y8/uXEFXNNQyPd50 "django@372d668cb3f6" (life: 0) (confirm: 0) (provider: none)
cvat          |
cvat          | 2021-11-12 06:58:24,443 DEBG 'rqworker_low' stderr output:
cvat          | Identity added: /home/django/.ssh/id_rsa (django@372d668cb3f6)
cvat          |
cvat          | 2021-11-12 06:58:24,470 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,472 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          |
cvat          | 2021-11-12 06:58:24,474 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:SOANhjL2M4rxL7qMcUZ2qw9OJm2Y8/uXEFXNNQyPd50 "django@372d668cb3f6" (life: 0) (confirm: 0) (provider: none)
cvat          |
cvat          | 2021-11-12 06:58:24,478 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          |
cvat          | 2021-11-12 06:58:24,485 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,489 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:SOANhjL2M4rxL7qMcUZ2qw9OJm2Y8/uXEFXNNQyPd50 "django@372d668cb3f6" (life: 0) (confirm: 0) (provider: none)
cvat          |
cvat          | 2021-11-12 06:58:24,493 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,493 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          |
cvat          | 2021-11-12 06:58:24,501 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,503 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          |
cvat          | 2021-11-12 06:58:24,505 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:SOANhjL2M4rxL7qMcUZ2qw9OJm2Y8/uXEFXNNQyPd50 "django@372d668cb3f6" (life: 0) (confirm: 0) (provider: none)
cvat          |
cvat          | 2021-11-12 06:58:24,508 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,509 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          |
cvat          | 2021-11-12 06:58:24,517 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:24,541 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:SOANhjL2M4rxL7qMcUZ2qw9OJm2Y8/uXEFXNNQyPd50 "django@372d668cb3f6" (life: 0) (confirm: 0) (provider: none)
cvat          |
cvat          | 2021-11-12 06:58:24,560 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          |
cvat          | 2021-11-12 06:58:25,562 INFO success: ssh-agent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2021-11-12 06:58:25,564 INFO spawned: 'clamav_update' with pid 104
cvat          | 2021-11-12 06:58:25,564 INFO success: git_status_updater entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2021-11-12 06:58:25,565 INFO success: rqscheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2021-11-12 06:58:25,565 INFO success: rqworker_default_0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2021-11-12 06:58:25,565 INFO success: rqworker_default_1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2021-11-12 06:58:25,566 INFO success: rqworker_low entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2021-11-12 06:58:25,566 INFO success: runserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2021-11-12 06:58:25,579 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140674653231760 for <Subprocess at 140674653465472 with name clamav_update in state STARTING> (stdout)>
cvat          | 2021-11-12 06:58:25,580 DEBG fd 16 closed, stopped monitoring <POutputDispatcher at 140674653231568 for <Subprocess at 140674653465472 with name clamav_update in state STARTING> (stderr)>
cvat          | 2021-11-12 06:58:25,580 INFO exited: clamav_update (exit status 0; not expected)
cvat          | 2021-11-12 06:58:25,581 DEBG received SIGCHLD indicating a child quit
cvat          | 2021-11-12 06:58:27,584 INFO spawned: 'clamav_update' with pid 147
cvat          | 2021-11-12 06:58:27,605 DEBG fd 16 closed, stopped monitoring <POutputDispatcher at 140674653231712 for <Subprocess at 140674653465472 with name clamav_update in state STARTING> (stderr)>
cvat          | 2021-11-12 06:58:27,607 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140674653466144 for <Subprocess at 140674653465472 with name clamav_update in state STARTING> (stdout)>
cvat          | 2021-11-12 06:58:28,609 INFO success: clamav_update entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2021-11-12 06:58:28,610 INFO exited: clamav_update (exit status 0; expected)
cvat          | 2021-11-12 06:58:28,611 DEBG received SIGCHLD indicating a child quit
cvat          | 2021-11-12 06:58:32,452 DEBG 'rqworker_low' stderr output:
cvat          | System check identified some issues:
cvat          |
cvat          | WARNINGS:
cvat          | ?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace
cvat          | DEBUG - 2021-11-12 06:58:32,451 - worker - Registering birth of worker 787e37781dcd426cb053c6ca23ed2ba1
cvat          |
cvat          | 2021-11-12 06:58:32,454 DEBG 'rqworker_low' stderr output:
cvat          | INFO - 2021-11-12 06:58:32,454 - worker - Worker rq:worker:787e37781dcd426cb053c6ca23ed2ba1: started, version 1.5.1
cvat          |
cvat          | 2021-11-12 06:58:32,454 DEBG 'rqworker_low' stderr output:
cvat          | INFO - 2021-11-12 06:58:32,454 - worker - *** Listening on low...
cvat          |
cvat          | 2021-11-12 06:58:32,455 DEBG 'rqworker_low' stderr output:
cvat          | DEBUG - 2021-11-12 06:58:32,455 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          |
cvat          | 2021-11-12 06:58:32,456 DEBG 'rqworker_low' stderr output:
cvat          | INFO - 2021-11-12 06:58:32,456 - worker - Cleaning registries for queue: low
cvat          |
cvat          | 2021-11-12 06:58:32,457 DEBG 'rqworker_low' stderr output:
cvat          | DEBUG - 2021-11-12 06:58:32,457 - worker - *** Listening on low...
cvat          |
cvat          | 2021-11-12 06:58:32,457 DEBG 'rqworker_low' stderr output:
cvat          | DEBUG - 2021-11-12 06:58:32,457 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          |
cvat          | 2021-11-12 06:58:32,566 DEBG 'rqworker_default_1' stderr output:
cvat          | System check identified some issues:
cvat          |
cvat          | WARNINGS:
cvat          | ?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace
cvat          | DEBUG - 2021-11-12 06:58:32,566 - worker - Registering birth of worker beb2c05525614267a308eb67d031021b
cvat          |
cvat          | 2021-11-12 06:58:32,568 DEBG 'rqworker_default_1' stderr output:
cvat          | INFO - 2021-11-12 06:58:32,568 - worker - Worker rq:worker:beb2c05525614267a308eb67d031021b: started, version 1.5.1
cvat          |
cvat          | 2021-11-12 06:58:32,569 DEBG 'rqworker_default_1' stderr output:
cvat          | INFO - 2021-11-12 06:58:32,568 - worker - *** Listening on default...
cvat          | DEBUG - 2021-11-12 06:58:32,569 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          |
cvat          | 2021-11-12 06:58:32,570 DEBG 'rqworker_default_1' stderr output:
cvat          | INFO - 2021-11-12 06:58:32,569 - worker - Cleaning registries for queue: default
cvat          |
cvat          | 2021-11-12 06:58:32,571 DEBG 'rqworker_default_1' stderr output:
cvat          | DEBUG - 2021-11-12 06:58:32,570 - worker - *** Listening on default...
cvat          |
cvat          | 2021-11-12 06:58:32,571 DEBG 'rqworker_default_1' stderr output:
cvat          | DEBUG - 2021-11-12 06:58:32,571 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          |
cvat          | 2021-11-12 06:58:32,608 DEBG 'rqworker_default_0' stderr output:
cvat          | System check identified some issues:
cvat          |
cvat          | WARNINGS:
cvat          | ?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace
cvat          | DEBUG - 2021-11-12 06:58:32,608 - worker - Registering birth of worker 5a505b6d48b8492e9cf5cf6b5cc4d76b
cvat          |
cvat          | 2021-11-12 06:58:32,610 DEBG 'rqworker_default_0' stderr output:
cvat          | INFO - 2021-11-12 06:58:32,610 - worker - Worker rq:worker:5a505b6d48b8492e9cf5cf6b5cc4d76b: started, version 1.5.1
cvat          |
cvat          | 2021-11-12 06:58:32,610 DEBG 'rqworker_default_0' stderr output:
cvat          | INFO - 2021-11-12 06:58:32,610 - worker - *** Listening on default...
cvat          |
cvat          | 2021-11-12 06:58:32,610 DEBG 'rqworker_default_0' stderr output:
cvat          | DEBUG - 2021-11-12 06:58:32,610 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          |
cvat          | 2021-11-12 06:58:32,611 DEBG 'rqworker_default_0' stderr output:
cvat          | DEBUG - 2021-11-12 06:58:32,611 - worker - *** Listening on default...
cvat          |
cvat          | 2021-11-12 06:58:32,611 DEBG 'rqworker_default_0' stderr output:
cvat          | DEBUG - 2021-11-12 06:58:32,611 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat          |
cvat          | 2021-11-12 06:58:32,714 DEBG 'runserver' stderr output:
cvat          | System check identified some issues:
cvat          |
cvat          | WARNINGS:
cvat          | ?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace
cvat          |
cvat          | 2021-11-12 06:58:32,714 DEBG 'runserver' stdout output:
cvat          | Operations to perform:
cvat          |   Apply all migrations: account, admin, auth, authtoken, contenttypes, dataset_repo, engine, sessions, sites, socialaccount
cvat          | Running migrations:
cvat          |   No migrations to apply.
cvat          |
cvat          | 2021-11-12 06:58:33,196 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:33,197 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          |
cvat          | 2021-11-12 06:58:33,198 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:SOANhjL2M4rxL7qMcUZ2qw9OJm2Y8/uXEFXNNQyPd50 "django@372d668cb3f6" (life: 0) (confirm: 0) (provider: none)
cvat          |
cvat          | 2021-11-12 06:58:33,201 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          |
cvat          | 2021-11-12 06:58:33,621 DEBG 'runserver' stdout output:
cvat          |
cvat          | 0 static files copied to '/home/django/static', 182 unmodified.
cvat          |
cvat          | 2021-11-12 06:58:33,751 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:33,752 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          |
cvat          | 2021-11-12 06:58:33,753 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:SOANhjL2M4rxL7qMcUZ2qw9OJm2Y8/uXEFXNNQyPd50 "django@372d668cb3f6" (life: 0) (confirm: 0) (provider: none)
cvat          |
cvat          | 2021-11-12 06:58:33,756 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          |
cvat_ui       | 172.27.0.3 - - [12/Nov/2021:06:58:36 +0000] "GET / HTTP/1.1" 200 1045 "-" "Wget/1.20.3 (linux-gnu)" "172.27.0.1"
cvat          | 2021-11-12 06:58:37,541 DEBG 'runserver' stderr output:
cvat          | System check identified some issues:
cvat          |
cvat          | WARNINGS:
cvat          | ?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace
cvat          |
cvat          | 2021-11-12 06:58:37,541 DEBG 'runserver' stdout output:
cvat          | Successfully ran command.
cvat          |
cvat          | 2021-11-12 06:58:37,544 DEBG 'runserver' stdout output:
cvat          | Server URL         : http://localhost:8080/
cvat          | Server Root        : /tmp/cvat-server
cvat          | Server Conf        : /tmp/cvat-server/httpd.conf
cvat          | Error Log File     : /dev/stderr (INFO)
cvat          | Request Capacity   : 5 (1 process * 5 threads)
cvat          | Request Timeout    : 60 (seconds)
cvat          | Startup Timeout    : 15 (seconds)
cvat          | Queue Backlog      : 100 (connections)
cvat          | Queue Timeout      : 45 (seconds)
cvat          | Server Capacity    : 20 (event/worker), 20 (prefork)
cvat          | Server Backlog     : 500 (connections)
cvat          | Locale Setting     : C.UTF-8
cvat          |
cvat          | 2021-11-12 06:58:37,576 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 12 06:58:37.576422 2021] [wsgi:info] [pid 230:tid 139715544292416] mod_wsgi (pid=230): Starting process 'localhost:8080' with threads=5.
cvat          |
cvat          | 2021-11-12 06:58:37,576 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 12 06:58:37.576520 2021] [mpm_event:notice] [pid 18:tid 139715544292416] AH00489: Apache/2.4.41 (Ubuntu) mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations
cvat          | [Fri Nov 12 06:58:37.576583 2021] [mpm_event:info] [pid 18:tid 139715544292416] AH00490: Server built: 2021-07-05T07:16:56
cvat          | [Fri Nov 12 06:58:37.576594 2021] [core:notice] [pid 18:tid 139715544292416] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/cvat-server/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'
cvat          |
cvat          | 2021-11-12 06:58:37,577 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 12 06:58:37.577431 2021] [wsgi:info] [pid 230:tid 139715544292416] mod_wsgi (pid=230): Python home /opt/venv.
cvat          |
cvat          | 2021-11-12 06:58:37,577 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 12 06:58:37.577472 2021] [wsgi:info] [pid 230:tid 139715544292416] mod_wsgi (pid=230): Initializing Python.
cvat          |
cvat          | 2021-11-12 06:58:37,596 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 12 06:58:37.596746 2021] [wsgi:info] [pid 230:tid 139715544292416] mod_wsgi (pid=230): Attach interpreter ''.
cvat          |
cvat          | 2021-11-12 06:58:37,599 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 12 06:58:37.599651 2021] [wsgi:info] [pid 230:tid 139715544292416] mod_wsgi (pid=230): Imported 'mod_wsgi'.
cvat          |
cvat          | 2021-11-12 06:58:37,599 DEBG 'runserver' stderr output:
cvat          | [Fri Nov 12 06:58:37.599686 2021] [wsgi:info] [pid 230:tid 139715544292416] mod_wsgi (pid=230, process='localhost:8080', application=''): Loading Python script file '/tmp/cvat-server/handler.wsgi'.
cvat          |
cvat          | 2021-11-12 06:58:37,750 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2021-11-12 06:58:37,752 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_message: socket 1 (fd=4) type 17
cvat          |
cvat          | 2021-11-12 06:58:37,753 DEBG 'ssh-agent' stderr output:
cvat          | debug1: process_add_identity: add ssh-rsa SHA256:SOANhjL2M4rxL7qMcUZ2qw9OJm2Y8/uXEFXNNQyPd50 "django@372d668cb3f6" (life: 0) (confirm: 0) (provider: none)
cvat          |
cvat          | 2021-11-12 06:58:37,756 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          | debug1: process_message: socket 1 (fd=4) type 11
cvat          |

when I open the browser from internet, it'll always show:
![image](https://user-images.githubusercontent.com/3241829/141425560-70744837-26fe-4315-b9a0-ee3b03e267e2.png)

could you help?

**Comment by azhavoro** [comment]
Hi, please note that `sudo` doesnt pass you current environment variables by default, you need to add `-E` flag for sudo like `sudo -E docker-compose ...`

**Comment by azhavoro** [comment]
Please let me know if you still need help with default port changing.

**Comment by v-datnvt2** [comment]
I use `sudo -E` but web page always show: 404 page not found

**Comment by shaojun** [comment]
@azhavoro thanks, after `export CVAT_HOST=mydomain.com`, and then `sudo -E docker-compose up -d`, I can access the web from public internet by url `mydomain.com`.  Could you update this to doc for others may miss it.

The default port change still not working, from the doc, what I did to `docker-compose.yml` under source folder is:

![image](https://user-images.githubusercontent.com/3241829/141602065-e784bc26-a6f4-4964-85bd-dab7bd8dd073.png)

after `sudo docker-compose down` and `sudo -E docker-compose up -d`, i still can open the web at the original `8080` port, but an error was popup:

![image](https://user-images.githubusercontent.com/3241829/141602189-4c9970a5-4eb9-4ac3-96b6-a395ebbe18ee.png)

**Comment by azhavoro** [comment]
@shaojun there seems to be a inaccuracy here, it doesn't matter which internal container port traefik is listening, you just need to change the external port here: https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.yml#L85
like this:
```
- 8077:8080
```
May I ask you to prepare a little PR to improve the documentation? Thanks.

**Comment by nmanovic** [comment]
@shaojun , I will close the issue. If you can help us to improve documentation, it will be awesome.

**Comment by shaojun** [comment]
i think i've send the PR, please take a look if that good.

**Comment by xml94** [comment]
> Hi, please note that `sudo` doesnt pass you current environment variables by default, you need to add `-E` flag for sudo like `sudo -E docker-compose ...`

This is useful for me. Thank you
