### ISSUE TITLE
Interpolated points for video labeling is not downloaded

### ISSUE THREAD

**Issue by HaomiaoLiu730** [openvinotoolkit/cvat#3907]
When I exported a task for video segmentation, the annotations.json only has the labeling data for the frames that are being manually labeled but not the interpolated labeling points (when I manually labeled frame 1 and frame 5, the json only has the coordinates of points for those two frames but not frame 2,3,4). Is there a way to get the interpolated points in the JSON file as well?

**Comment by nmanovic** [comment]
@HaomiaoLiu730 , it looks like a bug. Need to investigate. Thanks for the report.

@kirill-sizov , could you please look?

**Comment by kirill-sizov** [comment]
Hi, @HaomiaoLiu730, could you please clarify the format in which you export annotations? From your message it's not clear, because CVAT has few formats that supports mask and `*.json` files.

**Comment by zhiltsov-max** [comment]
> it didn't ask me for the data format

If you have JSONs in output and there was no question about format, I suspect you clicked on "Export task". This button is supposed for creating a backup for a task.

@azhavoro, can we make the button action more clear by renaming?

**Comment by HaomiaoLiu730** [comment]
Thanks! I then used COCO format and it actually has all the labeling information I need. Thanks for helping!

**Comment by Zesakof** [comment]
I'm encountering a very similar issue where non-keyframe annotations (interpolated annotations) don't appear when downloading annotations via Python's `requests` library. Here is my CVAT version information, copied from the "About" section in the GUI:

Server version: 2.8.0
Core version: 12.0.0
Canvas version: 2.18.0
UI version: 1.58.0

My Python command looks like this: `response = requests.get(<url>/tasks/<task id>/annotations, cookies=cookies)`, but the JSON that is returned in `response.json()` only includes annotations for keyframes. Furthermore, I didn't see any option to filter for keyframes in the API documentation here: https://app.cvat.ai/api/docs/#tag/tasks/operation/tasks_retrieve_annotations

When I manually download the annotations from the GUI using "Export task dataset" as explained in this issue, I see all annotations for keyframes and non-keyframes. Furthermore, the COCO 1.0 format option has a field `"keyframe":false` nested in the `annotations` part of the downloaded JSON file, so I feel that this should be possible to do via the API as well. Could this be a bug with the API that we aren't able to download annotations for non-keyframes?
