### ISSUE TITLE
"No such container: cvat_db" when trying to back up CVAT DB

### ISSUE THREAD

**Issue by haimat** [openvinotoolkit/cvat#3908]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I followed the [backup/restore guide in the official CVAT docs](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/backup_guide/), which said one should run the following command to backup the CVAT DB (after shutting down the docker container):

    docker run --rm --name temp_backup --volumes-from cvat_db -v $(pwd)/backup:/backup ubuntu tar -cjvf /backup/cvat_db.tar.bz2 /var/lib/postgresql/data

I would expect this command to finish without error.

### Current Behaviour

When running the above command., the following error is thrown:
**docker: Error response from daemon: No such container: cvat_db.**

What am I missing here?

### Your Environment

- Git hash commit (`git log -1`): commit 722dc74b95f5062bb9a7aea62fcf331d0595cab9
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.9
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu Linux 20.04

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
The mentioned backup guide says that you need to stop all your containers with `docker-compose stop`, but it looks like you used` docker-compose down`.

**Comment by haimat** [comment]
> The mentioned backup guide says that you need to stop all your containers with `docker-compose stop`, but it looks like you used` docker-compose down`.

You're absolutely right, thanks for pointing out my mistake.
