### ISSUE TITLE
Cannot create new Cuboids in 3D Workspace

### ISSUE THREAD

**Issue by Duke194** [openvinotoolkit/cvat#3912]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I have a 3D Task created from `.pcd` files and images, in which I want to label a calibration chessboard with cuboids. When I click on `Draw new cuboid` ⇾ `Shape` a cuboid should be placeable on the canvas.

### Current Behaviour
Instead of a new cuboid becoming placeable, an error occurs.

### Possible Solution
I have no clue how to resolve the issue, but I can tell where it happens. Seems like there is a `onDraw` function in `draw-shape-popover.tsx` in which the variable `canvasInstance` has no method `cancel()` to be called.

`draw-shape-popover.tsx:109` is where the error seems to be thrown.

### Steps to Reproduce (for bugs)
1. Create a 3D Task
1. Hover the `Draw new cuboid` button in the sidenav
1. Click on the `Shape` button
1. Open your web browsers inspection tool and recognize the error in the console

### Your Environment
- Git hash commit (`git log -1`): release-1.5.0 (commit: be3240e85d65b911d9507cb1156b0ceab0a77a89)
- Docker version `docker version`: 19.03.14
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- CVAT:
   - Server version: 1.3
   - Core version: 3.11.0
   - Canvas version: 2.3.2
   - UI version: 1.15.3

**Comment by bsekachev** [comment]
1.3 does not support cuboids yet. You need at least 1.5 where CHANGLELOG contains:

```Full support for 3D lidar annotation (import/export annotations and datasets in the release)```
But I would recommend to use the latest release.

**Comment by Duke194** [comment]
Interesting is, that we are on release-1.5.0 with the repository but on the web interface it says 1.3. We'll update to 1.7 on monday and report if that solves the issue.

**Comment by nmanovic** [comment]
@Duke194 , I will close the issue for now. Don't hesitate to reopen it if the problem exists.

**Comment by Duke194** [comment]
We have finally done the upgrade to 1.7. It seems that the docker container we were running was indeed on 1.3, although we have updated the repository to 1.5 in the past. Anyway, with 1.7 everything works fine in the 3D workspace.
