### ISSUE TITLE
How to connect cvat postgres db to Dbeaver

### ISSUE THREAD

**Issue by utkarshumarye** [openvinotoolkit/cvat#3914]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Docker container for cvat_db has following settings:
cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data
    networks:
      - cvat

while below is the connection setting in dbeaver, where "HOST IP" i have put the IP address where cvat is hosted.

![image](https://user-images.githubusercontent.com/46373314/142143203-b4c1ca3b-8c2f-402b-8548-f7cf58374ecb.png)

I'm getting error of timeout connection.

So, I want to know how to connect postgres database to dbeaver.

**Comment by nmanovic** [comment]
@utkarshumarye , it is out of our expertise. We don't know. Please post your question on https://gitter.im/opencv-cvat/public. Maybe somebody from our community knows.
