### ISSUE TITLE
Feature request: Preview of SegmentationClass / SegmentationObject

### ISSUE THREAD

**Issue by kazfujita** [openvinotoolkit/cvat#3922]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Confirmation of annotation of holes in polygon objects needs to export masks and to open the mask and corresponding original image. This type of annotation is very common in pathological images, such as lesion site in normal tissue, white blood cells in lesion site, and normal tissue in background slide.
A past issue #2958 was related to hole annotation, and they uploaded exported masks instead of screenshot to discuss the situation.

And this type of confirmation is time consuming for annotators, in our case pathologists.
If Preview feature of SegmentationClass / SegmentationObject is available in CVAT, it will be helpful for annotators and pathologists.

**Comment by nmanovic** [comment]
@kazfujita , why `opacity` appearance option doesn't work for you?

![Nov-19-2021 21-23-57](https://user-images.githubusercontent.com/40690625/142673124-5fd68a7f-adf3-4f5d-a323-98b8688b48d8.gif)

**Comment by kazfujita** [comment]
I have not noticed that usage of opacity.
It solved the situation.
Thank you very much!
