### ISSUE TITLE
Problem with rotated bounding box when importing a task

### ISSUE THREAD

**Issue by AmitN1212** [openvinotoolkit/cvat#3926]
Hi,
first of all, I would like to say thank you for adding the ability to have rotated bounding boxes - it is really useful. 
However, when I export a task that contains a rotated bounding box and then import it, the bounding box is not rotated anymore. It does not happen when I upload annotation (for an existing task).
What can I do in order to fix it?
Thank you.

**Comment by bsekachev** [comment]
Hi, 

Thank you for the feedback. Looks like a bug. Let me check.

**Comment by bsekachev** [comment]
@AmitN1212 

Reproduced, fix in related PR
