### ISSUE TITLE
is:issue is:open How to export "point" annotations from CVAT tool

### ISSUE THREAD

**Issue by Rishikavr** [openvinotoolkit/cvat#3930]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by Rishikavr** [comment]
I want to export the all the points after the annotations

**Comment by nmanovic** [comment]
@Rishikavr , if you want to dump points, need to choose an appropriate format (e.g. CVAT for images). I will close the issue. Don't hesitate to ask our community on https://gitter.im/opencv-cvat/public
