### ISSUE TITLE
Can't mount shared folder if it is mounted s3 filesystem

### ISSUE THREAD

**Issue by isudos** [openvinotoolkit/cvat#3935]
I'm trying to use directory /home/central-admin/s3-defects-data as shared folder in accordance with instructions from here: https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#share-path

If the directory is fully local then everything is ok.
If the directory is s3 mounting point (I mounted s3 using Fuse, and it is not AWS, it is another provider) then I get:

`ERROR: for 4925b50df6a1_cvat  Cannot create container for service cvat: open /var/lib/docker/volumes/cvat_share/_data: permission denied`

during docker compose.
All the files within /home/central-admin/s3-defects-data  are working. 

What can cause this? 

_Originally posted by @isudos in https://github.com/openvinotoolkit/cvat/issues/2263#issuecomment-974930428_

**Comment by nmanovic** [comment]
@isudos , most probably it is an issue with permissions. Try to access the directory as another user. Change permissions to the directory, mount the directory with correct rights.

**Comment by Marishka17** [comment]
@isudos , Hi, please check that you mount with `allow_other` option.

**Comment by isudos** [comment]
@Marishka17 Thanks a lot! That works.
