### ISSUE TITLE
Importing MOT annotations fails: ValueError: Unknown internal frame id -1\n

### ISSUE THREAD

**Issue by maartenvds** [openvinotoolkit/cvat#3940]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I tried to import MOT 1.1 annotations into a task using the web UI and it failed with a popup message: "ValueError: Unknown internal frame id -1\n".

### Expected Behaviour
The import should succeed

### Current Behaviour
A popup message displays: "ValueError: Unknown internal frame id -1\n".

### Steps to Reproduce (for bugs)

1. Create a new project and upload a video
1. Open the task
1. Click Actions -> upload annotations -> MOT 1.1
1. Select zip folder and click 'upload'

The content of my .zip folder contains:
```
mot/seqinfo.ini
mot/gt/gt.txt
mot/gt/labels.txt
```

Content of seqinfo.ini:
```
[Sequence]
name=Test
imDir=img
frameRate=10
seqLength=1454
imWidth=640
imHeight=480
imExt=.jpg
```

Content of labels.txt
```
person
```

First lines from gt.txt:
```
1, 1, 162, 367, 93, 110, 1, 1, 1
2, 1, 162, 364, 94, 114, 1, 1, 1
3, 1, 161, 359, 91, 119, 1, 1, 1
4, 1, 161, 357, 86, 120, 1, 1, 1
```

I also tried this with annotation data found on the https://motchallenge.net/data/MOT20/ and got the same error.

### Possible Solution

To further debug the problem, I installed the development environment as described here: https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/

After stepping through the code I found the following lines that process the annotations (mot.py, recent develop branch):

```
36 for item in dataset:
37     frame_number = int(item.id) - 1 # NOTE: MOT frames start from 1
38     frame_number = task_data.abs_frame_id(frame_number)
```
The first ```item.id``` appeared to already be zero since the datumaro package already returns zero based item ids. By subtracting with 1 on line 37, you become -1 for the first item, which generates a ValueError in the function called at line 38, which is the error that was displayed in the UI.

Simple fix:

```
36 for item in dataset:
37     frame_number = int(item.id)
38     frame_number = task_data.abs_frame_id(frame_number)
```

### Your Environment

- Git hash commit (`git log -1`): 723b2a8327171d8c1a93577f90d0b96d5bbbaffa
- Installed using steps in https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/
- Ubuntu 20.04

Note that I reproduced the same behaviour on cvat.org and with the docker installed environment as explained here https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64

**Comment by nmanovic** [comment]
@maartenvds , thanks for the report and your findings. Could you please help us and prepare a PR?

**Comment by zhiltsov-max** [comment]
Fixed on Datumaro side; checked in CVAT.
