### ISSUE TITLE
How to prohibit annotators to download the data

### ISSUE THREAD

**Issue by liuliaocheng** [openvinotoolkit/cvat#3950]
hi,I found that the annotator can also download data from the client,
How to prohibit annotators to download the data?
thinks!

**Comment by nmanovic** [comment]
@liuliaocheng , for now it is not possible. We are working on IAM: https://github.com/openvinotoolkit/cvat/pull/3788. It should resolve the issue.

**Comment by liuliaocheng** [comment]
> @liuliaocheng , for now it is not possible. We are working on IAM: #3788. It should resolve the issue.

ok~thank you ~
