### ISSUE TITLE
sorting task problem

### ISSUE THREAD

**Issue by rastinrastini** [openvinotoolkit/cvat#3954]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

i search but dont find any solution.

### Expected Behaviour
i see that sort must by creation.

### Current Behaviour
seems dont sort properly. i dont find any sorting.

### Possible Solution
sort by creation or name.

### Steps to Reproduce (for bugs)
create task.

### Context
sorting

### Your Environment
- ubuntu 20.04
![sort_bug](https://user-images.githubusercontent.com/7768900/143730522-dd2d7e30-1d4c-435b-be1e-cb2a3aaaf6cd.png)

**Comment by azhavoro** [comment]
Hi, please provide exact steps to reproduce the issue, currently tasks are sorted by id(reverse): https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/serializers.py#L365

**Comment by rastinrastini** [comment]
easily installed, create project and create task. i think dont any work on it.
 i dont find any meaning in sorting in task list.

**Comment by rastinrastini** [comment]
seems, problem founded. when i go to tasks then sorting is correct. but when going to project, tasks of specific project has problem in sorting.

**Comment by ActiveChooN** [comment]
Should be fixed via https://github.com/openvinotoolkit/cvat/pull/4409
