### ISSUE TITLE
track a pre-annotated objects 

### ISSUE THREAD

**Issue by omarreda14** [openvinotoolkit/cvat#3958]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by omarreda14** [comment]
i have a labeled frames resulted from a trained model , the frames are from a security camera video , i need to set an unique ID to each label to help in tracking  some objects over frames .
is there any way to do that ?

**Comment by azhavoro** [comment]
Hi, try to use ReID model: https://github.com/openvinotoolkit/cvat/tree/develop/serverless/openvino/omz/intel/person-reidentification-retail-300/nuclio
Installation guide: https://openvinotoolkit.github.io/cvat/docs/contributing/setup-additional-components/#dl-models-as-serverless-functions

**Comment by subhailams** [comment]
We have annotations from the person detection model, then we are trying to run the person [Reid model](https://github.com/openvinotoolkit/cvat/tree/develop/serverless/openvino/omz/intel/person-reidentification-retail-300/nuclio) and export that to Market 1501 dataset format. But we don't get the exact number of query images. For two-person in a video, when we export the data, we only receive one person query image. 

Could anyone please summarize how to export the data in Market1501 format after performing detection + reidentification using CVAT models??
