### ISSUE TITLE
Task creation ignore manifest name in code

### ISSUE THREAD

**Issue by Sigura** [openvinotoolkit/cvat#3968]
### Expected Behaviour

When I add s3 storage with the specified name, it will be used on task creation with a chosen manifest name.

Update: remove the limit of manifest files in [UI](https://github.com/openvinotoolkit/cvat/blob/1d952acee8dbce679daac99ff615b8bec2b3cbf9/cvat-ui/src/components/create-cloud-storage-page/manifests-manager.tsx#L23) (5 currentlly)

### Current Behaviour

Current implementation ignore settings and await `manifest.jsonl`
https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/task.py#L140

Without `manifest.jsonl` file will raise Exception('A manifest file not found')
https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/task.py#L241

And error "Unable to add manifest. The maximum number of files is 5." in UI

### Possible Solution

Would you please take the name from the chosen cloud storage settings?
And remove limit

**Comment by Sigura** [comment]
found workaround add the manifest file to subfolder and add subfolder name to manifest name

![Screenshot 2021-11-30 at 23 54 45](https://user-images.githubusercontent.com/428500/144126519-6290e20f-547c-46fa-a752-f5bd0b8f8308.png)

**Comment by Sigura** [comment]
@Marishka17 Would you please explain in a few words why cloud storage has a limit on manifest files?

When I tried to add 6, I got "Unable to add manifest. The maximum number of files is 5."

**Comment by Marishka17** [comment]
> @Marishka17 Would you please explain in a few words why cloud storage has a limit on manifest files?
> 
> When I tried to add 6, I got "Unable to add manifest. The maximum number of files is 5."

It was implemented for some reason. Manifest is needed to describe the contents of the bucket and there was an opinion "one dataset - one bucket". Maybe restrictions can be removed in the future. You can change restrictions [here](https://github.com/openvinotoolkit/cvat/blob/1d952acee8dbce679daac99ff615b8bec2b3cbf9/cvat-ui/src/components/create-cloud-storage-page/manifests-manager.tsx#L23)

> Update: And please help me to understand where API with register handler in `cvat` container? I mean physically as `js` file? Or `py`? (Spent about an hour to understand but... fail)

If I understand you correctly, you need to look at [here](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/views.py)

**Comment by Sigura** [comment]
> You can change restrictions [here](https://github.com/openvinotoolkit/cvat/blob/1d952acee8dbce679daac99ff615b8bec2b3cbf9/cvat-ui/src/components/create-cloud-storage-page/manifests-manager.tsx#L23)

Yeah, thank you! I replaced it in minified js.

**Comment by Sigura** [comment]
@Marishka17 I asked about endpoint `/api/v1/auth/register` I research a way to remove it in code in common part and leave register only through admin interface

**Comment by Sigura** [comment]
@Marishka17 Please don't warry, found [it](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/authentication/urls.py#L23)

**Comment by ztyree42** [comment]
> It was implemented for some reason. Manifest is needed to describe the contents of the bucket and there was an opinion "one dataset - one bucket". 

Is there a plan to fix this? AWS only supports 100 buckets so an organization that plans to move their entire annotation pipeline into CVAT hosted on AWS have to think carefully about scalability.

I've tried creating multiple datasets in the same bucket but have not had success in using create.py to create a well-formed manifest.jsonl file since it assumes everything is at the top level when creating the relative paths.

**Comment by nmanovic** [comment]
@ztyree42 , you can create as many manifest files in one bucket, as necessary. Could you please tell us what doesn't work for you?

**Comment by ztyree42** [comment]
@nmanovic putting the manifest file under a prefix and S3 causes a manifest not found error, alternatively having a manifest file at the top level and then in the name key inside of the manifest file including the unambiguous path in s3 to the image files does not seem to be supported by the create.py script. The only success I've had is to create a bucket per data set and include the manifest file at the top level along with the image files. Could you show a working example of either including a manifest file under a prefix in S3 or alternatively how to generate a manifest file at the top level that includes the unambiguous path to an image under a prefix?

**Comment by nmanovic** [comment]
@Marishka17 , could you please help and extend our documentation to make it clear?
