### ISSUE TITLE
Auto annotation problems

### ISSUE THREAD

**Issue by SabinaUS** [openvinotoolkit/cvat#3971]
![Screenshot from 2021-12-01 13-27-27](https://user-images.githubusercontent.com/61276853/144171871-e2ca06bc-5192-4757-aa09-edadc7d3c164.png)
After uploading own DL model I go to the dashboard. Now how can I open tool to annotate it automatic or semiautomatic

**Comment by nmanovic** [comment]
@SabinaUS , it is a question for our gitter channel: https://gitter.im/opencv-cvat/public. Here we try to keep only bugs or feature requests. Sorry that some information isn't very intuitive and users like you help us to improve documentation by questions. Also I have to say that automatic annotation is an advanced topic. I see that some users can run it without significant problems, others suffer from lack of information.

I will close the issue. Please ask your questions on our gitter channel. Our community is very helpful. The core team just cannot help everybody.
