### ISSUE TITLE
track pre-annotated objects in CVAT

### ISSUE THREAD

**Issue by seif210** [openvinotoolkit/cvat#3990]
I have a labeled images resulted from a trained model , the images from a video , i need to set an unique ID to each label to help in tracking some objects over frames .
is there any way to do that ?

**Comment by azhavoro** [comment]
Seems I have answered your question on gitter, for now I would only suggest try to use ReID model for person objects https://github.com/openvinotoolkit/cvat/tree/develop/serverless/openvino/omz/intel/person-reidentification-retail-300/nuclio
