### ISSUE TITLE
Could not create the task Open the Browser Console to get details

### ISSUE THREAD

**Issue by shajahanpc** [openvinotoolkit/cvat#3991]
### My actions before raising this issue
I just created one project in CVAT and Uploaded Task, But it shows "Could not create the task
Open the Browser Console to get details"

Issue showing in console: 
1- enviroment.ts:31 Web analitycs hit function has failed. ReferenceError: wap_tms is not defined
2- cvat-app.tsx:262 Error: 
  Could not create the task on the server. PIL.UnidentifiedImageError: cannot identify image file '/home/django/data/data/143720/raw/B11_A4/AG1046.jpg'.
3- cvat-app.tsx:262 Error: 
                                        Could not create the task on the server. PIL.UnidentifiedImageError: cannot identify image file '/home/django/data/data/143727/raw/B11_A4/AG1046.jpg'.
                                    
                                    

- I use CVAT.org online platform.
Does anyone can help me to fix, I know we can upload max of 10 task in a account. Is there any way to fix this issue.

Thanks in advance!

**Comment by azhavoro** [comment]
Seems there is a problem with this image which cannot be opened by PIL, could you try to create a task without this image or try to save it on any different format?

**Comment by shajahanpc** [comment]
Yes, That is correct. I checked the dataset, There I found an image has a problem. It is fixed. Thanks a lot for your help and support @azhavoro

**Comment by deeshantk** [comment]
> Yes, That is correct. I checked the dataset, There I found an image has a problem. It is fixed. Thanks a lot for your help and support @azhavoro

Same for me too. I had 2 corrupted images. 
Was able to successfully create task after fixing that.
