### ISSUE TITLE
Add support for S3 compatible storage providers (eg MinIO)

### ISSUE THREAD

**Issue by Qsi1984** [openvinotoolkit/cvat#3996]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The new clowd storage feature is great but we have our Data on a private s3 compatible storage. There are multiple offerings for such storage on the market and it would be great if those would be usable as well. 

### Current Behaviour

Currently the AWS S3 cloud storage provider only supports AWS hosted S3 buckets.

### Possible Solution

In essence we need a way to configure endpoint_url for the boto3 resource when adding a cloud storage.

**Comment by lozhn** [comment]
Can you please add [parameter](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client)  
 `endpoint_url` [here](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/cloud_provider.py#L143) (maybe set its default value to `s3.amazonaws.com` or so ) and 1 more field to the [form](https://github.com/openvinotoolkit/cvat/blob/develop/cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx#L333) ? That would enable using minio as an S3 compatible storage 🤗

**Comment by nmanovic** [comment]
@lozhn , could you please contribute the feature?

**Comment by lozhn** [comment]
@nmanovic  I'll try next week ;)

**Comment by Rekha-Prakash** [comment]
@Marishka17 I am also looking for this feature, since I use MinIO for storage. Is there any timeline on this when this will be implemented ?
