### ISSUE TITLE
Can't deploy CVAT on public ipv4

### ISSUE THREAD

**Issue by alexander-soare** [openvinotoolkit/cvat#3997]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I can go to my ipv4 address on a chrome browser and see the CVAT app running.

### Current Behaviour

It's not clear to me which url to try:

- With http://164.90.254.8/ I get "This 164.90.254.8 page can’t be found"
- With http://164.90.254.8:8080/ I get indefinite loading (blank page) with an eventual timeout to "This site can’t be reached"
- With http://164.90.254.8:8080/admin same as previous point

### Steps to Reproduce (for bugs)

1a. Set up an instance on AWS S3 (I used a t3.small) and enable inbound http

![image](https://user-images.githubusercontent.com/16543381/145073479-99843c82-bd9a-4b51-8f9d-fa7c3f9ca20a.png)

1b. OR set up a digital ocean droplet. Make sure to assign a floating IP. Add a firewall with the following inbound rules

![image](https://user-images.githubusercontent.com/16543381/145073859-702f235b-b00a-4952-9b44-879d21675da7.png)

2. SSH into the instance and follow the installation guide as written [here](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/). Don't run the `docker-compose up -d` yet, and don't follow the alternative route (building the images locally)

3. According to [these instructions](https://openvinotoolkit.github.io/cvat/docs/administration/basics/aws-deployment-guide/) set up `export CVAT_HOST={IPV4.ADDRESS}`.

4. Now run `docker-compose up -d`

Alternative:

Even though it is not in the docs I linked above, I found the approach of making a `docker-compose.override.yml` with

```
version: "2.3"

services:
  cvat:
    environment:
      ALLOWED_HOSTS: {IPV4.ADDRESS}
    ports:
      - "80:8080"
```

And then `sudo docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d`

This had no impact on the outcome.

### Your Environment

- Git hash commit: f313a710015fa29327f69bb918dc4f6bd0f7bf6e
- Docker version: 20.10.11
- OS: Ubuntu Server 20.04 LTS

**Comment by azhavoro** [comment]
You need to map port for `traefik` service instead of `cvat`:
https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

**Comment by alexander-soare** [comment]
@azhavoro thanks for jumping in. So to be clear, I have changed my `docker-compose.override.yml` to look like this:

```
version: "2.3"

services:
  traefik:
    ports:
      - 8080:8080
      - 8090:8090
```

AND I have used the `-E` flag with `sudo docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d`.

Unfortunately the outcome is the same
