### ISSUE TITLE
Semi-automatic and Automatic Annotation ：error

### ISSUE THREAD

**Issue by liucong255** [openvinotoolkit/cvat#4000]
Create cvat project inside nuclio dashboard where you will deploy new serverless functions and deploy a couple of DL models. Commands below should be run only after CVAT has been installed using docker-compose because it runs nuclio dashboard which manages all serverless functions.

nuctl create project cvat

nuctl deploy --project-name cvat \
  --path serverless/openvino/dextr/nuclio \
  --volume `pwd`/serverless/common:/opt/nuclio/common \
  --platform local
![image](https://user-images.githubusercontent.com/38726093/145185567-879b427e-a963-4eeb-b5f6-cbcfc1e10d45.png)

**Comment by liucong255** [comment]
![image](https://user-images.githubusercontent.com/38726093/145191018-5aec9f77-c32f-41d4-96c8-469fa21153b5.png)

**Comment by liucong255** [comment]
![image](https://user-images.githubusercontent.com/38726093/145316449-84c9a650-d947-4bba-ada8-b3ca1bb0ccad.png)

**Comment by AmitN1212** [comment]
It seems that you have a problem with your internet connection.

**Comment by SabinaUS** [comment]
The same problem with mask rcnn

**Comment by SabinaUS** [comment]
@bsekachev

**Comment by SabinaUS** [comment]
Hello, everyone when I try to add Mask RCNN trained model using gpu to the auto annotation process it is gives error as unhealthy.
And docker output is :
21.12.14 03:59:20.166 sor.http.w0.python.logger (D) Running wrapper {"command": "/usr/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-c6s1d60l2j1nqsluft90.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger"}
l{"datetime": "2021-12-14 03:59:21,337", "level": "error", "message": "Caught unhandled exception while initializing", "with": {"err": "expected str, bytes or os.PathLike object, not NoneType", "traceback": "Traceback (most recent call last):\n File "/opt/nuclio/_nuclio_wrapper.py", line 350, in run_wrapper\n args.trigger_name)\n File "/opt/nuclio/_nuclio_wrapper.py", line 57, in init\n self._entrypoint = self._load_entrypoint_from_handler(handler)\n File "/opt/nuclio/_nuclio_wrapper.py", line 159, in _load_entrypoint_from_handler\n module = import(module_name)\n File "/opt/nuclio/main.py", line 5, in \n from model_loader import ModelLoader\n File "/opt/nuclio/model_loader.py", line 10, in \n MASK_RCNN_DIR = os.path.abspath(os.environ.get('/home/user/Desktop/Mask_RCNN-master/'))\n File "/usr/lib/python3.6/posixpath.py", line 378, in abspath\n path = os.fspath(path)\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "worker_id": "0"}}
21.12.14 03:59:21.520 sor.http.w0.python.logger (E) Unexpected termination of child process {"error": null, "status": "exit status 1"}
panic: Wrapper process for worker 0 exited unexpectedly with: exit status 1

goroutine 82 [running]:
github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).watchWrapperProcess(0xc0002ec000)
/nuclio/pkg/processor/runtime/rpc/abstract.go:464 +0x576
created by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper
/nuclio/pkg/processor/runtime/rpc/abstract.go:236 +0x1b5

**Comment by SabinaUS** [comment]
@nmanovic

**Comment by SabinaUS** [comment]
...//nuclio/pkg/platform/abstract/platform.go:182
  NAMESPACE |                      NAME                      | PROJECT |  STATE   | NODE PORT | REPLICAS  
  nuclio    | pth.facebookresearch.detectron2.retinanet_r101 | cvat    | ready    |     49236 | 1/1       
  nuclio    | tf-matterport-mask-rcnn                        | cvat    | building |         0 | 1/1

**Comment by azhavoro** [comment]
@liucong255 Hi, I cannot reproduce this issue, in my case the function image built successfully.
Seems there are some network issues, please try again and make sure `pythonhosted.org` is reachable for you. Are you using a proxy?

**Comment by liucong255** [comment]
An error was reported due to repeated installation, which has been resolved
