### ISSUE TITLE
Unable to add a task, unable to export project dataset

### ISSUE THREAD

**Issue by corniels14** [openvinotoolkit/cvat#4002]
### My actions before raising this issue
I was adding tasks on cvat.org, annotating them, and downloading the project dataset, after a while this stopped working.

### Expected Behaviour
- Being able to add a task
- Being able to download the project dataset

### Current Behaviour
- After submitting a task the message "The data are being uploaded to the server.." appears, it's stuck here
  - This is also the case when uploading only 1 image
- After clicking "Export project dataset" the message "Dataset export started" appears, nothing happens after that

### Your Environment
- Tested on 2 computers, using Google Chrome

**Comment by bsekachev** [comment]
Please, check if your tasks created now. 
cvat.org was highly loaded recently.

**Comment by corniels14** [comment]
> Please, check if your tasks created now. cvat.org was highly loaded recently.

It's working now!
