### ISSUE TITLE
Auto annotation with Mask RCnn get error 

### ISSUE THREAD

**Issue by SabinaUS** [openvinotoolkit/cvat#4004]
@AmitN1212 Hello I have problem. I try to deploy MascRcnn deploy_gpu segmentation task using trained on coco dateset: serverless/tensorflow/matterport/mask_rcnn/ is optimized for GPU. serverless/deploy_gpu.sh serverless/tensorflow/matterport/mask_rcnn.
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/ but I got an error. The model not adde
![Screenshot from 2021-12-09 17-03-04](https://user-images.githubusercontent.com/61276853/145357675-6a8ac0d5-2188-4e5f-889e-d959fbb3b6f0.png)
I get error as  Error: Function is not healthy and I count not  use model in my local host

**Comment by AmitN1212** [comment]
Please write:
`docker ps
`Copy the id of that container
see the output of: `docker logs <id>`

**Comment by SabinaUS** [comment]
Hello @AmitN1212, thank you for your kind help. My output error showed above. Can you help with this. Thank you:  
21.12.14 03:59:20.166 sor.http.w0.python.logger (D) Running wrapper {"command": "/usr/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-c6s1d60l2j1nqsluft90.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger"}
l{"datetime": "2021-12-14 03:59:21,337", "level": "error", "message": "Caught unhandled exception while initializing", "with": {"err": "expected str, bytes or os.PathLike object, not NoneType", "traceback": "Traceback (most recent call last):\n File "/opt/nuclio/_nuclio_wrapper.py", line 350, in run_wrapper\n args.trigger_name)\n File "/opt/nuclio/_nuclio_wrapper.py", line 57, in init\n self._entrypoint = self._load_entrypoint_from_handler(handler)\n File "/opt/nuclio/_nuclio_wrapper.py", line 159, in _load_entrypoint_from_handler\n module = import(module_name)\n File "/opt/nuclio/main.py", line 5, in \n from model_loader import ModelLoader\n File "/opt/nuclio/model_loader.py", line 10, in \n MASK_RCNN_DIR = os.path.abspath(os.environ.get('/home/user/Desktop/Mask_RCNN-master/'))\n File "/usr/lib/python3.6/posixpath.py", line 378, in abspath\n path = os.fspath(path)\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "worker_id": "0"}}
21.12.14 03:59:21.520 sor.http.w0.python.logger (E) Unexpected termination of child process {"error": null, "status": "exit status 1"}
panic: Wrapper process for worker 0 exited unexpectedly with: exit status 1

goroutine 82 [running]:
github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).watchWrapperProcess(0xc0002ec000)
/nuclio/pkg/processor/runtime/rpc/abstract.go:464 +0x576
created by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper
/nuclio/pkg/processor/runtime/rpc/abstract.go:236 +0x1b5
