### ISSUE TITLE
API method to register does not return authentification token

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#4010]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
It authentificates the user, returns sessionid, csrftoken and CVAT token

### Current Behaviour
It authentificates the user, returns sessionid, csrftoken

**Comment by g-kartik** [comment]
Hi @bsekachev I solved this issue, may I open a pull request?

**Comment by bsekachev** [comment]
Hi @g-kartik 

That is great! Please, open the PR
