### ISSUE TITLE
Unable to to import project

### ISSUE THREAD

**Issue by wangzyon** [openvinotoolkit/cvat#4020]
I cannot find import dataset in project actions. 
> Log in as superuser  

![image](https://user-images.githubusercontent.com/36832126/145931619-3e2b1990-970b-46b7-8131-bb5f2c6d4ccc.png)

![image](https://user-images.githubusercontent.com/36832126/145930825-f94a3064-dccd-49ac-9403-7883a7353bdc.png)

```
$ git branch
* develop

$ git log -1
commit 1d952acee8dbce679daac99ff615b8bec2b3cbf9 (HEAD -> develop)
Author: Dmitry Kalinin <dmitry.kalinin@intel.com>
Date:   Thu Dec 2 07:07:04 2021 +0300

    Issue deleting (#3952)
```

**Comment by azhavoro** [comment]
Related PR https://github.com/openvinotoolkit/cvat/pull/3790 is not merged yet.
