### ISSUE TITLE
Assignement of labels to frames occurs in reveresed order

### ISSUE THREAD

**Issue by Chicone** [openvinotoolkit/cvat#4025]
### My actions before raising this issue
- [✓] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [✓] Searched [past issues](/issues)

### Expected Behaviour

Using the web interface at https://cvat.org/, when exporting task dataset, the annotations should be assigned to the frames as they are shown in the interface.

### Current Behaviour

When loading the images into the interface by selecting them all from a given directory, the uploading occurs without problems and they are shown in the correct order in the interface. However, when exporting the task dataset, labels are assigned to frames in reversed order, making the annotations unusable.  This does not seem to occur when a video is loaded instead of a batch of separate images.

### Steps to Reproduce (for bugs)

This link shows a sequence loaded in the right order but when you export with the "save the images" option clicked, the images are saved in reversed order. In other words, frame one contains last frame:. 
https://cvat.org/tasks/154079/jobs/234353

### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@Marishka17 , could you please investigate?

**Comment by Marishka17** [comment]
@Chicone, Hi, could you please describe step by step your case?
I can not reproduce a case when labels are assigned to frames in reversed order.
