### ISSUE TITLE
Get annotations from cvat_db

### ISSUE THREAD

**Issue by aaganaie** [openvinotoolkit/cvat#4032]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi , I have cvat installed on a server . My labels on UI got deleted( dont know how) and after that all my annotations in all the tasks of project were gone .
I tried to add labels on UI again in hope to get my annotations back but it did not .[ while adding same labels cvat would give it different id , which is why i think it did not work ] 
I looked in db_cvat volume /var/lib/postgresql/data folder .
I found pg_wal  folder having two files , when i opened those through dbeaver i could see only the Bounding Box's co-ordinates everything else looked kind of encrypted. [ added image for the reference ]
![Screenshot (20)](https://user-images.githubusercontent.com/27224331/146236046-7d1926ad-72ea-4e49-8078-0260ba64fdb0.png)

My Questions :

1. Can I get my annotations from this encrypted looking data ?
2. Can I add labels again with same id to revert everything back to normal ? [ i have old labels and their id saved in json format ] 
3. Any other way to get annotations back ?
4. Where is mapping of labels and label id stored in cvat ?

**Comment by bsekachev** [comment]
Hi, the only way to delete labels is to send explicit flag "delete" to the server. Unfortunately, if your labels actually were deleted, the annotations is also were deleted from the database (relations rules). On UI you can remove labels on project/task page, but we have confirmation messages there.

I am not expert in databases, but google says that pg_wal stores WAL (Write-Ahead Logging) journals. And there is no way to restore data having only them:

> If you only have the WAL, with no base backup (copy of the data directory, pg_basebackup, etc), you cannot restore.

https://dba.stackexchange.com/questions/183505/restoring-postgresql-database-from-wal-without-backup

This is not final NOT answer on your question, but restoring data this way is definitely not CVAT issue. I would suggest trying to find help in postgres community
