### ISSUE TITLE
Swagger LabelSerializer error

### ISSUE THREAD

**Issue by klakhov** [openvinotoolkit/cvat#4037]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

No error should be displayed

### Current Behaviour

An error is displayed in debug console
![image](https://user-images.githubusercontent.com/50956430/146351578-c78455b8-5764-4dbd-8aaf-fac6876d69c5.png)

### Steps to Reproduce (for bugs)

1.Start development server
2.Go to localhost:3000/api/swagger

### Your Environment

- Git hash commit (`git log -1`): 3cf5265b014296e6c9e7e08d98f298d4f00310ea
- Are you using Docker Swarm or Kubernetes? No, development env
- Operating System and version (e.g. Linux, Windows, MacOS): Linux

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by Marishka17** [comment]
I don't see this error after migration to `drf_spectacular`. I guess it can be closed after merging [PR](https://github.com/openvinotoolkit/cvat/pull/4210).
@klakhov, What do you think?

**Comment by klakhov** [comment]
@Marishka17 I don't see any errors now. It seems it was fixed
