### ISSUE TITLE
Could not create the task

### ISSUE THREAD

**Issue by liucong255** [openvinotoolkit/cvat#4049]
![image](https://user-images.githubusercontent.com/38726093/146744650-52212d9e-0425-460f-95eb-eb48fc121df8.png)

**Comment by azhavoro** [comment]
@liucong255 please provide details how we can reproduce this issue.

**Comment by liucong255** [comment]
@azhavoro docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml -f components/serverless/docker-compose.serverless.yml up -d --build

**Comment by azhavoro** [comment]
@klakhov could you please take a look?

**Comment by klakhov** [comment]
@azhavoro, sure. I'll check this out

**Comment by bsekachev** [comment]
@liucong255 

Probably your CVAT instance is not updated with this patch #3692 to upload big files via the browser.
I do not see any tus-related headers in HTTP Request headers field. 

The command you send ``docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml -f components/serverless/docker-compose.serverless.yml up -d --build`` does fetch available docker images for client and server from dockerhub. We update them when releases come, but this patch has not been released yet.

To build from scratch add ``-f docker-compose.dev.yml``

**Comment by liucong255** [comment]
@bsekachev Yes, I didn't use patch 3692, will my data be lost if I build from scratch?

**Comment by bsekachev** [comment]
@liucong255 

Just do ``docker-compose down``, do not need to drop any containers.

**Comment by nmanovic** [comment]
@liucong255 , I will close the issue. Feel free to reopen if you still have problems.
