### ISSUE TITLE
Incorrect progress bar

### ISSUE THREAD

**Issue by Marishka17** [openvinotoolkit/cvat#4058]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour

![image](https://user-images.githubusercontent.com/49038720/147057277-582380d6-3a0a-442f-8b2d-ab6df43bdf0d.png)

### Steps to Reproduce (for bugs)

1.  go to the task creating page
1. fill in the required fields, attach e.g dataset with images
1. create a task

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@klakhov Could you please look at the issue?

**Comment by bsekachev** [comment]
I think it was resolved
