### ISSUE TITLE
Update CONTRIBUTING.md guide to run debug version of CVAT

### ISSUE THREAD

**Issue by AmitN1212** [openvinotoolkit/cvat#4072]
### My actions before raising this issue
* [x]  Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
* [x]  Searched [past issues](/issues)

### Expected Behaviour
Sign in successfully to CVAT.
### Current Behaviour
I am getting the following error: 
![Screenshot from 2021-12-23 08-48-15](https://user-images.githubusercontent.com/69145846/147200236-967d3524-78fc-413e-a111-4a4ba9a7117d.png)
### Steps to Reproduce (for bugs)

1. I had CVAT worked well with the latest commits in the development environment.
2. I pulled the last commit.
3. I ran these commands in order to update CVAT : 
    - ```pip install -r cvat/requirements/development.txt```
    - ```python manage.py migrate```
    - ```python manage.py collectstatic```
    - ```npm ci```
4. I got the same error that I am getting now so I completely reinstalled CVAT using [these](https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/) steps.
### Your Environment
Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

Here are the logs from VScode console:
[server-chrome-logs.txt](https://github.com/openvinotoolkit/cvat/files/7767333/server-chrome-logs.txt)
[server-django-logs.txt](https://github.com/openvinotoolkit/cvat/files/7767336/server-django-logs.txt)

**Comment by bsekachev** [comment]
Probably need to run OpenPolicyAgent:

``docker-compose -f docker-compose.yml  -f docker-compose.dev.yml up cvat_opa``

**Comment by AmitN1212** [comment]
> Probably need to run OpenPolicyAgent:
> 
> `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up cvat_opa`

Thanks, it worked. However, now when I try to register and create another account (after I have created the superuser), it immediately fails and I get this exception:

```
Exception has occurred: Error: Async Validation Error
  at next (http://localhost:3000/cvat-ui.81eaae8014885db72a4a.min.js:135283:40)
    at count (http://localhost:3000/cvat-ui.81eaae8014885db72a4a.min.js:135193:7)
    at cb (http://localhost:3000/cvat-ui.81eaae8014885db72a4a.min.js:136288:11)
    at Object.pattern$2 [as validator] (http://localhost:3000/cvat-ui.81eaae8014885db72a4a.min.js:135929:3)
    at http://localhost:3000/cvat-ui.81eaae8014885db72a4a.min.js:136351:20
    at http://localhost:3000/cvat-ui.81eaae8014885db72a4a.min.js:135198:5
    at Array.forEach (<anonymous>)
    at asyncParallelArray (http://localhost:3000/cvat-ui.81eaae8014885db72a4a.min.js:135197:7)
    at http://localhost:3000/cvat-ui.81eaae8014885db72a4a.min.js:135298:9
    at Array.forEach (<anonymous>)
```  
Do you have any idea of solving it?

**Comment by bsekachev** [comment]
Could you please send us a screenshot?

**Comment by AmitN1212** [comment]
> Could you please send us a screenshot?

When I enter a character it is stuck:

![Screenshot from 2021-12-23 14-43-37](https://user-images.githubusercontent.com/69145846/147242177-ecb3b9b1-9007-48f1-a409-8d84455290b5.png)

This is what I see in VScode:
![Screenshot from 2021-12-23 14-46-46](https://user-images.githubusercontent.com/69145846/147242511-49a7523f-7e36-4fc8-bb53-518e31306abc.png)

**Comment by bsekachev** [comment]
Just remove breakpoint on uncaught exceptions in VSCode. It is a validation libary which throws different exceptions while working. It is a normal behaviour I believe.

**Comment by AmitN1212** [comment]
> Just remove breakpoint on uncaught exceptions in VSCode. It is a validation libary which throws different exceptions while working. It is a normal behaviour I believe.

It worked, thanks!

Btw, maybe it is better to update the dev environment [instructions](https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/), so it will include this:

> Probably need to run OpenPolicyAgent:
> 
> `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up cvat_opa`

**Comment by bsekachev** [comment]
> Btw, maybe it is better to update the dev environment instructions, so it will include this:

Agree.

**Comment by nmanovic** [comment]
@AmitN1212 , could you please help us and contribute?

**Comment by AmitN1212** [comment]
> @AmitN1212 , could you please help us and contribute?

I'll try.
Should I also add instructions for installing docker and docker-compose inside [it](https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/)?

It is necessary for it: 
> Probably need to run OpenPolicyAgent:
> 
> `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up cvat_opa`

**Comment by nmanovic** [comment]
@AmitN1212 , if you think it will make the tutorial better, let's do that. I will propose to insert links on official tutorials whenever it is possible. Otherwise it can be nightmare to keep it up to date.

**Comment by AmitN1212** [comment]
> @AmitN1212 , if you think it will make the tutorial better, let's do that. I will propose to insert links on official tutorials whenever it is possible. Otherwise it can be nightmare to keep it up to date.

Sure. Do you want me to change some more things that I think will make the instructions much clearer?

**Comment by g-kartik** [comment]
Another issue I faced when setting the development server is that UI was not able to find the server and returned 
![image](https://user-images.githubusercontent.com/83916067/147401290-4d530d36-f2eb-43b3-92be-b7a72c995c62.png)

![image](https://user-images.githubusercontent.com/83916067/147401306-d90da9f4-d6ad-48fb-b5f5-f19f0b4a6bd8.png)

![image](https://user-images.githubusercontent.com/83916067/147401312-f2d21829-ea87-4df0-a234-7dba30d75e26.png)

After I replaced localhost to 127.0.0.1, the UI was able to find the server
https://github.com/openvinotoolkit/cvat/blob/develop/cvat-ui/package.json#L8

I guess lookup from localhost to 127.0.0.1 is failing

**Comment by AmitN1212** [comment]
> Replacing localhost to 127.0.0.1 fixed the issue

@g-kartik I think you can fix it with running the ```server:chrome``` configuration in VSCode after you run ```server:debug``` so you don't need to change [this](https://github.com/openvinotoolkit/cvat/blob/develop/cvat-ui/package.json#L8).

**Comment by azhiv** [comment]
@g-kartik Downrading my Node v17 to smth like v12 fixed the issue for me, found the problem description [here](https://forum.dfinity.org/t/webpack-proxy-econnrefused-for-proxy-to-api/9263/2) (v16 should also work)

**Comment by sanjanaarora** [comment]
Hi I am trying to install CVAT on my Linux Machine have tried all the above said solutions but still not able to configure 
![docker-composr yml](https://user-images.githubusercontent.com/9069789/227130808-b7c710fc-e830-4ee4-b9bc-300b69df6ffe.png)
![docker ps](https://user-images.githubusercontent.com/9069789/227130817-ed8a2f94-9385-4bc3-989b-5fe9cf622ea8.png)
![Error after running cvat](https://user-images.githubusercontent.com/9069789/227130822-b8cac16b-29ab-4405-a1c7-7657172ff4bc.png)
![package json of cvat-ui](https://user-images.githubusercontent.com/9069789/227130825-eb003184-9683-40f9-a95e-5cfc9a00278b.png)
![server log](https://user-images.githubusercontent.com/9069789/227130827-1769a143-baea-4cde-9217-1ddb74ce9ab3.png)

**Comment by azhiv** [comment]
@sanjanaarora I don't remember the exact details, but this might be fixed by configuring a virtual network for the containers. In this way the connection will become available, this was my case.

**Comment by sanjanaarora** [comment]
@azhiv  If I run in the virtual Environment with "docker-compose up -d" it works fine but when I want to use it for development using
 docker run -d --rm --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.45.0-rootless \
 run --server --set=decision_logs.console=true --set=services.cvat.url=http://host.docker.internal:7000 \
 --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules

then it does'nt work
