### ISSUE TITLE
Does anyone use tfrecord file successfully? Why my tfrecord file exported from CVAT never work?

### ISSUE THREAD

**Issue by planetroger2020** [openvinotoolkit/cvat#4074]
RuntimeError: Did not find any input files matching the glob pattern ['/content/drive/MyDrive/OD_API/input_data/train.tfrecord']

I am not sure what is the problem. The tfrecord file I exported from CVAT can never be successfully trained.

**Comment by zhiltsov-max** [comment]
Hi, could you provide steps to reproduce the problem?

**Comment by planetroger2020** [comment]
> Hi, could you provide steps to reproduce the problem?

Thanks for your asking. This problem has been resolved, it is not a CVAT problem. I tried to label another data set, it can be trained normally.

**Comment by Kabalida271** [comment]
> > Hi, could you provide steps to reproduce the problem?
> 
> Thanks for your asking. This problem has been resolved, it is not a CVAT problem. I tried to annotate another images, they can be trained normally.

Hey. How did u resolved. I am getting the same error but unable to fix it. Can u help me out!

**Comment by hhhhhhehehe** [comment]
是路径问题吧
