### ISSUE TITLE
Running locally shows an error when openning the environement

### ISSUE THREAD

**Issue by nasiefk** [openvinotoolkit/cvat#4099]
Hi

I followed up the steps in the [documentation](https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/). However when I come to login page, I get the following error in a popup.

Can you please advise on this?

```
Could not check authorization on the server
Error: Request failed with status code 504. "Error occured while trying to proxy to: localhost:3000/api/v1/users/self?org=".
```

**Comment by AmitN1212** [comment]
> Hi
> 
> I followed up the steps in the [documentation](https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/). However when I come to login page, I get the following error in a popup.
> 
> Can you please advise on this?
> 
> ```
> Could not check authorization on the server
> Error: Request failed with status code 504. "Error occured while trying to proxy to: localhost:3000/api/v1/users/self?org=".
> ```

@nasiefk Try to run ```server:chrome``` after you run ```server:debug```.

**Comment by bsekachev** [comment]
@nasiefk 

Try this: https://github.com/openvinotoolkit/cvat/issues/4072#issuecomment-1000130984

**Comment by nasiefk** [comment]
@AmitN1212 I tried it but it did not work. @bsekachev I think it worked. Thanks guys.

Can you please update the documentation for contributing with this note?
