### ISSUE TITLE
Does support resize images when exporting?

### ISSUE THREAD

**Issue by shaojun** [openvinotoolkit/cvat#4106]
Hi, thanks for the great effort.

I'm using CVAT for labeling images for `object detection training`, the images I collected were from different channels, thus the sizes are **differ** (could be 1280x720, or 800x600 and etc.). While the training tool(expecting `KITTI` format data) requires dataset must have the same image size.

Does CVAT support this?

**Comment by nmanovic** [comment]
@shaojun , you can export your dataset and use https://github.com/openvinotoolkit/datumaro to transform your images (e.g. resize). Another approach is to transform images as necessary in your training code (pre-processing).

**Comment by shaojun** [comment]
@nmanovic thanks, I've played `datum` but got an [issue](https://github.com/openvinotoolkit/datumaro/issues/606), have you see this before?

**Comment by bsekachev** [comment]
Hi, 

If the issue is still relevant, better to ask in datumaro repository, thanks.
