### ISSUE TITLE
Support export balance dataset from imbalance source

### ISSUE THREAD

**Issue by shaojun** [openvinotoolkit/cvat#4107]
Hi, thanks for the great effort.

I'm using transfer learning for training an object detection model, the model convered 3 classes:

- people
- bicycle
- custom sign

the `people` and `bicycle` will get from public dataset like PASCAL VOC, which the amount is big, while the `custom sign` is a private dataset with very small amount, say **1000** images with a single label in each.

As the training tool requires a balance dataset for each class for achieve a good accuracy, so I'm planning import the full `PASCAL VOC` and `custom` dataset into 2 CVAT tasks （2 tasks are in **one** project), after labeled the `custom sign` data, when doing the export, I expect the exported (I prefer the format `KITTI`) dataset can achieve:

- limited classes
as `PASCAL VOC` has 20 classes, here I only want export `people`, `bicycle`, and plus `custom sign`
-  Balance distribution for that 3 classes
as `PASCAL VOC` has thousands data for each class, for balancing with `custom sign`, each class need to align with amount **1000**.

does the tool now support this?

**Comment by StellaASchlotter** [comment]
I use datumaro (https://github.com/openvinotoolkit/datumaro) for this usecase. It used to be a part of cvat and it is now it's own thing. You can download the tasks in one format, convert it to the format you want and remove classes you don't like. Balancing can be easily achieved by just sampling the annotations and removing the rest.

**Comment by shaojun** [comment]
@StellaASchlotter  thanks.

> Balancing can be easily achieved by just sampling the annotations and removing the rest.

could you specify more on this? is it by manual or?

**Comment by StellaASchlotter** [comment]
You could do it manually if you really want to. I was thinking more like this: https://github.com/openvinotoolkit/datumaro/issues/522

There is no command which does exactly want you want. But you can write a small script to achieve your goal. In the issue I linked there are some suggestions on how to get it working. 

It's also possible to not use datumaro or other libraries like that and write the code for it completly yourself.

**Comment by shaojun** [comment]
@StellaASchlotter thanks, besides datum, any other CLI or library you tried? could you recommend.
