### ISSUE TITLE
Integration of active learning with CVAT

### ISSUE THREAD

**Issue by anabia-alam** [openvinotoolkit/cvat#4115]
Hi, 
Does CVAT allow our own custom active learning integration with it? Is there any feature that allows in-house active learning to be built on top of it?

**Comment by nmanovic** [comment]
@anabia-alam , we are designing the feature at the moment. Do you have any specific requirements?

**Comment by anabia-alam** [comment]
My team is looking for annotation tools that can allow the incorporation of active learning. Given the build of CVAT, i wanted to know whether it allows integration of semi-automated labeling?

**Comment by nmanovic** [comment]
@anabia-alam , you can integration semi-automated labeling: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/. Also you always can upload generated annotations by your model. "Active learning" in my mind is something more advanced.

**Comment by anabia-alam** [comment]
Great thanks.

**Comment by doantientai** [comment]
Hi guys, is there any news on Active Learning?
