### ISSUE TITLE
401 Unauthorized 问题

### ISSUE THREAD

**Issue by liucong255** [openvinotoolkit/cvat#4121]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Current Behaviour
401 Unauthorized
analysis 403

### Steps to Reproduce (for bugs)

1.docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f components/serverless/docker-compose.serverless.yml -f components/analytics/docker-compose.analytics.yml up -d --build

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):Docker version 20.10.12
- Are you using Docker Swarm or Kubernetes?docker-compose
- Operating System and version (e.g. Linux, Windows, MacOS):ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
-https://github.com/openvinotoolkit/cvat/issues/4120
-https://github.com/openvinotoolkit/cvat/issues/4095
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container
    </details>
    `
[Thu Jan 06 08:24:12.768726 2022] [wsgi:error] [pid 545:tid 140418032420608] [remote 172.20.0.3:54956] WARNING - 2022-01-06 08:24:12,768 - log - Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:25:13.535091 2022] [wsgi:error] [pid 545:tid 140418040813312] [remote 172.20.0.3:55794] [2022-01-06 08:25:13,534] WARNING django.request: Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:25:13.535348 2022] [wsgi:error] [pid 545:tid 140418040813312] [remote 172.20.0.3:55794] WARNING - 2022-01-06 08:25:13,534 - log - Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:29:12.756417 2022] [wsgi:error] [pid 545:tid 140418049206016] [remote 172.20.0.3:58578] [2022-01-06 08:29:12,756] WARNING django.request: Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:29:12.756676 2022] [wsgi:error] [pid 545:tid 140418049206016] [remote 172.20.0.3:58578] WARNING - 2022-01-06 08:29:12,756 - log - Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:30:12.790443 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:59254] [2022-01-06 08:30:12,790] WARNING django.request: Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:30:12.790606 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:59254] WARNING - 2022-01-06 08:30:12,790 - log - Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:34:12.842466 2022] [wsgi:error] [pid 545:tid 140418049206016] [remote 172.20.0.3:33716] [2022-01-06 08:34:12,842] WARNING django.request: Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:34:12.842741 2022] [wsgi:error] [pid 545:tid 140418049206016] [remote 172.20.0.3:33716] WARNING - 2022-01-06 08:34:12,842 - log - Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:35:13.855855 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:34406] [2022-01-06 08:35:13,855] WARNING django.request: Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:35:13.856101 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:34406] WARNING - 2022-01-06 08:35:13,855 - log - Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:39:12.770764 2022] [wsgi:error] [pid 545:tid 140418049206016] [remote 172.20.0.3:37084] [2022-01-06 08:39:12,770] WARNING django.request: Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:39:12.771011 2022] [wsgi:error] [pid 545:tid 140418049206016] [remote 172.20.0.3:37084] WARNING - 2022-01-06 08:39:12,770 - log - Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:40:12.799817 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:37760] [2022-01-06 08:40:12,799] WARNING django.request: Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:40:12.800065 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:37760] WARNING - 2022-01-06 08:40:12,799 - log - Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:44:12.755567 2022] [wsgi:error] [pid 545:tid 140418040813312] [remote 172.20.0.3:40538] [2022-01-06 08:44:12,755] WARNING django.request: Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:44:12.755829 2022] [wsgi:error] [pid 545:tid 140418040813312] [remote 172.20.0.3:40538] WARNING - 2022-01-06 08:44:12,755 - log - Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:45:12.801825 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:41214] [2022-01-06 08:45:12,801] WARNING django.request: Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:45:12.802164 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:41214] WARNING - 2022-01-06 08:45:12,801 - log - Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:49:12.765462 2022] [wsgi:error] [pid 545:tid 140418040813312] [remote 172.20.0.3:43920] [2022-01-06 08:49:12,765] WARNING django.request: Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:49:12.765706 2022] [wsgi:error] [pid 545:tid 140418040813312] [remote 172.20.0.3:43920] WARNING - 2022-01-06 08:49:12,765 - log - Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:50:12.819877 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:44596] [2022-01-06 08:50:12,819] WARNING django.request: Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:50:12.820121 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:44596] WARNING - 2022-01-06 08:50:12,819 - log - Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:54:12.797304 2022] [wsgi:error] [pid 545:tid 140418057598720] [remote 172.20.0.3:47824] [2022-01-06 08:54:12,797] WARNING django.request: Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:54:12.797517 2022] [wsgi:error] [pid 545:tid 140418057598720] [remote 172.20.0.3:47824] WARNING - 2022-01-06 08:54:12,797 - log - Unauthorized: /api/v1/jobs/44/annotations
[Thu Jan 06 08:55:12.908960 2022] [wsgi:error] [pid 545:tid 140418040813312] [remote 172.20.0.3:48638] [2022-01-06 08:55:12,908] WARNING django.request: Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 08:55:12.909216 2022] [wsgi:error] [pid 545:tid 140418040813312] [remote 172.20.0.3:48638] WARNING - 2022-01-06 08:55:12,908 - log - Unauthorized: /api/v1/jobs/43/annotations
[Thu Jan 06 11:07:36.526480 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:35558] [2022-01-06 11:07:36,526] WARNING django.request: Unauthorized: /api/v1/users/self
[Thu Jan 06 11:07:36.526729 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:35558] WARNING - 2022-01-06 11:07:36,526 - log - Unauthorized: /api/v1/users/self
[Thu Jan 06 11:07:36.586095 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:35564] [2022-01-06 11:07:36,585] WARNING django.request: Unauthorized: /api/v1/auth/password/change
[Thu Jan 06 11:07:36.586357 2022] [wsgi:error] [pid 545:tid 140418024027904] [remote 172.20.0.3:35564] WARNING - 2022-01-06 11:07:36,585 - log - Unauthorized: /api/v1/auth/password/change
[Thu Jan 06 11:07:36.590021 2022] [wsgi:error] [pid 545:tid 140418057598720] [remote 172.20.0.3:35566] [2022-01-06 11:07:36,589] WARNING django.request: Unauthorized: /api/v1/auth/password/reset
[Thu Jan 06 11:07:36.590269 2022] [wsgi:error] [pid 545:tid 140418057598720] [remote 172.20.0.3:35566] WARNING - 2022-01-06 11:07:36,589 - log - Unauthorized: /api/v1/auth/password/reset
`

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
How is this issue different from the two mentioned issues (which appear to be different problems)?
