### ISSUE TITLE
Disabling Anti-Aliasing Modifier

### ISSUE THREAD

**Issue by mat48** [openvinotoolkit/cvat#4124]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I need to see the images in raw form without any modification when I zoom in and I'm working on pixel level 
(for example what you see in windows photo viewer when you zoom in)

### Current Behaviour
Right now CVAT uses an anti-aliasing modifier which smoothens the edges of every pixel

### Context
I don't know if this modifier is normal in other cases but I guess I'm gonna be able to annotate with higher precision if images are shown without any modification

### Your Environment

> Server version: 1.3
> Core version: 3.10.0
> Canvas version: 2.3.1
> UI version: 1.14.2

**Comment by nmanovic** [comment]
@mat48 , is `Smooth image` something you are looking for? https://openvinotoolkit.github.io/cvat/docs/manual/basics/settings/

**Comment by mat48** [comment]
Yes that's exactly what I was looking for. We'll upgrade CVAT to get that feature.
Thank you!

**Comment by EyescannerJE** [comment]
Hi @nmanovic I was also looking for `Smooth image` option but I can't see the option in the menu even thought I installed CVAT today by following the installation guide
