### ISSUE TITLE
Automically is spelled wrong ("automaticly") in export dataset modal

### ISSUE THREAD

**Issue by ZackMurry** [openvinotoolkit/cvat#4127]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When exporting a dataset, a modal should appear that states "Download will start _automatically_ as soon as the dataset is ready."

### Current Behaviour

When exporting a dataset, a modal should appear that states "Download will start _automaticly_ as soon as the dataset is ready."  
"Automatically" is spelled wrong in the current state.

### Possible Solution

Change "automaticly" to "automatically" in `cvat-ui/src/components/export-dataset/export-dataset-modal.tsx`.

### Steps to Reproduce (for bugs)

1. Create a task with a dataset
2. Click "Open" on the task
3. Open the "Actions" menu
4. Click "Export task dataset"
5. Click "Ok"
6. A modal will appear in the top-right corner of the screen with the misspelling

### Context

Obviously, this doesn't have a large impact. I am trying to fix a spelling error that I see.

### Your Environment

The live website, cvat.org.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Closed by the PR above
