### ISSUE TITLE
Installing CVAT: unable to find the IP address for the container \cvat

### ISSUE THREAD

**Issue by arasharchor** [openvinotoolkit/cvat#4130]
I am installing the v2.0.0-alpha version of cvat in my Ubuntu 16.04

The only changes I have made are: 
1) I have set the CVAT_HOST to the IP address of my machine `xxx.xxx.xxx.xxx`
2) changed all 8080 ports to 8088 as my 8080 port is already in use.

After executing the command `docker-compose -f docker-compose.yml up --build`  , I am getting the following error. 

traefik       | time="2022-01-09T23:51:29Z" level=error msg="service \"cvat\" error: unable to find the IP address for the container \"/cvat\": the server is ignored" providerName=docker container=cvat-cvat-fbcda30236d3385024e2d83db8b0ac06861095da56dfb001a79f338bcacd402f

when I run with `-d`, no errors shows up.
![image](https://user-images.githubusercontent.com/12903362/148706822-06b1c585-dc2f-48a0-ada4-b20c5023e41e.png)

CVAT website has loaded, but after running `docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'`, nothing shows up to enter a username and password.

**Comment by bsekachev** [comment]
Try this alternative:

```
If you don’t have winpty installed or the above command does not work, you may also try the following:

# enter docker image first
docker exec -it cvat /bin/bash
# then run
python3 ~/manage.py createsuperuser
```

**Comment by azhavoro** [comment]
You only need to change the port here https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.yml#L87 like 
```yml
      - 8088:8080
```
Does this solve the issue?

**Comment by arasharchor** [comment]
@bsekachev 
it does not enter the docker image
`Error response from daemon: Container e8a0fb8d1ddf82e1b6c65d6ec23f6713aa609a526b8897817c2c96798e94f56e is restarting, wait until the container is running
`

**Comment by arasharchor** [comment]
@bsekachev @azhavoro The problem is now solved. thanks!

**Comment by yustiks** [comment]
> Try this alternative:
> 
> ```
> If you don’t have winpty installed or the above command does not work, you may also try the following:
> 
> # enter docker image first
> docker exec -it cvat /bin/bash
> # then run
> python3 ~/manage.py createsuperuser
> ```

this solved the problem, but all my tasks and annotations have been deleted for now. Wtf?

**Comment by nmanovic** [comment]
@yustiks , the command cannot delete any annotations and tasks. It just creates a new user.

**Comment by ningjunwei2** [comment]
i meet  this problem too ， the cvat docker is always  Restarting

--------------------------------------------------
cvat_ui       | 2022/03/29 09:09:38 [notice] 1#1: start worker process 50
cvat_ui       | 2022/03/29 09:09:38 [emerg] 50#50: initgroups(nginx, 101) failed (14: Bad address)
cvat exited with code 2
traefik       | time="2022-03-29T09:19:39Z" level=error msg="service \"cvat\" error: unable to find the IP address for the container \"/cvat\": the server is ignored" providerName=docker container=cvat-cvat-f57b7f1ed0173b56733f513bebc191ba15ce075ea3d0f9a967a6fa144b9ee826
