### ISSUE TITLE
Rolling storage for supervisord.log

### ISSUE THREAD

**Issue by kbegiedza** [openvinotoolkit/cvat#4135]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context
After few weeks of working, new analytics' events are not saving properly due to:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 102, in emit
    self.stream.write(msg)
OSError: [Errno 28] No space left on device
```
I think for logs / analytics there should be some kind of rolling storage mechanism, but unfortunately I'm unable to find one.

Is there 'correct' way to handle this or I have to cron deletion?

### Your Environment
- https://github.com/Surveily/cvat
- Are you using Docker Swarm or Kubernetes? Kubernetes

**Comment by azhavoro** [comment]
This is already configured https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L13-L15

**Comment by kbegiedza** [comment]
Great! Didn't know about this setting.
Thank you @azhavoro
