### ISSUE TITLE
Can not see model tabs

### ISSUE THREAD

**Issue by CaRRotOne** [openvinotoolkit/cvat#4142]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I want to use interactors with bultin models

### Current Behaviour
I deployed builtin model f-brs with nuctl tool successfuly, but can not see the model tab. The version of CVAT is 1.5. Does 1.5 version support this function?

![image](https://user-images.githubusercontent.com/2860023/148921562-d79ed1a3-c88b-4cf9-ab32-be48262e8acd.png)
![image](https://user-images.githubusercontent.com/2860023/148921228-8d174f95-a690-4481-b5c9-5d9cdee7ae2c.png)

**Comment by bsekachev** [comment]
You need to deploy CVAT special way. Please, follow [this](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/) guide.

**Comment by CaRRotOne** [comment]
> You need to deploy CVAT special way. Please, follow [this](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/) guide.
thanks.,@bsekachev  it works.
