### ISSUE TITLE
Adjust the Image quality after task was created

### ISSUE THREAD

**Issue by shaojun** [openvinotoolkit/cvat#4148]
Hi thanks for this great tool.

I uploaded a 1080p video with nearly 2000 frames into a task with default `Image quality: 70`, I noticed when export it (for my case, into `kitti 1.0` format), the zip file size is over 2GB, the size is obvious too big for me.

my questions:

1. Does it support reduce the `Image quality` after the task was created, and annotation had been done?
2. Does it support export subset of images and annotations from a task or project for save some download time (say I want a quick export for a quick training, no full dataset is requried)?

**Comment by nmanovic** [comment]
@shaojun , when you export a dataset, it will include images in the original quality.

**Comment by shaojun** [comment]
@nmanovic  thanks, so there's no way to adjust (to lower) image quality once it get uploaded at creating task? 

also, I noticed for the non-annotation frames also get exported, is this the expected behavior?

**Comment by nmanovic** [comment]
@shaojun , you cannot. We guess that you are uploading us data which you are going to use for training. We don't have pre-processing pipeline at the moment.

It is expected that non-annotated frames are exported. Again, it can be an object which isn't implemented at the moment.

**Comment by nmanovic** [comment]
@shaojun , you can submit feature requests. I will close the issue.

**Comment by emmeduz** [comment]
Hi all,
a possible workaround to this problem would be to download only the annotations and then extract the corresponding frames from the mp4 files outside CVAT when needed. This is possible if we know how the frames are extracted by cvat to create the tasks.

Can someone link the exact command used to extract the frames?
