### ISSUE TITLE
Accessing cvat from server IP and using CLI

### ISSUE THREAD

**Issue by mrKallah** [openvinotoolkit/cvat#4156]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I want to be able to access CVAT from both localhost and from a server IP. The way we had it set up before the change from CVAT_HOST in the docker-compose file to the export CVAT_HOSTS in bash, was that we had both access through localhost and the server IP. This allowed multiple users to use CVAT while at the same time being accessible from the CLI, which we rely heavily on for managing tasks. This is no longer possible as I have been unsuccessful in finding a way to enable access through both localhost and server IP, as 

export CVAT_HOST=
                                   "localhost {Server IP}"
                                   ["localhost","{Server IP}"]
                                   "localhost, {Server IP}"
                                   "*"

neither of these options  seem to work. I have tried to find documentation on this subject but been unsuccessful

### Expected Behaviour
CLI can access server locally and users can access server

### Current Behaviour
Users can not access server at the same time as CLI, CLI gets error 404

### Possible Solution
Change export -> docker compose up -d -> do CLI stuff -> change export -> docker compose up -d -> users have access again 

### Steps to Reproduce (for bugs)
1. export CVAT_HOST="{Server IP}"
2. docker compose up -d
3. try to do something with CLI
4. get error

### Context

I can no longer use CLI as effectively as before the latest change

### Your Environment

- Git hash commit (`git log -1`): commit b5a9a0fbfd7957517db73098878e755e874da6bd (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
Error from cli
```
Traceback (most recent call last):
  File "cli.py", line 46, in <module>
    main()
  File "cli.py", line 36, in main
    cli = CLI(session, api, args.auth)
  File "/home/kallah/probotic/cvat/utils/cli/core/core.py", line 24, in __init__
    self.login(credentials)
  File "/home/kallah/probotic/cvat/utils/cli/core/core.py", line 272, in login
    response.raise_for_status()
  File "/home/kallah/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8080/api/v1/auth/login

```

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by mrKallah** [comment]
I have since posting this found the 
``` python
parser.add_argument(
    '--server-host',
    type=str,
    default='localhost',
    help='host (default: %(default)s)'
)
```
argument in the definitions.py, which I had not previously noticed. I would suggest adding this to the CLI documentation

**Comment by azhavoro** [comment]
Hello Lasse,
Have you tried this: https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-specify-multiple-hostnames ?

**Comment by mrKallah** [comment]
That worked, thanks!
