### ISSUE TITLE
Does it work with large ammount of images?

### ISSUE THREAD

**Issue by chenghan1995** [openvinotoolkit/cvat#4196]
Thanks a lot for this fantastic work first. I have one question. 
It says in README.md 'Limitations: No more than 10 tasks per user. Uploaded data is limited to 500Mb.'
So when I have Hundreds of thousands of images,the total size of uploaded data is 10GB-50GB, how can I use cvat to annotate my images?

**Comment by azhavoro** [comment]
Hi, this limitations are only applicable for cvat.org, in your case you need to deploy a local instance.

**Comment by chenghan1995** [comment]
Thanks a lot! How to deploy a local instance? Do you have any tutorial please?
I just learn Installation Guide in https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/. After the Installation Guide's work,  does it already use cvat.org? What should I do to deploy a local instance?
