### ISSUE TITLE
Connecting S3 with CVAT

### ISSUE THREAD

**Issue by anabia-alam** [openvinotoolkit/cvat#4197]
Is it possible to connect s3 storage with CVAT. My data is stored in cloud and i want to directly ingest images to CVAT. Kindly let me know if it is possible

**Comment by azhavoro** [comment]
https://openvinotoolkit.github.io/cvat/docs/manual/basics/attach-cloud-storage/
https://openvinotoolkit.github.io/cvat/docs/administration/advanced/mounting_cloud_storages/
