### ISSUE TITLE
How to create the superuser when deploying to AKS with the helm chart

### ISSUE THREAD

**Issue by petersgiles** [openvinotoolkit/cvat#4205]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

The [documentation](https://openvinotoolkit.github.io/cvat/docs/manual/basics/authorization/) discusses briefly how to create a superuser

```
  docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
```

How do I do this with a kubernettes cluster in the cloud?

### Current Behaviour

I can't work out how to make a superuser account

### Possible Solution

Improve documentation with a solution

### Steps to Reproduce (for bugs)

1. create AKS cluster
1. run the helm charts

### Context

I can't create projects or do any other privileged actions

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Azure 

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by petersgiles** [comment]
The answer (Please add to your documentation)

run get pods to get the names of the pods

```bash
kubectl get pods
```
The output will be something like this

| NAME | READY | STATUS | RESTARTS | AGE |
|---|---|---|---|---|
| cvat-backend-xxx | 1/1 | Running | 0 | 16h |
| cvat-frontend-xxx | 1/1 | Running | 0 | 16h |
| cvat-postgresql-0 | 1/1 | Running | 0 | 16h |
| cvat-redis-master-0 | 1/1 | Running | 0 | 16h |

```bash
kubectl exec -it "cvat-backend-xxx" -- /bin/sh
```
To get an interactive shell on the backend. Then run the createsuperuser script

```kubectl
python3 ~/manage.py createsuperuser
```

Hope this helps

**Comment by nmanovic** [comment]
@petersgiles , thanks for the issue. Could you please help us to improve documentation?
