### ISSUE TITLE
Add QA user option

### ISSUE THREAD

**Issue by NarenZen** [openvinotoolkit/cvat#4208]
Only admin can view all tasks and projects.

Only tasks assigned to the user, are visible to the user.

But what about QA users. If he wants to QA the tasks, he needs access to all tasks.

As of now, we have to make QA user as admin for visibility of all tasks

**Comment by bsekachev** [comment]
Hi @NarenZen 

You can create an organization and invite QA users there with 'maintainer' roles. They will see all the tasks and projects within the organization.

**Comment by NarenZen** [comment]
Ok., In that case, can you add the option to add project from personal workspace to organisation and vice-versa

**Comment by bsekachev** [comment]
We are going to do that. Please, follow #4202
