### ISSUE TITLE
[Q] Can we set default groups/permissions for new users that register via the front end?

### ISSUE THREAD

**Issue by alexander-soare** [openvinotoolkit/cvat#4224]
My actions before raising this issue
- [x] Read/searched the docs
- [x] Searched past issues

---

Right now, when users register themselves via the front end they end up in a null group. This are screen snips from the Django Admin page (first one to show the context)

![image](https://user-images.githubusercontent.com/16543381/150532605-930aade3-510b-4290-910d-eccdd2a9ae0a.png)

![image](https://user-images.githubusercontent.com/16543381/150532481-1cb70eea-e03d-48de-8b3e-56402737c4c2.png)

The only groups filters that show all the users are the "All" filter and the "-" filter.

My problem is that the users can instantly observe and annotate, without me having to allow it. Is there:

a) A way to make sure the users have no permissions by default?
b) A way to make a new group with no permissions and make sure that all new users start in that group until I change it?

### Your Environment

Git hash commit: f313a71
Docker version: 20.10.11
OS: Ubuntu Server 20.04 LTS

**Comment by nmanovic** [comment]
@alexander-soare , you need IAM feature which was merged by it wasn't released.
https://github.com/openvinotoolkit/cvat/pull/3788

**Comment by alexander-soare** [comment]
@nmanovic thanks for this.

> I will not recommend to run the version in production for now.

Any warnings in particular here?

**Comment by nmanovic** [comment]
@alexander-soare , it isn't well tested. Once it is deployed on cvat.org (which I hope will be done in a couple of weeks) and initial tests are merged (https://github.com/openvinotoolkit/cvat/pull/4090).

I will recommend to run it on a testing server and see if it works for you. Any feedback about the feature is valuable.

**Comment by alexander-soare** [comment]
Many thanks @nmanovic !
