### ISSUE TITLE
Faster way to export tasks datasets from Remotely Hosted CVAT server 

### ISSUE THREAD

**Issue by varungupta31** [openvinotoolkit/cvat#4227]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Export Task Datset on local machine, for multiple tasks using CLI, from a remotely hostel CVAT server.

### Current Behaviour

I tried following the [CLI Guide](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/cli/), and entered my (non-admin) credentials, in `--auth`, but I am getting a `KeyError:None`

### Steps to Reproduce (for bugs)

1. `cd cvat/utils/cli`
1. `python cli.py --auth <user>:<pass> --server-host <> --server-port 8080`

_(Most probably NOT a bug, but my lack of understanding - kindly explain if this is not meant to work this way)_

### Context
 
I'm connected to the remote CVAT server using a VPN, and have to export task dataset for each video tasks on my system manually. I'm looking for a faster way to export task datasets in COCO format for multiple tasks at once, using CLI.

**Comment by azhavoro** [comment]
> 2. `python cli.py --auth <user>:<pass> --server-host <> --server-port 8080`

Hi, please provide the full command you used.

**Comment by azhavoro** [comment]
No response for a long time
