### ISSUE TITLE
Cannot find KITTI format in label format list on localhost, while it exists on cvat.org

### ISSUE THREAD

**Issue by n-shubham** [openvinotoolkit/cvat#4234]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I see that the KITTI format has been added to the list of supported formats in the CVAT app. I can use this format successfully on the cvat.org web app.

### Current Behaviour
However, when I clone the repo and build it on my local Ubuntu system, I cannot find the KITTI entry in the menu on localhost:8080. 

![KITTI_CVAT](https://user-images.githubusercontent.com/98383716/150937858-66b38d7f-0021-4fb9-a2ae-bad702192927.png)

### Steps to Reproduce (for bugs)
Follow the installation steps for Ubuntu 18 on this page : 
[https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64)

### Context
I am trying to label a dataset in the KITTI format.

### Your Environment

I am on Ubuntu 20.04.3

I am on the following commit :

- Git hash commit (`git log -1`): commit e212d57136b6be9f961ddeada37bd07770635c54 (HEAD -> develop, origin/develop, origin/HEAD)

**Comment by hassan-mushtaq** [comment]
I am facing same issue... If you found any solution... Kindly Comment Here... If you found solution

**Comment by azhavoro** [comment]
Release 1.7 doesn't include this feature, you should build cvat images images yourself with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build` from the develop branch.

**Comment by n-shubham** [comment]
@azhavoro , I followed the steps you mentioned, but now I am unable to create a task due to the following error - 

![cvat_couldNotCreateTask](https://user-images.githubusercontent.com/98383716/151315032-fea33a69-0984-468f-8029-bc55a25539f6.png)

Could not find mention of this error anywhere. Is this related to a faulty upgrade process?

**Comment by azhavoro** [comment]
Try to clear browser cache and reload the page
