### ISSUE TITLE
Incorrect information in documentation and/or unexpected cli behavior on export

### ISSUE THREAD

**Issue by mrKallah** [openvinotoolkit/cvat#4244]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I'm going to say this is connected to #4119 and #4056 and @TOsmanov and @AetherBreeze 

When using command
```bash
python3 cli.py export --format "COCO 1.0" 267
```

I get the error
```bash
usage: cli.py export [-h] task_id filename
cli.py export: error: argument task_id: invalid int value: 'COCO 1.0'
```

even through the [Documetnation](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/cli/) says:

```bash
cli.py export --format "COCO 1.0" 136
```

There also seems to be no way to export without images?

### Expected Behaviour
Expect the documentation to be correct
Export without image to be possible

### Current Behaviour
Documentation is wrong
--format seems to be broken from my testing 
Export without image is not possible

### Possible Solution
export through web interface enables you to do all of the above

### Your Environment

- Git hash commit (`git log -1`): 5e431714863d4be44dc05ecd1b76c9c056658103
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.12
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by TOsmanov** [comment]
Hi @mrKallah,

There is an mistake in the documentation.
You can export task annotation without images using `cli.py dump`:
```
python3 cli.py dump --format "COCO 1.0" 267 annotation.tar
```

**Comment by mrKallah** [comment]
> Hi @mrKallah,
> 
> There is an mistake in the documentation. You can export task annotation without images using `cli.py dump`:
> 
> ```
> python3 cli.py dump --format "COCO 1.0" 267 annotation.tar
> ```


@TOsmanov 
I have it working now, thank you for your reply, just another suggestion, you have put annotation.tar but using for example 
```bash
tar -xf filename.tar
````
returns
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```
and if I do

```bash
mv filename.tar filename
file filename
```
that returns
```
Stabben - M2 - HD: Zip archive data, at least v2.0 to extract
```

So I'd say the likelihood is that the compression used is actually zip not tar, and the docs should probably be updated accordingly.

**Comment by mrKallah** [comment]
On second thought, maybe its zip because I am using YOLO and not COCO? If so maybe a list for the different ones?

**Comment by TOsmanov** [comment]
> On second thought, maybe its zip because I am using YOLO and not COCO? If so maybe a list for the different ones?

@mrKallah 
You're right, downloading the annotation must be in `zip` format, this is also relevant for the format `CVAT 1.1`
