### ISSUE TITLE
Version 2.0 official release date?

### ISSUE THREAD

**Issue by dshahrokhian** [openvinotoolkit/cvat#4254]
Hello! Was browsing through the release page, and the new features in version 2.0 look very lit! 
Any expected ETA for official release?

Thank you for this amazing tool!

**Comment by nmanovic** [comment]
@dshahrokhian , it will be released in Q1'22. Need time to test changes and polish REST API for v2.0. You are welcome to try the current develop version and share your feedback.

**Comment by MoBa90** [comment]
@nmanovic Thank you very much for the amazing tool. Is there any news regarding the release of CVAT 2.0?

**Comment by nmanovic** [comment]
@MoBa90 , the current plan is to release it at the end of next week with alpha version for REST API. It means that the release will be fully functional but we cannot still guarantee that REST API will not be changed in several next releases (don't guarantee backward compatibility).
