### ISSUE TITLE
COCO annotatation uploads falsely converts Rectangle Track (track_id) to Rectangle Shape

### ISSUE THREAD

**Issue by varungupta31** [openvinotoolkit/cvat#4260]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Uploaded Annotations file in `COCO 1.0` format having `track_id` in `attributes` section of annotation should show up on the CVAT GUI as `RECTANGLE TRACK` instead of `RECTANGLE SHAPE`

![image](https://user-images.githubusercontent.com/51288316/151699739-03555ec1-ec8e-49e6-b0d7-41aec3a95859.png)

### Current Behaviour

If we create a track using CVAT GUI, it shows it as `RECTANGLE TRACK` but if we upload a `COCO 1.0 JSON` file, it renders the Tracks as `Rectangle Shape`, not RECTANGLE TRACK (even though the JSON file has a mentioned `track_id` column with a track number)

![Track being rendered as Rectangle Shape](https://user-images.githubusercontent.com/51288316/151699577-daf73c87-86fd-4c83-a46b-d4f89eff6524.png)

### Steps to Reproduce (for bugs)

1. Upload a COCO 1.0 format JSON annotation file having track IDs.
1. Open the job on CVAT and visualize the tracks.
1. Tracks render as `Rectangle Shape` not `RECTANGLE TRACK`
 
### Context

I'm trying to automate the detections, so the annotation work speeds up (I'm aware there is an 'automatic annotation feature' now available in CVAT). I have trained a detector and used a tracker on my videos and created a JSON file using python in the EXACT same format as expected by COCO 1.0 format. Everything renders fine on the CVAT GUI (Detections, shape, boundary, etc.) but NOT the track ID. (As mentioned, `track_ID` changes to Rectangle Shape on CVAT GUI).

I also tried uploading files using `cli.py upload `method, but that lead to the same errors.

### Important Observation

**If I draw a `Rectangle Shape` and `Rectangle track`----> Download the COCO JSON file ------> Re-upload the JSON file, the `RECTANGLE TRACK` changes to `Rectangle Shape`. (And NO changes were made in the COCO JSON file!)**

But

**If I draw a `Rectangle Shape` and `Rectangle track`----> Download the MOTS format file ------> Re-upload the MOTS zip file, the `RECTANGLE TRACK` and `Rectangle Shape` are maintained as before (And NO changes were made in the files!)**

So, COCO uploads is having some issue, and is not able to handle the attribute `track_id` properly.

@azhavoro @nmanovic @bsekachev Please look into this and help me out, thank you.

**Comment by zhiltsov-max** [comment]
Hi, the original COCO format does not support tracks, nor attributes, it's both CVAT extensions. The MOTS format is developed for tracks, so it supports them natively. If you need to import tracks, I can recommend using a format that supports tracks - MOT, MOTS or CVAT for video (you can simplify exporting task using [Datumaro](https://openvinotoolkit.github.io/datumaro/docs/user-manual/supported_formats/)). Track Ids will not be kept in any case - CVAT assigns new ids to annotations on import.

**Comment by varungupta31** [comment]
@zhiltsov-max Thank you for the information. I will switch to the MOT format, and get my work done.
_(Keeping the issue open for a week, in case someone has an alternate workaround)_

**Comment by zhiltsov-max** [comment]
Also, take a look at format docs: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/

**Comment by zhiltsov-max** [comment]
Should be fixed by https://github.com/opencv/cvat/pull/6969
