### ISSUE TITLE
HTTPS not working because certificate has been revoked. TLS-ALPN-01.

### ISSUE THREAD

**Issue by Kucev** [openvinotoolkit/cvat#4261]
Hello everyone, on January 29, our ssl connection to CVAT stopped working.
We found out that this happened because the Let's Encrypt revoked 2.7m of certificates that were generated by the TLS-ALPN-01 method. Link: [https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449](https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449)

Now we are trying to figure out how to replace the certificate with a new one in the [traefik](https://traefik.io/blog/how-to-force-update-lets-encrypt-certificates/). If someone also faced the same problem, can you write how you fixed it?

**Comment by azhavoro** [comment]
Hi, did you tried to delete acme.json and restart traefik to issue new cert as described in the mentioned guide? acme.json is stored in the volume https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.https.yml#L30

**Comment by randyd12** [comment]
Hi,  I did try removing the acme.json and restarting.  It creates a new acme.json file, but there are no certificates.

Any ideas on what else to try?

Thanks
~Randy

**Comment by randyd12** [comment]
OK I figured it out... bottom line was firewall was blocking letsencrypt from doing its thing.  You must allow 80 and 443 ingress from any.  I knew that, but had a mistake in my firewall rule.

Anyway here are a few of the troubleshooting tips I wish I had from the get go.

To get the logs of traefik:
get the id of the docker by:  docker ps
using the docker id of traefik:  docker logs [id from above]

the logs showed me the error about "probably firewall"

So the solution ultimately was:
open firewall
delete acme.json   for me it is located at:  /var/lib/docker/volumes/cvat_cvat_letsencrypt/_data/acme.json

stop all cvat dockers:
docker-compose down

make sure variables set (with your values):
export CVAT_HOST=[your domain]
export ACME_EMAIL=[your email to register with letsencrypt]

restart docker (make sure you are in the folder where the yaml files are):
docker-compose -f docker-compose.yml -f docker-compose.https.yml up -d

Hope that helps someone.

~Randy

**Comment by azhavoro** [comment]
@randyd12 Thank you!

**Comment by nmanovic** [comment]
@TOsmanov , could you please add the scenario into documentation?

**Comment by TOsmanov** [comment]
> @TOsmanov , could you please add the scenario into documentation?

@nmanovic,  Yes, I will add
