### ISSUE TITLE
Deploying to AWS EC2 is not loading updated Typescript

### ISSUE THREAD

**Issue by nasiefk** [openvinotoolkit/cvat#4266]
Hi guys,

I just managed to install it on my EC2 instance. However, I did some changes on the typescript that I can't see. Moreover, when I open the chrome console, I don't see any javascript? 
Is there any settings or configuration I need to do??

**Comment by azhavoro** [comment]
You need to rebuild cvat images with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

**Comment by nasiefk** [comment]
Hi @azhavoro I actually tried this but it did not work. 

The case is that changes I did are only in typescript files, do I need to configure anything related to static files or anything else or maybe run `cvat_ui` by itself on my server?
