### ISSUE TITLE
Issue while using tool.

### ISSUE THREAD

**Issue by bhargav-sudo** [openvinotoolkit/cvat#4268]
Hi, Facing this issue while using the CVAT tool.

![Screenshot from 2022-02-01 11-39-26](https://user-images.githubusercontent.com/57169077/151921635-41feb4da-ae55-4d42-a11b-4f57f8a2702a.png)

**Comment by nmanovic** [comment]
@bhargav-sudo , could you please provide more details? I will close the issue. Try to fill the template. It is big, but information about CVAT version, your steps, how to reproduce is very critical to understand what is going on.

**Comment by bhargav-sudo** [comment]
Hi @nmanovic 

My CVAT version. 

Server version : 1.7 
Core version : 3.17.0
Canvas version : 2.8.0
UI version : 1.25.0 

I installed through the documentation of CVAT and created user too. After doing all these things. When I opened the tool it says the above error.

**Comment by rdutta1999** [comment]
I am facing the same issue. I am using the [Cvat web portal](https://cvat.org/) .

It was working fine yesterday, however, after I logged in today a few hours prior, I noticed multiple warnings (at the top-right of the page), all saying something along the lines of `reviewer object is removed`.

The layout of the Task details page has also changed.

- New categories in `Stage`: `validation`, `acceptance`.
- Gone is the `reviewer` column where we could add people to review the tasks.
- A new `State` column has been added.

Another important issue is, under `Assignee`, the old names are present but the respective individuals can't see the tasks on their Tasks page. I can't seem to assign other jobs to other people (other than myself). I type their username but I can't select their name (previously, typing the name caused them to appear in a dropdown sort of menu, and I could choose it).

**Comment by azhavoro** [comment]
> I am facing the same issue. I am using the [Cvat web portal](https://cvat.org/) .
> 
> It was working fine yesterday, however, after I logged in today a few hours prior, I noticed multiple warnings (at the top-right of the page), all saying something along the lines of `reviewer object is removed`.
> 
> The layout of the Task details page has also changed.
> 
> * New categories in `Stage`: `validation`, `acceptance`.
> * Gone is the `reviewer` column where we could add people to review the tasks.
> * A new `State` column has been added.
> 
> Another important issue is, under `Assignee`, the old names are present but the respective individuals can't see the tasks on their Tasks page. I can't seem to assign other jobs to other people (other than myself). I type their username but I can't select their name (previously, typing the name caused them to appear in a dropdown sort of menu, and I could choose it).

Please try to clear your browser cache and reload page

**Comment by rdutta1999** [comment]
> > I am facing the same issue. I am using the [Cvat web portal](https://cvat.org/) .
> > It was working fine yesterday, however, after I logged in today a few hours prior, I noticed multiple warnings (at the top-right of the page), all saying something along the lines of `reviewer object is removed`.
> > The layout of the Task details page has also changed.
> > 
> > * New categories in `Stage`: `validation`, `acceptance`.
> > * Gone is the `reviewer` column where we could add people to review the tasks.
> > * A new `State` column has been added.
> > 
> > Another important issue is, under `Assignee`, the old names are present but the respective individuals can't see the tasks on their Tasks page. I can't seem to assign other jobs to other people (other than myself). I type their username but I can't select their name (previously, typing the name caused them to appear in a dropdown sort of menu, and I could choose it).
> 
> Please try to clear your browser cache and reload page

Have cleared the cache and re-logged in, used incognito mode and even tried it on a different system - all show the same thing (and the issues mentioned above).

**Comment by nmanovic** [comment]
@rdutta1999 ,

1. `reviewer object is removed` can be fixed by clearing the browser cache. We are working to resolve the issue permanently in the future.
2. Stage/State now is the way to work with tasks. Your workers can change state (new, in progress, reject, completed). You or your supervisors can change stage and assign new workers. For example, your task in stage='annotation' and state='completed'. Somebody needs to change its stage on 'validation'. State will be set to 'new'.
3. Your assignees can see their jobs on `jobs` page. We introduced a new permissions system. On CVAT.org you cannot see other users. But you can create your own `organization` and it will fix the issue: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/organization/

**Comment by bhargav-sudo** [comment]
Hi guys, Is there any way that i can solve the above issue.

**Comment by nmanovic** [comment]
@bhargav-sudo , please send us logs

docker logs cvat > cvat_logs.txt

**Comment by bhargav-sudo** [comment]
Here it is. 
[cvat_logs.txt](https://github.com/openvinotoolkit/cvat/files/7977448/cvat_logs.txt)

**Comment by nmanovic** [comment]
I hope you don't have any useful data yet and it is first time when you install CVAT. Run commands below. They will delete your CVAT containers and corresponding volumes. After that they will start the latest develop branch.

```bash
docker-compose -f docker-compose.yml -f docker-compose.dev.yml down -v
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
```

**Comment by bhargav-sudo** [comment]
Yeah, data has been taken as back up. Will run this and let you know.

**Comment by nmanovic** [comment]
@bhargav-sudo , You cannot restore backup data for new version of CVAT. We change layout of DB, add/remove new fields. You should restore your DB exactly for the same version of CVAT. After that you can upgrade CVAT. Data will be migrated automatically during the process.

**Comment by nmanovic** [comment]
@azhavoro , your guess was right. Probably need to add a warning into corresponding page.

**Comment by bhargav-sudo** [comment]
Yeah no issues.

**Comment by bhargav-sudo** [comment]
It throws this error.
[cat_logs.txt](https://github.com/openvinotoolkit/cvat/files/7977643/cat_logs.txt)

WARNING: The no_proxy variable is not set. Defaulting to a blank string.
Building cvat
The command '/bin/sh -c DATUMARO_HEADLESS=1 python3 -m pip install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt' returned a non-zero code: 2
ERROR: Service 'cvat' failed to build : Build failed

**Comment by nmanovic** [comment]
@bhargav-sudo , some problems with network on your side.

```
 File "/opt/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
[0m
```

**Comment by bhargav-sudo** [comment]
Ok. Thanks I will try later. Regarding DB storage. Don't worry this is the first installation in this machine..

**Comment by bhargav-sudo** [comment]
Hi. @nmanovic it works. Thanks for the quick help.
