### ISSUE TITLE
Pixels are not displayed as square 

### ISSUE THREAD

**Issue by EyescannerJE** [openvinotoolkit/cvat#4291]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Pixels should be square (same width and height).

### Current Behaviour

The video I'm annotating is stretchered horizontally (see image). Both ellipses are perfect circles but they don't look like they are. The annotated objects are pupils and irises and they are close to perfect circles (the pupil is not so clear in the image).  
![Screenshot from 2022-02-04 15-20-00](https://user-images.githubusercontent.com/97439533/152544797-b824a823-b29b-4b0d-a318-2a5a5b67dac9.png)

### Context

I'm trying to annotate ellipses that in most cases (not all) are perfect circles.
However even thought the box surrounding the ellipse has the same height as width it does not appear like that.
And I can see that the pixels are rectangles, not squares. 
**NOTE:** VLC plays the video in correct aspect ratio 

### Your Environment

- Git hash commit (`git log -1`): 71dfd51be187ff23e66c716c439a86d2a3c1394e (Added missed migration, fixed couple of minor issues with job state (#4274))
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 20.10.12, build e91ed57
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hi, I see square pixels in the image, am I missing something?
Could you share any media data to help us reproduce the issue?

**Comment by EyescannerJE** [comment]
Hi @azhavoro it is a lite hard to see but if you look closely on a single pixel in the screenshot you can see that it is actually not square, it is wider than it is high. To make it clearer I add another screenshot here where you can see the dimensions of the ellipse (which should appear as a perfect circle). In the original movie this ellipse is 62 pixels wide and 62 pixels high, i.e. a circle. CVAT correctly says this too while drawing but it does not display it like that (from a quick look it is obvious that it is wider than high)
![Screenshot from 2022-02-11 10-49-35](https://user-images.githubusercontent.com/97439533/153571138-7d377897-5f8b-4b63-b5fd-84cb4dec71f2.png)

**Comment by azhavoro** [comment]
Could you draw a perfect circle with non-black color in any image editor on your screenshot to see difference?

**Comment by EyescannerJE** [comment]
Hi @azhavoro, I feel like an idiot now. There is nothing wrong with CVAT, I have two monitors and one had incorrect settings which caused the stretched image. Thank you for your help
