### ISSUE TITLE
How do you import data?

### ISSUE THREAD

**Issue by kimlia545** [openvinotoolkit/cvat#4293]
### My actions before raising this issue
- [ ✓ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ✓ ] Searched [past issues](/issues)

I exported task dataset(format cvat for images 1.1)
And I'm going to import that data to another project.
What should I do?

### Expected Behaviour
![image](https://user-images.githubusercontent.com/72369991/152644775-62247314-200d-466c-a82c-7959b53ff9b6.png)
There is no problem with "Export task" and import data to another projtect.
But "Export task dataset" I get an error.

### Current Behaviour
![image](https://user-images.githubusercontent.com/72369991/152644802-64943ad4-ae36-4eec-a1c5-246530288884.png)

### Possible Solution
File format conversion?

### Steps to Reproduce (for bugs)
1.  Page(Task) click(Actions)
1. "Export dataset" dataformat 
![image](https://user-images.githubusercontent.com/72369991/152645385-e65d2da3-cc75-417e-a109-322d0ca38c0e.png)
1. dowmload custom Dataset
1. click(Import Task) import custom Dataset

### Context
It's hard to give data to other users.

### Your Environment
ubuntu docker 
- Git hash commit (`git log -1`):
- Docker version `docker version` : newer
- Are you using Docker Swarm or Kubernetes?
- Operating System and version Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hi, there are different features:
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/export-import-datasets/
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/backup/
You cannot use a zip produced by `Export task dataset` with backup/create from backup (export/import a task before renaming).

**Comment by someq** [comment]
For those who found this in google, links in the previous comments are broken. Replace `openvinotoolkit` in them to `opencv` to get actual docs pages.
https://opencv.github.io/cvat/docs/manual/advanced/export-import-datasets/
https://opencv.github.io/cvat/docs/manual/advanced/backup/

Also, do I correctly understand that `backup/create from backup` and `export/import` are different versions of the same feature, and the `export/import` is newer?

**Comment by nmanovic** [comment]
@someq , Backup and import/export are different features.
