### ISSUE TITLE
Assignment problems

### ISSUE THREAD

**Issue by OllegShevchenko** [openvinotoolkit/cvat#4296]
Hello!
Can't assign tasks to another user after cvat update
Task in my "Project". The user should only open the  task that I assigned

Please explain, perhaps there is another mechanism for assigning tasks
Thanks :-)
![image (1)](https://user-images.githubusercontent.com/98515844/152762572-6a86ad7e-6aed-40ba-beb3-40a01dccd18c.png)

**Comment by nmanovic** [comment]
@OllegShevchenko , are you trying to assign a task/job on cvat.org? If so, by default regular users cannot see other users. But you can create an organization and invite users for collaboration: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/organization/

@azhavoro , could you please add the question in FAQ?

**Comment by OllegShevchenko** [comment]
thanks a lot
it really helped
