### ISSUE TITLE
Is it possible to rotate the polygon after copy and paste?

### ISSUE THREAD

**Issue by davodogster** [openvinotoolkit/cvat#4298]
The copy paste feature is great - from one frame to another. But if the camera moves I need to rotate the polygon aswell (after pasting it). Is this possible in CVAT? 

You know when you drag an image into Microsoft PPT, and you are able to rotate it as much as you want.

Thanks,
Sam

**Comment by bsekachev** [comment]
Hi, rotation feature was implemented only for bounding boxes and ellipses, so, you can not rotate polygons for now.

**Comment by bsekachev** [comment]
I will close the issue, if you have any more questions, do not hesitate to reopen. If you with to support polygon rotation in CVAT, please submit a new issue and describe your use case in details, provide screenshots, etc.
