### ISSUE TITLE
Is CVAT HIPAA compliant?

### ISSUE THREAD

**Issue by RAbraham** [openvinotoolkit/cvat#4302]
Hi,
I think CVAT is HIPAA compliant but I just wanted to confirm.

https://en.wikipedia.org/wiki/Health_Insurance_Portability_and_Accountability_Act

**Comment by nmanovic** [comment]
@RAbraham , CVAT doesn't have any certificates in the area. Our team is following Intel guidelines to develop open source software. It includes different practices, static and dynamic scans, SDL, protex, etc.

I will close the issue.
