### ISSUE TITLE
Manifest file not found when creating a task

### ISSUE THREAD

**Issue by dre2004** [openvinotoolkit/cvat#4309]
### Expected Behaviour
When creating a new task using Cloud storage I was expecting to be able to select the Cloud storage (s3 bucket) and manifest file to create a task.

### Current Behaviour
I attempt to create a task but when I select the Cloud storage and manifest and submit the task it fails with the following error.

"Could not create the task. Error: Could not create the task on the server. Exception: A manifest file not found."

### Steps to Reproduce (for bugs)
- Create the cloud storage (s3 bucket) and type in the name of the manifest file.
- Create a create a new task, specify the name, project and Cloud storage as the source.
- Select the manifest file and tick all the images defined in that manifest.
- Click submit and I get a popup error saying "Could not create the task. Error: Could not create the task on the server. Exception: A manifest file not found."
- I can confirm the file exists in the S3 bucket (aws s3 ls <bucketname/filename>)

### Context
This is the first time I'm using CVAT so I'm not sure if its something I'm missing or a bug. I've created the manifest with the same format outlined [in the documentation](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/dataset_manifest/). I created a small manifest by hand as the utility to create manifest would require me to download the files locally (doesn't generate from an s3 bucket) and it doesn't handle images that are broken (reading the image with Pillow can fail).

### Your Environment

- Git hash commit (`git log -1`): openvino/cvat_ui:latest (2b45ff0ccf48)
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.7
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux - Amazon Linux 2

**Comment by dre2004** [comment]
Managed to fix this myself, I believe the issue was with the manifest file. I updated the create.py file under utils locally so it would handle exceptions with pillow Image opening files.

**Comment by ztyree42** [comment]
@dre2004 do you mind outlining what _exactly_ was the issue with your manifest file and how you fixed it for other people who are experiencing this problem?

**Comment by m-ali-awan** [comment]
Hi @dre2004, hope you are fine.
I am also facing almost the same issue.
### Context:
Right now, I have CVAT server, running on an EC2 instance. I am able to create users, and also annotate and export. 
**Desired Behavior: When I create a new task, I want to have the option of selecting images from an s3 bucket.** For now, I am shown no mounted storage, and when I select s3, I provide bucket-name, access/secret access keys, but it is asking me for a manifest file. I don't know, what does it mean, as all I want is to have the ability to select images(as I can select **From Computer**), so how can I provide Manifest file(Infact, I don't know, what manifest file would be)..

Moreover, also ,right now, I create a task, using a TestUser, I created, and labelled it. But in my **superuser** dashboard, I was not able to see that task, so I cannot download the annotation using SuperUser account..

Kindly help me with this, 

Thanks, a lot..

**Comment by m-ali-awan** [comment]
Also, kindly suggest me what instance type, and EBS storage would be enough. 
I am planning to have around 5 labellers, but my data is huge, can be around 1TB, but I think, once I have s3 mounted, I can create tasks in chunks(e.g in chunks of few hundred images)....

Thanks

**Comment by muzik999** [comment]
@m-ali-awan please follow the instructions in the below link 
[cvat documentation ](https://opencv.github.io/cvat/docs/manual/advanced/dataset_manifest/)

you can save the manifest on the s3 bucket where your images reside. Manifest file will be created on your system locally. 
Make sure that the local folder structure for images and that on the s3 bucket MATCHES.
