### ISSUE TITLE
I can't assign task to annotators in CVAT, Why it's so? 

### ISSUE THREAD

**Issue by shajahanpc** [openvinotoolkit/cvat#4313]
I have created an account in CVAT online tool and added one project. I'm not able to assign that to my team members, Usually, I do that, But the last few days I'm getting this issue.

- I have tested with some other accounts too, But it is the same
- I'm using the admin account and normally I allocated task to others from this account

Can anybody help me out?

**Comment by naufalahnaf17** [comment]
1. Make sure you have organization first (default is personal space)
2. I assume you have a team that have CVAT account too, so you can invite them via email
3. You can find this on settings -> organization -> create If you don't have any -> back to setting again now you just invite your team to your organization

**Comment by naufalahnaf17** [comment]
![Screenshot from 2022-02-10 11-44-45](https://user-images.githubusercontent.com/49228747/153338771-b06f647b-c921-45a9-b764-09bdb2a0ea4a.png)

here I drop a screenshot hope this help solve your problem, i use this online too and no problem at all

**Comment by naufalahnaf17** [comment]
![Screenshot from 2022-02-10 11-56-17](https://user-images.githubusercontent.com/49228747/153339984-b0237e5d-0105-41a7-bbe2-4a5b964b8577.png)

like i said , no problem at all

**Comment by shajahanpc** [comment]
naufalahnaf17 Thanks a lot for the help. I just created an organization and invited members too But I got another issue When I create a project. it shows you don't have permission. also showing a warning message. Will you help me out?

**Comment by shajahanpc** [comment]
![warning](https://user-images.githubusercontent.com/94048053/153341790-16bce569-e70e-4026-8da6-bab6c9a75cf4.jpg)

**Comment by naufalahnaf17** [comment]
![Screenshot from 2022-02-10 13-37-25](https://user-images.githubusercontent.com/49228747/153351500-9dc4ff3f-93dd-43ea-9158-ae1e8775cc05.png)
![Screenshot from 2022-02-10 13-38-09](https://user-images.githubusercontent.com/49228747/153351503-f22923ef-7c87-423c-9ab3-edeb2102678a.png)


make sure at least you are a maintainer on role organization, and creating new projects is not a problem anymore.

if my answer work like you expected, you can close this issue thank you

**Comment by shajahanpc** [comment]
@naufalahnaf17 Thanks!  for the help, yes it is worked well
