### ISSUE TITLE
Development environment can not "python manage.py migrate"

### ISSUE THREAD

**Issue by jenhaoyang** [openvinotoolkit/cvat#4314]
OS:Ubuntu20.04
Python:3.8.10
following the step from [here](https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/) will have the following error with "python manage.py migrate" command
```
ImportError: cannot import name '_registerMatType' from 'cv2.cv2' 
```

according to this thread  
https://stackoverflow.com/a/70538761/3079247
will solve the issue but not sure other dependency will be affect

https://github.com/openvinotoolkit/cvat/blob/696e51fe2e6b309eec90f9db9c0da77a92484255/cvat/requirements/base.txt#L35

**Comment by naufalahnaf17** [comment]
just do this : 
pip uninstall opencv-python-headless==4.4.0.42 

then do this 
pip install opencv-python-headless

"python manage.py migrate" now working fine

**Comment by jenhaoyang** [comment]
should I make a pull request to update the opencv-python-headless?

**Comment by naufalahnaf17** [comment]
I think in the future the contributor will update it soon, if my answer works like you expected you can close the issue 

thank you
