### ISSUE TITLE
Worker can finish a job without the required permissions

### ISSUE THREAD

**Issue by bseres99** [openvinotoolkit/cvat#4323]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The worker (annotator) can't finish a job with the "Finish the job" button, since that would skip the validation stage completely.

### Current Behaviour

The worker can press the "Finish the job" button, and the job is put into the acceptance stage and the completed stage. This skips the validation stage, and if this job is the only one in the task, then the task shows that it is completed. 

### Possible Solution

The stage and state modification permission should be implemented on the iam/opa side.

### Steps to Reproduce (for bugs)

1. Create an organization
2. Create a task in the organization
3. Assign the job to a worker
4. With the worker, open the job and press the "Finish the job" button on the annotation topbar

### Your Environment

- Git hash commit (`git log -1`): 237f98d5f834af3f752aa001ff95457701a311e5
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 20.10.11
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Other diagnostic information / logs:
    - cvat_opa - doesn't log any incoming policy requests
    - cvat - doesn't show any errors

**Comment by nmanovic** [comment]
@bseres99 , thanks for the contribution! The fix looks right. Also please remove `TODO: ` comments. It is already documented here: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/jobs.csv
