### ISSUE TITLE
Previous added annotators lose access to tasks and cannot add new annotators to the task

### ISSUE THREAD

**Issue by JanineCHEN** [openvinotoolkit/cvat#4338]
Any help would be very much appreciated.

**Comment by JanineCHEN** [comment]
> Hi, it is because of huge reworking of CVAT permission system.
> Now to share a set of resources (tasks, projects, cloud storages, etc) with your annotation team, you should create an organization and invite your team members there. Please, refer to user guide: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/organization/
> All newly created resources will be available to all supervisors, assigned resources to corresponding workers. To move tasks/projects to a new organization need to wait a bit while this PR #4336 is merged and the server updated (if we are talking about cvat.org). There is a workaround, you can backup your tasks/projects and restore them within the organization.

Thanks a lot for your detailed response. Do we have an estimated date on which the server update will be finished? If soon enough I will wait, otherwise I will try the workaround. Thank you!

**Comment by bsekachev** [comment]
I think it will be the nearest Monday/Tuesday after the PR above is merged. Probably next week.

**Comment by JanineCHEN** [comment]
> I think it will be the nearest Monday/Tuesday after the PR above is merged. Probably next week.

Thank you very much indeed!
