### ISSUE TITLE
Vulnerability Tracking

### ISSUE THREAD

**Issue by devilsgrin** [openvinotoolkit/cvat#4348]
Hi. I've identified a critical security vulnerability that affects the latest version of cvat but I couldn't find where to report it.

Do you have any vulnerability tracking program? How and where can I report the vulnerability to help make cvat more secure?

**Comment by ZaibanAli** [comment]
@devilsgrin can you please explain the vulnerability in more detail? so whoever deployed the cvat on the server can make the patch.

**Comment by nmanovic** [comment]
@devilsgrin , you can send a mail to me. Also you can prepare a PR to close it.

**Comment by devilsgrin** [comment]
Hi @nmanovic, I sent you an email about vulnerability. Thanks.
