### ISSUE TITLE
400 Client Error: Bad Request for url: http://x.x.x.x:8080/api/v1/tasks/3928/annotations?format=CVAT%20for%20video%201.1

### ISSUE THREAD

**Issue by Jakubelo** [openvinotoolkit/cvat#4359]
### My actions before raising this issue
I tried to upload data (mp4) with annotations (CVAT for video 1.1) zipped with XML, using CLI. I prepare data and annotations to upload, like this one from dumped XML from a task from the same project.

### Expected Behaviour
Correct creation of task with annotations

### Current Behaviour
The task is created but there are no boxes from annots file.
I only see info in the terminal:
```
Created task ID: 3926 NAME: foo
Awaiting data compression before uploading annotations...
Awaiting compression for task 3926.
                            Status=Finished, Message=
400 Client Error: Bad Request for url: http://boo:8080/api/v1/tasks/3926/annotations?format=CVAT%20for%20video%201.1
```

### Steps to Reproduce (for bugs)

example of XML:
```
<?xml version="1.0" encoding="utf-8"?>
<annotations><version>1.1</version><meta><task><id></id><name></name><size></size><mode>interpolation</mode><overlap>5</overlap><bugtracker></bugtracker><created></created><updated></updated><subset>default</subset><start_frame></start_frame><stop_frame></stop_frame><frame_filter></frame_filter><segments><segment><id></id><start></start><stop></stop><url></url></segment></segments><owner><username>admin</username><email></email></owner><assignee></assignee><labels><label><name>doors</name><color>#ffcc33</color><attributes></attributes></label><label><name>head</name><color>#24b353</color><attributes><attribute><name>location</name><mutable>True</mutable><input_type>select</input_type><default_value>in</default_value><values>in
out</values></attribute></attributes></label></labels><original_size><width>700</width><height>1000</height></original_size></task><dumped></dumped><source>left_top1.mp4</source></meta><track id="1" label="head" source="manual"><box frame="1" outside="0" occluded="0" keyframe="1" xtl="360" ytl="910" xbr="455" ybr="810" z_order="0"><attribute name="location">in</attribute></box><box frame="2" outside="0" occluded="0" keyframe="1" xtl="362" ytl="909" xbr="455" ybr="811" z_order="0"><attribute name="location">in</attribute></box> 
...
```
Sorry for lack of proper indentation, but I used xmltodict lib to overwrite the values and I get it back in this form.

### Your Environment

- Git hash commit (`git log -1`): c996683d56111c861f192f9f7bcd5085e2cc16c5
- Docker version `docker version` (e.g. Docker 17.0.05): 
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Linux ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by azhavoro** [comment]
Please provide logs from cvat container: `docker logs cvat > cvat_log.txt`

**Comment by Jakubelo** [comment]
I upload only last ~30min-1h range, due to the logs are pretty large and I have an error when trying to dump them.

[cvat_log.txt](https://github.com/openvinotoolkit/cvat/files/8096388/cvat_log.txt)

**Comment by Jakubelo** [comment]
When I upload the same vid to ui and then upload annotations by hand(on UI), the annotations are uploaded properly.

**Comment by Jakubelo** [comment]
I figured out, that I badly specified the format. To upload annots you cannot use "CVAT for video 1.1" or "images 1.1", you have to describe the format as "CVAT 1.1"

**Comment by azhavoro** [comment]
Thanks for the investigation, so I suppose the issue can be closed.
