### ISSUE TITLE
In the api doc, the 'dimension' attribute of the /api/projects endpoint (post,patch) is marked as writable.

### ISSUE THREAD

**Issue by k1won** [openvinotoolkit/cvat#4367]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The 'dimension' attribute of the /api/projects endpoint (post,patch) should be marked as "readOnly: true" or excluded in the request body schema section.
### Current Behaviour

In the api document, the 'dimension' attribute of the /api/projects endpoint (post,patch) is marked as writable.
According to the implementation of the ProjectSerializer class, the 'dimension' field is a read_only field, so I think it should be marked as "readOnly: true" in the api document or excluded from the schema of the request body.
It seems to be due to the characteristic that the read_only_fields Meta option is not referred to in the case of fields explicitly declared in the ModelSerializer.
https://stackoverflow.com/questions/68946823/django-drf-read-only-fields-not-working-properly

<img src="https://user-images.githubusercontent.com/12894869/154840393-a8437fd7-725f-4c88-9025-8f925e709660.png" width="300" height="300">

### Possible Solution

Explicitly add "read_only=True" to the 'dimension' declaration code of the ProjectSerializer class.
After modifying the code in the local development environment, I've checked that the changes are as expected as shown below. (Request and Response)
<img src="https://user-images.githubusercontent.com/12894869/154840622-98741c91-12da-431f-b6f6-f411cd4400f5.png" width="300" height="300"> <img src="https://user-images.githubusercontent.com/12894869/154840653-71131dba-08d4-4117-bc53-7c1697339f13.png" width="300" height="400">

### Steps to Reproduce (for bugs)

1. check the swagger api document (POST /api/projects)
1.

### Your Environment

- Git hash commit (`git log -1`): c52c65ce
- Docker version `docker version` (e.g. Docker 17.0.05): 
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@k1won , thanks for the report. Please let us know if you can send us a PR with the fix.

**Comment by k1won** [comment]
> @k1won , thanks for the report. Please let us know if you can send us a PR with the fix.

I've already sent a PR to fix this.
thanks.
