### ISSUE TITLE
Automatic Annotation not working in Online cvat tool.

### ISSUE THREAD

**Issue by rahulsharma11** [openvinotoolkit/cvat#4372]
### My actions before raising this issue
- [*] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [*] Searched [past issues](/issues)

I am using online cvat tool, after creating the task i am not able to do Automatic annotation. It says Permission Denied.

### Context

I am using this tool for my project for training a model. I need Person to be automatic annotated as there is a large data for the same.
I know a user can create 10 tasks and it was already working for my previous 8 tasks.(Automatic annotation was working). I deleted few tasks and created the new one but this time Automatic Annotation for any model like Yolo/RCNN is not working.

### Your Environment

- Git hash commit (`git log -1`): Online tool so not using
- Docker version `docker version` (e.g. Docker 17.0.05): Not using
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem: Not there

Thanks.

**Comment by nmanovic** [comment]
@rahulsharma11 , unfortunately we don't allow run long running tasks on cvat.org anymore. You can annotate frame by frame using AI tools. You always can run CVAT on your local machine and use as many computing resources as you have.
