### ISSUE TITLE
Filter images by open issues

### ISSUE THREAD

**Issue by mlenarsic** [openvinotoolkit/cvat#4381]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

In our use case we would like to filter images by issues. After the reviewer adds the issues to a job, the annotator would like to navigate quickly through only the images that have open issues.

From playing around with the UI and reading the documentation that currently does not seem to be possible.

### Possible Solution
Possibly adding "issue" option to the rules in the filter modal or an arrow like button that cycles only through images with open issues.

**Comment by bsekachev** [comment]
Hi @mlenarsic 

There is ability to navigate between frames with issues (but it navigates even through closed issues, nevertheless might be helpful for you):
![image](https://user-images.githubusercontent.com/40690378/155488850-0672d9ba-d78d-43c4-8282-085bed6d011c.png)
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/review/

**Comment by mlenarsic** [comment]
Oh great I was focusing on getting it work with the filters and completely missed this part of the documentation somehow. This covers our requirements nicely. Thank you!
