### ISSUE TITLE
Could not check authorization on the server.

### ISSUE THREAD

**Issue by csf-123** [openvinotoolkit/cvat#4388]
When I build CVAT on centos7, I have a problem. docker starts without errors. When I open the login screen and when I open the register account button. This question appeared on the page.

![image](https://user-images.githubusercontent.com/60735331/155695218-626ea970-db74-4469-9c2f-6f9d51a390ea.png)
![image](https://user-images.githubusercontent.com/60735331/155695963-79d358c0-9916-4652-9b53-a4055b8928e4.png)
![image](https://user-images.githubusercontent.com/60735331/155696176-a32ef6ee-d1e6-4a29-92e5-dda68547e5f8.png)

I've just been working in IT for a while and it's possible that some operational error caused this problem. But no errors were encountered during the build process. Looking forward and thank you for your answer.

`
version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data
    networks:
      - cvat

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    restart: always
    networks:
      - cvat

  cvat:
    container_name: cvat
    image: openvino/cvat_server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      ADAPTIVE_AUTO_ANNOTATION: 'false'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat.loadbalancer.server.port=8080
      - traefik.http.routers.cvat.rule=Host(`${CVAT_HOST:-localhost}`) &&
        PathPrefix(`/api/`, `/git/`, `/opencv/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)
      - traefik.http.routers.cvat.entrypoints=web
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_ui:
    container_name: cvat_ui
    image: openvino/cvat_ui
    restart: always
    depends_on:
      - cvat
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat-ui.loadbalancer.server.port=80
      - traefik.http.routers.cvat-ui.rule=Host(`${CVAT_HOST:-localhost}`)
      - traefik.http.routers.cvat-ui.entrypoints=web
    networks:
      - cvat
    ports: 
      - 8999:80
  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: always
    command:
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=cvat'
      - '--entryPoints.web.address=:8080'
      - '--providers.file.directory=/etc/traefik/rules'
    # Uncomment to get Traefik dashboard
    #   - "--entryPoints.dashboard.address=:8090"
    #   - "--api.dashboard=true"
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.dashboard.entrypoints=dashboard
    #   - traefik.http.routers.dashboard.service=api@internal
    #   - traefik.http.routers.dashboard.rule=Host(`${CVAT_HOST:-localhost}`)
    ports:
      - 8011:8011
      - 8091:8091
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - cvat

  cvat_opa:
    container_name: cvat_opa
    image: openpolicyagent/opa:0.34.2-rootless
    restart: always
    networks:
      cvat:
        aliases:
          - opa
    volumes:
      - ./cvat/apps/iam/rules:/rules
    ports:
      - '8181:8181'
    command: run --server --addr :8181 --set=decision_logs.console=true /rules

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:

networks:
  cvat:`

![image](https://user-images.githubusercontent.com/60735331/155699639-b9e1fc19-75c6-4918-a5a1-1cb96301e7f8.png)
![image](https://user-images.githubusercontent.com/60735331/155700898-c4d10a67-e666-41fe-be20-42bd58bb0593.png)
![image](https://user-images.githubusercontent.com/60735331/155700939-8fde6d00-ecd9-42fc-be12-7b5c68bcfcd8.png)
![image](https://user-images.githubusercontent.com/60735331/155700973-e99f0bb6-d44b-40b8-8e69-178ad679f985.png)

**Comment by bsekachev** [comment]
@csf-123 

Try to update your Chrome browser.

**Comment by bsekachev** [comment]
Please, provide details of ``Network`` tab in dev tools. 
I suspect there are some failed requests.

**Comment by csf-123** [comment]
> @csf-123
> 
> Try to update your Chrome browser.

> Please, provide details of `Network` tab in dev tools. I suspect there are some failed requests.

ok thanks a lot, i have edited the comment

**Comment by bsekachev** [comment]
@csf-123 Hmm, interesting. What is your browser version?

**Comment by csf-123** [comment]
> @csf-123 Hmm, interesting. What is your browser version?

98.0.4758.102

I just used edge browser and had the same problem

**Comment by bsekachev** [comment]
``docker ps`` output?

**Comment by csf-123** [comment]
> `docker ps` output?

![image](https://user-images.githubusercontent.com/60735331/155702401-94016555-bdf8-4eb9-8b66-6d8d4bc69c31.png)

**Comment by csf-123** [comment]
> `docker ps` output?

How to read the docker ps output, I'm a college student, I don't know much about this.

**Comment by azhavoro** [comment]
@csf-123 your compose configuration is wrong, please follow this guide if you want to change default 8080 port

**Comment by csf-123** [comment]
> @csf-123 your compose configuration is wrong, please follow this guide if you want to change default 8080 port: https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

Thank you. I'll try it

**Comment by csf-123** [comment]
@azhavoro Sorry to bother you again, my port 8090 is also occupied, do I need to change the port 8090 below?After the change, I can't access the login page.
![image](https://user-images.githubusercontent.com/60735331/155710515-803c4b80-5f8c-4a57-9513-49e80e9e2b8c.png)

**Comment by azhavoro** [comment]
It's expected because you config is wrong again, you need to change only `external` port for the traefik service and don't change `internal` like:
```yml
ports:
  - 8999:8080
```
Hope this will be helpful https://docs.docker.com/config/containers/container-networking/
8090 port is used for traefik dashboard which disabled by default, so you can change `8090` to any free port or delete this line if you don't plan to use traefik dashboard.

**Comment by csf-123** [comment]
@azhavoro I'm so stupid. Thanks for your help. I really appreciate it.

**Comment by azhavoro** [comment]
> @azhavoro I'm so stupid. Thanks for your help. I really appreciate it.

👍

**Comment by pkumar219** [comment]
what was the fix for this issue as i have same issue and logs not getting much information
