### ISSUE TITLE
Move polygon

### ISSUE THREAD

**Issue by edumotya** [openvinotoolkit/cvat#4396]
Is it possible to move (shift) a polygon?

I wonder if polygons can be entirely shift  without having to edit each single point. For instance, for many applications it is very useful to propagate polygons from one frame to another (if frames comes from video) and then shift the whole polygons.

**Comment by nmanovic** [comment]
@edumotya , it is possible. Just unlock it. By default it is locked.

**Comment by o797** [comment]
@edumotya hi, This question has nothing to do with whether it is locked or not. I would also like to ask this question. Have you solved it?

**Comment by edumotya** [comment]
No, I have not. I am sorry I did not reply because I thought it was my fault... 
I still have to move the polygon point by point even if the polygon is unlocked.

**Comment by o797** [comment]
I just found out why. When using polygon annotations, the property "Switch pinned property" is automatically selected, and the polygon can be moved by unchecking this property in the sidebar on the right.
![image](https://user-images.githubusercontent.com/91304124/156993736-0ed331f2-36ae-40f3-bd49-c2b3482effc4.png)
Like this, to cancel the selected

**Comment by edumotya** [comment]
Perfect! it is just as @nmanovic pointed out

**Comment by shokohigol** [comment]
> I just found out why. When using polygon annotations, the property "Switch pinned property" is automatically selected, and the polygon can be moved by unchecking this property in the sidebar on the right. ![image](https://user-images.githubusercontent.com/91304124/156993736-0ed331f2-36ae-40f3-bd49-c2b3482effc4.png) Like this, to cancel the selected

This one works for me.

**Comment by shizratariq** [comment]
@o797 797 thank you so much 
it worked for me

i was trying to figure it out for so long
