### ISSUE TITLE
job assignee can remove or update any issue created by the task owner

### ISSUE THREAD

**Issue by k1won** [openvinotoolkit/cvat#4424]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

- issue_owner, job_staff(except job_assignee) and project/task_staff can remove/update any issue in their job
but job_assignee should not be remove/update an issue created by the task owner. (permission not allowed)

### Current Behaviour

- When the job assignee removes or update an issue created by the task owner, the opa(permission rule) returns true.
### Possible Solution

- Modify and add the allow rule set for scope: "update", "delete" in the permission rule for issues.
```rego
< omitted > ...
allow {
    { utils.UPDATE, utils.DELETE }[input.scope]
    utils.is_sandbox
    utils.has_perm(utils.WORKER)
    is_issue_admin
    not is_job_assignee
}

allow {
    { utils.UPDATE, utils.DELETE }[input.scope]
    input.auth.organization.id == input.resource.organization.id
    utils.has_perm(utils.WORKER)
    organizations.is_member
    is_issue_admin
    not is_job_assignee
}
```
### Steps to Reproduce (for bugs)

1. create a task(job) and assign a worker role user to the job (by maintainer)
1. create an issue (by maintainer i.e., task owner)
1. the job assignee open the job and remove the issue created by the task owner

### Your Environment

- Git hash commit (`git log -1`): b0e6074c
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@k1won , I agree that probably the job assignee should not be able to delete issues of other users. In this case it isn't a typo, it is a wrong decision (https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/issues.csv). Probably job assignee should not be able to `update` the issue as well. What do you think?

**Comment by k1won** [comment]
@nmanovic , Yes, you are right.
If ```update``` is allowed, the job assignee can change the issue assignee or resolve value, so it seems correct not to allow both ```update``` and ```delete```.

**Comment by k1won** [comment]
@nmanovic , I modified the issues.csv, issues_test.gen.rego and issues.rego and then after I got the test result like below.
I will send a PR.
```rego
$ opa test issues_test.gen.rego issues.rego utils.rego organizations.rego
PASS: 2860/2860
```
