### ISSUE TITLE
Can I use my own database?

### ISSUE THREAD

**Issue by zzhuncle** [openvinotoolkit/cvat#4427]
Can I use my own database, that is, replace the postgres database with the mysql database. Besides changing the ip, port and 

initialization code, do I need to change anything? Is there any official document about this part? I feel that enterprises need this function

 very much! Thanks!

**Comment by nmanovic** [comment]
@zzhuncle , you can. CVAT uses Django and it supports MySQL natively: https://docs.djangoproject.com/en/4.0/ref/databases/#mysql-notes

You need to change corresponding settings: https://github.com/openvinotoolkit/cvat/blob/b0e6074ca39c3c25b2c0065a2293dc1fc081ddcd/cvat/settings/production.py#L25

Information from stackoverflow: https://stackoverflow.com/questions/19189813/setting-django-up-to-use-mysql
