### ISSUE TITLE
AI tools Interactors no polygon output

### ISSUE THREAD

**Issue by jonathancaevans** [openvinotoolkit/cvat#4432]
Are the AI tool interactors disabled on the demo site? Having trouble using DEXTR specifically, after marking points no polygon is generated in any case. This issue is on the demo site and my install for me.

**Comment by bsekachev** [comment]
@jonathancaevans 

Thanks for the report. Looks like something is wrong also with FBRS interactor.
We will investigate.

**Comment by hyunchan123** [comment]
@bsekachev 

in cvat/apps/lambda_manager/views.py
```python
class LambdaFunction:
    ...
    def invoke(self, db_task, data):
        ...
        response = self.gateway.invoke(self, payload)
        response_filtered = []
        ...
        if self.kind == LambdaType.DETECTOR:
            ...
            response_filtered.append(item)
        
        return response_filtered
```

In this case, if it is not a detector, [ ] is returned.

**Comment by nmanovic** [comment]
@hyunchan123 , thanks for the investigation. It looks like it is a regression after recent changes in the area. Will you be able to help us and send a PR?

**Comment by kriskorrel-cw** [comment]
@nmanovic 
If I understand correctly, it is expected that DEXTR does not work in the latest version of CVAT? Because I think I have the same problem: Dextr seems to return a 200 response, but this is always an empty list.

Do you have any indication of how it will take for the fix to be released? Can I expect this to be today/tomorrow, or will this take more time. In that case I might have to downgrade.

**Comment by dprov** [comment]
FYI, to make the fix work until it is released, I think one has to run (as stated in https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/)

docker-compose -f docker-compose.yml -f docker-compose.dev.yml build

**Comment by kriskorrel-cw** [comment]
> FYI, to make the fix work until it is released, I think one has to run (as stated in https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/)
> 
> docker-compose -f docker-compose.yml -f docker-compose.dev.yml build

Thanks! It took me some time to figure this out, but just a few hours ago I indeed found that I needed to rebuild from local source code using `-f docker-compose.dev.yml` 😅 
I can confirm that DEXTR works again after applying this fix.

**Comment by amteusch** [comment]
I found that I also needed to set up auto annotation as shown [here](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/). After registering with nuclio I got DEXTR and YOLO to work, and I presume it would be similar for other auto-annotation models.

**Comment by stobias123** [comment]
Hi all, I'm still seeing this issue with f-BRS - even after following above steps. 

I can confirm that I even see an output from the call to the f-BRS function in browser, but no polygon is created.
