### ISSUE TITLE
Permission error occured when accessing the JobCommits

### ISSUE THREAD

**Issue by k1won** [openvinotoolkit/cvat#4434]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

- Related : #4368

### Expected Behaviour

- returns the list of tracked changes for the job
### Current Behaviour

- permission error occured (except admin account)
```html
HTTP 403 Forbidden
Allow: GET, HEAD, OPTIONS
Content-Type: application/vnd.cvat+json
Vary: Accept

{
    "detail": "You do not have permission to perform this action."
}
```
### Possible Solution

- add additional 'key:value'(('commits', 'GET'): 'view:commits') to the get_scopes() method in JobPermission class like below. (apps.iam.permissions.py)
```python
    @staticmethod
    def get_scopes(request, view, obj):
        scope = {
            ('list', 'GET'): 'list', # TODO: need to add the method
            ('retrieve', 'GET'): 'view',
            ('partial_update', 'PATCH'): 'update',
            ('update', 'PUT'): 'update', # TODO: do we need the method?
            ('destroy', 'DELETE'): 'delete',
            ('annotations', 'GET'): 'view:annotations',
            ('annotations', 'PATCH'): 'update:annotations',
            ('annotations', 'DELETE'): 'delete:annotations',
            ('annotations', 'PUT'): 'update:annotations',
            ('data', 'GET'): 'view:data',
            ('issues', 'GET'): 'view',
            ('commits', 'GET'): 'view:commits'
        }.get((view.action, request.method))
```
- add additional rule variable(VIEW_COMMITS:="view:commits") to the utils.rego
```rego
VIEW_DATA := "view:data"
VIEW_COMMITS := "view:commits"  <<---
UPLOAD_DATA := "upload:data"
```

-  update permission rule to the jobs.rego
```rego
allow {
    { utils.VIEW, utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_COMMITS }[input.scope]
    utils.is_sandbox
    is_job_staff
}

allow {
    { utils.VIEW, utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_COMMITS }[input.scope]
    input.auth.organization.id == input.resource.organization.id
    utils.has_perm(utils.USER)
    organizations.has_perm(organizations.MAINTAINER)
}

allow {
    { utils.VIEW, utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_COMMITS }[input.scope]
    input.auth.organization.id == input.resource.organization.id
    organizations.has_perm(organizations.WORKER)
    is_job_staff
}
```

### Steps to Reproduce (for bugs)

1. create a task
1. open the job
1. create some shapes and save
1. access the /api/jobs/{id}/commits endpoint

### Your Environment

- Git hash commit (`git log -1`): b0e6074c
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@k1won , thanks again for your contribution! It looks like I tested these changes only with admin account.

**Comment by nmanovic** [comment]
@k1won , if you can help us again, please do that. We like contributions. It is the power of our community and it makes our team bigger and stronger.

**Comment by k1won** [comment]
@nmanovic , OK. No problem. 
I will send a PR soon.
