### ISSUE TITLE
Release v2.0.0 the annotator can also download data

### ISSUE THREAD

**Issue by fanasite** [openvinotoolkit/cvat#4439]
I create a Organization，and make an member as worker，it can also download dataset

look at it，didn't solve the problem https://github.com/openvinotoolkit/cvat/issues/3950

**Comment by nmanovic** [comment]
@fanasite , by the description nobody can help or investigate the issue. See permissions in the file: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/tasks.csv

If your worker is an assignee or owner of the task, he/she can download the dataset. If the worker is an assignee for the job, he/she should not be able to download the dataset.

Feel free to add more details how to reproduce the issue. For now I will close the issue.
