### ISSUE TITLE
Can't get all tasks in a project by 'GET' method of '/projects/{id}/tasks'

### ISSUE THREAD

**Issue by Marxlp** [openvinotoolkit/cvat#4453]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am trying using the swagger api to get the tasks list of a project, but only get ten of about 50 tasks info.

### Expected Behaviour

Get all the tasks info in given project.

### Current Behaviour

Only get ten tasks info in one request.

### Your Environment

- cvat version 1.6.0

**Comment by nmanovic** [comment]
@Marxlp , please look at page_size query parameter: https://cvat.org/api/swagger/#/projects/projects_tasks_list

I will close the issue.

**Comment by pranavchaturved** [comment]
@nmanovic Doesn't seem to be the solution (anymore). I checked the swagger, I don't think this method exists anymore.

**Comment by nmanovic** [comment]
@pranavchaturved , please try /api/tasks?project_id=id
