### ISSUE TITLE
Unable to upload annotations

### ISSUE THREAD

**Issue by k1won** [openvinotoolkit/cvat#4459]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

- Annotations should be created through file upload.
### Current Behaviour

- After applying #4327, 403 Forbidden status code is returned when uploading a job annotation file.
- at the result of checking the opa log, the scope value of the input data is null.
- task annotations upload also same
- By #4327, when the "upload annotations" function is executed, the http request method is changed from PUT to POST, but the cause is that the new key:value definition for POST does not exist in get_scopes() of JobPermission.

![image](https://user-images.githubusercontent.com/12894869/158230132-f78deb42-a52e-464a-b227-47799869a713.png)

### Possible Solution

- Add the following two key:value pairs to get_scopes() in JobPermission and TaskPermission class.
> ('annotations', 'POST'): 'import:annotations'
 > ('append_annotations_chunk', 'PATCH'): 'update:annotations',
### Steps to Reproduce (for bugs)

1. create some labeled shapes
1. save and export annotations (w/ task owner account)
1. remove annotations and save
1. upload annotations

### Your Environment

- Git hash commit (`git log -1`): 7ef553fd
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@k1won , thanks.

@klakhov , could you please fix the issue and be sure that we have a test for the issue?

**Comment by klakhov** [comment]
@nmanovic Yes, the problem will be fixed

**Comment by MiiViiDynamics** [comment]
I also get the same problem.
The message indicated upload succeeded, but not rectangle can be seen.
The annotation as below.

<annotation>
    <folder>images</folder>
    <filename>hard_hat_workers1007.png</filename>
    <size>
        <width>416</width>
        <height>415</height>
        <depth>3</depth>
    </size>
    <segmented>0</segmented>
    <object>
        <name>helmet</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>104</xmin>
            <ymin>91</ymin>
            <xmax>164</xmax>
            <ymax>165</ymax>
        </bndbox>
    </object>
    <object>
        <name>helmet</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>142</xmin>
            <ymin>140</ymin>
            <xmax>171</xmax>
            <ymax>180</ymax>
        </bndbox>
    </object>
    <object>
        <name>person</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>47</xmin>
            <ymin>99</ymin>
            <xmax>165</xmax>
            <ymax>344</ymax>
        </bndbox>
    </object>
    <object>
        <name>person</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>141</xmin>
            <ymin>140</ymin>
            <xmax>173</xmax>
            <ymax>321</ymax>
        </bndbox>
    </object>
    <object>
        <name>head</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>313</xmin>
            <ymin>175</ymin>
            <xmax>329</xmax>
            <ymax>190</ymax>
        </bndbox>
    </object>
    <object>
        <name>person</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>308</xmin>
            <ymin>173</ymin>
            <xmax>348</xmax>
            <ymax>217</ymax>
        </bndbox>
    </object>
    <object>
        <name>helmet</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>104</xmin>
            <ymin>0</ymin>
            <xmax>165</xmax>
            <ymax>52</ymax>
        </bndbox>
    </object>
    <object>
        <name>person</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>47</xmin>
            <ymin>345</ymin>
            <xmax>166</xmax>
            <ymax>414</ymax>
        </bndbox>
    </object>
    <object>
        <name>person</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>141</xmin>
            <ymin>368</ymin>
            <xmax>174</xmax>
            <ymax>414</ymax>
        </bndbox>
    </object>
</annotation>

**Comment by bit-scientist** [comment]
@k1won, hi. do yo mind taking a look at #5653 ?
