### ISSUE TITLE
After upgrade to 2.0 all my tasks have lost their state (= reset to new)

### ISSUE THREAD

**Issue by haimat** [openvinotoolkit/cvat#4470]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I upgraded our CVAT installation from version 1.7 to latest 2.0. The process worked fine, I can log in again and see my old projects and their tasks. I was expecting these tasks to be in the same state as they have been before the upgrade.

### Current Behaviour

Unfortunately, all tasks have been reset to the initial "new" state, thus on the project overview page all their tasks seem to be completely new. However, when I open the tasks and their jobs then I can see that (luckily) the annotations are still there. It's just the "finished" state of the tasks which seem to have not been migrated during the update.

### Your Environment

- Git hash commit (`git log -1`): e33db5c2c2b3ee03a992f97b418e20cc026fa767  (2.0.0)
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 20.10.12
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04

**Comment by bsekachev** [comment]
Hi @haimat 

In the past there was a field ``status`` in a Job (actually it is still there, but is not used anymore and will be removed in the future). 
Task status was computed automatically based on its jobs statuses.

Now instead of ``status`` field, a job has ``stage`` (annotation, validation, acceptance) and ``state`` (new, in progress, rejected, accepted) fields.
And task status is computed based on jobs stages.

Since database migration file has default value for ``stage``: ``annotation``, task will be reset. You can manually (or automatically based on ``status``) restore correct ``stage`` value for jobs. 

@nmanovic 
Do you think it makes sense to add one more migration file now (with some code) to apply this logic automatically?

**Comment by haimat** [comment]
@bsekachev Thanks for the info, Boris.
What is the difference between `stage` and `state` though?

**Comment by bsekachev** [comment]
As I told, each job can be in different stages: ``annotation``, ``validation``, or ``acceptance``. On the first stage users annotate objects on images, on the second stage other users validate annotated objects, on the third the job is done by annotation team (but still might be validated by annotations customers if the dataset is annotated using workforce of 3rdparty vendor).

State defines progress in a specific stage. For example: ``annotation new`` means, that the Job is not started yet at all, ``annotation in progress`` means that the job is being annotated,  ``validation rejected`` means that reviewer requires some changes in the job, ``acceptance completed`` means that the job was totally finished, etc.

**Comment by haimat** [comment]
Ok thanks for the clarification. Thus I will manually update the stages of my previous/old tasks now ...

**Comment by debpriyoroy** [comment]
> 



> As I told, each job can be in different stages: `annotation`, `validation`, or `acceptance`. On the first stage users annotate objects on images, on the second stage other users validate annotated objects, on the third the job is done by annotation team (but still might be validated by annotations customers if the dataset is annotated using workforce of 3rdparty vendor).
> 
> State defines progress in a specific stage. For example: `annotation new` means, that the Job is not started yet at all, `annotation in progress` means that the job is being annotated, `validation rejected` means that reviewer requires some changes in the job, `acceptance completed` means that the job was totally finished, etc.



> Hi @haimat
> 
> In the past there was a field `status` in a Job (actually it is still there, but is not used anymore and will be removed in the future). Task status was computed automatically based on its jobs statuses.
> 
> Now instead of `status` field, a job has `stage` (annotation, validation, acceptance) and `state` (new, in progress, rejected, accepted) fields. And task status is computed based on jobs stages.
> 
> Since database migration file has default value for `stage`: `annotation`, task will be reset. You can manually (or automatically based on `status`) restore correct `stage` value for jobs.
> 
> @nmanovic Do you think it makes sense to add one more migration file now (with some code) to apply this logic automatically?

What might be the best way to change the state to completed automatically ?It would be very difficult to change the state manually as there are a lot of tasks
