### ISSUE TITLE
Couldn't get formats from the server

### ISSUE THREAD

**Issue by mahiratmis** [openvinotoolkit/cvat#4479]
### My actions before raising this issue
- I have been annotating for a long time. But last Thursday I wasn't able to reach the annotation website. I waited for some time in a hope that the problem will disappear by itself. However, the problem persisted so I stopped all containers using **docker-compose down**.  I restarted the computer. It asked me to update the system(Ubuntu) so I updated the system. I restarted the computer and run the following command to start the containers again **docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d**
- [+ ] Searched [past issues](/issues)

### Context

I am creating a dataset for my Ph.D. If I cannot make it work again I won't be able to finish it on time.

### Your Environment

-Cvat information:
CVAT version
Server: 1.3
Core: 3.12.0
Canvas: 2.4.1
UI: 1.18.1

-Error Message:
TypeError
Cannot read properties of null (reading 'loaders')

TypeError: Cannot read properties of null (reading 'loaders')
    at http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:404:790615
    at Ko (http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:57930)
    at gs (http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:104169)
    at cl (http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:96717)
    at sl (http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:96642)
    at Qs (http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:93672)
    at http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:45314
    at t.unstable_runWithPriority (http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:364:3844)
    at Ba (http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:45023)
    at Ga (http://193.255.60.118:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:45259)

- Git hash commit (`git log -1`):
**commit bd49d7ae99c66ebfec500e4a98af053cdc55e618 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Snyk bot <snyk-bot@snyk.io>
Date:   Wed May 5 14:27:05 2021 +0300
    fix: cvat/requirements/base.txt to reduce vulnerabilities (#3155)    
    The following vulnerabilities are fixed by pinning transitive dependencies:
    - https://snyk.io/vuln/SNYK-PYTHON-DJANGO-1279042**

- Docker version `docker version`: **Version: 20.10.12**

- Are you using Docker Swarm or Kubernetes?  **No**
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04.6 LTS (bionic)
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    Link to the log file:
    https://drive.google.com/file/d/1jXiF9IfVkI1UEzLTTYobAwYAHza5rGKs/view?usp=sharing

### Client Browser and OS
- Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)
- Ubuntu 18.04.6 LTS (bionic)

**Comment by bsekachev** [comment]
Hi, @mahiratmis 

Generally 1.3 version is too old. 
But I can try to help if you provide some more details:
1. ``docker ps`` output
1. A screenshot of the Network tab in dev tools
1. Also please say more about the error, is it reproduced each time you open CVAT and does not allow to work, or ...?

**Comment by mahiratmis** [comment]
Thank you for your quick reply @bsekachev. I know I shouldn't have posted an issue since it is old but this area is my last hope. I couldn't get any help over gitter.

docker ps output is as follows:
[Output jpg](https://drive.google.com/file/d/1feIZYO2Bus2MP2MVPLuS-SSB0CGCtIEu/view?usp=sharing)
[Network tab](https://drive.google.com/file/d/1drYftlzGw82KNJXKFtYnYEXmbj9TENoR/view?usp=sharing)

Each time I down and up the containers I face those same errors I shared above.
After that error, I can see the tasks and their preview images listed, but some of the preview images are missing as you can see here [Listed tasks](https://drive.google.com/file/d/1G7f-kg0196ntoXhRb245jvnSGDpo0tzQ/view?usp=sharing) . However, when I try to open the task I get following screen.
[After tasks listed](https://drive.google.com/file/d/1X0Q11jcz1elLEtaQOG_40NvzV7AcSKk3/view?usp=sharing)

**Comment by bsekachev** [comment]
@mahiratmis 

Please, first open Network tab, then update page and finally make a screenshot, because otherwise the tab does not have any details. 

I also suspect that all you see now in your browser is cached by the browser (try to click checkbox ``Disable cache`` in top bar of Network tab) and say what you will see

**Comment by mahiratmis** [comment]
@bsekachev [this](https://drive.google.com/file/d/176TILksyp2YwgZhtzWWG54H5mobEVBNN/view?usp=sharing) is the screen after your suggestions.

**Comment by bsekachev** [comment]
@mahiratmis 

Okay, could you please also click failed red ``self`` request and show us details?

**Comment by mahiratmis** [comment]
It says **"Failed to load response data: No data found for resource with given the identifier."**

**Comment by bsekachev** [comment]
@mahiratmis Does it have any HTTP response code?

**Comment by mahiratmis** [comment]
Does it have any HTTP response code? (No it doesn't)
Are you able to get a list of tasks using REST API 193.255.60.118:8080/api/v1/tasks? (I don't know how to test it)
What is output of docker logs cvat? ([logs](https://drive.google.com/file/d/1TYQM4g6F4xFa3Ozw7ivsCR80osSfy1Wz/view?usp=sharing))

**Comment by mahiratmis** [comment]
@bsekachev If it will be easier I can share a zoom link.

**Comment by bsekachev** [comment]
@mahiratmis 

>> Are you able to get a list of tasks using REST API 193.255.60.118:8080/api/v1/tasks?

> (I don't know how to test it)

Open this link in your browser. Also I would recommend to open CVAT in another browser (I do not think that the browser is a root cause, just in case)

**Comment by mahiratmis** [comment]
> Are you able to get a list of tasks using REST API 193.255.60.118:8080/api/v1/tasks?
It returns a connection timeout both on Chrome and Firefox

**Comment by bsekachev** [comment]
@mahiratmis 

Because of some reasons looks like backend can't connect to the database. 
Maybe there are useful information in ``docker logs cvat_db`` or ``docker logs cvat_proxy``, could you share output?
Also did you change any config files? Does ``git status`` show any modified files?

**Comment by mahiratmis** [comment]
@bsekachev  followings a re the outputs: 

**cvat_db logs:**
PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-03-15 15:23:37.072 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-03-15 15:23:37.072 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-03-15 15:23:37.081 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-03-15 15:23:37.108 UTC [21] LOG:  database system was shut down at 2022-03-15 15:02:52 UTC
2022-03-15 15:23:37.118 UTC [1] LOG:  database system is ready to accept connections
2022-03-15 15:23:38.880 UTC [28] LOG:  incomplete startup packet

**cvat_proxy log:**
172.28.0.1 - - [15/Mar/2022:15:24:17 +0000] "GET /favicon.ico HTTP/1.1" 404 555 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
172.28.0.1 - - [15/Mar/2022:15:24:23 +0000] "GET / HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
172.28.0.1 - - [15/Mar/2022:15:24:27 +0000] "GET / HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
172.28.0.1 - - [15/Mar/2022:15:24:35 +0000] "GET / HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
172.28.0.1 - - [15/Mar/2022:15:24:36 +0000] "GET /favicon.ico HTTP/1.1" 404 555 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
185.67.33.204 - - [15/Mar/2022:16:19:20 +0000] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03<P\xC1O\xF3Us\x0F\xBEP\xB6\xA0\xF4\x1E\xD2\xC4\x8Bo_\xB6\xCBo\x97}\xEE\x99F\xDC\x81fz\x98 C\x01d\xCC7]\x15\x00\xCDe\xCD\x02\xCE}\x07\xAE\xB1\x9F\xF9\xD4\x02\x1F\xA8@\x89\x0C\xB2\x9A\xE7B\x05 \x00&\xC0/\xC00\xC0+\xC0,\xCC\xA8\xCC\xA9\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-"
146.255.185.134 - - [15/Mar/2022:19:19:15 +0000] "\x12\x01\x00^\x00\x00\x01\x00\x00\x00$\x00\x06\x01\x00*\x00\x01\x02\x00+\x00\x01\x03\x00,\x00\x04\x04\x000\x00\x01\x05\x001\x00$\x06\x00U\x00\x01\xFF\x04\x07\x0C\xBC\x00\x00\x00\x00\x00\x00\x15\xD0\x00p\xF6\xF0^\xF2\x00\x00\x008y\xE8{\xF7\x7F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFE\xFF\xFF\xFF\x01" 400 157 "-" "-"
80.82.70.228 - - [15/Mar/2022:20:34:00 +0000] "\x16\x03\x02\x01o\x01\x00\x01k\x03\x02RH\xC5\x1A#\xF7:N\xDF\xE2\xB4\x82/\xFF\x09T\x9F\xA7\xC4y\xB0h\xC6\x13\x8C\xA4\x1C=\x22\xE1\x1A\x98 \x84\xB4,\x85\xAFn\xE3Y\xBBbhl\xFF(=':\xA9\x82\xD9o\xC8\xA2\xD7\x93\x98\xB4\xEF\x80\xE5\xB9\x90\x00(\xC0" 400 157 "-" "-"
192.241.225.109 - - [15/Mar/2022:22:28:17 +0000] "MGLNDD_193.255.60.118_8080" 400 157 "-" "-"
94.232.42.204 - - [15/Mar/2022:22:43:00 +0000] "\x03\x00\x00/*\xE0\x00\x00\x00\x00\x00Cookie: mstshash=Administr" 400 157 "-" "-"
5.8.10.202 - - [15/Mar/2022:23:35:46 +0000] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03\x18}#!e\xE5\x18(G@\x96\xB1*\xFF \xE5\xB7+\xC7\xA9\xC64\xE9W\xA51\x97sp\xB1y1 u\xB3\x18\xC3\xA0\x9F\xB8\xB3xU\xBE0w\xFFz\x8D\xEB9\xC1\x1Dp8H<\x0C~\x01\xD6\xC0J_\xED\x00&\xCC\xA8\xCC\xA9\xC0/\xC00\xC0+\xC0,\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-"
5.8.10.202 - - [15/Mar/2022:23:35:49 +0000] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03\x1D\x8E\xEDI\xAD},)\xDC\xD2\xE0r\x81" 400 157 "-" "-"
34.96.130.0 - - [16/Mar/2022:03:02:54 +0000] "\x16\x03\x01\x00\xCA\x01\x00\x00\xC6\x03\x03N\x18&f\xF0\xF9\x91\xF6~g\x16\xD0\xE3\x8F\xA8\x1D\xB1\xA0\xE4\xA4\xD3/'0\x9F\x1B\xB9\x8EKW\xA4\x83\x00\x00h\xCC\x14\xCC\x13\xC0/\xC0+\xC00\xC0,\xC0\x11\xC0\x07\xC0'\xC0#\xC0\x13\xC0\x09\xC0(\xC0$\xC0\x14\xC0" 400 157 "-" "-"
103.203.57.9 - - [16/Mar/2022:07:03:20 +0000] "\x00\x9C\x00\x01\x1A+<M\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00" 400 157 "-" "-"
103.203.57.9 - - [16/Mar/2022:07:03:20 +0000] "\x05\x02\x00\x02" 400 157 "-" "-"
103.203.57.9 - - [16/Mar/2022:07:03:24 +0000] "\x04\x01\x1F\x00\x00\x00\x00\x00\x00" 400 157 "-" "-"
195.142.69.177 - - [16/Mar/2022:08:44:58 +0000] "GET /auth/login HTTP/1.1" 200 1045 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:45:04 +0000] "GET /cvat-ui.2cce2fa422a65445a9c6.min.js HTTP/1.1" 200 5694766 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:45:12 +0000] "GET /api/v1/users/self HTTP/1.1" 200 298 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:45:12 +0000] "GET /api/v1/users/self HTTP/1.1" 200 298 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:45:12 +0000] "GET /api/v1/restrictions/user-agreements HTTP/1.1" 200 2 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:45:12 +0000] "GET /api/v1/server/about HTTP/1.1" 200 447 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:45:13 +0000] "GET /api/v1/server/plugins HTTP/1.1" 200 57 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:45:51 +0000] "GET /download.worker.cb069004e9ace5f89e8e.js HTTP/1.1" 200 16721 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:46:13 +0000] "GET /api/v1/tasks?page_size=10&page=1 HTTP/1.1" 200 64259 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:46:14 +0000] "GET /api/v1/tasks/44/data?type=preview HTTP/1.1" 200 7186 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:46:14 +0000] "GET /api/v1/tasks/39/data?type=preview HTTP/1.1" 200 4235 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:46:14 +0000] "GET /api/v1/tasks/38/data?type=preview HTTP/1.1" 200 12919 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:46:14 +0000] "GET /api/v1/tasks/37/data?type=preview HTTP/1.1" 200 11751 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:46:14 +0000] "GET /api/v1/tasks/36/data?type=preview HTTP/1.1" 200 14054 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:46:14 +0000] "GET /api/v1/tasks/35/data?type=preview HTTP/1.1" 200 13278 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:46:14 +0000] "GET /api/v1/lambda/requests HTTP/1.1" 200 2 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:08:47:37 +0000] "POST /api/v1/server/exception HTTP/1.1" 201 1205 "http://193.255.60.118:8080/tasks" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:08:51 +0000] "GET /auth/login HTTP/1.1" 200 1045 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:08:52 +0000] "GET /api/v1/users/self HTTP/1.1" 200 298 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:08:52 +0000] "GET /api/v1/users/self HTTP/1.1" 200 298 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:08:52 +0000] "GET /download.worker.cb069004e9ace5f89e8e.js.map HTTP/1.1" 200 77935 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:08:52 +0000] "GET /api/v1/server/about HTTP/1.1" 200 447 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:08:52 +0000] "GET /api/v1/server/plugins HTTP/1.1" 200 57 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:08:52 +0000] "GET /favicon.ico HTTP/1.1" 200 102581 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:09:58 +0000] "GET /cvat-ui.2cce2fa422a65445a9c6.min.js.map HTTP/1.1" 200 18810668 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:27:19 +0000] "GET /auth/login HTTP/1.1" 200 1045 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:27:31 +0000] "GET /cvat-ui.2cce2fa422a65445a9c6.min.js HTTP/1.1" 200 5694766 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:27:32 +0000] "GET /api/v1/users/self HTTP/1.1" 200 298 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:27:32 +0000] "GET /download.worker.cb069004e9ace5f89e8e.js HTTP/1.1" 200 16721 "http://193.255.60.118:8080/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:27:32 +0000] "GET /download.worker.cb069004e9ace5f89e8e.js.map HTTP/1.1" 200 77935 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
195.142.69.177 - - [16/Mar/2022:10:28:36 +0000] "GET /cvat-ui.2cce2fa422a65445a9c6.min.js.map HTTP/1.1" 200 18810668 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
206.189.205.251 - - [16/Mar/2022:10:47:13 +0000] "POST /api/v1/tasks? HTTP/1.1" 408 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
206.189.205.251 - admin [16/Mar/2022:10:47:53 +0000] "POST /api/v1/tasks? HTTP/1.1" 408 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
206.189.205.251 - admin [16/Mar/2022:10:48:34 +0000] "POST /api/v1/tasks? HTTP/1.1" 408 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"

**git status:**
Your branch is up to date with 'origin/develop'.

İzlenmeyen dosyalar:
  (gönderilecek olarak dahil edilmesi için "git add <dosya>..." kullanın)

	cvat.logs
	cvat_db_logs.txt
	cvat_logs_issue.txt
	cvat_logs_last.txt
	docker_komutlar.txt

nothing added to commit but untracked files present (use "git add" to track)

**Comment by bsekachev** [comment]
Can you open CVAT using ``localhost:8080`` in your browser? Just if you do not change any configs, I do not have any ideas why this IP should work: ``193.255.60.118``

**Comment by bsekachev** [comment]
You said you used ``docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d`` to run containers. What does ``*.override.yml`` contain?

**Comment by mahiratmis** [comment]
I couldn't get the YAML file as it is, because of indentations. so I took a screenshot:
[Here](https://drive.google.com/file/d/1a_Q9cn5HY7XFbKn0udzWkeWs54oz_qcZ/view?usp=sharing) is the image of the YAML file.

**Comment by bsekachev** [comment]
@mahiratmis 

Maybe I would suggest you to try to remove this section
![image](https://user-images.githubusercontent.com/40690378/158588287-157b5dec-afaf-40e9-b5c7-ca4f9efd4052.png)

Do ``docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d`` again, and try to open CVAT using localhost:8080. If it does not help, you can revert it back.

**Comment by bsekachev** [comment]
And to remove this one:

```
ports:
- "80:8080"
```

**Comment by mahiratmis** [comment]
I have a few questions before moving forward:
Should I stop all containers using the `docker-compose down` first before testing your suggestions?
Will those changes cause any loss on previous annotations?
If I remove CVAT_HOST: 193.255.60.118 part, how will I be able to reach the site remotely?
Thanks for your answers in advance.

**Comment by bsekachev** [comment]
> Should I stop all containers using the docker-compose down first before testing your suggestions?

Yes

> Will those changes cause any loss on previous annotations?

No, your data are in docker volumes. 

> If I remove CVAT_HOST: 193.255.60.118 part, how will I be able to reach the site remotely?

Now nohow, it is time to just investigate the root cause. As I said, you can revert it back.

**Comment by mahiratmis** [comment]
This is what I get after restarting and checking on localhost:
![Screenshot from 2022-03-16 15-31-37](https://user-images.githubusercontent.com/1335306/158590542-025c60eb-f8cf-4c28-8fe1-1dd147e49702.png)

**Comment by bsekachev** [comment]
@mahiratmis 

And what can you see in the browser console now? (and Network tab)

**Comment by mahiratmis** [comment]
Amazing :)) 
Now, I can see all annotations and able to log in to CVAT.

**Comment by bsekachev** [comment]
Nice, now you can try to return back section with ``CVAT_HOST``.
I actually think that 

```
ports:
- "80:8080"
``` 

was the root of the issue.

**Comment by atmismahir** [comment]
@bsekachev interestingly, I get following screen when I switch back to remote version.
![Screenshot from 2022-03-16 16-03-21](https://user-images.githubusercontent.com/79939971/158595934-1e7558b8-bfff-4ace-9605-3d970abe6c96.png)

**Comment by bsekachev** [comment]
@mahiratmis 

Interesting. Maybe configuration is guilty.. Is this IP address correct? Can you see it in ``ifconfig`` tool?

**Comment by atmismahir** [comment]
@bsekachev the server is on campus and the network administrator directs incoming requests for that ip to my computer on campus.

**Comment by bsekachev** [comment]
@atmismahir 

To be honest, I am not sure it will work in such scenario. At least you can back up all your data and maybe try newer CVAT version

**Comment by atmismahir** [comment]
is there a step by step guide on how to backup the current setup and upgrade to newer version without a problem?

**Comment by bsekachev** [comment]
Upgrading is very simple:

```
git checkout develop
git pull origin develop
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
```

Generally all your data are expected to be kept during upgrading
But just in case backup guide is here https://openvinotoolkit.github.io/cvat/docs/administration/advanced/backup_guide/#how-to-backup-all-cvat-data

**Comment by atmismahir** [comment]
thank you very much for everything @bsekachev . I can't tell how grateful I am.

**Comment by bsekachev** [comment]
I will close the issue, do not hesitate to reopen if you have other questions
