### ISSUE TITLE
can‘t  open Admin page

### ISSUE THREAD

**Issue by ningjunwei2** [openvinotoolkit/cvat#4494]
I Install CVAT with helm  
version is :V2.0.0
when i click Admin page ，When I click Admin Page, it redirects to the Task page。
Back-end and front-end pods do not have any logs  
My ingress is Kong

**Comment by azhavoro** [comment]
Hi, what is your ingress configuration? Seems you don't have right route for `/admin` path

**Comment by ningjunwei2** [comment]
> 你好，你的入口配置是什么？似乎你没有正确的`/admin`路径路径



> 你好，你的入口配置是什么？似乎你没有正确的`/admin`路径路径

my

> Hi, what is your ingress configuration? Seems you don't have right route for `/admin` path



> Hi, what is your ingress configuration? Seems you don't have right route for `/admin` path

I'm following the  value. yaml configuration on Github
and my ingress configuration is :

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cvat-ingress
  namespace: cvat
spec:
  ingressClassName: kong
  rules:
  - host: cvat.test-r2d2.narwal.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: cvat-develop-frontend-service
            port:
              number: 80
      - path: "/api/.*|git/.*|tensorflow/.*|auto_annotation/.*|analytics/.*|static/.*|admin|admin/.*|documentation/.*|dextr/.*|reid/.*"
        pathType: Prefix
        backend:
          service:
            name: cvat-develop-backend-service
            port:
              number: 8080

**Comment by azhavoro** [comment]
> * path: "/api/._|git/._|tensorflow/._|auto_annotation/._|analytics/._|static/._|admin|admin/._|documentation/._|

I'm not sure that is correct path configuration for your ingress controller, this should works for nginx if ` nginx.ingress.kubernetes.io/use-regex: "true"`; Please try to use Nginx ingress controller or read the documentation for your preferable controller

**Comment by ningjunwei2** [comment]
> > * path: "/api/._|git/._|tensorflow/._|auto_annotation/._|analytics/._|static/._|admin|admin/._|documentation/._|
> 
> I'm not sure that is correct path configuration for your ingress controller, this should works for nginx if ` nginx.ingress.kubernetes.io/use-regex: "true"`; Please try to use Nginx ingress controller or read the documentation for your preferable controller


I can access via domain ,  it looks like some configuration  problem with  my Ingress

**Comment by ningjunwei2** [comment]
> > * path: "/api/._|git/._|tensorflow/._|auto_annotation/._|analytics/._|static/._|admin|admin/._|documentation/._|
> 
> I'm not sure that is correct path configuration for your ingress controller, this should works for nginx if ` nginx.ingress.kubernetes.io/use-regex: "true"`; Please try to use Nginx ingress controller or read the documentation for your preferable controller

I can access by ip:port , it looks like some configuration problem with my Ingress
