### ISSUE TITLE
`localhost:8080` get `404 page not found` after installation in Ubuntu

### ISSUE THREAD

**Issue by JanineCHEN** [openvinotoolkit/cvat#4501]
Hi, after following the installation instruction for Ubuntu (I'm using Ubuntu 20.04) without any outstanding error, I got `404 page not found` after opening Chrome browser and going to localhost:8080. Any idea why this might happen, or anything I have overlooked? Thank you in advance for any help!

**Comment by JanineCHEN** [comment]
The issue is solved after close and restart the terminal somehow

**Comment by kylevedder** [comment]
For anyone else that finds this issue, the cause is setting `CVAT_HOST` variable properly; if you set the variable wrong, it gives you an undescriptive 404 error, but if you restart the terminal like described above, it unsets `CVAT_HOST` causing it to default to the behavior of using `localhost`.
