### ISSUE TITLE
Draw new label/tag by shortcut after annotate a tag blocks "Rectangle" selection button in side-bar

### ISSUE THREAD

**Issue by admer7** [openvinotoolkit/cvat#4503]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
- [x] Searched [Gitter](https://gitter.im/opencv-cvat/public)

We are using the "Standard" Workspace and a handful of labels and one tag with attributes for our annotation jobs. We often need to switch between placing a tag and placing a label.

### Expected Behaviour
1. Create a tag by clicking the tag symbol on the side-bar -> Tag gets created
2. Create a new tag by shortcut "n" or select by mouse the rectangle shape in the side-bar to create a new rectangle label

### Current Behaviour
1. Create a tag by clicking the tag symbol on the side-bar -> Tag gets created
2. Create a new tag by shortcut "n" -> Tag gets created
3. Pressing "n" again does nothing and the rectangle button is "locked" and cannot be clicked anymore, see image. 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/bd3xFCT/bug-ui.png" alt="bug-ui" border="0"></a>

### Possible Solution
Current workaround is to select by mouse another label/tag from the side-bar, place it, delete it again and create the original label.

### Steps to Reproduce (for bugs)
1. Create a tag by clicking the tag symbol on the side-bar
2. Create a new tag by shortcut "n" 
3. Rectangle button is locked

No errors or warnings gets printed.

### Context
Same problem with [cvat.org](cvat.org), CVAT v2.0.0-alpha and v2.0.0 release version.

### Your Environment
- Server version: 2.0
- Core version: 4.2.0
- Canvas version: 2.13.1
- UI version: 1.35.0
- Docker version 20.10.12, build e91ed57
- Ubuntu 20.04

**Comment by bsekachev** [comment]
@admer7 

Thank you for the report, it is a bug.

P.S. For tags I would recommend to look at "Tag annotation" mode. If you do not have lots of classes it probably would be more effective.

**Comment by admer7** [comment]
Thanks for the quick response! 

We have it the other way round. A lot of classes and usually only one or two tags. I assume for this scenario the "Standard" mode is the logical one.

**Comment by bsekachev** [comment]
Hi @admer7 

Could you please check if the fix above works for you?

**Comment by admer7** [comment]
Problem still remains. After pressing "n", the rectangle button in the side-bar is locked.

**Comment by bsekachev** [comment]
@admer7 

Are u sure you updated CVAT? What steps did you do to update? I tried this patch and actually looks like it works.

**Comment by admer7** [comment]
Ok, it is fixed after fresh cloning and building from source :) 

But we are using 2.0.0 release and only coping `cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/setup-tag-popover.tsx` is not enough to fix this bug... Any suggestions?

**Comment by bsekachev** [comment]
Maybe because you fetched server release from docker hub instead of buidling from source first? ``-f docker-compose.dev.yml`` file must be included when build.

**Comment by admer7** [comment]
I used the git repo with the [2.0.0 tag](https://github.com/openvinotoolkit/cvat/releases/tag/v2.0.0), added the modified `setup-tag-popover.tsx` file and build via `-f docker-compose.dev.yml`.
