### ISSUE TITLE
instructions on using https

### ISSUE THREAD

**Issue by alex9311** [openvinotoolkit/cvat#452]
I just got CVAT working with HTTPs. I'm new to Django so I had to dig a bit through the gitter chat to find the info I needed. Would it be helpful for me to summarize the steps I took and add to instructions.md?

**Comment by nmanovic** [comment]
@alex9311 ,

Absolutely! It will be awesome if you can contribute your experience. Together we will write a nice instructions. We also uses https access internally but I don't have enough time to cover all such topics.

**Comment by nmanovic** [comment]
No support from our community. Move to backlog.

**Comment by xuchenCN** [comment]
@alex9311 I viewed your documents add ```--https-only``` and some parameters in order to enable https, but got error log
 ```AH01630: client denied by server configuration: /tmp/mod_wsgi-localhost:8080:0/htdocs/favicon.ico```

**Comment by radoye** [comment]
@nmanovic Is this still of interest? I just did this yesterday, and it seems to work. I also got it to work on Azure (using VM).

**Comment by nmanovic** [comment]
@radoye , sure. Don't hesitate to send a PR with instructions. I believe we can add them into https://github.com/opencv/cvat/blob/master/cvat/apps/documentation/installation.md#advanced-topics
