### ISSUE TITLE
executor failed running [/bin/sh -c DATUMARO_HEADLESS=1 python3 -m pip install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt]: exit code: 2 Service 'cvat' failed to build : Build failed

### ISSUE THREAD

**Issue by tzx1205** [openvinotoolkit/cvat#4523]
Need help！
I am using Win10 OS and when I execute the following command, I get the following error：
（thanks !!
![image](https://user-images.githubusercontent.com/68260567/160356493-bbb4a10e-491f-45ae-b702-230e2d95f78f.png)
![image](https://user-images.githubusercontent.com/68260567/160356642-7a159b30-7bb4-42f9-9117-1410d31d5a9f.png)

**Comment by azhavoro** [comment]
Hi, I cannot reproduce the issue, seems there is some network issue on your side and `files.pythonhosted.org` is not accessible from your container. Also please check proxy setting if you are behind a proxy
