### ISSUE TITLE
Uploading annotation doesn't work on cvat.org public version

### ISSUE THREAD

**Issue by Mohammed-Elias** [openvinotoolkit/cvat#4531]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Can't upload annotation to a dataset!
the last month uploading dataset and its annotation was working well, right now, when I try to upload the annotation using COCO format or any other format, I got this error:

```Could not upload annotation for the [task 228819](https://cvat.org/tasks/228819) Open the Browser Console to get details ```

and when I opened the dev tools in Chrome, I got this 2 messages in the console: 

1)
```httpStack.js:96 Mixed Content: The page at 'https://cvat.org/tasks/228819/jobs/322540' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://cvat.org/api/jobs/322540/annotations/a2d11c72-b171-43cb-a16f-81380ba2f517'. This request has been blocked; the content must be served over HTTPS. (anonymous) @ httpStack.js:96```

2)
```cvat-app.tsx:283 Error: tus: failed to upload chunk at offset 0, caused by [object ProgressEvent], originated from request (method: PATCH, url: http://cvat.org/api/jobs/322540/annotations/a2d11c72-b171-43cb-a16f-81380ba2f517, response code: n/a, response text: n/a, request id: n/a).```

### Expected Behaviour

it always was successfully uploaded.

### Current Behaviour

The dataset aren't annotated

### Steps to Reproduce (for bugs)

I just logged in ```cvat.org``` and signed up, uploaded the dataset (png files), with the classes names, everything is still working till this point, then: 
when I try to upload any format of annotation, I can't get any annotated images.

### Context

keep annotating.

### Your Environment

******************************
I didn't use any local env, I used the public cvat.org website env.
******************************
- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by dragonscandance** [comment]
Having the same issue.

**Comment by Mohammed-Elias** [comment]
@dragonscandance  let me know if you have any solutions!

**Comment by nmanovic** [comment]
@klakhov , could you please look?

**Comment by kylevedder** [comment]
The issue seems to stem from the fact that the page resources are served using HTTPS but the requests to do things like upload files are done under HTTP, and they're consequently being blocked by CORS. This seems to also be impacting other basic functionality such as assigning users to tasks.

**Comment by azhavoro** [comment]
@Mohammed-Elias Hi, the issue should be fixed now, could you please test?

**Comment by kylevedder** [comment]
@azhavoro I can now upload files when I previously could not. Thank you!

**Comment by Mohammed-Elias** [comment]
@azhavoro Thanks a lot for your help, it works like magic!

**Comment by rushabh-v** [comment]
I am facing the same issue. Any suggestions?

**Comment by nmanovic** [comment]
@rushabh-v , you can move your data to our new instance: app.cvat.ai. Use these steps: https://cvat-ai.github.io/cvat/docs/faq/#how-to-migrate-data-from-cvatorg-to-cvatai

**Comment by rushabh-v** [comment]
Thanks for responding @nmanovic!

I tried moving to cvat-ai. But it still shows projects and tasks from my old cvat app after new deployment. 

Here's what I did
```
1. take Backup
2. clone `cvat-ai/cvat` repo.
3. `docker prune` all old images  (otherwise it was saying `cvat_db uses an image, skipping` etc)
4. `docker compose up -d` from new repo.
```

**Comment by nmanovic** [comment]
You need to run `down -v` to stop CVAT containers, delete images and volumes. Be careful, `-v` option will delete your docker volumes for CVAT and it will not be possible to restore.  Please look at documentation for docker-compose: https://docs.docker.com/engine/reference/commandline/compose_down/

**Comment by rushabh-v** [comment]
My apologies if this is a stupid question.

in the documentation it says

```
To update CVAT, you should clone or download the new version of CVAT and rebuild the CVAT docker images as usual.
```

That means clone https://github.com/cvat-ai/cvat and build right?

Note: I was already using the latest code from https://github.com/openvinotoolkit/cvat.

**Comment by nmanovic** [comment]
@rushabh-v , yes. You should clone cvat-ai/cvat and follow installation instructions.

**Comment by rushabh-v** [comment]
I did. pruned old images and volumes and deployed `cvat-ai`. But I am facing the same issue while trying to upload the annotations.

Also, I was not able to upload a backup dataset. It said `Network error`.

**Comment by nmanovic** [comment]
@rushabh-v , try to use app.cvat.ai. If you can reproduce it here, tell me the task number and attach annotations to the issue.

**Comment by rensdebee** [comment]
How can I fix this issue on a local CVAT installation? 
CVAT is running on the HTTP localhost:8080 but accessed via a Cloudflare tunnel using HTTPS/
