### ISSUE TITLE
Cannot dump video annotation from CVAT on onepanel

### ISSUE THREAD

**Issue by KhidirGlal** [openvinotoolkit/cvat#4542]
CVAT do not allow me to dump my video annotation data it keeps loading in infinit-loop without any result.

I have tried to reduce the number of tasks, frames and annotation format but still the same, here is an image of what I am facing 
![image](https://user-images.githubusercontent.com/99792172/161476741-51e983e3-da3a-489a-b12c-32f7fb686a6a.png)

if there is no direct solution, please give a suggestion to proceed with my project. 
THANKS

**Comment by nmanovic** [comment]
@KhidirGlal , we don't support OnePanel. It is an independent company with own CVAT fork. I believe their CVAT version is pretty old. Please contact them for fixing the problem.
