### ISSUE TITLE
Access CVAT on computers from a local office network.

### ISSUE THREAD

**Issue by isspid** [openvinotoolkit/cvat#4549]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Expected Behaviour

The process of accessing CVAT from other computers in a network, or from the internet should be explained clearer. 

### Current Behaviour

I want to access CVAT from computers which are connected via an office network so that teams can work together to annotate images. What I currently do is follow the guide for the installation, get CVAT up and running and then try to access it from another computer using my network ip address and adding :8080 but this doesn't seem to work. Before this i run `export CVAT_HOST=<YOUR_HOSTNAME_OR_IP>`. After doing this nothing happens, when trying to access it from another computer, 404 page not found comes up. 

### Possible Solution

I understand that other people have managed to make this work, but for the life of me I can't and it probably is so because of the lack of my skills. I would really appreciate it a step by step guide, not simply a reference to the documentation, since the documentation only contains a couple of lines with regards to this. If this is too much to ask or there is no support offered for this simple of an issue, please let me know and I will close the issue. 

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):  
Author: Boris Sekachev <boris.sekachev@intel.com>
Date:   Tue Nov 23 10:34:03 2021 +0300

    Export rotation field when backup a task (#3932) 
- Docker version `docker version` (e.g. Docker 17.0.05): 
- $ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:13:04 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.6.0 (75818)
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:06:05 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@isspid 

Please share ``docker ps`` output from the machine where CVAT container is up. 
And be sure that you can ping IP address of machine where CVAT is located from another machine. 

Also try to do ``docker-compose down`` before ``docker-compose up`` (with correctly exported env variable CVAT_HOST)

**Comment by isspid** [comment]
This is my docker ps output:
![image](https://user-images.githubusercontent.com/91065022/162374130-17562823-6b1c-451d-a7f0-8f50c788061c.png)


This is my ipconfig output:
![image](https://user-images.githubusercontent.com/91065022/162374228-2af2e56f-6536-4a32-bc1f-d949d427b71b.png)

The commant I run for the exportation of CVAT_HOST is `export CVAT_HOST=10.5.4.25`

**Comment by bsekachev** [comment]
Have you installed CVAT under WSL? If yes, probably CVAT can not be binded to this ``10.5.4.25`` IP. 
Try to open CVAT on host PC using ``172.23.128.1:8080``

**Comment by nmanovic** [comment]
@isspid , the problem here that it is very difficult to predict all possible problems which a user can have with the network configuration. Network configuration is a complex topic and my team doesn't have huge expertise in the area. For example, proxy, VPN, and firewall could create network issues which are difficult to investigate.

I hope that you find the problem and help us improve the documentation (use [edit this page](https://github.com/openvinotoolkit/cvat/edit/develop/site/content/en/docs/faq.md)): https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

I will close the issue.
