### ISSUE TITLE
Job assignee can not access the task

### ISSUE THREAD

**Issue by qin2294096** [openvinotoolkit/cvat#4558]
Current behavior: After Identity Access Management implementation, annotators are not able to see a task if they assigned only to jobs.

My question is: How a regular job_assignee/worker without extra permissions can access the task and do annotation/review/accept jobs?

**Comment by qin2294096** [comment]
![sendpix0](https://user-images.githubusercontent.com/54561764/162561834-0ef9909f-6e19-4af8-b8d4-3b867a60faaf.jpg)
![sendpix2](https://user-images.githubusercontent.com/54561764/162561837-1dfdb8c7-aa54-487c-9534-a0738d977594.jpg)
![sendpix3](https://user-images.githubusercontent.com/54561764/162561841-689ee324-82fa-4dce-b266-303d777b3c38.jpg)

**Comment by nmanovic** [comment]
@qin2294096 , you should have one more page with the list of jobs. I don't see it on your screenshot. It is expected that the annotator, which is assigned on a job, cannot access a task.

**Comment by qin2294096** [comment]
@nmanovic, the problem is solved after rebuilding cvat. Thank you very much.
