### ISSUE TITLE
Business user does not see existing projects

### ISSUE THREAD

**Issue by yb-imerit** [openvinotoolkit/cvat#4560]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour
A user in Business group should be able to see existing projects.

### Current Behaviour
Existing and new users in business cannot see existing projects.

### Context
Business user is unable to see existing prjects.

### Your Environment

- Git hash commit (`git log -1`):
commit eb634200e46c1f031739b13e9ac1eeea18251185 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Adam Teuscher <43582901+amteusch@users.noreply.github.com>
Date:   Fri Mar 25 06:30:47 2022 -0600

    Return the response from the AI tool (#4432) (#4505)

    Co-authored-by: Adam Teuscher <adamteuscher@smartvisionworks.com>

- Docker version `docker version` (e.g. Docker 17.0.05):
Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3

- Are you using Docker Swarm or Kubernetes?
No

- Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu-18.04

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@yb-imerit , The difference between 'business' and 'user' roles are minimum. The business role doesn't have limitations on the number of projects and tasks which such user can create. Visibility of projects and tasks should be solve using organizations. An organization can have members with different roles (e.g., worker, supervisor, maintainer, owner). These roles have effect on visibility of different objects in an organization.
