### ISSUE TITLE
'Truncated' attribute option ?

### ISSUE THREAD

**Issue by whiteplatin** [openvinotoolkit/cvat#4572]
Hi,

How can I label an object as truncated similar to "occluded property" ?

**Comment by nmanovic** [comment]
@whiteplatin , you can add custom attributes for any label. Please read documentation: https://openvinotoolkit.github.io/cvat/docs/manual/basics/creating_an_annotation_task/#labels

I will close the issue. Please don't hesitate to reopen, if the question isn't solved. Please ask our gitter community: https://gitter.im/opencv-cvat/public
