### ISSUE TITLE
Could not get models from the server

### ISSUE THREAD

**Issue by curiositer** [openvinotoolkit/cvat#4627]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I used the configuration file related to the yolov5 model provided in the project, and wanted to perform automatic labeling.

### Current Behaviour
Follow the given tutorial`https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/`, but I just cannot see any model in Model on the UI. And when I open the F12 console, it says`cvat-app.tsx:283 Error: Request failed with status code 503. "HTTPConnectionPool(host='nuclio', port=8070): Max retries exceeded with url: /api/functions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc45980d970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))".`

### Possible Solution

Follow the issue`https://github.com/openvinotoolkit/cvat/issues/4525`, I provided cvat.txt above.
[cvat.txt](https://github.com/openvinotoolkit/cvat/files/8649922/cvat.txt)
I also provided the docker logs about nuctl.
[nuctl_yolov5.txt](https://github.com/openvinotoolkit/cvat/files/8649949/nuctl_yolov5.txt)

### Steps to Reproduce (for bugs)

1. Searched on google, but I cannot find any resolution.
2. Reinstalled it again, but it didn't solve the problem.

### Your Environment

- Git hash commit (`git log -1`):commit ba417
- ubuntu 18.04
- Docker Version=20.10.15
- nuclio dashboard version=1.5.16

Thanks!

**Comment by piwawa** [comment]
> Thanks. I really forgot to cancel the proxy setting.

请问你怎么解决的？是不是unset http_proxy? 你修改`docker-compose.serverless.yml`文件了吗

**Comment by Thunderstring** [comment]
Please, how did you solve this problem? I can run other models but can't run mine with the error: Request failed with status code 503. "HTTPConnectionPool(host='nuclio', port...

**Comment by piwawa** [comment]
> Please, how did you solve this problem? I can run other models but can't run mine with the error: Request failed with status code 503. "HTTPConnectionPool(host='nuclio', port...

你怎么配置的？我一个模型都调用不了，全是503，nucilo都配置正常

**Comment by curiositer** [comment]
> 

检查一下终端代理，配置文件代理，保持一致就可以，时间有点久了不大记得了

**Comment by curiositer** [comment]
> > Thanks. I really forgot to cancel the proxy setting.
> 
> 请问你怎么解决的？是不是unset http_proxy? 你修改`docker-compose.serverless.yml`文件了吗

检查一下终端代理，配置文件代理，保持一致就可以，时间有点久了不大记得了

**Comment by piwawa** [comment]
> 保持

系统Ubuntu，代理用的是clash，全局和系统代理都试过了，也在docker compose里添加了代理环境变量，各种方案都试过了，还剩没法使用自动化标注
