### ISSUE TITLE
could not invite member to the organization

### ISSUE THREAD

**Issue by misbahch6** [openvinotoolkit/cvat#4631]
Could not invite this member "user@host.fr" to the organization
Error: Request failed with status code 400. ["You cannot invite an user with user@host.fr email. It is not a valid email in the system."].

The user I am trying to add have an account on cvat but every time i try to add I get the error. I also tried case sensitive solution as mentioned in previous issues but it did not resolve the problem.

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by misbahch6** [comment]
First had to assign users in django...

**Comment by flaviusfetean** [comment]
> First had to assign users in django...

Can you please clarify what assigning users in django means? I am facing the same problem. Thank you
