### ISSUE TITLE
Cvat draws polygon automatically without auto annotation being enabled

### ISSUE THREAD

**Issue by vinit13792** [openvinotoolkit/cvat#4645]
### Current Behaviour
I have images, on which i draw a lot of polygon masks. After a day or two, i see that other not annotated images, have polygon masks of annotated images. I do not have automatic annotation enabled as it is a Ubuntu VM with cpu only and 32GB RAM.

Any idea why this might be happening?

**Comment by bsekachev** [comment]
Hi @vinit13792 

Maybe you created ``tracks`` instead of ``shapes``?) Tracks are automatically interpolated to further frames.

**Comment by vinit13792** [comment]
Hi @bsekachev !

No I didnt select tracks. I selected shapes. Still it automatically annotates the next one. And when i delete those extra annotations on the next image, the annotations in the original image gets deleted.

**Comment by bsekachev** [comment]
Could you please provide screenshots or gif?

**Comment by vinit13792** [comment]
![c1](https://user-images.githubusercontent.com/25182167/169478493-cf8b80b9-67f3-4e94-926a-ae54ab2dae36.PNG)
![c2](https://user-images.githubusercontent.com/25182167/169478497-29a42656-4ce7-4955-884c-e01a40135626.PNG)

**Comment by bsekachev** [comment]
@vinit13792 
Thanks, but I need the whole screen with other part of CVAT interface

**Comment by vinit13792** [comment]
Please check i have updated the images in previous comment.

**Comment by bsekachev** [comment]
Interesting.. 

What is version of CVAT you are using?
If you update the page, does the problem persist?
Could you please also make one more screenshot where you highlighted one of such extra object? 
Do you have any exception message on the browser console?

**Comment by vinit13792** [comment]
What is version of CVAT you are using?
Server version: 1.7
Core version: 3.17.0
Canvas version: 2.8.0
UI version: 1.25.0

If you update the page, does the problem persist?
What do you mean by update the page? If you mean update the annotations, then yes, the problem persists.

Could you please also make one more screenshot where you highlighted one of such extra object?
![c3](https://user-images.githubusercontent.com/25182167/169481258-0bee6e21-7879-4a9e-a580-6042d7e59a89.PNG)

Do you have any exception message on the browser console?
No exceptions on the browser console.

**Comment by bsekachev** [comment]
> What do you mean by update the page? 

I mean if you press F5.

**Comment by vinit13792** [comment]
> > What do you mean by update the page?
> 
> I mean if you press F5.

The problem still persists

**Comment by bsekachev** [comment]
Is it possible to you to backup this task and provide to us to investigate the problem, or the dataset is private?

**Comment by vinit13792** [comment]
the dataset is private, so cannot share it.

**Comment by bsekachev** [comment]
Object you've highlighted on the latest screenshot is correct, at least as I can see it first time appeared on frame 7.
And also could you please click to I can see the object details in the right sidebar?

**Comment by vinit13792** [comment]
> Object you've highlighted on the latest screenshot is correct, at least as I can see it first time appeared on frame 7. And also could you please click to I can see the object details in the right sidebar?

Please check this image, i have marked the annotation with blue pen.
![c4](https://user-images.githubusercontent.com/25182167/169501287-4362ebd8-ef9a-4ccf-8d9b-01cf4dece8df.PNG)

**Comment by bsekachev** [comment]
@vinit13792 

Okay, now I see. That is a track, as you can also see :)
Tracks are interpolated automatically to further frames as I told before.

**Comment by vinit13792** [comment]
So here's the thing, I used Auto annotate algorithm, to annotate these images. And then uploaded them onto CVAT. The annotators in my team are now complaining that there is this problem. Is there a way i can change the property of the polygon to shape? Annotators use shape to label the image. 

How to resolve this issue?

**Comment by bsekachev** [comment]
You can mark tracks as outside on the following frame, than they will disappear starting from frame where they are outsided. 
![image](https://user-images.githubusercontent.com/40690378/169502911-7406accd-dffe-4346-aa93-679e51fd5c79.png)

Read more here: https://openvinotoolkit.github.io/cvat/docs/manual/basics/track-mode-basics/

Also maybe one hack, not very convenient, but maybe applicable. If you propagate a track to 1 frame further, it creates a shape on the next frame with the same position. Then you can copy this shape to the previous frame and remove original and propagated object. 

Or just redraw objects using shapes.

**Comment by vinit13792** [comment]
So you mean to say if i select that, it would stop propagating to next frame?

But may i know why does this happen?

**Comment by bsekachev** [comment]
> So you mean to say if i select that, it would stop propagating to next frame?
> 
> But may i know why does this happen?

Tracks are used to annotate videofiles, in this case you do not need to annotate each frames, it accelerates the process, but you need to specify where a track starts and ends, and where keyframes are. To specify it outside and keyframe property are used.

**Comment by vinit13792** [comment]
Ohkay, understood. Thanks 👍 :)
