### ISSUE TITLE
Development environment failed

### ISSUE THREAD

**Issue by zuixiaosanlang** [openvinotoolkit/cvat#4650]
![image](https://user-images.githubusercontent.com/20105627/169483066-2ed55a39-2b85-427c-bfdf-ad3f51ac3491.png)

i also try open3d==0.11.2 in base.txt and add pip install libusb-1.0-0

but not work
![image](https://user-images.githubusercontent.com/20105627/169486447-411117d1-4383-45d4-9079-8232f558c7c4.png)
![image](https://user-images.githubusercontent.com/20105627/169486536-f1466845-12b8-4b18-a9c2-6ac44e8a3dcb.png)

python 3.9+ seems only support open3d 0.14+

what can i do , thanks

**Comment by bsekachev** [comment]
@zuixiaosanlang 

Hi, try fix from this branch https://github.com/bsekachev/cvat/tree/bs/open3d_fix

**Comment by zuixiaosanlang** [comment]
@bsekachev 
thank you for reply so fast. i try this branch, but other error occurs
![image](https://user-images.githubusercontent.com/20105627/169498853-6b82d1b9-cf50-479e-ba7f-beb8baf13857.png)

**Comment by bsekachev** [comment]
Are you building it with docker?

**Comment by zuixiaosanlang** [comment]
@bsekachev
i am sorry to disturb again.
when i run the stage "npm ci", error occurs

![2022-05-24 09-30-00屏幕截图](https://user-images.githubusercontent.com/20105627/169930871-e8dc1d67-f874-4b8d-89e8-72907df1d000.png)

**Comment by zuixiaosanlang** [comment]
@bsekachev
hi，i try try the fix branch. But when i create task, error comes
![image](https://user-images.githubusercontent.com/20105627/169987421-c37aa589-973e-4354-ac4a-b1c954d74b21.png)

i do as this
![image](https://user-images.githubusercontent.com/20105627/169987923-63d9da90-fe6c-499d-9077-a943cbe24b96.png)

it donnot mention the redis server

any step i missing??

**Comment by bsekachev** [comment]
Please check if you have installed redis, it was shown in the instructions above.

**Comment by zuixiaosanlang** [comment]
@bsekachev

oo, good. thanks very much
