### ISSUE TITLE
bounding box pixel values (double -> int)

### ISSUE THREAD

**Issue by Petros626** [openvinotoolkit/cvat#4661]
Hey @nmanovic,

https://github.com/openvinotoolkit/datumaro/issues/716 this was a question I discussed with a user. Is there an option to do it without installind further package to get directly the bounding box coordinates in integer values? For my purposes I need integer and my solution was to round the values, but is there a solution from source (CVAT)?

**Comment by nmanovic** [comment]
@Petros626 , let's keep the issue open. In general when a user exports data, we can have some extra options in UI to adjust the output. The main problem that the number of options to transform data can be huge. Thus need to understand needs. I believe we can provide CLI, which can have extra parameters to export data in a desired format and post-process results if it is necessary.

**Comment by Petros626** [comment]
> 

So for now it's not possible to get integer bounding box coordinates or should I follow the advice from the other guy in #716 ?

**Comment by Petros626** [comment]
I found out, that it's ok to get the labels with `floating point pixel coordinates`. 
Using this for exmaple in the `Object Detection API` of **TensorFlow** occurs no problems.
