### ISSUE TITLE
Where is the cvat data stored, (raw images and project/task etc.) on Ubuntu Server?

### ISSUE THREAD

**Issue by waqarsqureshi** [openvinotoolkit/cvat#4675]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

I was curious about where is raw data stored on my server.

**Comment by waqarsqureshi** [comment]
The data is stored in the following directory
/var/lib/docker/volumes/cvat_cvat_data/_data/data
/var/lib/docker/volumes/cvat_cvat_data/_data/projects
/var/lib/docker/volumes/cvat_cvat_data/_data/tasks
/var/lib/docker/volumes/cvat_cvat_data/_data/cache
raw images for a project
/var/lib/docker/volumes/cvat_cvat_data/_data/data/48/raw

**Comment by varungupta31** [comment]
@waqarsqureshi Hi, Please take a look at my issue #4691.
Also, I tried `locate cvat_data` and locate `cvat_data_data`, but nothing showed up.
