### ISSUE TITLE
How to disable Rotation Point Tool ? 

### ISSUE THREAD

**Issue by arcibiyo** [openvinotoolkit/cvat#4698]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
I wanna disable Rotation point tool from interface 

### Current Behaviour
I can't find how to disable this tool 

### Possible Solution
There must be enable/disable feature in cvat/ui repo

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context
**I wanna disable Rotation point tool from interface like below pic**

![image](https://user-images.githubusercontent.com/47760055/174235143-5bdd3e93-2249-478d-9698-dd3640c551d5.png)

### Your Environment
 I am using last release docker and cvat project. 

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by arcibiyo** [comment]
@[nmanovic](https://github.com/nmanovic)   Maybe you can help me about this situation.

**Comment by nmanovic** [comment]
@arcibiyo , probalby in the future each label will have a "type" (box, circle, rbox, point, polygon). It will solve the problem. For now you have to modify the code or ask your annotators don't rotate the box.

**Comment by arcibiyo** [comment]
> @arcibiyo , probalby in the future each label will have a "type" (box, circle, rbox, point, polygon). It will solve the problem. For now you have to modify the code or ask your annotators don't rotate the box.

Thanks @nmanovic

**Comment by arcibiyo** [comment]
> @arcibiyo , probalby in the future each label will have a "type" (box, circle, rbox, point, polygon). It will solve the problem. For now you have to modify the code or ask your annotators don't rotate the box.

Thanks @nmanovic
