### ISSUE TITLE
How to locally develop docker container with changes?

### ISSUE THREAD

**Issue by kkmehta03** [openvinotoolkit/cvat#4705]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

I'm checking out [this](https://github.com/openvinotoolkit/cvat/tree/bs/masks) branch and trying to implement custom changes to the brush tool. 
I want to know how to rebuild the whole container so that the changes are reflected
Currently, with `docker-compose rm` and `docker-compose up` or `docker-compose up --build`, the changes aren't being reflected on the ui. 
is there something missing from my side?

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hello, `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`
