### ISSUE TITLE
Pre-defined set of points as template

### ISSUE THREAD

**Issue by Loc-Vo** [openvinotoolkit/cvat#4711]
Hi,

I am having a use case where we need to pre-defined set of points (rules) for specific label. Whenever a label is selected, a number of points with pre-defined (x,y) show up as a group. Tagger will need to drag those points and put on the object and do adjustment.
By doing so, we can setup rules for each object (number of points and positions)

**Comment by nmanovic** [comment]
@Loc-Vo , we have the feature in our road map.
