### ISSUE TITLE
error getting credentials - err: exit status 1, out: `Could not connect: Connection refused` on docker-compose up

### ISSUE THREAD

**Issue by RAbraham** [openvinotoolkit/cvat#4733]
Hi,
I'm trying to install the latest cvat on our on-premise server and I get the following error.

```shell
rajiv@Zeus:~/software/cvat$ git pull
...ready up to date.
rajiv@Zeus:~/software/cvat$ docker-compose build
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
rajiv@Zeus:~/software/cvat$ docker-compose up -d
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
[+] Running 0/0
 ⠋ cvat_opa Pulling                                                                                                                                                                                   0.0s
error getting credentials - err: exit status 1, out: `Could not connect: Connection refused`

```
### Your Environment

```shell
- Git hash commit (`git log -1`):'
commit d7560bbd39fec68f944515c2591dda74f3764b90 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: ba4175bf b7dba6aa
Author: Nico Galoppo <nico.galoppo@intel.com>
Date:   Tue May 17 11:25:58 2022 -0500

    Merge pull request #4639 from openvinotoolkit/ncgalopp/fix-build

```
- Docker version `docker version` (e.g. Docker 17.0.05):
```
Docker version 20.10.14, build a224086
Docker Compose version v2.6.1

```
- Are you using Docker Swarm or Kubernetes?
A: None of the above
- Operating System and version (e.g. Linux, Windows, MacOS):
A: Ubuntu 18.04

Thanks,
Rajiv

**Comment by azhavoro** [comment]
Looks like a network issue, try to pull explicitly with `docker pull openpolicyagent/opa:0.34.2-rootless`

**Comment by azhavoro** [comment]
Also check your docker credentials if you have them https://docs.docker.com/engine/reference/commandline/login/

**Comment by RAbraham** [comment]
> Looks like a network issue, try to pull explicitly with `docker pull openpolicyagent/opa:0.34.2-rootless`

This worked. and then the erroring command also worked. Thanks! I didn't have to modify my docker credentials.
