### ISSUE TITLE
Maximum timeout value on the task creation

### ISSUE THREAD

**Issue by Rub21** [openvinotoolkit/cvat#475]
Hey Cvat team, We are facing an issue on the task creation, in the beginning, we created the tasks successfully with the same amount of images and with the same images, but now the application throws this error, it is trying to create and when it is in around 60% throws the error.👇 
<img width="540" alt="Screen Shot 2019-06-05 at 9 13 52 AM" src="https://user-images.githubusercontent.com/1152236/58963431-bee1c780-8772-11e9-8e16-1f2294592cbb.png">

**Comment by bsekachev** [comment]
@Rub21 
Once, we have already increased timeout value #136.
We supposed that 4 hours it is enough for any task. 
Okay, as the fastest solution you can change a value like it's done in the patch above.

**Comment by nmanovic** [comment]
I will close the issue as outdated.
