### ISSUE TITLE
Connecting AWS S3 as cloud storage

### ISSUE THREAD

**Issue by darkAlert** [openvinotoolkit/cvat#4753]
Could anyone share an example of manifest.json for AWS S3? I tried to use manifest.json generated for local files but got the error:
"Error: . "Invalid 'manifest.jsonl file structure': 'extension' is required, but not found"."

**Comment by FrankUSC** [comment]
The generated file should look like this:
There is a extension field for the file type
```
{"version":"1.0"}
{"type":"images"}
{"name":"000000","extension":".jpeg","width":720,"height":405,"meta":{"related_images":[]},"checksum":"548918ec4b56132a5cff1d4acabe9947"}
{"name":"000001","extension":".jpeg","width":183,"height":275,"meta":{"related_images":[]},"checksum":"4b4eefd03cc6a45c1c068b98477fb639"}

```

**Comment by darkAlert** [comment]
thank you very much! it is working!

**Comment by darkAlert** [comment]
> I connected my s3 bucket to cvat, I am confused as to how one can maintain multiple projects in the same s3 bucket. Something like `bucket-name/project-1/manifest.json` and `bucket-name/project-2/manifest.json` . It throws an error if I put another manifest file in the same directory or different folder in the s3 (`same storage already exists`). How can I provide the folder prefix , i.e, project name while creating storage.

You can have multiple manifest.jsonl with different names (e.g., project1.jsonl, project2.jsonl), but they must be in the root folder.

**Comment by divinit7** [comment]
Thank you so much! I was adding new cloud storage for new project instead of adding multiple manifest files in the same one.

**Comment by mherzog01** [comment]
> > I connected my s3 bucket to cvat, I am confused as to how one can maintain multiple projects in the same s3 bucket. Something like `bucket-name/project-1/manifest.json` and `bucket-name/project-2/manifest.json` . It throws an error if I put another manifest file in the same directory or different folder in the s3 (`same storage already exists`). How can I provide the folder prefix , i.e, project name while creating storage.
> 
> You can have multiple manifest.jsonl with different names (e.g., project1.jsonl, project2.jsonl), but they must be in the root folder.

@darkAlert I was not able to create a task for images in my S3 bucket until I moved the manifest file to the root of the bucket.  Should that be documented in https://opencv.github.io/cvat/docs/manual/basics/attach-cloud-storage/#attach-new-cloud-storage?
