### ISSUE TITLE
no permission error by trying to resolve issues 

### ISSUE THREAD

**Issue by arasharchor** [openvinotoolkit/cvat#4754]
I have an annotator id. I am trying to resolve issues after solving them, but I constantly receive no permission error.  Could you please kindly guide on the reason for this phenomena?

**Comment by nmanovic** [comment]
@arasharchor , not enough information. Could you please provide steps to reproduce?

**Comment by arasharchor** [comment]
@nmanovic 
![image](https://user-images.githubusercontent.com/12903362/179623370-c1095713-9538-4728-9e04-5bd25fb1a3f2.png)
Having "user" account, I am not able to resolve an issue, created during QC by admin.
