### ISSUE TITLE
Data leak for self-created users

### ISSUE THREAD

**Issue by xXxTheUserxXx** [openvinotoolkit/cvat#4757]
Hello,

I use CVAT and am very happy with it. So I want to give some feedback to improve the software.
This Issue does not need to be solved. I found a workarround.

I use CVAT on an AWS server and everyone has access to it. I also use a shared path:

https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#share-path

The problem is that anyone who creates their own account, is assigned to the group user and has access to the shared path and can steal my data.

If that's the way it should be, I think it should be changed.

If this post is somehow redundant, wrong or incomprehensible, you can simply delete it.

Siccerelly,
xXxTheUserxXx

**Comment by nmanovic** [comment]
@xXxTheUserxXx , thanks for the feedback. Need to think how to protect share-path. Did you try Cloud Storages: https://openvinotoolkit.github.io/cvat/docs/manual/basics/attach-cloud-storage/?

**Comment by xXxTheUserxXx** [comment]
@[nmanovic](https://github.com/nmanovic),

currently the files are stored on a private AWS FSx file server. But we will think about using cloud storage. Thank you for this advice.

Maybe another possible improvement would be that an account assigned to the group worker doesn't even see that there are "shared files". At the moment, if he tries to create a new task, he can see that there are shared files and folders, but he cannot create a task.

**Comment by ninafiona** [comment]
> The problem is that anyone who creates their own account, is assigned to the group user.

How can I change this behaviour? I don't want new users to have any rights. 

@nmanovic
