### ISSUE TITLE
How do you kill a popular, open-source project in two steps ?

### ISSUE THREAD

**Issue by ragmondo** [openvinotoolkit/cvat#4758]
This question is not trying to be flippant, but somewhere between v1.x and 2.1 a change went in that breaks cvat when used on a network.

That change has now (well a few weeks ago) propagated to the public system (cvat.org)

The maintainers of cvat.org are not responding to any user queries. There is no path for escalation. See all the individuals below who have tried to get this resolved.

**** PLEASE **** fix the cross server origin issue when deploying to a network 

Request URL: http://xxxxxxx.us-east-1.elb.amazonaws.com/api/auth/login?org=
Request Method: POST
Status Code: 405 Not Allowed
Remote Address: 3.210.238.184:80
Referrer Policy: strict-origin-when-cross-origin

see:

[CVAT is down](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-is-down/td-p/1400499)
[Cvat.org](http://cvat.org/)
[Due to cvat server down, how can I access and get my latest data from server?](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Due-to-cvat-server-down-how-can-I-access-and-get-my-latest-data/td-p/1399283)
[Cannot login to CVAT](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Cannot-login-to-CVAT/td-p/1394143)
[Not been able to login into the CVAT](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Not-been-able-to-login-into-the-CVAT/td-p/1395409)
[Cvat server is down](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Cvat-server-is-down/td-p/1397772)
[Cannot login or create a new account on CVAT](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Cannot-login-or-create-a-new-account-on-CVAT/td-p/1396147)
[Cannot access CVAT online server](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Cannot-access-CVAT-online-server/td-p/1396843)
[CVAT online tool](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-online-tool/td-p/1395423)
[Cvat annotation tool](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Cvat-annotation-tool/td-p/1395170)
[CVAT Down For Days](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-Down-For-Days/td-p/1394825)
[CVAT annotation tool](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-annotation-tool/td-p/1391633)
[Could not login ](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Could-not-login-CVAT-org/td-p/1391932)[CVAT.org](http://cvat.org/)
[CVAT online tool not available](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-online-tool-not-available/td-p/1394533)
[CVAT server stability](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-server-stability/td-p/1394218)
[CVAT server is not working](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-server-is-not-working/td-p/1394065)
[CVAT.org Stability Issues](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-org-Stability-Issues/td-p/1392692)
[CVAT server is not working](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/CVAT-server-is-not-working/td-p/1391979)

GitHub
[Could not login ](https://github.com/openvinotoolkit/cvat/issues/4685)[CVAT.org](http://cvat.org/)

**Comment by ragmondo** [comment]
From cvat.org - the same error

![image](https://user-images.githubusercontent.com/616888/179181378-859c65a4-628e-4145-92df-4a344250ad2a.png)

**Comment by nmanovic** [comment]
@ragmondo , cvat.org is down by another reason. It is not `fix the cross server origin issue`. CVAT.org was not updated for 3 months already. I understand your indignation. The core team cannot fix any problems right now due to [Intel Suspends Operations in Russia](https://www.intel.com/content/www/us/en/newsroom/news/russia-business-statement.html).

P.S. I believe already next week the community will see some changes. Please be patient.

**Comment by ragmondo** [comment]
Ok - I apologise that I confused the two issues and I am deeply sorry to hear that world issues are affecting this project. I hope that you manage to get things back on the rails soon. On the plus side, I've written a convertor for CVAT Image format to Apple's CreateML format. I can't raise a pull request just yet as the code runs independently on an exported unzipped file, but if I can figure out how to integrate it then I will.

**Comment by nmanovic** [comment]
@ragmondo , you can see how other dataset formats are implemented in CVAT. Basically we add support of a format into https://github.com/openvinotoolkit/datumaro and after that it is more or less trivial to add such support into CVAT.

**Comment by bsekachev** [comment]
@ragmondo 

Online tool: https://app.cvat.ai/ 
Work is being done also to restore access to cvat.org, but dedline is unclear because it out of our management now.

**Comment by ragmondo** [comment]
> https://app.cvat.ai/

Much appreciated. I am giving it a test run now but I am very much appreciate of your efforts in this matter. I have another query which is basically my inability to self-host an installation as I get the CORS error (which I mistakenly conflated with the cvat.org unavailability issue) but I'll keep researching.
