### ISSUE TITLE
Azure Deployment Guide 

### ISSUE THREAD

**Issue by gcosne** [openvinotoolkit/cvat#476]
What is the current state of Azure deployment guide ? 

I tried building the docker image with *Azure Kubernetes Service* and I have the following error : 

**Step 15/58 :** RUN adduser --shell /bin/bash --disabled-password --gecos "" ${USER}
 ---> Running in 7c8137d60f2c
adduser: Only one or two names allowed.‌
##[error]The command '/bin/sh -c adduser --shell /bin/bash --disabled-password --gecos "" ${USER}' returned a non-zero code: 1
##[error]/usr/bin/docker failed with return code: 1
##[section]Finishing: Build an image

Thank you for your help, 

Gautier

**Comment by nmanovic** [comment]
@gcosne , need to check. Internally we don't use Azure. Could you please ask the question on our gitter channel as well? At the same time we will check these instructions on our side and try to fix.

**Comment by gui2dev** [comment]
@gcosne you have to specify a username.
In your "build image" task, in the argument field, you have to specify :

> --build-arg USER=username

**Comment by JParzival** [comment]
I am interested in this!
@taranais probably too!

**Comment by nmanovic** [comment]
Let's close the issue as outdated.
