### ISSUE TITLE
bug(cvat.org): cvat.org connection refused

### ISSUE THREAD

**Issue by sicoyle** [openvinotoolkit/cvat#4777]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

I navigate to [cvat.org](http://cvat.org/) and can see the UI for the tool on Chrome.

### Current Behaviour

I see an `ERR_CONNECTION_REFUSED` when I go to [cvat.org](http://cvat.org/).
See picture for more details.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/25728646/180575624-88a5da5e-cadd-4c5f-9c07-5eba570b0c30.png">

### Possible Solution

I have tried alternative browsers and see the same error. Is there something that has impacted the hosting of `cvat.org`?

### Steps to Reproduce (for bugs)

1. Go to [cvat.org](http://cvat.org/)
1. See error message: "cvat.org refused to connect" with an `ERR_CONNECTION_REFUSED`

### Context

I would like to use `cvat.org` and am unable to do so at this time. I would like to set up an annotation project.

### Your Environment
`cvat.org`

### Next steps
Adding @NeethuES-intel for updates.

**Comment by nmanovic** [comment]
@sicoyle , It should be online in the nearest future. But you can try this one: http://cvat.ai (click `Try for free`).
<img width="609" alt="image" src="https://user-images.githubusercontent.com/40690625/180587719-4c2a9214-e86f-494a-a0fd-43f3687d4928.png">

The new GitHub repo from the CVAT core team: https://github.com/cvat-ai/cvat. Please star us on GitHub!

**Comment by ActiveChooN** [comment]
Hi @sicoyle, cvat.org was on maintenance. Should be work fine by now

**Comment by nmanovic** [comment]
@sicoyle , https://cvat-ai.github.io/cvat/docs/faq/#how-to-migrate-data-from-cvatorg-to-cvatai

**Comment by sicoyle** [comment]
Thank y'all so much for the links and updates!

**Comment by sicoyle** [comment]
Issue resolved!
