### ISSUE TITLE
Unable to login and sign up 

### ISSUE THREAD

**Issue by Pawan-Ambhore** [openvinotoolkit/cvat#4799]
I have installed cvat development environment on my Ubuntu Operating system. after completing the setup, when i tried to open cvat on localhost 3000 i get the login error,
![407cac36-e442-4955-a2a4-be30afd72c78](https://user-images.githubusercontent.com/72788746/183903431-c2a4ae89-71b7-4af8-935c-120d71d56e6c.jpg)

![2ed9d159-b303-4bc3-bc5e-4a8da9d59b18](https://user-images.githubusercontent.com/72788746/183903698-a26e2dda-fbc7-4579-98d7-d44bc25bbbc1.jpg)

i was not able to find out the solution.

**Comment by ActiveChooN** [comment]
Hi, @Pawan-Ambhore, did you run cvat server?

**Comment by Pawan-Ambhore** [comment]
Is there any different command for running the server? I have used npm run
start:cvat-ui
Command. For starting the server which command should I use?

**Comment by nmanovic** [comment]
@Pawan-Ambhore , `npm run start:cvat-ui` starts only CVAT UI. Please read contribution guide: https://cvat-ai.github.io/cvat/docs/contributing/development-environment/
