### ISSUE TITLE
Merging tasks/XML files together

### ISSUE THREAD

**Issue by mattavallone** [openvinotoolkit/cvat#608]
Hello,

Is there a way to merge two tasks together or a script to merge multiple annotation files into one? I had broken up annotating the same dataset into multiple tasks and wanted a clean way to merge them together. I tried combining the XML files manually (copy and paste) before converting to TFRecord (using the converter.py inside cvat/utils/tfrecords) but when I tested the TFRecord file, it says 

"tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 4154189"

Any assistance on this would be greatly appreciated.

**Comment by nmanovic** [comment]
@mattavallone , there is no such opportunity at the moment. I will keep your feature request open till we have a functionality to cover the request.

**Comment by LukeAI** [comment]
This would also be helpful for my workflow!

**Comment by hairychris** [comment]
Does anyone have a workaround for doing this?

**Comment by ValerianGonnot** [comment]
I am also interested in this

**Comment by shaojun** [comment]
waiting for this feature as well.

**Comment by agazibaric** [comment]
This feature would be really helpful

**Comment by nikste** [comment]
any update on this yet?

**Comment by zhiltsov-max** [comment]
After #3365 multiple tasks can be exported as a single dataset from CVAT via projects.

Also, you can use [Datumaro](https://github.com/openvinotoolkit/datumaro#installation) to merge existing annotations and datasets following this comment: https://github.com/openvinotoolkit/datumaro/issues/16#issuecomment-893260740.

**Comment by nmanovic** [comment]
I will close the issue. It was implemented.

**Comment by ccomkhj** [comment]
anyone wants to have gui interface for merging datasets, I made simple gui interface using streamlit [here](https://github.com/ccomkhj/datumaro-gui)
