### ISSUE TITLE
No duplicate storage for image only jobs

### ISSUE THREAD

**Issue by KaiLicht** [openvinotoolkit/cvat#621]
Hey! 
I'm mostly working on image recognition problems (no video). For such problems, it would really make sense to only select from a mounted folder despite loading all images into the container. Does that make sense?

Thanks!

**Comment by KaiLicht** [comment]
I just found #204 which should be pretty much the same thing

**Comment by nmanovic** [comment]
@KaiLicht , I will close the issue as a duplicate. We improved the data flow. In many cases images should not be copied by default (only cache some data for effective data streaming from the server to a browser).
