### ISSUE TITLE
Multiple groups for the same object (now only one is possible)

### ISSUE THREAD

**Issue by synsis** [openvinotoolkit/cvat#698]
The relation between groups and the objects is one-to-many, but the relation between object to group is one-to-one. It is enough for easy projects, but I am doing something complicated, and if you can change the structures between the groups and objects, it would be very useful as well.

Cheers

**Comment by nmanovic** [comment]
@synsis , could you please describe your task?

**Comment by synsis** [comment]
@nmanovic Thanks for your reply.
I am trying to label a machine structure, the nuts linked by the same string and the linked string should be made into a group. but some nuts are linked by different strings, so these nuts should be marked into several different groups. However, so far, all the label applications only support that one object can only belong to one group. It is painful for me and my task.

**Comment by nmanovic** [comment]
@synsis , could you please give me a visual example with desired annotations?

**Comment by nmanovic** [comment]
@synsis , I believe I don't have enough information to understand how the feature should be implemented. I will close the issue as outdated. Nobody from our community voted for the feature.
