### ISSUE TITLE
Host Container on Docker Hub

### ISSUE THREAD

**Issue by JulianWgs** [openvinotoolkit/cvat#7]
Could you please connect this repository to docker hub. This way it would be possible just to download to already built container, since the build process is rather lengthy.

**Comment by nmanovic** [comment]
Hi,

Let's try to do that. It can be a nice feature especially if you want to try the tool quickly. There are several problems with the approach:
- If the user wants to change configuration it is necessary to build the image again but probably it will be much faster
- There are several options to build the image (e.g. with TF or without TF)

But in any case it will be a good experiment. We will see how much user will decide to use the image out of the box.

**Comment by nmanovic** [comment]
Hi,

It seems that the feature isn't so easy as it looks like. Our image is based on Ubuntu. Ubuntu has [Intellectual property rights policy](https://www.ubuntu.com/legal/terms-and-policies/intellectual-property-policy):

> Any redistribution of modified versions of Ubuntu must be approved, certified or provided by Canonical if you are going to associate it with the Trademarks. Otherwise you must remove and replace the Trademarks and will need to recompile the source code to create your own binaries. This does not affect your rights under any open source licence applicable to any of the components of Ubuntu. If you need us to approve, certify or provide modified versions for redistribution you will require a licence agreement from Canonical, for which you may be required to pay. For further information, please contact us (as set out below).

As far as I understand any image which is based on Ubuntu and redistributed through Docker Hub violates the policy. In general to be compliant  it is necessary to use another distribution and check all packages which it includes by default. It is a big piece of work.

Thus I have decided to close the issue. Probably it is better to invest time into creating a demo server.

**Comment by JulianWgs** [comment]
I don't think this policy applies to docker images using ubuntu as the base image.

1. Take a look at https://github.com/sameersbn/docker-redmine (and other projects from sameersbn). Its also using a ubuntu base image. The project is over 4 years old and has over 800 commits. I think if canonical would have something against that, they wouldve done something.
2. The docker image is officially by canonical and nothing on https://hub.docker.com/_/ubuntu/ says it is illegal to redistribute ubuntu based images. If I would be on there legal team, I would have definitely put a hint there!

However those are not definitive proofs, but reasons to reopen the issue.

If you tell me how to convince you that a docker image would be legal, then I will take care of it.
Greetings!

**Comment by nmanovic** [comment]
@JulianWgs ,

1. Unfortunately I cannot accept it as a proof. Maybe I'm wrong but I have to follow strict policies and guidelines. Also I consulted with experts in this area.
2. [Intellectual property rights policy](https://www.ubuntu.com/legal/terms-and-policies/intellectual-property-policy) has the following statements:

> You can redistribute Ubuntu, but only where there has been no modification to it.

> You can redistribute Ubuntu in its unmodified form, complete with the installer images and packages provided by Canonical (this includes the publication or launch of virtual machine images).

If anybody creates and supports images for CVAT we will be glad to specify the information somethere (need to check that). I will reopen the issue. Maybe someone from community will find a solution.

P.S. But I believe it is much better to spend time and energy to build a demo server.

**Comment by nmanovic** [comment]
Nice post: https://www.reddit.com/r/linux/comments/3ezwi4/canonical_explains_its_ip_policy_regarding_docker/

**Comment by JulianWgs** [comment]
So why isnt this happening then? Do you need help?

**Comment by nmanovic** [comment]
Hi @JulianWgs ,

It states that we cannot redistribute ubuntu docker image:

> Redistribution of non modified Ubuntu images is OK

> Distributing a Docker file (a text file) containing the words "FROM ubuntu" is permitted

> Private distribution of Docker images containing Ubuntu to your friends is OK if you are able to apply the Canonical definition of personal use (someone you are confortable giving root).

> Contact Canonical for everything else (get a license, it's not explicitely permitted)

**Comment by Langhalsdino** [comment]
Why not switching to debian?

I am currently trying to get cvat up and running in kubernetes. In the process i started to change the dockerfiles to get faster builds. 

For the docker.ui simply switch the image to:
`FROM node:10.16.3-buster-slim AS cvat-ui`

I will create a pull request after i managed to get it working in our kubernetes cluster.

**Comment by nmanovic** [comment]
@Langhalsdino , if you can help us and optimize CVAT images it will be awesome. Look forward for PRs from you.

**Comment by Langhalsdino** [comment]
since gitlab is currently down, i a have a little bit of time on my hand and try to move both two buster-slim :)

**Comment by Langhalsdino** [comment]
@nmanovic I have no legal experience therefore, can you check wether or not we are allowed to publish software like ffmpeg, gstreamer0.10-ffmpeg, unrar-free provided by http://www.deb-multimedia.org (non-free) on hub.docker.com? Furthermore check the rest of the used software stack?

I will create a pull request with my changes to the docker files and reference them here.

It seems like it worked, but i have to check a few more thinks before creating the PR :)

**Comment by Langhalsdino** [comment]
Looking for some help testing the new docker container (CUDA support, ...).

Furthermore, ci integration for publishing it on Docker Hub is needed :)
What is the timeline on this issue?

**Comment by nmanovic** [comment]
It seems that OpenVINO is on DockerHub. Thus CVAT image also can be placed on DockerHub.

https://hub.docker.com/u/openvino
http://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_docker_linux.html

**Comment by nmanovic** [comment]
[cvat_licenses.xlsx](https://github.com/opencv/cvat/files/4053299/cvat_licenses.xlsx)

**Comment by Langhalsdino** [comment]
Thank you for sharing the software licenses @nmanovic 

I checked a few of the unknown licenses and if I am not mistaken unrar could be replaced by their open-source counterpart unrar-free as shown in the Dockerfile and prev. pull request: https://github.com/opencv/cvat/blob/c7d1c82aeb0a81f26f03673050c33de83b57bfb7/Dockerfile 

Furthermore, the GLP V2 license can replace UNKNOWN in the excel of pkg-config is GLP V2
SRC: https://www.freedesktop.org/wiki/Software/pkg-config/

Why is CVAT needing the following X11 extensions: 
libxext6 -> X11 miscellaneous extension library
libsm6 -> X11 Session Management library

So what are the next steps for moving forward to a prebuild DockerHub version of CVAT?

Furthermore, why are we using Ubuntu and not Debian?

**Comment by nmanovic** [comment]
@Langhalsdino ,

The file is only for my reference. I'm working now to clean up packages and prepare dockerfiles for DockerHub.

**Comment by nmanovic** [comment]
[ip-plan.zip](https://github.com/opencv/cvat/files/4170629/ip-plan.zip)

**Comment by nmanovic** [comment]
[npm_audit.txt](https://github.com/opencv/cvat/files/4299277/npm_audit.txt)

**Comment by nmanovic** [comment]
[bandit_cvat_results.txt](https://github.com/opencv/cvat/files/4312903/bandit_cvat_results.txt)

[bandit_datumaro_results.txt](https://github.com/opencv/cvat/files/4312904/bandit_datumaro_results.txt)
