### ISSUE TITLE
Enhancement Request - Provide capability to allow for simple JS plugin triggering to send performance data

### ISSUE THREAD

**Issue by HeffRaleigh** [openvinotoolkit/cvat#727]
@nmanovic I thought about how to submit this enhancement request after we last spoke and decided the best path forward was to consider including in CVAT the ability to easily insert JS scripts designed to gather then send task completion (aka Annotator Performance) data to whatever BI reporting repository best suits their needs.  

This could be a plug-in based design or just a code container of sorts in the admin panel that allows a person to drop in some JS code, add a range of variables into the code, and target where the code will execute within the CVAT code.

Basic task completion data would consist of the following:
- Task Start Time - Defined by when an image/frame first completes loading into the annotation UE
- Task Finish Time - Defined by when the user clicks the next button, but ideally CVAT would be enhanced to include a "Submit" or "Complete" button the user would click on when they were finished annotating the current image.  
- Task ID - Defined as the Job ID + Task ID + Image File Name/Video File Name+FrameNumber
- Annotator ID - Defined as the email address for the currently logged in user.

Example of JS CloudFactory uses for accomplishing this:

var cfPulse = new CFPulse({
	apiKey: '<Insert_CloudFactory_API_Key>',
	trackingId: '<Insert_CloudFactory_Workstream_ID>'
});

cfPulse.taskStarted({
	   	taskId: '<Task_ID>',
	  	workerId: '<Annotator_ID>'
});

document.getElementById('nextButton').addEventListener('click', function(){
  cfPulse.taskCompleted();
});

Please let me know if you have any questions.

Thanks!

**Comment by nmanovic** [comment]
We have an issue about web hooks. Probably it can cover the issue particular. I will close it as a duplicate.

**Comment by nmanovic** [comment]
https://github.com/openvinotoolkit/cvat/issues/2657
