### ISSUE TITLE
Ability to change attributes by keyboard without AAM mode

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#78]
It can be more convenient to change attributes by shortcuts without necessary to go to attribute annotation mode. You just move cursor and setup attributes by keyboard instead of mouse. In such case you don't need find object in right panel.

**Comment by nmanovic** [comment]
The feature was deprioritized due to other more agent requests.

**Comment by nmanovic** [comment]
I will close the issue as outdated.
