### ISSUE TITLE
Clone tasks to provide a default set of parameters

### ISSUE THREAD

**Issue by egrinstein** [openvinotoolkit/cvat#817]
Hello,

It would be interesting to have a "default task" object, a mechanism which would allow to setup a task without having to specify the form every time.

This would be interesting for annotators who only want to upload images to the server, but should not define the annotation task themselves.

**Comment by nmanovic** [comment]
@egrinstein ,

Probably the way to do that is to "clone" a task and provide new data. Do you want to invest resources to implement such feature?

**Comment by egrinstein** [comment]
Maybe the right thing to do would be to have a Database table called "LabelSet", and the input form for Labels could show the available ones.

So, for example, I could create the "Vehicle Annotation" LabelSet, containing the string for the labels.

Then, one could choose "Vehicle Annotation" in the labels and get these loaded.

The labels are loaded pretty easily using the dropdown, so I don't think investing resources in this is needed right now, but maybe it's a good backlog item.

**Comment by nmanovic** [comment]
At the moment I see only one way to implement the feature: clone a task on server using REST API or in UI. Thus it will be possible to easily create similar tasks.

**Comment by egrinstein** [comment]
Hey @nmanovic . Indeed, I found the REST API to be very suitable for such needs.

**Comment by nmanovic** [comment]
@egrinstein , we have improved UI and now it is much more easy to create new tasks and specify labels. I will close the issue as outdated.
