### ISSUE TITLE
Git sync for video xml format

### ISSUE THREAD

**Issue by advnic93** [openvinotoolkit/cvat#849]
The git sync functionality is very useful and working well for us. However, it seems that currently it is only possible to sync the annotations in the `cvat xml 1.1 for images` format. For us it'd be very helpful if we could sync the annotations also in the `cvat xml 1.1 for videos` format. Is this possible already?

**Comment by nmanovic** [comment]
hi @advnic93 , annotation format is chosen automatically based on uploaded data. For not it is not possible to choose manually.

Could you please describe your workflow? We are trying to improve `dataset repository` functionality and it is worth to know how people use the feature internally.

**Comment by advnic93** [comment]
Hi @nmanovic, thanks for your swift reply. So what we do is that we:
1) create a new task
2) upload the frames and our pre-generated annotation file in `cvat xml 1.1 for videos` format
3) Improve the detection (polygons) and tracking annotations
4) Would then like to automatically download the supervised annotation file from the synced git repo

Thus, we do upload the annotation file in the `cvat xml 1.1 for videos` format and also see the tracking feature in the cvat tool. However, in the synced git repo there is only the `cvat xml 1.1 for images` annotation available. Thus, I am not sure it works as intended here?

**Comment by nmanovic** [comment]
@advnic93 , now it is possible to choose the format. I will close the issue.

![image](https://user-images.githubusercontent.com/40690625/143779504-79dde131-a3b2-4381-80d9-94b6a97d22ba.png)
