### ISSUE TITLE
Download raw data from the server

### ISSUE THREAD

**Issue by ArefAz** [openvinotoolkit/cvat#861]
Hello,

Is there anyway that I could download the videos from the CVAT server remotely? So I can extract training data from the videos annotated and uploaded by other users.

Thanks.

**Comment by nmanovic** [comment]
@ArefAz , the functionality isn't ready yet. One PR was merged and now we have REST API to download datasets. Here another PR: https://github.com/opencv/cvat/pull/834 to add a button in UI to download datasets. But they will return you `compressed` images + annotations. When I say `compressed` I mean that quality of images will be poor (the same as used for annotation process). We are working on a feature to return images and frames in the original quality.
