### ISSUE TITLE
Ability to specify number of tasks per page in UI

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#898]

**Comment by nmanovic** [comment]
it should be fixed by https://github.com/opencv/cvat/pull/884

**Comment by nmanovic** [comment]
It is about UI but #884 covers only the server part.

**Comment by nmanovic** [comment]
I will close the issue. Server has page_size parameter. Default value for UI looks reasonable. Let's wait more feedbacks from community.
