### ISSUE TITLE
Installation guide installs "develop" branch

### ISSUE THREAD

**Issue by egrinstein** [openvinotoolkit/cvat#911]
This might not be an issue, but it has created some trouble here so I thought it might be worth reporting. 

The installation guide says to clone https://github.com/opencv/cvat/ , which points to the branch origin/develop, and not master. 

I thought this guide was meant for an end user, so it would be better to make the default branch to be master. 

The new version on the develop branch has a different label adding mechanism which is not documented.

Thank you,

Eric

**Comment by nmanovic** [comment]
@egrinstein , probably we can mention that there are multiple options: develop branch, a stable release, etc. I agree, need to modify documentation.

Could you please help us to improve documentation and prepare a PR?

**Comment by nmanovic** [comment]
I will close the issue as outdated.
