### ISSUE TITLE
Copying a “list of labels” from one task to another task

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#919]
After last update, it is not possible to copy "label list" from one task to another.
An error occurred while copying "label list" from a raw view. Perhaps this is due to value "id" of each label.
Please make it possible to copy the “list of tags” from one task to another, this is necessary to create tasks with a similar or identical “list of labels”

**Comment by zanilzanzan** [comment]
The issue continues when copying raw labels with attributes. Tried to alter the attribute IDs and it worked. Could you please take a look at it as well?

**Comment by nmanovic** [comment]
@bsekachev , could you please check?

**Comment by bsekachev** [comment]
@TOsmanov 
@zanilzanzan 

Do not copy labels with Ctrl+C from the raw view. 
There is a button for that purpose. It copies labels & attributes without their IDs. 
![Screenshot from 2020-01-17 11-11-00](https://user-images.githubusercontent.com/40690378/72595399-d2fdc200-391a-11ea-971e-16248d66aca3.png)

**Comment by nmanovic** [comment]
@bsekachev , let us keep the issue open. I believe we can implement "smart" paste option to ignore ids if it is necessary. It will be a good solution for users.

**Comment by gitunit** [comment]
> @TOsmanov
> @zanilzanzan
> 
> Do not copy labels with Ctrl+C from the raw view.
> There is a button for that purpose. It copies labels & attributes without their IDs.
> ![Screenshot from 2020-01-17 11-11-00](https://user-images.githubusercontent.com/40690378/72595399-d2fdc200-391a-11ea-971e-16248d66aca3.png)

someone copied with IDs and now whenever i want to create a task with same attributes i get ` duplicate key value violates unique constraint "engine_attributespec_pkey" DETAIL:  Key (id)=(1516) already exists.`
is there a way to fix this? @nmanovic @bsekachev

**Comment by nmanovic** [comment]
Let's treat the issue as a bug. In general CTRL+V  should not insert IDs.
