### ISSUE TITLE
Support uploading big files using a browser

### ISSUE THREAD

**Issue by korabelnikov** [openvinotoolkit/cvat#956]
I'm trying to upload video of size 2GB and webpage show me error just after few second 

Could not create the task
Error: Network Error.

and I've checked it works with videos of size 100mb

**Comment by bsekachev** [comment]
@korabelnikov 
Hi, what error can you see in the Browser Console?

Try to use [share](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path) functionality.
Similar issue: #799

**Comment by korabelnikov** [comment]
```
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
create:1 
Access to XMLHttpRequest at 'http://localhost:8080/api/v1/tasks/8/data' from origin 'http://localhost:7080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cvat-app.tsx:145 Error: Network Error.
```

I suppose it's not an enhancement but real bug

**Comment by nmanovic** [comment]
@korabelnikov , in the particular case your problem isn't connected with the size of data. The request is blocked by CORS policy. There are settings in CVAT which you need to adjust.

```
# Cross-Origin Resource Sharing settings for CVAT UI
UI_SCHEME = os.environ.get('UI_SCHEME', 'http')
UI_HOST = os.environ.get('UI_HOST', 'localhost')
UI_PORT = os.environ.get('UI_PORT', '3000')
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [UI_HOST]
UI_URL = '{}://{}'.format(UI_SCHEME, UI_HOST)
if len(UI_URL):
    UI_URL += ':{}'.format(UI_PORT)

CORS_ORIGIN_WHITELIST = [UI_URL]
CORS_REPLACE_HTTPS_REFERER = True
```

**Comment by korabelnikov** [comment]
Thank you! Maybe it worse to add this adjustment as default?

**Comment by bsekachev** [comment]
@korabelnikov 
Actually, default settings from current develop branch are expected to work. 
It wasn't stable for some short time, but now it must be.

**Comment by korabelnikov** [comment]
@bsekachev I've checkout this repo just a few days ago

**Comment by bsekachev** [comment]
@korabelnikov 

Anyway. Try rebuld and clean the browser cache just in case. 
CORS messages aren't expected to appear in default settings. 

What about code 413 (Request Entity Too Large), CVAT never supports large files uploading via a browser. We use "shared" functionality to do it. But I agree it make sense to implement better approach of uploading.

**Comment by korabelnikov** [comment]
I get, just simple message that shows "CVAT doesn't support large file uploading, use shared folder functionality instead" will be helpfull

**Comment by bsekachev** [comment]
@korabelnikov 
Great idea!

**Comment by yrz2015** [comment]
@bsekachev 
But I don't know how to use shared folder function. Is there any guide for doing this?

**Comment by nmanovic** [comment]
https://github.com/openvinotoolkit/cvat/pull/3692
