### ISSUE TITLE
Timeout when uploading a big file with annotations

### ISSUE THREAD

**Issue by alontrais** [openvinotoolkit/cvat#964]
When I try upload 100 MB xml file annotation, I get this error on log and "Failed to load resource: the server responded with a status of 504 (Gateway Timeout)" error on console.

How can I increase the timeout of the upload annotation?

**Comment by nmanovic** [comment]
Probably it will be necessary to do the following changes:
- Optimize upload
- Change REST API because the operation can be heavy

**Comment by alontrais** [comment]
Thanks for the replay!
Meanwhile I wander if there is possibility this parameter  "Timeout 60" or "request-timeout=60" in the httpd.conf file.
I was trying to change this file manually, but the change didn't effect. Those parameters are constants and I didn't find which process creates this file.
Do you know which process creates this httpd.conf file, or how to change those parameters?

**Comment by gitunit** [comment]
is it possible to upload the annotation (250 MB) to the server and run some CLI instead?

**Comment by alontrais** [comment]
@gitunit 
Yes, it is possible.

**Comment by gitunit** [comment]
@alontrais good to know. how would you do it?

**Comment by zhiltsov-max** [comment]
Related #673

**Comment by nmanovic** [comment]
@klakhov , it is something which you need to fix in your next PR.

https://github.com/openvinotoolkit/cvat/pull/3692
