### ISSUE TITLE
In User Guide not work shortened links to GitHub 

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#990]
The user guide that opens when you click the help button does not work shortened links to GitHub. 
I also noticed that ordinal lists are not displayed as on a github. Lists a, b, c... are displayed as 1,2,3...

Maybe it’s worth making the render as close as possible to the [user guide on github](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md)?

**Comment by nmanovic** [comment]
https://openvinotoolkit.github.io/cvat/docs/
